### ISSUE TITLE
Gamepad "Button is down" inside an "OR" block

### ISSUE THREAD

**Issue by ghost** [Scirra/Construct-3-bugs#1006]
## Problem description

Whenever a "Button is down" condition is inside an "OR" block, it stops working

 ## Attach a .c3p

[ButtonIsDownBug.zip](https://github.com/Scirra/Construct-3-bugs/files/1465190/ButtonIsDownBug.zip)

## Steps to reproduce

1. Have a Gamepad "Button is Down" condition inside an "OR" block
2. This block should contain another condition (above or below)
3. The event will not trigger for the Gamepad, but will work for the other condition

## Observed result

Someone paying to be a beta tester of a software that does behind the scenes refactoring

## Expected result

Software working since someone is already paying to work in such conditions

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

**Comment by flipog** [comment]
Oh... I guess this isn't a beta now because you say so. Congratulations, I'm not renovating my license ever, nor recommending the software. You have a childish approach to business. I sincerely hope you can improve that about the company someday and, as Borat, I wish you great success.

**Comment by AshleyScirra** [comment]
FYI Construct 3 uses the same runtime as Construct 2, which has been out for 6 years.

**Comment by XpMonster** [comment]
My "button is down" is a good one I think ;D

**Comment by XpMonster** [comment]
Some problem with a logic, but can't see how this can be critical. 
On the very start of the app it can actually work, but only few times max. 

And you already have working method so why bother?

OR is working well with OR keyboard/mouse buttons as I used for my experiments. 

You just unlucky here. Everyone deal with such sort of problems in any software.

**Comment by AshleyScirra** [comment]
Believe it or not, this actually isn't a bug. It's a counter-intuitive result of the way OR blocks handle picking.

OR blocks have special rules for picking to get what is usually the expected result. Consider an OR block with:

+ Sprite X > 100
+ OR Sprite Y > 100

An AND block will filter down instances to those which are *both* greater than 100 on both the X and Y axes. An OR block must filter down instances to those which are *either* greater than 100 on the X axis *or* greater than 100 on the Y axis. In other words it has to pick instances which match *any* of the conditions.

If you then add a false condition to the top, e.g.:

+ Spacebar is down
+ OR Sprite X > 100
+ OR Sprite Y > 100

It doesn't matter if spacebar is not pressed: the event can still run if any of the *other* conditions are true. So even though the first condition is false it goes ahead and checks the other conditions, picks which sprites are greater than 100 on either axis, and runs actions on them. This is a key difference between AND blocks and OR blocks: an AND block stops running the event at the first condition, but OR blocks *always run all the conditions*, then run the actions with whichever instances are left picked.

This has something of an unintuitive result in that actions can end up running with *no instances picked*.  For example if you have this event:

+ Spacebar is down
+ OR Sprite X > 100
+ Action: move Sprite right
+ Action: play sound

If there are no sprites with X > 100, and you hold spacebar, the event runs anyway, because it's an OR block and one of the conditions was true. It still runs the "Sprite X > 100" condition, and finds no sprites matching it, so none are picked. Since actions run only on picked instances, the "move Sprite right" action does nothing! However it still plays a sound because that doesn't depend on which sprites are picked. This sometimes ends up with incorrect bug reports claiming "I hear a sound so the event is running but none of the sprites moved right, so it looks broken". In fact it is working correctly: it would be incorrect if any of the sprites moved, because that would mean running an action on an instance that did *not* meet the event's conditions.

So if you take your example:

+ Gamepad A is down
+ OR Sprite is overlapping Box
+ Action: change Box animation frame

If you hold down A on the gamepad, the rest of the OR block conditions still run. So it still runs "Sprite is overlapping Box". If the sprite is *not* overlapping the box, then no Box instances are picked. The event runs anyway since the gamepad button was down; but the 'Set animation frame' action does nothing, because no Box instances met the event. Basically, the event is the same as only having the overlap condition, because the gamepad condition has no effect on whether the action is run or not.

So: it's actually working as designed. Simply rearranging the events to not use the OR block, as you've demonstrated, is the way to get the logic you want.
