### ISSUE TITLE
json editor size value deletes all input field and doesn't prompt save option

### ISSUE THREAD

**Issue by damjancd** [Scirra/Construct-3-bugs#1033]
## Problem description

*Changing the size of the possible json inputs in the editor deletes all fields when for example you try to write 100 input fields and you had 5 before, since it updates immediately, it registers the 1 instantly and deletes all, and then 0 0 and adds 100 entry fields. All your json data so far has been deleted by this.

Additionally changes in json files don't prompt the option to autosave, it reads it as if nothing was changed in the project, so when you close the project, it won't prompt you to save your changes*

## Attach a .c3p

**

## Steps to reproduce

1.Import a json file
2.add values
3. change the number to 100
4. values gone
5. no option to save project even though changes to project were made

## Observed result

*all json entries be deleted and C3 not recognizing that changes have been made to the project*

## Expected result

*all json entries not be deleted and C3 recognizes that changes have been made to the project*

## Affected browsers

* Chrome: yes

## System details

*OSX laptop, High Sierra 10.13.1*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Hmm the behaviour on resize is a bit of a pain, also it should be remembering the contents of the cell when your undoing so that's obviously broken. I'm seeing any change in the size or content marking the project as changed, although the cell has to lose focus before the change is registered. Does this not match what your seeing?

**Comment by damjancd** [comment]
@shortercode OK the changes works perfectly, my bad. The only problem is the resize deleting everything unless I copypaste 100 on the side :)

**Comment by shortercode** [comment]
I remember rewriting the hasChanged logic for the data editor a few months back, in theory it should be better than the project level one :P

**Comment by shortercode** [comment]
Okay so the good news is Undo is working correctly 👍 Not sure why I thought it was broken before, just getting confused I guess. So I just need to fix the toolbar update logic.

**Comment by damjancd** [comment]
Thank you Iain! I won't be of existential dread each time I enter the world of json now ! :)

**Comment by shortercode** [comment]
I found the source of my madness, if you undo while the size controls are focused it tries to use the browsers own undo system... Which was behaving like using the controls to change the size instead of actually undoing, so you lose the old contents of the cells ( because they are new cells! ).

To get around the overly speedy updates I switched it to use the "change" event over "input", the exact behaviour is a little difficult to describe but it seems to be work pretty much perfectly now. It also mostly mitigated the above issue. I'm tempted to replace the 3 spinners with a "resize" button that launches a small dialog, but I'm going to leave this for the future I think.
