### ISSUE TITLE
AJAX Stopped working

### ISSUE THREAD

**Issue by Allardje** [Scirra/Construct-3-bugs#1065]
## Problem description

AJAX requests simply stopped working. No results will be given. Tested on multiple domains with multiple different links.

## Attach a .c3p

http://project-mine.com/AJAX_BUG.c3p

## Steps to reproduce

1. Click button
2. Wait for AJAX request
3. See AJAX request isn't working

## Observed result

Nothing. 

## Expected result

Return the string via AJAX as requested by C3.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

x
<details><summary>View details</summary>

x

</details>

**Comment by AshleyScirra** [comment]
Use 'On button clicked' rather than the Mouse plugin's 'On object clicked'. The Mouse plugin only checks for canvas input (e.g. on sprites) and does not fire for button controls, which have their own click triggers. This is the reason the AJAX action is not run.

When you do run it, it logs an error because it's mixed content:

> Mixed Content: The page at 'https://preview.construct.net/local/index.html' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://project-mine.com/test.php'. This request has been blocked; the content must be served over HTTPS.

You should run all web content on HTTPS these days, to avoid such problems.

**Comment by Allardje** [comment]
Hi Ashley,

Even though that example might have a little issue in my original project i get no HTTPS error at all.
