### ISSUE TITLE
Referring to effect's names is case sensitive, therefore Dark Theme needs to not use all caps

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#1170]
## Problem description

When you're trying to use an action that changes a parameter for an effect, it feels like the code is broken because when you try to reference the effect it does not work, you look at the object's name and it says "TINT" so you type "TINT" or "tint" in expression editor but the code does not work, and you don't know where you went wrong.

This is because Dark Theme displays sensitive string data (effect names) in all caps.

I'd suggest either make it so that when you refer to the name of an effect it is not case sensitive, or to change the theme.

## Attach a .c3p

[effect.zip](https://github.com/Scirra/Construct-3-bugs/files/1621370/effect.zip)

## Steps to reproduce

1. Use Dark Theme
2. Click on a sprite with an effect

## Observed result

The effect name says "TINT"

![image](https://user-images.githubusercontent.com/5744908/34810065-5223af94-f6ed-11e7-862c-44e9e8a29228.png)

## Expected result

"Tint", so that I know how to refer to the effect in the code.

I'd suggest either make it so that when you refer to the name of an effect it is not case sensitive, or to change the theme.

## Affected browsers

* Chrome: yes

**Comment by shortercode** [comment]
I think this is pretty closely related to #1171, basically the sub groups in the properties bar need some adjustment. Incidentally you can view the case correct name in the effects dialog, just in case you missed that :)

**Comment by Animmaniac** [comment]
@AshleyScirra 

Issues #1171 #1170  #537 are all related. I kind of hacked the current dark theme style over the original table layout so there's some limitations that currently prevent me from fixing those. The HTML structure was made with a table in mind and there's no way to target certain elements through CSS.

Here's an example of the current implementation for effects. On the left side I color-coded what each line is and on the left it shows how it's implemented:
![properties-hierarchy-a02](https://user-images.githubusercontent.com/29487913/42297470-004fa2fa-7fd6-11e8-920b-ec90ff50708d.png)

As you can see there's no way to differentiate the category group "Effects" from the effect "Tint" since they use the same element tag and class. Also there's no way to differentiate the effect "Exclusion" from Tint's properties and the add/edit button. This same kind of situation happens for behaviors and other category titles.

In order to fix these issues some additional classes and/or attributes are needed to reflect more what the elements are/mean (semantic) rather than what they look (syntactic).

The hierarchy of the properties panel in a more semantic context would be something like this:
`propertiesPanel
	...	
	categoryGroup behaviors
		behavior
			behaviorProperty
			...
		behavior [noProperties]
		...
		addEditButton

	categoryGroup effects
		effect
			effectProperty
		effect [noProperties]
		...
		addEditButton
	...`

By turning these into classes/attributes applied to `<ui-proprow>` elements I could easily fix these issues.

Is this something feasible on your end?

**Comment by alastajj** [comment]
@AshleyScirra

**Comment by AshleyScirra** [comment]
The current design of the Properties Bar makes it difficult to change the DOM structure. Right now the best solution is to work with the existing structure of the elements.

**Comment by Animmaniac** [comment]
The DOM structure can remain the same, what's needed is just some classes/attributes to be able to target specific types of elements. Isn't that something feasible?

**Comment by AshleyScirra** [comment]
Sorry, misread that. I've added some more classes to help distinguish the different kinds of properties for instance variables, behaviors and effects, including the section headers, group headers, entries with no properties, the add/edit link, and the special "blend mode" effect property. @Animmaniac - take a look once the next release is out and let me know if anything else needs changing.

**Comment by AshleyScirra** [comment]
These changes are now in r135.3.

**Comment by Animmaniac** [comment]
@AshleyScirra 
Thanks, that helps a lot.

The only things that are missing are classes for the other **sections** like 'Object type Properties', 'Common', 'Container' and 'Properties' (I believe other plugins may have custom sections also).

Maybe instead of having a single 'behaviorsSection' class it could be more useful to split into a 'section' and a 'behavior' class. Then I could style all '.section' the same, and if there's need to differentiate only one I can use a '.behavior.section' selector. The same could be applied to other classes like 'behaviorWithNoProperties' that could become 'behavior' and 'noProperties' since the same case applies to effects (so would be 'class="effect noProperties").

I'm currently trying to set a darker border above the sections and a lighter border above the propertyGroups (behaviors, effects...), as well as doing some experiments with positioning to make the hierarchy more clear, but the other sections are missing classes so I'm not able to style them.

**Comment by AshleyScirra** [comment]
I could refactor all the CSS classes but we're at an awkward time in the release cycle - we want to get a stable release out soon and I don't want to make any changes that will break the existing dark theme. AFAIK the changes made so far have all been backwards-compatible, but the other changes you described would not be, so we would probably have to do a beta release that knowingly breaks the dark/light themes, and then update it before the next stable release after that. So we'll wait until the next stable release comes out then I'll revisit this.

**Comment by Animmaniac** [comment]
The current versions of the dark and light theme don't use any of those classes. So feel free to change them if you like, there will be no breaking.

If you can at least add the remaining 'section' classes I can probably fix most of these theme issues for the next stable.

**Comment by AshleyScirra** [comment]
I'll postpone it anyway - this release cycle is proving a bit tricky and it'd be really bad to find that something was broken only in the stable release.

**Comment by AshleyScirra** [comment]
OK, I've refactored the classes for the next beta release. The dark/light themes will likely need updating since the new class names are different now, but hopefully this covers all the required flexibility.

**Comment by AshleyScirra** [comment]
r137 is out, @Animmaniac does this cover everything?

**Comment by Animmaniac** [comment]
@AshleyScirra 
The only thing that is missing are "section" classes for the other sections like
"Object Type Properties", "Common", "Container", "Properties"... and so on. It's currently only being applied to "Instance Variables", "Behaviors" and "Effects". Basically everything with a class "propertyGroup" should have a "section" class, with the exception of all ".propertyGroup" that are "children" of a ".section" (like variables, behaviors and effects).

Like this:
*the desired classes are between parenthesis
**the ones in bold are currently missing
`
Object Type Properties (**section**)
Common (**section**)
Instance Variables (section)
	Variable01 (propertyGroup)
Behaviors (section)
	Platform (propertyGroup)
Effects (section)
	Brightness (propertyGroup)
Container (**section**)
Properties (**section**)
`

The sections can have additional "propertyGroup" classes or not, I can filter them regardless. But the "section" classes are essential, as well as children of sections not having "section" classes.

If there's any doubt let me know.

**Comment by AshleyScirra** [comment]
OK, so the difference between "section" and "propertyGroup" is that only top-level property groups have "section"? I've updated the next build to give all the top-level groups a "topSection" class (renamed to make it clearer) in instance properties. Should this be applied to other property views as well (e.g. layout properties)?

**Comment by AshleyScirra** [comment]
OK, I've gone through and updated all kinds of properties for the next release. Hopefully that covers it!

**Comment by AshleyScirra** [comment]
OK, changes are now in r140. @Animmaniac - does it cover everything now?

**Comment by Animmaniac** [comment]
Yes, everything is working well. Thanks!

Should be fixed for the next theme release.
