### ISSUE TITLE
Неправельно работает предаврительный просмотр

### ISSUE THREAD

**Issue by kop9000** [Scirra/Construct-3-bugs#1208]
[GE-NE-RA-TOR.zip](https://github.com/Scirra/Construct-3-bugs/files/1640887/GE-NE-RA-TOR.zip)

1) работаю над проектом
2) открываю макет map
3) открывают события car
4) немного работаю
5) делаю предварительный просмотр этого макета. всё ок
6) сохраняю проект
7) позже открываю проект. он открывает тоже место где я был тоесть в событии car
8) но когда я запускаю предварительный просмотр он должен по идее показать макет map но вместо этого он показывает другой макет а именно mario_map2

[EDIT google translate]

1) I'm working on a project
2) open the map layout
3) open the events car
4) I work a little
5) I do a preview of this layout. all OK
6) I save the project
7) I open the project later. he also opens the place where I was in the event car
8) but when I run a preview it should in theory show the map layout but instead it shows a different layout namely mario_map2

**Comment by AshleyScirra** [comment]
I can't reproduce here: when I open the project again it still previews with the 'map' layout. Note however that the "Preview" button really means "Preview layout", and if you're looking at an event sheet, there is not always an associated layout, or it could be used by multiple layouts. In that case if you're only looking at an event sheet and there are no other layouts open, "Preview layout" falls back to previewing the first layout. I guess that's what's happening, but it's currently by design.

**Comment by kop9000** [comment]
https://youtu.be/eTg8gXpW3eE.

**Comment by kop9000** [comment]
it would be better if it could be done so that when saved, it was saved in the same place where I was earlier in the last layout so that when I open and open the preview again, I could not choose layout
