### ISSUE TITLE
brackets in the above plugins

### ISSUE THREAD

**Issue by kop9000** [Scirra/Construct-3-bugs#1216]
when I translate a plugin and install it in Construct 3, then, together with the translated text, there are brackets

Here is the file in which I translated one text for verification

[en-US.zip](https://github.com/Scirra/Construct-3-bugs/files/1650945/en-US.zip)

here is the plugin with one translated text

[rex_text_typing.zip](https://github.com/Scirra/Construct-3-bugs/files/1650953/rex_text_typing.zip)

here is the version of the plug-in with the ru-RU.json file without the en-US.json file, which when you install and restart the Construct 3 program itself, the Construct 3 program stops running and sees an error

[rex_text_typing.zip](https://github.com/Scirra/Construct-3-bugs/files/1650967/rex_text_typing.zip)

**Comment by AshleyScirra** [comment]
You must always include en-US.json in the addon. The language system always loads English, even when you choose a different language file, since it uses it as a fallback in case strings are missing in the translation. If it loads a fallback English string, it puts it in square brackets to indicate it's not in the correct language. Besides, it's crazy to distribute a separate addon per language, you just want one .c3addon that works for everyone.

I did notice if both en-US.json and ru-RU.json are present, and you set C3's language to Russian, it won't load ru-RU.json from the addon. This should be fixed in r80.
