### ISSUE TITLE
Alt + Arrow Keys naviagtion shortcut for Desktop Version.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#1219]
## Problem description

The C2 shortcut ( Alt + Arrow Keys ) that lets you navigate in the pop up windows changed to Alt + Shift + Arrow Keys for C3 because browsers already use the Alt + Arrow Keys.

I often use this shortcut and it's not that ergonomic to press Alt + Shift + Arrow keys. If it's possible please add Alt + Arrow Key shortcut to Desktop Version.

**Comment by AshleyScirra** [comment]
The addition of the shift key is not because of browser navigation - it's because macOS users expect it to be a shortcut to move the text cursor forwards or backwards. It was originally reported in #982.

The same problem applies in the desktop build. We haven't released a macOS desktop build yet, but we will. I'd rather keep the keyboard shortcuts the same everywhere.
