### ISSUE TITLE
Can't export to NWjs after update .r80 [desktop version]

### ISSUE THREAD

**Issue by drezgames** [Scirra/Construct-3-bugs#1228]
## Problem description

After the .r80 update, no project will export to NWjs for me. 

## Steps to reproduce

1. Load a project
2. Try to export to NWjs
3. Will fail

**NOTE:** You can use the Glokar demo as test case, I was never able to get it to export even with the fix from last version.

**Comment by AshleyScirra** [comment]
Looks like this only happens if you enable mac or linux platforms. Windows seems to work OK.

**Comment by drezgames** [comment]
In all the times ive tried i only have win32 selected.

**Comment by AshleyScirra** [comment]
I can't reproduce any issue exporting win32 or win64 in the desktop build. Are you sure you're using the latest version of the desktop build? I updated the forum thread with a new download a while ago.

Anyways the fix for the mac/linux export issue is in for r81, and basically reverts back the desktop build to exporting a zip for NW.js exports like the browser does (this is important to set the right file permissions for mac/linux). So it should be working in r81 anyway.

**Comment by drezgames** [comment]
Ahh ok, didnt see the new version posted. Just updated and it now works. Thx.
