### ISSUE TITLE
WebGL renderer clears background even if set not to

### ISSUE THREAD

**Issue by Ludonaut** [Scirra/Construct-3-bugs#1241]
## Problem description

Unchecking 'Clear background' in the Advanced project settings seems to have no effect as long as WebGL is enabled.

I am seeking to replicate something similar to http://mrdoob.com/lab/javascript/effects/ie6/ without the use of third-party addons and without unnecessarily spawning tons of objects. I'd like to keep using the WebGL renderer for its obvious performance benefits.

Unfortunately I have no way of checking but I'm pretty sure this was possible using the WebGL renderer in Construct 2.

## Attach a .c3p

[Clear background issue.zip](https://github.com/Scirra/Construct-3-bugs/files/1664584/Clear.background.issue.zip)

## Steps to reproduce

1. Make sure layers are set to transparent
2. Disable 'Clear background' in the advanced project settings
3. Preview and move the cursor (see _Observed result_ below)
4. Uncheck the 'Enable WebGL' setting in the advance project settings
5. Preview and move the cursor (see _Expected result_ below)

## Observed result

![screenshot from 2018-01-25 16 40 28](https://user-images.githubusercontent.com/932664/35397345-86f8fa32-01ef-11e8-8ca8-dec2ed9f0e9c.png)

## Expected result

![screenshot from 2018-01-25 16 41 02](https://user-images.githubusercontent.com/932664/35397354-8c97ed22-01ef-11e8-9587-e521b12292d7.png)

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: untested
* Safari: untested

**Comment by AshleyScirra** [comment]
I think you've slightly misunderstood what 'Clear background' is for, which is understandable, because it's not a very good name for the option! A better name would be "The background is already completely covered by opaque objects, so don't clear the background before starting to draw a frame, because that would be redundant". That's all it's for; it looks like instead you want the "preserve drawing buffer" mode where the last frame's content is left behind, whereas WebGL (and the runtime) currently default to re-drawing all content every frame. However the WebGL spec warns that preserving the drawing buffer can have significant performance implications on some hardware.

I think what you really want is a canvas object that you can draw in to, rather than relying on a possibly performance-destroying behavior of leaving the backbuffer intact between frames. Unfortunately we don't have such an official plugin, so you will need to use a third-party plugin for this.

**Comment by Ludonaut** [comment]
I see! I'll try the Paster plugin then. Thank you for your time :)
