### ISSUE TITLE
The Dropbox open/save window is not showing all the existing .c3p files.

### ISSUE THREAD

**Issue by bible9230** [Scirra/Construct-3-bugs#1243]
## Problem description

While using 'cloud open' within C3, Dropbox is not showing all the existing .c3p files.  When viewed with Dropbox directly, all the saved files are visible.

I believe it is a matter of moving the file within Dropbox itself since it happened after I reorganized the Dropbox file locations.  I have restarted everything to try to get C3 to see the file within Dropbox, even trying to access with my mobile device, without success.  The only thing that makes the file visible to C3 is to put it back into its original location, but even then that doesn't always work.

Also the 'Up to parent folder' arrow can be greyed out not allowing you to access existing parent folders.

## Attach a .c3p

non-specific

## Steps to reproduce

1.  Use Dropbox and move .c3p file to a folder that you can already access from within C3.
2.  Try to access the file with C3's 'cloud open'.  It will not be visble
3.  Also, create a 'New Folder' in the C3 Dropbox window.
4.  The new folder will be visible until you click the refresh button, and then it will disappear.
5.  The files and folders are still visible directly within Dropbox.

## Observed result

All .c3p files are not visible.
You do not have access to your entire Dropbox folders due to the 'Up to parent folder' being greyed out.

## Expected result

I expect all of my Dropbox files to be visible and loadable.

## Affected browsers

* Chrome: yes
* Firefox: yes

## System details

r81.2

**Comment by bible9230** [comment]
Google drive is working correctly.

**Comment by shortercode** [comment]
I don't seem to be able to repeat this, it all appears to be working fine to me.

You cannot move any higher than the `/Applications/C3` folder, is that what you are referring to when you say "'Up to parent folder' being greyed out"? It's expected behaviour, we use the dropbox API in "application mode" which only gives C3 access to that folder.

Could you have moved the folder in which you were currently viewing? I would expect that to cause strange behaviour.

**Comment by bible9230** [comment]
> You cannot move any higher than the /Applications/C3 folder, is that what you are referring to when you say "'Up to parent folder' being greyed out"? It's expected behaviour, we use the dropbox API in "application mode" which only gives C3 access to that folder.
> 

Yes that is what I am referring to.  In Google Drive, I am not limited to where I can go.  I can go avove the C3 folder and the Apps folder.  In Google Drive, I can access a file no matter where it is.

> Could you have moved the folder in which you were currently viewing? I would expect that to cause strange behaviour.
> 

I believe that I did move it while organizing my folders.  But that being said, how do I correct it, or how do others prevent it from happening to them?

Here is an example of what happens when I add a folder to Dropbox through C3 right now.
https://www.dropbox.com/s/n6cm6tnfp0937ss/20180126_085402.jpg?dl=0

This is what happens when I refresh or close and reopen the window.  Test #5 folder disappears.
https://www.dropbox.com/s/7tu9sbvy256vc8i/20180126_085807.jpg?dl=0

This is how many folders and files are actually in Dropbox at that directory level.  I can only see 3 folders and no .c3p files.
https://www.dropbox.com/s/dgcvyn70s6t5zpv/20180126_085834.jpg?dl=0

Have you tried moving folders and files around (even the Apps and C3 folders) to duplicate the problem?

**Comment by shortercode** [comment]
We made the decision to use the application mode in Dropbox to give users better security ( C3 cannot access the other folders through any means ). As for Google Drive the only reason we went for global access is that it's application mode prevents the user from actually accessing the files outside of the application, so it's a hindrance to the user. As such I don't intend to change our dropbox settings to global access, I would prefer to change Google Drive to access less but it's too late now.

I've tried moving files and folders within `/apps/Construct 3` and it's subfolders through the dropbox website and then creating folders in C3 and had no issues. I've also reviewed our code and the only reason I can see for the files not appearing is if the dropbox api isn't sending those entries. You could verify this through Chrome's network debugger, but I don't think it will gain us much.

I definitely would not recommend moving the apps or `Construct 3` folder, they are created automatically by dropbox when you grant the app permission and are not expected to be changed by users. I have no idea what would happen, but I guess by moving them you've altered the underlying directory subtly and as a result C3 now only has partial access to the folder. 

Providing I'm correct about that I would recommend moving all of your C3 projects out of the `/apps/Construct 3` ( maybe making extra copies on your computer to be safe). Then delete the `Construct 3` folder and go into dropbox settings to disconnect C3 from your account. If you then reconnect Dropbox through editor.construct.net it should return it to it's correct state. Hopefully you will be able to just copy your projects back into the folder and they will be visible and editable in C3.

It's a pain but I can't see any action I can take to fix this situation, or even prevent it from happening again.

Incidentally the folder disappearing after the refresh is down to the caching system we use to speed up folder navigation. Instead of reloading the file list after adding a file or folder if it succeeds we just add the entry into the cache. So it doesn't reflect whether Dropbox would show you the folder or not. It's possible to disable this caching in the C3 settings if your interested.

**Comment by bible9230** [comment]
Thank you for your effort.  I'll try your suggestions on how to fix it.

Do you recommend not having sub-folders in Construct 3?  And wherever the file is initially saved through C3, don't move it?

**Comment by shortercode** [comment]
It's totally fine to have sub folders, and unless there's some obscure dropbox bug I'm unaware of it should be fine to move projects. I just wouldn't recommend moving the `/apps` or `/apps/construct 3` folder.

**Comment by bible9230** [comment]
I downloaded all my folders to my desktop and then deleted the Apps/construct 3 folders from Dropbox.  Upon accessing Dropbox through C3 again, it created fresh C3 folders.  I uploaded all the original files into the new folders.  I'm still having a little bit of trouble since only MOST of the files show up, which is more than before.  If it is subtly of Dropbox that I have fallen into, for the mean time I am going to use Google Drive exclusively.

**Comment by shortercode** [comment]
I've made an adjustment to the paging behaviour for Dropbox, which might improve things in r86.

**Comment by shortercode** [comment]
r86 is out now, does this show all of your files now?

**Comment by bible9230** [comment]
YES! This is great.  
I opened r85 and r86 side by side and r86 showed ALL of the available files.

Thank you very much!

**Comment by shortercode** [comment]
Awesome! Guess we did have an issue there as well, at least we got it sorted in the end. Thanks for your help tracking this down.
