### ISSUE TITLE
Facebook Login does not work on native mobile

### ISSUE THREAD

**Issue by hansonbrody** [Scirra/Construct-3-bugs#1298]
## Problem description

The Facebook object only works in HTML5 export and not in iOS or Android. I think this is a known issue so I'm not attaching a c3p, but it is definitely a bug as I would expect it to work but it doesn't.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Facebook have turned off the Facebook Games features and moved their gaming support to the Instant Games platform, which we support separately with the Instant Games plugin. Additionally I suspect this is due to the web API being blocked or otherwise unusable in a Cordova app, which was similar to what happened with Google Play, and we ended up having to reimplement the entire plugin with a custom-coded Cordova plugin. That's a lot of work, and given the movement towards Instant Games instead of Facebook integration, we don't currently plan to support this. If you still want to suggest it then you can post it to our feature suggestions platform here: https://construct3.ideas.aha.io/
