### ISSUE TITLE
dynamic mp4 not playing in desktop build 

### ISSUE THREAD

**Issue by rems32** [Scirra/Construct-3-bugs#1304]
## Problem description

export desktop has a problem with video in .mp4

## Attach a .c3p

[https://mab.to/bN21kNlyy](https://mab.to/bN21kNlyy)

## Steps to reproduce

1. launch (preview or desktop build)
2. type small.mp4 in the text field input
3. click on Load button

## Observed result

mp4 is playing in preview but not in desktop build
and if you try small.webm or small.ogv it works in desktop build

**Comment by AshleyScirra** [comment]
The desktop build is based on Chromium, which does not include support for proprietary formats like MP4 (which is a patent-encumbered format). We can't work around this for legal reasons, so you should add a fallback in another format (e.g. WebM). You need to have other formats to cover all platforms anyway, especially since the NW.js export is the same.
