### ISSUE TITLE
C3 - iOS export with MobileAdvert plugin error. Application does not load.

### ISSUE THREAD

**Issue by bark888** [Scirra/Construct-3-bugs#1316]
## Problem description

Export to iOS with MobileAdvert Plugin - error.
_Black screen_ on device after Splash screen.
Loading project does not starting.
Android = OK (via AndroidStudio)
iOS = FAIL.

**1.** I tried **xcode-export** (step by step with official tutorial) => black screen on device, but runs good in xcode's simulator.
**2.** I tried **cordova-export** (cordovaExportFromC3 -> IntelXDK -> phonegapBuild) => .ipa creating on phonegap site was OK, but on device - black screen.
**3.** I tried **cordova-export** (cordovaExportFromC3 -> phonegapBuild) => .ipa creating failed with "**swift version error**" in log file. When I delete string with plugin "construct-mobile-advert" => build and run = OK.

**Plugin versions with Error:**
construct-mobile-advert v=1.0.17 (export from C3 default)
construct-mobile-advert v=1.0.18 (manually edit in config.xml)

**Construct3 version:** R85
Minimal iOS version in C3-Export-Settings: 9+

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
[test.zip](https://github.com/Scirra/Construct-3-bugs/files/1749550/test.zip)

## Steps to reproduce

1. Export from C3 (xcode, cordova)
2. Use xcode with official Scirra's tutorial
3. Build and run on device connected (result=black screen)
4. Build and run on xcode's simulator (result=OK, normal launch)
5. Build and deliver .ipa via "ApplicationLoader" on Mac.
6. Run "Testflight"
7. Intall on device from Testflight (result=black screen)

## Observed result
1. SplashScreen
2. Pemanent _black screen_ after SplashScreen
3. Loading application does not starting.

## Expected result

Normal loading and running the app.

## Affected browsers

iOS = yes (FAIL)
Androind = no (OK)

## System details

Device: iPad with iOS v.9.3.5
MacBookPro with xcode 8.3.3

phonegapBuild use xcode 9.2 and cordova-cli-8.0.0 as they say.

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
What version of iOS does your simulator use?

**Comment by shortercode** [comment]
I'm sorry to say I can't reproduce this. I have heard people mention this a few times, but I'm still none the wiser as to why or how it's happening.

Do you know how to debug JavaScript on an iPad? There might be something useful in the log, as I expect this is a JS error of some kind.

**Comment by bark888** [comment]
@shortercode simulator: iPhone 8 (iOS 11.2)

**Comment by shortercode** [comment]
I can't find any good sites about it I'm afraid. But it's not too hard thankfully.

For starters you will need to enable the developer menu for Safari on your Mac. Go to `Preferences > Advanced` and ensure "Show Develop Menu in Menubar" is enabled.

Then on the iPad go to "Settings > Safari > Advanced" and enable "Web Inspector".

Now when the iPad is attached you should be see an item under the "Develop" menu which matches the name of the iPad, and a list of available JS contexts inside it. Clicking on one of these will open a debugger for it.

If you go to xcode and launch the app on the iPad, then go back to Safari, you should see a new entry under the list for the webview in the app.

One of the tabs in the debugger is "console"; this will give you any error messages that have been produced since the debugger was opened. On the top left side of the debugger is a refresh/reload button. You will need to use this to reload the webview to see if there was any errors in the project start up.

**Comment by bark888** [comment]
@shortercode I did these steps.
New entry under the list: 1. blank 2. Appname

**Comment by shortercode** [comment]
So if you select Appname it should open the debugger for the app

**Comment by bark888** [comment]
@shortercode logs errors:

1. SyntaxError: Strict mode does not allow function declarations in a lexically nested statement. c2runtime.js:23664

2. TypeError: window.cr_createRuntime is not a function. (In 'window.cr_createRuntime({
exportType: "cordova"
})', 'window.cr_createRuntime' is undefined) start.js:7

**Comment by shortercode** [comment]
Thanks @bark888 I've seen this error before with older versions of iOS Safari, although I can't remember the exact cause. I'll see if I can figure it out.

**Comment by shortercode** [comment]
Okay I've put a patch in for r88 which should fix this. A frustrating syntax limitation on older versions of iOS.

**Comment by bark888** [comment]
**Good job, much thanks!**
