### ISSUE TITLE
MP3 sounds don't work with NW.js export

### ISSUE THREAD

**Issue by russellrain** [Scirra/Construct-3-bugs#1343]
## Problem description

*Enter a concise description of your problem here*
MP3 music music works in preview in the Construct 3 editor, but when exporting to NW.js the sound doesn't work

## Attach a .c3p
https://drive.google.com/open?id=12jQjLbRT1bh_ZwBgvJl5GgT-prb_s8mV
*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. preview the project in C3 editor, you'll hear music playing
2. export the C3 project to NW.js 
3. Notice the sound doesn't work.

## Observed result

*What do you see happen?*
no music

## Expected result
hear music

*What did you expect to happen instead?*

## Affected browsers

* NW.js

</details>

**Comment by AshleyScirra** [comment]
According to this comment on a Chromium bug about enabling MP3: https://bugs.chromium.org/p/chromium/issues/detail?id=746579#c20

Chromium 64 technically supports MP3, but the MP3 feature detection returns "not supported", which means Construct will assume playback won't work. They fixed that in Chromium 65. It's actually due out this week so it should be fixed in the next update of NW.js shortly.
