### ISSUE TITLE
Est. Image Memory Very High in C3 (vs C2)

### ISSUE THREAD

**Issue by Ninjadoodle** [Scirra/Construct-3-bugs#135]
## Problem description

Est. image memory in C3 is much higher than the same project in C2

## Attach a .c3p

https://www.dropbox.com/s/750bb15310fut3u/ImageTest.capx?dl=0

## Steps to reproduce

1. Use the debug to read est. image memory and compare to C2
2. Image memory will be over 200 MB

## Observed result

The same project in C2 take around 70 MB

## Expected result

To get a similar est. image memory reading to C2 (around 70 MB)

## Affected browsers

* Chrome: YES
Can't test C3 on other browsers

## System details

PC (Win 10) and MAC (Yosemite)

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Short response: should be fixed in r24.

Long response: this is a worst-case scenario for spritesheet packing, since the images are all just over 1024x1024, and the maximum sheet size is 2048x2048. This means it can only fit one image per sheet, and C3 adds padding to a power-of-two size to avoid a bug where it displays with different quality on WebGL 1 systems. Unfortunately this does mean a lot of extra memory usage in this specific case. So in r24 I've added a size cap for applying that padding, so this project can use shrink-to-fit sheets instead of padded sheets, bringing the memory usage back down. (This assumes the graphics driver doesn't use power-of-two surfaces in memory :P)

In general, images just over a power-of-two size are the least efficient for spritesheet packing. Also this project is pretty inefficient in using lots of large animation frames that only have small differences; it's much more efficient to have a single large base image, and use separate sprites for the changing parts. You could probably bring the memory usage under 30mb with that approach. For more information see: https://www.scirra.com/blog/112/remember-not-to-waste-your-memory

**Comment by Ninjadoodle** [comment]
Hi Ashley

Thank you for the detailed explanation. The reason I'm using large images with small changes is because Construct doesn't allow us to build composite objects which can be animated / squashed and stretched as one. The only way I can attach parts is the pin behaviour and very laboriously animate through code. The other option is Spriter which is not yet available for C3.

It would be awesome to have some form of container feature which can be animated as one object, if I want to for example squash and stretch the cars with the parts included.

I'm going to try and reduce my textures to drop them under the thread hold :)

Thank you again for the explanation.
