### ISSUE TITLE
Pathfinding and booleans don't work

### ISSUE THREAD

**Issue by mammothinc** [Scirra/Construct-3-bugs#1356]
Hi there, 

I am trying to blend pathfinding and grid based movement with a turn based mechanic. I ran into a road block. I am not sure if it is a bug or not. 

https://imgur.com/a/J87BY

This code doesn't work. I am not sure why when the boolean is toggled that the pathfinding doesn't stop / resume.

https://www.dropbox.com/s/inudwa7nvv2pc ... g.c3p?dl=0

It doesn't work on my computer but it works on others. I tried clearing my cache and restarting my computer.

**Comment by AshleyScirra** [comment]
The link isn't working, can you provide a working one?

**Comment by mammothinc** [comment]
https://tinyurl.com/y7vgnkd9

**Comment by AshleyScirra** [comment]
Please always remember to follow the bug report guidelines. It's not clear what you expect this project to do or what you think the problem is. As far as I can tell it is working correctly. If I make a wild guess, I would say you want it to resume moving along the path when you touch and toggle isTurn back to true, but it won't do that because you already stopped the movement. You only ever use 'Find path' on start of layout, so 'On path found' will only ever trigger once after the start of the layout, and that's the only event that starts the object moving. So the events never attempt to start the object moving more than once, but you seem to think it ought to. That's not a bug, just a mistake in the events.
