### ISSUE TITLE
no object icons from the insert panel

### ISSUE THREAD

**Issue by LiamDawe** [Scirra/Construct-3-bugs#1404]
## Problem description

On Ubuntu + Chrome, when inserting a new object, all their icons are gone.

## Attach a .c3p

No need, you can test with an empty project on Linux.

## Steps to reproduce

1. Load Linux
2. Open C3 in Chrome
3. Insert object, see no icons only text

## Observed result

No icons

## Expected result

Icons

## Affected browsers

* Chrome: yes
* Firefox: no

**Comment by AshleyScirra** [comment]
I just checked Chrome 65 on Ubuntu and it worked fine for me. I'd guess this is a graphics driver issue.

**Comment by LiamDawe** [comment]
What GPU and driver version did you test with?

I'm using NVIDIA with 390.25
![screenshot_20180319_190325](https://user-images.githubusercontent.com/83223/37616548-385f1d10-2ba8-11e8-88dd-76d0a2d4610e.png)

**Comment by AshleyScirra** [comment]
According to chrome://gpu on the device I'm using NVidia drivers 384.111. So - a little older actually :P

Maybe it's a driver bug introduced in the newer version, or hardware-specific - the device I'm testing on has a GeForce GTX 660. Anyway, since it looks OK here, this must be some kind of hardware/driver/browser/OS issue, so closing as not a Construct bug.
