### ISSUE TITLE
[Chrome] Unable to write to storage

### ISSUE THREAD

**Issue by masscube** [Scirra/Construct-3-bugs#1409]
## Problem description

I can't open construct 3 anymore. I have clear my cache, change the chrome profile, but nothing works.

## Steps to reproduce

1. Open Construct 3 in Chrome : https://editor.construct.net/
2. Get always this Error Message: https://drive.google.com/file/d/1zaaf2gHKZeUBs7acrK-Gc5eZdRawsx_Q/view?usp=sharing
3. I can't add any plugins..

## Affected browsers

* Chrome: yes
* Firefox: no
* Edge: no
* Safari: no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 65.0.3325.146
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36
C3 release: r89 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 110 kb
Storage usage (approx): 110 kb (100%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
How much space do you actually have on your hard drive? Chrome is allowing 110Kb of space for construct3 according to your platform information.

Chrome allows applications to use up to 20% each of it's local storage pool, and the storage pool is a third of ( used storage pool space + available disk space ). So thats around 7% of available disk space.

**Comment by masscube** [comment]
Okay, 7 gig free space is not enough?! 
I have delete something (32 gig free space)... and now it works.

**Comment by shortercode** [comment]
Disk space isn't really an absolute, if your a heavy computer user it can go up and down ALOT while your using the computer. It's not uncommon for windows to page the contents of memory to disk if your running low and some programs will create large amounts of temporary files while working. For example, I used to have a computer that would basically lock up while I was exporting photos in lightroom because it was creating over 10GB of temp files which weren't deleted until the system restarted, leaving less than a MB of free space. 

Another factor is that other websites could have been using most of your storage. At 7GB chrome would have about 2.3GB of storage to share between every website you visited; this includes the network cache, web applications, session cookies, offline cache. Each website would be allowed up to 230MB but visit enough websites and it builds up. I couldn't find a number for all of my local storage but my network cache is apparently 650MB.

It's frustrating, but local storage in the browser has issues which nobody has worked out and we have to work around them where we can. If chrome allows us 100kB then that's all we have to work with.
