### ISSUE TITLE
Construct 3 [FireFox] - Small Selection Boxes In Settings Menu

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#1443]
## Problem description

Construct 3 in FireFox seems to have sizing problems with selection boxes (select tag).
I can only reproduce this using the light or dark themes, default works fine.

## Observed result

![select tag c3 issue](https://user-images.githubusercontent.com/15656049/38032828-d37e7f14-329e-11e8-938e-2ac716f5e50e.PNG)

## Expected result

I would like to see those selection boxes in their full glory just like in Chrome.

## Affected browsers

* Chrome: no
* Firefox: yes
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Nothing.

</details>

**Comment by AshleyScirra** [comment]
Looks like it only happens with the Dark theme in Firefox.

**Comment by TheRealDannyyy** [comment]
@AshleyScirra Nope, can confirm it for both dark and light themes. Default works fine.
![select tag c3 issue](https://user-images.githubusercontent.com/15656049/38034101-cea3320c-32a1-11e8-9648-884418d2dd49.PNG)

**Comment by AshleyScirra** [comment]
I meant it doesn't occur in the default theme, but yeah, the light theme is just the dark theme with a different palette so it would make sense it reproduces there too.

**Comment by AshleyScirra** [comment]
@Animmaniac - looks like the `margin-right: 100%` style on `select` elements causes the element to become zero width in Firefox. It makes sense, you've forced the full available width to come up to the right edge of the element. Not sure why it works in Chrome.

**Comment by Animmaniac** [comment]
@AshleyScirra 
Since there's no way to differentiate the `label` wrappers to know if they represent a dropdown, checkbox or button and set the flex-direction depending on type, I added this "hack" to force the `select` element to wrap.

I fixed it by setting the flex-shrink to 0. Should be on the next theme release.

*As a side note, eventually I think it would be nice to do a proper design for the settings panel. A multi-column layout would probably work better, but it needs proper semantic markup to be implemented. CSS alone is not enough in the current state.
