### ISSUE TITLE
Html5 export not able to reproduce sound on iOS Safari

### ISSUE THREAD

**Issue by IJCT95** [Scirra/Construct-3-bugs#1445]
## Problem description
not able to reproduce audio on iOS.
*Enter a concise description of your problem here*
is not possible to reproduce audio files on any iOS device, neither using "remote preview" or exporting to html5, all audio files are .webm 
## Attach a .c3p
here is the project already running on a domain:

http://killasoft.com/demos/pong/

here are the audio files:
http://killasoft.com/demos/pong/media/
(i exported some .ogg files aside to see if that could fix it but i was wrong)

## Affected browsers

* Chrome: /no
* Firefox: /no
* Edge: /no
* Safari: yes/

**Comment by IJCT95** [comment]
it works on OSX safari but not on iOS

**Comment by IJCT95** [comment]
.c3p example:

https://drop.me/ad20D2

sound file is copyrighted.

**Comment by IJCT95** [comment]
found another issue:

if you import an .m4a file to c3 aside a .webm version, the project will never load on remote preview.

**Comment by AshleyScirra** [comment]
The server does not send a Content-Type header for .webm files so I assume that is the problem. Please review this manual entry: https://www.construct.net/make-games/manuals/construct-3/tips-and-guides/mime-types

I would also strongly recommend that you move to HTTPS hosting, since nowadays using insecure hosting can cause other problems.

Please do not report unrelated issues in bug reports. If you have any other issues, please file a new report for them following all the guidelines.

**Comment by IJCT95** [comment]
that means the servers that are used for remote preview doesnt have the MIME types correct?

**Comment by IJCT95** [comment]
already added webm in the mime types, doesnt work

killasoft.com/demos/ping 

try it.
