### ISSUE TITLE
[r94.2] Evaluate Pick somehow reset with OR condition with instance variable condition at second position

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#1464]
## Problem description

*Enter a concise description of your problem here*

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
[PickTest.zip](https://github.com/Scirra/Construct-3-bugs/files/1876385/PickTest.zip)

## Steps to reproduce

(see c3p/zip)
1. open c3p
2. go to events
3. see evaluate by Sprite.type="timer"
4. preview
5. see second sprite turns

i made several tests and disabled them so you can see which version works.
the reset only happens if the instance variable condition is at the second position and the condition is true - if you set the value of the second sprite to -1 and swap the instance checks it will also turn the second sprite

edit: if you pick again after the condition with the OR, it will work again

## Observed result

*What do you see happen?*
second sprite also rotates, even though in an event above a different object is picked

## Expected result

*What did you expect to happen instead?*
second sprite does not do anything, as i ruled it out in the evaluate

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I think this is related to #815, which appears similar: an instance is picked when it's not supposed to be, and the project unnecessarily uses a system pick condition when a normal condition would have sufficed (in this case "compare instance variable"). If you just use "compare instance variable" instead of "pick by evaluate" it does not cause the issue, so the bug only happens when you use this somewhat roundabout way of using an advanced system picking condition to do what a basic built-in condition does.

Still the next issue fixes #815 and looks like it also fixes this.
