### ISSUE TITLE
Google cloud timeout for long saving time

### ISSUE THREAD

**Issue by darthbinks911** [Scirra/Construct-3-bugs#1465]
## Problem description

When you are saving a project to Google Cloud, and the saving takes over 10 minutes (maybe the game is big, or the WiFi connection is slow), then Google Cloud's authentication times out, and the saving progress will be stuck e.g 83.6%. I think there may be a configuration set by either Google or Scirra that requests the user to re-authenticate after 5-10 minutes. If this problem is indeed a Google Auth timeout, then there should be a prompt asking the user to re-authenticate after a save takes too long, or the re-authentication time could be set longer, otherwise the save will hang forever.

This can be sorted right now by selecting Menu -> Project -> Save As -> Cloud Save -> and creating a new folder in your Google Drive. The save then continues without any prompts.

## Attach a .c3p

Not a project specific bug

## Steps to reproduce

1. Reduce WiFi connection or have a very large project open
2. Make sure the project already exists on your Google Drive
3. Save, and look at the save progress at the bottom left corner after 5-10 minutes, it should be stuck.

## Observed result

The progress is forever frozen until manual intervention and the project never saves.

## Expected result

The project should save, or there should be some additional prompt to stop the Google Auth timeout.

## Affected browsers

* Chrome: yes
* Firefox: unsure
* Edge: unsure
* Safari: unsure

**Comment by shortercode** [comment]
Google Drive authentication timeout should be 1 hour, but it could be they have a hard limit on the upload time. How big is a typical project that suffers from this? I believe they have an upload size limit, so I'm wondering if it could also be that.

**Comment by darthbinks911** [comment]
The upload size of my project was 38 MB, I will try to create a scenario to replicate the problem

**Comment by shortercode** [comment]
I'm slowing uploading a 24MB project at 50kb/s at the moment, it's made it to 43% so far. I'll let you know how it goes.

**Comment by shortercode** [comment]
It took over an hour, but the upload completed without stalling. Which is interesting as the authentication expired during the upload, but there was still no problem by the looks of it. I had a quick look and Google seem to suggest the size limit is about 5TB so somehow I don't think that's the problem.

If the percentage for the upload is still in place it would mean the network connection is still open and hasn't failed/timed out. My best guesses are:
1. Google Drive bug
2. Something is locking up on your local network
3. Something between you and google is aggressively throttling connections that have been open a long time.

I can't see much we can really do at this point, as it sounds like it sits outside of our control. We have previously talked about implementing folder based cloud saving which **could** work around your issue, as it would use lots of small requests instead of one big one. However, on a high latency connection the additional requests could make it much slower. Also as I don't know exactly what the issue is, so that wouldn't guarantee a fix.

If you can come up with something I can repeat then I might be able to figure out the reason...

**Comment by darthbinks911** [comment]
No problem, thanks for investigating, I'll try get more data for next time if it happens again.
