### ISSUE TITLE
DARK THEME : the animation preview is the negative of the background brightness (r94.2)

### ISSUE THREAD

**Issue by Picoti** [Scirra/Construct-3-bugs#1476]
# Problem description

DARK THEME : When I make a preview of an Animation in Animations editor, the background is the negative of the brightness defined

## Steps to reproduce

1. Make a preview of a sprite animation

## Observed result

Negative background

## Expected result

Same defined background

## Affected browsers

* Chrome: yes

**Comment by Animmaniac** [comment]
@AshleyScirra 
Can the animation preview background be changed to use a CSS background instead of being baked/rendered in the canvas? Like rendering the canvas background as transparent and wrapping it on a div with a CSS bg like it's done for the sprite editor?

For the dark theme I swapped the colors for the sprite editor as a way to set the default background color to dark, making it less jarring to the eyes. However the preview bakes it in assuming it's like the default.

I can revert this change, however the background will always be a dissonant white by default, which I believe is a less than ideal solution.

**Comment by AshleyScirra** [comment]
Not sure why the animation preview doesn't use the same CSS background approach as the editor. Assigning to Diego to look in to switching animation preview to CSS background as well so themes can alter it correctly.

**Comment by DiegoScirra** [comment]
Not too sure myself why I did it like that in the first place, must have been a good idea at the time.

It's converted now, the new CSS rules can be found at  **src/dialogs/animationsEditor/subdialogs/previewAnimation/dialog.css**

**Comment by AshleyScirra** [comment]
@DiegoScirra - it's better to mention the relevant CSS selectors since the theme is based on a precompiled CSS file which has all the individual source files merged together.

**Comment by DiegoScirra** [comment]
There are 2 new selectors

#previewAnimationDialog canvas (Regular checkered background)

#previewAnimationDialog[dark-background] canvas (Dark checkered background)

**Comment by Animmaniac** [comment]
Thanks Diego.

It's fixed for the next theme release.
