### ISSUE TITLE
'Run' command not working with NWJS on MacOS

### ISSUE THREAD

**Issue by ACC-Math** [Scirra/Construct-3-bugs#1489]
## Problem description
After importing a pdf file in my Construct 3 project, I've tried to use the "run file" action of the NW.js Plugin to open the pdf file with the system's default pdf viewer. This worked as intended on Windows but fails on MacOS (exported project).

## Attach a .c3p

[testpdf.zip](https://github.com/Scirra/Construct-3-bugs/files/1920512/testpdf.zip)

## Steps to reproduce

1. Open the project and export it with NW.js (MacOS only)
2. Download, unzip and run the app on a Mac
3. Click on the black rectangle to run the attached file

## Observed result

The "run file" action of the NW.js Plugin doesn't seem to work correctly on Mac.

## Expected result

The mentioned action should open the pdf file with the system's default pdf viewer as it does on Windows. 

## Affected browsers

* NW.js: yes 

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 65.0.3325.181
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_3
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
C3 release: r94.2 (stable)
Language setting: fr-FR

Local storage
Storage quota (approx): 14 gb
Storage usage (approx): 618 mb (4.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon R9 M370X OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by TheRealDannyyy** [comment]
@AshleyScirra I've also looked into this and the run command seems to fail to run the default pdf viewer of the system. This can either be caused by the plugin not executing with correct file arguments or NW.js in general not being able to run the default pdf viewer on MacOS because of reasons unknown (permissions?).

If the plugin code is not at fault, I would directly report to the NW.js team if requested.

**Comment by AshleyScirra** [comment]
The "run" command launches a process, i.e. it's intended to run an app. Also if you don't specify a path it just uses the current directory, which isn't guaranteed to be where the file is.

For the next release I've added a 'Shell open' action which is what you want to open a PDF file (it means "open with the default app" rather than "run as an app"), and a new ProjectFilesFolder which returns the path where you can find the PDF file. So if you use 'Shell open' with `NWjs.ProjectFilesFolder & "abc1.pdf"` it should work as you want.

Today's C2 beta already has these features and the next C3 release will have them too.

**Comment by TheRealDannyyy** [comment]
Great work, thanks for backporting it to C2 as well!

**Comment by ACC-Math** [comment]
Hi AshleyScirra. I'm very pleased with this solution and can't wait to test it in the r96 !
Thank you for the quick support !
