### ISSUE TITLE
Mobile right panel doesn't slide out

### ISSUE THREAD

**Issue by jook00** [Scirra/Construct-3-bugs#1549]
## Problem description

On any project (no specific c3p) on mobile, sliding finger from right side doesnt pull out right panel drawer. After multiple tries it eventually opens, but sometimes cannot. Stylus works fine to pull out drawer.

## Steps to reproduce

1. Start a new project on mobile
2. Swipe finger from right edge of screen

## Observed result

No right panel drawer slides put.

## Expected result

Swiping finger from right should pull out right panel drawer.

## Affected browsers

* Chrome: yes
* Firefox:
* Edge:
* Safari:

## System details

Samsung Note 8

**Comment by AshleyScirra** [comment]
It works fine for me on a HTC 10, and AFAIK we haven't had any other similar reports.

Does the device have a curved-edge screen? Maybe you need to move your finger in from the edge of the curve instead of flat? Does the device have any other built-in feature that relies on swiping in from the side that might conflict?

**Comment by AshleyScirra** [comment]
No response from reporter so closing
