### ISSUE TITLE
[R98]Issue with Scale rate of a layer and the usage of its parallax rate

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#1553]
## Problem description

Setting a scale rate of 0 to a layer did actually not "block" its scaling when its parallax value was over 0%.

## Attach a .c3p

https://kyatric.com/c3/bugs/20180503.BugParallax_Scale.c3p

## Steps to reproduce

1. Open the project
2. (modify a value)
3. Preview

You can "swipe" in the screen and it will make the layer with the blue drawing move accordingly on an horizontal axis.
When you use the mouse wheel up or mouse wheel down, you are having the layer with the blue drawing changing scale. That's intended.

Now if you go back in the project and modify the parallax value of the layer "Background" and set it to 25% instead of 0 as it is currently, I would be expecting the background to move during the swipe, but keep its size when changing the scale of the "Avion" layer with the mouse wheel.

## Observed result
The background layer does change scale as well despite having a scale rate of 0 and not being "picked" to change scale in the actions.
Note: You have to reduce the size of "Avion" layer a lot (5 or 6 mouse down) to start seeing the "Background" layer affected as well.

## Expected result
Like when the parallax was 0%, the size/scale to not change and to move independently from the layer on top of it.

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 66.0.3359.139
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
C3 release: r98 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 12 gb
Storage usage (approx): 151 mb (1.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I don't think it's actually a bug. If you look carefully at the background layer, it's not actually scaling - it's just being offset. The reason it gets offset is because bounded scrolling is enabled for a small layout and then you change the layer scales, which affects the scroll bounds. As you zoom out, the scroll bounds shrink closer to the middle of the layout, to try to prevent content outside the layout becoming visible. The scroll bounds are set by the "Avion" layer, since that is the layer that scales. These scroll bounds affect the whole layout, so the background layer gets offset by the changing scroll bounds. There's a special mode for parallax 0,0 layers though, to prevent things like HUD affecting the scroll bounds, which is one of the reasons it might seem inconsistent with when you change the parallax.

You can work around it by simply enabling "unbounded scrolling" - this turns off the scroll bounds and scaling and parallax can work normally, and it seems to produce the expected result that way.
