### ISSUE TITLE
Car behavior + disabled solid

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1562]
## Problem description

Having car  and solid behavior on sprite. Enabling car while solid is disabled = huge CPU usage.

## Attach a .c3p
[CarTestPerf.zip](https://github.com/Scirra/Construct-3-bugs/files/1988233/CarTestPerf.zip)

## Steps to reproduce

1.Add huge amount of sprites
2. add car + solid behavior
3. disable both
4. go debug mode and enable car behavior on all sprite
5. see huge CPU usage, which wont happen when there is just car behavior

## Observed result

When sprite has solid which is disabled, and car behavior which is enabled, CPU will go from 1% to 80%

## Expected result

Having car behavior on sprite which also has disabled solid behavior should not raise CPU usage from 1% to 80%. Instead it should happen when i enable solid and all the collisions check begin.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
It doesn't make any sense to add the Solid behavior with the Car behavior. It should have no effect on its movement. Only the things it collides with need to be solid.

Once you enable the Car behavior, it checks every tick whether it's hit a solid, as part of its normal handling of the behavior. Since you have around 800 instances, and each of them has to check if it's colliding with the other 799 instances, then this requires around 640,000 collision checks per tick, or around 38 million collision checks per second. This is what is consuming the CPU. Without any good explanation of why this is necessary for a realistic game, it just looks like a deliberately inefficiently made project, so closing.
