### ISSUE TITLE
Request whitelististing of unityads 2.2.1

### ISSUE THREAD

**Issue by artemisoftnian** [Scirra/Construct-3-bugs#1563]
Hi, I just update my unityads cordova plugin to version 2.2.1,  please if this version can be whitelisted will be wonderful.

Thanks in advance.

- Some code cleaning and optimization
- Updated UnityAds SDK to version 2.2.1

Cordova Plugin v2.2.1:
https://www.npmjs.com/package/com-artemisoftnian-plugins-unityads2

**Comment by shortercode** [comment]
Sure thanks for letting me know, I'll review it and let you know when I've
updated the whitelist.

On 10 May 2018 02:18, "Artemisoftnian" <notifications@github.com> wrote:

Hi, I just update my unityads cordova plugin to version 2.2.1, please if
this version can be whitelisted will be wonderful.

Thanks in advance.

   - Some code cleaning and optimization
   - Updated UnityAds SDK to version 2.2.1

Cordova Plugin v2.2.1:
https://www.npmjs.com/package/com-artemisoftnian-plugins-unityads2

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Scirra/Construct-3-bugs/issues/1563>, or mute the thread

**Comment by shortercode** [comment]
@artemisoftnian just reviewed your plugin and all looks good so I'm updating the whitelist.

I'm not sure your aware of it, but I don't think your plugin will work with Phone Gap Build. Not sure  if that troubles you or not. The "add swift support" plugin doesn't work on PGB because it doesn't support hooks and I haven't been able to get our first party swift based plugins to compile using their "swift version" preference.

If you do find a way to get swift plugins to compile on PGB 8.0.0 then please let me know how!

**Comment by artemisoftnian** [comment]
Thanks for the update!  I'm aware of that, I personally don't use Phone Gap build, but I know a lot of user does.  I'm also looking for a way to make it work.  If I figure it out I let You know, and if You make it first, please pass the knowledge! LOL!

thanks for everything!
