### ISSUE TITLE
GooglePlay Plugin issue: Sometimes "On auto-sign in failed" is not coming on HTML5.

### ISSUE THREAD

**Issue by jarvisjang** [Scirra/Construct-3-bugs#1572]
## Problem description

My game is only for HTML5 web.
In the first layout, I'm checking the GooglePlay login.
After all browser history is cleared, I tested. Sometimes, "On auto-sign in failed" is not coming.
So I should refresh my browser. After that, the event is coming.

## Attach a .c3p

I cannot attach .c3p. Because in the c3p file, my Secret Id and Passphrase is included.

## Steps to reproduce
[This is very easy to reproduce]

1.  Make a layout.
2. Add GooglePlay plugin. And make sure the setting Secret Id, Secret Key,...
3. Publish.
4. Clear all browser history. Open the game URL on the browser.
5. Repeat [clear history - open game URL - close browser]

## Observed result
Sometimes, "On auto-sign in failed" is not coming.

## Expected result
100% the event should be coming.

## Affected browsers
* Chrome: yes
* Safari: yes

## System details
Macbook Pro

**Comment by shortercode** [comment]
Clearing your browser cache completely is a bit of an edge case. Typically when a service does an auto sign in it uses information from the browser cache to attempt to restore the session. If the user has cleared that information then it wouldn't know it was originally signed in, so wouldn't attempt to restore the session.

So I'd say what your seeing is fully expected behaviour. Looking at the code I expect if you try looking at the **on signed in**, **on signed out** and **on error** callbacks one of them will fire instead of **on auto sign in failed**
