### ISSUE TITLE
Admob banner not displaying

### ISSUE THREAD

**Issue by cjpacewicz** [Scirra/Construct-3-bugs#1580]
## Problem description

Admob banner does not display. Test returns true for Mobile Advert is configured. 
[adMobTest.zip](https://github.com/Scirra/Construct-3-bugs/files/2002598/adMobTest.zip)

## Steps to reproduce

1. export to cordova, min Lollipop, not minified.
2. Build apk with phonegap
3.

## Observed result

App opens, test returns Mobile Advert is configured, no banner ad is displayed.

## Expected result

See banner ad displayed.

<details><summary>View details</summary>

The sample file is very simple. 
Mobile Advert - On configuration complete
- Set app ID
- Create banner advert using admobs test ID
- show current banner advert

MobileAdvert is configures
-  set text to "is configured = true"

</details>

**Comment by shortercode** [comment]
I think you might be misunderstanding the "on configuration complete" event, it's triggered when you have successfully set the application ID. So setting the application ID will never have an effect, either it won't be called or it will already be configured. 

As it turns out you've also specified the application ID in the Mobile Advert properties, so during start up the plugin configures itself. Unfortunately this means it has already configured before the event sheet has loaded, so the "on configuration complete" event won't fire.

If you call "create banner" within the "is configured" block it works correctly. 

Another note. Calling "show banner" immediately after "create banner" does not work, as the banner needs time to load. This is what the "show" argument is for in "create banner"; if it's set then it will show the banner when it has loaded.

I've modified the example with the changes I mentioned for you to take a look at.

Hope that's all clear for you!

[RevisedAdmobTest.zip](https://github.com/Scirra/Construct-3-bugs/files/2009453/RevisedAdmobTest.zip)
