### ISSUE TITLE
Touch events outside viewports are detected

### ISSUE THREAD

**Issue by dr460neye** [Scirra/Construct-3-bugs#1581]
Touch events are beeing recived if happens in letterbox ( outside the viewport).

Project in attachement contains an example project and a screenshot how to reproduce. Just click on the blue drawn location in the screenshot. Log Textfield shows the touch on object was registered

## Expected result

For my understading touch events only should work inside the viewport. So button 2 calls should not be seen as a valid event.

## Affected browsers

* Chrome: ?
* Firefox: yes
* Edge: ?
* Safari: ?

[TouchIssueExample.zip](https://github.com/Scirra/Construct-3-bugs/files/2004554/TouchIssueExample.zip)

**Comment by NetOneGames** [comment]
Just as I am here

It is very important that touch events are detected and maintained outside the game viewport in the black letterbox areas
it is also important that any touch events initiated inside the game window regardless of in letterbox area or not are maintained even outside the game window.
This is the way it currently works and is correct and good.
please dont change the way current touch events work in this respect  

If you are talking about being able to click html buttons outside view-port then thats different I suppose but the dev should really manage this themselves using anchor or whatever

**Comment by AshleyScirra** [comment]
I think it's reasonable that object touches (and clicks) should not be registered off the canvas (e.g. in the black bars area of letterbox scale). However I think it's important to still detect touches in these areas, particularly since they can be dragged off the canvas or back on to the canvas. So there's a kind of compromise: you can still detect touches off the canvas, but they won't trigger object conditions off the canvas. This is implemented for the next release.
