### ISSUE TITLE
 Google Play reports that the achievements are not working correctly

### ISSUE THREAD

**Issue by ERAgames777** [Scirra/Construct-3-bugs#1595]
## Problem description

My game on PlayMarket and google sent an error to the developers console that the achievements do not work correctly.

## Attach a .c3p

n/a

## Steps to reproduce

1.add plugin googleplay
2.add achievements

## Observed result

When using plugin googleplay with achievements, there is a problem when unlocking the achievement, it happens but the reach window does not pop up on the device screen. But if I open the achievements through ID then I see that it is unlocked.

## Expected result

When unlocking the achievement, I have to watch the pop-up icon of the achievements at the top of the screen.

## Affected browsers

android browser

**Comment by shortercode** [comment]
Originally I thought this was an issue caused by our use of the deferred API, but doing a little research I think I need to set the view for the popups to appear in. I will report back when I've tried it.

**Comment by shortercode** [comment]
Okay I made the change and it looks like the popups are working.

I've published the new version to NPM and the build server, and it should be available now. If your not building via the build service you will need to modify the "construct-play-games" update version to 1.0.9 before you build or wait until r101 is released.

**Comment by ERAgames777** [comment]
@shortercode thank you! I will now update.

**Comment by shortercode** [comment]
No worries, any other problems let me know :)

On 17 May 2018 19:37, "Anton" <notifications@github.com> wrote:

@shortercode <https://github.com/shortercode> thank you! I will now update.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Scirra/Construct-3-bugs/issues/1595#issuecomment-389966866>,
or mute the thread
