### ISSUE TITLE
[r24] Selecting multiple objects doesn't show every common properties

### ISSUE THREAD

**Issue by glerikud** [Scirra/Construct-3-bugs#164]
## Problem description

This is a bit interesting situation, since it might as well be a feature request too.  If it's not appropriate here, please inform me and I'll repost it on the feature request page.

While selecting multiple objects of the same type (for ex. sprites) the editor doesn't show behaviors or instance variables in the selected objects' properties. This forces the user to re-apply every changes she wants to do on all of the selected objects one-by-one if it is about managing behaviors or instance variables. I'm aware that the families function should handle this, but I think having bulk options for these properties could save time and effort in certain cases (my case was developing educational material for students who'll use the free edition).

## Attach a .c3p

While it happens in an empty project as well with 2 sprites added in it, here's my c3p where I first noticed this:
https://www.dropbox.com/s/79x4pspjdnm3t8c/raktari_rend.c3p?dl=0

## Steps to reproduce

1. Create a new project and add 2 new sprites, or open my project.
2. Select multiple sprites on the layout.

## Observed result

The properties bar does not show behaviours or instance variables common in the selected objects.

## Expected result

That I could set/manage behaviours or instance variables with one action for all of the selected sprites in the properties bar.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 57.0.2987.133
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

Local storage
Storage quota (approx): 7.7 gb
Storage usage (approx): 124 mb (1.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 6
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is by design. If you select two unrelated sprites, the editor can't show instance variables, behaviors or effect properties, because they don't have anything in common. The clearest example case of this is if you have SpriteA with Platform behavior and SpriteB with 8direction behavior, then if you select both sprites, there is nothing in common so it can't show any behavior properties. In your .c3p you coincidentally use the same type of behavior with the same name, but this doesn't change the editor's interpretation of the selection: none of them have anything in common. (The same behavior added to two separate sprites, even with the same name, are treated as unrelated behaviors, like the Platform vs. 8direction case.)

The editor could make a special case for if the selection happens to have the same set of behaviors with the same exact names, but this would be an exception to the rule, and seems like an obvious place to use family behaviors anyway.

**Comment by glerikud** [comment]
Thank you for taking the time to explain this.
