### ISSUE TITLE
Sprite sheet count cause system to wait for longer times for every tick, which cause fps drop

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1641]
## Problem description
I was having problem on some strange case when add sprite or modify project fps changes a lot! Even after i save modified project and load it. Did project files 1 vs 1 comparison, to look if something odd is saved there from previous project - was all correct. Only thing that was common for each of them and when fps problem occurred was sprite sheet count, which you can check in tools - view spritesheets.
 I tried to make different projects, with different methods to rule out some other behavior, plugin, random, set angle or something like that affect it. 
Same thing happens on stable 98 version and both c2/3 runtime.

Having 1 spritesheet vs 2 or 3. every tick will go much longer - result low fps. whole system is designed to wait for everything and then add 1 tick for system, for logic to stay correct. But sprite sheet count cause this wait to grow alot.
It showed first on my pc, did test on 2 laptop and problem occurred, but they have graphics driverc which are very old(last update 3+ year ago etc).
So i did test with my phone redmi note 4. Android version 7.0 NRD90M
Spawned sprites every tick, while tick count lower then 250.
Check wallclock time to reach 250 tick. 
I did multyple test, result stays always the same.
1 sprite sheet ~4.3 sec, 
2 sprite sheet  ~4.7sec,
3 sprite sheet ~6.1sec
Wasent enable to generate 4 sprite sheet and put 1 sprite into each of 4 sprite sheet to test this. But it could still happen on big project i bet.
Same thing happens when you now rotate, move etc. much lower fps. While everything else seems to stay the same. Sometimes there was CPU, sometimes draw calls but i think thous measurements result of specific test method. 
Difference on phone fps was lower, while everything was spawned already, while you do sprite rotate, move etc. But my oldest laptop there was difference on 1 case 13 fps vs 40 fps.
Even my oldest laptop is still more powerful then atm sold new ones around 200 eur.
My test use wallclock time but using timer, or no timer at all, debug or not debug mode , or text object. You can clearly see thing take longer to happen and lower fps.

It also tend to happen while you use sprites from different spritesheets, there was some test where i did not see any difference, something like third spritesheet was occupied just by tilemap etc.
I can also link chrome dev tool results if needed.

## Attach a .c3p

[Tests.zip](https://github.com/Scirra/Construct-3-bugs/files/2054126/Tests.zip)

## Steps to reproduce

1.Open test.zip
2.Import all 3 tests into c3
3.Start with spritesheet 1 test, check spritesheet count. Do remote preview for phone(weaker systems it shows up better) (i dont have super gamer rig to test, or set test for)
4. look timer and note it down
5. Open 2 project, confirm sprites sheet count and do same test, look timer
6. Repeat same procedure for 3 sprite sheet test, check all used sprite  occupy least 3 spritesheet.

(-One of the simplest method to replicate this, is creating 30  32x32 sprites which result 1 big spritesheet and then delete 10 - which results 3 sprite sheet. Which is fast method to switch between fast fps or low.)

## Observed result

Each tick take much longer while there are more spritesheets, which cause fps drop and or so called jankiness which is bad.

## Expected result

There should be smaller difference, or have way to change sprite sheets inside project or something like that.
I personally hope if this is a bug, it also gives less fps drops on smaller projects with fewer objects. 

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
See this blog post: https://www.construct.net/blogs/ashleys-blog-2/how-the-construct-2-webgl-renderer-works-917

Essentially by mixing up different sprites in the Z order you are hitting a worst-case-scenario performance situation where the runtime must switch texture for every instance. However spritesheeting largely mitigates this by substantially reducing, or completely eliminating, texture switches. For example if all the sprites are on the same spritesheet, it never needs to switch texture.

As you've noticed though, when the objects are spread across different spritesheets, this forces the runtime to switch texture while rendering through the Z order. The way spritesheets are assembled is partially optimised to reduce memory use, and is somewhat unpredictable depending on precisely which images your project uses. You can't really depend on any particular spritesheet arrangement, and the editor can't predict in advance what the runtime rendering patterns will be either.

The best solution is to sort similar sprites in the Z order. In the fake 3D example this would basically mean sorting the Z order so that all the base layers are next to each other in Z order, then all the next layer all together, then the next etc. In other words instead of having a Z order of ABCABCABC, make it AAABBBCCC. Layers are a good way of doing this, or with lots of objects it might be easier to use the system "Sort Z order" action.
