### ISSUE TITLE
[Website | Feature Request] Enhancements To Website Notifications

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#1680]
## Problem Description & Feature Request

With the added notifications from forum posts, notifications can get quite messy.
I would like to suggest the following enhancements to the notifications page:
- Filters:
  - Events & Sales
  - Construct 3 Updates
  - Construct 2 Updates
  - Blog posts
  - Forum posts
- "Mark notification as read" button(s)
- "Mark notification as not read" button(s)
- "Mark all as read" button

**Comment by Kyatric** [comment]
I would also add an option to mark some specific notification as "not read" even if they had been seen.
At times you will check the notifications, and not be willing to "treat" it right away/leave it for later.

Marking a notification as "not read" is a good way to do so.

**Comment by AshleyScirra** [comment]
We'd like to move all non-trivial suggestions off the Construct 3 bug tracker, so this issue is being closed. Please post all feature suggestions to https://construct3.ideas.aha.io/ or mention them in the [Website forum](https://www.construct.net/forum/scirra-website/website-issues-and-feedback-35).
