### ISSUE TITLE
Groups affecting execution

### ISSUE THREAD

**Issue by Keevle** [Scirra/Construct-3-bugs#1697]
## Problem description

*Enter a concise description of your problem here*

## Attach a .c3p

Go to the start page
Then go to the "Infinite jumping template"

## Steps to reproduce

1.Create the infinite jumping template project
2.Preview the project then when you die close the project 
3.Put the same code inside of a group then run the project again

## Observed result

Puting the same exact code into a group somehow messes up the execution

## Expected result

It runs normally like how it runs outside of the group

## Affected browsers

* Chrome: yes
* Firefox: Na
* Edge: Na
* Safari: Na

## System details

No crashes

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Moving all the events in to a group means moving global variables in to a group, where they become local variables scoped to that group only. Local variables reset their value every tick by default (mimicking how they work in programming languages). This change breaks the logic of the project. If you mark the local variables "static", they preserve their values like global variables, which fixes it again. This is all by design.
