### ISSUE TITLE
[Desktop Build - R105] Open recent only shows folders, not files

### ISSUE THREAD

**Issue by RabloGames** [Scirra/Construct-3-bugs#1703]
## Problem description

When using the Desktop build withR105, the "open recent" tab only shows the folder containing my files and "New Folder"

## Attach a .c3p

Not relevant as not dependant upon the project.

## Steps to reproduce

1. Make a simple project
2. Save it on the cloud (Onedrive)
3. Also save it locally
4. The open recent tab doesn't show any files, but only the folder name and new folder

## Observed result

https://i.imgur.com/7oyhf6A.jpg
(I've put a big bold stroke upon the name of my project as it is secret at the moment, but the name of the folder was displayed)

## Expected result

I would like to see the list of all files in the folder (maybe even along with files from onedrive)

## Affected browsers

Desktop build

**Comment by shortercode** [comment]
I've had a search through and I think I've found the issues that you were encountering.

Firstly I should point out the existing version uses the project ID to decide if it should update an existing entry or add a new one. So if you have multiple versions of the same project in different locations only the last saved will appear in recent projects.

Based on your report I've identified and fixed the following issues:
- when opening a project the recent project entry was being updated to the project name instead of it's filename.
- saving ( not save as )  to local file or local folder was not updating the recent project entry.

Additionally I've updated the matching logic to have different entries based on the project location, so if your saving your project to multiple locations for backup etc each one will have an entry in the list.
