### ISSUE TITLE
Can't save to Google Drive after refusing accessing my files

### ISSUE THREAD

**Issue by avicbk** [Scirra/Construct-3-bugs#1728]
Nevermind. Found the way to set it up again.

**Comment by shortercode** [comment]
I'm afraid it's a compatibility issue at this point. If we changed it
existing users would be unable to access their projects.

I understand your concerns about giving general access. At the time it was
being set up we chose to use general because app specific access prevents
the user from accessing the files outside of the application and we
considered that more important.

If you want to use a sandboxed style file access I would recommend using
Dropbox instead as we use "app mode" on that.

On 24 Jun 2018 13:49, "avicbk" <notifications@github.com> wrote:

Problem description

Can't save to Google Drive after refusing accessing my files. I can't
change my settings to allow access to my files on my drive.
I'd rather of course to allow Construct3 to access only a specific
directory and not to all my personal files...
Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please
see the guidelines*
Steps to reproduce

*There is no need to explain how you made the attached project. Just
explain what to do to with it to observe the issue.*

   1.
   2.
   3.

Observed result

*What do you see happen?*
Expected result

*What did you expect to happen instead?*
Affected browsers

   - Chrome: yes/no
   - Firefox: yes/no
   - Edge: yes/no
   - Safari: yes/no

System details

*If you see a crash report dialog, please copy and paste it to where it
says "PASTE HERE" below. Otherwise please go to Menu -> About -> Platform
information and paste that information there instead.*
View details

PASTE HERE

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Scirra/Construct-3-bugs/issues/1728>, or mute the thread
