### ISSUE TITLE
In the animation editor, any pixel touching an edge will get duplicated outwards

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#1783]
## Problem description

In the animation editor, if a pixel touches the edge of the animation editor, it gets duplicated.
Here's an example:
![image](https://user-images.githubusercontent.com/32940085/42458929-d5644406-8368-11e8-925b-bd462b976373.png)
![image](https://user-images.githubusercontent.com/32940085/42458978-f0827884-8368-11e8-8f5d-65b5a3df6eab.png)

This makes it so that any image in a power of two takes a lot of space on the spritesheets
![image](https://user-images.githubusercontent.com/32940085/42459095-26cb81a6-8369-11e8-8213-807d93dd689a.png)

Once the image is resized to 30x30, it fits the spritesheet properly with the doubled pixels on the edges 
![image](https://user-images.githubusercontent.com/32940085/42459511-be6de35a-8369-11e8-8774-37f162a3bd20.png)

Sorry about not adhering to the guidelines I thought the problem would be better represented with pictures, I hope that's okay

**Comment by DiegoScirra** [comment]
When does this happen? When the image is imported?

**Comment by eleanorawesome** [comment]
https://puu.sh/ATxsW/a38ab1c98b.c3p

new empty project
![image](https://user-images.githubusercontent.com/32940085/42463543-69920f9a-8374-11e8-8fc6-ee2ed268e2d3.png)

sprite touching on all sides
result:
![image](https://user-images.githubusercontent.com/32940085/42463596-9859b49a-8374-11e8-8e54-41c0cb36439c.png)

all the borders got added an extra pixel, images take 4 times the space they should because of this

**Comment by eleanorawesome** [comment]
Sorry if It wasn't clear, right after creating the image and closing the image editor, I open the spritesheet and download the resulting image by drag n dropping it on my desktop and then open an image editor to be able to zoom it to see that all of the edge pixels got duplicated

**Comment by eleanorawesome** [comment]
Ah I misunderstood what you said. I'm sorry.

I created a new sprite
I resized the new sprite to 32x32
I filled it with green with the bucket
I gave it blue lines with the line tool to make duplicated pixels noticable
I duplicated it
I added colored dots along the edges to see they got duplicated more clearly and marked them with a number corresponding to their frame in the animation editor,
then when I went to check the sprite sheet it was like that

**Comment by SnipG** [comment]
I had this issue but, if you read ashley blog it is like that.
https://www.construct.net/ee/blogs/ashleys-blog-2/you-can-ignore-power-of-two-image-sizes-now-937
Read there spritesheeting :)

**Comment by eleanorawesome** [comment]
Using the crop button adds a 1 pixel border. My 30x30 image edited to fit inside those restriction then bumps up to 32x32, then gets extra transparent pixels on all sides and is unable to fit the spritesheet properly. Something is wrong

**Comment by AshleyScirra** [comment]
This is by design. It is essential to repeat the outer pixels of images on the spritesheet, because if images are placed exactly adjacent, then color bleed can occur between them. For example if a red sprite gets a green sprite placed on its spritesheet exactly adjacent to its right, then displaying the red sprite can show a green tinge down the right side of the image due to the adjacent green image bleeding over with linear sampling. Note this is still essential even when cropping adds a 1px transparent border, since it could still bleed in an opaque color on a transparent edge, too.

This is why we specifically advise not to use power-of-two size sprite images, as mentioned in that blog post: they are the worst-case size for fitting on to spritesheets given the fact they're padded.
