### ISSUE TITLE
Request Fullscreen and Set Canvas Size not working

### ISSUE THREAD

**Issue by dru1000** [Scirra/Construct-3-bugs#1789]
## Problem description

After switching the game to fullscreen the set canvas size action doesn't change the canvas size.

In Project Properties I've got Fullscreen Mode set to Off (I don't want the layout scaling when resized).

Running the latest C3 Beta version.

## Attach a .c3p

[Fullscreen issue (1).c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2184145/Fullscreen.issue.1.c3p.zip)

## Steps to reproduce

1. Press F to switch to fullscreen

## Observed result

Canvas size doesn't change

## Expected result

Canvas should resize to Browser.WindowInnerWidth x Browser.WindowInnerHeight

## Affected browsers

* Chrome: yes

**Comment by gloater** [comment]
**not working for me 2**

**Comment by AshleyScirra** [comment]
The problem is "request fullscreen" takes a moment to actually switch in to fullscreen mode and then apply the new fullscreen rendering settings. Also note the name "request", which could potentially involve prompting the user if they want to allow it or not. However you change the canvas size immediately after making the request, when it has not actually finished entering fullscreen mode yet - or could still be waiting for a response from the user. If you use a different key to change the canvas size, and then press that after switching in to fullscreen mode, it works correctly.

**Comment by gloater** [comment]
when i export to xcode i able full screen but now it show bar like this 
![simulator screen shot - iphone 6 plus - 2018-07-17 at 01 04 52](https://user-images.githubusercontent.com/9677929/42813400-8d546a80-89c9-11e8-90c0-4d39173f8f81.png)
