### ISSUE TITLE
Game behaves differently depending on the runtime

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#1812]
## Problem description

In my game the player have the ability to dash in any direction, and the ability works pretty well in the C2 runtime, but not in the C3 runtime, it's buggy for no reason.
I'll show you a sequence of dashs in various directions (→↑←) on both C2 and C3 runtime so you can see what i'm talking about.

C2 RT - Everything works well here, i press "x" + "→" and the player will dash to the right, i press "x" + "↑" and the player will dash upwards, i press "x" + "←" and the player will dash to the left.
https://i.imgur.com/Dx5jO9k.gif

C3 RT - Somethings are buggy here, a random black block appear on top of the player sometimes when he starts a dash (probably a webgl problem because i have a ball with some effects to distort the background when the player start the dash), the first dash is normal, but if you hit a wall the second dash will not work, and the third dash works, but the player go off the ground before starting the dash.
https://i.imgur.com/EhBAEH6.gif

All this weird behaviours start by simply changing from one runtime to another, definitely a bug.

I removed everything i could from the project, the only thing left is the player code and sprites.

## Attach a .c3p

[C3 RT Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2206303/C3.RT.Bug.zip)

## Steps to reproduce

1. Open the game (C2 RT)
2. Press "x" + "→"
3. Press "x" + "↑"
4. Press "x" + "←"
5. Open the game (C3 RT)
6. Press "x" + "→"
7. Press "x" + "↑"
8. Press "x" + "←"

## Observed result

The player behaviour change according to the runtime.

## Expected result

The player behaviour to be always the same.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by BonzerKitten7** [comment]
Yes, you're right about that, you need to use any directional input before pressing "x", sorry for my bad description.

That's weird, i can reproduce it on my main PC, on my work PC and on the laptop that i use for college, so it's definetely not on my side.

I'll try to recreate the problem with an empty project, but i'm afraid that i'll end up with something similar to what i already sent you, so you still may have some work to do since it need to be fixed anyway. Well, i'll come back later with some news about this project.

**Comment by BonzerKitten7** [comment]
Forget what i said, i'm trimming down many of the project parts and still being able to reproduce the bug.

**Comment by BonzerKitten7** [comment]
I removed everything i could, layouts, event sheets, sprites, plugins, behaviours, everything! I only left the pieces that i need to make everything work together, and the bug still is present, if you switch between runtimes you will be able to see the same problem happening again.

I really hope that you can fix this engine problem soon because I'm planning to release my game on Steam by the end of August, and the performance boost that the C3 runtime can offer would be a good addition.

[c3_rt_bug_minimal_repro.zip](https://github.com/Scirra/Construct-3-bugs/files/2214375/c3_rt_bug_minimal_repro.zip)

**Comment by AshleyScirra** [comment]
There are still 37 events. Are you sure you can't reduce it any further? As I mentioned debugging anything with more than about 5 events is a formidable challenge and could take a very long time to work out - so much so that it's often quicker to spend quite some time reducing the project to the tiniest possible repro, so that debugging is effective.

**Comment by BonzerKitten7** [comment]
[c3_rt_bug_minimal_repro.zip](https://github.com/Scirra/Construct-3-bugs/files/2220494/c3_rt_bug_minimal_repro.zip)

I reduced it to 18 events, and ~10 of them are just for setupping the player and detecting input, so you basically have 8 events to analyze, which sounds like a good number. Let me know if there's anything more that i can do to help you with this issue.

**Comment by Tarek200** [comment]
BonzerKitten7

The problem it looks like is when they switch from (Platform to 8Direction) Behaviour it gives an extra push in direction of the last Dash making it go in diagonal first then correct himself to the correct Angle, that's why when you dash next to any of the solids walls and you try to Dash up what happens is that first jumps moving in diagonal making it collide with the solid Wall then the Event 17 stops it from jump because it collides with the wall.


Example:
1-Here I dash to the Right but not too near to the wall 
2-Then when the Dash it finishes I make another Dash Up 
3-The (Blue box) the stopper of the Dashes which spawns right at the top of the Player and at the exact Player.x, so here you will notice the player when jumps go slightly at the right of the box which is wrong he should jump straight at the  Box.X  meaning on the exact Middle of the blue box 
[https://www.dropbox.com/s/8mk3jjt7eu8idid/DashBug1.png?dl=0](url)
https://www.dropbox.com/s/50sh3hk8dzo9gxc/DashBug2.png?dl=0
https://www.dropbox.com/s/d9ooszpagji4ewx/DashBug3.png?dl=0
https://www.dropbox.com/s/kofn76xsgbp7taw/DashBug4.png?dl=0


And the same will happen if you test the same but Dashing to the Left direction then after Up, it will do the same but this time it will go first to the Left diagonal then Up

In Resume when jumping Up he should Only be Moving by  Player.Y, in this case, he Moves both (X,Y)

**Comment by Tarek200** [comment]
In Resume when jumping Up he should Only be Moving by  Player.Y, in this case, he Moves both (X,Y) 


The Good News is that if you are using the 8dir behaviour just to make the Dash then you can remove it as you don't need it, you can use instead move at Angle and this problem will solve

Just replace this 3 Events
event 14: var_dash_direction = 180 >>>  set player Move at Angle 180  and distance 512 x dt

event 15: var_dash_direction = 0 >>>  set player Move at Angle 0  and distance 512 x dt

event 16: var_dash_direction = 270 >>>  set player Move at Angle 270  and distance 512 x dt

**Comment by BonzerKitten7** [comment]
Thank you very much for your efforts, Tarek200!! I'm pretty sure that all this information will help Ashley find the problem inside the engine and fix it properly.

Your workaround sounds good, but i already tried to make something similar, and the problem is that sometimes the player will first clip inside the wall and then he will be "spit" out of the wall when the platformer behaviour is re-enabled after the dash, that's why i added the 8direction behaviour, it's easier to control the player and prevent him to clip inside the wall since the 8 direction behaviour is made to work with the solid behaviour on the walls.

BTW, i hope that the new Tween behaviour/plugin will have the option to "stop on collision with solid", just like the old move_to behaviour from Rex, it will make everything easier to re-create this dash mechanic.

**Comment by Tarek200** [comment]
No problem mate :)

> Your workaround sounds good, but i already tried to make something similar, and the problem is that sometimes the player will first clip inside the wall and then he will be "spit" out of the wall when the platformer behaviour is re-enabled after the dash

I see what you mean, 
I didn't test much is good you checked it,
After reading your comment I was curious about if it was possible to do it without the 8dir Behaviour I will leave the Results here you may find something useful, it's working ok for me no missing solids, when jumping on diagonals you may have to put that red detector that you have in your capx to smooth block the solids.
I hope it helps, Good luck 

[https://www.dropbox.com/s/hk9br0t5dylvgtx/DashBug.capx?dl=0](url)

**Comment by AshleyScirra** [comment]
OK, thanks for the help, I think I finally got to the bottom of this. In the end it turned out to be combining "simulate control" with a disabled behavior did not always work exactly the same in the C3 runtime. It could end up with the control still considered down when enabling the behavior, which in this case caused a tick of horizontal movement into the tilemap, causing a collision and prematurely ending the dash. This should be fixed in the next release.

**Comment by BonzerKitten7** [comment]
Nice! Thank you, Ashley. :)
