### ISSUE TITLE
Construct Store Request - Purchase Product List

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1814]
I have a ton of purchased products, the store layout is vertical and a long list., 
I would like to see this abbreviated and in a grid with paging possible, web pages do have a memory limit and the load time for my list is a very long load time with over 200+ and i still have a ton to claim.

So a better organization to the list is preferred, maybe even just details and no image, like a gridview with a button next to each data item for download, if picture still wanted, then reduce to maybe 64px,64px etc.

**Comment by AshleyScirra** [comment]
We'd like to move all non-trivial suggestions off the Construct 3 bug tracker, so this issue is being closed. Please post all feature suggestions to https://construct3.ideas.aha.io/ or mention them in the [Website forum](https://www.construct.net/forum/scirra-website/website-issues-and-feedback-35).
