### ISSUE TITLE
Construct Store Request - Un-redeemed items list

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1815]
This list currently is beneath the current list of available downloads, this really needs its own page, maybe combine it with the Redeem code page, which makes more sense, you can click the item to redeem and redeem it on the redeem page.  Also, this would best be suited with smaller images, a gridview with limited details to increase load time.

**Comment by AshleyScirra** [comment]
We'd like to move all non-trivial suggestions off the Construct 3 bug tracker, so this issue is being closed. Please post all feature suggestions to https://construct3.ideas.aha.io/ or mention them in the [Website forum](https://www.construct.net/forum/scirra-website/website-issues-and-feedback-35).
