### ISSUE TITLE
Construct Store Request - No Duplicates as filter option

### ISSUE THREAD

**Issue by zumwaltwood** [Scirra/Construct-3-bugs#1816]
Since I want to buy more items, i am old, thus, i can't remember everything i purchase, so i want the system to have some intelligent interface that filters out what i already own, as an option. I mean, i get it, people want to buy duplicate items as gifts, that's cool, but, in the event someone like myself wants to full my cart with goodies that i don't already own, i have no way to really do that, so it highly limits me as to how I do my shopping.

**Comment by AshleyScirra** [comment]
We'd like to move all non-trivial suggestions off the Construct 3 bug tracker, so this issue is being closed. Please post all feature suggestions to https://construct3.ideas.aha.io/ or mention them in the [Website forum](https://www.construct.net/forum/scirra-website/website-issues-and-feedback-35).
