### ISSUE TITLE
[Possible Issue][Part 1] On Layout Change, Anchored objects on Bottom or Left sides disappears.

### ISSUE THREAD

**Issue by ChadoriRebornXD** [Scirra/Construct-3-bugs#1817]
## Problem description

**This happens when changing the Canvas Size + LayoutScale.**

Imagine having two similar layouts. One is an initial layout, and another is to be the next layout.
If the initial layout have some anchored startup objects to the bottom or right side of the view-port, it will anchor without a problem.

But if another layout, even a clone layout, with the same conditions, were to be the next layout by calling "Go To Layout", it will have anchor problems.
The anchored objects will disappear.

## Minimal Project Sample

[BugReport1.zip](https://github.com/Scirra/Construct-3-bugs/files/2212061/BugReport1.zip)

## Steps to reproduce

1. Press the button to change layouts.
2. Observe the effects of 2 similar layouts.

## Observed result

After "Changing Layouts", the destination layout's anchored objects from the [Bottom, Right, Bottom Right] side will disappear outside from the view-port.

## Expected result

For the Anchored Objects to not only anchor properly from the initial startup layout but also to other possible destination layouts. 

## System details

Construct 3 :: Release 109
Construct 2 :: Release 261

## Note

There is still a Part 2 version of the issue, which seems similar to this Part 1 version of the issue.

Thank You in advance for looking into this.

**Comment by ChadoriRebornXD** [comment]
[1/2] This is the first out of the 2 issues.
Part 2 :: https://github.com/Scirra/Construct-3-bugs/issues/1818

**Comment by SnipG** [comment]
If you go base layer - remove render cells and click sprite make global, it will work.
But there is some strange behavior.

**Comment by AshleyScirra** [comment]
This is a super confusing setup. It's hard to work out what's going on. I think it's something like this: on startup, the Anchor behavior pins itself based on the position in the layout view. So in this case due to the settings it calculates the vertical space from the bottom of the object to the bottom of the dashed line in the layout view, and then aims to always keep the object positioned that distance from the bottom of the viewport. Then on start of layout you immediately change both the canvas size and layout scale, both of which affect the viewport; the anchor behavior ignores this change and continues to position the objects at the same vertical distance from the bottom of the new viewport, which causes everything to shunt vertically. (This is probably already not what you want - it causes every object to move in the viewport to somewhere else instead of staying where you put it.) When you change layout the object is destroyed and recreated on the next layout; the Anchor behavior repeats the process of calculating its offset to the bottom of the viewport, which is now a different viewport to the one in the layout view, so then it moves again and goes to a third position, which this time happens to be offscreen :P

AFAICT it's all working as designed, but I guess the Anchor behavior isn't appropriate in this case because the viewport is dynamically changed by events and the Anchor behavior isn't designed to respond to that. I think you should just use events based on the viewport expressions instead.

**Comment by ChadoriRebornXD** [comment]
@SnipG Your solution seems to might work for some projects but might be too unnecessary for me since I, as much as possible would want to avoid global objects for larger scale optimization. Thank you for showing and providing your say and solution on the topic though.

@AshleyScirra Okay. Thank you for explaining. I've made some workarounds based on your suggestion.

**For documentary purposes, for people in the future who would need a workaround for this.**

Using the Self Function Plugin :: [Easier Version]
[Workaround_SelfFunction.zip](https://github.com/Scirra/Construct-3-bugs/files/2215753/Workaround_SelfFunction.zip)

Using the Function Plugin ::
[Workaround_Function.zip](https://github.com/Scirra/Construct-3-bugs/files/2215754/Workaround_Function.zip)
