### ISSUE TITLE
Won't load preview

### ISSUE THREAD

**Issue by markbellharmony** [Scirra/Construct-3-bugs#1821]
## Problem description

The project won't run in either online or destop version (stable and beta). Works sometimes and not others. Must have failed to load preview 200 times in the past week. Then crashes Construct. 

I have tried the following:

* save as file
* save as project 
* reinstalling desktop stable and beta
* updated java
* restarted machine
* tried on 2 different machines
 
## Attach a .c3p
PLEASE DO NOT MESS WITH MY PROJECT. I have worked two years on this project and don't want to loose it all. 

[cp0.3.2.30.zip](https://github.com/Scirra/Construct-3-bugs/files/2216357/cp0.3.2.30.zip)

## Steps to reproduce

1. Click preview, debug or preview project. 
2.
3.

## Observed result

Construct shows error and won't respond. Must be restarted. 

## Expected result

The viewer to show my project. 

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.31.2
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@878cd31214ac27a3996927cd5c9c138b10c9fc8d) NWjs/0.31.2 (like Chrome/67.0.3396.87)
C3 release: r109 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 19 gb
Storage usage (approx): 179 mb (0.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 6
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by NetOneGames** [comment]
It looks like it is falling over trying to render the sprite sheets for something. You do realize you have some unnecessarily super huge sprites and tile-maps hanging around.  Also the tile-maps are already huge repeated patters in themselves in some cases.   Although Ashley may be able to figure it out I would say you should look into sorting the overlarge sprites/tilemaps first and then start to delete stuff bit by bit saving and previewing as you go to see what is causing the error

**Comment by markbellharmony** [comment]
Thanks so much. Today is a travel day for me but I'll have a crack at that on Tuesday.

**Comment by AshleyScirra** [comment]
It looks like there's something wrong with the spritesheeting. (It also crashes if you go to project -> tools -> view spritesheets). The project also has some extraordinarily large and wasteful images - for example tbg_00.png is 4480x2688, which is larger than many devices actually support (4096 being a common limit), and the image content is the same small image tiled over and over again. So the image takes up 48mb of memory when it could just tile the repeating 128x128 section, which would use 64kb of memory. So the image unnecessarily wastes about 750x as much memory as it needs to, for a single image. This should be fixed anyway, but may also be related to the problem, since the spritesheeting engine has to specially handle such large images.

**Comment by AshleyScirra** [comment]
The problem appears to be that the project is corrupt. In 14 cases the project file states the wrong size for the image. For example tbg_01 specifies a size of 2813x1688 in the project file, but the actual image is 4480x2688. To avoid having to decode the image when loading projects Construct will honour the size in the project file, but since this is incorrect and images are a different size to what Construct thinks they are, it can end up generating a spritesheet too small to fit them and then crashes trying to render the image off the edge of the spritesheet.

I've never seen this before. It ought to be impossible. The only way I can think this happened is if you directly edited the images in the project file outside of Construct, and replaced them with ones which are a different size. @markbellharmony - have you done something like this?

Marking this issue as 'difficult' as we don't have steps to reproduce for the root cause that ends up with incorrect image sizes in the project file, so we can't directly debug this.

**Comment by AshleyScirra** [comment]
I'm not sure you understood my comment? I asked if you had previously replaced image files to ones with a different size outside of Construct. This is not something new to try, it's something I need to know to help diagnose the problem.

**Comment by markbellharmony** [comment]
@AshleyScirra Thank you so much for your help on this. I made my background files in Photoshop using its tiling function and inported them into Construct. This is most likely causing the problem. I am going to try to fix this today and see if I can build. 

M

**Comment by AshleyScirra** [comment]
How did you import them in to Construct? I specifically need to know if you did this outside of Construct (i.e. editing the project folder/zip file directly), in which case the root cause of the bug has been identified; otherwise if you did it entirely inside Construct, there is probably a bug in Construct itself that still needs to be properly identified.

**Comment by markbellharmony** [comment]
@AshleyScirra I dragged them into the construct imain mage viewer from a file explorer after editing them. Today I replaced then all in the image viewer by using open in the construct image viewer. Works fine. Runs fine. Save and check back into my github. Stops working again. The image files are now all tiny but then layout  is still huge. According to the statistics game_layout is 61 mb. Is that layout corrupt now?

**Comment by AshleyScirra** [comment]
I still have no idea what you're doing. It sounds like you're using github as source control for the project. Is that correct? I assume you are therefore using the desktop build's save as folder option to keep separate files?

If so there would be plenty of opportunity to swap out image files with different ones on source control - either intentionally, or accidentally by merge/conflict/etc. Basically if you have a folder project and at any point an image is replaced with one of a different size by overwriting the file (rather than editing in C3), it will corrupt the project because Construct expects it to be a different size. Based on what you've mentioned I suspect this is what is really happening, but it would be nice to have some kind of direct confirmation that this has happened at some point with your project, to rule out the possibility there is a bug in C3 itself somewhere.

Replacing image files outside of C3 is tricky to fix - we could stop trusting the size in the project file, but then this means decoding the image while loading the project to find out the true size. This would slow down loading projects for everybody, so I'd prefer not to do that.

**Comment by markbellharmony** [comment]
@AshleyScirra I am using github as source control. I am therefore using the desktops build as a folder option to keep separate files. I have to do this so that I can edit the json array files that make up part of my game in notepad++ because the viewer in construct 3 makes them very difficult to read. The X and Y are swapped.

I have not directly edited any of the image files except through construct image editor, either by dragging in a file or by using the open command. So I am not editing image files outside of C3. 

I have made all my images small and close to the 0,0 point on that layout and i am still having the problem. 

I understand this is probably a very rare occurrence. At this point my game is toast that I have been working on for two years and have no idea what to do.  

Would having access to my github help you? 

Anything else you can suggest?

M

**Comment by AshleyScirra** [comment]
I can probably recover the project attached in the original report if that would be helpful? However there's no guarantee it won't happen again.

It wouldn't take much to swap some image files accidentally with source control, you only need to miss a file on a commit or update and it could end up with the wrong image. Unless anyone can find steps to start with a good project and make it go bad from within C3, I'm going to assume that's the root cause problem.

**Comment by markbellharmony** [comment]
It will just corrupt again. I am sorry I am pretty wrecked over this since I have put 2 years into this and there is no way I can see to complete the project. 

I can't use the project as single file option because of my jsons and I can't use multiple file option without it corrupting. I know I added every one of those images through C3 but basically am looking at starting again. 

I worry this project is too much for c3 to handle yet.

**Comment by SnipG** [comment]
Is it even possible to import images, that are not renamed on export? Shouldn't that example big images be renamed differently? All other images are right and follow construct renaming order, but thous problematic ones don't follow renaming order!
Markbell - what are image original names and file format, before you drag them into Construct?Could you test it yourself. Import just 1 image, check on export have Construct renamed it, if it fails to rename, it could cause some other problem on export/import.

**Comment by markbellharmony** [comment]
I'm on the road until Friday. Saturday I'll try to build a branch and see if i can fix this. 
M

**Comment by markbellharmony** [comment]
I was already to tell you i had gone back and fixed everything. Basically recreating two weeks work and there was no preview problems when I check it in and went to reopen the project and I get a new error. 

Failed to open project. Check it is a valid Construct 3 folder project. 

I have attached entire folder project 
[cq.zip](https://github.com/Scirra/Construct-3-bugs/files/2238260/cq.zip)

Any ideas?

Also, even after downloading newest c3 beta I get a warning I am running r110.2 and need to upgrade to r111 so I undate and yet it asks me every single time.

**Comment by markbellharmony** [comment]
Tried on 2 machines same problem though the text of the c3proj file looks ok.

**Comment by markbellharmony** [comment]
@AshleyScirra  Should this be submitted as a separate bug?

**Comment by AshleyScirra** [comment]
The last provided project is corrupt for the same reason (wrong image sizes), as well as also incorrectly duplicating an image ID.

I have never seen anybody else reporting issues like this. Given that you mentioned you are using GitHub as source control, which could corrupt projects if incorrectly merged/updated, I strongly suspect you are doing something with source control that is corrupting your project.

It is absolutely critical to get steps to reproduce the problem in the first place. We need a list of instructions to follow that starts with a working project, and ends with a broken project. Without that all I can see is a corrupt project and it's a mystery how it ended up like that, because Construct should never save such a project. Presumably something else (source control) is corrupting the project.

Even if you get the steps, they may simply outline how to use source control to corrupt a project. This means the problem isn't with Construct, it would be to do with how you are using source control.

**Comment by markbellharmony** [comment]
@AshleyScirra  First, thank you so much for all the work and thought you have put into this issue. 

I am using git hub and have been using it for 2 years with no problems with this particular project. What is weird is that this version of the project is a branch from the original that had no large files in it at all. 

Also I am using github in the the most basic of ways. Just check in and update. No merges, branches or anything that is difficult. 

Is there any way to save this project and do you have a suggestion for an alternative version control?

M

**Comment by AshleyScirra** [comment]
Source control is all in principle the same and probably equally easy to corrupt the project. I'd rather not comment further before we properly understand how this is happening.

**Comment by markbellharmony** [comment]
@AshleyScirra ok I didn't mean to piss you off.  All I did in the latest version was:

1. Normal construct functionality.
2. Import images using construct. nothing larger than 128x128
3. Resize within construct. 
3. Save in construct. 
4. Check in and push to origin. 

I never merge or used another machine or version of construct. After check in I go back to construct and open the file and I get the corruption message. 

I am so sorry I have upset you. I never meant any offense.

**Comment by AshleyScirra** [comment]
I'm not upset, I'm just trying to work out what the root cause is, like we do with all bug reports. I need specific steps to reproduce that I can follow though, I can't follow an instruction like "normal construct functionality", there is no chance I can be following what you're doing with that.

**Comment by markbellharmony** [comment]
@AshleyScirra Sorry I offended you. I'll take care of this and you can close the issue.
