### ISSUE TITLE
Transparent screen on Android using Multiplayer

### ISSUE THREAD

**Issue by Nabbo-extreme** [Scirra/Construct-3-bugs#1835]
## Problem description

Transparent screen on Android using Multiplayer when any peer joins on R104

## Attach a .c3p

[Archive.zip](https://github.com/Scirra/Construct-3-bugs/files/2220867/Archive.zip)

Attached apk and c3p inside Archive.zip file

## Steps to reproduce

1. Run Android version and click on any map location
2. It connects as host or client
3. On any browser or andriod - run the game - when it joins the Android version - blank screen shows only on Android. But able to play game.

## Observed result

Blank screen shows on Android when 2 players joins a room. I see I am able to touch and play game on android if i see on browser but all screen is transparent on Android.

## Expected result

Screen shouldn't go blank on android.

## Affected browsers

* Chrome: no
* Firefox: no
* Android: yes

## System details

I tried to get error logs but couldnt get any error via chrome inspect.

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines. You should test the latest version of Construct 3 (currently r110). There are also no system details provided; it could simply be an out-of-date webview but this cannot be verified since the information is missing. (You can get the info on Android by opening C3 on the device and copying the platform info from there.)

I tested the 'multiplayer pong' demo with r110 built as an APK on an up-to-date HTC 10 and it worked fine as both host and peer, so I suspect the webview on the device is simply out-of-date. Try installing any available software updates.
