### ISSUE TITLE
[C3 Editor] Changing tabs is currently hard.

### ISSUE THREAD

**Issue by ChadoriRebornXD** [Scirra/Construct-3-bugs#1881]
## Problem description

**Ctrl + Shift + Left/Right Arrow** is hard to use when changing tabs. This process involves two hands, a very tedious process that makes it easier just to click from the layout using the mouse.
While compared to Construct 2, changing tabs is super easy. Just, **Ctrl + Tab** or **Ctrl+Shift+Tab**.

Please do fix this issue.

## Note

Thanks in advance for looking into this.

**Comment by shortercode** [comment]
I think the issue here is that chrome already uses those shortcuts and it's not possible to override them. Other logical ones are used by windows and are also not override-able So we've gone with a fairly logical choice, but it unfortunately requires 2 hands.

`ctrl + meta + tab` /  `ctrl + meta + shift + tab` works but requiring 4 keys makes it awkward for some people. In addition meta is the `cmd` key on mac, so I'm not sure what behaviour that might trigger.

**Comment by ChadoriRebornXD** [comment]
Okay. I understand.
If I may suggest. Would it be possible to use **Ctrl + Q** and **Ctrl + Shift + Q** instead.
Seems a lot easier. And I've tried on Construct 3, it seems as it still isn't used yet.

**Comment by AshleyScirra** [comment]
The desktop apps can override browser shortcuts. I've added support for Ctrl+Tab and Ctrl+Shift+Tab for the desktop apps in the next release.
