### ISSUE TITLE
Opening google cloud with 2 factor authentication on your 2factor device doesnt work

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#1883]
## Problem description

trying to access my projects stored on google cloud on the device that does the 2factor authentication results in chrome crashing

## Steps to reproduce

1. attempt to log into my google drive to access my projects
2.enter my credentials

## Observed result

bunch of flashes and then
google chrome crashes

## Expected result

log into my chrome account to access my projects

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE
![image](https://user-images.githubusercontent.com/32940085/43563503-74ad16de-95f0-11e8-98ba-77f291ee5140.png)
![image](https://user-images.githubusercontent.com/32940085/43563523-872708ba-95f0-11e8-84a5-0a99a9c64b3a.png)
![image](https://user-images.githubusercontent.com/32940085/43563531-929a7650-95f0-11e8-983c-b3f315f656e7.png)
![image](https://user-images.githubusercontent.com/32940085/43563543-a0d1c7fa-95f0-11e8-8dae-e6bb9ab580bb.png)

</details>

**Comment by shortercode** [comment]
So I tried this on my personal phone, which is about as close as we're going to get with the office devices. Pixel 2 XL running android 8.1.0, although I am using chrome 68 not 67. My phone is set up as the authenticator, so I'm not using any authentication apps. Finally I had to sign out of chrome, so that I actually saw the sign in screen.

Unfortunately after all that it worked perfectly. Might be worth checking everything is up to date on your phone, there may have been a bug in an older bit of software. Particularly chrome as there's definitely a new major version out.

If it's still broken then perhaps try signing into chrome like I had?

**Comment by eleanorawesome** [comment]
I managed to access my drive when in incognito mode, so I went back to normal mode, cleared cache and browsing data and site storage, and now chrome doesn't crash anymore, but it remembers my credentials and goes into full-screen without a prompt and as soon as I touch "Open from cloud"  it does a bunch of stuff and then the construct 3 tab closes, and I'm not sure what to do to make it work. Also it's probably not a bug at this point, I'm sorry.

**Comment by shortercode** [comment]
Well not crashing is progress... I'm not sure why the tab closes though. It could be related to the history stack, we've had issues with that in the past. Did you try updating chrome?

**Comment by eleanorawesome** [comment]
I logged out of chrome and tried again, It asked for the authentification but it never came and it said authentication failed, i pressed previous, then i tried again, the page to put my password was stuck loading for a minute, i pressed previous and I could finally see my google drive files. So solved ?
