### ISSUE TITLE
OR-block conditions not work correctly (Construct 3 ver R113)

### ISSUE THREAD

**Issue by Mit1988** [Scirra/Construct-3-bugs#1938]
## Problem description

OR-BLOCK is not triggered correctly if it has more than one object condition. It does not take the condition of different objects

## Attach a .c3p

[TEST OR-BLOCK.zip](https://github.com/Scirra/Construct-3-bugs/files/2306696/TEST.OR-BLOCK.zip)

## Steps to reproduce

Just run it ^^!

## Observed result

https://orig00.deviantart.net/c6d1/f/2018/233/f/8/test_by_mitteam-dckre06.jpg

## Expected result

The OR-BLOCK conditions should work right when at least one condition is true.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

**Comment by AshleyScirra** [comment]
This is not a bug. It's a common misunderstanding.

Actions run on the instances picked by the conditions. In your "does not work" example, you test "ConditionA < 0". The sprite A *does not meet this condition*, so it is not picked. The event runs anyway because a different condition is true, but *no 'A' instances are picked*, so the "Set visible" action does nothing.

If the event did set 'A' visible, it would mean it ran an action on an instance that did *not* meet the condition, which would fundamentally reverse the purpose of conditions in events.

**Comment by Mit1988** [comment]
Thank you Ashley, I understand. But if it is that, the way OR-block works really weird in the understanding of most people. Especially for this under example:

[TEST OR-BLOCK.zip](https://github.com/Scirra/Construct-3-bugs/files/2333782/TEST.OR-BLOCK.zip)

IF (Ant.Size > Elephant.Size) OR **( Ant.Size < Elephant.Size)** >> Set Ant ... // this action will WORK
IF (Ant.Size > Elephant.Size) OR **( Elephant.Size > Ant.Size)** >> Set Ant ... // this action will NOT WORK

I keep the same condition meaning but change the way of writing condition, and the result works in an unexpected way, such as writing 1 < 2 will work, but writing 2 > 1 does not work. 

It seems to be out of the normal logic and makes OR statement more complicated to understand than normal.

Anyway, it's only a small problem. Thank you and your team to bring this awesome engine to everyone. I really enjoy what Construct can do!

**Comment by AshleyScirra** [comment]
I think the way conditions pick instances is at odds with the way a normal boolean "OR" operator works. It's hard to reconcile. I think if we changed it so the event could run in those circumstances, it is equally unintuitive, because it makes actions run on instances that did not meet the conditions.

**Comment by Mit1988** [comment]
Yup, although I do not understand much about the details why OR in Construct works differently from a normal boolean "OR" operator works, but believe Construct are doing the best possible way. Thank you very much, Asley.

**Comment by VictoryRice** [comment]
Glad I read this, thanks for the example Mit1988. I think the manual entry on OR I'd love to see a tutorial on how to use OR blocks (and link the manual entry on OR blocks to it). It makes sense once you adjust your thinking, but for many people it's not what you'd expect at first.
