### ISSUE TITLE
'Minify script' breaks projects that use effects

### ISSUE THREAD

**Issue by Digital-Prophet** [Scirra/Construct-3-bugs#195]
## Problem description

I get a black screen when launching a game exported with NW.JS on Mac.

## Attach a .c3p

Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. Make simple project
2.Export with NW.JS option from menu (Also gt NaN errors on there - Screenshot attatched.)
3. Run game on Mac.

## Observed result

Black screen

## Expected result

To see the game

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

[test1_blackscreen.zip](https://github.com/Scirra/Construct-3-bugs/files/1000506/test1_blackscreen.zip)
<img width="510" alt="screen shot 2017-05-15 at 10 26 51" src="https://cloud.githubusercontent.com/assets/27424744/26049352/fd1fc848-395a-11e7-8a58-7b90965f996b.png">

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please always specify the exact export settings and provide a project so we can reproduce exactly what you're doing. In this case the real bug was to do with exporting projects using effects with "Minify script" enabled, which is almost nothing to do with the original report and took some time to figure out. Anyway, should be fixed in r27.
