### ISSUE TITLE
C3 Build Service with Cocoon Cordova Plugins

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct-3-bugs#1952]
I tried C2 project with C3 Build service, it is give me build error.
I used with this plugins;

- cocoon-plugin-ads-android-admob 1.0.11
- cocoon-plugin-inapps-android-googleplay 1.0.2

[LOG.txt](https://github.com/Scirra/Construct-3-bugs/files/2319299/LOG.txt)
[C2Project.zip](https://github.com/Scirra/Construct-3-bugs/files/2319300/C2Project.zip)

**Comment by shortercode** [comment]
According to your build log the server was trying to include a non-existent version of `cocoon-plugin-ads-android-admob` ( 1.0.19 ). This isn't the one you requested, but we always try to match the latest whitelisted maintenance version ( 1.0.X ) of a plugin

The problem looks to be a typo in our plugin whitelist. We had the version number from a different plugin written in for that plugin. I've switched it to 1.0.11,  as that was the last one that had been reviewed.

Unfortunately when I tried to rebuild your project I get a large number of compilation errors:

<details>

```
ludei/inapps/googleplay/GooglePlayInAppService.java:13: error: package com.android.vending.billing does not exist
	import com.android.vending.billing.*;
```
```
ludei/inapps/googleplay/GooglePlayInAppService.java:51: error: cannot find symbol
	private IInAppBillingService mService;

	symbol:   class IInAppBillingService
	location: class GooglePlayInAppService
```
```
ludei/inapps/googleplay/GooglePlayInAppService.java:66: error: package IInAppBillingService does not exist
	mService = IInAppBillingService.Stub.asInterface(service);
```
```
ludei/ads/admob/AdServiceAdMob.java:9: error: AdServiceAdMob is not abstract and does not override abstract method createRewardedVideo(Context,String) in AdService
	public class AdServiceAdMob implements AdService {
```
```
ludei/ads/admob/AdServiceAdMob.java:56: error: createRewardedVideo(Context,String) in AdServiceAdMob cannot implement createRewardedVideo(Context,String) in AdService
	public AdInterstitial createRewardedVideo(Context ctx, String adunit) {

	return type AdInterstitial is not compatible with AdRewardedVideo
```
```
ludei/ads/admob/AdServiceAdMob.java:14: error: method does not override or implement a method from a supertype
	@Override
```
```
ludei/ads/admob/AdServiceAdMob.java:55: error: method does not override or implement a method from a supertype
	@Override
```
```
ludei/ads/admob/AdRewardedAdMob.java:43: error: cannot find symbol
	AdInterstitial.Reward result = new AdInterstitial.Reward();

	symbol:   class Reward
	location: interface AdInterstitial
```
```
ludei/ads/admob/AdRewardedAdMob.java:43: error: cannot find symbol
	AdInterstitial.Reward result = new AdInterstitial.Reward();

	symbol:   class Reward
	location: interface AdInterstitial
```
```
ludei/ads/admob/AdRewardedAdMob.java:54: error: cannot find symbol
	AdInterstitial.Reward result = new AdInterstitial.Reward();

	symbol:   class Reward
	location: interface AdInterstitial
```
```
ludei/ads/admob/AdRewardedAdMob.java:54: error: cannot find symbol
	AdInterstitial.Reward result = new AdInterstitial.Reward();

	symbol:   class Reward
	location: interface AdInterstitial
```
```
ludei/ads/admob/AdRewardedAdMob.java:94: error: cannot find symbol
	AdInterstitial.Reward result = new AdInterstitial.Reward();

	symbol:   class Reward
	location: interface AdInterstitial
```
```
ludei/ads/admob/AdRewardedAdMob.java:94: error: cannot find symbol
	AdInterstitial.Reward result = new AdInterstitial.Reward();

	symbol:   class Reward
	location: interface AdInterstitial
```

</details>

I expect most of these are caused by the first failure, it looks similar to an issue I've seen before when moving from cordova 7 to cordova 8 ( which we use ). It might be fixable with a newer version of the plugin, according to [npm](https://www.npmjs.com/package/cocoon-plugin-ads-android-admob) there are 2 newer versions of `cocoon-plugin-ads-android-admob` but I'm not sure what the status of these are or if they are compatible with your project. 

Please let me know if you want either or both reviewing and I will update the whitelist.

**Comment by QuasarX** [comment]
They made 2.0.0 for Cordova 7.x.x
2.0 versions will work with my project too.
If we can build with cocoon-plugin-ads-android-admob 2.0.0 and cocoon-plugin-inapps-android-googleplay 2.0.0
This also need for TobyR' Ultimate Ads and IAP (C3 Plugins)

**Comment by shortercode** [comment]
Okay dokes, I've reviewed the following plugins and added them to the whitelist:
- `cocoon-plugin-ads-android-admob@2.0.0`
- `cocoon-plugin-ads-android-common@2.0.0`
- `cocoon-plugin-inapps-android-googleplay@2.0.0`

The other dependencies were already on the whitelist.

Just to warn you; `cocoon-plugin-ads-android-admob` includes a specific version of `play-services-ads` as a dependency ( 15.0.1 ). If you use a cordova plugin which requires any play services module ( play games for instance ) that isn't version 15.0.1 then it will likely fail to compile due to version mismatch.

**Comment by bewa11** [comment]
> 
If you use a cordova plugin which requires any play services module ( play games for instance ) that isn't version 15.0.1 then it will likely fail to compile due to the version mismatch
> 

What would be the recommended solution to this problem?

**Comment by shortercode** [comment]
There isn't really a solution, it's down to the developers of the plugins
which version they use.

To work around it in the first party plugins we specify to use whatever the
latest is. So they will all be in sync. But that does risk that the plugin
may be broken by updates to play services. In practice if that happens we
just fix the plugin so that it works with the new version.

It's probably not a strategy that would work for most Cordova plugins, as
the developers have relatively little time to maintain them. It makes sense
for them to use a known good version so that it doesn't break while they
aren't looking.

If you do have the issue the best solution is to download the Android
studio project and manually change the version numbers in the gradle file
to match.
