### ISSUE TITLE
iOS User Media (camera) seems to not be working as it used to

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#1964]
## Problem description

Trying to access and display the camera of the device (iPad) using the User Media plugin does not seem to work as intended.

## Attach a .c3p

https://kyatric.com/c3/bugs/2018.08.29.ios_usermedia_issue.c3p

## Steps to reproduce

1. Remote preview in Safari on iPad
2. Press the button "Start camera"
3. It requires the permission to use the device's camera, accept
4. (optional) you may try and take a snapshot

## Observed result

The user media area stays black.
Trying to take a snapshot (and downloading it) results in a new blank tab without content and/or download

## Expected result

The content of the camera to be displayed.
When taking a snapshot, an actual download from the browser to start

## Affected browsers

* Safari: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
looks to be an issue binding the mediastream to the video element. I know @AshleyScirra has had to make some modifications around this a few times so I'm going to assign this to him.

**Comment by AshleyScirra** [comment]
No idea why this isn't working. Would not be surprised if this is another bizarre Safari bug.

**Comment by AshleyScirra** [comment]
Turns out Safari just wanted a play() call on the video :P should be fixed for the next release.

**Comment by cjbruce3** [comment]
It appears that this (or similar) bug might have appeared again in iOS 16.5.1 Safari.  iPadOS 16.5.1 and MacOS 12.16.2 Monterey Safari are working correctly.  

To see the problem, try loading the "Camera Average Color" example project and using remote preview on an iPhone.  On my iPhone the GetUserMedia stream stops after loading a single frame.  The first frame's color is computed correctly.  Even though we all have access to the project, I have included a .zip copy below.

[camera_average_color.c3p.zip](https://github.com/Scirra/Construct-bugs/files/12022601/camera_average_color.c3p.zip)

The problem still occurs on iOS Safari when I export the project and host it from a secure website.

A few years ago the fix was to add a few lines.  I have tried adding everything I can think of, but I can't seem to get it working for my iPhone.

**Comment by cjbruce3** [comment]
I was able to get the camera working from script on iOS Safari 16.5.1 by adding the following lines to the project.

// If camera input approved, show it in the video element.
		const videoElem = Globals.videoElem;
		videoElem.crossOrigin = "anonymous";
        videoElem.autoplay = true;
        videoElem.muted = true;
        videoElem["playsInline"] = true;
		videoElem.srcObject = mediaStream;
		videoElem.play();
