### ISSUE TITLE
Mobile Advert Locations & Spoofing Settings

### ISSUE THREAD

**Issue by KENYONBcom** [Scirra/Construct-3-bugs#1975]
## Problem description

Mobile Advert Location and Spoofing settings not working as expected. I am in the US.

## Attach a .c3p

Test using any project built with r114.

## Steps to reproduce

Test #1:

LOCATIONS TO SHOW: EU AND UNKNOWN
SPOOF LOCATION: INSIDE THE EU

Test #2:

LOCATIONS TO SHOW: EVERYWHERE
SPOOF LOCATION: DISABLED

## Observed result

Consent dialog does not show.
Ads show (banner and interstitial)

## Expected result

I expected to see the Consent Dialog box.

## Affected browsers

* Android: yes
* iOS: I haven't tested on iOS yet

**Comment by shortercode** [comment]
@KENYONBcom thanks for filing the issue

**Comment by shortercode** [comment]
So I've discovered that Google are actually preventing the consent form from being displayed outside of the EEA. When you try to display it the error `Error: request is not in EEA or unknown.` is returned instead. So unfortunately the "everywhere" option is dysfunctional for now, although I have filed a bug with their tracker about it.

[https://github.com/googleads/googleads-consent-sdk-android/issues/83](https://github.com/googleads/googleads-consent-sdk-android/issues/83)

In terms of location spoofing it seems to be working correctly for me, at least when configuration is completed via the plugin properties. The `setDebugGeography` method is definitely being called with the correct simulated location options, and I can confirm that for me ( in the UK ) setting simulated to "outside the EU" will make it behave like its outside the EU ( how I discovered the above error ).

Got a few questions for you so I can move forwards:

- are you configuring via the plugin properties or the action?
- are you testing on device or on the android simulator?
- are you uninstalling the app before trying the simulated location? ( required to reset the user preference )

**Comment by KENYONBcom** [comment]
Thanks for confirming the issue with the "everywhere" option. Hopefully they fix the bug and allow it.

As for your questions regarding location spoofing:

1- I have the plugin configured in properties and also events/action.

1-a- At first I had the plugin configured to spoof location in the properties only, and left Simulate Location: Disabled in the event action. No Consent Dialog showed, but ads were showing.

1-b- I then changed the event action to Simulate Location: Inside the EU and kept spoofing settings the same in Properties (In the EU). No Consent Dialog showed and no ads showed.

1-c- I then toggled the event action with configure settings as disabled so that only the properties were configuring the plugin. No Consent Dialog showed and no ads showed.


2- I am testing with a signed APK on my Android device, Pixel XL v9.


3- I have uninstalled the app before installing for each test.

**Comment by shortercode** [comment]
The plugin will only allow itself to be configured once, it will silently skip successive configuration calls once it has been successfully configured. For the sake of simplicity I think you should attempt configuration only via one route. I feel like there might be a configuration error occurring here, so having less ground to cover will probably help as well.

It's kind of hard for me to track exactly what the problem is here, would you mind sending me a project showing how you are using the plugin? Either by uploading to this issue or emailing it to iain@scirra.com

**Comment by KENYONBcom** [comment]
Understood about configuring only once. That's why one of my tests was configuring only via the properties, but that still didn't trigger it.

But just to clarify, what is the proper method we should use to configure- Properties or Events?

Just FYI, I previously had the plugin configure in the events action because the properties weren't available to configure prior to one of the recent C3 updates.

I'll email you a project. Thanks for your help

**Comment by shortercode** [comment]
There isn't really a "proper" way, initially when I wrote the plugin you could only configure via an action and it was optional. Some people were initially confused about how you configured it, as they were used to configuring via properties. Hence I added in what was effectively an automatic call to the action using the properties when the app started. We couldn't remove the action, since it was already released, so it stayed. 

In hindsight configuration via properties is easier, so I would advise using that.

**Comment by shortercode** [comment]
_This response is mostly for keeping the issue up to date with email correspondence_

I've had a look at your project. The project worked correctly when using my admob credentials. So it's either an admob configuration issue, a location specific bug ( kinda hard for me to test ), a mistake putting your admob credentials in or a race condition.

I've sent back a slightly modified project which should eliminate any race condition, and test if 1/3 are the cause.

**Comment by shortercode** [comment]
Ah excellent! Sorry for slow reply I've been on holiday for the last week. In the last release I've added a piece of code to map show "everywhere" to "eu and unknown". It might cause some unexpected behaviour, but at least it won't break configuration ( and hopefully reduce the number of bug reports I get... ).
