### ISSUE TITLE
Lower particle performance in c3 runtime

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#1977]
## Problem description

Tried some particle test on C3, and saw C2 runtime holds ~17 000 at 30fps, while C3 can hold only 13 000.
So maybe some issue there.

## Attach a .c3p
[ParticlePerf.zip](https://github.com/Scirra/Construct-3-bugs/files/2343746/ParticlePerf.zip)

## Steps to reproduce
1.Open example, preview in c2 runtime. Note count at 30fps
2.Preview in c3runtime.
3.See C2, holds 60 fps longer and more particles at 30 fps

## Observed result
C3 runtime does have a bit lower particle performance.

## Expected result
Better or same, if it does not affect something else.

## Affected browsers
* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 68.0.3440.106
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
C3 release: r114 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 463 mb (3.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by SnipG** [comment]
Made similar test in each runtime with sprites 1x1(disabled collision,move at angle), C2 had similar performance like particles ~17k at30fps, while c3 runtime got ~23k at30fps.  From this C3 should hold higher particle count also.

**Comment by AshleyScirra** [comment]
This is kind of an extreme edge case - who would ever create thousands of separate particles objects firing 1 particle rather than just creating one (or even several) particle objects firing lots of particles each? While we're working hard not to regress performance anywhere, I don't think it's worth investing much time in such obscure cases that probably no game ever has actually done. Work on this kind of area will probably not affect any real-world games, so is essentially a waste of our limited engineering time.

Anyway I found a few simple tweaks to make it slightly more efficient. It didn't seem to improve the measurement but I think that's enough for now. Try to keep benchmarks focused on real-world cases.

**Comment by AshleyScirra** [comment]
The Particles plugin has overhead to manage multiple particles. Instead of creating a particles object with 1 particle, just create a sprite, and you lose all the overhead of managing multiple particles per object. So there shouldn't be any reason to make multiple Particles plugins at all.

We're definitely interested in hearing about any performance regressions in the C3 runtime - it's just we probably won't do anything about them if there's no reason to do what the project does.
