### ISSUE TITLE
RegexReplace fails on firefox.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#1985]
## Problem description

Found a regex string to add seperators to numbers. Worked well in chrome but in firefox there was an error message. 

<img width="469" alt="screen shot 2018-09-04 at 09 20 54" src="https://user-images.githubusercontent.com/27011641/45016146-16a4a400-b024-11e8-9f40-39f3d69690f9.png">

Might be failing on NW.js as someone had problem described in this thread as well:
https://www.construct.net/mt/forum/construct-2/how-do-i-18/number-with-space-136985

## Attach a .c3p

https://www.dropbox.com/s/x5tfq6up8os4idh/regex_fail.c3p?dl=0

## Steps to reproduce

1. Open attached project in firefox
2. Run preview, and click to add to var.
3. Notice error message.

## Observed result

Error message is displayed.

## Expected result

Should work.

## Affected browsers

* Chrome: no
* Firefox: yes

**Comment by shortercode** [comment]
The regex you linked uses lookbehind, it's existed in some languages for a long time but hasn't in JS due to it's inherent complexity. I'm not particularly familiar with the syntax, as I've never used that feature of regex. I can't offer much help finding an alternative expression but this website is very handy [regexr](https://regexr.com/) for writing regular expressions.

Lookbehind is part of the ES2018 language proposal ( the javascript specification ) so I would expect some browsers to support it, but it's not a good idea to rely on it working in anything but the latest chrome.

Here's an article written by the V8 team when they launched the proposal for the feature, it does go into some of the details. I'm not sure if your particularly familiar with regex syntax but you might be able to create an alternative using lookahead ( which has much better support ).

**Comment by SnipG** [comment]
https://github.com/Scirra/Construct-3-bugs/issues/1741  there is example, and it works in mozilla. Replace string, to str with var
