### ISSUE TITLE
Keyboard input problem

### ISSUE THREAD

**Issue by Max19871** [Scirra/Construct-3-bugs#1993]
## Problem description

Keep down RIGHT ARROW + UP ARROW and pressing SPACE work correctly, but keeping down LEFT ARROW + UP ARROW and pressing SPACE, space keypress where not detected .

## Attach a .c3p
[KEYBOARD TEST.zip](https://github.com/Scirra/Construct-3-bugs/files/2351418/KEYBOARD.TEST.zip)

## Steps to reproduce

1. Keep down LEFT ARROW + UP ARROW
2. Press SPACE BAR

## Observed result

When LEFT ARROW & UP ARROW are down, pressing SPACE BAR result that trigger event with "On SPACE Press" detect nothing.

## Expected result

To detect SPACE BAR press action

## Affected browsers

* Chrome: yes

**Comment by shortercode** [comment]
Your hitting the key rollover limit of your keyboard, it physically cannot transmit that those keys are all active. My keyboard also has this issue, it's a cheap microsoft one. I tried one of the better keyboards in the office and it is able to report all those keys simultaneously without any issue. You can read more [here](https://gaming.stackexchange.com/questions/6669/how-do-i-remove-the-limit-on-pc-keyboard-button-presses).

As the article says you will often get better responses if you use WASD instead of the arrow keys, I can confirm this works better with my keyboard.

**Comment by Max19871** [comment]
I'll try later as you suggested with wasd, but it seems a bit strange to me that works with up + right + space and not with left + right + space. Moreover I use a laptop, no external/cheap keyboard. I admit to haven't tried wasd, using arrow key was a temp solution.

**Comment by AshleyScirra** [comment]
Yep, it's a hardware limitation. Take a look at this explanation: https://geekdroids.com/keyboard-ghosting-explained/

**Comment by Max19871** [comment]
Ok, as said I'll try to fix using the correct keys later this evening.

Thank you both!
