### ISSUE TITLE
Cannot SEE or USE Debug Mode - (Beta r116)

### ISSUE THREAD

**Issue by AlonDan** [Scirra/Construct-3-bugs#2020]
## Problem description
When running the application on Full Screen using Browser object (for NW.js use), the NEW C3 Runtime Debugger is showing super fast and hidden right away BEHIND the main full screen of the game.
in other words, it can't be use at all as it's under the game, unlike it supposed to work by default and split the screen in 2: TOP = Game, DOWN = Debug panel.

Please note:
I already reported this on the last release, Ashley claimed it is not a bug so I created a simple file and tested it on 2 different computers to make sure it is not just in a specific computer setup.
To be more helpful, this time I attached both: c3p file + MP4 to show the issue in action, I hope that this will help to understand, find and fix this bug, I would love to try the new debugger.

## Attach a .c3p
[Full Screen COVERS Debug Panel - BUG on C3 Runtime Beta r116.zip](https://github.com/Scirra/Construct-3-bugs/files/2366880/Full.Screen.COVERS.Debug.Panel.-.BUG.on.C3.Runtime.Beta.r116.zip)

## Attach .mp4 (video)
[Construct3__Fullscreen_COVERS__Debug_Panel__Beta_r116.zip](https://github.com/Scirra/Construct-3-bugs/files/2366953/Construct3__Fullscreen_COVERS__Debug_Panel__Beta_r116.zip)

## Steps to reproduce

1. Add Browser Object
2. Make an event to show Fullscreen on start of layout.
3. Try it on: C2 Runtime = It works fine.
4. Try it on: C3 Runtime = Watch the bug.

## Observed result

Cannot SEE or USE the Debug Panel since it's hidden UNDER the game screen on fullscreen mode.

## Expected result

Just like in C2 Runtime: supposed to split the screen in 2 parts by default: 
TOP = Shows the Game.
DOWN = Shows Debug panel.

## Affected browsers

* This bug appears when using the built-in NW.js 

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.28.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@5bae9719551562c019846c01a2d4b971add30f16) NWjs/0.28.1 (like Chrome/64.0.3282.140)
C3 release: r116 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 121 gb
Storage usage (approx): 649 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

The Clipboard API is not supported. Some clipboard features may be unavailable.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This only reproduces in the NW.js build and does not happen in the browser, which I think has been the source of some confusion. If the game requests fullscreen in debug mode, then the current situation is:

- Browser, C2 runtime: debug pane disappears
- Browser, C3 runtime: debug pane disappears
- NW.js, C2 runtime: debug pane remains
- NW.js, C3 runtime: debug pane disappears

So at the moment the fact the debugger remains visible when requesting fullscreen with the C2 runtime in NW.js is the discrepency. It makes sense to ensure it is consistent everywhere.

The simplest solution is to make the NW.js/C2 runtime case consistent with all the others (debugger disappears unless popped out to own window). Arguably this is also what some people will want when requesting fullscreen: it's to make the game take up the entire screen, but if the debugger remains, the game isn't taking up the whole screen anymore, meaning graphics are scaled and GPU profiling numbers won't be accurate to the fillrate required by fullscreen.

On the other hand we could make sure the debug pane remains everywhere, which means changing three of the four cases - but this might be tricky in the browser since it would mean posting a message to the debugger to go fullscreen, by which time the user gesture required for fullscreen is probably lost, so the fullscreen attempt will fail.

Not sure which way to go on this right now...

**Comment by AshleyScirra** [comment]
Given that NW.js/C2 runtime is the odd-one-out, and the fact it's currently difficult to forward a fullscreen request to another frame in the browser due to user-input restrictions, the next release aligns the NW.js/C2 runtime case to work like all the other cases (i.e. debug pane disappears). If you have a multi-monitor setup you can first undock the debug pane and move it to a different display, and still use it in fullscreen mode.
