### ISSUE TITLE
[Edge/Windows Store] can't select text. (r116)

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#2024]
## Problem description

Can't select text when editing expressions. You can select one word, but that's it. Both mouse and touch affected. Handle bars when using touch cant be used to extend the selection past one word.

## Attach a .c3p

N/A

## Steps to reproduce

1. Open any template project in windows store version.
2. Click an expression to edit it.
3. Use mouse or touch to make a text selection.
4. Notice that only one word can be selected.

## Observed result

Can't select multiple words or span of text.

## Expected result

Should be able to select multiple words or span of text.

## Affected browsers

*edge: yes

**Comment by AshleyScirra** [comment]
It looks like this was caused by the fix for #1876. I've changed the fix for that issue so that it doesn't break text selection in Edge, so should all be working in the next release.

**Comment by shortercode** [comment]
Just reviewing this change, this has changed how brackets are treated in respect to line breaks. I recall that I had a reason for not using the revised solution, but not why... Might have been the bracket behaviour but it's probably worth keeping an eye on this.

Incidentally the edge bug that caused this issue is apparently fixed in Edge 18 ( next month I believe? )
