### ISSUE TITLE
C3 Runtime Fade Issue: Fade does not work if Opacity set to 0%

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#2046]
## Problem description

C2 - Fade-in fades to 100% from 0% if opacity is initially set to 0%

C3 - Fade-in does not work if Opacity set to 0% 
(assume it is actually fading in to max opacity which is 0% so no fade-in)

## Attach a .c3p

[Fade Issue.zip](https://github.com/Scirra/Construct-3-bugs/files/2388523/Fade.Issue.zip)

## Steps to reproduce

Project has sprite set to 0% opacity and fade baviour disabled.
Fade Behaviour is set to fade in 1s wait 1s fade out 1s

Events: One event. On start of layout waits 1 second to start (enable) fade

Try with C2 runtime
Try with C3 runtime

## Observed result

C2 runtime box fades in fades out
C3 runtime no box appears

## Expected result

after 1 second box should fade in then fade out.

## Affected browsers

* Chrome: only tested

**Comment by NetOneGames** [comment]
to add.   I can see the conflict here .    What if we do not want to fade to 100% but want to start from 0% or other.    
The fade behaviour could probably do with another feild eg max fade level, different from the initial opacity of the sprite.

**Comment by AshleyScirra** [comment]
This is actually a small bug in the C2 runtime: the fade should fade-in to a maximum of the object's starting opacity, but due to an incorrect check, when the object's starting opacity is 0% it actually uses 100%. Changing this would probably break a bunch of C2 projects, and it's a small change, so instead I've implemented the same quirk for the C3 runtime.
