### ISSUE TITLE
IAP Purchase Problem

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct-3-bugs#2047]
IDC ABOUT BUGS.

**Comment by QuasarX** [comment]
#1966

**Comment by shortercode** [comment]
The plugin currently doesn't have a mechanism for attempting configuration a second time, `register product` and `complete registration` can only be called before registration is attempted. On iOS it will retry periodically to initialise the store, but Android does not do this yet. I'm undecided if manual reloading is preferable to automatic reattempts.

Also in terms of your implementation; you should only show the purchase options once you have successfully configured the product list. Apple in particular require you to use the product name and product description returned by the server instead of a hardcoded value within your application.

**Comment by shortercode** [comment]
You shouldn't need to detect an active internet connection. I need to make some changes to make the plugin trigger it's `registration failed` condition and come up with some solution to retry configuration.

**Comment by ERAgames777** [comment]
@shortercode 
Hi in the 119 version when making a purchase, writes: an error - the purchase is not available. In other versions, the purchase was made. I'm using C2runtime.

**Comment by QuasarX** [comment]
@shortercode Any ETA for this fix?

**Comment by QuasarX** [comment]
@shortercode Hi, half year have passed. Any ETA or plan for this fix?

**Comment by shortercode** [comment]
The bug was marked difficult because we didn't have a plan on how to easily resolve it at the time. There is a long planned overhaul for the underlying cordova component of MobileIAP which may resolve this issue. But given the complexity of it, and the expected implementation time it would require, it's quite low priority. Hence why this has been sitting with the difficult flag since last September.

**Comment by QuasarX** [comment]
It doesn't matter, idc about Construct 3 bugs. I won't waste my time to explain something to someone from Scirra. I'm trying to explain everything but I'm getting trolled. I'm writing steps, I'm recording videos... someone don't understand soo no more bug reports.

**Comment by shortercode** [comment]
As the original issue statement has been deleted by the OP I'm going to close this issue. For anyone else who is tracking this issue the upcoming update for this plugin should add automatic connection reattempt on Android.
