### ISSUE TITLE
Can't preview if no layout tab is open.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#2049]
## Problem description

I'm not sure if this is bug or intended but I find the behaviour a bit odd. Many times I close project tabs to not have too much tabs open. Especially finished layouts. Pressing Preview with no layout tab open and preview does not start.

## Attach a .c3p

N/A any template project will do.

## Steps to reproduce

1. Open any template project.
2. Close all Layout tabs.
3. Press Preview button. - Nothing happens.

## Observed result

Preview does not start if there is no Layout tab open.

## Expected result

I would expect Construct to use the layout from project settings- "First Layout". This setting does not seem to do anything when previewing. Optimal would be if "first layout" is used as long as you're in a project related event sheet.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes

**Comment by shortercode** [comment]
Given the preview button is actually "preview current layout", if there isn't one open then there's nothing to preview.

I've had a look at C2 and it will load the last active layout, even if it's closed. Do you think that or "preview project" is preferable?

**Comment by tunepunk** [comment]
I would guess the first layout in project setting is preferable. Usually I have to add events to all my layouts anyway to go to first layout, if I preview anything other than the first layout. Because often things are set or initialised on first layout.

**Comment by shortercode** [comment]
Okay so I've made a couple of revisions here. So if no layout is open it will now display the default layout for a project.

The second change I've made is add a new setting for the preview button called "preview action" this allows you to change it so the button will always preview the default layout instead of the active one. I figured this would be useful for you if your always redirecting back to the first layout anyway!

The setting is set for "active layout" by default, so that it's the same as the current behaviour. Preview layout is still an option on the dropdown.

**Comment by tunepunk** [comment]
This seems to work great in the latest release..... BUT.... a minor caveat.

If you have two projects open, it will always preview the last project you opened. I was thinking if you were editing an event sheet, or any other "file" (array, js, dictionary included) from project 1, and pressing preview it would preview that project. If you were editing an event sheet from project 2, it would preview that project.

**Comment by AshleyScirra** [comment]
Please file a new issue, the multi-project case is different to the original report.
