### ISSUE TITLE
Custom Importer API missing features or feature requests

### ISSUE THREAD

**Issue by lucidspriter** [Scirra/Construct-3-bugs#2051]
## Problem description
Families are not yet supported.
IWorldInstance has GetOpacity but no SetOpacity.
Add the ability to set Select Mode for IContainers

**Comment by AshleyScirra** [comment]
What capabilities do you need for a family? Just the ability to create a family with a specified list of members?

**Comment by lucidspriter** [comment]
Exactly.  

Ideally, it should be possible to create events for them as well, but that's just for future-proofing.  I don't have any immediate need for the events part.

**Comment by AshleyScirra** [comment]
Added the following for the next release:
- IWorldInstance.SetOpacity(o)
- IContainer.SetSelectMode(), GetSelectMode() (one of "normal", "all", "wrap")
- IProject.CreateFamily(name, members)
The class heirarchy has also been updated so that both `IObjectType` and `IFamily` derive from `IObjectClass`, and you can use an `IObjectClass` when adding conditions and actions, so you can create events for families too. This should cover everything mentioned here. I've updated the documentation already so I don't forget, but the APIs won't be available until the next release.
