### ISSUE TITLE
Preview with R119 throws some unexpeceted warnings with a capx file using c3 runtime

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#2063]
## Problem description

If you check the console when doing a preview in C3 runtime of the given capx file, chrome's console provides several unexpected warnings

## Attach a .c3p

It is actually the "localisation.capx" of this tutorial : https://www.scirra.com/tutorials/444/supporting-multiple-languages/revisions

## Steps to reproduce

1. Open the capx
2. Remove the webstorage plugin
3. Pass in C3 runtime
4. Preview and open chrome's console

## Observed result

Warnings 

loading-logo.png:1 GET https://editor.construct.net/r119/preview/loading-logo.png 404
index.html:1 Failed to load https://editor.construct.net/r119/preview/loading-logo.png: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://preview.construct.net' is therefore not allowed access. The response had HTTP status code 404. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
imageAsset.js:1 Failed to load texture:  TypeError: Failed to fetch
<details>LoadStaticTexture._texturePromise._texturePromise.GetBlob.then.catch @ imageAsset.js:1
Promise.catch (async)
LoadStaticTexture @ imageAsset.js:1
InitLoadingScreen @ canvasManager.js:1
_InitialiseCanvas @ runtime.js:1
Init @ runtime.js:1
async function (async)
Init @ runtime.js:1
self.C3_InitRuntime @ runtime.js:1
_InitDOM @ domSide.js:1
async function (async)
_InitDOM @ domSide.js:1
_Init @ domSide.js:1
async function (async)
_Init @ domSide.js:1
f @ domSide.js:1
(anonymous) @ start-preview.js:1</details>
index.html:1 Uncaught (in promise) TypeError: Failed to fetch 

## Expected result

Not sure if a CORS error should really happen during preview.
The missing textures to possibly not miss ?

Unless it is all specific to this capx ?

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
It looks like this fails in the c2 runtime as well, just less errors are printed to the console.

The issue is that the loading logo has been deleted from the project, in both cases the runtime seems to decide that in the absence of the file to try a normal network request instead of loading it from the editor.

Not sure if there's an actual problem here, it's going to fail anyway but I guess it could fail more correctly.

Going to assign @AshleyScirra to take a look at this, will leave it up to him.

**Comment by AshleyScirra** [comment]
It needs loading-logo.png in the project to be able to show the loading progress screen, but it's missing in the project so the fetch fails. The error is harmless, but I've adjusted the error handling so that case will not show anything in preview mode, and after export will log an extra message explaining that loading-logo.png needs to be added to the project.
