### ISSUE TITLE
IAP - error purchase is not available

### ISSUE THREAD

**Issue by ERAgames777** [Scirra/Construct-3-bugs#2065]
When you make a purchase action, the error window pops up - the purchase is not available. What I just did not try, the old versions of C3 work correctly and a window pops up with payment. I found this error in the 119 version of c2runtime.

The error that I see:
<img width="369" alt="1ebccd6aa312ee91" src="https://user-images.githubusercontent.com/33450672/45890492-882e7180-bddc-11e8-8edb-87edde85249b.png">

What should I see without error:
![google-play-launches-first-carrier-billing-in-africa-as-telkom-sa1](https://user-images.githubusercontent.com/33450672/45890598-ce83d080-bddc-11e8-8a81-b416d31df72f.png)

**Comment by shortercode** [comment]
The c2runtime version of the mobile IAP plugin hasn't changed since R97. Have you actually gone back and checked that it works in r118 now or is that just from memory?

By looking at your screenshots it would suggest that either that account already owns the product, or that there is some issue with your setup on the google play side.

**Comment by ERAgames777** [comment]
@shortercode 
I'm confused if I have a game hosted on GooglePlay and I release an update, then when I test the file, the purchase will not be found unless I update the update file on GooglePlay?

in 118 the purchase is working!
