### ISSUE TITLE
Loader layout enabled, c3runtime still displays default loader style while c2runtime does'nt.

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2073]
## Problem description

With C3runtime if you enable loader layout. Have almost nothing on it, with event: loader layout complete go - layout 1. It still shows default loader style, while c2runtime does not.

## Attach a .c3p
[LoadingC3.zip](https://github.com/Scirra/Construct-3-bugs/files/2409187/LoadingC3.zip)

## Steps to reproduce

1.Click Preview project(not preview layout). See loader layout for few frames.
2.Change runtime to c3. Preview project. You can see Loader Style(progress bar in this example) for few frames but not the layout.
3.Disable Use Loader Layout. Preview project with both runtimes.

## Observed result

C2runtime and C3runtime display loading different. C2runtime does not show default loader, while C3runtime shows it. 

## Expected result
Not sure how it should be, but c2runtime version seems to be better. C3runtime always tries to show default loader for few frames.

## Affected browsers

* Chrome: yes

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 69.0.3497.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
C3 release: r119 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 505 mb (3.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
As far as I can tell there is nothing wrong here. The issue is simply that you're using preview mode (so nothing really needs to load, it's all available locally), and the C3 runtime is faster at loading.

It's normal for the standard loader to appear even when you are using a loader layout. It actually uses two phases of loading: first loading the loader layout's images (showing standard loader), then loading the rest of the project's images (showing loader layout). If I artifically throttle the rate of loading, the C3 runtime correctly does both phases of loading. I think the C3 runtime loading is so fast in preview mode that in the time it takes to load the loader layout, it also finishes loading the rest of the project's images, so it simply skips the loader layout in preview mode. It still shows the standard loader while loading so this has incorrectly given you the impression it did not use the loader layout.

It's probably best to only test loader layouts on a local web server, and you might be able to configure it to be deliberately slow to test the loading time more realistically.
