### ISSUE TITLE
C3 runtime image memory issue (game crashing due to high img memory usage)

### ISSUE THREAD

**Issue by drg8** [Scirra/Construct-3-bugs#2094]
## Problem description
C3 runtime memory usage way too high than C2 runtime :(

when switching to C3 runtime the image memory is increased 4-5 times than that of C2 runtime. even tho it is estimated image memory usage, but it is making the game unplayable as it crashes instantly on mobile phone when remote previewing and even if I create an apk and then test it :( (_the sample file attached doesn't crash as it is using very less memory._).

**I'm also working on a project and have same issue and game does crash on mobile phones, but it is bit more confusing as the memory usage increases after switching to C3 runtime, but after restarting Construct 3 it is increased way more than it already has  @_@!?** 

1. default memory in C2 runtime :-84MB.
2. switching to C3 runtime :- 110Mb
3. after restarting Construct 3 while having C3 runtime selected earlier :- 297MB
4. switching back to C2 runtime :- 224MB**
5. again restarting Construct 3 while C2 runtime selected image memory drops back to:- 84MB

**the issues mentioned above doesn't appear in the sample file that I've attached, so let me know if you want to have a look at my project file and I'll provide the project file at support mail or any other mail, as I don't want to post it here as it will get stolen 💃**

I do want to use C3 runtime as it has better performance on mobile devices also my project is in its final stage(almost) and I want to publish is asap as I'm already way ahead of my deadline because of C2 runtime slower performance on mobile phone. 
I recreated the whole game again in C3 runtime as some addons didn't work in  C3 runtime, but unfortunately this new problem of image memory usage was waiting for me :( , so I'll be really nice if you can fix this issue as fast as you can :D.

## Attach a .c3p
[imgmemory_test.c3p](https://drive.google.com/open?id=1tL49CuiSA6M7auIx_QxRvEBOVqax-Rlt)

## Steps to reproduce

1. (C3 runtime is selected by default) run the debugger notice the image memory usage which is ~25.8MB

2. change runtime to C2 runtime

3. run the debugger and notice the difference. image memory will be ~4.2MB

## Observed result

C3 runtime image memory way too higher than C2 runtime.
## Expected result

image memory should be exactly same as shown in C2 runtime.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

Platform information
Browser: NW.js
Browser version: 0.30.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@004e06da11e10bb08f6632224ae48ee3d5f7b303) NWjs/0.30.0 (like Chrome/66.0.3359.117)
C3 release: r120 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 17 gb
Storage usage (approx): 6.1 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 1030 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The reason the provided project shows a different image memory usage in the C3 runtime is specifically because it uses the "C3 splash" loader style, and in preview mode the textures used for the splash aren't always released after the splash finishes. This is fixed for the next release, however it has a fixed cost of ~18mb so probably doesn't explain what is happening to your main project. Send it to ashley@scirra.com and I'll take a look. Based on the symptoms I suspect it is simply due to some tweaks in how the spritesheeting engine works with the C3 runtime enabled - specifically that the C3 runtime enables a larger maximum spritesheet size. This is trading off memory usage for improved performance, but if the memory regressions are that large then we can probably just put it back to what the C2 runtime was doing. If I have your project I can verify this is the case.

**Comment by drg8** [comment]
just sent an email with link to project file.

**Comment by drg8** [comment]
any updates on what's causing high memory usage in the project?

**Comment by drg8** [comment]
@AshleyScirra 

> any updates on what's causing high memory usage in the project?

**Comment by drg8** [comment]
I know you have lot of work to do but my intention was not to nag you to investigate the issue, as you said you'll verify to see if larger spritesheet size is the issue or not, so I just wanted to hear from you whether this can be fixed soon or might take some time so that I can patiently wait.
 
p.s. I deleted one comment and then tagged you in the next same comment (idk why I thought you might have not seen the comment), I guess that's why you might have thought that i'm nagging you ^_^! sorry for that.

**Comment by AshleyScirra** [comment]
I took a look at the project you sent me. It uses a ton of duplicated images. Construct does not deduplicate images in the editor itself, so all image memory measurements in preview/debug mode will include all duplicated images. However when you export you can tick "deduplicate images" and they all get removed. This makes a huge difference as it reports in the export stats:

> Image deduplication eliminated 259 redundant images, saving about 142 mb RAM

Based on exported projects with deduplication enabled, my measurements are:

C2 runtime export: 58mb
C3 runtime export: 87mb

The C3 runtime does use more memory, but it's still low enough that it should comfortably run on pretty much any mobile device.

So the main solution seems to be, just let Construct optimise the game for you.

I think the reason the C3 runtime uses more memory is a couple of spritesheets get bumped up to a 4096x4096 size. This is largely due to the use of a lot of spritefont images that are sized 2048x512. Power-of-two sizes are actually the least efficient memory-wise since Construct adds a 1px of padding around them on the spritesheet. If you can rearrange them to be more square and just under a power-of-two size, e.g. 1022x1022 or smaller, they will pack much more efficiently on to spritesheets and save even more memory.

Nevertheless this does demonstrate that the larger spritesheet size can result in higher memory usage, so I've reduced it back down to the same as the C2 runtime (2048x2048) for the next beta to ensure it doesn't cause increased memory usage for any other projects.

**Comment by AshleyScirra** [comment]
If you clone an object, it uses a separate, duplicated image of the original object. For example you have lots of SpriteFont objects using the same images. Those will be loaded in to memory as separate images in preview, but if you export and select "deduplicate images", they're all reduced to a single image for the exported project, saving memory.

**Comment by drg8** [comment]
:o , so not importing same images was the right choice.

any advice ^_^
> as you have tested the project is there any advice or pro tip you can give that might help me?
also I'm spawning few objects when enemies are destroyed, bullets are continuously spawned ( with other guns more bullets will be spawned really fast in few milliseconds), so any better way do the same without spiking the cpu usage and fps drops?
