### ISSUE TITLE
Rewarded videos on Android always fail to load

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-3-bugs#2131]
## Problem description

Rewarded videos always fail to load since the last patch, it may be related with last MobileAdvert patch, on friday (Oct 5th) rewarded videos still show, but from the past days they are always failing to load. I tested on Debug APK's and Signed APK's and got the same result.

## Attach a .c3p

TestAds.c3p renamed as zip
[TestAds.zip](https://github.com/Scirra/Construct-3-bugs/files/2462888/TestAds.zip)

## Steps to reproduce

Click on "Rewarded Video" and wait for reply from ads services

## Observed result

Rewarded video always fail to load

## Expected result

Rewarded video must show.

## Affected browsers

* Andoird : yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by MrWonka** [comment]
+1

**Comment by shortercode** [comment]
Your publisher ID hasn't been filled in. Is this the same as your actual project or did you just forget to fill it in?

**Comment by shortercode** [comment]
So I copied the pub ID from your app ID ( all the IDs contain the pub ID ) and put in a dummy privacy URL.

Testing like that it looks like your admob account is configured correctly for use with the consent SDK, so your project doesn't run in the EU at all. 

From the [mobile advert documentation](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/mobile-advert)

> 1. Go to the Admob console and select Blocking controls then at the far right EU USER CONSENT
> 2. Copy your publisher ID and paste it into the mobile advert Publisher ID property
> 3. Select the custom set of ad technology providers option, then on the select providers page choose up to 12 ad providers

To continue testing I enabled location spoofing and set it to "outside the EU" with this enabled I had no issues running the project and viewing all 3 advert types.

I have received several complaints about rewarded advert not showing, and the issuesall seemed to have solved themselves after a few days.

I had this issue myself when I overhauled the testing mode. I back tracked it to the SDK which was basically just not giving me an advert, with no explanation ( I think the message is something like "no advert to show" ). After 2 days passed the problem was gone ( no changes ) and I haven't had an issue with that unitID since. 

It's frustrating but I'm not sure what else to suggest except for be prepared for adverts not loading ( which you probably should be anyway, network issues are a thing ).

**Comment by sotano42** [comment]
I have this app in production and tested it in several devices and locations (including changing the network I connect from) and they always fail, although you suggested adding publisher's id this wasn't required before and rewarded videos still showed up in the past... it's really weird but the coincidence is that I got this error at the same time you guys uploaded the patch for mobile advert.

Today I'm still not getting rewarded videos to play (app in prd) so I managed to place an intestitial ad whenever it fails to guarantee monetization but the error still there... and btw, I can't minify mi games because the build fail to run in android (uncaugth exception) and geolocation plugin throws an exception if I don't use "is supported" condition first, I don't know if it may had something to do with this but I got all of these errors at the same time.

Anyway, I'll keep testing during the whole week to see if it solves itself and post you guys back.

**Comment by shortercode** [comment]
Both publisher ID and privacy URL should have been required since the GDPR update, I believe if you check you should be getting "is configured" as false. In the past we didn't require it, as the Admob SDK seems to work without it ( but I'm not sure what effect leaving it out has ). To meet GDPR requirements the "user consent SDK" was added that requires the publisher ID to work, hence why it's now needed.

The October the 5th patch wasn't ours, it was by admob. We use the latest version of all Google services ( such as admob ), so that we are in sync across plugins ( there's a special label for latest, it doesn't need any manual changes on our part ). We put out our own fix on Monday that changed the "latest" label to "16.0.0" for the mobile advert plugin ( which is the previous version ). That was the only recent change on our part to mobile adverts. If there's any service change it's on admobs side.

From my testing your advert unit ID seems fine when it's configured, so maybe they've put some restriction on the server that requires the pub ID? I don't know I'm afraid.

I've reviewed the code for the plugin and realised that we are not currently blocking adverts if configuration has failed, which we probably should be to match GDPR. Although I can see a lot of bug reports coming in if I turn that on...

As for the other errors I'm guessing your using r120. It has a minification bug ( unable to minify the system `int` expression ) that's already been resolved in r121. So try r121 and see if it fixes that. Otherwise file new issues for us please, it makes it hard to keep track of whats going on if you tack on additional bugs.

One bug per issue please!

**Comment by sotano42** [comment]
So I didn't change anything on my game and it started working again. Production game is now showing rewarded videos and I haven't made any release, so I guess is a google thing what causes this...

Thanks Ian, I know about just posting one issue just wanted to point things that may help.

**Comment by shortercode** [comment]
No worries, so long as we get your issues involved it's all good. It's generally better if we can avoid repeat issues though, as each one eats into our development time.

I've been talking to laura about maybe writing a new tutorial to help people with developing a game with adverts, hopefully if we can that done it will make things easier for people coming to the plugin for the first time.
