### ISSUE TITLE
Google Play Games Achievements & Leaderboards

### ISSUE THREAD

**Issue by MrWonka** [Scirra/Construct-3-bugs#2153]
## Problem description

I can get google play games to sign the player in, but then if I try to reward an achievement, submit a score or request a leader board nothing happens. 

## Attach a .c3p

[test.zip](https://github.com/Scirra/Construct-3-bugs/files/2478817/test.zip)

## Steps to reproduce

1. app shows up in google play games, showing that there are achievements and a leaderboard
2. app is released to closed alpha testing with users allowed to use play games
3. play games signs in, then refuses to do anything more.

**Comment by MrWonka** [comment]
Any update?

**Comment by sotano42** [comment]
Same problem here, I have an App in production and leaderboards doesn't load at all. Achievements in contrast work just fine. I also tested with an older application already deployed in production with an older version of construct and it works with no problem. So if you guys can have an update on this it will be really appreciated. (Problem just with leaderboards)

**Comment by MrWonka** [comment]
on build r125 this issue is still present.

**Comment by shortercode** [comment]
Apologies for slow response on this, fell to the back of the queue. Given the time since your initial report could you confirm to me that this is still an issue?

Incidentally you do not need to publish to alpha/beta channel for testing builds, it's possible to test debug/release builds that have been directly installed provided they are signed with your signing key.

I've just loaded up my testing project for the C2 runtime and it looks like viewing leaderboards/ submitting scores/unlocking achievements works correctly.

**Comment by MrWonka** [comment]
The issue is resolved

**Comment by shortercode** [comment]
Thanks for confirming @MrWonka
