### ISSUE TITLE
Incorrect X & Y position for sprite object when cropped. 

### ISSUE THREAD

**Issue by cjl014** [Scirra/Construct-3-bugs#2191]
## Problem description
I'll keep it simple. 
When you upload an image to the sprite object in "Animations Editor", then crop it, then go to the main layout page editor, you'll see the x & y position is way off. It may say 1000 instead of 250 for X position.

## Attach a .c3p
No time..

## Steps to reproduce

1) Create sprite
2) Enter "Animations Editor"
3)Upload an image
4) Crop it, 
5) Go to the Layout editor page
6) Move your object around and you'll see the numbers for x & y position is off.

## Observed result

Numbers for x & y position is off.

## Expected result

The object x & y position numbers to be right. It should match where the mouse points and shows the x & y position numbers.

## Affected browsers

* Chrome: yes
* Firefox: Don't know
* Edge: Don't know
* Safari: Don't know

## System details

N/A

**Comment by DiegoScirra** [comment]
The position of the mouse and the position of an instance will not match in most cases, unless the mouse is right on top of the origin of the instance.

If you drag from any other point other then the origin, the mouse and instance positions will always be different.

**Comment by DiegoScirra** [comment]
That is how the crop tool works.

In most cases when you crop you want the origin and image points to remain in the same relative place to which they where before the crop, so when the game is playing there won't be any difference other than the image being a different size.

Ej. You have a space ship image, with an image point on the tip, where the bullets will spawn. If there is some empty space in the image and you crop it, the image point will remain in the same place, at the tip of the ship, instead of changing position.

**Comment by cjl014** [comment]
Makes sense. Thanks.
