### ISSUE TITLE
ReflectY Effect behaves differently on C3 runtime vs C2 runtime - simplified example

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-3-bugs#2204]
## Problem description

My reflectY effect behaves differently between C2 runtime and C3 runtime. In the C2 runtime the background is reflected across the top line of the box sprite that is controllable via the mouse. In the C3 runtime, the background is not reflected across the top line, instead, it is offset. This is a simple effect, which is sampling the background and rendering based on a parameter passed into the effect. The parameter (0-1) represents how far up from the bottom of the viewport the top of the box sprite is. I removed the other effect to simplify the issue (and not require another effect / addon)

## Attach a .c3p

[ReflectYTest.zip](https://github.com/Scirra/Construct-3-bugs/files/2527348/ReflectYTest.zip)

[ReflectY.c3addon.zip](https://github.com/Scirra/Construct-3-bugs/files/2527358/ReflectY.c3addon.zip)

## Steps to reproduce

1. Install two addons in addons.zip
2. Install and run project
3. Move mouse cursor to move reflection box
4. Change to C3 runtime and observe different results from reflection box

## Observed result

Reflection box effect changes between C2 runtime and C3 runtime

## Expected result

The reflection box effect should appear to be the same between C2 runtime and C3 runtime.

## Affected browsers

Chrome: yes
Firefox: ?
Edge: ?
Safari: ?

## System details

Tested on both
Mac OSX and Win 10

<details><summary>View details</summary>

I suspect this is not an issue of the effect, it may be different behavior regarding the parameters that are being passed into the effect. Namely: 1-(Sprite5.Y-ViewportTop(0))/(ViewportBottom(0)-ViewportTop(0))

</details>

**Comment by shortercode** [comment]
Assigned to @AshleyScirra as he if responsible for the effects compositor. This is likely going to marked as difficult...

**Comment by AshleyScirra** [comment]
It looks like the effect depends on running in screen space to get the texture co-ordinates to work as expected (which makes sense for a reflection shader). Previously the C2 runtime always did a pre-draw step for anything marked as background blending, and the first bounce moves from object space to screen space as it draws to an intermediate surface. The C3 runtime has an optimisation where it can skip  the pre-draw stage for unrotated background blending effects, which improves performance but in this case causes the effect to render in object space since it hasn't had a pre-draw step yet, which given the way the shader is written results in the wrong texture co-ordinate calculations.

If you set `"must-predraw": true` in addon.json it restores the previous behavior and works as expected again in the C3 runtime, so that's your workaround. This is a compatibility difference between the runtimes, but given it's due to an optimisation for the C3 runtime that we want to keep, the solution is to alter the effect instead.

**Comment by MikalDev** [comment]
@AshleyScirra - thanks for the quick response, I will try that. One question - do you have any hints on how I might change my effect to use object space instead of screen space, so that the effect will keep the C3 runtime optimization of not doing the pre-draw?

**Comment by AshleyScirra** [comment]
The effect compositor is incredibly complicated. I'm not sure, I don't think so. Pre-draw is the way to go.

**Comment by MikalDev** [comment]
@AshleyScirra ok, thanks will go with just pre-draw.
