### ISSUE TITLE
Drawing Canvas Snapshot Coords does not line up.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#2209]
## Problem description

Getting the alpha from a snapshot position and the Coordinates does not seem to match what's shown.

## Attach a .c3p

https://www.dropbox.com/s/hguh2gs1xmr8bdj/snapshotcord.c3p?dl=1
## Steps to reproduce

1. Open Attached c3p
2. Move mouse around to get the Alpha value from snapshot. (shown in text)
3. Snapshot seems to be scaled up, compared to what's shown.

## Observed result

Snapshot is bigger than canvas area.

## Expected result

Should line up with the drawing canvas.

## Affected browsers

* Chrome: yes

**Comment by AshleyScirra** [comment]
We don't yet have documentation covering this so it's not immediately obvious, but the Drawing Canvas plugin defaults to creating a surface with the same pixel density as the runtime, while using the same co-ordinate system as the layout. Since the mouse position is in layout co-ordinates it does not map exactly to the canvas surface pixels.

The `PixelScale` expression gives you the scaling factor though - so in short if you take the offset in to the canvas in object co-ordinates, and divide it by the pixel scale, that should give you the surface pixel co-ordinates.
