### ISSUE TITLE
WindowHeight, WindowWidth behavior differs between C2 and C3 runtime (and OSes for C3 runtime)

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-3-bugs#2222]
## Problem description

WindowHeight, WindowWidth behavior differs between C2 and C3 runtime (and OSes for C3 runtime)

## Attach a .c3p

[WindowSizeTest.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/2536930/WindowSizeTest.c3p.zip)

## Steps to reproduce

1. Load project, set to C2 runtime
2. Debug layout
3. Observe WW and WH (WindowWidth and WindowHeight), resize window
4. Compare vs debug values of Canvas size.
5. close Debug layout
6. set to C3 runtime
7. Debug layout
8. Observe WW and WH (WindowWidth and WindowHeight), resize window
9. Compare vs debug values of Canvas size.
10. C2 runtime vs C3 runtime  behave differently (also in C3 runtime LayerToCanvas behaves differently depending on OS.)

## Observed result

C3 w/ C2 Runtime / MacOS / Windows:
- Window Width WindowHeight matches System Canvas Size dimensions listed in C3 Debug inspector
- WW, WH changes dynamically as preview window is manually scaled via mouse

C3 w/ C3 Runtime / MacOS:
-  WindowWidth, WindowHeight are fixed at Layout / Viewport sizes
    - Does not vary, does not match System Canvas Size dimensions listed in C3 Debug inspector.
    - Canvas size in debug inspector also does not match: LayoutToCanvasX(0, WindowWidth, 0), LayoutToCanvasY(0, 0, WindowHeight). The Canvas size in the inspector is 2X the LTCX/Y.

C3 w/ C3 Runtime / Windows:
-  WindowWidth, WindowHeight are fixed at Layout / Viewport sizes
    - Does not vary, does not match System Canvas Size dimensions listed in C3 Debug inspector.
    - Canvas size in debug inspector DOES match: LayoutToCanvasX(0, WindowWidth, 0), LayoutToCanvasY(0, 0, WindowHeight).

The reason this matters is I’m using a normal map effect and I need to pass in parameters to the shader for the location of the light on the layout (x,y) which I need to translate with LayerToCanvas and to scale the effect properly also, also need to pass in the overall canvas/window height and width.

There may be others way to do this (open to suggestions), but I am wondering why there is variability between C2 runtime, C3 runtime and OSes for WindowWidth/WindowHeight

## Expected result

WindowWidth and WindowHeight to behave the same between C2 and C3 runtimes and OS.

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: yes
## System details

Windows 10 PC
MacOS High Sierra

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
The WindowWidth/WindowHeight are confusingly named expressions which is one of the problems here. The name is vague and could probably be reasonably expected to refer to any of:

- the project viewport setting (previously referred to as "window size" in C2, renamed in C3 to avoid confusion)
- the current viewport size (per layer, e.g. ViewportRight(layer) - ViewportLeft(layer))
- the main canvas CSS size
- the main canvas device size
- the window inner size
- the window outer size

It turns out in C2, this ended up referring to the main canvas device size, which actually isn't very useful - it's basically viewportSize * letterboxScaleFactor * devicePixelRatio, which doesn't really correlate to anything you'd want to use in events. In C3 the expressions were changed to return the project viewport setting, but I guess by this point we're better off getting rid of these vague and confusing expressions and replacing them with something better.

The project's use of LayerToCanvas with WindowWidth/WindowHeight doesn't make sense even in the C2 runtime, because you're passing a size in device pixels to an expression that takes layout co-ordinates and converts them to CSS pixels.

Anyway, I've made a few changes for the next build to try and sort out this mess:

- added PlatformInfo expressions CanvasCssWidth, CanvasCssHeight, CanvasDeviceWidth, CanvasDeviceHeight (which are clearer names for these values)
- changed WindowWidth/WindowHeight expressions in the C3 runtime to return the canvas device size as they appear to do in the C2 runtime, for compatibility
- deprecated the WindowWidth/WindowHeight expressions in the C3 runtime to discourage using them - PlatformInfo.CanvasDeviceWidth/Height are better named if you really want that size, which you probably don't want anyway because they don't correlate usefully to anything in layout co-ordinates
- added new C3 runtime system expressions ViewportWidth(layer) and ViewportHeight(layer), essentially shortcuts for e.g. ViewportRight(layer) - ViewportLeft(layer), which gives you the size of the viewport in layout co-ordinates for a given layer - probably the thing you want to refer to in events

Hopefully that will finally sort this out!

**Comment by MikalDev** [comment]
Thanks Ashley for the quickly, this helps, yes it was confusing before.

I agree on the comment: "The project's use of LayerToCanvas with WindowWidth/WindowHeight doesn't make sense even in the C2 runtime, because you're passing a size in device pixels to an expression that takes layout co-ordinates and converts them to CSS pixels."

After I posted this bug, I changed that to use ViewPortRight, ViewPortBottom, which is what I actually wanted to do. I will look to change my C3 runtime code to use the new expressions

For my case with the normalmap effect (shader) which needs a light x,y  parameter (relative to the pixel being shaded) passed in what I think is final rendered space, so I think I may need to use the new Canvas expressions.  I will think about other possibilities, but the above works now for C2.
