### ISSUE TITLE
Can't open project - "duplicate animation name" & "Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project." -errors

### ISSUE THREAD

**Issue by JUlmanen** [Scirra/Construct-3-bugs#2277]
I was working on my game project yesterday and after I saved and closed the project, I was suddenly unable to open it anymore. Instead it gave me 2 different error codes in a small window when trying to open the project.

Here's the project:

[Inderell.zip](https://github.com/Scirra/Construct-3-bugs/files/2561627/Inderell.zip)

Steps to reproduce:

I tried to recreate the problem a few times with no results, sorry about it.

Observed result:

- When opening with a browser the error code is as follows: "duplicate animation name".
- When opening as a local file, the error code is as follows: "Failed to open project. Check it is a valid -Construct 3 single-file (.c3p) project." 

Affected browsers:

* Chrome: yes
* Firefox: yes

Site notes:

- I already tried to open the project with r119-r124, but none of them helped me with the situation.
- I tried to open the project on multiple computers with different browsers, with no results.

Thank you in advance!

**Comment by AshleyScirra** [comment]
The object `spr_armor1` appears to have two animations named "Animation 2". This should be impossible. I've recovered the file but without steps to reproduce the problem in the first place there is no way to investigate it, so it could happen again. Here's the file: 
[inderell-recovered.zip](https://github.com/Scirra/Construct-3-bugs/files/2562400/inderell-recovered.zip)
If you find a way to reproduce the issue please let us know - otherwise there is nothing else we can do about this, so closing.

**Comment by JUlmanen** [comment]
Thank you so much for your fast reply and for fixing my project so fast!
I'll try to figure out what caused the name duplication and will update here.
