### ISSUE TITLE
Bug/Crash - C2 Runtime Only plugins can still be added to C3 Runtime projects by custom importer drops

### ISSUE THREAD

**Issue by lucidspriter** [Scirra/Construct-3-bugs#2281]
If you drop a zip file into C3 that's recognized by a plugin using the Custom Importer API, then it will be added to the project even if it's a C2 runtime only plugin and the project is set to C3 runtime.  The editor will crash if you attempt to preview under these circumstances.

**Comment by AshleyScirra** [comment]
Since `AddDragDropFileHandler` does not directly reference the plugin or the runtime, the editor cannot currently make a decision about whether the plugin itself can be added to the project. Further, there may be use cases for this to be supported regardless of the runtime (notably the Custom Importer API sample does not actually add the plugin itself to the project, so can import regardless of the runtime).

I think the easiest solution is just to add `IProject.GetRuntime()` so the plugin can make its own decision about compatibility. This is added for the next release.
