### ISSUE TITLE
Colors in the C3 editor use the 0-255 range instead of the new standard of 0-100

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#2282]
## Problem description

Many places of the Construct 3 editor use the old 0-255 range.

This range does not align with the goal of r124. 

The new range is suppose to be 0-100 to fit with other ranges like opacity.

## Images that show the error

Color filter

![image](https://user-images.githubusercontent.com/5744908/48242075-950b3100-e42d-11e8-880c-02f388b42b4b.png)

Game properties

![image](https://user-images.githubusercontent.com/5744908/48242548-c553cf00-e42f-11e8-9412-739fcd5806aa.png)

Image editor, notice that the Alpha value is also in the wrong range.

![image](https://user-images.githubusercontent.com/5744908/48242476-86257e00-e42f-11e8-84f0-932dc21b6864.png)

**Comment by alastajj** [comment]
This error is also in the project properties.

![image](https://user-images.githubusercontent.com/5744908/48242373-0a2b3600-e42f-11e8-9361-bd1f4f0ffbba.png)

**Comment by alastajj** [comment]
This error is also in the image editor

![image](https://user-images.githubusercontent.com/5744908/48242421-3f378880-e42f-11e8-9d16-9ffefdc32e91.png)

**Comment by AshleyScirra** [comment]
Hmm, this is messier than I first thought. I think there are two separate cases here:

- image editing, which for better or worse still uses the 8-bit 0-255 scale, and the industry generally still uses that as a de-facto standard
- graphics programming, which almost always uses a normalized scale since the math works out better, and it avoids any precision issues from having `/ 255`, `* 255` everywhere

Construct's own image editor still uses 0-255, and I don't think we should change that, since it is the de-facto standard for image editors. If events are to be analogous to programming and the graphics programming standard is normalized then I'd prefer color expressions to follow that. However I think in practice the color expressions are used for both - e.g. adjusting color parameter effects (in a graphics programming style), or just for the color of a "fill rectangle" action in Drawing Canvas (in image editor style). So I think the easiest solution is to have the color expression both ways. So for the next release I've added rgbEx255 and rgba255 expressions which use the 0-255 range instead of 0-100, so you can have it both ways.
