### ISSUE TITLE
Tilemap problem on mobile.

### ISSUE THREAD

**Issue by ibiz3091** [Scirra/Construct-3-bugs#2297]
## Problem description

After you add a spritefont object to the project. tilemap is not displayed correctly.

## Attach a .c3p
[Tilemaps.zip](https://github.com/Scirra/Construct-3-bugs/files/2571804/Tilemaps.zip)

Beginner examples "Tilemaps"

## Steps to reproduce

1.Open project "tilemap" on mobile. (Iphone6, Samsung A5)
2.Add object spritefont in project.
3.look at the tilemap

## Observed result
tiles are distorted
Video: Watch until the end
https://drive.google.com/file/d/141KVS9pF11-gBI_2r72QDBkatDktpuKx/view?usp=drivesdk

## Affected browsers

* Chrome: yes
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

1. Samsung Galaxy A5 (SM-A520F)
Android 8.0

2. Iphone 6

<details><summary>View details</summary>

PASTE HERE
Video bugreport:
https://drive.google.com/file/d/141KVS9pF11-gBI_2r72QDBkatDktpuKx/view?usp=drivesdk
</details>

**Comment by ibiz3091** [comment]
@AshleyScirra Updated information

**Comment by SnipG** [comment]
Helping guy out, i had phone that could replicate this issue and that previous one he reported.

Phone samsung A3 2017 SM-A320FL
<details><summary>Phone details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.80
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Android
Operating system version: 8.0.0
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2.25
Logical CPU cores: 8
Approx. device memory: 2 GB
User agent: Mozilla/5.0 (Linux; Android 8.0.0; SM-A320FL) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.80 Mobile Safari/537.36
C3 release: r125 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 61 mb
Storage usage (approx): 47 kb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL 2 is currently disabled on Android due to reports of GPU driver bugs.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: ARM
Renderer: Mali-T830
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1024
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_sRGB
OES_element_index_uint
OES_standard_derivatives
OES_vertex_array_object
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc1
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
I can't reproduce any issue on a Pixel 3. It might be something to do with the precision of the GPU - when you add a spritefont its texture causes the tilemap to be moved across on the spritesheet, which might make it less precise in the tilemap shader. However I can't see any such issue on my own device and the provided system details for the Samsung A3 indicates it supports high precision calculations. So I'm not sure what to do about this...

@eleanorawesome - it's not at all clear that you have the same issue, this issue is specific to tilemaps and you did not mention them, so I assume it's unrelated. Please file a separate issue following all the guidelines if you have a non-tilemap related issue that you think should be investigated.

**Comment by ibiz3091** [comment]
@AshleyScirra good afternoon, I made a video for you. https://drive.google.com/file/d/1ndP-YUhEOydqlmfZSD5-hkAUlfKkwxZJ/view?usp=drivesdk

**Comment by ibiz3091** [comment]
I left C3p for you. https://drive.google.com/file/d/11ypAnd7os4Val95ua5CaZOBbRmdDv-1Z/view?usp=sharing @AshleyScirra

**Comment by AshleyScirra** [comment]
I dug through our Android device pile and it seems most devices aren't affected - I tried 5 before I found one that could reproduce the issue, a Samsung Galaxy Tab S2. I found that making sure tilemaps aren't combined on spritesheets works around the issue, which I think confirms the theory that it's to do with shader precision issues on specific GPUs. Anyway that seems to fix it, so it should be sorted for the next release.
