### ISSUE TITLE
Tween to wrong position

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#2313]
## Problem description

When using tween end position is often wrong.

## Attach a .c3p

https://www.dropbox.com/s/s1vxs5fob622z44/tween-fail.c3p?dl=1

## Steps to reproduce

1. Open attached c3p and run preview.
2. Click green boxes to tween to them.
3. Notice they are not always aligned.

## Observed result

Tween does not end up at the correct end position.

## Expected result

Should end up at exact position specified.

## Affected browsers

* Chrome: Not tested
* Firefox: yes

**Comment by tunepunk** [comment]
Happens in chrome also. Just tested

**Comment by Wackytoaster** [comment]
Can confirm this one. I had the same issue when developing my tween addon. This applies to all tweening (also value tweening). The tween should guarantee to end at the specified value.

Very interesting results also happen if you set the tween duration to 0.01 or 0. In both cases the object should imo end at the expected position, except with 0 it doesn´t move at all and with 0.01 it straight up vanishes (to some position offscreen)

**Comment by bilgekaan** [comment]
+1

**Comment by DiegoScirra** [comment]
This should be fixed in the next release.

I ended up removing the "Allow Multiple" option. It really doesn't work with absolute interpolation and it just ends up being confusing.

The one thing you should watch out for now, is that each time a new tween is started, if there is a similar one running, the old one will be stopped and then the new one played after it. This has 2 subtle effects:

1) The easing function is applied again from the beginning.
2) The time starts again from the beginning.

Check it out in the next release.

**Comment by AshleyScirra** [comment]
r126 is now out, please check again!

**Comment by tunepunk** [comment]
Can confirm. Behaves much better now. Thanks
