### ISSUE TITLE
Changing Array Settings in Array editor Crashes C3.

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#2373]
## Problem description

When changing the Array settings (widht, height) Crashes construct.

## Attach a .c3p

N/A

## Steps to reproduce

1. Create a new project.
2. Right click on file, to create a new array.
3. In the Array editor, change width to something else and hit enter.

## Observed result

Construct Crashes

## Expected result

Should not crash.

## First affected release

Worked in 125, broken in 127.

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r127/components/editors/dataEditor/dataEditor.js, line 1, col 33508
Message: Uncaught TypeError: Cannot read property 'ǃflo' of null
Stack: TypeError: Cannot read property 'ǃflo' of null at Object.ǃfEr (https://editor.construct.net/r127/components/editors/dataEditor/dataEditor.js:1:33508) at e (https://editor.construct.net/r127/components/editors/dataEditor/dataEditor.js:1:31637) at Object.ǃdp (https://editor.construct.net/r127/components/editors/dataEditor/dataEditor.js:1:32002) at Array. (https://editor.construct.net/r127/components/editors/dataEditor/dataEditor.js:1:26782) at Object.ǃfLj (https://editor.construct.net/r127/main.js:2:204627) at Object.dispatchEvent (https://editor.construct.net/r127/main.js:2:202662) at Array. (https://editor.construct.net/r127/components/editors/dataEditor/dataEditor.js:1:1411) at Object.ǃfLj (https://editor.construct.net/r127/main.js:2:204627) at Object.dispatchEvent (https://editor.construct.net/r127/main.js:2:202662) at Object.ǃJH (https://editor.construct.net/r127/main.js:2:270001)
Construct 3 version: r127
URL: https://editor.construct.net/r127/
Date: Tue Nov 27 2018 14:05:36 GMT+0100 (Central European Standard Time)
Uptime: 5465 s

Platform information
Browser: Chrome
Browser version: 70.0.3538.102
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.14_1
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1.7999999523162842
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
C3 release: r127 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: ATI Technologies Inc.
Renderer: AMD Radeon Pro 560 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Are you sure it was introduced in r127? I can reproduce this in r126...

r126 introduced a fairly major change to the array editor, by separating selection from editing. There's a batch of bug fixes for the array editor due in r128.

The bug your suffering from here is when enter is hit when no cell is selected it causes a crash. It's a pain but you can work around it by just selecting a cell after changing the height instead of using enter.

Incoming bug fixes for the array editor:

- Crash when pressing enter when no cell was selected
- Undo of cell edit could sometimes leave behind the first letter
- Redo of row or column insertion/deletion could scramble the locations of cell edit undo/redo
- Undo would not unselect the current cell if it was removed ( causing potential crashes )

**Comment by tunepunk** [comment]
Sorry. Should say 125, not 126... a bit fast typing there...

**Comment by shortercode** [comment]
No worries, just checking that there wasn't something else hiding there...

I'm going to close this as it should be fixed in the next release. Thanks for the report anyway, I managed to catch it first this time but that doesn't always happen!

**Comment by tunepunk** [comment]
Another thing, not sure if it's a bug or not. After changing the cell sizes, the width of columns is not stored for example, so it's pretty annoying next time you open project having to change the cell sizes every time. Should I file this as a bug of feature request?

**Comment by shortercode** [comment]
Sorry I hadn't seen your previous comment, just looking back through a few recently closed issues.

So yeah... I'm aware of this. There's currently nowhere to store the column/row sizes, which is why it's not implemented. We'd probably need some additional project file that holds the information related to basic project files. I'll think on it. Feel free to file it as a issue ( can be pretty minimal ). I'll pick it up when it appears.
