### ISSUE TITLE
Replace color is leaving color artifacts on text even with 100% tolerance.

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#2374]
## Problem description

If you combine a text object (which is very useful since you can use fonts like Arial with support for special characters and language symbols, unlike spritefonts) with the replace color effect it will not work as intended. The replace color will leave color artifacts even in 100% tolerance. Here’s the results of my tests:

In engine text render: https://i.imgur.com/YY0bq0B.png 
Pre rendered text (+aa): https://i.imgur.com/YYa8hJJ.png 
Pre rendered text (no aa): https://i.imgur.com/SrMQn8H.png 

This is probably not a bug, just a limitation, but the end results are very “ugly”, however i do have an easy solution to suggest. In my game i’m using pixel art graphics combined with high res text (screenshot: https://i.imgur.com/yjLfktt.png) and the result are also bad, but if you add a simple tick box that allow the developer to disable text aa this can be easily fixed. Photoshop already have that option (Screenshot: https://i.imgur.com/URnpPn0.png).

## Attach a .c3p

[Text AA.zip](https://github.com/Scirra/Construct-3-bugs/files/2620328/Text.AA.zip)

## Steps to reproduce

1. Just execute the project.

## Observed result

The final render have many color artifact around the text.

## Expected result

An option to disable text aa and avoid the artifacts.

## First affected release

Every release have this problem.

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The problem is you're running a "replace color" effect over a pre-rendered alpha-blended image. The soft text edges are achieved with alpha channel semitransparency. Once the text is drawn to the layout, the soft-edges opacity is "baked" in to the background color, becoming opaque with a color gradient. Then you run replace color over a very small gradient. I suspect this cannot mathematically produce the same result as having changed the source and destination colors when performing the alpha blending. The example seems very contrived as well; why not just change the layer color and the text color directly instead of using "replace color"?

Further, as noted in https://construct3.ideas.aha.io/ideas/C3-I-641, an option to disable text antialiasing is not currently possible, although you can use the alpha clamp effect to sharpen the soft edges.
