### ISSUE TITLE
mobile browsers use CSS Viewport instead of their real resolution

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#2376]
## Problem description

Browsers on mobile devices use CSS viewports instead of their screen's resolution.

For example a samsung galaxy S4 has a screen resolution of 1080x1920 but a CSS resolution of 360x640

So using anything other than a 360x640 or 180x320 viewport will end up with huge letterbox bars on the screen. Since mobile screens are small already this is a huge problem. 

Also, any device that isn't using a perfect 16:9 ratio will get huge letterbox bars too.

The issue is that CSS resolutions are so low that pixel art games will only scale by a factor of 1x or 2x at those low resolutions, but a lot of the time it will stay at 1x because it does not have a perfect 16:9 ratio and not take a lot of the screen space

## Attach a .c3p

https://puu.sh/C8Fs2/0d3ebefd1d.c3p

## Steps to reproduce

1. Preview the project
2. Open the browser console with Ctrl+Shift+J
3.Open the Device toolbar
![image](https://user-images.githubusercontent.com/32940085/49108182-81493280-f255-11e8-826e-6b3657307bb1.png)
4.Using the Device Toolbar, check multiple devices's resolutions

## Observed result

![image](https://user-images.githubusercontent.com/32940085/49108239-b05fa400-f255-11e8-8350-e70ab82d3d91.png)
The device's resolutions use CSS resolutions which are super small and break integer letterbox scale

## Expected result

I mean I don'T expect anything different but I expect the games to use pixel resolutions for integer letterbox scaling not already scaled CSS resolutions

## First affected release

all
## Affected browsers/platforms

All mobile browsers

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.102
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
C3 release: r127 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 464 mb (2.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by eleanorawesome** [comment]
Which means scale outer has to be used and that'S kind of weird

**Comment by AshleyScirra** [comment]
Construct already uses device pixels, not CSS pixels, for calculating the size for letterbox integer scale. In your example, using a Pixel 2 XL in landscape mode, the calculation happens as follows:
- viewport is 640 x 360
- window inner size is 823 x 411 CSS pixels
- devicePixelRatio is 3.5, so the window inner size is 2880.5 x 1438.5 device pixels
- the viewport fits ~4.5x horizontally and ~3.99583x vertically
- unfortunately it doesn't quite clear 4x vertically so chooses 3x scaling
- the resulting canvas size is 1920 x 1080 device pixels. Note this is based in display pixels, not CSS pixels.

This calculation is carried out correctly by Construct, given the information the browser provides it. The problem here seems to be that the browser has calculated the window inner size by rounding down the conversion to CSS pixels. The real display is 1440 pixels, and 1440/3.5 is ~411.429, which it appears to have rounded down to 411. When Construct scales this back up to device pixels it gets 1438.5; even if this was rounded up to 1439 it still cannot fit 4x scaling because it's 1 device pixel too small. In other words, the browser is telling Construct the window is slightly smaller than it really is. This should only happen on specific devices where the screen size divided by devicePixelRatio is not integral.

I've added a workaround for the next release that just adds 1 to the window inner size in CSS pixels :P I don't think we can do better, since it's impossible to determine the real window inner size in device pixels without rounding having been applied. Anyway, this looks like it sorts out the devices that are affected.
