### ISSUE TITLE
LayerToCanvas not returning correct values?

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#2394]
## Problem description

Was playing around with this system expression and I did not get the values I expected. Either this is by design or a bug, but I had to create my own scale rate in order to place objects at correct positions.

## Attach a .c3p

https://www.dropbox.com/s/n5ht2y4h66zrhet/canvas_scale.c3p?dl=1

## Steps to reproduce

1. Open attached project.
2. Preview and rotate with left arrow. position is offset, based on the scale of the window. 
3. Scale the window to see the effect.
4. In event sheet, enable the action that set the Scale global variable.
5. Run preview again. (this is how it should look)

## Observed result

Placement seems to be offset based on window width.

## Expected result

Should be aligned no matter how much the window scales.

Suggested, it would be good if the window scale is taken in to account, or if there were a system expression to get the current scale rate.

**Comment by AshleyScirra** [comment]
LayerToCanvas converts from layout co-ordinates to canvas CSS co-ordinates. The viewport size is in layout co-ordinates, so an expression like `CanvasToLayerX(0, OriginalViewportWidth, OriginalViewportHeight)` is incorrect because it mixes different units. In other words, it makes no sense to position something in the layout using canvas CSS co-ordinates. In particular, letterbox scale mode keeps the visible area in layout co-ordinates the same, while changing the canvas CSS size. I checked the expression descriptions and they are slightly misleading though - it talks about "screen" co-ordinates, which isn't quite right. I've changed the description for the next release to clarify that the expressions convert to and from canvas CSS co-ordinates.

**Comment by tunepunk** [comment]
I see, but in this case I tried to add HUD elements on a seperate Layer, that places itself correctly on a rotated Layer. This was the only solution I could come up with since there is no other way to ge the Absolute Sprite position on the rotated layer.... When a layer is rotated all sprites retain their X.Y coordinates on the rotated layer, and I can't get their screen space XY coordinates another way.

**Comment by AshleyScirra** [comment]
If you're trying to undo the rotation of a layer, shouldn't you just place them on an unrotated layer instead?

**Comment by tunepunk** [comment]
No the game map can be rotated (Layer 1). But on Layer2, I have my HUD elements (that don't rotate). This is where the Blue sprite2 is placed. I want to place this blue sprite on top of the Sprite in the Rotated layer. So that's why I used LayerToCanvas, because there was no other way to get the the absolute position for the objects on Layer1. 

If you check the example again You'll see what I'm trying to do. The blue has to place itself precicely on top of the red sprite on layer1. I found the solution, but found the behaviour of the LayerToCanvas, a bit odd. 

When I layer is rotated, the XY remains the same for all objects in that layer. And there's no "Absolute" position for objects. 

Anyway.. My solution worked, but filed a bug, just in case because I found it odd that this was the only way I could achieve what I wanted.
