### ISSUE TITLE
Input '*' error when changing Viewport size 

### ISSUE THREAD

**Issue by AmateurX-14** [Scirra/Construct-3-bugs#2409]
## Problem description

on any PROPERTOES Input box, 

Example value:  854 x 480

**_Select all_** and input  'n\*m', 
it will discern ‘(854 \* n)  x 480’, but is not cover  'n*m'
 (n, m is any number)

## Observed result

Viewport size /  LAYOUT Size / Gird size

Viewport size:  854 x 480

Select all and **Input '1920*1080'  error: 100000 x 480**

Select all and Input '1920x1080'  work: 1920x1080
Select all and Input '1920,1080'  work: 1920x1080
Select behind 854 and Input '854*2,480'  work: 1708 x 480

## Expected result

Select all and **Input '1920*1080'   work: 1920x1080

**Comment by AshleyScirra** [comment]
This is by design so you can enter calculations in to number properties. Typing * therefore does a multiplication; the `x` or `,` characters are separators for the different values. So if you want to enter two values, type a `x` or `,` character; if you want to do a calculation, type a `*` character.
