### ISSUE TITLE
Sprite animation speed vary based on framerate

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#2421]
## Problem description

The sprite animation speed vary based on their framerates 
## Attach a .c3p

https://puu.sh/Cf6ls/52170c12bb.c3p
## Steps to reproduce

1.preview the project

## Observed result

The sprite that uses construct 3 animation speeds won't drop frames and will always display the next frame 
## Expected result

for the animation to take the same amount of time to complete regardless of the framerate
## First affected release
all of them probably

## Affected browsers/platforms

all of them

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 70.0.3538.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
C3 release: r129 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 541 mb (3.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I think this is just because sprite animations don't run catch-up frames, i.e. they advance a maximum of one frame per tick. This is currently by design and mentioned in the manual (that you can't set an animation speed higher than the framerate, because it will only advance one frame per tick). Also changing this would actually be a breaking change, since someone with an animation speed of 1000 would currently get it advancing one frame per tick, but with catch-up would suddenly go much faster and possibly affect gameplay logic too.

This should only ever happen if a tick takes longer than the duration of a frame, which I think only happens in the example because it's based on quadissueperf and that occasionally creates thousands of objects in a single tick, which makes it quite a contrived example. Also the sprite uses animation frames which are doubled up with a doubled animation speed (presumably to demonstrate the issue?), using a normal approach with single frames and a lower animation speed would make this less likely to happen.

**Comment by eleanorawesome** [comment]
The issue was raised because if game object'S behaviors depend on their animation frames there might be inaccuracies/de-synchronizations in online multiplayer games
