### ISSUE TITLE
Petition!!! colors in event list, for visual simplicity!!! :D

### ISSUE THREAD

**Issue by lxstkid** [Scirra/Construct-3-bugs#2422]
Hi, I would like to request that a color function be implemented for the list of events, for which we have vision problems or difficult to read a long list of events.
this function would automatically put colors in the events and actions.
helping to quickly locate the part of the code we are looking for when we have many events.
this would also serve for education, other programs work like this. An example ; scrath:

https://ibb.co/m9ZZV96

I do not request to change or select the colors, what I ask is a default configuration inside construct 3 that automatically gives the events the predetermined colors.
This would also be very useful when you read a .capx file from another person and try to decipher it.

I hope this request is liked and carried out.

thanks!!

**Comment by CureUnlovely** [comment]
I know this isn't completely relevant, but I feel like it might belong here more than in a new thread. Can I request that we can set "alpha blend mode" of an object to a specific COLOR rather than just the current blend mode options given (like XOR and stuff, which honestly don't make sense to me as to what they are). Game Maker has this option. :)
Or better yet, have an option for "flash" that makes the object flash in a color rather than making it invisible and visible again?

**Comment by NoSoul8** [comment]
If it is to be applied - make it optional pls. I'm totally fine with dark theme. Myself (and some other indie devs) have to make games during night, and those multicolored events are the last thing i want to see.

**Comment by lxstkid** [comment]
I am sorry if I do not express myself well in English, this would be an option that could be activated or deactivated, according to the needs.
for those of us who have visual problems or who have trouble finding a long list of events

**Comment by AshleyScirra** [comment]
Please post suggestions to https://construct3.ideas.aha.io/

**Comment by lxstkid** [comment]
sorry ashley
