### ISSUE TITLE
Mouse sprite cursor issue in runtime C3

### ISSUE THREAD

**Issue by ArtRow** [Scirra/Construct-3-bugs#2475]
## Problem description

Mouse custom cursor works with dealy in C3. 

## Attach a .c3p

There are .c3p file and video with explanation in details.
[Issue C3 mouse cursor sprite delay.zip](https://github.com/Scirra/Construct-3-bugs/files/2710687/Issue.C3.mouse.cursor.sprite.delay.zip)

## Steps to reproduce

Just run project with C2 and C3 runtimes and compare how they work.

1. Open project
2. Run with C2
3. Run with C3

## Observed result

Cursor is being changed to a sprite with delay in C3. And also we are going to another layout, we see old cursor sprite for a few time (about 0.1 second). In C2 it works pefect.

## Expected result

Fast work with C3 as it is with C2.

## First affected release

It was also in previous stable version, before 

## Affected browsers/platforms

* Chrome: yes

## System details

Windows 7, 10.

<details><summary>View details</summary>

No details

</details>

**Comment by AshleyScirra** [comment]
This is because of the new architecture of the C3 runtime: the engine is decoupled from DOM updates to allow it to run in a worker.

There's no clear workaround to this, and since it should not cause any perceptible issues to the user (the report does not mention any direct negative effects that result from this other than a delay within the threshold of perception of instantaneous), closing as won't fix.
