### ISSUE TITLE
The "iFrame" 

### ISSUE THREAD

**Issue by OutlandPictures2** [Scirra/Construct-3-bugs#2477]
## Problem description

When I try to insert an iFrame into one game that I ported over from C2, it does not allow me to do it.

The iFrame icon does not even appear in the CREATE NEW OBJECT TYPE pop-up (under form controls, where it normally shows up). It's like the editor is deliberately blocking me from adding iFrames.

I can open other projects and the control for iFrames is there.  So I know it's not my setup or my versions of C3.  It's something else where the editor is not allowing we to use iFrames for this file. 

Note - I used iFrames in C2 in this game using the HTML_PODE iframe plugin, but I stripped that out when porting over this game to C3.

That said, I stripped everything out of the project until it was almost empty, and it STILL won't allow me to add an iFRAME.  I've attached that stripped out project. 

## Attach a .c3p

[Unable_to_add_an_IFRAME.zip](https://github.com/Scirra/Construct-3-bugs/files/2715074/Unable_to_add_an_IFRAME.zip)

## Steps to reproduce

1.  Open the attached c3P project. 
2.  Try to add an iFrame
3.  You won't be able to. 

## Observed result

The controls for adding an iFrame are blocked.

## Expected result

Simple adding of iFrame, as works in other projects. 

## First affected release

r131.  I never tried an earlier release for this. 

## Affected browsers/platforms

Chrome YES. 
Others UNKNOWN.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Wackytoaster** [comment]
Your project is set to use the c2 runtime. The new iframe plugin only works in he new c3 runtime. Since you ported your project from c2 it is automatically set to the c2 runtime while new projects have the c3 runtime as standard.
![to3w3cp](https://user-images.githubusercontent.com/31101309/50537442-de3f4d80-0b5f-11e9-98a0-4c822d583ac7.png)

I also confused this in the beginning and I have the feeling this will keep happening and be reported as bug for a while. Maybe as an idea for scirra: Show all the c3 runtime only plugins greyed out with a visible info somewhere that you have to switch the runtime.

**Comment by OutlandPictures2** [comment]
That solved it.  You rock!   Thanks.

**Comment by shortercode** [comment]
Thanks for the assist @Wackytoaster and the excellent answer.

Your suggestion about showing the icons greyed out is interesting, I think perhaps a label at the bottom of the list might be better though ( reduces the amount of on screen content ). We could also do the same when simplified mode is enabled, as some people have been confused about hidden plugins while using that.

@OutlandPictures2 you may find this [guide on importing C2 projects](https://www.construct.net/en/make-games/manuals/construct-3/tips-and-guides/importing-c2-projects) useful.
