### ISSUE TITLE
PROBLEM WITH ANDROID 5.0 AND 6.0

### ISSUE THREAD

**Issue by idjer83** [Scirra/Construct-3-bugs#2510]
Good day! I use the stable version of construct 3 (runtime). When exporting the game to android (cordova), I use the signed apk file version 5.0. My phone has android version 6.0, the game does not work, gives an error, tested the game on android 7.0, everything worked well. How to make the game work on all android 5.0? Sorry, I can not put a screenshot here.
https://play.google.com/store/apps/details?id=com.camolet_03

**Comment by idjer83** [comment]
![1](https://user-images.githubusercontent.com/46623319/51072540-6dc22180-1673-11e9-9afc-65d52f03f424.png)

**Comment by SnipG** [comment]
For reporter: https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en_US

Software update needed
Webview - https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en_US
Chrome - https://play.google.com/store/apps/details?id=com.android.chrome

After tens of issus like this. And to consider they are devs. There should be link to webview android store.
If casual kid, older  or not english speaker saw this, they would pick next game. Every phone/User converted will help all Construct devs, light should guide them.

I also have seen huge amount issue reports in  Crbugs, where webviews are just disabled somehow. So even if webview high enough, update could only do good.

**Comment by idjer83** [comment]
Мои действия:

1 I do project properties
![default](https://user-images.githubusercontent.com/46623319/51086767-c371f900-175b-11e9-9986-8f26992baba3.png)
2 Made a project, 1 layer background, second player without behavior
![default](https://user-images.githubusercontent.com/46623319/51086778-d4226f00-175b-11e9-9840-8c9e99fa3a64.png)
3 I do export 5.0, I create the signed key. Password is the same everywhere.
![default](https://user-images.githubusercontent.com/46623319/51086799-eef4e380-175b-11e9-83c7-eb8c276d9a35.png)
![default](https://user-images.githubusercontent.com/46623319/51086802-f3b99780-175b-11e9-8374-6d8895b6b708.png)
![1](https://user-images.githubusercontent.com/46623319/51086806-f5835b00-175b-11e9-8979-cc688a1f8d5d.png)
4 file is ready
![default](https://user-images.githubusercontent.com/46623319/51086810-0fbd3900-175c-11e9-93d9-67e984911803.png)
5 Загрузить в мой блог и загрузить на телефон kvest1.at.ua/load/1-1-0-3
![default](https://user-images.githubusercontent.com/46623319/51086816-1b106480-175c-11e9-80d5-2c04cf3cd6e6.png)
6 проблема
![error2](https://user-images.githubusercontent.com/46623319/51086818-2499cc80-175c-11e9-8f9e-e0d1983d7739.jpg)
7 NOX player программа для Android 6.2
![default](https://user-images.githubusercontent.com/46623319/51086823-2fecf800-175c-11e9-89ba-706d9c1f1c43.png)
Tried to do export in the stable version and betta version.

I do a test on the phones

Qysters android 6.0 updated, all new costs https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en_US
Huawei android 6.0

Tablet Huawei android 6.0

Samsung version I do not remember.

Please deal with the problem, I have been suffering for 2 weeks

**Comment by Silversen** [comment]
Hi.. I assume your post will closed immediately because not following their guideline.

Anyway this is clasic problem.. your android phone not supporting webgl which is needed for Contruct 3 generated APK

**Comment by idjer83** [comment]
I do not understand you well. Translation done in Google translit. There are many games created in construct 3 that run on my phone. But my game doesn't start. In the screenshots above, I tried to show what I was doing wrong? The game above does not work on other phones, wrote above. The same test game also does not work. Updated web browsing.

**Comment by SnipG** [comment]
That samsung-g955n is samsung s8+. It should support webgl and construct 3 by factory settings.

Problem here might be some phone versions, ones for india/china/korea has some own default browser or samsung internet browser, that is out of date.

Best is if you upload your example. Add c3p  to .zip and drag it here.

Or check if there are some other browsers that phone uses and update thous.

**Comment by AshleyScirra** [comment]
The error message only appears if the device's software is 2+ years out of date. I assumed that the majority of devices would be at least reasonably up-to-date. If this is not the case then unfortunately there's nothing much we can do about it. Many of the improvements in the C3 runtime are solely because we are using modern browser features. If devices have software which is long out of date, we simply can't support them without removing many improvements in the C3 runtime, which we don't want to do.

If you have to publish your app in a market where, for some reason, lots of customers have ancient software with updates disabled, I'm afraid the only feasible option is to continue using the C2 runtime.

**Comment by SnipG** [comment]
Its not just ancient software - its also cheap and how stores operate. If i go local online e-store, list phones by price i can easily buy phones with android 5/6 etc. There are countless phones brand, not just top 5-6 brand. You never know the default browser version and if users will update them.
Also e-stores sell phones from new to 4-5+ year olds. 
More around the corner shops you go, the older the brands are.

There should be just some "easy" solution to get users to update/change/use correct stuff. Each of them just has to do it once. Like internal android pop-up message, insisting to update/change/modify browser or app. So they know its their problem not app - results user to"asking parent, son  or relative to fix it".
If apps are wrapped to chrome, so should chrome internal stuff  do the asking/update/pop-up window logic. 
When phone is resetted alot of default apps request stuff, chrome wrapped apps could and should do it somehow, and that would be nice. But it could be hard to implement something like it.

**Comment by AshleyScirra** [comment]
It's not to do with the Android version. Any version of Android 5.0+ is supported (which is now over 90% of devices). However they must have an up-to-date Android System Webview (on Android 5-6), or an up-to-date version of Chrome (on Android 7+). It sounds like this only affects Android 5-6 devices, since I assume most Android 7+ devices use Chrome as their main browser and so are kept up-to-date via the app. Still, I assumed the Android System Webview was automatically updating as well (indeed that is the point of making the system webview a Play Store app, so it can update independently of Android and track the Chrome version). However it seems sometimes the webview is literally years out of date, and why this would be the case is still something of a mystery.

If this has never been observed on Android 7+, maybe we could at least target the error message to the Android System Webview only - it mentions Chrome as well to cover Android 7+ but that seems to not be an issue by the sound of it...

**Comment by AshleyScirra** [comment]
Also it looks like Android 7+ now covers around 60% of devices, so even if we can't figure this out at all, it should fix itself over time as updates propagate and that proportion of devices becomes the vast majority - much like the Android 5.0+ requirement has now become pretty much ubiquitous.
