### ISSUE TITLE
Persist behaviour bug

### ISSUE THREAD

**Issue by ArtRow** [Scirra/Construct-3-bugs#2511]
## Problem description

Objects with persist behaviour don't save thier Z-index when layout is restarted.

## Attach a .c3p

[Persist behaviour bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2752016/Persist.behaviour.bug.zip)

## Steps to reproduce

1. Run Preview
2. Restart the layout a few times

## Observed result

Object with persist behaviour changes its Z-index and hovers other objects which don't have persist behaviour. With every restart our object takes +1 for its z-index and goes up.

## Expected result

All objects must save their z-index, because it ruins level design. 

## First affected release

Based on your forum it's continue for a few years. Probably users create games with gameplay within one layout (one level - one layout). I started to create a quest and I have to return to previous  rooms/layouts. That's why I think there are no report for this bug. Or they don't use persist behaviour.

## Affected browsers/platforms

No info

## System details

No crash dialog

**Comment by AshleyScirra** [comment]
This turned out to be quite a complex problem in the engine. It's fixed for the next release in the C2 runtime. However the age and less flexible design of the C2 runtime makes it significantly more difficult to fix there, so I don't think we'll be able to backport the fix. One workaround is to use the persist behavior on those other objects too, since the engine does already correctly restore Z order between objects which use the Persist behavior.
