### ISSUE TITLE
Text object issue in editor

### ISSUE THREAD

**Issue by ArtRow** [Scirra/Construct-3-bugs#2512]
## Problem description

Text object becomes black

## Attach a .c3p

[Text area issue.zip](https://github.com/Scirra/Construct-3-bugs/files/2753176/Text.area.issue.zip)

## Steps to reproduce

1. Open the project
2. Change text placeholder scale as you wish on the layout with mouse.

## Observed result

Text area mustn't become black

## Expected result

Text area becomes black

## First affected release

r131 stable / desktop
r133 / web

## Affected browsers/platforms

* Chrome: yes

## System details

No details

**Comment by AshleyScirra** [comment]
Can't reproduce here. I'm not sure if you mean simply zooming the layout view, or adjusting the font size in the Properties Bar, but both work fine.

These are basic features that AFAIK work fine for everyone else - we've not heard of any other such issues, and presumably lots of people would notice if this was really broken. So I suspect the issue is specific to your system, perhaps a graphics driver issue. To help diagnose this it would have been useful if you attached your system details as per the bug report requirements. Try installing any available updates for your system.

**Comment by ArtRow** [comment]
Hi Ashley,
I meant changing size of text container. Drag any point
![image](https://user-images.githubusercontent.com/46167226/51109234-6ab36680-1816-11e9-9735-ca15c947964b.png)
I'll try to run it on another machine with windows 10. I found it on win7. But, if there is no more such reports, it really might be video driver problem. Thanks

**Comment by AshleyScirra** [comment]
That's the size, not the scale. Anyways it works fine here also, and the same applies.
