### ISSUE TITLE
Unexpected movement with 8direction behaviour

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#2520]
## Problem description

Objects with the 8direction behaviour moves in a very unexpected way when they're pushed by other solid objects, but it doesn't happen everytime.

Here's an example of a correct movement where the player (pink) is pushed by other solid object (blue):
https://i.imgur.com/W2O16J5.gif

Here's an example of an incorrect movement where the player moves to a random direction.
https://i.imgur.com/IZCQp0l.gif

## Attach a .c3p

[New Project.zip](https://github.com/Scirra/Construct-3-bugs/files/2768692/New.Project.zip)

## Steps to reproduce

1. Open and play the project
2. Get in front of one of the blue boxes

## Observed result

Sometimes the player is pushed in a random direction.

## Expected result

The player to be pushed in a straight line.

## First affected release

I only use the desktop build, i'm not sure about how to use old releases, but the problem is affecting the latest beta (r134).

## Affected browsers/platforms

* Chrome: yes

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is just the same, age-old problem of teleporting solid objects in to movements that aren't allowed to overlap solids. It triggers the "get me out of here" code which looks for the nearest place to exit the solid, and the place it goes to isn't always a predictable direction.

I'm not sure what can be done about this - we've long advised not to teleport solid objects on to behaviors (and using something like the Sine behavior just teleports them in small steps, because nothing really moves truly smoothly when you have discrete time steps). We've made a few tweaks to improve things for the platform behavior, but those are based on the fact it knows which way is down - 8 direction has no special directions so I can't think of anything we could easily do to improve this.

**Comment by BonzerKitten7** [comment]
> I can't think of anything we could easily do to improve this.
Maybe add conditions to make behaviours interact in a sensible way instead of giving users a "wontfix" label? Well, one more feature to remove from my game.

**Comment by AshleyScirra** [comment]
What conditions exactly? If you don't have a specific algorithm in mind, that's little better than saying "use magic to fix it".

Construct has worked this way for years, we've provided consistent advice about it, and for the most part it seems like most people design their games taking it in to account.

**Comment by AshleyScirra** [comment]
All I'm saying is this is a very difficult problem and I can't think of a good way to solve it right now. Getting annoyed and demanding a fix doesn't mean that a solution is suddenly forthcoming - in fact it generally has the opposite effect.

From our [community guidelines](https://www.construct.net/en/forum/general/open-topic-33/forum-community-guidelines-141035), "bad faith" discussion includes:

> Demanding impractical measures or infeasible solutions. If we say we can’t do something, it’s not because we don’t want to, or we’re being difficult, we genuinely can’t do everything!

On that basis, locking this issue.
