### ISSUE TITLE
[Desktop] Entire UI occasionally resets to default when reopening

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#2531]
## Problem description

Could be related to #2304 but often times when I launch C3 Desktop, my entire UI state has been reverted back to the default. All bars, dialogs, editors, and display scale.

## Attach a .c3p

Blank .c3p

## Steps to reproduce

1. Open C3
2. Change display scale, move and re-dock windows and bars
3. Close C3, Open C3.
4. Repeat a few times. Might need to wait a bit.

## Observed result

Eventually, UI is completely reverted to default.

## Expected result

UI should stay as I left it.

## First affected release

Always, but using r135 now.

## Affected browsers/platforms

Desktop

**Comment by shortercode** [comment]
Seems odd, it would suggest the local storage might be being cleared. I will take a look.

**Comment by shortercode** [comment]
Okay think I've resolved this while looking at #2304 

Restoring window positions is kinda complex; mainly because the size, position and number of screens can change between runs. This doesn't sound that bad, until you realise windows can be placed off screen, so we have to check if the window would be visible when restoring. The old code was quite aggressive that if any part of the window was off screen then it would reset the position, which is quite easy to trigger. I've changed this so that we only require part of the window caption to be on screen now ( so that you can at least move the window around ). Hopefully this won't cause too many edge cases with editor hidden behind stuff or being barely on screen...
