### ISSUE TITLE
Text input can be placed under sprites in editor ( inconsistent with runtime )

### ISSUE THREAD

**Issue by Roguelike2018** [Scirra/Construct-3-bugs#2582]
If you insert the "text input" plugin and then draw a sprite and close the text input with the sprite, then the sprite in the editor closes the "text input" but when you preview it, the text input still becomes visible.

## Steps to reproduce

1. create a project
2. create text input and where to put it on the layout
3. draw a sprite such as a black square and close it "text input"
4. run preview

## Observed result

the "text input" plugin is still shown above the sprite

## First affected release

stable 131

## Affected browsers / platforms

Preview

* Chrome: no
* Firefox: no
* Edge: no
* Safari: no

## System details

**Comment by Roguelike2018** [comment]
can you fix it?

**Comment by shortercode** [comment]
This is a won't fix. The text input is a separate element from the main canvas. It can either be in front or behind it, but not interleaved. So there is no "fix" for the problem unfortunately. If it helps you can apply styling to the input using the "Set CSS style" action, or by setting the "ID" property and attaching a stylesheet to the project that has a rule effecting that element.

In the editor we draw a fake version of the input box, which incorrectly can be moved on the Z axis. We may want to correct the inconsistency. Assigning to @AshleyScirra to review the changes needed for that.

**Comment by Roguelike2018** [comment]
it is very difficult for me

**Comment by Roguelike2018** [comment]
Please correct

**Comment by AshleyScirra** [comment]
I think this would actually be pretty difficult to fix. Form controls are DOM elements that float over the canvas, so nothing in the canvas can appear on top of them. However in the editor we draw a placeholder in the canvas, so they can layer normally. Drawing an object on top of everything else is tricky since it would have to bypass the entire Z ordering infrastructure - for example placing a sprite on a layer above another layer with a text input would have to bypass the text input on the layer below, then actually draw it later on. Z ordering is already quite complicated with integration with the Z order bar, sorting affected by Z elevation, and so on. Given the difficulty in fixing this and the comparitively minor nature of the issue, closing as wontfix.
