### ISSUE TITLE
Minification Breaks Touch (TouchID)

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#2592]
## Problem description

Minification breaks touch control

Man Ive been suffering this for months
Is nobody using touch????

## Attach a .c3p

[C3_TOUCH_ID_MINIFICATION_ISSUE.zip](https://github.com/Scirra/Construct-3-bugs/files/2838035/C3_TOUCH_ID_MINIFICATION_ISSUE.zip)

## Steps to reproduce
(1)
Export the attached file with minification
Tap the screen on touch devices
The number displayed records the ID of the last touch
Notice that is seems to be recording some kind of index rather than ID and getting that wrong also and resets to 0 sometimes. I dunno , anyway it's not working as it should.
(2)
Export the attached file without  minification
Tap the screen on touch devices
The number displayed records the ID of the last touch
Notice that the number is always increasing this is how it has worked since C2 days.

## Observed result

**TEST THESE EXPORTS WITH MULTI-TOUCH TAPPING - NUMBER REPRESENTS TOUCHID OF LAST TOUCH**

**MINIFIED**
http://yamaforce.com/C3_MINIFIED_TOUCH_ID_MINIFICATION_ISSUE%20(1)/

**NON MINIFIED**
http://yamaforce.com/C3_NOMIN_TOUCH_ID_MINIFICATION_ISSUE/

## Expected result

Minified behaves as per non minified

## First affected release

Some months ago when minification scrip was changed.

## Affected browsers/platforms

* Chrome: only tested

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by SnipG** [comment]
There was workaround for this. I don't remember what it was, but something like store variables, index or something. As ID can reset when minification enabled etc. I once wrote it on forum and they looked at me like crazy, feels like they don't use touch much in phones :D

**Comment by SnipG** [comment]
Just checked, i am using touchindex in game to control touches. I save it into var, when it touches button, to know if it is still in use etc. Pretty solid and does not bug, least if you don't use Xiaomi phones.
On Xiaomi phones, touches are still bugged when doing 2+1 touch and google don't care about it. Checked their own bug tracker and they don't care about it there either, and they promote their gaming phones. - Multi billion scale company :D

**Comment by NetOneGames** [comment]
Na man, screw that, you were right in your original assumptions that touch is broken. 
The index var workaround is not fool proof and wont work dependably with multi-touch implementations.
Index and ID are used for very different aspects of touch control.
You need the ID to clearly separate out and process (or ignore) new touches. 
It is the minification is causing the bug. 
I have 4 phones and 3 tablets (surface pro and android) in the house they all record increasing ID when there is no minification.  And they all show the same screwed up behavior on minified.
This has been doing my head in put me off development for ages. Needs to get sorted.

**Comment by SnipG** [comment]
No the index version works even when user needs to use 3 fingers.
![touch](https://user-images.githubusercontent.com/28864889/52373088-7e8f6880-2a62-11e9-92dd-dc32bafc053d.jpg)

**Comment by NetOneGames** [comment]
Na man!!! 
**You should totally not be using touch index like that.**  
**That is exactly where you should be using TouchID ....  if it was working correctly.** 
Using index there is going to lead to a whole load of trouble.
What happens if you keep 1 finger on (index 0)  then add a second (index 1) then third (index 2) then remove the second finger then add it back agian (it will be then given index 2 as the third touch) then both the last touches have the same index how can you track that properly?

**Comment by SnipG** [comment]
You save/remember them. Then use TouchXAt(Index) and with touch end, you check which index got cancelled. Its works 100%.  In ideal world ID should work, but it does not. So index is only way to make it work.

**Comment by NetOneGames** [comment]
Yes but no but....
Go back to my example.  
There are now two touches with Index 2
In your code, releasing either of those two touches will trigger the touch off/end events.

**Comment by SnipG** [comment]
There won't be 2 index with same number, but 2 ID with same number. If you add touches. index increments 0,1,2,3,4. But ID sometimes resets like 0,1,0,2,1,2. So you can't use ID.

**Comment by NetOneGames** [comment]
Its the other way around.    Or it is supposed to be.

Touch ID might reset if all touch off (though Ive never seen it).  But otherwise Touch ID should reliably give you a unique and dependable ID whatever it does. In all cases I've only ever seen in continually increase as the game is running.

Index just counts the number of touches at last touch.

So say if you had three touches 1 2 3 
and then took them off and put them back on one by one (leaving the other two touches on) 
all touches will eventually have the same index  (index 2)
as at some stage they will all have been the third touch.

When you are observing Touch ID  doing "0,1,0,2,1,2."   it is totally broken

**Comment by NetOneGames** [comment]
here 
this is how it should work  ,  un-minified

http://yamaforce.com/TouchTest/

**Comment by SnipG** [comment]
Well yeah,both ID and Index could both be broken, if you think about it. I tried it on my case and it broke my code too, feels good. Looks like you only one who is using Touch :))

**Comment by AshleyScirra** [comment]
It's actually still working after export. Your test just makes it difficult to see that it's assigning pointer IDs differently. The problem is the minified export broke the detection of Pointer Events API for touch input, so it fell back to using touch events. These APIs assign pointer IDs differently: pointer events seem to use an ever incrementing number for the ID, but touch events reset to 0 when all touches are released. Since your demo shows the number 0 when nothing is happening, you can't see a touch that also has the ID 0.

In both cases, it is still working correctly: the only guarantee made about pointer IDs is that they are different for each simultaneous touch. This means either approach to assigning IDs is still valid - and some browsers use other approaches, e.g. using a timestamp for the pointer ID, or just a random number. Your events should not depend on specific pointer IDs, because they aren't guaranteed to be anything in particular; if your events correctly take this in to account - and they should because other platforms could work differently - then they will work either way.

Anyways the API detection is fixed for the next release so it correctly identifies Pointer Events support and uses that, so it works the same as it does in preview, but if your project was broken by this it still needs fixing, because other platforms still assign pointer IDs differently.

**Comment by SnipG** [comment]
Maybe i am not connecting here. Or it's topic for forum, but anyway.

I reported 7 month ago that case referenced in this issue, then started using index for fast fix for my own project, which does not work either when tested more.

Simple Example, game with touchstick: User must hold down touch for 1 button and can click 1-2 more buttons for fire etc. I must able to track the 1 touch.
  * If i use index, save it. It can be same with other touch at some point.  I can't convert index over to something, because i must also able to check when the specific touch got canceled. I can only do it, if it references to original index. So it's no go.
* Using ID worked 100% correctly, but when minified, it started to bug, going back 0. And it also could not be used when i needed to track use and touch end.
 
Games do not need specific touchID, but ID that does not change and can be tracked overtime. It worked like that when not minified, as it keeps incemending or picks random unique ID,  you can pick lets say ID 50 or -23 324 324, and it does not revert, when you spam touches with other fingers.

It is good it will be fixed for next release, but you are saying touch Pointer Events API can revert to touch event. Could it happen mid-game ? at some brower/platform etc? If it does, then there is no way to use touch for touchpads etc. 

Anyway good job and NetOne raising issue again, i bet this fixes a lot of bugged games out there.

**Comment by NetOneGames** [comment]
I think I get it.  What Ashley is saying in a round about way is that it's "fixed" for chrome next release as chrome uses ever increasing IDs. However if the minification broke your game then the fallback was a format that other platforms use and if it didn't work in chrome with minification it won't work on may edge or Firefox etc even after the fix.  My game assumed that every touch would generate a unique Id different from all others that came before so the code doesn't worry about scrapping IDs on touch off but now it looks like we need to consider that IDs can will be reused. Should be a simple fix.  I'm rushing out now but will follow up Sunday. Cheers.

**Comment by SnipG** [comment]
I further testing and it seems, my own test example was bad. ID could be used and tracked before too. 

Even with so simple thing you can end up with complex issues and cases :D

**Comment by NetOneGames** [comment]
Yep ..... Me too..... @SnipG 
it is good though,   it means that we will use touch correctly in the future.

I just made this simple but better test of the "bugged" minification script  to track touches and show their ID.   

 http://yamaforce.com/TouchTest2/

[TOUCHTEST (11).zip](https://github.com/Scirra/Construct-3-bugs/files/2849101/TOUCHTEST.11.zip)

It works perfectly in chrome , and in edge (which seems to record ID differently, starts high and reduces number each time)  ive never tested edge before.

so im sorry for being an ass in the original post although I did find a bug I am glad that this bug existed
as it has highlighted a touch bug in my own game which I now need to go figure out.... darn... 

cheers @AshleyScirra
