### ISSUE TITLE
Greenworks Plugin creates "wrong" steamid64

### ISSUE THREAD

**Issue by EsteranOlea** [Scirra/Construct-3-bugs#2598]
## Problem description

When reading the static steamid (or steamid64) via the greenworks plugin (greenworks.StaticAccountID, the plugin gives out a steamid with an added -2³². 
As this steamid still links to the correct steamprofile, it is no big deal when you just want to open the players profile.
But for the inventoryservices you need the correct steamid64.

The steamid3 (or accountID via greenworks.AccountID) is correct. 

## Attach a .c3p

No .c3p added, as its a direct error produced by the plugin.

## Steps to reproduce

1. just create a variable and read the greenworks.StaticAccountId into it. Read it out with a textobject
2. if you use this id to open up a steamprofile (https://steamcommunity.com/profiles/<ID HERE>
 it will open up the correct profilepage
BUT this is NOT the correct steamid64 to use for the inventoryservices. 
Granting or reading Items from the Inventory via this ID will send and read Items from a hidden Inventory. 

## Observed result

The greenworks.StaticAccountID function returns a steamid64 with an added -2³²

## Expected result

The greenworks.StaticAccountID should return the real steamid64 

## First affected release

r136 stable 

## Affected browsers/platforms

NW.js

**Comment by AshleyScirra** [comment]
The problem is it's a 64-bit ID, but Construct returns it as a number, and numbers in JavaScript only have 53-bit integer precision (because it uses double-precision floats). To work around this I've added a new StaticAccountIDStr expression that returns it as a string, preserving the full precision. This release is now available here: https://www.construct.net/en/make-games/addons/84/greenworks/0-33-3-r2
