### ISSUE TITLE
External scripts are not properly referenced in exported versions

### ISSUE THREAD

**Issue by nagyv** [Scirra/Construct-3-bugs#2621]
## Problem description

I've noticed this error using the GameSparksMinimal c3addon, but I expect it to be the same for other addons too that use an external file dependency with `type: "external-script"`

## Attach a .c3p

https://www.dropbox.com/s/wizhn46v0nzhgaq/ExternScriptBug.c3p?dl=0

You might need to install https://www.construct.net/en/make-games/addons/228/gamesparksminimal or any other plugin that has an external file under its c3runtime directory.

## Steps to reproduce

0. Install the plugin used in the example (https://www.construct.net/en/make-games/addons/228/gamesparksminimal)
1. Start the project in preview mode. In the console there will be an error that it can not connect to GameSpark websocket. That's OK.
2. Export the project as html5 game
3. Start the exported game

## Observed result

Check the console. `ReferenceError: GameSparks is not defined`

## Expected result

The game starts fine.

## More details

The problem is with the external files. 

* They are stored under the c3runtime directory in the project folder. 
* They are exported to the root of the bundle
* They are referenced in index.html under the c3runtime directory

**Comment by AshleyScirra** [comment]
It looks like the addon specifies external dependencies under the c3runtime folder. I've not see anything else do this yet, and it turns out the export path is wrong, still specifying the c3runtime folder when the scripts are actually exported in the root, e.g. `<script src="c3runtime/gamesparks.js"></script>`. I've fixed this for the next release. Also the addon can work around it in current releases by moving the dependencies to the root folder.
