### ISSUE TITLE
Changing orientation causes background color to cover all the screen

### ISSUE THREAD

**Issue by kingpirux** [Scirra/Construct-3-bugs#2643]
## Problem description
In android changing the device orientation causes the background color of the bottom layout to cover the screen not allowing to see anything

## Attach a .c3p

Any proyect, try with KiwiStory

## Steps to reproduce

- Open Kiwi Story template
- Use Remote Preview and open with Chrome in Android
- WHEN LOADING change the device orientation constantly (allow it to shift orientation and then change again)

## Observed result

The color of the bottom background covers the entire screen

## Expected result

To see the game

## More details

**Affected browsers/platforms:**
- Chrome on Android
- Android with Signature

**First affected release:** r137 (r136 is ok)

## System details
Nokia 3

**Comment by kingpirux** [comment]
it get worse, some android devices doesn't have an Android Theme for Portrait (like Samsung or Nokia), so when you try to open a portrait Construct proyect, it force the orientation change and causes this bug to show up.

**Comment by AshleyScirra** [comment]
I think this is another case of driver bugs killing WebGL 2 on Mali GPUs (the Nokia 3 has one). I've reimplemented the WebGL 2 bypass for Android in the next release, but this time specifically targeting Mali GPUs (so at least Adrenos + others can keep using WebGL 2). This makes Android devices with Mali GPUs drop back to WebGL 1 where everything seems to keep working OK. Marking to verify when the next release out since it depends on specific devices.

**Comment by AshleyScirra** [comment]
r140 is now out, please check again!

**Comment by AshleyScirra** [comment]
Based on link to #2650 and my own testing I believe this is now fixed, so closing. Please let us know if you still have any issues.
