### ISSUE TITLE
Function's "Compare Parameter" condition causes the event to fail. 

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#2683]
## Problem description

In various places around your event sheets you'll call functions, sometimes you'll realize you need to add another parameter. Then you go to add the function condition to check a parameter then test the game and find the function doesn't work because you didn't go back and add the extra parameters to every old function call.

The condition feels bugged and confusing.

![image](https://user-images.githubusercontent.com/5744908/53712887-dcb23e80-3e9c-11e9-8e1a-714399871478.png)

In this example, the "A" sprite does not change position while the "B" sprite does. I call the party function early in the project, but later on I realized I need to add another parameter to the function. Now to check the parameter in the function, I add the "compare paramater" condition to see if it's 0 (the default empty value), but the event does not even trigger at all despite it being true in reality (the truth can be tested with the system compare condition which is disabled in the image). 

Currently the solution in this case for users is either of the following: 

- Go back and search the entire project for every time you've called the function and manually add in the empty parameters
- Or, switch all the events from using the function's condition to the system compare condition. 

Using the system compare condition is fine, but I frequently forget to use it because using the condition from the Function object is more intuitive and I often wonder: "why is my game not working properly any more?". It doesn't feel like there's anything wrong with the code. 

## Attach a .c3p

[function_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2924484/function_bug.zip)

## Steps to reproduce

1. Preview

## Observed result

The B position is changing randomly. The A is not visible.

## Expected result

The A position should be changing randomly on the screen like the B. 

The condition in event 3 should work the same as the disabled condition.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is due to how out-of-bounds parameter accesses are handled. The `Param()` expression has to return something for out-of-bounds parameters, so returns 0. The 'Compare parameter' condition on the other hand returns false, causing the event not to run. I think this is a reasonable design, but it's true it complicates refactoring and makes it inconsistent with 'Compare two values', so I've changed 'Compare parameter' for the next release to allow the comparison to work, but also using a value of 0 for out-of-bounds parameters. It also now logs a warning to the console in this case (where it didn't previously) as a reminder about the missing parameters, as the `Param` expression does.

There's probably still a gotcha here if you add a string parameter: the value, and comparisons, will still treat the missing parameter as the number 0, so not passing a parameter will still be different to passing an empty string parameter. There's nothing that can be done about that though because currently functions are untyped and there's no information about what the parameters are meant to be. Luckily we've just started on [a redesign of functions](https://construct3.ideas.aha.io/ideas/C3-I-345) which should clear up this and more!
