### ISSUE TITLE
Vsync Issue with Moving Platform and Player Standing on Platform

### ISSUE THREAD

**Issue by Bat-Computer** [Scirra/Construct-3-bugs#2699]
## Slow Vsync update of sprite when moving on top of moving platform that has Bullet Behavior in very basic scene.

1) Create a low resolution scene (320x180) scene with a moving platform using Bullet, Bounce off Solids and Solid Behavior. 
2) Create a Floor Sprite with Solid Behavior. 
3) Create a wall at each end of the scene for the Platform to rebound off with Solid Behavior. 
4) Create a Player with Platform Behavior. 
5) Scale the Preview window to see clearly what is happening.

## I have tested this issue previously and it occurred with Construct 2 also. I have asked the community many times for a possible fix. Other than suggesting to try with Pixel Round on or off, no one seems to know what to do. This also happens in Firefox, Chrome, NWJS and also the Offline Windows 10 Beta App. Latest test was using Chrome browser today (06/03/2019). 

The only time I've seen the problem fixed is using the addon "MoveTo" by Rex. It seems unusual that this can't be fixed inside Construct without having to resort to an addon. This case was recently closed as the file I supplied was corrupted from using the Windows 10 Construct 3 App. The file has been recreated now.
[Test Moving Platform.zip](https://github.com/Scirra/Construct-3-bugs/files/2936781/Test.Moving.Platform.zip)

**Comment by AshleyScirra** [comment]
This isn't anything to do with v-sync or physics. You've changed the project settings so that pixel-perfect rendering is no longer guaranteed. For pixel art games upscaled a lot, the only way to guarantee pixel perfect rendering is with *Letterbox integer scale* fullscreen mode, but in your project you've changed it to *Scale outer*, which allows fractional scaling levels. Since you then upscale a pixel art game with fractional scaling and 'nearest' (aka point) sampling, then you will get aliasing as rounding errors affect the visual motion of objects across the screen. I think it comes down to the fact that the player and the platform are being unpredictably rounded in different directions (e.g. both rounded down on one side of the screen, both rounded up on the other, and in between, one rounded down and one rounded up - creating a discontinuity between the two).

So just set it to letterbox integer scale and it looks perfectly smooth. Here's the project with that change and it looks perfect now - and I also added text objects demonstrating that the engine is always keeping the objects exactly the same distance apart, proving the engine's calculated positions are perfect: 
[Test Moving Platform.zip](https://github.com/Scirra/Construct-3-bugs/files/2936936/Test.Moving.Platform.zip)

**Comment by SnipG** [comment]
I was just looking into the issue aswell out of curiosity and it seems it has some strange behavior. 
Platform with speeds 60 and 90 are correct, ones with 70 and 80 show lagging.  Not sure if it's bug

[TestMovingPlatformReMastered.zip](https://github.com/Scirra/Construct-3-bugs/files/2936998/TestMovingPlatformReMastered.zip)

**Comment by AshleyScirra** [comment]
I think the same floating point rounding error inconsistency can happen with both "nearest" sampling and "pixel rounding" enabled, since they both round fractional positions to integers one way or another. To avoid that you can turn off pixel rounding and use high quality fullscreen mode - then at least the maximum error is one real pixel rather than one resized pixel, making the error almost indistinguishable.

**Comment by Bat-Computer** [comment]
Thanks for the info Ashley, maybe this knowledge should be mentioned in the docs, as no one else I've spoken to has realised these settings we so important for retro pixel perfect games, and I've spoken to so many users in the last 6 months about this topic.

I used your settings and all seemed good.

I thought I'd just mention that I was unable to open your file you supplied in Construct 3.

In Chrome I received the error:
Unknown file extenion. Please choose a valid Construct 2 or Construct 3 project file.

**Comment by AshleyScirra** [comment]
I'm not sure where we would mention this in the docs. It's not really a Construct thing, it's maths: if you round two numbers with the same offset, sometimes they will round in different directions. It can happen on both the CPU (e.g. "pixel rounding" setting) and GPU (e.g. "nearest" sampling mode). The [New Project dialog](https://www.construct.net/en/make-games/manuals/construct-3/interface/dialogs/new-project) covers optimizing for pixel art, but that does not change the way rounding numbers works. It seems more of a general game design issue to me...

**Comment by Bat-Computer** [comment]
I guess it I thought it would be useful information for everyone, It wasn't that obvious to me, nor anyone I spoke to. Beginners would I'm sure find it worth knowing - the more knowledge users have in docs the better. But it was just a suggestion thanks :)
