### ISSUE TITLE
Color pickers don't appear in Edge

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#2702]
## Problem description

Windows 10 Store Construct 3 bets not pop up color to change tabs color.

## Attach a .c3p

No file need for this

## Steps to reproduce

1. Open new project (Windows Store version)
2. right click on tabs > Color > Change tab Color

## Observed result

Color popup window not popup

## Expected result

it should popup

## More details
working on desktop version and web version

**Comment by AshleyScirra** [comment]
This actually looks like a general problem with color pickers in Edge - picking colors for event groups and comments doesn't work either.

**Comment by luckyrawatlucky** [comment]
pick a web font from this project don't appear in Edge, only gives option to pick a local font available on this device. Do i need to create new bug report on this?

**Comment by AshleyScirra** [comment]
Yes, please do create separate reports for separate issues.

**Comment by AshleyScirra** [comment]
This looks like a specific quirk of Edge - we call `click()` on a color input, and all browsers bring up a color picker in that situation, except Edge. Any further workarounds would get really hacky, and Edge is currently due to switch to using the Chromium engine where this is working correctly. So rather than do difficult work to support a browser engine that will be phased out, I think we will simply wait until Edge switches to the Chromium engine.
