### ISSUE TITLE
Sprite image bleeding in different cases

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2703]
## Problem description
Not sure if bug, could be just some extreme case.
You have frame 0 black and frame 1 transparent. You resize sprite to very thin, you will get strange image bleeding in different cases with different behaviors. It's very chaotic and adding frames will change it or changing sprite location in viewport changes bleeding behavior.

Bleed occurs on top or bottom, sometimes left side.

Having sampling nearest fixed it, but most games you don't want whole game to be with nearest sampling.

## Attach a .c3p
[SpriteBleeding.zip](https://github.com/Scirra/Construct-3-bugs/files/2940591/SpriteBleeding.zip)

## Steps to reproduce

1.Open example, preview

## Observed result
I had 30x30 sprite resized 2 x 161.  1 black frame, other transparent. => bottom side bleeds on frame 1.
I added another transparent frame, bleed occures top with frame 1, frame 2 is transparent
I duplicate sprite, both sprite start to bleed left side, leaving behaind 1 px black border.
I cropped 1 sprite, it fixed it, then i moved it on viewport bleeding occured again.

## Expected result
Not sure what.

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
I tried r125, same behavior
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.121
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
C3 release: r140 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 1.1 gb (8.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is a combination of a normal result in computer graphics, and unavoidable bleed issues when using extreme sizing with spritesheets.

Extreme resizing (in this case downscaled extremely thin on X axis and upscaled larger on Y axis) generally doesn't look good because it selects the lowest resolution mipmap given the smallest dimension. So in this case it's selecting a low-resolution mipmap based on a 2px width, and upscaling that to 2x161. That often results in the gradient characteristic at the ends of the sprites.

Additionally if you use any degree of spritesheeting whatsoever, and resize an object to 2x2, it selects a mipmap that is so tiny ultimately everything on the spritesheet bleeds together. The only way to avoid this is not to use spritesheets at all, which would significantly degrade performance. "High quality" downscaling mode can help, but cannot solve such extreme cases as this.

Closing as wontfix since I don't think there's anything we can reasonably do about this. Basically you should use images that are more reasonably sized to how they are used.

**Comment by SnipG** [comment]
If i have 20x32 and i resize it 1x32. Same thing happens, so it does not have to very extreme.
And when i have 5x5, resized 1.399 x 43.434, the blend bleed can happen outside sprite area:
![bleed](https://user-images.githubusercontent.com/28864889/53957105-2fcb0200-40e6-11e9-8048-01a9914712dc.jpg)


Leaving it here, if it happens with someone else they would know why. As some bleed artifact seems very strange in some cases.
