### ISSUE TITLE
r141 Tween Value Problem

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#2718]
## Problem description

I used tween value to rotate the sprite 360 degrees before r141 and it was working fine. In r141 it won't complete the tween, sprite stops at ~350 degrees.

BTW I wish we could use the tween angle for this, it would be easier and makes more sense. But when you try 360 degrees with the tween angle, it won't do anything. It thinks 360 is 0.

## Attach a .c3p

[rotate-problem-141.zip](https://github.com/Scirra/Construct-3-bugs/files/2954074/rotate-problem-141.zip)

## Steps to reproduce

1. Open the example c3p. 
2. Touch anywhere.

## Observed result

![VruYt9IPcr](https://user-images.githubusercontent.com/2965842/54156060-7908b200-4456-11e9-92ef-321cc6e3e0bf.gif)

## Expected result

![mr1bh2XxIX](https://user-images.githubusercontent.com/2965842/54156104-92116300-4456-11e9-8a33-b961d90db0ca.gif)

## More details

**Affected browsers/platforms:** 

r141

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
The first issue is fixed in the next beta.

**Comment by AshleyScirra** [comment]
Should be fixed in r141.2. FYI I think a value tween is an acceptable workaround for the angle tween's behavior regarding angles. Since angles are cyclical, 0 and 360 degrees are mathematically identical. Using a value tween forces it to treat it linearly so you can get a spinning effect like you want. If you still think there should be an extra feature for this, post to the suggestions platform instead of the bug tracker.
