### ISSUE TITLE
8 Direction Vector X and Y doesn't work properly

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#2754]
## Problem description

I did a few tests using the 8 Direction behaviour and i realized that it's impossible to reach the Max Speed value using Set Vector X and Set Vector Y, which doesn't make any sense.
Please, take a look at this comparissons I've made:

Simulate Control vs Set Vector Y in a straight line (using a keyboard).
https://i.imgur.com/yTk3n7m.gif
As you can see, the red one (simulate control) walk at 256 pixel per second, which is his Max Speed value, but the blue one can barely reach 221 pixel per second.

Simulate Control vs Set Vector X+Y in a diagonal line (using a keyboard).
https://i.imgur.com/yKXXDre.gif
I don't know why, but when you combine both axis (horizontal and vertical) both of them can walk at 256 pixels per second.

## Attach a .c3p

[8Direction Vector Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/2992274/8Direction.Vector.Bug.zip)

## Steps to reproduce

1. Run the project.
2. Use the arrow keys to move around.
3. Keep an eye on the debug information on the top left corner of the screen.

## Observed result

The Set Vector X/Y actions can't reach the requested speed values (256).

## Expected result

The player to reach 256 pixel per second without a problem.

## More details

**Affected browsers/platforms:** 
Chrome (NW.js)

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by BonzerKitten7** [comment]
I did a few more test and aparently there is a way to pass the Max Speed value. I set the Max Speed to be 256 but i could reach more than 300 pixels per second. This behaviour seems to be very broken.

**Comment by AshleyScirra** [comment]
It's not a bug. You're directly setting the vector Y instead of using controls. If no controls are pressed the behavior applies deceleration. So in this case you're always getting one tick of deceleration applied, which prevents you reaching the max speed. If you set deceleration to 0 it works.

Some options to work around this: simulate controls instead; temporarily set the deceleration to 0 while moving; use a different behavior (e.g. custom movement); or just write the movement in events.
