### ISSUE TITLE
issue in Bullet bouncing when there is no instance in layout

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#2761]
## Problem description

bullet is not bouncing on collide with solid when there is not instance (bullet instance) in the layout but if we add instance in layout then its working.

## Attach a .c3p
[Bullet Bounce issue.zip](https://github.com/Scirra/Construct-3-bugs/files/2997444/Bullet.Bounce.issue.zip)

## Steps to reproduce

1. insert 2 sprites
2. add solid behavior to Sprite and bullet to Sprite2.
3. make sprite2 bigger and fit it in layout corners.
4. delete Sprite2 (bullet sprite)  from the layout
5) in Event > On start of the layout Create sprite2 (bullet Sprite).
6) set bullet enabled and set speed 500.

## Observed result

Bullet is not bouncing with Sprite with Solid behavior.

## Expected result

it should bounce

## More details
insert sprite2 (bullet sprite) in layout and see preview and then delete it (bullet sprite ) from layout and see preview.

**Affected browsers/platforms:** 

**r142.3

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is because there are no instances of 'Sprite2', therefore when it is created all its properties revert to defaults, which in this case is having 'Bounce off solids' disabled. The workaround is simply to add an instance to the layout to ensure its property is enabled. I also noticed there's no action to control this setting, so I'll resolve this issue by adding a 'Set bounce off solids' action.

In general if you want to use specific property settings, you'll need to either add an instance and set the properties you want, or use actions to set the properties after creating an instance.

**Comment by luckyrawatlucky** [comment]
in DragDrop Behavior there is no action to control axis **(Horizontal/Vertical)** if there is no instance in layout.

**Comment by AshleyScirra** [comment]
Added 'Set bounce off solids' and 'Set axes' actions for next release.

**Comment by luckyrawatlucky** [comment]
one more thing to add 
there is no action available to change Tiled Background's origin from events.
I also added this in Idea Forum

**Comment by luckyrawatlucky** [comment]
Hi @AshleyScirra Can you add scale X and scale Y to the action.
