### ISSUE TITLE
Particle properties misleading description

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#2762]
## Problem description
Something that might need checking if it is still correct.
Particle Lifetime properties: Angle, speed and opacity randomiser are misleading on Construct app and on manual. I am not saying effects are bad, but manual and app description should be changed accordingly.
Angle randomiser:"from manual"  set to 10 to allow particles to change up to 5 degrees left or right per second. In reality it seems it's 1 degrees per tick or something!  Because if i set timeout 1 sec and i set angle randomiser to 10, it can change angle much more then 10.  
Same for opacity randomiser: "from manual" Useful for creating "twinkling" effects. 
Setting it for example 30 results fast blinking, some particles change opacity even to 0, multiple times from 100.

Thous effects been there for long time, so changing them is not good idea. But their in app description should be maybe something else, as if i set opacity randomiser to 30 and i have particle with opacity 100 or 70. It changes self opacity to 0 multiple times before timout 1 sec destroyes it! But durning 1 sec, it should only have ability to change +-30 opacity. As description indicates per sec change.

## Steps to reproduce

1.Create particle, set cone to 0, type constant, rate 1
2.Test out Particle lifetime properties: opacity,angle and speed randomiser
3. Read description and see what really happens, compare them.

## Observed result
Description in manual and in-app are different from real particle effect outcome

## Expected result
Change manual or in-app property description to match what rly happens, how it is coded etc.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 72.0.3626.121
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
C3 release: r142.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 13 gb
Storage usage (approx): 936 mb (6.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Radeon HD 5700 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I discovered a bug in the way the lifetime randomisers work: it doesn't convert the values properly - the angle randomiser applies a degrees randomiser to a radians angle internally (so multiplying by about 57), and the opacity randomiser applies the 0-100 opacity to a 0-1 value internally (so multiplying by 100). Fixing this almost completely removes the effect, because of the probability distribution. For example if the opacity randomiser really did only apply up to a maximum of +/- 30 a second, the visual result is virtually no change, because to get +/- 30 a second, every tick random() has to return either the maximum or minimum value. The chances of this are vanishingly small. Really there is a probability curve with middle values being by far the most likely, and so most of the time the opacity would simply randomly vary very slightly around the initial value. Therefore it's actually useful it applies a multiplier of 100, since it makes an imperceptible effect much more visible.

I think this may have actually been intentional to solve the "imperceptible randomiser" problem, but the particles behavior was originally written 7 years ago and has been inherited all the way through to the C3 runtime, and frankly I can't remember. It wouldn't actually be useful to make it work like the description says, because the effect would be largely invisible, and fixing it to work like that would break all existing projects using Particles made since 2012. So I think the best solution is just to change the description. Given that I don't recall this having been an issue for years past, largely because I assume people just judge it by watching the effect, I think it's OK to basically treat them as unitless values, so the new terminology simply refers to "apply a random variation over time" instead of specifying precisely how or what the units or probability distribution is.
