### ISSUE TITLE
Entering Digits and Autocomplete

### ISSUE THREAD

**Issue by Mak14** [Scirra/Construct-3-bugs#2770]
## Problem description
Hi Team,
On the event sheet when i'm entering digits at the text field ( for example i'm setting the x, or y), there is autocomplete ( suggestion) drop down menu appears, even when i dont have any digit variable to suggest. 
So i see abc,acos,angle etc. When i hit enter it just closing the dropdown menu, and i need to hit enter again to finish editing. 

Problem is in the drop down menu, i don't need it when i don't have digits in my variables which it might suggest. This slows down work and distracts since it appears any time i'm typing numbers.
## Steps to reproduce

1. Add any  event to the event sheet
2. add action System-Wait ( for example)
3. Clear textfield
4. Start typing any digit ( 1,2,3...)

## Observed result
Autocomplete window is apperaring even when you don't have digits to suggest in your project. And it need to be closed by pressing enter, and then enter again to finish editing.

## Expected result
No autocomplete window like in C2 when it reacts only to the existing numbers of the project ( global variables). After entering digits i'd like to hit enter and close the window.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is related to #2305 - since object names can begin with numbers, autocomplete appears when typing numbers. However I agree this is inconvenient for typing numbers only. Therefore I've changed it in the next release so autocomplete only appears when you type the first non-numeric character. So typing `1 + 1` won't show autocomplete, but typing `1u` will show autocomplete and highlight an object named `1up`.

**Comment by Mak14** [comment]
Thanks for Quick response!
