### ISSUE TITLE
Pixelart rendering artifacts

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#2802]
## Problem description
There's rendering artifacts in my pixel art game

## Attach a .c3p
https://puu.sh/D92jD/9a0904e7f2.c3p

## Steps to reproduce

1.preview the minimal project

## Observed result

Artifacts or errors in the rendering like this
 
![image](https://user-images.githubusercontent.com/32940085/55414703-a4ecf400-5539-11e9-82cc-ebe934c39e7e.png)

## Expected result

I expect the sprite to completely cover up the sprite's white area below it
## More details

it's a huge issue in my game because my characters are made out of multiple sprites on top of eachother

**Affected browsers/platforms:** 
Chrome and firefox, others not tested

**First affected release:** 
forever I think, but I've just been able to narrow it down and make a minimal project about it today
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 73.0.3683.86
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36
C3 release: r143 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 16 gb
Storage usage (approx): 614 mb (3.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 980 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by eleanorawesome** [comment]
Also note that the right of the sprite seems to move a few ticks before the left does, this might be part of the issue

**Comment by Wackytoaster** [comment]
Interesting problem. After some testing I found the solution. I´m pretty sure it happens due to floating-point rounding errors. You create your sprites at random positions without any rounding, causing them to be placed at e.g. X: 153.0031593921
You move them at 0.01 pixels per tick, that seems to be big enough of a number to avoid the rounding errors, however, beeing initially placed at a sub-pixel position reintroduces that problem. So simply adding a rounding on the object creation like **round(random(ViewportLeft(0)+16, ViewportRight(0)-16))** fixes the problem.

You will still have to make sure that all your sprites don´t move at too small steps or the problem might show up again. Though I don´t know how, since Construct only offers pixel rounding and not sub-pixel rounding. Potentially you´ll have to make an event at the very bottom of the event sheet that draws everything at a big enough position every tick, like **set X to round(self.X/100)*100** to draw it at 1/100 steps. Sounds rather hacky and unoptimized though.

At first I thought it happens only because you move them at sub-pixels, probably causing floating-point rounding issues. But that doesn´t seem to be the whole story. The problem can be entirely fixed by creating them at a round pixel number like **round(random(ViewportLeft(0)+16, ViewportRight(0)-16))**

**Comment by AshleyScirra** [comment]
This isn't a Construct bug; it's a normal result in computer graphics. It's yet another case of floating-point positioning artefacts. This will happen with any software and any graphics API using the same approach. The rounding error is occuring in the texture sampler on the GPU hardware. You're using fractional positions with exactly aligned objects, but "nearest" sampling mode. In this case getting the result you expect depends on perfect precision of floating point operations, but floating point operations are fundamentally imprecise in computing, so there will always be some error. (The equivalent in events is to test for small tolerances instead of exact values.) If you switch to trilinear sampling you can see a white "glow" around the inner sprite as the white section inside bleeds to the outside even though it's covered up; when you use "nearest" sampling that basically still happens due to floating point imprecision, but with a much smaller magnitude.

Typical game design approaches to avoid this are either to round everything (Construct's pixel art mode also turns on "Pixel rounding", which this project has turned off - turning it on fixes it), or use art techniques to hide it, such as adding another row of black pixels inside the white area to hide sampler bleed, using a separate object representing the white area which is set to invisible when hidden, etc.
