### ISSUE TITLE
MALI Devices Issue is back in r143

### ISSUE THREAD

**Issue by kingpirux** [Scirra/Construct-3-bugs#2813]
Saddly the White screen on mali gpu devices is back-
According to:
https://bugs.chromium.org/p/chromium/issues/detail?id=934823#c33
the crhomium solution is NOT comming until JUNE. I recommend to leave the blacklisting until this issue is complettly solved and implemented in stable releases of chrome and android studio.

**Comment by AshleyScirra** [comment]
Since Google identified the precise cause and a corresponding workaround, the bug is worked around in our code in the mean time until the fix reaches Chrome 75. I verified the workaround fixes the issue on an affected device. Therefore I suspect any other problems are unrelated, and we will need a full report following all the guidelines to investigate.
