### ISSUE TITLE
Tiled often crashes desktop C3

### ISSUE THREAD

**Issue by corlenbelspar** [Scirra/Construct-3-bugs#2844]
## Problem description
Many times when I've been using Tiled while C3 is open in the desktop build, C3 crashes.

## Attach a .c3p
[https://drive.google.com/open?id=1G0ZHPnb6ZS9jRTvIS8mRm4hioZaO2qd-](https://drive.google.com/open?id=1G0ZHPnb6ZS9jRTvIS8mRm4hioZaO2qd-)

## Steps to reproduce
1. Edit a file for a while in Tiled and keep putting focus back on C3 until it crashes.

## Observed result
C3 crashes.

## Expected result
C3 should be unaffected.

## More details
**Affected browsers/platforms:** Desktop C3

**First affected release:** r144

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.37.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.37.0 (like Chrome/73.0.3683.75)
C3 release: r144 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 52 gb
Storage usage (approx): 4 gb (7.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 8
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I'm afraid it's not generally feasible for us to investigate reports like this, for several reasons:

- if the app closes instead of showing a crash message, that generally indicates the browser engine crashed, which isn't Construct's code and is beyond our control
- the problem could actually be caused by Tiled, which isn't Construct's code and is beyond our control
- we need more reliable reproduction steps to be able to investigate problems - often debugging an issue involves reproducing the issue a couple of dozen times and unreliable steps that take a long time can make this impossible.

If you can narrow this down to a particular action or sequence of steps that always crashes we could take a look, but even then I would guess this is likely not to do with Construct's code so beyond our control.
