### ISSUE TITLE
Minor visual bug after clearing recent projects

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#2852]
## Problem description

Clearing recent projects while having the _recent projects_ tab opened in the _starting page_, doesn't automatically refresh the list.

## Steps to reproduce

1. Open starting page and go to recent project tab
2. Clear recent projects from settings menu
3. Close settings menu and notice list has not been refreshed

## Observed result

Clearing recent projects works fine but doesn't automatically refresh the tab in the starting menu. No further issues are caused by this.

## Expected result

Clearing recent projects should automatically refresh the list. Optionally some feedback on process completion, would be appreciated. (Could also be applied to other "button based" settings.)

## More details

**Affected browsers/platforms:** Any 

**First affected release:** r145

**Comment by shortercode** [comment]
Yeah normally it only updates when its tab comes into focus, often your viewing a different tab when it's updated so that's fine. The same thing can happen by saving a project while your viewing the start page, I'd wager that isn't a common thing to do though. 

I've added a mechanism so that the start page can listen for changes from the recent projects manager, so it updates pretty much instantly now. Will be in the next release.
