### ISSUE TITLE
No watchdog timer! :o

### ISSUE THREAD

**Issue by djfg0** [Scirra/Construct-3-bugs#2904]
## Problem description

On an infinite loop the project freezes and you never gain control anymore...
## Attach a .c3p

I can't, I didn't saved my project before this happened :(
## Steps to reproduce

1. Make something ridiculous (now I'm thinking about it)
2. Start the project
3. Watch the rainbow colored beach ball spin for ever!

## Observed result

The game doesn't start and I can't close it...
It's loading...
... For ever!
## Expected result

Just a watchdog timer to kill it if nothing happens in a givven time...
## More details

**Affected browsers/platforms:** 
Safari on mac OS

**First affected release:** 
Online web editor tuesday 4 PM european summer time
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
If you make your project run an infinite loop (assuming your project did that, since you didn't attach one), unfortunately the preview window shares the same main thread with the editor, so it gets stuck. However you can enable 'Use worker' in project properties and the runtime will run in its own thread in a web worker, avoiding this problem. We'll probably make that the default in future.
