### ISSUE TITLE
Drawing Canvas' paste object action not work outside of the viewport

### ISSUE THREAD

**Issue by henrikszucs** [Scirra/Construct-3-bugs#2919]
## Problem description

Drawing Canvas' paste object action not work outside of the viewport

## Attach a .c3p

https://drive.google.com/file/d/1g4yQc2mrPph3dq8JeHRVSnUgdUb9sPm-/view?usp=sharing

## Steps to reproduce

1. Click "Move (overlap screen)" button
2. Click "Replace" button --> (Appear the sprite's part)
3. Click "Move (out screen)" button
4. Won't appear the sprite's part

## Observed result

Canvas cannot paste objects outside viewport

## Expected result

Canvas can paste objects outside viewport

## More details

I do not know it is a bug or not. I cannot find any documentation about this limitation.
 Chrome/Firefox/Safari, Windows/macOS/Android

## System details

Platform information
Browser: Chrome
Browser version: 74.0.3729.131
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36
C3 release: r147.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 15 gb
Storage usage (approx): 160 mb (1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
Should be fixed in the next release.

**Comment by SnipG** [comment]
I rly like canvas plugin so I followed this "possible" bug.  It took me a while to get know why the reported bug happens. And i was super curious when Ashley linked this bug fixed, because it seemed same canvas offset etc bug(not 100% sure)
Anyway: this fix removed ability to paste into canvas when it's outside of viewport and sprites too.(it broke one of my canvas test project).

ie, original bug seemed like sprite with spritesheet, moving it back does not display the image because you scrolled the shader viewport to different location, but pasted image still exist inside but still on original position{outside viewport} -> if you scale layer/layout and resize canvas you still can see it. Not sure if i make any sense, but i try to make example and possible new issue report, because canvas plugin is cool and should work correctly!
