### ISSUE TITLE
Missing Feature Possibly?  Set Web Font event.

### ISSUE THREAD

**Issue by mfoster98** [Scirra/Construct-3-bugs#293]
## Problem description

I've just realised that the Set Web Font event has disappeared from the Text Plugin.  is this intentional or is it a missing feature?

I don't feel like the template is much use for this type of issue, correct me if I'm wrong :)

**Comment by jaydonteh** [comment]
When importing a C2 project that uses the "Set web font" action in an event sheet will not trigger any errors. Which means the option is currently hidden in C3 but it still can read them.

Maybe because they have implemented a new way of managing and importing web fonts that this action has to be re-implemented. An overlook perhaps.

**Comment by AshleyScirra** [comment]
The action is deprecated because it's not necessary any more: the built-in web font support in C3 lets you set a web font directly in the editor.

The action can still be used when importing C2 projects, solely for backwards compatibility.

**Comment by jaydonteh** [comment]
Just to add an extra info:

You can use Textbox's "Set font face" action to change the font from the event sheet. Just key in the name of the imported web font without the extension (.ttf).
