### ISSUE TITLE
Save and then Load - Spritefont change text

### ISSUE THREAD

**Issue by SamueleDev** [Scirra/Construct-3-bugs#2946]
## Attach a .c3p

[bug.zip](https://github.com/Scirra/Construct-3-bugs/files/3183870/bug.zip)

## Steps to reproduce

1. Click Plus to increment the variable
2. Click Save to Save the Game State
3. Click Plus to increment the variable
4. Click Load and the spritefont is not be loaded (only spritefont)

## Observed result

I am creating a little videogame and when I load the game (not project) the whole game loads perfectly except for the sprite fonts.

## Expected result

I attached two project. On Construct 2 works perfectly but on Construct 3 I have this problem. When I click 'Load' (state) I must see the correct text for each spritefonts

## More details

![2019-05-15 19_44_41-CrazyNewBall](https://user-images.githubusercontent.com/26904027/57798472-2052df80-774d-11e9-9cf2-980a59f92788.png)

This screen is captured after click Load State; all of the objects are in correct positions but spritefont text is zero (on debug we can see 7 - the right text)

**Affected browsers/platforms:** Chrome 74.0.3729.131 (Build ufficiale) (a 64 bit)

**First affected release:** r148

**Comment by Kramdos** [comment]
Seems like the spritefont has the right 'text' but it doesn't update on screen. If you press the 'Plus'-button again to increase the number it updates the text to the correct number.

Same problem as zOrder had that was fixed in 146?

![image](https://user-images.githubusercontent.com/49698600/57803646-31a1e900-7759-11e9-8727-63f7ad3b1fae.png)

**Comment by AshleyScirra** [comment]
Thanks, fixed for next release.
