### ISSUE TITLE
Multiplayer cannot reconnect after disconnected

### ISSUE THREAD

**Issue by wilsonapa** [Scirra/Construct-3-bugs#2947]
## Problem description
In multiplayer, once a peer is disconnected from the room and signalling server, cannot reconnect back to the same room again without reloading the page. Hence once a player quits from a game he is not able to rejoin

## Attach a .c3p
[Sample c3p](https://drive.google.com/open?id=1ins-TiCb8PEpX8gykANFvRIqlB_gWqxF)

## Steps to reproduce
1. Enter alias
2. Open in two tabs
3. Click on Connect (one as peer one as host)
4. Click on Disconnect for the Peer
5. click on Connect again

Same issue if opening one tab with a host only.

## Observed result
On reconnect, stuck at Joining... room (Join room event doesn't fire)

## Expected result
Player should be able to join the room as per normal after disconnecting

## More details

**Affected browsers/platforms:** 
on PC Chrome: as above
on PC Firefox: Cannot even connect but thats another issue...
on iOS Safari: as above

**First affected release:** 
Not sure about first affected release but this is observed as of r148

## System details
No crash details

**Comment by eonianvr** [comment]
any update on https://bugs.chromium.org/p/chromium/issues/detail?id=961393 ? 
it seems that chromium is waiting for you to anwer them

**Comment by AshleyScirra** [comment]
This is a subtle mistake in your events. 'Disconnect from room' requires a short back-and-forth with the signalling server to complete the process, confirm that you have left the room, and inform the room host of your exit. However immediately after that action you disconnect from the signalling server, which prevents that process completing successfully. I think this then leaves behind a dead client on the server who will eventually time out.

Make sure 'On signalling left room' triggers before you disconnect from the signalling server, and it works correctly.

**Comment by Sudarmin** [comment]
I think there should be an easier way to disconnect than waiting for "On signalling left room" first before disconnect from the signalling server, because when I try to disconnect, I have to check if :
1. is in a room and connected to signalling server, we leave the room, wait 'On signalling left room', then disconnect 
2.  is in a room and not connected to signalling server, we need to connect to signalling server, leave room, wait 'On signalling left room', then disconnect
3. not in a room and connected to signalling server, we disconnect
4. not in a room and not connected to signalling server, do nothing

there are 4 if(s) just for disconnecting before trying to connect back, could be more if I check is logged in, maybe the user connected to the signalling room but haven't logged in or logged out, so we have to logged in first, before leaving room, wait 'On signalling left room' and then disconnect
