### ISSUE TITLE
Important!!! 

### ISSUE THREAD

**Issue by layilpaht** [Scirra/Construct-3-bugs#2956]
I have been working on 5 mobile games made with construct 3. And my experience was very excellent and I did not encountered even a single bug
But story got twisted when I made an apk files for android platform 
In most of my friends and relatives mobile, after installing the game, a message appears after opening the app, "instructing them to update android Web view". The painful part, it is already updated. And there is no other way round to start the game. The irony - pubg runs smoothly but a construct 3 game fails to run. 
I thought that I was missing some settings (I am new to construct 3),but when I looked for other games made with construct 3 by other developers ,they were not even visible in their play store(but those games were visible in play store in my mobile) 
## Steps to reproduce
🤨🤨🤨
##Expected result
My friends and relatives would play my game and would suggest me some suggestions 
##Observed result
The game just on the starting asks to update android Web view and the story ends there 
My opinion -game does not work on 2-3 years old phone. Game definitely does not work in Panasonic eluga a2 etc and works definitely in Huawei honor 7x,8x 7c etc. Infact it does not work even in many Samsung mobiles
Friends:- Which game engine did you used😂😂😂??? 
Relatives:- the game was excellent 😜😜😜
## More details
I have great respect for construct 3. I do not have any issue with performance rather I have strong issues with construct 3 mobile compatibility. If your excuse is that it does not run on old phones or specific phones running some particular android version, then again that's a grave issue. I this way I would not be connected to a large section of mobile users. When pubg can run but a construct 3 game refuses to start, then it is something which can't be ignored. When I was developing the games, it was working perfectly in my mobile and I did not expected this(otherwise I would not had invested my 5 projects in construct 3).Every game developer wants to make his game available to each and every user. 
Or is I am doing something wrong??? (I am new to construct 3)
Please Atlest reply so that I can plan my future in advance ( I want my games to be compatible in almost every phone) . Truly, I am feeling very low today 😞😞😞
Thank you

**Comment by layilpaht** [comment]
And it would be the third time that I am shifting my source code from one game engine to other game engine
From godot engine to gdevelop to construct 3

**Comment by layilpaht** [comment]
If you want then I can ask for screenshots

**Comment by layilpaht** [comment]
I don't want to break any one heart but still I am really worried about my games and my time spend on them

**Comment by layilpaht** [comment]
Confirmed--no construct 3 game (even made by other developers) is running on their mobile( downloaded from play store)

**Comment by AshleyScirra** [comment]
This is explained in the manual entry on [the C3 runtime](https://www.construct.net/en/make-games/manuals/construct-3/tips-and-guides/the-c3-runtime). The key points are:

- this only affects Android 5-6 devices - Android 7+ devices do not use the Android System Webview, using Chrome directly instead, and already ~60% of devices are Android 7+
- of Android 5-6 devices, this only happens if the software is 2-3 years out of date, or more. Construct 3 is modern software using the latest browser technology, and as long there has been an update within the past couple of years, it should work fine. Not updating software carries other risks, like exposing your device to more security problems.
- although this should only affect a minority of devices, if it is for some reason a problem for you, you can switch back to the C2 runtime and keep using that.
