### ISSUE TITLE
Tweening a value resets end value to 0

### ISSUE THREAD

**Issue by tunepunk** [Scirra/Construct-3-bugs#2989]
## Problem description

After tweening a value. The value is reset to 0 at end of tween.
Same as happened before. https://github.com/Scirra/Construct-3-bugs/issues/2734

## Attach a .c3p

https://www.dropbox.com/s/izpwo3hfygmm6yr/tweenvalue.c3p?dl=1

## Steps to reproduce

1. Open and run project
2. Notice value resets after tween finishes.

## Observed result

Value is set to 0 after tween finishes. Not end value.

## Expected result

Shold hold end value.

**Comment by DiegoScirra** [comment]
This isn't a bug. Once a tween is finished it is destroyed, in the case of value tweens, if you query for the value after it has finished, you will get a result of 0 because the tween no longer exists.

In your example this happens because the tween value is requested every tick, regardless of the tween being active or not, so after it reaches the end, the expression starts returning 0.

When you use the Tween behavior's **IsPlaying** condition, it works because the action stops being executed after the tween finishes playing.
