### ISSUE TITLE
Media keys (play/pause) affect music playback in NWjs export and Desktop build

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#3003]
## Problem description

Unfortunately Chrome added a new default "feature" where pressing the pause/play button on your keyboard would take priority from things like your music player, and pause the media in chrome (youtube etc.), instead of pausing the music from your background player! 

This has rolled over into affecting NWjs exported games and even the Desktop build of C3. 

Which means that pressing the media keys on my keyboard will now stop the music in my game, not good!  I don't think that taking away peoples ability to play music in the background players while developing or playing our games should be the default setting.

Thanks :)

## Steps to reproduce

1. Have a music file play in any capx
2. Press the play/pause button your keyboard

## Observed result

the music stops in the game

## Expected result

the music should not be affected by media keys, it should not take away priority from background media players.

**Comment by AshleyScirra** [comment]
This appears related to the new MediaSession API, and bizarrely there doesn't seem to be any way to completely disable it - so it looks like we're always stuck with a disabled MediaSession instead of being able to get rid of it. I just [filed a Chrome bug about this](https://bugs.chromium.org/p/chromium/issues/detail?id=972051) and also [created an issue for the spec](https://github.com/WICG/mediasession/issues/215). I think we need to see what the response is to those before acting on this.

**Comment by TheRealDannyyy** [comment]
Any progress on this? Is there really no hack to prevent those keys from triggering?

**Comment by simstratic** [comment]
Since the original issue pertains to nwjs export, I think there may be a chromium parameter that solves this issue:

--disable-features=HardwareMediaKeyHandling

**Comment by TheRealDannyyy** [comment]
@alastajj Would you mind testing that (or anyone else with media keys)?
Add `--disable-features=HardwareMediaKeyHandling` as a chromium arg, inside the package.json file.

**Comment by alastajj** [comment]
@TheRealDannyyy I tried but I don't think it changed anything. When I press pause/play it still stops both the players music and the game's music, while previewing.

This is what I did:

I edited this file: C:\Construct 3 - Launcher V2.2.0\data\package.json

and I have a line that was edited to say:

> "chromium-args": "--enable-node-worker --enable-features=NativeFileSystemAPI #ARGS#", "--disable-features=HardwareMediaKeyHandling",

**Comment by simstratic** [comment]
It worked for me, when using the Construct 3 NW.js export dialog, and in 'Command line options' put:

--disable-features=HardwareMediaKeyHandling

Tested using r214 beta and the in-built project: Intermediate Example - Audio player

**Comment by TheRealDannyyy** [comment]
@alastajj The Construct 3 Launcher has nothing to do with exported games. Please do no edit any files inside the "data" folder! These are files that the Launcher is fetching and specifically only work for the Construct 3 editor and not exported games. Chromium args that only affect the editor, should be added inside the Launcher settings menu instead. Any further questions can be asked inside the [Launcher specific topic](https://www.construct.net/en/forum/construct-3/general-discussion-7/construct-desktop-launcher-139502) in the forum.

---

Please do as @simstratic said and add that line during NWjs export. The reason why I mentioned "package.json" is because Construct 2 users don't have that feature and I'm used to doing it that way. Sorry for that!

_Construct 3 NWjs export dialog:_
![nwjs-options_v550](https://user-images.githubusercontent.com/15656049/92306258-fd75bb80-ef8d-11ea-8966-f8c0d386762c.png)

**Comment by alastajj** [comment]
Thanks, yeah that works fine for exported games!

Strange we can't do the same for the editor when previewing games.

**Comment by TheRealDannyyy** [comment]
@alastajj I also tested this on my end and it works fine for both. If you export a game, you have to add it like mentioned above. If you want it for the Construct 3 editor, you have to do one of the following:

_Vanilla C3 Desktop:_
![VanillaMediaOff](https://user-images.githubusercontent.com/15656049/92395753-22039c00-f124-11ea-9af9-01643448c7c0.png)

_C3 Desktop Launcher:_
![LauncherMediaOff](https://user-images.githubusercontent.com/15656049/92395781-2cbe3100-f124-11ea-9937-24dbd7195da0.png)

**Comment by TheRealDannyyy** [comment]
@AshleyScirra I think this issue might be ready to be closed now. 

I'd recommend automatically adding `--disable-features=HardwareMediaKeyHandling` inside the package.json file for Construct 3 NWjs exports. We could also wait for [Chromium to fix it](https://bugs.chromium.org/p/chromium/issues/detail?id=972051) but I doubt that'll happen anytime soon.

**Comment by AshleyScirra** [comment]
OK, I added `--disable-features=HardwareMediaKeyHandling` to the package downloads for the C3 NWjs downloads. This doesn't help with the Chrome browser at all, but as noted we probably need to wait for some spec change or new feature to cover that, and this issue only mentioned NW.js anyway, so closing.

**Comment by TheRealDannyyy** [comment]
@alastajj I recommend removing it from the command line options as soon as it's released with the next beta/stable of C3.

**Comment by AshleyScirra** [comment]
Note this affects package.json, it's already updated in the downloads here so there is no need to wait for a new release: https://www.construct.net/en/forum/construct-3/general-discussion-7/construct-nw-js-desktop-app-131317

**Comment by TheRealDannyyy** [comment]
> Note this affects package.json, it's already updated in the downloads here so there is no need to wait for a new release: https://www.construct.net/en/forum/construct-3/general-discussion-7/construct-nw-js-desktop-app-131317

Wait, does the change not automatically apply to Construct 3 NWjs exports?

**Comment by AshleyScirra** [comment]
If you want to disable hardware media keys for the editor, this is already done with the package downloads I linked to, and there is no need to wait for another release of C3.

If you want to disable hardware media keys for your NW.js exports, you can already add `--disable-features=HardwareMediaKeyHandling` in the command line options on export. Since this is already supported there is no need to wait for another release of C3.

**Comment by TheRealDannyyy** [comment]
> If you want to disable hardware media keys for your NW.js exports, you can already add `--disable-features=HardwareMediaKeyHandling` in the command line options on export. Since this is already supported there is no need to wait for another release of C3.

I'd honestly just add it by default to C3 game exports. This means that future bug reports regarding this need to be informed about this workaround. Just additional work in my opinion but it's up to you guys at Scirra I guess.

Thanks regardless, for adding it to C3 desktop!

**Comment by simstratic** [comment]
It's probably an edge case, but some people want want the media key functionality, multimedia type apps rather than games. for example I saw a user developing an app that looked like it was for teaching music, and it had buttons for play, rewind etc. and he would probably want the hardware keys to work. And if you add it as a default to turn it off, I don't think you can turn it on again. Maybe an extra check box on the NWjs export dialog would be best?
