### ISSUE TITLE
Deleting browser saves with enter key results c3 crash.

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#3045]
## Problem description
Deleting browser saves one by one and using Enter key, often results C3 crash. Crash message under 
 view details

## Steps to reproduce

1.Create few browser saves
2.Navigate browser saves, right click project and call up menu.
3.Click Delete Entry by mouse and few ms later Click Enter.

## Observed result
After mouse clicks delete entry and you press enter to delete it. Enter somehow tries to open project and then also delete it which results crash. As delete pop-up is slow to open, enter still manages to open project instead delete it from delete pop-up!
Can't reproduce 100% but it happens often.

## Expected result
No crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read property 'name' of null @ TypeError: Cannot read property 'name' of null at Object.ǃytH (https://editor.construct.net/r153/main.js:63:196358) at https://editor.construct.net/r153/main.js:63:196133
Stack: TypeError: Cannot read property 'name' of null at Object.ǃytH (https://editor.construct.net/r153/main.js:63:196358) at https://editor.construct.net/r153/main.js:63:196133
Construct 3 version: r153
URL: https://editor.construct.net/r153/
Date: Mon Jun 17 2019 00:26:29 GMT+0300 (Ida-Euroopa suveaeg)
Uptime: 58.5 s

Platform information
Browser: Chrome
Browser version: 74.0.3729.169
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.800000011920929
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36
C3 release: r153 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Mobility Radeon HD 5000 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>

**Comment by shortercode** [comment]
Interesting error, thanks for the report. Turns out there is a short delay between the context menu starting to close and the action for it being triggered. This is enough time for the save/open action to be triggered by an enter press, complete and close the dialog.

I'm not sure I can come up with a clean solution to prevent the dialog from allowing a save/open action during this window of danger... but I have made some changes to prevent the crash, by simply bailing on the rename/delete actions if the dialog has been released. I have blocked enter from triggering anything when the context menu is open, but it unfortunately doesn't count as open during that window. You may find disabling animations reduces/eliminates the window completely, I expect it's caused by the contextmenu fade out animation.

Patch should be in the next release, will leave an item on my TODO list to see if I can prevent enter from triggering during that window.
