### ISSUE TITLE
Selecting multiple properties in a timeline and changing Result Mode changes only the last property

### ISSUE THREAD

**Issue by trueicecold** [Scirra/Construct-3-bugs#3053]
## Problem description

Selecting multiple properties in a timeline and changing Result Mode changes only the last property

## Steps to reproduce

1. Create a timeline, and add an instance of a sprite to it
2. Select both X and Y properties
3. Change Result Mode from Relative to Absolute or vice versa

## Observed result

Checking the properties shows only the last property's Result Mode was changed

## Expected result

Both properties should change

**Comment by DiegoScirra** [comment]
The fix for this will be available in the next beta release.

Selecting multiple elements of a timeline now works like selecting multiple instances in a layout. The properties bar shows a list of the common properties that all the elements in the selection share and changing a shared property will affect all the selected elements.

**Comment by AshleyScirra** [comment]
Note this did not make r156.2 - it will be in the next beta cycle after the next stable release.
