### ISSUE TITLE
Construct 3 Suggestion - Simplified Bug Reporting

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#306]
## Suggestion

I would like to suggest **built-in Github bug reporting support for Construct 3**.
As you guys might have already noticed, a lot of people don't like to go out of their ways to report bugs on a 3rd party website, which requires a registration process for its use.

The Github API allows automatic bug reporting and since we're on the web, why not integrate this into Construct 3 and make things easier for us C3 users right?

## Execution

This would be fairly simple to implement. A _report bug_ button inside the crash dialog would open up another dialog, in which C3 users have to insert all the necessary information and upload a C3p file.
(An option to include the currently opened c3p file, could also be implemented.)

## Technical details

**Link to the API:** https://developer.github.com/v3/issues/#create-an-issue

Construct 3 users don't have to be logged in, in order to report a bug.
It should be possible to create a Scirra owned "trash account" to post _guest bug reports_, without the requirement of a manual registration/login from the user.
(Users should still have the option to login manually though.)

**Comment by Kyatric** [comment]
The advantage of having people logged in is that when dev need to contact the user to have further indications about a badly reported bug (missing informations/repro project, provided steps actually not allowing to reproduce the issue consistently, etc...) the user WILL be contacted through email and hopefully provide the required informations for the bug to finally be squashed.

With an automated, anonymous account that anyone can write into, this likely will not be possible and bugs may get reported but also may not be allowed to be fixed due to poor informations and no way to have more precisions about it.

**Comment by AshleyScirra** [comment]
No way - with Construct 2 we get as high as 50% useless or mistaken bug reports, sometimes more. It's a significant drain on engineering resources to have to wade through these to find real issues. In particular anonymous reports are even more likely to be useless, since we very often need more information from the reporting user to be able to resolve the problem. If they are anonymous they rarely come back with the information we need, making it more likely the report is just a waste of time.

We absolutely need bug reporters to be logged in and engaged enough to help us resolve the issue. Anything that relaxes that will just clog up the issue tracker.

**Comment by TheRealDannyyy** [comment]
I understand the concerns and I agree. I would still like to suggest to make it a bit _more obvious_, on where and how to report bugs inside the crash dialog itself. Perhaps a button which links to the github issues page?
