### ISSUE TITLE
Non-Conformity in Easing System in Timeline

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-3-bugs#3061]
It's not really a bug but i think more of a misunderstanding how animators understand and work with easing across all common animation tools (i.e. After Effects).

Let's look at an example and compare it to C3:

In after effects let's say i want to move an object across the screen and have it Ease IN (which means it will go slower as it goes IN to the next keyframe).

As usual, i do two keyframes with the first and second position. Then i add an easing parameter i.e. AE's Easy Ease. I add the Ease IN parameter on the SECOND keyframe, since that is where i want to slow down:

![image](https://user-images.githubusercontent.com/30116964/59862425-0c6d4f80-9383-11e9-9c94-9c31426ca146.png)

Now in Construct it seems to be mixed up. To get the same result as in AE i have to select the first Keyframe and select something like "Out Cubic" to get the same result. The object starts moving at a linear speed and then eases IN. This is confusing and as far as i know, most if not all animation apps work with the former method, which also makes more sense.

I don't know how other users would feel about this and maybe it's in the eye of the beholder but from my pov it really is a more abstract way of setting eases than necessary. Easing OUT means in classical animation that something gradually gets faster. Easing IN means that it gradually gets slower.

See this Page from "The Animator's Survival Kit" by Richard Williams which is THE standard book about Animation:

![image](https://user-images.githubusercontent.com/30116964/59862718-93bac300-9383-11e9-9e41-6d3addb650a1.png)

Coming from an animation background, we are used to this method of thinking and C3 was the first software that did it the other way around which is technically wrong... But maybe i'm missing something here or am doing something incorrect which might be as well. Hope this makes sense and thanks!

EDIT: I spoke to a few befriended GameDevs and Interaction Designers, not all of them Construct users, but all of them used to working with different animation applications and they all agreed with the method i've showed from After Effects that this is the more intuitive way so i think this is a usability issue that i would suggest looking into.

**Comment by Wackytoaster** [comment]
Some refs.
https://greensock.com/ease-visualizer (they use it for their timelines like in construct)
https://css-tricks.com/ease-out-in-ease-in-out/
https://developers.google.com/web/fundamentals/design-and-ux/animations/the-basics-of-easing
https://lucyxwalker.files.wordpress.com/2014/02/easing1.jpg

In after effects you are easing INto the second keyframe, while in construct you are easing OUT the first one. Either way seems to make sense with the same result.

For me, I prefer as it is now. Why? Because I have keyframe A describing the motion to keyframe B ("left to right") rather than keyframe B describing how the motion before it should happen ("right to left")

**Comment by joelmayer87** [comment]
I guess this could be an argument that goes on forever, to me most of these links simply have the thing the wrong way around but it could be that historically somewhere there was a mixup between slowing in and easing in or whatever :) So @DiegoScirra feel free to close this report since most seem to be fine with the way it's currently set up and i guess then resources are better spent elsewhere :D sorry for the trouble :D

**Comment by DiegoScirra** [comment]
@joelmayer87

Sorry for not replying earlier.

When I implemented this, I took the **Back** eases as the main example on how everything should work.

If you look up an **In Back** ease you will find out the effect is that the values go bellow the starting value in the beginning of the transition. On the other hand an **Out Back** ease produces a similar effect but at the end of the transition, the values go past the ending value.

With that in mind I assumed that **IN** referred to the beginning of the animation and **OUT** to the ending of the animation. That seems to be the way ease functions are understood in the CSS/Javascript world.

I don't really like the idea of having two different and logically opposite methods of setting eases, because it would be even more confusing for everyone.

If you still think this is important you can post it in https://construct3.ideas.aha.io. Granted that is no guarantee that it will be implemented, at least the thought will be safe guarded for future consideration, instead of just getting lost.
