### ISSUE TITLE
Textbox(TextInput) - Status Bar not hide

### ISSUE THREAD

**Issue by Salfer13** [Scirra/Construct-3-bugs#3067]
Construct 3 r148 stable

## Problem description

(On Android) With the focus on the [Plagin] Textbox(TextInput), the Status Bar appears and no longer disappears.
And [Plagin] Browser - Request fullscreen - Navigation UI (Hide) do noit working (On Android)

## Attach a .c3p

TextInput.c3p
https://drive.google.com/file/d/1284z6SDaAkWQOxokXH3OgIsu3fcy0e3Z/view?usp=sharing

## Steps to reproduce
1. Export: Android (Cordova)
    Min. version: 5.0+
    Android build: Debug APK
    Hide status bar
2. Install APK on Android device  ver. 7.0
3. With the focus on the [Plagin] Textbox(TextInput), the Status Bar appears and no longer 
   disappears. And [Plagin] Browser - Request fullscreen - Navigation UI (Hide) do noit working 
   (On Android)

## Observed result

A status bar appears and you can not hide it.

## Expected result

If I exported when exporting - hide the status bar, then in the application it is not needed.

If this is not possible, then at least with the help of a browser [Browser - Request fullscreen - Navigation UI (Hide)] to give the opportunity to hide the status bar.

## More details

Construct 3 r148 stable
Export: Android (Cordova)
Min. version: 5.0+
Android build: Debug APK
Hide status bar
Android device  ver. 7.0 (Chrome) Last version

## System details

not crash

**Comment by shortercode** [comment]
I think from a bit of reading this is an issue with the keyboard cancelling immersive mode when it opens and not restoring it. I haven't found a device that replicates it yet, but will update this issue when I've tried a few more.

**Comment by Salfer13** [comment]
Blackview BV6000s not work

**Comment by shortercode** [comment]
I'm still unable to reproduce this, but there has been a slight change to the fullscreening behaviour recently. Could you retry and see if it is still affecting your device?

**Comment by Salfer13** [comment]
r157 
all work. thx

**Comment by shortercode** [comment]
Thanks for confirming!

**Comment by Hodgekins** [comment]
This has always been a real problem for me. 

I attached a c3p which might make it easier to reproduce the issue.

Steps to reproduce:

I'm using r196.

1.) Export the project as Android (Cordova).

2.) I'm not sure if I'm making a mistake in the export but the app won't load automatically in fullscreen. In order to make the app load in fullscreen I go to res/xml/config.xml and change:

`<preference name="fullscreen" value="false" />`
to
`<preference name="fullscreen" value="true" />`

3.) In the app, tap on the text input to focus. The status and navigation bar will return as expected.

4.) Tap the circle icon to the right of the text input. This triggers the action 'Set unfocused'. At this point, the status and nav bars should disappear but they remain, blocking that area of the screen.

List elements don't seem to have this issue. I put one in my c3p to demonstrate. When you tap out of the list, the status and nav bars disappear. This is the behaviour I'm hoping to achieve with the text inputs.

One other thing: After unfocusing the text input, it's possible to make the status and nav bar disappear by pulling down on the status bar and then pushing it back up. 

I'm using a Moto G5 Plus. I've received emails from users reporting the same issue.

Let me know if there's anything else I can do to help.

[android_nav_bar_input_issue.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/4527486/android_nav_bar_input_issue.c3p.zip)

**Comment by AshleyScirra** [comment]
This issue was resolved and closed about a year ago. If you think there is a new or different problem, please file a new issue following all the guidelines.

**Comment by Hodgekins** [comment]
Apologies. I wasn't sure whether it would be considered a duplicate of this one.
