### ISSUE TITLE
Changing size or position property values will not undo with crtl + z properly

### ISSUE THREAD

**Issue by LukeNecklace** [Scirra/Construct-3-bugs#3088]
## Problem description

Changing size or position property values will not undo with crtl + z properly until you click off onto the layout.

## Attach a .c3p

https://www.dropbox.com/s/3pw21g0i9qf2wwp/Undoing%20properties%20will%20not%20be%20displayed%20until%20the%20layout%20is%20clicked.c3p?dl=0

## Steps to reproduce

1. Click on the red sprite.
2a) Change either one of the size values on the properties bar.
OR 
2b) Change either one of the position X or Y values on the properties bar.
3. Press Enter
4. Undo with CTRL + Z

## Observed result

The values change back but the selected sprite does not change until I click in the layout. This is annoying.

## Expected result

The sprite position/size should change back to what it was as I press CRTL + Z not just the values in the properties bar.

## More details
This looks like a similar report: #2660
The visual representation of the sprite will change when you click undo with the mouse, but it will not change with CRTL + Z until you click on the layout.

**Affected browsers/platforms:** Desktop

**First affected release:** r156.2

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.37.0
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.37.0 (like Chrome/73.0.3683.75)
C3 release: r156.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 67 gb
Storage usage (approx): 1.9 gb (2.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
In both this issue and #3089 the problem is that so long as an input field is focused, we delegate undo to the browser's own undo. This is so Ctrl+Z undoes the last typing in the input field, which is what users expect, rather than reverting the last change to the project.

The problem is when you press enter it focuses the next input field ready for typing in the next property (a usability tweak that was previously requested by users). Since another input field is focused we still delegate Ctrl+Z to the browser. However if nothing is changed in the input field there is nothing to undo. Unfortunately the browser's undo system is pretty opaque so I don't think we can detect this case. As to why in some cases it selects the previously edited property, I don't know why it does that, it seems to be the browser's default handling again and I don't know why it's different. Either way I don't think there's anything we can do about this I'm afraid: so long as you have an input field focused, the browser handles undo, not Construct.
