### ISSUE TITLE
Invalid grouping of files

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-3-bugs#3104]
## Problem description

When import Javascript and Css with the same name depending on where the file was imported first the files will grouped in that folder. for example i import a script named chart.js and then i try and import a project file called chart.css, the file will not show up in the project files it will show up in the script folder nested under chart.js

## Steps to reproduce

1. import script chart.js (any file with name chart.js)
2. import project file chart.css (any file as long as name match)
3.

* note, this only works for importing, if you create a file chart.js and try and create a file chart.css you get an error file with same name exists

## Observed result

the file will be nested in the script folder 

here is an attached gif of the behavior 
[https://drive.google.com/open?id=1Vcc8mZqt-yPH-TOmiOdUbBhRFvkZLhua](https://drive.google.com/open?id=1Vcc8mZqt-yPH-TOmiOdUbBhRFvkZLhua)

## Expected result

the css file will be imported correctly in the project folder

## More details

**Affected browsers/platforms:** 

chrome

**First affected release:** 
not sure when it started probably been there for a bit.

## System details

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
It's always helpful to provide the project and any relevant files you used so we can follow your steps and ensure we see the same thing.

**Comment by AshleyScirra** [comment]
Missing repro: [project files.zip](https://github.com/Scirra/Construct-3-bugs/files/3354486/project.files.zip)

This is tough because the grouping is designed for audio files, so e.g. music.ogg and music.m4a get grouped under a single "music" item which is listed once in the project bar. However due to an architectural oversight this is applied to all project files of any type, and when using files with the same name from different folders, causes them to be grouped and displayed in one place, so inevitably one file ends up in the wrong folder.

Fixing this would basically require re-architecting and re-writing most of the project file handling in the editor. This would be a lot of work, and given we're a small team already with stretched resources, I'm not sure this is easy to justify at this time. Maybe it's a quirk we'll just have to live with for a while...

**Comment by armandoalonso** [comment]
just to let you know, so far this has not had any impact with the functionality (that i have come across)

**Comment by AshleyScirra** [comment]
I've done a large-scale overhaul of the editor code to completely remove the file grouping feature. This is in the next release and avoids the problem of inappropriately grouping files.

There was a lot of code all through the editor that touched on file grouping, so it's been a big change and could cause a few other things to break, but hopefully we'll get it all sorted over the next few beta releases.
