### ISSUE TITLE
Android 5 - Webview 37.0 - Black screen [r157]

### ISSUE THREAD

**Issue by QuasarX** [Scirra/Construct-3-bugs#3108]
## Problem description

Default **Android System Webview version 37.0** in **Android 5**. All users don't know how it is works. So they don't update it. When you run Construct 3 apk in Android 5 with Default System Webview. It is show you only "Black Screen". **People don't know how to fix. They will uninstall your app and will give you 1 star on Googleplay.**
Just tested only Android. Idk about IOS default web browser version, show you info screen or black screen.

## Attach a .c3p

Use empty project with C3Runtime.

## Steps to reproduce

1. Export any empty project using C3Runtime.
2. Install your phone (It must be Android 5 and System Webview 37.0)
3. Black screen.

## Observed result

Black screen on phone.
![image](https://user-images.githubusercontent.com/13033837/60591273-ccf12b00-9da6-11e9-9abd-1ecd21cab6ae.png)

## Expected result

Show me how to fix, like this.
(**Used Android 6.0 (Marshmallow)  Default System Webview version** - Android System WebView 44.0.2403.117)
<details><summary><code>Screenshot</code></summary>

![Screenshot_2019-07-03-15-22-41](https://user-images.githubusercontent.com/13033837/60591382-09248b80-9da7-11e9-8c01-1686257b0766.png)

</details>

## More details

**Affected browsers/platforms:** Android

**Comment by shortercode** [comment]
Looks like a side effect of the Kasperky warning, @AshleyScirra wrote that patch so assigning to him. Looks to be a very simple fix though.

**Comment by QuasarX** [comment]
@shortercode I hope.

**Comment by QuasarX** [comment]
@shortercode 
I found another issue.
**Steps:**
1.) I run my game with supported webview version. (I tested with v74)
2.) I remove system webview. It is now using default (v37)
3.) Run my game with webview v37. It is show me black screen.
4.) Reinstall webview v74
5.) Run again my game. All datas removed. (Game saves with Localstorage)

**Comment by AshleyScirra** [comment]
The real problem is WebView 37 is about **5 years old* which is far too old to support the C3 runtime (more details on support and compatibility [here ](https://www.construct.net/en/make-games/manuals/construct-3/tips-and-guides/the-c3-runtime)).

It looks like the webview is too old to even show the "not supported" message. I fixed a possible problem with that (ugh, two problems with one line of code to check for Kaspersky Internet Security breaking things...) but the only change will be it will show a message saying you need to update the Android webview.

**Comment by QuasarX** [comment]
Thx. Will try with next release
