### ISSUE TITLE
Puting a tilemap on a global layer resets the tilemap on the next layout

### ISSUE THREAD

**Issue by ome6a1717** [Scirra/Construct-3-bugs#3111]
#2630  Problem description

When you create a tilemap on a global layer and change the layout, whatever changes you've made to the tilemap are erased.

## Attach a .c3p

https://www.dropbox.com/s/czap8hn0czqog72/tilemapLayoutChange.c3p?dl=0

## Steps to reproduce

1. Press 1 on the keyboard as many times as you'd like to fill up some of the tilemap
2. Press 2 to go to a different layout with the same global layer.

## Observed result

The tilemap gets erased

## Expected result

It should contain all the tiles you added in the previous layout

**Affected browsers/platforms:** 

Chrome : Yes
NWJS : Yes
Safari/Firefox: No

**First affected release:** 

Only noticed it today 07/05/2019

## System details

Windows 10

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's not a bug - you've got the global aspect of layers confused with the global property on object types.

All non-global objects are destroyed when changing layout. This is what is happening to the tilemap object - it is being destroyed and recreated on the next layout, which reverts its state. (You can see this in the debugger if you inspect it then change layout - it tells you it got destroyed.)

The fact the layer is global just means instead of the next layout's layer having its own unique objects placed on it, it uses a copy of the layer from the first layout. So it's the same as automatically duplicating the layer to the next layout. It's the same as if you manually copied the layer instead of using a global layer - objects are still destroyed and recreated as you switch layout.

Enable the "Global" property on the Tilemap object and it works like you want it to.
