### ISSUE TITLE
Docs lack info on frame properties

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#3123]
## Problem description
There are disabled properties in the frame properties and there is no info about them anywhere and it's kinda driving me mad not knowing what they are.

## Attach a .c3p
n/a

## Steps to reproduce

1. Create sprite
2. Create frame
3. Click frame

## Observed result

![image](https://user-images.githubusercontent.com/11213825/60822317-85531080-a1a5-11e9-8959-d5376d681339.png)

## Expected result

I don't know, explanations

## More details
Now Index is straightforward. The one I don't understand is the "Original Source" one. The description is "Source of this image in the local file system" but I don't know what that is supposed to mean.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
I have no idea... but I believe @DiegoScirra made this control, so assigning to him.

**Comment by AshleyScirra** [comment]
@DiegoScirra - note the strikethrough style should never be applied to properties, and the original source is an internal property that should not be exposed to the user.

**Comment by DiegoScirra** [comment]
The strike through style issue is resolved in the next beta release as well as not showing the Original Source property.

@skymen As you said, the index property is pretty obvious, it's just there to make it clear to what frame the image you are looking at corresponds, in case you loose track of that. As for the Original Source property Just pretend it was never there. 

It was never meant to be changed from the editor (I only kept it there while I was developing a feature, to see if things were working properly), that is why it is disabled. If you still want to know, It is the path to the image file corresponding to the frame in the local file system. For various reasons it can be an empty, mainly because C3 is primarily a web app and in that context we don't have access to a local file system. You can choose to link a frame to file using the **link** tool, only available in the desktop app.

If you import an image from your computer, by using the **open** tool or by dragging and dropping, the property will be filled too, again this will only work when C3 is running as a desktop app.

When the property has a valid path, C3 can then use it with the **reload from original source** tool, to retrieve any changes that have been made from outside of C3. Again, the **reload from original source** tool is only available in the desktop app mode.

I hope that helps to clarify, but as I said, it will be soon gone from sight.

**Comment by skymen** [comment]
Ok great, thanks for explaining 👍
