### ISSUE TITLE
Disabling a group with new Function causes runtime error

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#3127]
## Problem description

Disabling a group with new Functions inside of it, causes black screen and the following error in browser console:
Uncaught (in promise) TypeError: Cannot read property 'IsEnabled' of null

## Attach a .c3p

https://www.dropbox.com/s/e1lza3eob1bk1pi/FunctionsBug.c3p?dl=0

## Steps to reproduce

Run the project in preview.

## Observed result

Black screen.

## Expected result

Project should run normally, or there should be some warning message displayed.

## More details

**Affected browsers/platforms:**
Chrome
Firefox
Android

## System details

<details><summary>View details</summary>

Uncaught (in promise) TypeError: Cannot read property 'IsEnabled' of null
    at C3.Action._SetCallFunctionRunMethod (action.js:1)
    at C3.Action._PostInit (action.js:1)
    at C3.EventBlock._PostInit (eventBlock.js:1)
    at C3.EventSheetManager._PostInit (eventSheetManager.js:1)
    at C3.Runtime._LoadDataJson (runtime.js:1)
    at C3.Runtime.Init (runtime.js:1)
    at async e._InitDOM (domSide.js:1)
    at async e._Init (domSide.js:1)

</details>

**Comment by AshleyScirra** [comment]
Hmm, looks like the same problem as was meant to be fixed in r153:

> Disabling a built-in function block could prevent the project running

but this case uses a disabled group with a function inside it, instead of disabling the function itself, which is a new case not covered by the original fix. It's an awkward case since you have "call function" actions referring to disabled functions that aren't exported (since disabled events are not included). I've adjusted the fix to take in to account the nested-disabled case, which should fix it.
