### ISSUE TITLE
Pressing J with a condition selected should add a JS action block

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#3135]
## Problem description

J is the key shortcut for adding a JS block in the editor. Pressing it when an action is selected adds a JS action block. Pressing it when an event is selected adds a JS event block. However pressing it when a condition is selected also adds a JS event block. That means that if you want to run some JS on an event that has no other action, you can't use J and must  use the contextual menu.

## Attach a .c3p
n/a
## Steps to reproduce

1. Create "On start of layout" trigger (or any other condition)
2. Select  the condition
3. Press J

## More details
This is not really a bug per se. It's just that this means that there is no way to quickly add a JS action block to a new event block.
Also the case of empty events (aka no condition, no action), adding a JS action to them is dumb because they would run the same as just a JS event block, which would be the behavior when selecting them and pressing J if it only added a JS event block if another event is selected.

**Comment by AshleyScirra** [comment]
The problem is having a condition or empty event block selected is ambiguous - do you want to add a block or action? It applies to comments as well as script. Changing the answer to that question doesn't necessarily solve it, since if you select an empty event block and press Q, you might want either a block or an action comment.

I think the best way to solve this is to add a variant of the keyboard shortcut to always prefer adding as an action, which I've added for the next release as Shift+Q / Shift+J.
