### ISSUE TITLE
Loading a save game fails

### ISSUE THREAD

**Issue by dru1000** [Scirra/Construct-3-bugs#3140]
##  Problem description

Save game fails to load after a new object is created and the game/preview is reloaded.

## Attach a .c3p

[SaveLoadTest.zip](https://github.com/Scirra/Construct-3-bugs/files/3396765/SaveLoadTest.zip)

## Steps to reproduce

1. Preview the game
2. Click the mouse to create a new sprite
3. Press S to save
4. *At this point pressing L to load the save game works fine
5. Restart the preview and press L to load - I get the Load Failed message.

This only seems to happen after a new object is created before saving and the game has been restarted.

## Observed result

Load Failed message.

## Expected result

I should be able to load my save game

## More details
Tested on R158 Beta & R157 on Chrome/Windows

Didn't try the save game on any previous versions

**Comment by QuasarX** [comment]
Oh I have similar issue but I forgot report.
**When I load save, it was not save some objects and values.**
If I found that will report.

**Comment by AshleyScirra** [comment]
It happens because there are no instances of the sprite placed in the project, and it doesn't handle that case when trying to create them when loading the savegame. It's fixed for the next release, but you can also work around it by placing an instance somewhere in the project (including on an unused layout).
