### ISSUE TITLE
Drawing Canvas image resets when the layer angle is changed

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#3186]
#2630  Problem description

If you try to change the drawing canvas layer angle the image will disappear for no reason. I think it can also disappear when you resize the game window and when you change the layer scale. It's very annoying, because we need to start to limit ourselves by ignoring these features because a few parts of the engine can't deal with other parts.

I'm not sure on how you guys designed this feature, but I believe the texture should be drawn using the project resolution, and then scaled down or up depending on the situation, and also using the same sampling method as the project to keep the desired aesthetic.

## Attach a .c3p

Gif demo: https://i.imgur.com/OiIk8X3.gif

[Canvas Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/3462160/Canvas.Bug.zip)

## Steps to reproduce

1. Move the cursor to draw something
2. Click the button to change the layer angle

## Observed result

The image is gone.

## Expected result

The image to stay the same, but with a different angle.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The Drawing Canvas object does not support rotation. Notice that it does not have an angle property. You have circumvented this by rotating the layer the Drawing Canvas object is on rather than the Drawing Canvas object itself, but unfortunately it is still not supported. (If you rotate at a larger angle like 45 degrees you'll see it starts glitching pretty badly.) The reason it is not supported is because it's extremely complicated to support this case, and it's not clear why it would be useful. If you really think this is important please file a feature request and describe the rationale for it.
