### ISSUE TITLE
Animation editor Pixel loss/Addition

### ISSUE THREAD

**Issue by Zinderavin** [Scirra/Construct-3-bugs#3192]
## Problem description

When duplicating and editing Animations in the Editor some animations have pixels removed or black splotches added. Even with fixing the problem spots manually they return and sometimes get worse after.
## Attach a .c3p
[Bug project.zip](https://github.com/Scirra/Construct-3-bugs/files/3469619/Bug.project.zip)

## Steps to reproduce

1.Open the only sprite in the project
2.The animations are labeled based on order duplicated and examples of the problem are marked in the name of the animation
3.

## Observed result

Pixels removed and black splotches added
## Expected result

The animations should not be missing anything nor have anything added
## More details

I have not released anything on any platform so I don't think it's an export issue. I use the construct 3 app on windows 10 with no subscription. I also opened the attached project in the chrome version of Construct 3 and it still had the bug.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
@Zinderavin

Can you write down the exact steps that reproduce the bug?

I tried the following:

1. Start with animation labeled **"4"**.
2. Duplicate **"4"** and name the duplicate **"A1"**
3. Add frames to **"A1"** and edit them using the pencil tool until it looks like animation labeled **"5"**.
4. Duplicate **"A1"** and name the duplicate **"A2"**

At this point **"A2"** looks just fine.

Which of the tools did you use as you were editing the images? I ask because it seems like a specific order of operations is triggering the bug.

**Comment by AshleyScirra** [comment]
Issue is 2 weeks old with no repro, so closing.
