### ISSUE TITLE
Japanese input difficult in Parameters Dialog

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#32]
## Problem description

Original report: https://www.scirra.com/forum/japanese-conversion-bug-in-parameters-input-window_t189992

According to the reporting user, entering Japanese words is difficult in the Parameters dialog. It's probably something to do with how we handle input events or autocomplete. Pasting in details from the forum here. Marking as difficult since we need to figure out how to enter Japanese text, all our systems are configured to English right now.

> This bug ONLY happens specifically in parameters input window.
If I want to use Japanese at properties, project, layers or event sheet column, it works just fine.
I know this bug is too specific for the beta release but other Asian languages might encounter this too.

## Steps to reproduce

1.Start a project
2.Insert a text
3.Add event: System "On start of layout"
4.Add action: Text "Set text"
5.Type Japanese word and try to convert it

## Observed result

> Every time I try to convert Hiragana words to Kana or Kanji, C3 keeps adding possible conversion results.

## Expected result

> Possible result words shouldn't be added.

**Comment by taker7** [comment]
Hi, I'm the person who posted the issue on the forum.
I made a gif of the issue to show what actually happens.
We hit space key to convert Japanese and then hit enter to choose a desirable result.
I only hit space on the gif.
Hope those info help. 
![japanese_input_issue](https://cloud.githubusercontent.com/assets/24697133/24829898/d2831750-1cb5-11e7-8a40-6e5d1ee4c153.gif)

**Comment by oosyrag** [comment]
Hi Taker, I think it may also help a lot if you had an gif example of "normal behavior" as well.

**Comment by AshleyScirra** [comment]
I'm still not able to test this because I haven't set up a Japanese language system yet, but I've added a speculative fix for r18: the autocomplete system now just ignores input events when the "isComposing" flag is true. I think this might help. Please check again when r18 and let me know if it's better.

**Comment by AshleyScirra** [comment]
r18 is out now, can you check if it's improved?

**Comment by taker7** [comment]
I tired r18 but unfortunately the issue still remains.

I noticed that pressing other non-alphabet keys middle of conversion also adds words such as arrow keys. 
Which also shouldn't be happening.

To make thing clear, I attached the normal behavior of gif.
There is no problem typing Japanese if it's not on parameters windows.
![japanese_input_normal](https://cloud.githubusercontent.com/assets/24697133/25010599/94537fee-20a5-11e7-9ec2-9d26c2415773.gif)

**Comment by taker7** [comment]
Now and then I come back and check the input would work or not.
So far no luck. I've tried with Android devices but the result is same.

Work around is type Japanese in notepad and copy and paste in C3.
Since Ctrl+v doesn't require Japanese input, it works.

I want to let you know that this isn't the issue on C2.

**Comment by AshleyScirra** [comment]
I've not made any changes for this yet. We're extremely busy and I still don't really understand how Japanese text input works and what's different about it that it breaks the field. Hopefully I can come back to this soon.

**Comment by AshleyScirra** [comment]
In bug #26 I made some tweaks to how autocomplete works. After that I actually managed to figure out how to activate Japanese IME, and although I have no idea what I'm doing, as I type stuff it looks like it works more like the correct gif. So I think it's worth checking this at the next release in case it works better.

**Comment by AshleyScirra** [comment]
r32 is out now, @taker7 can you check if it works better for you when entering Japanese text?

**Comment by taker7** [comment]
It didn't work with r32. I tried with windows7 and android 7.1.2.
Still it behaves like the wrong gif in my end.

However, I found out that if I hold space or hit it really really fast to convert, it works correctly.
It's not practical though. I do not know this was the case with the previous versions.

**Comment by AshleyScirra** [comment]
Okay, back to the drawing board.

**Comment by AshleyScirra** [comment]
One of the reasons I'm struggling with this is I have no idea what to type and what I should get in response to that.

Can you provide a sequence of characters to type on a UK keyboard, and the expected result when inputting those keys? Otherwise I am really just shooting in the dark here.

**Comment by taker7** [comment]
I typed "hashi" on the above gif. "ha" will be "は" and "shi" will be "し".
The possible result is most likely "はし", "ハシ", "橋","嘴","梯","箸","端","波子" and "派し".

The sound, "hashi", could mean "bridge", "chopsticks", "edge of corner" and so on.
To get the specific meaning, in this case kanji, we need to hit space and until we hit enter, no letter should not be added.

**Comment by AshleyScirra** [comment]
Ah, thanks - that makes it clearer. I've now been able to reproduce the problem shown in your gif. I've tweaked the autocomplete system to not interfere with the IME and it looks to me like it's working better now. But I am entirely unqualified to tell, so let's check this again in r34 and see how it looks then.

**Comment by AshleyScirra** [comment]
r34 is out now, can you check it again? Hope it works this time :P

**Comment by taker7** [comment]
It works almost perfectly!
Certainly, there is no issue on conversion. C3 stopped adding letters when I press space anymore.

However, I found a minor issue.
That adding letter problem sometimes happen at only the beginning of typing.

I typed "aiueo" in the new gif. It works fine at the first try: あいうえお.
At the second try, I typed exactly same "aiueo" but the result was ああいうえお.
So the first "a(あ)" is duplicated.
When you look closer you can see an underscore and that means the conversion still is not happening.
But under the duplicated letter there is no underscore. Which mean the conversion is already done even though I did not do anything.

I tested with windows 7, 10 and android 7. I could only reproduce the issue with windows.
Maybe it's because I used a keyboard with only with windows.

I tried to find how to reproduce the new issue but I couldn't because it happened randomly and so rarely.
It seems like if it happen once, most likely it would happen next time.
![aiuoe](https://cloud.githubusercontent.com/assets/24697133/26758538/b546e2b0-491b-11e7-90a3-bf3a9592da96.gif)

**Comment by AshleyScirra** [comment]
Sounds like we're getting there! I can't reproduce the last issue though on my Windows 10 system: I kept typing "aiueo" in between the two double-quotes then backspacing and typing it again, but it seems to work every time. I guess it might be timing related since it looks like you're faster at typing this way than I am, and the syntax highlighting might be interrupting it. I made a tweak for r35, hopefully that fixes this last issue. Just to verify if it's timing related though - if you hesitate before re-typing, does it work better?

**Comment by AshleyScirra** [comment]
OK, r35 is out now.

**Comment by taker7** [comment]
It's been a long ride and it comes to an end. This works perfectly!

Whenever I had time, I opened up C3 and checked to see the issue would pop up.
I already spent using r35 more than r34 and there is no problem.
No matter how I type, quickly, slowly, gently, hesitantly, rhythmically and randomly, it works.

I highly appreciate it since you could tackle this issue much later or even could overlooked.
Thank you for fixing the bug!

**Comment by AshleyScirra** [comment]
Thanks for confirming - I sure am happy to close this bug now! Thank you for co-operating so much with this issue, it was difficult to deal with but you've been very helpful in aiding the process. I'm glad we've got it all sorted!
