### ISSUE TITLE
Perf issue with Sprite Load from url

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-3-bugs#3201]
## Problem description

Performance issue with Sprite Load from url. When repeatedly loading Sprite from URL (in the test case it's a data URI), the frame stutters. Looking at the chrome console in preview, it appears like memory is growing and a major garbage collection is triggered which causes the stutter.

Some ideas: are new blobs created on each load? Can the old ones be deref or revoked so they are more likely to clear with minor GC? Are there memory leaks in this action? Are there other C3 SDK or C3 scripting methods to load a sprite image/texture without putting pressure on memory?

## Attach a .c3p

[LoadSpriteURLTest (2)zip](https://github.com/Scirra/Construct-3-bugs/files/3488115/LoadSpriteURLTest.2.zip)

## Steps to reproduce

Load c3p project and run.

## Observed result

Animations are loaded, however every few seconds the FPS drops (stuttering.)
Note the animations are just 3 random frames, so the animation will not be smooth, to look for issues, look for the FPS drop.

Also, open up Chrome dev tools and do a few seconds of perf capture, in this you can also see the FPS drop and that at the time a 'Major GC' task is running.

## Expected result

No stuttering or FPS drop when loading from URL (local blob or data uri) each frame.

## More details
For more background see this thread on the forum:
https://www.construct.net/en/forum/construct-3/general-discussion-7/exploring-possible-issue-145915

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The problem is 'Load image from URL' is designed for one-off use, not regular use.

The action throws away the entire old image, loads (possibly downloading over the internet) a compressed copy of the image, decompresses the image, and uploads it to a WebGL texture. This is a heavyweight process and could take several frames on low-end devices, so it's not even feasible to try to use it for a fast animation. Additionally since the old frame is thrown away, it inevitably throws away both and compressed and decompressed copy of the entire image every time it's used, causing the garbage build up and necessitating the major GCs you've observed.

Since the action is not designed for this purpose, you should find a different solution - presumably you have some dynamic image source rendering to a canvas or some such, which could be rendered directly without going through a redundant compress then decompress cycle.
