### ISSUE TITLE
r???-r162.2 Loopindex does not work with JSON 'for each entry'.

### ISSUE THREAD

**Issue by Kramdos** [Scirra/Construct-3-bugs#3261]
## Problem description

Using loopindex does not work for each entry with JSON object.

## Attach a .c3p

[loopindexJSON.zip](https://github.com/Scirra/Construct-3-bugs/files/3537129/loopindexJSON.zip)

## Steps to reproduce

1. Run layout.
2. See that all sprites get created in the same spot and frames don't get changed when using loopindex.

## Observed result

All sprites get stacked on top of each other with the same frame#.

## Expected result

All sprites spawning at different coordinates with forumula e.g. 10+loopindex*150. Also having different anim. frames set by loopindex.

## More details
**First affected release:** 
Found it in latest stable. Still a bug in 162-2.

**Comment by Kramdos** [comment]
Can also be seen by just logging loopindex with the broswer object.

**Comment by shortercode** [comment]
This is the expected behaviour. `loopindex` is a system expression, and only works with the system loop conditions such as `repeat` and `while`.

The JSON plugin has the expressions `CurrentKey`, `CurrentType` and `CurrentValue` specifically for it's `foreach` condition. https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/json

Other plugins with their own looping conditions (  array for instance ) work the same.
