### ISSUE TITLE
autocomplete dosen'T show the object's instance variables when using indexes

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#3267]
## Problem description
autocomplete dosen'T show the object's instance variables when using indexes
https://puu.sh/E9wrA/feafabe2f8.mp4

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design, since supporting this would require parsing arbitrary expressions for the index, which adds a great deal of complexity. Meanwhile it's a little-used feature making it difficult to justify a lot of difficult work given our limited resources. Please file it as a suggestion if you think it should be supported.
