### ISSUE TITLE
Set rotation (orbit behaviour) doesn't work on created

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#3273]
## Problem description

The set rotation action from the orbit behaviour doesn't work on created.

## Attach a .c3p

[tired_of_this_kind_of_bugs.zip](https://github.com/Scirra/Construct-3-bugs/files/3547520/tired_of_this_kind_of_bugs.zip)

## Steps to reproduce

1. Just run the project.

## Observed result

Action not working.

## Expected result

Actions to work.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
It would appear the orbit behaviour initialises its target location and current rotation from the world instance on it's first tick. It doesn't tick until AFTER the action has occurred and hence overwrites the angle. Initialisation should probably be forced in the affected setter functions prior to modification so that the operations occur in the correct order. You can technically work around it for now by setting the instances angle, but that could be problematic if you don't want "match rotation" enabled.

Did this used to work? I tried r157 with the same project ( after hacking the version number in the project ) and the behaviour appeared to be the same. The only thing that would have changed it would be if the instances were previously ticked once when created, but I'm not sure if that was ever the case.

**Comment by shortercode** [comment]
Okay I've made a revision to fix this behaviour for the next beta release, I think it's probably a bit late to add this to the next stable unfortunately.

I'm still interested to here about if this used to work however.

**Comment by shortercode** [comment]
For a circular orbit "set offset" should have a similar effect as changing the rotation, but wouldn't be effected by the method that was overwriting the values. As it only set the "rotation" and "target" properties of the behaviour.

Orbit doesn't have any async actions so I don't think "wait for previous actions" would have done much, unless something async occurred in the event as well. The timing behaviour for "wait for previous actions" might vary from browser to browser when there is nothing to wait upon, due to how promises are scheduled in JS, but I'm not sure. Using a wait(0) after creating the instance will probably pause the block until after everything has ticked, and hence ensure that the initialisation method has been called. Although as I say the future release will ensure the initialisation occurs before any actions take effect.

It's a bit of a silly race condition which has been in the behaviour since it's release. There's actually been remarkably few changes to the orbit behaviour. I had a look at the changelog: one bugfix related to timeline integration and this issue. The rest of the commits are just pre-release iterations

**Comment by AshleyScirra** [comment]
@shortercode - is there any particular reason the Orbit behavior delays initialisation? IIRC all other behaviors initialise on startup. That avoids this type of issue where first-tick changes are overwritten, and avoids the complexity of having to add lazy-initialisation to every single possible setter.

**Comment by shortercode** [comment]
I can't remember the exact reason why it delays it. It might be a false assumption on my part that the worldinfo object would not be available at the time. Another option is that it allows the position and angle properties to be set after an instance is created but prior to the initialisation. Given that a position is set by the spawn method and rotation can be modified in a more natural way by using the behaviours SetRotation action that behaviour likely isn't very useful anyway.

The actual change wasn't all that complex, as it only affects 2 setters. But I expect it's safe to move initialisation to the ctor and ditch the delayed initialisation.

**Comment by shortercode** [comment]
I've revised the behaviour to not use a lazy init pattern, I can't see it having a major impact and it simplifies the behaviour to behave more intuitively.  Will be included in the next beta release.
