### ISSUE TITLE
Theme Change Deleting UI State

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-3-bugs#3274]
## Problem description

When you change theme your UI positions, Dialog sizes etc.. all removed.

## Attach a .c3p

Not required.

## Steps to reproduce

1. Open new project.
2. Change UI positions.
3. Restart C3. You can see they saved.
4. Change theme and restart C3. All UI will be changed.

## Observed result

UI positions changed.

## Expected result

UI positions not changed.

## More details
Before
![1](https://user-images.githubusercontent.com/54614906/63828705-0e015800-c970-11e9-9007-33c270b2b8b2.PNG)

After
![2](https://user-images.githubusercontent.com/54614906/63828757-2f624400-c970-11e9-8101-e4e2f89d3af1.PNG)

**Affected browsers/platforms:** Firefox

**First affected release:** r163

**Comment by shortercode** [comment]
This has been a conscious restriction since the release of themes in r38 ( now over 2 years ago ). Although it's not obvious what the reasoning was, it could cause some minor issues with the sizes of dialogs but otherwise I cannot think of any problems.

According to our changelog it would appear the original decision was made by @AshleyScirra but there's no notes on the reasoning.

**Comment by AshleyScirra** [comment]
There's no guarantee that a different theme will have the same layout and sizes of panes and dialogs as other themes. Therefore there's no guarantee that the old UI state is valid if it's from a different theme, which is why it's cleared. I don't think this is serious, since the assumption is that people rarely change their theme, and given there's no way to know it's valid to load, I don't think there's anything to be done here.

**Comment by CrackHub** [comment]
I don't think it is a problem. The problem you need to set everything again when you switch theme. Which really annoying.
