### ISSUE TITLE
Cannot upload to the app store. 

### ISSUE THREAD

**Issue by mammothinc** [Scirra/Construct-3-bugs#3301]
It seems like you cannot upload apps to the app store using UIWebView.

I received this message from apple

<img width="806" alt="Screen Shot 2019-09-04 at 9 54 23 AM" src="https://user-images.githubusercontent.com/31543676/64275256-06a2f700-cefa-11e9-9ba0-b2b556973fb0.png">

Here is the link in the image.

https://developer.apple.com/documentation/uikit/uiwebview

Right now, I cannot test my app in Testflight or submit it to the app store.

**Comment by AshleyScirra** [comment]
That message is telling you the upload *did* work. It does not prevent you uploading or publishing, it's a deprecation warning.

Construct already defaults to the modern WKWebView (and has done for a long time). The warning appears due to remaining UIWebView references in Cordova. These are being tracked at https://github.com/apache/cordova-ios/issues/661
