### ISSUE TITLE
HRTF audio engine playback is delayed and crackling

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#3315]
## Problem description

HRTF audio engine doesn't start immediately. It also crackles a lot when it starts playing.

## Attach a .c3p
[HRTF Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/3587712/HRTF.Bug.zip)

## Steps to reproduce

1. Open project in Chrome/NWjs or FireFox
2. Select 1 playback action and toggle the other
3. Preview + press "play" button
4. Notice that HRTF kicks in after a couple of seconds

(Use the "play at object" action and drag the listener to reproduce the crackle. It usually happens at random but this seems to make it worse.)

## Observed result

HRTF audio playback seems to be broken in Chrome/NWjs, it starts delayed and crackles.
In FireFox it starts with a very short delay but doesn't crackle at all. It cuts ~1sec of audio though.

(Audio file format doesn't matter, also occurs using WebM on my end.)

## Expected result

HRTF should start immediately and not crackle at all.

## More details
**Affected browsers/platforms:**
- Chrome + NWjs [YES]
- FireFox [YES]

**First affected release:** Not sure but this also affects Construct 2. ([HRTF Bug C2.zip](https://github.com/Scirra/Construct-3-bugs/files/3587716/HRTF.Bug.C2.zip))

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 76.0.3809.132
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36
C3 release: r164.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 82 gb
Storage usage (approx): 635 mb (0.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 192000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by TheRealDannyyy** [comment]
I've tried to reproduce this on my laptop without studio quality audio. 
The delay is still present but shorter. It crackles like before, no changes here.

Initial reproduction was done using a studio setup with the following default audio format:
![image](https://user-images.githubusercontent.com/15656049/64491187-9c75b380-d265-11e9-9fbb-c6bccfcde446.png)

**Comment by AshleyScirra** [comment]
I can't reproduce any crackling in Chrome on Windows here. The playback engine and HRTF transform is handled entirely by the browser, not Construct, so this would not be a Construct bug anyway.

The delay initialising is because HRTF is computationally expensive to initialise, so it is lazy-loaded. This is also entirely in the browser engine and not related to Construct. It looks similar to [crbug.com/602668](https://bugs.chromium.org/p/chromium/issues/detail?id=602668), which was filed by a C2 user, where they found a significant jank on first playback. Chrome was then changed so the HRTF initialisation happens asynchronously, but while it's loading playback is just pass-through. You can work around this by playing a silent/quiet positioned sound on startup before other positioned sounds play.

**Comment by TheRealDannyyy** [comment]
I will try to record the crackling and open a Chromium issue later.

Is there really no way to "warmup" and know if HRTF is ready? The suggested workaround is a bit too hacky and unpredictable for me. It also takes up to 8sec in NWjs on my end, which would mean I'd have add a "fake" startup loading screen with at least 10sec of wait, to make sure it's ready.

**Comment by AshleyScirra** [comment]
I'm not aware of any way to know it's loaded I'm afraid. Perhaps you could ask in the same Chromium issue. It might need to go as far as a spec change though.

**Comment by TheRealDannyyy** [comment]
Will do, thanks for checking the issue out!

Might be a good idea to include the info about HRTF being async, somewhere in the editor or manual to avoid confusion in the future.

**Comment by TheRealDannyyy** [comment]
Here it is: https://bugs.chromium.org/p/chromium/issues/detail?id=1002093

If the request for additional HRTF methods for initialization goes through, I'd appreciate if they could be implemented and back-ported. I assume an action and condition would be enough.

**Comment by alastajj** [comment]
@TheRealDannyyy  when you change your computer's audio settings, does it still happen? 

![image](https://user-images.githubusercontent.com/5744908/220038540-32a45517-013d-4888-bb27-832505b358b8.png)

I notice that HRTF sounds a lot different when I change the audio setting! 😬 Sometimes it's way too loud, sometimes it's soft, sometimes it crackles.

I've had to return to "equal power" because that gives more consistent results for me.

I don't know which setting from that list I'm supposed to have my computer set to! And likely users don't either! So I don't see  a point in using HRTF.

Unless it's just me that this is an issue for.
