### ISSUE TITLE
Game shows Cordova icons after released on iOS

### ISSUE THREAD

**Issue by Kraudi** [Scirra/Construct-3-bugs#3333]
## Problem description

When I build xcode files and upload them to itunesconnect my game works ok like in the past. Though there is one problem with the game icon. In the Multitasking menu of iOS it shows a cordova icon and when you start your app from the home screen or close it as well. 
The icon on the homescreen is only changed for a short period and return to the correct one.

## Attach a .c3p

Can't really share one here because it's a paid project.

## Steps to reproduce

1.  Export a iOS xcode build
2.  Add all icons to your project (except Apple watch icons)

## Expected result

My icon should appear everywhere in the system. Worked fine with my past games and releases.

## More details

![IMG-2433](https://user-images.githubusercontent.com/7287143/64918173-ffea6e80-d79a-11e9-903c-94071ff37440.PNG)

Video of the problem:
[RPReplay-Final1568531620.zip](https://github.com/Scirra/Construct-3-bugs/files/3613499/RPReplay-Final1568531620.zip)

**Comment by AshleyScirra** [comment]
Sounds like you just missed a few icons... maybe @shortercode can provide advice. In general though there is not much we can do to help unless you follow all the guidelines.

**Comment by shortercode** [comment]
As @AshleyScirra said it sounds like an icon is missing from the set. It's been awhile since I looked at icons but I believe that you can have multiple icon packages in xcode, so it might be worth checking that you have the correct icon package set. Also check that all the sizes are completed and of the correct size in the icon package. I believe sometimes iOS can cache the icons, so if your doing multiple builds try uninstalling between tests as well.

I expect that we don't set all the icons when we export the cordova project, but it sounds like your already editing the icons anyway when you build your archive. If your confident that you've done what I suggested above I'm not sure I have anything else to suggest. This is just the fun of working with xcode, you might be able to find more resources online through some careful searches. Sorry I can't be more help.
