### ISSUE TITLE
Can't open a very important commercial project

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#3351]
#2630  Problem description

Hi. I'm working a commercial project called Rabisco (https://store.steampowered.com/app/1125860/Rabisco/). Everything was going quite well, but today I decided to open the project files to update a few things but I was very surprised by this error.

https://i.imgur.com/3ysE8D0.png

What is that? I know exactly which variable the error is mentioning, it's the bool I was using inside a function in order to determine if a audio clip should loop or not. It was working as expected yesterday, but today I can't even open the project.

I can't upload the project here for obvious reasons, but it would be okay to send it via e-mail to a Scirra employee, just contact me. Please, help me recover this project, I really need it in order to keep the game development. It's unacceptable that the engine simply destroys a project for no reason in a stable release. I do have older backups, but I don't want to lose a whole day of progress if it's not my fault.

## Attach a .c3p

Can't upload.

## Steps to reproduce

1. No steps to follow.

## Observed result

The engine destroyed the project for no reason.

## Expected result

The engine to simply open the project and allow me to work.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please send the project to ashley@scirra.com and I'll take a look there.

Any bugs that could make a project unopenable are obviously a high priority to fix, but as with any bug report it is extremely difficult to do anything about it unless we have steps to reproduce the problem. Otherwise all we can do is recover the project and send it back to you, with the risk exactly the same thing might happen again. If you can use one of your backups to find a series of steps to follow to cause the problem, please let me know and it will be our top priority to fix that. As it stands though this report is not actionable by itself and this will be taken up by email, so closing this issue.

**Comment by BonzerKitten7** [comment]
I'm sending you a e-mail with the project files and more informaiton about the bug. I believe I'll be able to find an way to reproduce it in the next couple of days.
