### ISSUE TITLE
Unable to open the .c3p project (error message: invalid function name "very_log")

### ISSUE THREAD

**Issue by mgsoftwaring** [Scirra/Construct-3-bugs#3353]
Cannot open C3 project. It stars with "opening" message and then gives an error message "invalid function name [verofy_log]". Problem occurred after copying part of the code, which included function and it's call, from one project to another.

I will send the .c3p project file which i'm not able to open, 

https://www.dropbox.com/s/3g5jqtyzykznmw9/globeway3.c3p?dl=0

## Steps to reproduce

    Copied the code from Project "B" to this Project
   I add some code
    Saved Project "A"
    Tried to open project "A"

## Observed result
Project was downloaded from Dropbox. Then it started opening and after that the error message was shown:

![image](https://user-images.githubusercontent.com/36589148/65229689-f9c2fd80-dacc-11e9-9073-a34f5749751c.jpg)

## Expected result

Project should be opened normally.

## More details
Chrome and Safari were tested. Same problem.

**Affected browsers/platforms:** 

**First affected release:** 

## System details
MacMini 2012
El Capitain 10.11.6

</details>

**Comment by AshleyScirra** [comment]
This looks like exactly the same issue as #3074 which was already fixed. However you're omitted important fields of the report such as which version you're using and how exactly the problem occurs (we can't follow steps like "add some code" because they are too vague, we need to know exactly what you did).

Therefore all I can do is assume the problem is the same as the one we already fixed and so no further action is required. I recovered the project for you: https://www.dropbox.com/s/vkniqsqbkpfh3fm/GLOBEWAY3-recovered.zip?dl=0

If you have an issue in the latest release this would be a high priority issue for us to fix, but it is critical to have steps to follow to reproduce the problem in the first place, otherwise there is nothing we can do other than recover the project and send it back to you, with the chance the same thing might happen again.
