### ISSUE TITLE
Canvas doesn't respect the game's resolution

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#3361]
## Problem description

When using high quality fullscreen, the canvas plugin uses the device resolution instead of the game's resolution. This does not happen when using low quality fullscreen, but this reduces the quality too much to be usable.

## Attach a .c3p

[New project.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/3642628/New.project.c3p.zip)

## Steps to reproduce

1. Play game in fullscreen

## Observed result

The line should respect the game's resolution (100 x 100)

## Expected result

The line does not respect the game's resolution.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. High quality fullscreen mode means to use the full display resolution, and low quality fullscreen mode means to render at the viewport size and stretch the result to fill the screen. Drawing Canvas correctly respects both cases. Since high quality fullscreen mode is the default, it means games get high quality rendering by default. I imagine many games will specifically want high-resolution rendering too.
