### ISSUE TITLE
Android export using local storage has app version dependance

### ISSUE THREAD

**Issue by kingpirux** [Scirra/Construct-3-bugs#3368]
## Problem description

Is not a bug, it's a warning on the Local Storage use, with android exports.
The local storage with android export on google playstore, is app version dependant, it is not erased but it might not be accesible on the updated app. 

## Steps to reproduce

Is not easy, since is needed all the publishing steeps. Also is not happening in all androids (i had no trouble on 5 and only some times in 6, but sure in 9) 
1. An app with local storage, version 2.0.0
2. Android studio export, published on production in Playstore
3. Update the app version (in construct and in the export) to 3.0.0 and do all the publishing steeps again.
4. Try to access the local storage

## Observed result

After the version update, the local storage is not accesible. You might downgrade the app to read the local storage again, so it is there but is not visible for the updated version.

## Expected result

read the local storage with no problem

## More details
After some research, i had found that this might be because the installed apps of google play, have a particular directory path for the local storage (ex: apps/com.stuff.app/VER/storage). Also i only found warnings on the use of local storage with js. Also might be for the way it is exported.

A FIX tested: if you DONT update the version on the Construct export (example i leave it in 2.0.0) AND only update the version in the android studio manifest, then you can access the local storage with no problem.

**Affected browsers/platforms:** 

Android 9 in particular

**Comment by AshleyScirra** [comment]
If Android does store data under a path like *apps/com.stuff.app/VER/storage* then there is nothing we can do about this: the Android platform is designed to reset storage after a major version update.

Assigned to @shortercode in case he has any comments but I expect this will be closed without action on our part, since it is part of Android, not Construct.

**Comment by shortercode** [comment]
@kingpirux with your "fix" are you updating the version or the versionCode? Note that version is basically a label to show users. versionCode is the important one on Android.

IndexedDB is expected to be persistent across releases in Cordova, I'll see if I can pull any information about it.

**Comment by kingpirux** [comment]
@AshleyScirra that's why i think this is something that should be added to the documentation if we can find the reason.

@shortercode 
maybe is how construct pass the android versioning to the manifest, in construct it figure out as 0.3.0.1 but in the manifest  android:versionCode="30041" android:versionName="0.3.0.41" and this is readed for the google playstore as 3.0.41 so, a constructs minor update became a major update for playstore, i think there is missing "00" at the begining "0030041"

**Comment by shortercode** [comment]
Android doesn't actually care what the version number is, there is no concept of Major, Minor, Maintenance in it. The only value that matters is the version code, newer versions must be higher. It's read as a integer so having additional zeroes on the front doesn't matter. 

We use a 4 value version system: MAJOR, MINOR, MAINTENANCE, BUILD. The build process generates a versionCode from those. Using the following sum:

```
(MAJOR * 1000000)
+ (MINOR * 10000)
+ (MAINTENANCE * 100)
+ BUILD
```

**Comment by kingpirux** [comment]
yes that's why i think the problem is how construct and playstore handle the versioning, and i think is more important to have the playstore vision of versioning because any android app is going to playstore. It is also recommended on the android versioning code https://developer.android.com/google/play/publishing/multiple-apks.html#VersionCodes

**Comment by kingpirux** [comment]
PD: yes i know you hate me for 0.3.0.1 and not using 1.3.0.1  :+1:

**Comment by shortercode** [comment]
Using 0 for your MAJOR version is fine if your pre-release in my book 👍  Although in practice I would use a BUILD version of 0 for any published release, as it's more of an internal thing.

I can't actually see anything that recommends using leading zeroes in your version code in that article. The point of the article is a suggested solution for generating versionCodes for an application where you have multiple archives per release, targeted at different devices but without causing conflicts in the versioning. As they say:

> This scheme for version codes is just a suggestion

I'm not sure what adjustment you want us to make to the version code system, it's exactly what the play store is expecting. It's literally just a revision number, it could be a single digit if you wanted and the play store would treat it the same. Changing it would break the expected versioning for any existing application made with construct, possibly preventing users from updating their apps.

**Comment by AshleyScirra** [comment]
Is there actually anything in the Android developer documentation that suggests the version number has anything to do with storage at all? I think it would be weird to say the least if adjusting your version number could end up in wiping storage. If not I would guess this is just a confusion with some other issue and no action is required on our part.

**Comment by kingpirux** [comment]
true, maybe im stuck with the version thing because it's the only thing i found, but there is nothing in the android documentation on why this happens... but there it is :( ... maybe as shrotcode said, its something with indexedDB, but thats out of my league, if i found something ill let you know.

**Comment by kingpirux** [comment]
maybe the problem is with cordova: https://stackoverflow.com/questions/47659352/cordova-apps-localstorage-wiped-after-appstore-update

they recommend using native and secure storage.

**Comment by shortercode** [comment]
> maybe the problem is with cordova: https://stackoverflow.com/questions/47659352/cordova-apps-localstorage-wiped-after-appstore-update

I'm not particularly convinced by the quality of that answer. There's some notes in the Cordova documentation that the JS localStorage API used to have problems on iOS, but it also claims that iOS doesn't have indexedDB. Which it has supported for a number of years.

------
As for actually replicating you issue I followed the following steps and experience no data loss:

1. Load local storage - high score example
2. Update project settings for mobile export
3. Set version to "1.0.0"
4. Export as debug APK
5. Install APK on device
6. Run app and set score
7. Close app, reopen set score again ( note score was preserved )
8. Update version on project to "2.0.0"
9. Export as APK
10. Install APK on device ( do not uninstall old application )
11. Run app
12. Note score was preserved.

It's not quite the same as the original replication but I would expect this to behave the same as installing an application from the play store, and was faster to try. I can think of some edge cases that MIGHT trigger the deletion of local storage. However, you seem to be suggesting that the data is preserved, but access is limited to an older version. I can't think of any reason why that would actually be happening, and I can't find any Cordova developers actually talking about this issue.

I recall a user experiencing an issue with local storage not being preserved on Android a while back, but it was swiftly fixed by updating the WebView/Chrome version. I was never able to replicate it personally.

It is worth doing further investigation into this I believe, but I'm unsure of what direction to take. There are certainly some known issues with storing data locally using indexedDB; such as size restrictions and aggressive quotas causing data loss. We can't change the plugin to use a different storage format because of compatibility reasons, but we could potentially provide the option for an alternative storage location. We'll discuss the option internally, if there is a rare issue here we might be able to side step it by making this addition.

**Comment by kingpirux** [comment]
that's an other part of the weird thing, it doesnt happen in debug or beta. it only happens in production (published app) that's why i put it that way in the steeps to reproduce. (maybe beta and debug has unrestricted access to local storage data for debugging?

**Comment by kingpirux** [comment]
ill try to test more, i didnt pay attention to the size of the local storage, if i get more info ill be back

**Comment by AshleyScirra** [comment]
@shortercode - is there any action to take over this? If not I'd suggest closing it. I'd guess that something else cleared storage, and this was falsely attributed to a coincidental version number change.

**Comment by shortercode** [comment]
@AshleyScirra as per my last comment I don't believe this is related to the version number, but there is potentially an issue causing the loss of localstorage data between upgrades. It's worth investigating but I don't see a clear way forwards on the issue.

@kingpirux if you can come up with some more information for me I will investigate, but for now I'm going to close this issue. I will leave a low priority note on my todo list related to adding an alternate storage option for mobile exports that work around issues related to storage pressure clearing app data.

**Comment by kingpirux** [comment]
for now im just using lower incremental versioning and the problem is not showing again. but it is there. the cause is related to versioning. Not clear what, maybe cordova, maybe android studio, maybe google playstore, maybe android, it is there.
ill keep in touch if i found something else
