### ISSUE TITLE
(Audio) Fade does not respect current volume of tagged sound

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#3372]
## Problem description

When fading up or down the current volume of the tagged sound is not respected and instead seems to start from a lower volume if fading up and a higher volume if fading down.

## Attach a .c3p

[FadeBug.zip](https://github.com/Scirra/Construct-3-bugs/files/3666612/FadeBug.zip)

file extension changed from .c3p to .zip

## Steps to reproduce

run the c3p
start the sound (click sound button)
repeatedly click the volume up down button

## Observed result

harsh change in volume if fade is changed during a fade
fade appears to start at 0% vol if fading up and 100% vol if fading down.

## Expected result

fade should start from the current volume of the tagged object,  even when a new fade is started before previous is finished.

Tested in Desktop Chome 77 only

**Comment by AshleyScirra** [comment]
Normally this would work as expected in most browsers, but Safari has a bug that forces us to set the starting volume of the fade, which is what is breaking this. It's pretty awkward but I think I've got a change that fixes it for all browsers. Since we have a stable release coming up and I'm not confident this won't regress anything, this fix will come out in the next beta cycle after the stable release.
