### ISSUE TITLE
Android Software Keyboard Immediately Hides Itself

### ISSUE THREAD

**Issue by Chaia86** [Scirra/Construct-3-bugs#3376]
## Problem description

Entering text into a Text Entry on Android is impossible because the keyboard immediately hides itself. This seems to happen when Fullscreen is set to Scale Outer.

## Attach a .c3p

[BrokenMobileSoftwareKeyboard.zip](https://github.com/Scirra/Construct-3-bugs/files/3674044/BrokenMobileSoftwareKeyboard.zip)

## Steps to reproduce

1. Set Project to Scale Outer
2. Add Text Entry to project
3. Run on Android. I used the Chrome browser app.
4. Tap Text Entry to try and type. It will be impossible because it will immediately close.

## Observed result

Software Keyboard hides as soon as it appears.

## Expected result

Software Keyboard should stay up and let user type.

## More details
Affected browsers: Android 9 and Android 10 tested and broken. Chrome.

**First affected release:** R164.3

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 77.0.3865.92
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Android
Operating system version: 10
Operating system architecture: (unknown)
Device type: mobile
Device pixel ratio: 2.75
Logical CPU cores: 8
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Linux; Android 10; Pixel 3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.92 Mobile Safari/537.36
C3 release: r164.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 46 gb
Storage usage (approx): 211 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Qualcomm
Renderer: Adreno (TM) 630
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1023
Extensions:

EXT_color_buffer_float
EXT_float_blend
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by eleanorawesome** [comment]
I have the same issue with full-screen crop

**Comment by AshleyScirra** [comment]
Ugh, this is another horrible edge case caused by Android's poor handling of the on-screen keyboard (OSK)...

Unfortunately when Android's OSK appears it resizes the whole window. (For comparison on iOS, it doesn't resize the window, the OSK overlaps the view and it scrolls the remaining view to center on the form control, which is really nice.) Resizing the window in a mode like 'Scale outer' changes which objects are visible on-screen. In the example project this is exacerbated by having a landscape viewport which can be viewed in portrait orientation, causing most of the visible area to be part of the extension added by 'Scale outer', and therefore causing a very significant change in what is visible when the window size changes. This can move the input control off-screen. Off-screen controls are removed by the runtime, so the control is removed, causing its OSK to be removed again, which then restores the original window size and moves the control back in to view.

This is really annoying to deal with in the engine, I guess we will just have to put in some ridiculous hack to get around this.

**Comment by AshleyScirra** [comment]
OK, I've put in a hack for the next beta cycle that ensures you can at least keep typing, but the text field can still move off-screen as the keyboard appears. I don't know what we could do about that, but at least it allows for typing.

**Comment by Chaia86** [comment]
Thanks! I appreciate your help and insight! :)
