### ISSUE TITLE
New Functions Object Creation change

### ISSUE THREAD

**Issue by ariepert** [Scirra/Construct-3-bugs#3379]
## Problem description

starting with version R167, object creation and the ability to pick new objects has changed. From release R143 (new built in functions first release) to R166, if you call a function that creates objects, you can then call a second function that can pick those new objects - if the second function is called from the same event that called the first function. (You can't call the second function from the end of the first function - that fails and you can't pick the new objects)

Using the old function plugin follows the old rules of having to wait until the next top level event.

## Attach a .c3p

[https://www.rieperts.com/games/forum/ObjectCreationTest.c3p](url)

## Steps to reproduce

1. load the file in R143 and up to R166 and run it
2. the text will say if it could pick the new objects, and how many it deleted
3. move the mouse over the red obstacle sprites to see if the tile under it has been deleted

4.  then open the file in R167 or later and run it again. New objects can not be picked.

## Observed result

in releases R143 to R166, the new objects can be picked. starting in R167 picking has reverted back to the old rules of having to wait until the next top level event (or adding a wait 0)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 77.0.3865.90
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
C3 release: r166 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 31 gb
Storage usage (approx): 869 mb (2.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 3000 Direct3D9Ex vs_3_0 ps_3_0)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_float_blend
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I'm afraid that prior to r167 your project was actually relying on a bug that was subsequently fixed. We cannot change it back without reintroducing the original bug, so I'm afraid you'll have to change your project instead.

It's been a long-standing quirk of Construct that newly created instances cannot be picked by other events until the end of the next top-level event. This is because updating the internal instance lists while other events are running causes crashes. This was not implemented correctly for the new built-in functions, and it caused crashes (see #3337). We correctly imposed the rule for the new built-in functions to resolve that issue, but it caused this one, since your project relies on newly created instances being picked before the next top-level event has been reached.

I'd point out this restriction also existed with the legacy Function plugin, and so the latest behavior as of r167 actually matches the old Function plugin. Therefore it is now actually more consistent with how it used to be.

For the record: minimal repro - [create-func-picking.zip](https://github.com/Scirra/Construct-3-bugs/files/3697378/create-func-picking.zip)
Demonstration of legacy functions working equivalently - [create-legacyfunc-picking.zip](https://github.com/Scirra/Construct-3-bugs/files/3697380/create-legacyfunc-picking.zip)

**Comment by alastajj** [comment]
Thanks for reporting this, I'm suprised this breaking change was not mentioned in the release notes. r167 broke my game, and couldn't figure out what was happening.
