### ISSUE TITLE
Audio: Seek To, doesn't seem to work

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#3399]
## Problem description

Seek To doesn't work, it just plays the song at the start even though I set it to start at 20 seconds, as shown here:

![image](https://user-images.githubusercontent.com/5744908/66477607-3e4a2380-eae4-11e9-9cab-539a1ae20aba.png)

##

Actually I just came up with a new experiment (as shown below), and it seems that I can get it to work, but it needs to be delayed for a while in order to work? Is that a bug because I didn't see it in the manual entry for it, it made me confused for ages because other things like the fade effect work straight away.

![image](https://user-images.githubusercontent.com/5744908/66477553-1d81ce00-eae4-11e9-966b-82c016b38d17.png)

Unfortunely the waiting isn't a good solution, because it seems to be variable, depending on the computer it may need to be a larger number. In my bigger game it's loading other things at the start of the layout, so on my computer if I wait around 0.5 seconds it works. 

## Attach a .c3p

[seekTo.zip](https://github.com/Scirra/Construct-3-bugs/files/3707166/seekTo.zip)

## Solutions ideas

1. Make it so that the Seek is applied whenever the file is ready
2. Have a "on tag playing" trigger, so that when the music is ready we can apply the Seek then.

##

Tested on desktop stable build

**Comment by alastajj** [comment]
I tried this, but it doesn't work

![image](https://user-images.githubusercontent.com/5744908/66478698-abf74f00-eae6-11e9-9612-28a2a614e208.png)

**Comment by alastajj** [comment]
Applying a fade to the audio works right away!

![image](https://user-images.githubusercontent.com/5744908/66479083-799a2180-eae7-11e9-9ecf-9ac3b8003bbe.png)

**Comment by AshleyScirra** [comment]
Playing audio is actually asynchronous: in the background it must load/download the audio, decode it, and then start playback. This has been the source of some really awkward synchronization issues in the past and is a real pain to deal with... it looks like it's trying to seek before the audio has finished loading, so it ignores the attempt. That would explain why a short wait would fix it (although that just creates a race condition rather than properly fixing it).

"Play" is not marked as an async action so "wait for previous actions" will have no effect. Perhaps the best thing to do would be to actually make it an async action so that approach will work correctly, ensuring the audio has finished loading before seeking it. You might get a fraction of a second of playback from the start of the audio though...

**Comment by alastajj** [comment]
Thanks for explaining.

Making it an async action sounds like a good idea. Missing a fraction of playback seems fine, since most of the time you want the sounds to play straight away, in cases where it matters we can just have the volume at -100 then bump it up once we've waited for the async action to complete.

**Comment by AshleyScirra** [comment]
Well, on closer inspection, it turns out there is already a mechanism to wait for audio that is still loading to finish before applying a change, and that was done for fades to make sure fade-ins worked. So this actually is quite a straightforward fix - I just applied the same thing for seeking (and setting the playback rate which was also affected). So it should be working in the next release.
