### ISSUE TITLE
Code editor still uses light theme in dark theme

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#3446]
## Problem description

Inline event blocks in event sheets still use a light theme when the editor is set to the dark theme.

Script files appear to automatically switch to a dark theme, but this doesn't happen for script blocks in event sheets.

## Attach a .c3p

Open 'Integrating events with script' example

## Steps to reproduce

1. Set editor to dark theme
2. Open project
3. Look in event sheet

## Observed result

Script blocks using light theme

## Expected result

Script blocks using dark theme

**Comment by shortercode** [comment]
Turned out to be relatively easy to resolve, the style was actually already 99% correct. The static render of script blocks have the CSS class for the codemirror theme, but not the editor. So it appeared correct only when being edited. Most of the changes had been made to the theme, with the exception of 2 rules for the background color and default text color. I changed that rule to target the theme instead and it appears correctly now.
