### ISSUE TITLE
(Audio) Incorrect pitch in IOS when changing playback speed (also some possible time stretching?)

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#3457]
## Problem description

IOS appears to set the pitch far lower (incorrectly so) than Android when adjusting playback speed in events , is also potentially adding some sort  of time stretching.

## Attach a .c3p
[Link](https://drive.google.com/open?id=1ReMGWOnP3l8yU0AgqqE-hzCwbVnOHXbs)

## Steps to reproduce
[hosted test app](https://yamaforce.com/ironpan/open/soundlagtest/)
Press Top Button to start sound.
Tap the bottom button to change sound frequency.

## Steps to reproduce
Open website on Android.    Take note of tones when pressing lower button.
Open website on IOS .   Take note of lower (possible distorted incorrectly pitched) tones 

## Observed result
The tones on Android play at the correct pitch based on the playback frequency.  I have confirmed this with other apps.
The same playback rate tones on IOS are incorrectly pitched lower. There also appears to be sort of time stretching going on to confuse matters.

## Expected result
Parity in playback pitch across IOS and Android for the same playback rate set in events

## More details
Video Examples
These videos are from tarek2 on the construct forums and demonstrate the difference between android and IOS.

[android Samsung galaxy s8 demonstrating correct pitches](https://www.dropbox.com/s/r8cnjqi54no347c/s8%20browser.mov?dl=0)

[website on iPhone demonstrating strange playback rate anomalies](https://www.dropbox.com/s/vuu8ipzw57a7ls5/iphone%207%20%2B%20chrome.mov?dl=0)

[app on iPhone - ditto](https://www.dropbox.com/s/q17u7phiitu2epp/iphone%208%20plus%20ipa%20sount_test.mov?dl=0)

**Affected browsers/platforms:** IOS

Im looking to produce some real time playable music applications. This appears to be impossible on Chrome Android due to huge lag with web audio API however web audio API lag on IOS appears to be extremely low so potentially viable.
I was about to invest in some apple gear before tarek2 brought this up.  But have put a halt on that until  confirmed this issue is resolvable.

**Comment by AshleyScirra** [comment]
It works fine in Chrome and Firefox, and reproduces in Safari. In general anything of the pattern "works on all browsers/platforms except one" indicates a bug with that browser/platform, not Construct.

In this case I think the problem actually stems from the sound used. It is just 41ms long, which is unusual in its extremely short length. That's only ~1800 samples at 44.1KHz. This can cause problems with audio encoders and decoders, which sometimes have minimum lengths, e.g. if at any point in the audio engine it uses a minimum audio buffer size of 2048 samples, this will be shorter than that and so artefacts will become audible. Further 41ms is within the audible frequency range, since it will loop at ~24 Hz (where >20Hz is audible). Therefore any artefacts in the looping of the sound will be heard as a change in the pitch produced by the looping of the audio.

The typical thing to do would be to use a ~1 second clip that is looped, avoiding any such problems. I tried using a longer sound, and Safari adjusts the playback rate just fine in this case: 
[soundpitchtest2.zip](https://github.com/Scirra/Construct-3-bugs/files/3803917/soundpitchtest2.zip)

So this is probably some Safari-specific issue resulting from the extremely short length of the audio clip. You could report it to Apple, but given that there have been other histortical problems with extremely short audio clips, I'd recommend just using a longer clip.

**Comment by NetOneGames** [comment]
Thanks Ashley, that is very valuable info.  The sample came from a commonly used sample pack of single cycle wave-forms to be used in pro samplers thus the short length.  If that is the problem then that is easily rectified by repeating them a few times in an audio editor. That's great news.

**Comment by NetOneGames** [comment]
Ok ive tried a few different sample lengths, it seems it is not about the sample length. dosent matter how long I make this sample there is allays an artifact before it loops on macos safari and IOS.
I will raise a new issue with a demo
