### ISSUE TITLE
Generic parameter 'ContentType' could not be inferred (xcode)

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#3458]
Exported the project and opened it in xcode.

![image](https://user-images.githubusercontent.com/31101309/68091722-90802980-fe83-11e9-8ce6-a4b67ca5dc65.png)

Getting this error in Plugins > ConstructAd.swift
Not sure how to solve it properly (google wasn´t exactly helpful)

EDIT: Did some more digging and I still have no idea. There are a couple of suggestions but they either don´t work or just open up more errors. I´d rather not dig around in unknown territories anymore :V

## Attach a .c3p

🍨 I also get this error if I export an empty project with just the ad plugin.

## Steps to reproduce

1. Export for IOS 12+
2. Load in xcode
3. Wait a bit until the error pops up

## Observed result

Error

## Expected result

No Error

## More details

Won´t let me build the project until that error is solved.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 78.0.3904.87
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36
C3 release: r173 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 34 gb
Storage usage (approx): 984 mb (2.8%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Huh... that's kinda odd. I'll take a look, could you confirm a few extra details for me please? Don't panic if you can't find them. I'll try to take a best guess, or send you a guide on how to find them.

Swift version?
Are you using the xcode legacy build system?
xcode version?

**Comment by Wackytoaster** [comment]
Can only say that it´s a swift version < 4.2 because it promted me that I can update it (except it won´t let me update it as long as that issue exists)

I´ll check all the stuff when I´m at home.

**Comment by shortercode** [comment]
I'm going to be honest, this has very much confused me. I've tried compiling that section with  the new and default and legacy build system. Swift 4, 4.2 and 5. They all worked, not so much as a warning from that snippet. I do vaguely recall hearing that the Swift compiler will fail to infer a type if it takes too long. So it might be that?

That block of code probably needs refactoring anyway so I might just do that, and see if it fixes your issue.

**Comment by shortercode** [comment]
I've published an updated version, which is linear instead of relying on closures and should be simpler for the type system to understand. Let me know how you get on with it.

**Comment by Wackytoaster** [comment]
Alright so:

**Swift version?**
Swift 4

**Are you using the xcode legacy build system?**
No (It´s set to **New Build System (Default)**)

**xcode version?**
Version 10.1 (10B61)

If it really is because it´s too slow..... lmao. Either way **your change seems to have solved the issue <3**. I mean there is still 79 warnings about mostly deprecations and such but I guess that´s something that can be ignored to some degree. Can´t really give it a full test until I have more time on the weekend.

On a different note: Should I convert the project to 4.2? There is only one small change but who knows... might break something (I don´t think I even use the rate app plugin currenlty...)
![image](https://user-images.githubusercontent.com/31101309/68170546-8ab44200-ff70-11e9-84ec-ad85c3def917.png)


Also on another different note: Should I update Xcode? I´ve noticed that there´s already version 11.2, I thought about updating it in the app store before I posted the bugreport but it just hangs there for some reason and I kinda ended up glossing over it. I´ll try downloading it from the developer site directly.

**Comment by shortercode** [comment]
Well I'm glad the change resolved it, thanks for confirming!

I'm on xcode 11.1 (11A1027) so that might be the difference. Although the example I took the MD5 hash from isn't exactly new, so I would have thought that it would have worked on an older version of xcode. Might vary with iOS version as well I guess.

I would normally advise using the latest major version of xcode at least, as Apple tends to lock out the older versions from being able to release to the store. It's generally a good idea to use the latest version of software, as you will eventually hit an issue that will require a newer version. The further behind you are the harder it will be. However, I can't guarantee it's going to be bug free. I'm not sure what the exact version was but they were advising downgrading to a previous version last week due to a bug that prevented storyboards containing textviews from compiling. That shouldn't affect construct though...

It's very much possible that it times out, this:

> error: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions

is a known error you can get writing long expressions. The message doesn't match what we got, but perhaps is of a similar ilk. There's something about the type inference system which operates in exponential time, I guess timing out is preferable to capping the max input size. Provided you write simple expressions it's not a problem. However, in my search I found a separate bug someone reported a while back where compiling a dictionary literal expression was taking 12 hours!

As for Swift 4.2+ I don't think it will make much difference, I imagine it's mostly new language features which aren't required at the moment. You might get some performance improvement in swift code, but the swift code does very little heavy lifting in Construct so I doubt you'll see any change. So very much up to you.

**Comment by Wackytoaster** [comment]
Thank you! :)
