### ISSUE TITLE
Setting cursor from sprite with DPI > 100% upscales the cursor sprite very badly

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#348]
## Problem description

I've noticed a problem on the project on my laptop compared to my desktop. I use on the Mouse object set cursor from sprite. My laptop's screen is kinda small so I have the DPI increased.

![image](https://cloud.githubusercontent.com/assets/7268697/26411694/28ff208e-40af-11e7-98fe-31cbc83ed831.png)

This lead me to notice the cursor gets upscalled in a very badly manner. I posted pictures of my screen (primitive, i know) because print screen didn't catch the cursor and it was faster than downloading some software for this.

Normal DPI, normal looking cursor from sprite
![normal cursor](https://cloud.githubusercontent.com/assets/7268697/26411801/787354f0-40af-11e7-8088-15fc75b9c5ae.jpg)

Higher DPI, upscalled very badly
![upscalled badly cursor](https://cloud.githubusercontent.com/assets/7268697/26411811/7fd2f5ac-40af-11e7-8ff5-746afae7c838.jpg)

I would normally hide the cursor and set the mouse sprite to be every tick at Mouse.X / .Y however this makes the movement lag a lot, especially in big projects.

## Attach a .c3p

[MouseProblem.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1026098/MouseProblem.c3p.zip)

## Steps to reproduce

1. load the project and preview it, hold left mouse button and right mouse button; notice no difference on DPI 100%
2. set your windows DPI to anything above 100%, preferably 125% (attached pic for win 7)
![540px-how_to_change_dpi_size_in_windows_7-004](https://cloud.githubusercontent.com/assets/7268697/26411877/b2d3f7bc-40af-11e7-80c0-5489185bbaf3.png)
3. go back to the preview and use the buttons again

## Observed result

Notice how badly upscaled the cursor is, looks like it doesn't care about transparent pixels anymore.

## Expected result

I expect the cursor to look as if the sprite would be scalled up.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I think this also affects C2. It's a difficult problem because the C2 engine doesn't control the scaling, the browser or OS does. We can't fully resolve this because what we really need is proper responsive image selection for a cursor (e.g. progressively sized images at 1x, 2x, 3x etc. and pick the best one for the DPR), but the action only takes a single image, so it's hard to see how that can be fitted in.

If the quality is the only thing that bothers you, I'd file a Chrome bug report at crbug.com, maybe they can prepare the image better. But they might say to just use responsive cursors, which we don't have a way to do yet.

**Comment by JeFawk** [comment]
Alright, thanks for the explanation. It helps me to understand better what is happening and how I can work around this.
