### ISSUE TITLE
Audio Looping issue on MacOS

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#3481]
## Problem description

looping audio glitching in mac OS / also potentially in IOS

## Attach a .c3p

[Link](https://drive.google.com/open?id=15HAF3dOf4pnjVgIYAXUankVNDY3CdPIe)

## Steps to reproduce

have a play with the hosted version of the linked c3p
try on windows / android / mac / ios
[Link](https://yamaforce.com/ironpan/open/iosloopissue/)

## Observed result
on MacOS there is a glitch in the audio just before the loop reagrdless of the sample length or playback rate

this does not happen in android or windows chrome

note the loops are verified OK for seamless looping

## Expected result

no looping glitch.

## More details

**Affected browsers/platforms:** 

macOS

also potentially related to #3457 which suggests IOS but have not tested this.

**Comment by AshleyScirra** [comment]
Safari doesn't support WebM Opus so we have to fall back to our own WebAssembly decoder in that case. That decoder appears to add trailing silence to the end of the decoded buffer. The same thing happens in Chrome if it's forced to use the WebAssembly decoder. I'm not sure if we can fix that, since it's essentially a build of ffmpeg, but assigning to @shortercode to see if there is something about the duration calculation that needs fixing.

For reference: the "loop14ms" sound decodes to a duration of 0.013645833333333333 seconds with the browser built-in decoder, and 0.041 seconds with the WebAssembly decoder. The same still happens with longer sounds (2.6125208333333334 seconds vs. 2.62 seconds).

**Comment by shortercode** [comment]
Some audio formats have a minimum buffer length, and then include a label that says to ignore a set number of leading/trailing bytes if the actual clip is shorter than that. I'll need to look at the WebM header information to tell what the situation is but this sounds quite possible.

**Comment by shortercode** [comment]
I'm still reviewing the file here attached an older version of our decoder that emits more debug data, initial findings:
- the file duration is listed as 41ms
- it appears to contain 960 valid samples, and silence after that ( ~ 21ms )
- there's a "discard padding" value which we are currently not looking at which suggests to remove 19854167ns ( ~20ms ) from the end of the buffer
- there appears to be an additional block of audio data in a different format that we aren't processing, but it appears to occur during the discard zone

**Comment by shortercode** [comment]
I have been able to get this _nearly_ perfect, I'm seeing a variance of 1 sample for the first 2 tracks and 3 samples for the last. A sample being ~0.021ms. I can't see any obvious reason for that variance at the moment, but it appears to be inaudible. So I'll think we'll just go with this for now. I'll make a note to take a look in future to see if we can get an exact match, but it's not high priority.

Change will be in the next beta.

**Comment by shortercode** [comment]
I did wonder that, I tried switching between floor and ceil and didn't get the correct values. It's rather frustrating that the 2 values related the discarding samples are in nanoseconds instead of samples so the conversion isn't absolute.
