### ISSUE TITLE
C3 freeze on importing C2 projects

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#3492]
## Problem description

in r176 when Imported C2 .capx projects automatically switches to the C3 runtime and shows  popup message then instead of pressing OK or close button If press **Esc** button then C3 freezes. 
It works fine with OK and close button.
## Attach a .c3p

no file need

## Steps to reproduce

1. import any C2 capx file  compatible to C3 runtime 
2. On popup message appear Press Esc button (don't press OK or Close button)

## Observed result

C3 freeze

## Expected result

popup cancel

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** 
r176
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The precise time this dialog appears exposed an awkward edge case in the windowing system - notice how the dialog appears unfocused. If you click it then press Escape, it works normally. It turns out internally it was allowing the Layout View underneath it to become focused even though the OK dialog was showing and blocking it, which had unexpected consequences.

It was fairly complicated to fix but I think this case should now be properly handled by the windowing system for the next beta. It was a fairly low-level change so hopefully it won't break anything else...
