### ISSUE TITLE
Tesla Model 3 - Cloud Source Picker misaligned

### ISSUE THREAD

**Issue by clrammer** [Scirra/Construct-3-bugs#3493]
## Problem description

I thought you might be interested to know Construct 3 runs on a Tesla Model 3.  However, I'm unable to open my cloud project because the cloud source drop down is offset and I can't tell where to tap.  In fact, all drop downs appear to be affected by this (for example the "Stable releases vs. Beta releases" drop down in Settings" is stuck on Stable because I can't figure out how to tap Beta releases).

## Attach a .c3p

This issue involves the editor, not a project.  I'm unable to navigate to a project to open it.

## Steps to reproduce

1.  Go to the online C3 editor in the web browser of a Tesla Model 3.
2.  Choose Cloud Open.
3.  Choose the "choose source" drop down.

## Observed result

The choices appear far away to the left and tapping on them (or under the drop down where they "should be") clears out the drop down list the same as if you clicked in the wrong spot.

## Expected result

I expected the choices to appear under the drop down and allow me to tap on them.

## More details
I understand if this is the lowest priority bug you have and that there's not a lot of call for being able to run C3 in a car.  However, I thought you might be interested to know it does work and that I would provide browser information.

According to whatismybrowser.org/b/ZTQ6SFV the car is running Chromium 75.  OS: GNU/Linux, Websockets and WebGL supported.

**Affected browsers/platforms:** 

There are no other version of browsers to try in the car.

**First affected release:** 
171.3 stable (I would try to upgrade to the latest beta release, but the drop down bug prevents me from choosing this in the options)

## System details

<details><summary>View details</summary>

Platform Information
Browser: Chromium
Browser version: 75.0.3770.100
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Linux
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (X11; GNU/Linux) AppleWebKit/537.36 (KHTML, like Gecko) Chromium/75.0.3770.100 Chrome/75.0.3770.100 Safari/537.36 Tesla/2019.36.2.1-ea322ad
C3 release: r171.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 462 mb
Storage usage (approx): 48 mb (10.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.
- Nothing is missing.  Everything is OK!

WebGL Information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) HD Graphics 505 (Broxton)
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 255
Extensions:
- EXT_color_buffer_float
- EXT_disjoint_timer_query_webgl2
- EXT_texture filter_anistropic
- OES_texture_float_linear
- WEBGL_compressed_texture_astc
- WEBGL_compressed_texture_etc
- WEBGL_compressed_texture_etc1
- WEBGL_compressed_texture_s3tc
- WEBGL_debug_renderer_info
- WEBGL_debug_shaders
- WEBGL_lose_context

Audio Information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:
- Ogg Opus (audio/ogg; codecs=opus)
- WebM Opus (audio/webm; codecs=opus)
- Ogg Vorbis (audio/ogg; codecs=vorbis)
- WebM Vorbis (audio/webm; codecs=vorbis)
- MPEG-4 ACC (audio/mp4; codecs=mp4a.40.5)
- MP3 (audio/mpeg)
- FLAC (audio/flac)
- PCM WAV (audio/wav; codecs=1)

Supported encode formats:
- WebM Opus (audio/webm; codecs=opus)

Video Information
Supported decode formats:
- WebM VP9 (video/webm; codecs=vp9)
- WebM VP8 (video/webm; codecs=vp8)
- Ogg Theora (video/ogg; codecs=theora)
- H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:
- WebM VP9 (video/webm; codecs=vp9)
- WebM VP8 (video/webm; codecs=vp8)
</details>

![Tesla_model3_cloud_source_picker](https://user-images.githubusercontent.com/58028958/69327917-f4d91200-0c13-11ea-9771-2237ea7d1c89.jpg)

![Tesla_model3_whatismybrowser01](https://user-images.githubusercontent.com/58028958/69327995-13d7a400-0c14-11ea-999a-a71b97bf4b2c.jpg)

![Tesla_model3_whatismybrowser02](https://user-images.githubusercontent.com/58028958/69328064-2fdb4580-0c14-11ea-8a0b-c0e6620b4527.jpg)

**Comment by shortercode** [comment]
It's pretty cool to hear that Construct works on a Tesla, I don't think it's something that has occurred to any of us on the team!

I'm quite curious about how well it runs ( and of course looking at this issue ) but I'm not really sure how we'd test it at the moment. It might be that this affects certain linux versions of Chromium as well so that might be easier for us.

**Comment by clrammer** [comment]
I thought it was neat, too!  The browser in the car was terrible (unusable) until they went to Chromium.  Now it's surprisingly responsive.  Obviously, I don't intend to do serious development work in the car even as a passenger, but I was pleasantly surprised to see I could get logged in and use the app - minus the drop down issues.  As far as running C3 games, I have a silly prototype I'm working on that runs very smoothly in the car.  [https://corysdomain.com/Warforged]  Drag weapons around to make combos.

![Tesla_model3_running_C3_game](https://user-images.githubusercontent.com/58028958/69339268-91a6aa00-0c2a-11ea-9a84-7f39fecc07ef.jpg)


I'm happy to do any testing or answer any questions you guys have if you're curious to know more.

**Comment by AshleyScirra** [comment]
I've never heard of Construct 3 running in a *car* before, that's kind of fascinating!

As for the bug itself, the dropdown is a normal `<select>` element handled by the browser, and so it's the browser, not Construct, that handles where the dropdown is located and how that works. Therefore I don't think there's anything we can do about this. It's possible it was a browser bug already fixed in the latest Chrome (v78, whereas the tesla appears to run v75).

We have in the past bought devices specifically to test a bug report, but I think buying a whole Tesla Model 3 to check this out is a step too far! However this means we have no way to verify the issue or test any changes, which combined with the fact it's probably not a Construct bug, makes it infeasible to investigate. If you really want us to look in to this, the best approach is probably to find a standard Linux desktop system that demonstrates the same issue, since it looks like the Tesla Model 3 is running a Linux OS.

I'd be interested to see Construct's Platform Info output on a Tesla Model 3 - you can find that by selecting Menu - About - Platform Information. However I only ask out of sheer curiosity, it won't affect our ability to do anything about the reported bug.

**Comment by clrammer** [comment]
I totally understand closing the bug.  To answer your question, I actually typed out the contents of the Platform Information in my bug submission above, so have at it! (It's collapsed in the View Details section above my first screenshot).

**Comment by AshleyScirra** [comment]
Ah OK, thanks!
