### ISSUE TITLE
Preview, and editor crash with Move To and Solid

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#3495]
## Problem description

Using Solid On Move To with the "On Move To Hit Solid" condition with multiple instances causes the editor, and it preview to crash.
## Attach a .c3p

https://www.dropbox.com/s/8y5lbn7m3hqj131/movetosolid.c3p?dl=1
## Steps to reproduce

1.Run the project
2.Click anywhere till it stops.
3.

## Observed result

As soon as it bottlenecks the preview crashes. The editor is also affected.
Possible browser as well.

## Expected result

No crash

## More details

Affected browsers/platforms: Chrome

First affected release: Current release, and beta

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Interesting find - it ends up hanging because hitting the solid stops the movement (and stops ticking the behavior), and the 'Move to' action in that event starts the movement (and starts ticking the behavior), all while behaviors are being ticked. This ends up accidentally adding the instance to be ticked again, resulting in an infinite loop.

I've got a fix for the next beta which avoids it being accidentally re-added again and ensures it doesn't hang. Note the fact the editor is affected is because the preview and editor windows share the same thread - enabling worker mode changes that and ensures the runtime hanging does not affect the editor. (That will be enabled by default once some last outstanding Chrome bugs with OffscreenCanvas are fixed.)
