### ISSUE TITLE
Minimized Playable Ad does not execute in Facebook Playable Ad Tester

### ISSUE THREAD

**Issue by EnriqueAlbirCodi** [Scirra/Construct-3-bugs#3511]
## Problem description

After exporting a new project with a clickable image as a fully minimized playable ad and uploading it to the [Facebook Playable Ad Tester](https://developers.facebook.com/tools/playable-preview/), it shows a black screen.

## .c3p File

[MinimumFacebookAd.zip](https://github.com/Scirra/Construct-3-bugs/files/3912364/MinimumFacebookAd.zip)

## Steps to reproduce

1. Export as a Playable Ad with all the compression options enabled (image deduplication, base64 compression, and advanced JavaScript minification.
2. Upload to the [Facebook Playable Ad Tester](https://developers.facebook.com/tools/playable-preview/)
3. Execute the test

## Observed result

A black screen appears.

## Expected result

The first layout of the project.

## More details

The console reports multiple "Violations of Security Content Policy"

**Comment by AshleyScirra** [comment]
The problem is the Facebook Playable Ad Tester is broken. Playable Ads requires everything in one file, so Construct converts images to data: URIs. However the Playable Ad Tester blocks loading of data: URIs with its Content Security Policy. You'll need to report this to Facebook.

p.s. you don't need to use eval, and you don't need to use the scripting feature to call the CTA action. Add the Facebook object and use its CTA action instead.
