### ISSUE TITLE
SVG picture plugin - SVG preview shows wrong line thickness 

### ISSUE THREAD

**Issue by TackerTacker** [Scirra/Construct-3-bugs#3524]
## Problem description

The SVG preview shows the wrong line thickness 
![grafik](https://user-images.githubusercontent.com/18266300/70156466-45407d00-16b4-11ea-8edb-16a6f4f4b2d4.png)

## Attach a .c3p

https://cdn.discordapp.com/attachments/637830595778445322/651809427975831564/SVGPreview.c3p

## Steps to reproduce

1. Open attached .c3p
2. Double click the SVG picture
3. Observe visual differences between the SVG in editor and SVG preview

## Observed result

Visual differences between the SVG in editor and SVG preview

## Expected result

No visual differences between the SVG in editor and SVG preview

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 78.0.3904.108
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 8.1
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
C3 release: r178 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 101 gb
Storage usage (approx): 1.2 gb (1.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 760 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 8
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This looks like a browser SVG rendering bug, or possibly an issue with the SVG itself, I'm not sure which... here's a test page just displaying that SVG in different sized img elements: https://www.scirra.com/labs/bugs/svgscaling/index.html

In Chrome and Firefox the dark grey line thickness seems to stay fixed regardless of the scale of the image. The default size of the SVG is very large, so when downscaled it's too thick. I'm not sure if that's a deliberate feature of SVG or if it's a browser bug. Edge and Internet Explorer seem to work proportionally, but I'm not sure if that's because they're ignoring some kind of fixed-width feature of SVG.

It might depend on the SVG and I don't know much about this area - you can file it as a browser bug if you want and reference the test page above and see what the browser makers say.

**Comment by TackerTacker** [comment]
As long as it only affects the preview.
I thought it was a simple fix since everything looks fine in game and editor.
