### ISSUE TITLE
Can't pick objects by comparing their instanced variable inside functions on the tick they're created

### ISSUE THREAD

**Issue by cb130felix** [Scirra/Construct-3-bugs#3554]
## Problem description

Pretty much the tittle. 

## Attach a .c3p

https://drive.google.com/open?id=1Tezh2SQf0EDTM4fGRMz_k0iUkVgZ9ofC

## Steps to reproduce

1. Run the project in the "Main" layout and see that the object created is not destroyed by the "destroySprite" function
2. Go to the event sheet and enable the "wait 0 seconds" action  and restart the project
3. See that now the object is destroyed, since the function runs 1 tick after the object is created

## Observed result

Can't pick object on the tick they're created inside a function by comparing instanced variables.

## Expected result

For objects to be able to be picked inside functions by comparing instanced variables on the tick they're created.

## More details

I tried  picking the object inside a function by it's UID in a diferent test and it looks like it works fine. Only picking by comparing the object stanced variables that doesn't seem to work inside functions.

Also important to notice that you can reference the "sprite" instanced variable inside the "on created" trigger even though its placed before the "destroySprite" function in the event sheet.

I'm using construct 3 r180 on chrome

**Comment by AshleyScirra** [comment]
This is a long-standing quirk of the event engine. In order to maintain the performance and stability of the engine, newly-created instances aren't really created until the end of the next top-level event. They can't be picked by other events until then. There are a couple of exceptions to this, including the fact the created instance is picked in its own event and all sub-events so it can be initialized, and "pick by UID" works so you can use the common pattern of passing an instance to a function by its UID. There doesn't seem to be any good reason to use a custom ID here, so it should be easy to work around.

**Comment by cb130felix** [comment]
> newly-created instances aren't really created until the end of the next top-level event. They can't be picked by other events until then. 

This seem to be a huge limitation imo, there are lots of cases were picking by comparing instanced variables is useful. I used a "customId" in the example just because it was covenient for the minimal project but the way things are now you can't pick objects on the tick they're created inside functions by comparing string variables for example.

So even though I can pick objects by UID in their first tick inside functions, I can't reference their variables so I can't execute certain actions depending of the startings value of these variables. Like checking if a boolean variable is true or false, or if a string variable has a certain name, and then executing some actions.

Is there no way for this to be reconsidered?

**Comment by AshleyScirra** [comment]
Running events involves using complex in-memory data structures, and creating instances changes those data structures while they are in use. This results in crash bugs which users reported and caused us to change it to work this way instead. As far as I can tell there is fundamentally no way to avoid this restriction without either imposing a very high performance overhead on the entire event engine, or allowing the crash bugs to happen, neither of which are sensible options.

Meanwhile there are two clear workarounds:

1) Create and initialise objects in the same event (which is probably a good way to organise things anyway)
2) Pass instances to functions by their UID, which is a common pattern that still works this way due to special handling in "pick by UID".
