### ISSUE TITLE
Saving causes a page unresponsive cycle about 70% of the time that takes 5 minutes to resolve

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-3-bugs#3559]
Since r180. I am having issues saving my project. There is nothing specific that I am aware of that is causing the issue in terms of replication. It does appear to occur more often if I use cloud save vs local storage saving. Downloading the file even causes the crash also. I can't pull up the console to find what might be causing the issue as it appears to freeze the entire tab. It remains at 0% for around 5 minutes and then suddenly starts saving the project. 

My project has around 100 event sheets, and a lot of events, objects, etc. I can go through the process of removing chunks if need be, but I hope it doesn't come to that.

Best.

1Step

**Comment by OneRepCloser** [comment]
I do get this on a save that doesn't freeze: main.js:2 Error while parsing the 'sandbox' attribute: 'allow-storage-access-by-user-activation' is an invalid sandbox flag

**Comment by AshleyScirra** [comment]
I'm afraid there's nothing we can do about reports like this. At a minimum we need a crash report (and the sandbox error message you mentioned is unrelated and has no consequence), or a project that demonstrates the issue. However even this is commonly insufficient for us to fix an issue, which is why we have the guidelines requesting various details to ensure we can properly investigate the problem. If you can provide more information about the problem, please file a new issue and follow the bug report template as far as possible.

**Comment by OneRepCloser** [comment]
Yeah I understand. 👍
