### ISSUE TITLE
Speech Synthesis on Mobile Issues

### ISSUE THREAD

**Issue by Ranmekler** [Scirra/Construct-3-bugs#3575]
Hi! 
The speech synthesis doesn't work on mobile platforms.I tried running the "Speech Synthesis Example" coming with C3 on four different Android and two IOS devices and It didn't work. The example didn't show any massage that it is not supported by the device.

However, I tried an app I'm making on 40 different phones and one of them actually worked (Don't know which OS).

My region is Israel. If it helps.. But I'm using it for English only.

I make language games. Speech Synthesis is a very important feature for many Ed-Tech apps.

Thank you!
Ran

**Comment by AshleyScirra** [comment]
Support is determined by the browser/OS, not Construct, so in general there's nothing we can do about this.

Speech synthesis is not yet supported in Android apps because it's not supported in the WebView. Follow this issue for updates: https://bugs.chromium.org/p/chromium/issues/detail?id=487255

I'd imagine it's a similar situation on iOS if it's not supported either there, in which case you'd need to take it up with Apple.
