### ISSUE TITLE
Play At Object producing distorted sounds

### ISSUE THREAD

**Issue by jobel0092** [Scirra/Construct-3-bugs#3578]
## Problem description

When using the Audio object's Action "Play At Object" the sound is sometimes distorted. It doesn't happen every time, but you can replicated the issue easily if you restart the preview a couple of time.

## Attach a .c3p

https://drive.google.com/file/d/1b6NpRzEEfBNbTRBA9e3p2R0FbLrXzUGA/view?usp=sharing

## Steps to reproduce

1. Set a listener for the Audio Object
2. Make some sprites at different positions
3. Play a sound at a specific object triggered by a keyboard event

## Observed result

You will hear the sound (at least 50% of the time) be distorted or have pops and stutters
## Expected result

Would expect the sound to play normally as it would with using the Play function (not at object)
## More details

only tested in Chrome
**Affected browsers/platforms:** 

I'm using the current stable version. r171.3
**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
I think this is likely to be a browser issue, but will see what @AshleyScirra has to say.

**Comment by AshleyScirra** [comment]
The audio playback engine is part of the browser, not Construct, so in general these types of issues are not Construct bugs.

I could reproduce very small, subtle artefacts in Chrome. They were difficult to hear though. It sounded a bit like a minor amount of clipping. I tried in Firefox and it did not seem to reproduce there, which is further evidence it's a Chrome issue.

So I think the best thing to do would be to report this to Google at crbug.com.

**Comment by SnipG** [comment]
I think problem is much more severe then just minor case. Firefox it indeed does not show up so often.
But firefox crash/freeze etc with audio or music or something, so i did not test much.

[AudioMaster.zip](https://github.com/Scirra/Construct-3-bugs/files/4041647/AudioMaster.zip)
Use mouse and move smaller Construct logo around - hear few artifacts.
Go settings enable full unlimited ticks instead vsync. See glitces intensify a lot. This pretty much render music with location unusable. 
Unlimited ticks did not increase glitches on firefox(but i did not test much).

**Comment by jobel0092** [comment]
I agree with SnipG that its a lot more severe than a "minor issue".  The audio sounds broken and would be 100% unacceptable for a finished game.   I'm extremely surprised this is being closed instead of trying to add some other functionality, like adding pan or some other way to achieve the same effect.  Play At Sound may be on Chrome's end, but the Construct functionality of being able to use "positioned audio" with volume/pan is broken.

**Comment by AshleyScirra** [comment]
Positioned audio is implemented entirely in the browser engine. Construct's code only sets the position of the audio source and the listener. I can't see any way that we could have any impact on this, hence the suggestion to report it to the relevant browser vendor, who are probably the ones in a position to do something about this.

**Comment by SnipG** [comment]
[MasterAudio.zip](https://github.com/Scirra/Construct-3-bugs/files/4045593/MasterAudio.zip)
Open example: 
*click preview -> see glitch
*Disable play at object and enable play at position -> preview hear no glitch

Using: play at position vs play at object. Where play at position does not bug, when object is involved glitch appear.

There is no way to use set listener position, so using listener only with object in this case also cause glitch. So if you can test listener without object and it does not glitch. Then problem cause is from object handling for audio.

Why 1 action work and other does not? Is objects involved source of this bug?
Just something before sending it to chrome.

**Comment by AshleyScirra** [comment]
@SnipG - that happens only because you have set unlimited ticks, which the audio engine is not designed to handle. That option is for performance testing only and no games should be published with it enabled, so any bugs which happen only in that mode are not important and won't be fixed.

**Comment by jobel0092** [comment]
@AshleyScirra does Construct have the ability to access Chrome's Audio Engine's panning Left/Right?  I can't imagine you couldn't.  If so adding a 'pan' parameter to the Audio Object could be a work-around for users.

**Comment by SnipG** [comment]
Made report to: http://crbug.com/1041182

I used unlimited ticks only because it made bugged behavior more clear and the fingerprint of the cracks happening there where very similar. So whatever things makes them happen in unlimited ticks also cause them in vsync mode. But in vsync mode sometimes cracks never occur at all and but next time happen almost constantly. Which renders it heavily unusable as it is.

**Comment by SnipG** [comment]
As ever, chrome guys need smaller reproduce example!

Side note: the sound cracking on mobile is much much bigger. Strange nobody else have heard it or made issue report here or crbugs. Strange times.

**Comment by jobel0092** [comment]
@SnipG you need to have a sustained sound to really hear it well.  But when you use it throughout your project even short sounds... like I did, it ends up making the entire game feel "glitchy" and buggy.  It's not good, even a mild pop is not professional and non-audio-professionals will never notice those little pops.  However when players play the game they will "feel something is off" it's often hard for them to articulate, but they know something is wrong.  To my ears, its hell.

**Comment by SnipG** [comment]
It does not matter. It's clearly bugged.
Just navigate to: https://snipg.github.io/Bugs/AudioPosition_Bug/  with your phone. The few cracky sound on pc, will multiple x100 on phone. With C2 engine version example, i used different music by mistake, which makes cracks less noticeable. But chrome guys should use code and  other means to track it down. Does not matter if we hear it or not. Because even on construct audio analyser the cracks were clearly visible.
Bad case is if thous cracks come from engine itself and how it handles code or something. But nevertheless chrome should fix it asap.
Not to mention chrome audio guys should have their own examples and test cases!

**Comment by SnipG** [comment]
Just a question for Ashley, regards of audio issues, as this issue is kinda freezed on both sides.
As a user, there is almost nothing one could do at this point to advance this!
     *Changing C3 audio settings indeed can disappear/remove the random cracks, but new ones appear with different dynamic. How user can  know which ones are bugs or expected outcome of the setting
     *There is no reference point, c3 uses very advanced audio settings. I have searched countless js audio examples, without any luck on minimal problem example. At this point i must litterly learn whole js(browser) audio system to point, where i could litterly code C3 similar audio system myself. So at that point i would know what is expected what is not. 

Ofc chrome audio or even whole web audio could be problematic for countless people and it is indeed unreasonable for single dev(Ashley), to go, test and get fixes on multiple platforms. But as C3 user, navigating in darkness is strange too.

Some advanced guide would help, but it could'nt cover everything. Or there is one already? similar to some other internal architecture, like draw calls etc?
