### ISSUE TITLE
Previous "Function Return Value" actions are ignored if there are multiple "Function Return Value" actions.

### ISSUE THREAD

**Issue by ChadoriRebornXD** [Scirra/Construct-3-bugs#3585]
## Problem description

Previous **Function Return Value** actions are ignored if there are multiple **Function Return Value** actions.

It's a simple enough event.
![image](https://user-images.githubusercontent.com/31282960/72371506-7eeab600-373f-11ea-9427-c6d19d1f6fdc.png)

Not sure if this is a bug, or by design, but this scenario could make it confusing, for those unaware that the Functions can't be finalized with the return call.

![image](https://user-images.githubusercontent.com/31282960/72371566-9c1f8480-373f-11ea-9f47-18baea71d23c.png)

**Thanks!**

## Attach a .c3p

[Issue Report.zip](https://github.com/Scirra/Construct-3-bugs/files/4060760/Issue.Report.zip)

## Steps to reproduce

1. Preview, check the **Browser console**.

## Observed result

Previous **Function Return Value** calls are ignored.

## Expected result

First **Function Return Value** call should have ended the function.

**Comment by AshleyScirra** [comment]
This is currently by design. Note the phrasing "set return value" - it is assigning an internal value that is automatically returned when the end of the function events are reached. It does not mean "exit function now" (which return statements in programming languages normally do). It would also be difficult to change this since it would count as a breaking change and there might be a lot of projects out there relying on the ability to change the return value before exiting.

**Comment by ChadoriRebornXD** [comment]
Oh, I see. Alright, no problem.
