### ISSUE TITLE
Animation List names sort error

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#3587]
## Problem description

[Sprite - Properties - Initial animation](https://imgur.com/03oawOD)

## Observed result

Animation 1
**_Animation 10
Animation 11
Animation 12_**
Animation 2
Animation 3
...
Animation 9

## Expected result

Animation 1
Animation 2
Animation 3
...
Animation 9
**Animation 10
Animation 11
Animation 12**

**Comment by AshleyScirra** [comment]
This is actually the correct sorting order when using alphabetic sort. It's possible to handle the numbers as you suggest using a different and more advanced sorting algorithm. However nothing else in Construct uses this, and I'd advise renaming your animations to something relevant to what they are rather than leaving them numbered, which makes this a moot point.

**Comment by broknecho** [comment]
@XHXIAIEIN Also just name your first animation by padding left with 1 zero.  So:
`Animation 01`
`Animation 02`
etc.

Using the `zeropad(1, 2)` system expression, you can still using number indexes but get your `01` like number from that.
