### ISSUE TITLE
Search result page won't remember its size and position.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#3601]
## Problem description

The search result page won't remember its position and size. It always opens at a default location with a default size.

## Steps to reproduce

1. In the event, search something with CTRL+F
2. Adjust the result page's size and location then close it.
3. Search something again.

**Comment by AshleyScirra** [comment]
This appears to have also been filed as a suggestion here: https://construct3.ideas.aha.io/ideas/C3-I-1192

Closing this issue to avoid duplication. For the record this actually appears to be pretty difficult: since the results are a dockable bar, they don't fall under the existing dialog system that remembers state. So we'd need to basically invent a whole new layer for remembering state in the docking system, and currently none exists.
