### ISSUE TITLE
Function action: "Set return value" is in the wrong section

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#3613]
When you go to add an action with the function object, in the list of all the function names you've made, hidden within that list is the "set return value" action, this is different from all the other ones on the list. It seems like putting it there was a mistake or an oversight.

__________________

See how there's divisions between "function maps" and my own "functions":

![image](https://user-images.githubusercontent.com/5744908/73153227-1fb97800-4127-11ea-9596-e1712b2e9efb.png)

In my list of functions, the "set return value" is hiding among them, it's the only one not like the others!

![image](https://user-images.githubusercontent.com/5744908/73153273-4bd4f900-4127-11ea-905e-d8cf67552479.png)

**Comment by AshleyScirra** [comment]
It's currently by design. Returning a value is not to do with function maps, so it's not suitable for that group. Instead it goes in the default "Functions" group, which is the same group functions with no category go in. The assumption is that if you have lots of functions, you'll use categories to organise them, so there won't be lots of functions in the default category along with 'Set return value'.

What were you expecting it to do instead?

**Comment by alastajj** [comment]
What I was expecting (compare with previous picture): 

![image](https://user-images.githubusercontent.com/5744908/73219121-7ec2cf80-41af-11ea-94f4-12ad2a5054cd.png)

I didn't notice the category thing, that looks great for future games! But still didn't expect it to be mixed in with your own.

**Comment by AshleyScirra** [comment]
That screenshot shows something the UI never does, which is have a group with no title. Are you just saying that the 'Set return value' should go in its own group? I'm not sure what that would be called... "Functions: built-in" would be confusing since the editor already refers to built-in functions in some places...

**Comment by AshleyScirra** [comment]
I just moved the 'Set return value' action to its own group named 'Function return value' for the next beta, hopefully that will do.
