### ISSUE TITLE
Text object not respecting character spacing when having tags between letters

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#3626]
## Problem description

This appears to be the same issue as #2850, but with the text object instead of sprite font. That is, putting bbcode tags in-between characters can mess up their spacing.

## Attach a .c3p

[TextTagSpacingBug.zip](https://github.com/Scirra/Construct-3-bugs/files/4138287/TextTagSpacingBug.zip)

## Steps to reproduce

1. Just preview the layout. The events toggle the string between "Text" with and without tags after each character.

## Observed result

The spacing is changing each time the variable is toggled.

## Expected result

The spacing should remain the same.

## More details

**Affected browsers/platforms:** Only tested on Chrome / preview

r184, assuming previous releases.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 79.0.3945.130
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
C3 release: r184 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 447 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I don't think it's the same issue as the SpriteFont issue. For starters, Text objects don't have a character spacing property.

I think what is actually happening is it is altering [kerning](https://en.wikipedia.org/wiki/Kerning), which is unique to Text objects. (SpriteFonts do not use kerning, although you can get a similar effect with per-character spacing.) Notice how with no styling the "e" of "Text" appears just underneath the edge of the "T"; it's actually overlapping the "T" character box, but without any visual overlap. In order to apply this kerning, the text renderer must have access to the full string so it knows what the next and previous characters are.

When you set BBcode on individual characters it forces the text renderer to measure and render characters one at a time. This means it doesn't have access to the full string when rendering text, and doesn't apply kerning, causing a different spacing (and you can see in this case the "e" moves to the right so that it does not overlap the "T" box at all).

Unfortunately the canvas text rendering APIs only allow us to measure and render text all with the same style, so I cannot see any feasible way around this. Browser's HTML layout doesn't have this problem, so presumably they do something smarter, but we don't have access to the same layout engine from a canvas. Text layout is actually absurdly complex and full of labyrinth caveats and adjustments covering all the world's languages; I also really don't want to have to run down that rabbit hole with our own simple little BBcode parser. Anyway this suggests a possible workaround, of using text in a HTML element floating over the canvas.
