### ISSUE TITLE
User Media Camera Freezes on iOS (HTML Web App)

### ISSUE THREAD

**Issue by Gilel** [Scirra/Construct-3-bugs#3651]
## Problem description

Using User Media Camera on iphone sometimes freezes the camera, until restart of the layout. 
This does not happen in the remote preview, ONLY when uploading to a server like Itch.io etc. 
The current version can be found here - https://twinsen.itch.io/camera-app

## Attach a .c3p

[Taking screenshots (1).zip](https://github.com/Scirra/Construct-3-bugs/files/4216206/Taking.screenshots.1.zip)

## Steps to reproduce

1.Upload game to a server because it does not happen in "Remote preview"
2. Press button to approve camera while on iOS
3.Camera will probably freeze

## Observed result

The camera image freezes but app is still running
## Expected result
The camera should not freeze

## More details

This is for the election in Slovakia, the campaign starts on the 20th (3 days from now) so it will be incredible if we can get it working before

**Affected browsers/platforms:** 
Safari

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
As far as I can tell, this is a bug in iOS. I filed it with Apple here: https://bugs.webkit.org/show_bug.cgi?id=207888

It seems the only option is for Apple to fix it in the next iOS release. However unfortunately these days they have been very poor at dealing with issues, so it may take a very long time. I did find a couple of workarounds though which I noted in the report with Apple which may help you (i.e. tapping the video icon off then on again, switching tab, lock/unlock device all gets video working again). Anyway since this is out of our hands, closing this report, we will follow up at the linked issue.
