### ISSUE TITLE
Object added to wrong layer when active layer is locked/invisible

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#3655]
## Problem description

When selected layer is locked/invisible, objects are added to a previously selected unlocked layer.
This happens "silently", without any warning message.

## Attach a .c3p

N/A, here is a gif:

[![bug.gif](https://i.postimg.cc/wMQMT2Gj/bug.gif)](https://postimg.cc/8fsNZRG2)

## Steps to reproduce

1. Select an unlocked layer.
2. Select locked layer
3. Insert or paste any object.

## Observed result

Object added to the wrong layer.

## Expected result

Object should not be added at all. Or it can be added to the currently selected layer with a warning message.

## More details

**Affected browsers/platforms:** all

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.106
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.106 Safari/537.36
C3 release: r187 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 127 gb
Storage usage (approx): 621 mb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_draw_instanced_base_vertex_base_instance
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_multi_draw_instanced_base_vertex_base_instance
WEBGL_video_texture
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
It's working correctly. Your video has cut off the relevant part: the active layer indication in the layout view. When you select a locked layer, it does not change the active layer. This is by design and in response to prior user feedback asking for this change to avoid accidentally inserting objects to locked/invisible layers.

**Comment by dop2000** [comment]
When both the Layers bar and Properties bar show that "GameOverMenu" layer is selected, but the active layer is different - this is confusing and feels very much like a bug.. 
There must be a better way of preventing adding objects to locked/invisible layers.

**Comment by AshleyScirra** [comment]
Well, if you want to change the properties of a locked/hidden layer, you still have to select it. However it does not change the active layer to prevent you adding objects to a locked/hidden layer. I'm not sure what else could be done, do you have any proposals?

**Comment by dop2000** [comment]
To tell you the truth, I never even noticed that there is a caption on the layout showing active layer, and didn't know that the active layer can be different from the currently selected layer. This is definitely confusing.

I think the most fail-proof and logical solution would be this:
1. When you click a locked/invisible layer, it becomes selected and also active. 
2. If you try to insert an object to a Locked layer, the object is not added and you get a warning message.
3. If you try to insert an object to an Invisible layer, the object is added. And you also get an information message, saying that the object has been added to invisible layer.

**Comment by AshleyScirra** [comment]
Step 2 will be confusing because there are actually two steps to creating a new object: creating a new object type, and then placing the instance. If you block creating the object type, then you can't even place objects that have no placement on a layer (e.g. Mouse). If you block placing the instance, then you allow the user to create an object type, then tell them they couldn't place it. So you're left with an object type with zero instances. Both cases seem like equally likely ways to confuse someone.

**Comment by dop2000** [comment]
I see.. Well, in this case, maybe allow adding objects/instances to locked layers with a warning message. The same way it works now when all layers are locked.
It will still be better than when object is added to some other layer, not the one currently selected.

**Comment by SnipG** [comment]
This change about active layer is different in certain case, is indeed somewhat confusing. I mean for thous who have used editor before. For someone uses it first time it could make sense.

I also never looked for that Active layer sign, did not even know it was there(I never needed, so my brain must have excluded looking at it). 

All of this is still all behaind ones Behavior. Something that could be done before, now cannot.

If there would be any change how it works.  Then my solutions would be:

- Locked layer selected and active. Dragging new object from Project bar to layer. 
     *Nothing happens.
or
     *A message is shown. Layer locked

- Suffling though layers, selecting locked layer, missed to unlock. --> Adding object
     *Little pop-up bubble message near active layer sign. "Object added to - layer name"

- Locked layer selected, wanting to create new object. 
-->From Insert new object
    *Only globals objects listed. Somewhere in dialog, red text "Layer locked"
--->From project bar - Add new object type. Everything is listed. 
    *When object placement cursor appears and users click on locked and active layer. -> pop-up: Layer is locked...layername.

This active layer system could stay. But it would need improvement. Why i never looked at it, because it was never needed. 

But why would that indicator even be there and what would make it useful -> User can click on active layer: layer name. And instead it shows New instances would be places on this layer, a small compaxt menu opens and user can select layer. - So Layer dialog is never needed! And would save more space on editor, which is already very full and small.
