### ISSUE TITLE
TouchID with mouse bug

### ISSUE THREAD

**Issue by Milesloh** [Scirra/Construct-3-bugs#3665]
When using the mouse to simulate touch, touch.touchID is always 1. There is no warning about this in the documentation. 

The problem is present in Construct 2 also but touch.touchID is always 0

Any project with the touch object. [Example](https://1drv.ms/u/s!AjosfNFG8jCjofpXvLSA_V7p3ljMFA?e=t7fYHh)

## Steps to reproduce

1. Add touch object
2. use debug to look at touchID with mouse and touch
3.

## Observed result

TouchID should increase with each new mouse down like it does with touch. 

## Expected result

TouchID is always 1

## More details

**Affected browsers/platforms:** 

**First affected release:** 
All versions of C3 and C2

## System details

<details><summary>View details</summary>

PASTE HERE
[TouchID Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/4239512/TouchID.Bug.zip)

</details>

**Comment by SnipG** [comment]
From documentation:
Use mouse input: However, only single-touch input can be simulated with a mouse.
Return the unique ID of a touch (which is an arbitrary number)

But you should never relay on specific TouchID, and should use TouchIndex instead.

Why do you think "TouchID should increase"?

**Comment by Milesloh** [comment]
TouchID increments with each successive touch when they are real touches. It is meant to be a unique identifier for each touch. From the manual:

"Return the unique ID of a touch (which is an arbitrary number)"

Two separate touches shouldn't have the same TouchID.


________________________________

**Comment by SnipG** [comment]
I also had similar issue long time ago. when xiaomi phones are set by default to do sceenshot with 3 touch, which does not trigger screenshot durning app use but will mess up touch controls.

Anyway Ashley replay from that post:
These APIs assign pointer IDs differently: pointer events seem to use an ever incrementing number for the ID, but touch events reset to 0 when all touches are released. Since your demo shows the number 0 when nothing is happening, you can't see a touch that also has the ID 0. You can see it working correctly if you hold down multiple touches, then the number increases.

In both cases, it is still working correctly: the only guarantee made about pointer IDs is that they are different for each simultaneous touch. This means either approach to assigning IDs is still valid - and some browsers use other approaches, e.g. using a timestamp for the pointer ID, or just a random number. Your events should not depend on specific pointer IDs, because they aren't guaranteed to be anything in particular; if your events correctly take this in to account - and they should because other platforms could work differently - then they will work either way.

**Comment by AshleyScirra** [comment]
This is not a bug. The only guarantee made about touch IDs is that they are different for all simultaneous touches, so they uniquely identify an active input. There is no guarantee that real touches will keep incrementing their IDs; touch IDs could be random numbers, or it could recycle past touch IDs that have since ended. This is why the documentation refers to it being an "arbitrary number". The particular values of touch IDs does not matter and should not be depended on in any way. Therefore the handling of the touch ID for the mouse input is correct no matter what ID it is assigned, as long as no simultaneous touches have the same value.

**Comment by AshleyScirra** [comment]
We've had a few cases of issues filed along the lines of "touch IDs have some particular value", so I added a note to the manual for the TouchID expression emphasising that touch IDs aren't assigned any particular value.
