### ISSUE TITLE
JS Linter considers import and import() to be the same

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#3672]
## Problem description

The JS linter marks an error when it sees import, but it does too when it seems import() which should work fine, even outside of modules.

## Attach a .c3p

n/a

## Steps to reproduce

1. Open an empty project
2. Create a script
3. Write `import('https://unpkg.com/preact?module')`

## Observed result

The linter freaks out

## Expected result

The linter should not freak out

## More details

As a proof that this shouldn't happen, I'm doing this terrible workaround instead:

```JS
eval(`globalThis.myImport = (arg) => {return import(arg)}; console.log("done")`);
Promise.all([
    globalThis.myImport('https://unpkg.com/preact?module'),
    globalThis.myImport('https://unpkg.com/htm?module')
]).then(([{ h, Component, render }, {default:htm}]) => {
    // Initialize htm with Preact
    const html = htm.bind(h);

    const app = html`<div>Hello World!</div>`
    render(app, getApp());
})
```

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Minimal repro since one wasn't provided: [parse-dynamic-import.zip](https://github.com/Scirra/Construct-3-bugs/files/4281759/parse-dynamic-import.zip)

This looks like an awkward bug in acorn, the JS parser we use for validation: https://github.com/acornjs/acorn/issues/809

It's difficult to work around since it throws a syntax error and fails to parse the rest of the file. In the end I added the acorn-dynamic-import plugin and that seems to have sorted it, so it should be working again in the next build.
