### ISSUE TITLE
It should not be possible to delete a Group containing events without warning.

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#3692]
I thought this was fixed in the past but maybe not.

use any official demo with groups as an example.

-- 

Groups can be deleted accidentally by brushing delete or back space key without any warning. Then the user can carry on oblivious to the error.

it is not the same as accidentally deleting a single event that can be easily recreated once realized as as groups can sometimes contain 1000s of events. 

Groups are too important to be allowed to be deleted in such a way without warning.

**Comment by AshleyScirra** [comment]
This is currently by design. There's lots of ways to delete large amounts of events, e.g. by shift+select, select all, long sub-events, and so on. Targeting only groups would not do anything to fundamentally avoid this. Even accidentally deleting just one important event out of thousands could cause a lot of confusion. Adding confirmation prompts would probably be too annoying so people would either turn them off or learn to ignore them, making them ineffective. And at any time you can press undo to bring them back. I don't think this counts as a bug, if you think we should make other design changes I'd suggest discussing them on the forum first to work out a reasonable design that is useful and not too annoying for general use, and then posting it to the suggestions platform.
