### ISSUE TITLE
Problem with Guided Tour in Spanish when entering code

### ISSUE THREAD

**Issue by DavidCB14** [Scirra/Construct-3-bugs#3697]
## Problem description

In the guide, when you reach to the step of introducing the angle and position, you can get to introduce the 2 parameters but when you press done you get a syntax error and you can't continue neither forward nor backward

## Attach a .c3p

No .c3p involved only follow the Guided Tour 'Beginer's Guide
![guide-sintax-error](https://user-images.githubusercontent.com/11505355/76290945-6fee3300-62ac-11ea-8103-3725494b6cc6.png)

'

## Steps to reproduce

Put construct3 in Spanish and restart the application
Click on menu item Guided Tours -> Beginers Guide

Follow the steps of the guided tour until you reach the point where you give the angle coordinates manually as mouse.X and mouse.y
then when you click done there is a syntax error

## Observed result

Cannot continue with the guide and the application is blocked

## Expected result

To be able to finish all the steps and complete the guide

**Affected browsers/platforms:** None

**First affected release:** r190beta

**Comment by AshleyScirra** [comment]
The problem is no translation has been provided for the guided tour in Spanish yet. Guided tours set language-specific terms for the names of objects, and expressions use those language-specific names. So if there is no translation it still may not be able to use the English expression. The standard way the language system displays an English fallback is in square brackets, but even if it didn't show this, there would be a syntax error as the English name "Mouse" does not exist.

The only way I can think to deal with this and ensure you can always proceed, is if the translated expression is missing, just insert the default value (0). This means the game won't work properly at the end, but at least you can proceed to the end of the tour with an incomplete translation. I've made that change for the next release.

**Comment by DavidCB14** [comment]
Even if I type 0 in the fields, the guide changes it to [mouse.x] and [mouse.y]

**Comment by AshleyScirra** [comment]
I was describing the change made for the next release.
