### ISSUE TITLE
platform jump when another platform is above is not always accurate

### ISSUE THREAD

**Issue by trueicecold** [Scirra/Construct-3-bugs#3699]
## Problem description

Player has Platform+Solid, Player2 has Platform. Player2 jumps on top of Player, and then Player jumps.
Everything is ok that way. However, if it's the other way around (Player2 has solid and Player doesn't), the sprites collide into each other when jumping.

[platform_bug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/4311881/platform_bug.c3p.zip)

## Steps to reproduce

pressing C will switch solids between the 2 players so you can test it.

1. Have player jump on top of player2, and jump with player2.
2. Press C
3. Have player2 jump on top of player, and jump with player.

## Observed result

Some pixels from player are "inside" the player2 sprite. The other way around works just fine, for some reason.

## Expected result

Both cases should work ok.

## More details

Oddly enough, we've confirmed this is an issue with c2 as well.

**Affected browsers/platforms:**

Chrome Version 80.0.3987.132, FireFox 72.0.2

**First affected release:** 

Tested on C3 Stable (189.2) and C2 version 275

**Comment by AshleyScirra** [comment]
Sorry, this isn't a case we can support. Movement behaviors are not designed to be used with the 'Solid' behavior. In theory this makes the object block its own movement, because the behaviors are designed to never allow them to overlap a solid. However the engine currently ignores this, but then other weird circumstances can emerge.

In particular this case also depends on the precise order the engine ticks behaviors, which does not currently use any specific order. In other words there is a circular dependency between processing the object movements, because moving one may or may not require a previously moved object to be moved again. This is a notoriously difficult problem to resolve and is one of the reasons we don't support this case I'm afraid. Solids are meant to be static scenery or moving platforms, not actual interactive players themselves.
