### ISSUE TITLE
Failed to create advert in iOS

### ISSUE THREAD

**Issue by joosh00** [Scirra/Construct-3-bugs#3707]
## Problem description

Failed to create ads (banner, interstitial, and video) in iPhone

## Attach a .c3p

[https://drive.google.com/file/d/1v8WEqWgDDThzSNAOY4TfbboyUf-uxErp/view?usp=sharing](url)

## Steps to reproduce

1. Open the construct file
2. Export to the iOS xcode file
3. Open the file with xcode
4. Build and run it to iPhone
5. Tap the black button for create ad
6. Tap the grey button to show the ad

## Observed result

Error message is -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'

## Expected result

Able to create the ad and can show the ad

## More details

I tried to the ads in my dummy project before I moved it to the original project. It's keep failing to create ads (banner, interstitial, and reward video) in iPhone. I built and ran it through xcode and connected to my iPhone. I've crosschecked the iOS app ID and the publisher ID, both are correct. I've checked the testing mode in the mobile advert. I dunno it's a bug or just misconfiguration.

**First affected release:** 
I'm using latest version of Construct, r189.2

**Comment by AshleyScirra** [comment]
It doesn't work because you haven't specified a privacy policy URL in the Mobile Advert properties. The documentation notes this is required, and a message indicating this also appears in the Xcode log.

Also your events don't make sense: you only try to show the video advert if the video is *not* loaded, which means you only try when it will fail.
