### ISSUE TITLE
"On finished" tween behaviour issue

### ISSUE THREAD

**Issue by ArtRow** [Scirra/Construct-3-bugs#3716]
## Problem description

Tween behaviour **'On finished'** does not work with copies of the tweened object.

## Attach a .c3p

[TweenIssue.zip](https://github.com/Scirra/Construct-3-bugs/files/4351416/TweenIssue.zip)

## Steps to reproduce

Open attached file

1. Click on the left green square
2. It starts tween (moves down)
3. After tween finish 'On finished' triggers its actions
4. Other 2 squares should move down, but just one of them wil start move (different sprite)

## Observed result

Conditions inside tween 'On finished' won't work for copies of that object (doesn't matter how we specify them)

## Expected result

Conditions should work for copies of tweened object as well

## More details

**First affected release:** r189.2 Stable

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r189.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 44 gb
Storage usage (approx): 662 mb (1.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1660 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by BonzerKitten7** [comment]
Was about to report this issue! It's clear that some of them finish before and some after each other, even if they have the exact same value in the "Time" property.
https://i.imgur.com/qfVVAZV.gifv

**Comment by DiegoScirra** [comment]
@ArtRow This is not a bug, it looks like your events are wrong.

When you use a trigger condition, denoted by the green arrow next to the condition. The instances that meet the condition are picked to be used exclusively for the rest of the block. That means that the sub condition **Sprite.ID = "duplicate"** can never be met, because only the instance that started the tween, and later finished it, is taken into consideration.

One quick way of forcing the picking system to test all instances of an object is to add a **Pick all** condition, and then put your events under that condition. Then the picking system will check against all existing instances and **Sprite.ID = "duplicate"** condition will be met.

Below is an example project showing what I just wrote.

[TweenExample.zip](https://github.com/Scirra/Construct-3-bugs/files/4422458/TweenExample.zip)

Be mindful though, that in this particular project this will cause the duplicate green square and the red square to move down indefinitely because **On Finished** condition is always met later on. You could solve that by changing the tags used by those tweens.

**Comment by DiegoScirra** [comment]
@BonzerKitten7 That seems like a different issue, after staring at the gif for a little while I think I understand what you mean. You should open a different issue. With an example project if possible, that would be of great help.
