### ISSUE TITLE
[share plugin] “This build is missing export compliance information.”

### ISSUE THREAD

**Issue by SalmanShhh** [Scirra/Construct-3-bugs#3719]
## Problem description
unable to get into the review version review process due to "App Uses Non-Exempt Encryption" not being enabled/true.

someone had a similar problem and i believe they're related to this issue [https://stackoverflow.com/questions/51908451/this-build-is-missing-export-compliance-information](https://stackoverflow.com/questions/51908451/this-build-is-missing-export-compliance-information
)
## Steps to reproduce

1. create an project with the share plugin.
2. add events for requesting review.
3. export as xcode project, upload build to testflight/app store.
4. should see this after uploading.
<img width="451" alt="Screenshot 2020-03-22 at 00 40 20" src="https://user-images.githubusercontent.com/21278459/77240304-3c7ca400-6bdc-11ea-8175-70b6267a1a39.png">

## Observed result

app store asks for a document, whether you say yes or no to any of the questions it gives.
<img width="846" alt="Screenshot 2020-03-22 at 01 31 52" src="https://user-images.githubusercontent.com/21278459/77240370-173c6580-6bdd-11ea-8a8e-ccc003da6c6c.png">
<img width="451" alt="Screenshot 2020-03-22 at 00 40 20" src="https://user-images.githubusercontent.com/21278459/77240372-199ebf80-6bdd-11ea-8c80-71ec284f659f.png">

## Expected result

should not be asking for compliance documents for encrypting things related to just requesting a review.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Are you sure this is a Construct bug? At first glance it looks like you just need to do some extra config in Xcode.

**Comment by Chadori** [comment]
I believe you can automate this through the `config.xml`, but until then:
Add the key `ITSAppUsesNonExemptEncryption` with the value `NO`, into the `Info.plist`.

**Comment by Chadori** [comment]
```XML
<config-file target="*-Info.plist" parent="ITSAppUsesNonExemptEncryption">
   <false/>
</config-file>
```
This is the easy fix, paste this into your `config.xml`, between `platform name="ios>` and `/>`.

**Comment by AshleyScirra** [comment]
I don't think we should actually set that for you automatically. Construct doesn't actually know if your app uses non-exempt encryption - I'm not sure what it really is referring to but in theory other features like third-party addons and scripting can use any features, which presumably can also involve non-exempt encryption. If we always set that setting for you and then you actually do end up using it, then Construct has set the wrong setting and you could get in to trouble since you then violate encryption export regulations and also misled Apple about it. I would guess at a minimum this could result in your app being pulled off the app store, and possibly worse (who knows what happens if you violate export regulations?)

These are a combination of Apple's rules and tools, as well as US export laws, and I think it has to be the responsibility of the publisher (i.e. you) to assert that you do not use non-exempt encryption, since that covers all features of your entire app, not just the Share plugin (and I don't know why the Share plugin seems to cause this, it seems to be something in Apple's detection). It also looks like they provide clear guidance on what to do about it, guiding you to changing the relevant setting in Xcode, so it seems to be straightforward to identify and solve based on what they tell you. I don't think there's anything that should change on our end on this, so closing.

**Comment by SalmanShhh** [comment]
it would be a good idea to make sure other users of the share plugin know about this, since there isn't a resource that says this can result from using the Share Plugin on IOS for C3 users.
