### ISSUE TITLE
Bullets ignoring angle of motion

### ISSUE THREAD

**Issue by Bigbeto123** [Scirra/Construct-3-bugs#3741]
Bullet shells (using Bullet Behavior + Physics and Solid), are not moving in the desired angle I've set them to do.

## Attach a .c3p
[bugrep.zip](https://github.com/Scirra/Construct-3-bugs/files/4427921/bugrep.zip)

1- Create a sprite with 8d movement
2. Whenever you press the mouse button, it'll shoot a bullet shell (exclusive collision filter and physics collision disabled with the player sprite) from it's point of origin to the opposite side where its heading to.
3. they will still be thrust to his his front, instead of his back.

1.Read
2.The steps
3.Above

## Observed result

The bullet shells spawn in his front

## Expected result

They should be thrust to the back of the main char.

To find the function regarding this matter, just enter the "Projectiles" folder -> "BulletShells" folder, and then see the function called "SpawnShell".

**Affected browsers/platforms:** 

**First affected release:** 
r193. Used to work in previous releases.

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.149
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
C3 release: r193 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 392 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines. We don't normally accept projects like this. Since you have 90 events, the assumption is anything that is wrong is a mistake in your events. In order to prove the problem is with Construct, please only submit projects that use minimal objects and events (2-3 objects and 2-3 events only is usually sufficient to demonstrate).

I can't see anything wrong with the project, either. When I click the bullets fire forwards and the player is moved backwards for a kind of kickback effect. Visually it makes sense so appears to be correct. I don't know why your expected result says "thrust to the back of the main char", it seems the player is already thrust backwards for the kickback effect.

If you want this to be investigated further please file again using a minimal project to both prove there is a problem with Construct and not a mistake in your events, and also to make it clearer what the problem is.
