### ISSUE TITLE
mouseOver doesn't work in Chrome

### ISSUE THREAD

**Issue by Gildas44** [Scirra/Construct-3-bugs#3743]
## Problem description

MouseOver doesn't work when the project is exported in Google Chrome.

## Attach a .c3p

[survolExposure.zip](https://github.com/Scirra/Construct-3-bugs/files/4430881/survolExposure.zip)

## Steps to reproduce

1. Add sprite with Exposure effect to the layout
2. Add the mouse Object to the Project
3. events : when the mouse is over sprite set exposure to 30
4. else set exposure to 0

## Observed result

It works in local.
But when it's exported it doesn't work in Google Chrome (in firefox and Edge, it's ok)

[Look here the exportation (with Chrome please)](http://jeux-http-logicieleducatif.fr/r.html)

## Expected result

It should work in Chrome.

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 

## System details

 No crash report

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It does work correctly after export for me: https://downloads.scirra.com/labs/mouse-overlap-test/

It looks like you are using custom HTML and styles in your page which possibly break Construct, because it assumes it has control over the style and positioning of the canvas. I'm afraid I can't investigate a bug with such possibly breaking changes on your side. If you still think there is a problem with Construct please make the absolutely most minimal case possible.

**Comment by AshleyScirra** [comment]
Looks like same issue as #3748 in the end.
