### ISSUE TITLE
"Saving to Dropbox" Popup should be hidden 

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#375]
## Problem description
we have habit of saving progress each time by pressing Ctrl+S
but now in construct 3 when we do each time Ctrl+S for save
processing popup irritate. whatever its for 5 sec or above it
it should be hidden somewhere so we don't have to wait for it to be saved 
*Enter a concise description of your problem here*

## Attach a .c3p
no file need
*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no
* Firefox: yes/no
* Edge: yes/no
* Safari: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by jaydonteh** [comment]
Yes I agree with you. What I did to speed things up is by saving to Dropbox once in awhile​ and use local storage for everyday work.

I wished​ I could just hit the Dropbox save and keep working on my project while it uploads.

**Comment by AshleyScirra** [comment]
Yeah, running the upload part of the save in the background is on the TODO list. @shortercode - recommend using a status indicator instead of progress dialog; will also need to guard against saving again while uploading.

**Comment by shortercode** [comment]
Yup agreed, it's just been on the back burner for awhile. The fix will likely be a merge in of [#376](https://github.com/Scirra/Construct-3-bugs/issues/376) when it comes.

**Comment by shortercode** [comment]
Okay so exciting news! I've just committed the changes for this. Instead of displaying a modal dialog it will now display everything except error messages as status prompts at the bottom of the screen. This makes it much easier to fire and forget while you keep working.

I've also implemented a lock on the saving system to prevent double saving. This will currently display a warning dialog if attempt a double save, but this may change.

Changes will appear in the next release.
