### ISSUE TITLE
Line of sight OR bug

### ISSUE THREAD

**Issue by Bigbeto123** [Scirra/Construct-3-bugs#3770]
Whenever you create multiple line of sight (has LOS to an object) conditions within the same event block utilizing the OR operator, all of these conditions except for one (the first create LOS behavior) will trigger the action. This should not happen.
Discovered an workaround to it, and proved its functionality on this project (press g to test it in game). If you separate each of these conditions in different event blocks, and including exact the same action on them, it will fire as it should have happened in the first place.

## Attach a .c3p
[helloagain.zip](https://github.com/Scirra/Construct-3-bugs/files/4482262/helloagain.zip)

1.create multiple line of sight related conditions in the same event block
2.Change the event block operator to OR
3.throw in some random action inside it for demonstration purposes

Watch it NOT fire in all occasions it should (only in 1 of them at most)

It should fire for every condition, since they're all in an OR block

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
r195
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.163
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
C3 release: r195 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 437 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 630 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Bigbeto123** [comment]
Been a good run of bugs so far, as usual, to say the least, but well. This one specially has been driving me crazy but finally figured it out.
Dunno if its exclusively related to the LOS behavior, but tested on keyboard and mouse conditions and the bug didn't happen. So it must have something to do with it.

**Comment by AshleyScirra** [comment]
The OR block is running - add an action like logging to the console and it runs - but it has no Sprite2 picked which is why the 'Destroy' action doesn't run. Internally the way OR blocks handle picking is super complicated and full of lots of awkward cases, so this might take a while to figure out.

**Comment by SnipG** [comment]
Won't it be simpler just to disable Or block with behaviors? If there is behavior disable OR. So it works just with vars, global compare math, instance vars, families etc.

Currect case seems that OR block is still AND block(in object handling case). And only picks/passes objects if all picking conditions is correct. ie, if all thous "or" block conditions are correct it works just like "and" block.

Also you claiming it passes actions, it does not in all cases. If i add action "add 1" to  var, it stop adding in some cases it should. And it only adds var action when first OR block is correct, but not when 2 is.

From all previous. OR block work just like AND block with objects and other cases it runs actions if first is correct, but wont run action for second block if that is correct. It does run action when all is correct but then it is already and block.

My 1 cent on the issue.

**Comment by Bigbeto123** [comment]
Ok this was a lot more complex than I expected

**Comment by AshleyScirra** [comment]
>Won't it be simpler just to disable Or block with behaviors?

Break all existing projects using behaviors in OR blocks is simply not an option. So we have to support it anyway. So we have to fix the associated issues anyway. Besides, my approach has always been to aim to have all features working all the time - if you go too far down the route of "certain features only work at certain times", you end up with confusing limitations and people getting the impression it's a messy, inconsistent product. (Which happens to some extent already due to platform/browser differences, but there's no need to make it worse.)

It's also naive to think if we just stop supporting it, the problem goes away. For example there was a bug in Construct 2 that incorrectly let you add event includes in sub-events, which it was never supposed to support. Construct 3 imposes the limitation correctly, but still has to import C2 projects with nested includes in order to preserve backwards compatibility. And then we still end up fixing bugs that only happen when you do that. We just recently fixed a bug with that case in the C3 runtime. These things hang around for years.

**Comment by aiaicaptain** [comment]
The operator messes up my project after the last update, but not with a behavior. I can't reproduce the exact scenario in a clean project to demonstrate the issue, but I'm trying to. If I don't manage I'll post a screen of my set up.

**Comment by AshleyScirra** [comment]
We fixed a different issue with OR blocks in r193 ("OR blocks could incorrectly run with instance not meeting conditions"). Your project may have depended on this bug. That would be unrelated to this issue, which is specifically dealing with the Line of Sight behavior only. As ever it is difficult to say anything at all without a minimal project and following all the guidelines: we require all that information because it is generally impossible to help without it.

**Comment by rogerty** [comment]
> 
> 
> > Won't it be simpler just to disable Or block with behaviors?
> 
> Breaking all existing projects using behaviors in OR blocks is simply not an option. So we have to support it anyway. So we have to fix the associated issues anyway. Besides, my approach has always been to aim to have all features working all the time - if you go too far down the route of "certain features only work at certain times", you end up with confusing limitations and people getting the impression it's a messy, inconsistent product. (Which happens to some extent already due to platform/browser differences, but there's no need to make it worse.)
> 
> It's also naive to think if we just stop supporting it, the problem goes away. For example there was a bug in Construct 2 that incorrectly let you add event includes in sub-events, which it was never supposed to support. Construct 3 imposes the limitation correctly, but still has to import C2 projects with nested includes in order to preserve backwards compatibility. And then we still end up fixing bugs that only happen when you do that. We just recently fixed a bug with that case in the C3 runtime. These things hang around for years.

You should use this text and idea as a blog post some day. This was interesting to read.
And made me appreciate the work behind the scenes more.

**Comment by AshleyScirra** [comment]
I think this should be working in the next beta. With the fix, the Sprite2 object is immediately destroyed, because the first condition (Sprite2: Has LosNoise to Sprite) is true: it has a cone of view of 360 degrees and a range of 200, and the sprites are less than 200px away. Being an OR block, none of the subsequent conditions filter out the relevant instances, so the destroy action runs on Sprite2.
