### ISSUE TITLE
Move To behaviour stops before real collision.

### ISSUE THREAD

**Issue by BonzerKitten7** [Scirra/Construct-3-bugs#3776]
## Problem description

The Move To behaviour stops the object before it even makes a real collision, which can lead to weird issues if you rely on wall detection. I made a .gif showing how the Move To behaviour works right now vs how it should (with a custom bullet behaviour).

Example: https://i.imgur.com/uurtKcd.gif

## Attach a .c3p

[Move To Stop Without Collision.zip](https://github.com/Scirra/Construct-3-bugs/files/4488785/Move.To.Stop.Without.Collision.zip)

## Steps to reproduce

1. Press the "Restart" button.

## Observed result

Move To behaviour stops before any real collision.

## Expected result

Move To behaviour to make the object really collide with the wall.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The problem is the movement actually steps inside the solid, and so it leaves it the last non-overlapping step. Most behaviors handle this by then doing further collision detection to find the edge of the solid. I added this to MoveTo to ensure it stops close to the solid too.

We're aiming to avoid non-essential changes for the next stable release now, so this fix will come out in the next release cycle.

**Comment by BonzerKitten7** [comment]
Thanks for the in-depth explanation and fix, Ashley. 👏
