### ISSUE TITLE
Pressing Escape on pop-out window freezes up application

### ISSUE THREAD

**Issue by tommakesgames** [Scirra/Construct-3-bugs#3780]
On 195 in both installable Chrome application and on Firefox window (Firefox latest).

I have a variables event sheet which I've opened as a pop-up window to have open on a second screen. When I create a variable there, but then change my mind and press Escape as a matter of habit, the pop-up window AND THE MAIN WINDOW dims and I cannot click anything or interact with the contents of the window. I can still press Ctrl-S to save the current project, but then I must exit/reload C3 and reload the project.

So, to replicate:

* Open project
* Create Event sheet with just variables
* Un dock
* Turn into pop-up window.
* Create variable, but before finishing, press escape.

**Comment by AshleyScirra** [comment]
Attaching sample project because none was provided: 
[repro3780.zip](https://github.com/Scirra/Construct-3-bugs/files/4493789/repro3780.zip)

Please always follow the bug report guidelines as described, since we're a small team and it saves time (and very commonly we are not able to reproduce the issue if you don't follow the guidelines - this time you were lucky!)

**Comment by AshleyScirra** [comment]
I'm not sure what's going on here and it seems pretty bizarre, but I found a workaround. We're close to a stable release and it's a low-level change I don't have much confidence in, so I'm saving this change for the next release cycle (i.e. after the next stable release), which should come in a couple of weeks.

**Comment by tommakesgames** [comment]
Thanks! Sorry I didn't follow guidelines, and sorry I didn't get back to you quickly on this.
