### ISSUE TITLE
Object with persist behaviour doesn't keep its z-index

### ISSUE THREAD

**Issue by ArtRow** [Scirra/Construct-3-bugs#3796]
Object with persist behaviour doesn't keep its z-pozition as it should

[Persist behaviour bug (z-index).zip](https://github.com/Scirra/Construct-3-bugs/files/4506250/Persist.behaviour.bug.z-index.zip)

## Steps to reproduce

1. Open the project (Just green object has persist behaviour)
2. Press S to spawn object (it also moves behind of our green object)
3. Press R to restart layout

## Observed result

After the restart green object is on the top

## Expected result 

After the restart (in game situation: we left that layout and visited it again) green object should be at the same z-index position

## More details
I found how to fix that. Spawned object should has persist behaviour. But I think it shouldn't work as it does.
**Also**, you can remove object spawn from code and just move object within z-index. It's also broken.

**First affected release:** r189.2 stable

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.35.1
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.35.1 (like Chrome/71.0.3578.80)
C3 release: r189.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 40 gb
Storage usage (approx): 661 mb (1.6%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1660 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is by design and appears to actually be a consequence of a related prior issue you filed (#2511).

The persist behavior only remembers its Z index relative to other objects with the persist behavior, because nothing else saves its information so that information is lost. However as an effort to leave itself in the right place - implemented after #2511 - it remembers its Z index and if it can, inserts itself back to the same Z index. When you spawn an object underneath it, its Z index becomes 2. Then when you restart the layout, the initial objects are recreated, and the persist behavior identifies that its Z index used to be 2, so it'll put it back at 2, which this time is on top of everything.

If you add the persist behavior to the other objects, it works correctly, because the persist behavior remembers its Z order relative to other objects with the persist behavior.
