### ISSUE TITLE
Zsorting isn't optimal for nearly sorted or sorted data

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#3802]
[zsorting.zip](https://github.com/Scirra/Construct-3-bugs/files/4539430/zsorting.zip)

## Problem description
Hello I'm Eleanor!

I think i am encountering a problem with Zsorting where it takes more CPU time than it should!

It takes the same amount of CPU time regardless of if things move or not, and it's only slightly faster than sorting random data.

## Attach a .c3p
[zsorting.zip](https://github.com/Scirra/Construct-3-bugs/files/4539463/zsorting.zip)

## Steps to reproduce

The c3p isn't really a real world example but it shows that it uses about the came cpu time regardless of if things are moving or set completely randomly 

## Observed result

CPU usage remains about the same regardless of the data and how close it is to already sorted or completely random
## Expected result
CPU usage to go way down when the dataset is close to sorted or sorted already

## More details

I think it should sort faster in real world cases where the data is always close to sorted since game objects move within the world but the world does not change much.

I'll give an example so it makes more sense
The world looks like this 
![image](https://user-images.githubusercontent.com/32940085/80254149-a7d8ec00-8648-11ea-9dec-446a9daa9ae6.png)
and is made out of individual sprites that must be constantly be set to z order
https://streamable.com/yo40qo

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The link to the project is not working.

**Comment by eleanorawesome** [comment]
sorry! i updated the project in the original report!

**Comment by eleanorawesome** [comment]
enabling one of these two should make for testing values that do not change and therefore are close to the final sort order versus completely random

**Comment by eleanorawesome** [comment]
random values that change every tick: 
![image](https://user-images.githubusercontent.com/32940085/80370418-12af4080-885e-11ea-89e5-0d95e9577fa9.png)

unchanging values based on y position:
![image](https://user-images.githubusercontent.com/32940085/80370481-3bcfd100-885e-11ea-880e-677968e869a8.png)

**Comment by eleanorawesome** [comment]
I feel like this is an important bug to report because a lot of construct 3 users report "sort z order" in their game being too slow to use on every tick and suggest putting it on a "every 0.1 second" condition to inflate their cpu usage and fps counter since it does not report usage on every frame, while actually janking their game for 1 frame when that condition is actually met instead of reporting the bug

**Comment by eleanorawesome** [comment]
if I may make a suggestion, maybe using an algorithm with better results when the data is nearly sorted for better results https://www.toptal.com/developers/sorting-algorithms/nearly-sorted-initial-order

**Comment by AshleyScirra** [comment]
It's working as designed and I don't believe there's a good way to improve on it.

The problem is that "Sort Z order" means "make the Z order match the sequence of instance variables". The instance variables are all in a jumbled order. So the first thing it has to do is sort all of the instance variables. If you have thousands of instances, that means it has to sort a list with thousands of items in it. This is pretty CPU intensive.

The internal implementation does then correctly identify that nothing has actually changed. But by then it's already done the most CPU-intensive part of the job, which is sorting a very long list of instance variables.

It is also not a nearly-sorted list, so an improved algorithm there will not help. The objects are created in a random order, so their Y value is essentially a random number. The instances are stored in the engine's instance lists in order of creation. So the instance variable list that the action deals with is always completely jumbled even after sorting by Z order. So trying to have some special handling for "nearly sorted data" doesn't seem to help in this case.

It doesn't seem necessary in practice to sort everything, though, so you shouldn't ever need to have to sort thousands of instances like this. The 'Sort Z order' action only sorts picked instances. So you can limit sorting to only the things that are on-screen. Then you never waste time sorting things that won't be seen.

**Comment by eleanorawesome** [comment]
I understand, i wish something could be done, but if you say it can't be done, then it can't be done.

I'm already doing all that I can in my project to reduce the picked instances because there could be a hundred thousand of them,

by storing them in a map(dictionary object) and so that I don't even need to add the condition "is on screen" on them because when they leave the screen their instance is destroyed and they are created when they enter the screen by using the map as coordinates to lookup if something exists in a certain position or not, but the issue seems to be that the more object I add, not only they use more CPU time for their logic but also for their Zordering since they are a composite of layered sprites so I am reaching a soft cap on low end mobile devices that is much lower and close to about 1500, most of it taken by the level 

thank you again for your time and explanation, i will figure something out  and make people realise that construct 3 is a super duper cool engine !!
