### ISSUE TITLE
Inconsistencies in the Yes and No button positions in the dialogues

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#3806]
## Problem description
The position of the Yes and No buttons in the edit action and in the edit condition are as follow:
Cancel, Back, Yes.

examples:

edit action:
![image](https://user-images.githubusercontent.com/32940085/80330328-df938f80-8812-11ea-94bf-823effce8132.png)

edit condition:
![image](https://user-images.githubusercontent.com/32940085/80330354-f2a65f80-8812-11ea-9fba-092b8f4c1b20.png)

In all of the other dialogues in the engine, the buttons are placed like so:
Nothing, Yes, Cancel.

examples:

Edit family:
![image](https://user-images.githubusercontent.com/32940085/80330165-6f850980-8812-11ea-9222-ce2e1e61a079.png)

Create new object type:
![image](https://user-images.githubusercontent.com/32940085/80330220-9a6f5d80-8812-11ea-97d7-2f5e370bc78b.png)

Edit Variable:
![image](https://user-images.githubusercontent.com/32940085/80330267-b4a93b80-8812-11ea-9821-7d8342251929.png)

## Attach a .c3p
does not apply

## Steps to reproduce
does not apply

1.
2.
3.

## Observed result
The yes and no button oftentime switch positions in different dialogue boxes making me accidentally click the wrong one.

 I edit actions and conditions the most so I don't even read the buttons anymore and simply click on the rightmost one by habit,
but when the time comes to add a new object type or a variable, I accidentally pretty much always click cancel without noticing and then I can'T find my new object or variable and I'm left confused

## Expected result
for the Yes and no buttons to be more consistent

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I don't think it's a fair comparison, because the Parameters dialog is a special case. All the other dialogs are a "Confirm / Cancel" choice, but the Parameters dialog is more like a wizard, with a sequence of dialogs and three choices: "Next / Back / Cancel". For this special case the dialog button positions are positioned to match the "direction" of the process, with "next" moving "right" through the sequence (hence positioned on the right) and "back" on the left. Cancel is a third option so is put on the opposite side. I think it would be weird to change that since it would put "back" on the right, which also does something different to "Cancel" which is still in a different place. Further, changing this will trip up thousands of users who have already gotten familiar with the way it works, and could involve changing lots of documentation, updating lesson plans that teachers use, and so on. Changing the other case (the "Confirm / Cancel" case) would then make it inconsistent with what Chrome and Windows do, further causing confusion. I don't think it's worth making changes in either case, it's I think it's something to live with.

One way of avoiding the problem is to use keyboard shortcuts: "Enter" is always Next / OK, and "Escape" is always cancel.

**Comment by eleanorawesome** [comment]
thank you for the reccomendation i will try that
