### ISSUE TITLE
multiplayer bug with the disconnection of players

### ISSUE THREAD

**Issue by pippopippi1** [Scirra/Construct-3-bugs#3817]
## Problem description
in a project that use the multiplayer object... after a peer disconnection from the room(max 2 player in a room) and the signaling, if there is a restart of the layout, the device can't join an other room 

## Attach a .c3p
[Nuova cartella compressa.zip](https://github.com/Scirra/Construct-3-bugs/files/4553255/Nuova.cartella.compressa.zip)

## Steps to reproduce

1.connect into a room
2.disconnect from the signaling server and the room
3.restart layout 

## Observed result
after the restart of layout the device doesn't join to an other room

## Expected result
after the restart of layout the device should join to an other room 

## More details

**Affected browsers/platforms:** 
chrome/firfox (i have no possibility to test on other browsers because i dont have apple device...) windows 10

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 81.0.4044.122
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36
C3 release: r197.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 548 gb
Storage usage (approx): 169 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is a mistake in your events - you don't disconnect from the room properly. Your events do:

- Leave room: this leaves the room on the signalling server, but leaves the peers/host connected
- Disconnect from signalling server
- Disconnect from room - you just disconnected from the signalling server, so this cannot be completed. Using "Leave room" is also redundant because this action does that as well.

As a result you restart the layout but leave the peer and host connected to each other. Then the subsequent attempt to join a room and connect fails, because the peer connections are still active.

These actions are also asynchronous: they don't actually finish until "On left room" / "On disconnected" triggers. You should wait for these triggers before restarting the layout, otherwise you risk restarting the connection before it's actually finished leaving/disconnecting.

FWIW, "Disconnect from room", "Wait 1 second", "Disconnect from signalling server" worked for me, but you should rely on the triggers instead of waiting, since if the process takes longer than 1 second it will still be broken.

**Comment by pippopippi1** [comment]
thank you very much, this is a great support for users
