### ISSUE TITLE
Multiplayer - Host does not see "Peer" leave the room

### ISSUE THREAD

**Issue by Jase0000** [Scirra/Construct-3-bugs#3833]
## Problem description

If a Host and Peer are in a room, and the Peer leaves the room, then the Host will not receive this information (Peer see's that they have left and have 0 peers in their current room, whilst Host still see's 2 peers in the room).
No triggers (Such as "On Peer Disconnect" or "On Kicked") are called, so the host will not know this.

## Attach a .c3p

https://drive.google.com/open?id=1B8wdWWb0QH3ZLm2xp9hwSvOFxdyywJ9D

## Steps to reproduce

1. Preview the above C3P file, then hold ALT and click Preview to open a 2nd window.
2. You will now have 2 preview windows. Reading the log, you will see one says "You are Host!" and "You are Peer!".
3. Observe the "Peer Count" on both, it will be 2, which is correct.
4. On the "Peer" window, click "Leave Room", you will see your PeerCount goes to 0, but then look over at Host, it still reports "2"

## Observed result

Host see's PeerCount = 2 when the peer leaves.

## Expected result

Host see's PeerCount = 1 when the peer leaves, as the host is the only one remaining in the room.

## More details

Chrome, no extensions or plugins.
Windows 10
r198

**Comment by AshleyScirra** [comment]
The project makes the peer leave the room on the signalling server, but they remain connected to the host. This is why the host doesn't see them disconnect (use the disconnect action for that). The peer count returns the number in the room, so once you leave the room it falls to 0 because it no longer has information from the signalling server; the peer is still connected to the host and they are in the room and they still see 2 peers.
