### ISSUE TITLE
Platform behavior does not set gravity correctly on Sprite created with JavaScript

### ISSUE THREAD

**Issue by Makoren** [Scirra/Construct-3-bugs#3836]
## Problem description

If you create a Sprite object with a Platform behavior using the createInstance() method in a JS script, and no instance of that object exists in the layout already, that behavior's gravity is set to 0. This causes the Sprite to lose its ability to fall or jump, while the rest of the behavior functions normally.

## Attach a .c3p

[PlatformBehaviorBug.zip](https://github.com/Scirra/Construct-3-bugs/files/4585819/PlatformBehaviorBug.zip)

## Steps to reproduce

Preview the attached project and attempt to control the sprite with default controls.

## Observed result

The sprite should only move left and right, and cannot fall or jump. Dev tools should have a console.log that shows the behavior's gravity set at 0.

## Expected result

Gravity should be set to 1500, which is the default amount when an instance is created in the editor.

## More details

**Affected browsers/platforms:** 
Latest versions of Chrome, Firefox, and Edge.

**First affected release:** 
r198. I have not tested earlier versions.

## System details

N/A

**Comment by Makoren** [comment]
I'm finding more bugs similar to this simply because the created instances are the first instances to be created. I'm also getting these issues from using the Create Object action.

Looking through the project examples, it looks like it's better to have a layout where an instance of all your object types are stored, so they can be instantiated normally without this issue.

I might have posted this issue a little too early since I'm new to Construct, but I'll keep it open just in case.

**Comment by AshleyScirra** [comment]
I changed the default gravity if no instances are placed in the project to the behavior default of 1500 for the next release, but this still does not allow any control over the gravity in the editor - you only get the default value. Presumably you want to control these values, which requires an instance placed in the editor so that there are some properties somewhere that can be specified, or you can set every property explicitly in code or events, which is what your workaround does.
