### ISSUE TITLE
Since r193, when using conditions from 2 different sprites with OR, loses picked sprites

### ISSUE THREAD

**Issue by trueicecold** [Scirra/Construct-3-bugs#3849]
## Problem description

When using 2 conditions of different sprites with OR with them, those sprites loses picking, making it impossible to destroy/update them.

## Attach a .c3p

[instance_variable_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/4605709/instance_variable_bug.zip)
(rename to c3p)

## Steps to reproduce

1. Enable the "Not Working Code" group and disable the "Working Code"

## Observed result

The conditions are met, but it's impossible to update spr_explosion instance variable, or even destroy it.

## Expected result

Picking should be kept for updating/destroying

## More details

Oddly enough, the "Working Code" group which uses booleans instead of direct comparisons inside the conditions works well.

Oddly enough #2, in both "Working" and "Not Working" groups, both spr_explosions.UID are correct, meaning the picking wasn't ENTIRELY lost, I guess...

This is an issue since r193, older revisions work just fine with both groups enabled.
I assume it's related to the issue #3732  fix.

**First affected release:**
broken in r193 and above

**Comment by AshleyScirra** [comment]
The events are wrong. This is a common mistake when using OR blocks: they can run with zero instances picked.

spr_explosion has var_color_id 0. The OR block tests if it equals 3. It does not, so the instance is not picked. However the spr_plane condition is true, meaning the actions run - but with zero spr_explosions picked. This means no actions on spr_explosion have any effect. If they did, it would mean actions ran on instances that did *not* meet the event conditions, which contradicts how events work.

Prior to r193 your events only worked because they depended on a bug that meant Construct incorrectly ran the event. This bug was fixed and it's now working properly.

**Comment by trueicecold** [comment]
but I though spr_explosion was picked because of the "on collision", not because of the IF inside.
In that case, both spr_explosion and spr_plane should be picked, as a result of the on collision condition, no?

And as a result of that, if either condition is true regarding the picked objects, should the picked objects keep their reference? I mean, it does have a correct UID when I log it.

Do you mean to say that even if the objects are picked as a result of a condition, if an IF is false regarding them, it resets the pick? and how come "Browser console spr_explosion.UID" returns the correct UID then? meaning it IS picked...

**Comment by AshleyScirra** [comment]
> I though spr_explosion was picked because of the "on collision"

No, because subsequent conditions filter out instances. They don't add them back in.
