### ISSUE TITLE
Instance variable are case sensitive in scripting, but case insensitive in editor  

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-3-bugs#3858]
## Problem description

please see post : https://www.construct.net/en/forum/construct-3/scripting-51/instance-variable-case-152390

in scripting, instance variables are case sensitive, but in the editor they are not 

## Attach a .c3p

https://drive.google.com/open?id=1qjQb8fCV3ajBzxGX9r2VMntrliT5rCNG

## Steps to reproduce

1. create instance variable with upper case
2. try and access it from scripting api, with lower case
3.

## Observed result

when referencing the variable, you get undefined

## Expected result

it's not really a huge deal 
the case of the variable should not matter, construct 3 editor does not allow you to have same variable name with different casing. 
or it should be documented that the casing is important 

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is by design. The editor is case-insensitive since it makes it easier for beginners, but the JavaScript programming language is case-sensitive. The instance variable properties in JavaScript are added with the original case you used (case-preserving), but the fact it's case sensitive when accessing them is because of the design of the JavaScript programming language, which treats all object property reads as case-sensitive.
