### ISSUE TITLE
Tile thru does not snap player up anymore

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#3861]
## Problem description

I believe someone posted this behavior as a bug in the past, but it softly breaks one of my games.
I wish to be able to revert this, or select this behavior to be present in a way, through some checkbox or something like it.

I do not wish a full revert to how it was, this was a good change and I also believe this is not a feature request because it was there in the past and it isn't now. Developer hours were spent in developing with this old behavior in mind.

## Attach a .c3p

Any project should present this with a simple square having Platform behavior and any tile object having Tile-Thru behavior.

## Steps to reproduce

1. Make Platform sprite jump so it is more than half of itself above any tile thru object´s surface.
2. Observe it just falls again.
3. In the past it would be snapped up.

**Comment by AshleyScirra** [comment]
Please attach a project as per the guidelines, since without a project we routinely find we cannot reproduce the described problem.

**Comment by AshleyScirra** [comment]
I made a project doing what you seem to describe and it works fine: 
[tile-jumpthru.zip](https://github.com/Scirra/Construct-3-bugs/files/4656449/tile-jumpthru.zip)

This is pretty much always what happens if you don't provide a project. Please always follow the bug report guidelines, they are there to make sure we can help.
