### ISSUE TITLE
tokencount results are always +1 from the actual count.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#3863]
## Problem description

I understand how it works by the docs, it counts how many elements there are between a given separator as in "tokencount("a|b|c", "|")' will result in 3, but it just seems very counter intuitive.

Using, for example, 'tokencount("aaa", "a")' will result in a 4, where there are actually 3 "a" in the string.

Also using a 'tokencount("bbb", "a")' will result in a 1, where there is not a single "a" in the string, which is probably the real issue here aside personal opinion, since the separator requested does not even exist in the string, therefore it should result in 0, right?

It is easy to put "-1" into tokencount results, but it would make sense if it already provided the actual result for a more intuitive approach, as if the tokencount function really counted how many times a symbol exists inside a given string.

I understand this is probably going to break a billion projects, so I'm totally comfortable with this issue being closed, just thought that for newcomers it would make a lot more sense.

I also believe it would be a lot more useful then counting how many objects there are in between separators. Cheers :)

## Attach a .c3p

Every file should present it.

**Comment by AshleyScirra** [comment]
It's working as designed.

Note that `tokencount("aaa", "a")` results in 4 because it is considered four empty strings separated by three separators. Consider `tokencount(",,,", ",")` instead: three commas implies four values.

`tokencount("bbb", "a")` has a single token of "bbb".

Internally it just calls the JS `split` function, which is what does all of this, so it's also consistent with how JavaScript handles string splitting. The only difference is if you pass an empty string to tokencount, it returns 0 (whereas `split()` will return an array with one element, implying 1).
