### ISSUE TITLE
[C3 Build Service] Update  Whitelisted Cordova plugins.

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#3865]
Hi, would you please update the whitelisted plugins to its latest version. This is to stop a current build error and prevent future ones. 

I have updated the **IronSource Android SDK** to [6.16.1](https://developers.ironsrc.com/ironsource-mobile/android/sdk-change-log/) and had their dependency versions static, to avoid sudden build errors. (So I don't use up anymore of the Construct Team's time whitelisting, due to frequent IronSource and ad-network mediation updates.)

**Whitelist plugin updates:**
- `chadori-mobile-ironsource@0.0.3`
- `chadori-mobile-ironsource-debug@0.0.3`
- `chadori-mobile-ironsource-vungle@0.0.2`
- `chadori-mobile-ironsource-unityads@0.0.2`
- `chadori-mobile-ironsource-tapjoy@0.0.2`
- `chadori-mobile-ironsource-mintegral@0.0.2`
- `chadori-mobile-ironsource-maio@0.0.2`
- `chadori-mobile-ironsource-inmobi@0.0.2`
- `chadori-mobile-ironsource-hyprmx@0.0.2`
- `chadori-mobile-ironsource-fyber@0.0.2`
- `chadori-mobile-ironsource-facebook@0.0.2`
- `chadori-mobile-ironsource-chartboost@0.0.2`
- `chadori-mobile-ironsource-applovin@0.0.2`
- `chadori-mobile-ironsource-amazon@0.0.2`
- `chadori-mobile-ironsource-admob@0.0.2`
- `chadori-mobile-ironsource-adcolony@0.0.2`

**New plugin to whitelist:**
- `chadori-mobile-ironsource-pangle@0.0.2`

I hope you can whitelist these as soon as you can, since there are build errors with the current old versions.

Thank you very much!

**Comment by C3GameDev** [comment]
Hey Ashley,
is there any chance to get this done fast? We really need this update to build an important bug-fix for a big live project.
Thanks!

Best regards.

**Comment by AshleyScirra** [comment]
We're a small team with limited resources, and requesting a large number of plugin updates creates a lot of manual review work. You should plan on such requests taking a long time to approve. As I advised previously, reviews are faster if you use only the strictly minimum number of dependencies and plugins. I also pointed out previously that you can always do local builds using completely unrestricted plugin versions. So if you urgently need some update then you can do your own local build instead of waiting for the build service to be updated, which as I mentioned could take a long time.

The build service whitelist has been updated and is now live.

I'd also point out that the build service does not differentiate 0.0.x updates. This means it is not possible to whitelist both 0.0.2 and 0.0.3, since the build service will assume 0.0.3 is compatible and always choose that over 0.0.2. Therefore as of this change all plugins will be getting 0.0.3 even if they request 0.0.2. This may be useful, but note if it is not and you actually need multiple versions to be whitelisted, use a 0.x version change instead (e.g. 0.0.2 -> 0.1.0).

**Comment by Chadori** [comment]
Thank you for the great work @AshleyScirra . We really appreciate it.

Regarding the version whitelisting, yes we do not need multiple versions, we only always need the latest.
Just to be clear, if I release a new version `0.0.4` from `0.0.3`, it will pass through the build service even without having to file a new whitelist request?

**Comment by AshleyScirra** [comment]
All version changes must be approved. If the build service has only whitelisted 0.0.3, that's the only version you'll get.

**Comment by Chadori** [comment]
Alright, got it. Thanks.
