### ISSUE TITLE
Part 2: Physics bug when velocity is 50 or less

### ISSUE THREAD

**Issue by awb11** [Scirra/Construct-3-bugs#3900]
## Problem description

I have been playing with every settings possible. As soon as velocity is 50 or less physics the ball stops bouncing. Take a look in the attached C3p. See the difference when velocity is 50 compare to 51.

I have been googling this and a lot of people have having this problem with Box2d, [Here](https://gamedev.stackexchange.com/questions/10922/why-are-my-objects-becoming-permanently-stuck-to-walls-using-box2d), [Here](https://gamedev.stackexchange.com/questions/12003/physics-engine-recommendation-which-can-simulate-pool-game-correctly), [Here](https://stackoverflow.com/questions/5381399/how-can-i-prevent-a-ball-from-sticking-to-walls-in-box2d), [Here](https://stackoverflow.com/questions/2962344/how-to-make-billiards-in-box2d-and-prevent-balls-from-getting-stuck-on-the-walls). 

However, people are reporting that the solution is simply changing b2_velocityThreshold to 0 in the Box2d settings. 

Please see potential solution [Here](https://gamedev.stackexchange.com/questions/12003/physics-engine-recommendation-which-can-simulate-pool-game-correctly)

A user wrote:

> “For Box2D, set b2_velocityThreshold in b2Settings.h file. In my case, I set it to 0.0f and it worked!”

In the [documentation](http://www.box2dflash.org/docs/2.1a/reference/Box2D/Common/b2Settings.html) under b2_velocityThreshold it states 

> “A velocity threshold for elastic collisions. Any collision with a relative linear velocity below this threshold will be treated as inelastic. ”

I think this might be the problem. Changing b2_velocityThreshold to 0 might be a solution. 

Why do we need the ball to stop bouncing if velocity is 50 or less? We can do this using the events. 

This is a huge problem and makes it impossible to create even simple billiards game. For my current game I need super icy surface but the ball sticks to a wall if velocity is 50 or less.

This is a problem on both Construct 2 and Construct 3. Please help. 

## Attach a .c3p

https://drive.google.com/file/d/150Fc1Ph9HENx2btlXq6ARTZz5aQHCX6J/view?usp=sharing

**Comment by AshleyScirra** [comment]
Unfortunately `b2_velocityThreshold` is not configurable at runtime. It's a compile-time constant that must be set at the time Box2D is built, which means we can only set one value for all use of the behavior. I would also assume that there is a good reason the default is 1.0f, and if we change it to 0.0f for everyone, it will break other cases which rely on the default of 1.0f. It's not clear to me how we could easily support both cases.

You could file this as a feature request, but given the difficulties with changing it I think it would be tough to do anything about it. Really this would need an alteration to Box2D to make this value dynamically configurable, which is an issue that would have to be filed with them, since it's a third-party project.
