### ISSUE TITLE
Object count seems wrong right after destroying an object

### ISSUE THREAD

**Issue by fodi** [Scirra/Construct-3-bugs#3948]
If I destroy an object and in the next action I display the number of current instances of that object (using .Count), the returned value still includes the object that was just destroyed. It seems like Destroy behaves like an async function; however if I include a "Wait for previous actions" action between the destroy action and the .Count action, it returns "0" which is completely wrong. Please see First.c3p. I've also included a Second.c3p, which only includes code related to this bug, and in that one including "Wait for previous actions" the count is correct, which is all the more confusing.

## Attach a .c3p

[FirstAndSecond.zip](https://github.com/Scirra/Construct-3-bugs/files/4785146/FirstAndSecond.zip)

## Steps to reproduce

1. Create an object, place it on the layout (maybe a couple of instances).
2. Create an event when you destroy an object and display it's current count in the next action eg. using a Text object.
3. Run the project.

## Observed result

Count is wrong and still includes the object that was just destroyed.

## Expected result

Count should not include the object instance that was just destroyed. Or the Destroy action should be advertised as async or something.

## More details

**Affected browsers/platforms:** 

I've tested this using the latest version of Construct 3 (r197.2) on Linux using Chromium 83.0.4103.61 (Official Build) and Firefox 77.0.1.

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chromium
Browser version: 83.0.4103.61
Browser engine: Chromium
Browser architecture: (unknown)
Context: webapp
Operating system: Linux
Operating system version: (unknown)
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/83.0.4103.61 Chrome/83.0.4103.61 Safari/537.36
C3 release: r197.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 42 gb
Storage usage (approx): 52 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) HD Graphics 630 (Kaby Lake GT2)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is actually by design. The idea behind it is actions are often loosely sequenced, e.g.:

- On Bullet collides with Enemy:
  - Destroy Enemy
  - Create explosion at Enemy.X, Enemy.Y

Note the explosion is created after the "Destroy" action. This still works as expected, because the enemy is not really immediately destroyed. If it really did destroy the enemy immediately, the second action would not work since the enemy is not available any more, so the explosion would be created at (0, 0) or a different enemy's position.

There is also a similar quirk about creating instances and when they can be picked. The reason is the engine cannot actually create and destroy instances half-way through running events, because various important data structures are actively in use, and modifying them mid-use can crash the engine. So the engine postpones the real creation and destruction until the next safe time - which is the next top-level event.

"Wait for previous actions" always runs at the end of the tick regardless of if it needs to wait for anything, similar to using "Wait 0 seconds". As a side effect of this, it will reach the next top-level event, and finish any pending instance creation/destruction.

It is a quirk that the count doesn't update, but as noted, the object does actually still exist. If the count decremented anyway, it would mean there's an instance in this weird zombie state where it's not counted, but it's actually still there and can still be used in events. I think it's better not to lie about it, and have the instance included in the count.

**Comment by fodi** [comment]
Thanks for the answer and the explanation, Ashley! I appreciate you taking the time. As I've searched for similar issues on GitHub I did come across a few other quirks as well - it would be awesome to have those and related internal mechanisms explained in the manual. (Or maybe I've missed it?) I'm in the process of designing and teaching game programming courses for Hungarian students between ages 10-14 completely based around Construct 3 and I'm trying to stay away from tricky/somewhat unexpected behaviours in the beginning :)
