### ISSUE TITLE
Audio.analyserFreqBinCount returns 0

### ISSUE THREAD

**Issue by castpixel** [Scirra/Construct-3-bugs#3970]
## Problem description

The expression Audio.analyserFreqBinCount returns 0 instead of the Frequency Bins

## Attach a .c3p
[frequencyBinCount.zip](https://github.com/Scirra/Construct-3-bugs/files/4812070/frequencyBinCount.zip)

## Steps to reproduce

1. Run the .c3p

## Observed result

 TEXT reads 0 

## Expected result

 TEXT should read "128" which is the number of frequency bins

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Unfortunately due to the architecture of the runtime, particularly the fact it can run in a web worker without the real Web Audio API available, the frequency bin count is not immediately available. It becomes available after a short delay.

If you take a look at the [audio analyser example](https://editor.construct.net/#open=audio-analyser), it just stores the value it sets so it doesn't have to deal with this issue. The runtime could do this itself, but if the audio engine clamps or alters the value in any way, it will return the wrong value. So really the runtime can't know the real value until it uses the Web Audio API, which takes a small delay to happen. So I think it's just something you have to work around.
