### ISSUE TITLE
c2 capx wont import on c3 - no infos given by c3

### ISSUE THREAD

**Issue by sndcode** [Scirra/Construct-3-bugs#3986]
## Problem description

We have a game made with construct 2 started development back in 2013. 
The capx was using the plugin "moveTo" by rex. I removed it already as its not working with c3.
Now when i want to import the capx c3 just fails.

## Attach a .c3p

this is a very old capx with the plugin removed already, should open on a fresh c2 installation, but does not on c3 without any information given why.

## Steps to reproduce

load capx to c3.

## Observed result

c3 fails importing without info.

## Expected result

the capx should load normal 

## System details

[2013.zip](https://github.com/Scirra/Construct-3-bugs/files/4831068/2013.zip)
[2018.zip](https://cloud.emtee.cc/index.php/s/JCwg9MSsMoeYzxE)

**Comment by AshleyScirra** [comment]
For reference, you can press F12 and see more error details in the browser console.

The problem here is a difficult compatibility problem: the C2 project has an object named 'sign', but in C3 a new system expression was added named 'sign'. This causes a conflict and prevents the project opening.

Fortunately the workaround is simple: open the project in C2, rename the object 'sign' to something else, and save it again. Then it imports in to C3.

**Comment by sndcode** [comment]
thanks alot mate ill look into this !!
