### ISSUE TITLE
Pathfinding causes decline in performance with each Layout restart/change

### ISSUE THREAD

**Issue by KekGames** [Scirra/Construct-3-bugs#3988]
## Problem description

If you have multiple objects using Pathfinding behavior - CPU performance gets worse each time you restart or switch the Layout. 

## Attach a .c3p

[TEST-PathfindingIssue.zip](https://github.com/Scirra/Construct-3-bugs/files/4831090/TEST-PathfindingIssue.zip)

## Steps to reproduce

1. Start preview and wait for 12 seconds to get the average and lowest FPS results over this period
2. Press R to restart the layout, or use arrow keys to switch between layouts
3. Wait for 12 seconds to get new results, and compare it to the initial results
4. Repeat this few more times to see further decline in performance

## Observed result

If, for example, on the first run you can get an average of 60fps with no stuttering, after a few Layout restarts - you'll get 40fps with serious stuttering.

## Expected result

Consistent performance.

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
No info
## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 83.0.4103.116
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
C3 release: r204.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 67 gb
Storage usage (approx): 219 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1070 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I think this is a problem with your project. You kick off 50 pathfind jobs - each one involving a heavyweight processing job - *every tick*, non-stop. That means you're starting 3000 pathfind jobs a second, no matter what. Since these are extremely CPU demanding jobs, the processing capacity of the system may only be able to finish say 2000 jobs a second. This means the backlog of jobs increases by 1000 a second, gradually clogging up memory, increasing latency, and reducing performance.

Computers do not have unlimited resources. You need to make sure you don't issue work faster than the system can run it.

**Comment by KekGames** [comment]
Of course, this is just an extreme example using as events as possible, so that you can clearly see a big difference in performance even on powerful PC. What if I need not thousands, but hundreds of units moving in RTS on mobile devices while other calculations happen at the same time? Besides, I did try to do this: run code for 10 seconds, disable the group with ALL events for few minutes, restart layout - and it still lags and stutters. So if you clog up memory - will these useless jobs ever be unloaded? Shouldn't it be unloaded when I restart or switch the layout?

**Comment by AshleyScirra** [comment]
This project just overloads the system. If you think there is some other issue, you need to provide some other demonstration that does not just overload the system.

In practice if you only find paths in response to user input, such as a "move units" command, then this will never happen, since paths are queued on a one-off basis instead of loading up the system faster than it can work through them.

If for some reason you really do want to find paths for hundreds of instances every tick - which I didn't think a realistic RTS game would do - then you need to design your events to not overload the system. One scheme for approaching this would to only have a limited number (say 50) pathfind jobs done at a time. You can use a counter which you add to when finding a path, and subtract from when it finishes calculating (or has an error), which gives you the number of currently-processing pathfind jobs. If there are more than 50 jobs in progress, then stop using 'Find path' and wait until the number comes down. This should avoid overloading the system and make sure it stays responsive at all times.

**Comment by KekGames** [comment]
Okay, thanks. So far it doesn't seem to be the real problem in this case.
