### ISSUE TITLE
Saving single file does not work correctly in r205 (Desktop app)

### ISSUE THREAD

**Issue by Anonymitet** [Scirra/Construct-3-bugs#3989]
## Problem description

When saving a single file in r205 two files are created. One corrupted 0kb .c3p file and one .crswap file around 300kb. You only get an error message when trying to open the .c3p file so to make it work you need to rename the .crswap file to .c3p. Then you can open it.

The issue only happens when updating to latest the latest c3 version and saving works just as expected in r204.2 for example.

## Attach a .c3p

Happens to any new project so no project file is needed.

## Steps to reproduce

1. Run C3 desktop app using any of the new nwjs versions.
2. Update to C3 version r205
3. Start a new empty project
4. Save as single file.
5. Browse the files created.
6. Try to open the created c3p file.

## Observed result

Two files are created. One corrupted 0kb .c3p file and one .crswap file around 300kb.

## Expected result

One c3p file should be created and not be 0kb in size.

**First affected release:** Works in all versions pre r205

**Comment by AshleyScirra** [comment]
This sounds like an NW.js bug that was already fixed. You need to use NW.js 0.46.3+. The editor should be prompting you to use that version if you're on an older version, specifically because of this issue. Please always include the system information with bug reports, you haven't provided anything indicating that you are using NW.js, so I'm guessing.
