### ISSUE TITLE
Using Tween Behaviour with a Global Sprite

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#3997]
## Problem description

I'm trying to use tween with a global object but it doesn't work. Object remembers its last state but all tweens are canceled when you changed the layout.

## Attach a .c3p

[tween global.zip](https://github.com/Scirra/Construct-3-bugs/files/4845398/tween.global.zip)

## Steps to reproduce

1. Open the example c3p and run the Layout 1.
2. Pressed A to start tween.
3. Pressed S to go to Layout 2.

## Observed result

Tween stops.

## Expected result

Tween should remember its state and keeps playing.

## More details

**Affected browsers/platforms:** Chrome 83

**First affected release:** r205

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
This is fixed in the next beta. The fix also affects timelines modifying global instances.

Mind that if the event sheet in the old layout had any actions related to the state of the tween, they won't be executed in the new layout. 

**_Ej._** **Layout 1** has an event waiting for a tween to be finished before doing something else. If the flow of the program goes to a different layout with a different event sheet before the tween is finished, the event on **Layout 1** waiting for the tween to be finished will never be handled.
