### ISSUE TITLE
iframe HTML content external files not load in NWjs

### ISSUE THREAD

**Issue by henrikszucs** [Scirra/Construct-3-bugs#4004]
## Problem description

iframe not load external files in NWjs when set html in HTML content.

## Attach a .c3p

https://drive.google.com/file/d/1z23AMZB0XgC-lIh3fCSlkX2WUFCCkHNW/view?usp=sharing

## Steps to reproduce

1. Add iframe
2. Add HTML content property which load files (css, js, etc.)
3. Not load the external files

## Observed result

Not load the external files

## Expected result

Load the external files

## More details
I cannot find in documentation which platform how support iframe.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 83.0.4103.116
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
C3 release: r206 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 134 gb
Storage usage (approx): 1.4 gb (1.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 640M Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_draw_instanced_base_vertex_base_instance
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_multi_draw_instanced_base_vertex_base_instance
WEBGL_video_texture
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The problem is that most of the iframes make relative URL requests (e.g. requesting just "page_style.css") with a page URL that does not have "page_style.css" available.

When you load a HTML string (or use the 'HTML content' property), there is no page URL, therefore no relative requests will work. The page is loaded from a special single-purpose `blob:` URL which returns the HTML string. Requesting a relative URL like "page_style.css" from a blob: URL is invalid.

In preview mode, local files also load from blob: URLs. Your project is not uploaded anywhere - it only runs locally. Since the preview runs on preview.construct.net, the iframe cannot request preview.construct.net/page.html, because your project is not uploaded there. Construct uses a blob: URL in preview mode as well to make sure the content can load - but then sub-requests fail for the same reason as above.

After export, the project files are available and can be directly requested, which allows the "HTML file & external" case to work. Note however "HTML content & external" still does not work, because the page is loaded from a HTML string and so has no URL (in other words this is just an incorrect setup). The inline cases work because they don't rely on making requests to relative URLs.

I'm afraid this is difficult to do anything about so you'll just have to work around it. The "HTML file & external" case works after export. You could also use a local HTTP server for development purposes and load the iframe from a localhost URL in preview, and then switch to the project files after export.
