### ISSUE TITLE
"Pick overlapping point" inside a "Cursor is over [object]"

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4009]
## Problem description

Using "Pick overlapping point" inside a "Cursor is over [object]" trying to get another instance of the same object that the mouse is over does not give another instance of the object.

## Attach a .c3p

[Pick_Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/4863217/Pick_Bug.zip)

## Steps to reproduce

1. The file is very minimal.

## Observed result

I'm unable to pick another instance of the hovered object through "Pick overlapping point". I don't know the extent of how many picks are actually affected by this behavior.

## Expected result

Being able to pick another instance of the same object.

## More details

**Affected browsers/platforms:**  Latest chrome.
**First affected release:** Tested on 206.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's a mistake in your events. 'Cursor is over Tile' will pick a single instance. Since sub-events can only pick from the instances picked so far, its sub-events can only pick from the single instance the cursor is over. Therefore sub-events cannot pick a different tile, unless you do something else like call a function or use the system 'Pick all' condition, both of which reset picking.

**Comment by dupuqub** [comment]
Thanks a bunch! "Pick all" is a perfect solution.
