### ISSUE TITLE
Update TargetSDK to 29 for Cordova Android 9.0.0

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#4028]
## Problem description

Update **TargetSDK** to `29` for **Cordova Android 9.0.0**. It's currently still on `28`.
Reference: https://cordova.apache.org/announcements/2020/06/29/cordova-android-9.0.0.html

## Steps to reproduce

1. Export (Construct 3 r204-2 or Construct 3 r206).
2. Check the `config.xml`.

<hr>

Thank you

**Comment by Chadori** [comment]
Kindly update the build tools too according to the `cordova-android@9.0.0`. Thank you!

**Comment by AshleyScirra** [comment]
The linked reference appears to state that this default only applies if no other target SDK is specified. This doesn't seem to be important since we set our own target SDK. We normally set it according to the Play Store requirement, which currently appears to be 28 (ref: https://developer.android.com/distribute/best-practices/develop/target-sdk). We'll change it when the Play Store requirement changes.

**Comment by Chadori** [comment]
Alright, got it.
