### ISSUE TITLE
Saving over original c3p file when opened from OS

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4066]
## Problem description

When you open a c3p file from your OS (not from within C3), then you try to save it, it doesn't save over the opened file, it opens the save as dialogue and not even in the directory of the C3 file.

## Attach a .c3p

Happens with all c3p files.

## Steps to reproduce

1. Run any c3p file from your OS explorer.
2. Try to save it.

## Observed result

Save as dialogue shows up

## Expected result

Save over opened file.

## More details

**Affected browsers/platforms:** 

Windows

**First affected release:** 
r208

## System details

<details><summary>View details</summary>

Platform information
Browser: NW.js
Browser version: 0.46.4
Browser engine: Chromium
Browser architecture: 64-bit
Context: nwjs
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (@ac9418ba9c3bd7f6baaffa0b055dfe147e0f8364) NWjs/0.46.4 (like Chrome/83.0.4103.116)
C3 release: r208 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 51 gb
Storage usage (approx): 48 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
We recently unified most of the NW.js specific code to run the same code as Chrome does with its file system access support. This allowed a major cleanup of the codebase, considerably simplifying the code. It should also reduce the number of NW.js specific bugs we have to deal with.

I'm afraid a consequence of that is projects opened from the OS can no longer directly be saved over the original file, because Chrome doesn't support that yet, and that's the code we're using now. Chrome should get this feature later this year with the [planned file handling support](https://bugs.chromium.org/p/chromium/issues/detail?id=829689).

Once it does come to Chrome, a benefit of that is you won't need to use the NW.js build at all, and can do all file system interaction from the browser. This is our goal - we want to move people off NW.js if you're just using it for file system access, and get you using the browser version instead.

**Comment by avishaymizrav** [comment]
Could I access and preview all NWjs (plugin) features through chrome?
Will I be able to preview in an external NWjs window for testing on current NWjs version and not chrome?
