### ISSUE TITLE
Error in edge, while you undo shader move

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4067]
## Problem description
Select object add 2 effects. then you move first shader under other and undo it. Edge preview won't start.

Uncaught (in promise) TypeError: Cannot read property 'SetBatchValueCustom' of undefined
    at WebGLShaderProgram.SetCustomParametersInBatch (shaderProgram.js:18)
    at WebGLRenderer.SetProgramParameters (webglRenderer.js:63)
    at RenderFirstBounce (renderEffectChain.js:17)
    at Function.RenderEffectChain (renderEffectChain.js:10)
    at Layer._DrawInstanceWithEffects (layer.js:31)
    at Layer._DrawInstanceWithEffectsAndRestore (layer.js:30)
    at Layer._DrawInstances (layer.js:28)
    at Layer.Draw (layer.js:26)
    at Layout.Draw (layout.js:27)
    at C3Runtime.Render (runtime.js:73)

## Steps to reproduce

1.Microsoft edge, new project. create sprite
2.Add 2 effect, move first shader under other. Undo
3.Preview the error

## Observed result
When you undo or redo shader position move, edge cant preview project.

## Expected result
No bug when i try simple things. Edge to work like chrome, or chrome work like edge if one of them is bugged

## More details

**Affected browsers/platforms:** 
Edge affected

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Edge
Browser version: 84.0.522.44
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 Edg/84.0.522.44
C3 release: r208 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 110 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
It seems to work fine here. Please always follow the bug report guidelines (attach a .c3p, include precise steps e.g. which effects you add) to ensure we can help.

**Comment by SnipG** [comment]
I have followed them and it 100% reproduce if you follow the steps.
 .c3p does not help in this case. if you save project and open it back up, it works. 

Case is, like it is desciped in report. That object effect list is not updated when you undo or redo. There are 2 list, first which appear on object, in properties bar and the effect list in effect dialog. If you undo effect dialog effect move, it does not update properties bar list. Doing same thing with variables, behaviors - it works because it is developed correctly and has support added between dialog and properties bar, while effects dialog list and effect list in properties bar do not update correctly, if you undo or redo -> which now causes bug in Microsoft Edge, while i have also seen strange crashes on Chrome, with same thing but it's more rare(most likely origin from same case). But mainly chrome works if you redo or undo.

This applies to all effects, the update mechanic is just missing/not added,  while it's there for variables and behaviors.

I try to keep reports as minimal as possible, it takes a lot of time to write and check stuff.

**Comment by AshleyScirra** [comment]
I tried it several times in a few different combinations. It worked fine every time.

This is exactly what I would expect from a report like this, because it is not specific enough. For example, the effect compositor is [extremely](https://www.construct.net/en/blogs/ashleys-blog-2/constructs-effect-compositor-1024) [complicated](https://www.construct.net/en/blogs/ashleys-blog-2/constructs-effect-compositor-1025). It is probably the most complex part of Construct and has dozens of ways it can work, depending on the exact effects in use and their precise characteristics.

You didn't mention which effects you used, so I'm probably only testing one or two out of 20-30 possible modes and paths through the effect compositor. You are probably finding an issue with a different path.

This **always** happens when people don't file specific reports. The whole reason we have comprehensive bug report guidelines is to avoid this happening and avoid wasting everyone's time. It wastes your time, and it wastes my time. Please - just always follow the guidelines, always be specific, and provide more information if asked. Otherwise your bug reports will be useless and I will simply be unable to do anything about them, and if I can't do anything about them, I close them.

**Comment by SnipG** [comment]
I think we just are on wrong page, while from my perspective the update system causes it, which is not implemented for effects, while you think it's shader compination. Which indeed for some effects, error does not happen, for others different errors happen.

Anyway:
1. Micosoft edge, open new, add sprite
2. Add effect Tint, add effect Swirl
3. Drag swirl on top of Tint. Click Ctrl+Z , preview

Uncaught (in promise) TypeError: p.getR is not a function
    at WebGLShaderUniform.IsSetToCustomInBatch (shaderUniform.js:7)
    at WebGLShaderProgram.AreCustomParametersAlreadySetInBatch (shaderProgram.js:17)
    at WebGLRenderer.SetProgramParameters (webglRenderer.js:62)
    at RenderFirstBounce (renderEffectChain.js:17)
    at Function.RenderEffectChain (renderEffectChain.js:10)
    at Layer._DrawInstanceWithEffects (layer.js:31)
    at Layer._DrawInstanceWithEffectsAndRestore (layer.js:30)
    at Layer._DrawInstances (layer.js:28)
    at Layer.Draw (layer.js:26)
    at Layout.Draw (layout.js:27) 

4. Add noise mask and soft light, drag soft on top of noise. Click Ctrl+Z. Preview

Uncaught (in promise) TypeError: Cannot read property 'SetBatchValueCustom' of undefined
    at WebGLShaderProgram.SetCustomParametersInBatch (shaderProgram.js:18)
    at WebGLRenderer.SetProgramParameters (webglRenderer.js:63)
    at RenderFirstBounce (renderEffectChain.js:17)
    at Function.RenderEffectChain (renderEffectChain.js:10)
    at Layer._DrawInstanceWithEffects (layer.js:31)
    at Layer._DrawInstanceWithEffectsAndRestore (layer.js:30)
    at Layer._DrawInstances (layer.js:28)
    at Layer.Draw (layer.js:26)
    at Layout.Draw (layout.js:27)
    at C3Runtime.Render (runtime.js:73)

**Comment by AshleyScirra** [comment]
Thanks for the extra details, I can now reproduce it with the specific Tint/Swirl ordering. The crash only happens when you use effect types which have different parameter types, in this case the fact the Tint effect uses a color parameter and the swirl parameter does not causes the problem. So as I suspected it is specific to certain combinations of effects only. I had tested effects which either did not use parameters or had compatible combinations of parameters, so it did not reproduce the crash. It should be fixed for the next release now.

For me it reproduced the same in Chrome and Edge. Since both now use the same browser engine (Chromium), bugs that only happen in one or the other should be rare - there's no particular reason to expect any difference between them. Perhaps you tried different combinations of effects in Chrome that did not reproduce it, and using a combination that did reproduce it in Edge made you falsely attribute the problem only to Edge. The only reason I mention this is for future reference with other reports. Bugs by definition mean something weird or unexpected is happening, and it can manifest in bizarre or incredibly specific ways. It's important to be consistent and specific while investigating and reporting them, otherwise it makes for a confusing report with missing or misleading details, and that can be the difference between the bug being fixed or not being fixed.
