### ISSUE TITLE
OneDrive login through PIN code.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4086]
## Problem description

When logging into OneDrive through PIN code, it throws an error message.
After that, you may just refresh the page, you'll be logged in, even though the error was thrown.

![bug](https://user-images.githubusercontent.com/34659544/89194188-6cba5300-d57d-11ea-9637-eab7595c39a2.PNG)

## Attach a .c3p

n/a

## Steps to reproduce

1. Access your OneDrive through PIN code.
2. Observe message.
3. Refresh page.
4. See that you were and are still logged in.

## Observed result

Error.

## Expected result

No error.

## More details

**Affected browsers/platforms:** Latest Chrome.

**First affected release:** Tested in 209.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This doesn't seem to make any sense, I just checked and there doesn't appear to be any "version 2 of the protocol" that we can use.

Also, what account type are you using? (Personal or work/school) And how did you configure a PIN? I had a look round my test OneDrive account, and could not immediately find any way to set a PIN.

**Comment by dupuqub** [comment]
I'm using a Personal license, and I defined a PIN through my system. When logging on the OneDrive it gave me the option to login through my system's PIN number.
![bug](https://user-images.githubusercontent.com/34659544/89215171-84ee9a00-d59e-11ea-8fc7-fc7c29f3dcbc.PNG)

**Comment by dupuqub** [comment]
Just checked in the console, hope it helps.
![bug](https://user-images.githubusercontent.com/34659544/89632304-5ad7f900-d878-11ea-89e5-3895916221d9.PNG)

**Comment by AshleyScirra** [comment]
I can reproduce this, but as far as I can tell we'd have to rewrite all the OneDrive cloud authentication code to support this, since we have to switch to a whole new protocol. We already recently upgraded the account system for OneDrive to support more account types, and it was a long and very complicated process. Working with Microsoft's systems here is a real nightmare, and I don't really want to go through all that again for one sign-in option. You'll just have to use the standard password-based sign in option for the time being. If you really think we should do all the work for this, please file a feature request.
