### ISSUE TITLE
Tiled Background Objects have seams on "repeat" setting

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#4099]
## Problem description

I'm getting tiny black lines / seams on seemingly random points of my tiled BG objects (not even at the edges, or where 2 objects meet) ever since the new clamp/repeat/wrap options were added. Adding a transparent row/column of pixels around the edge fixes it, but then, of course, there's a 1px transparent edge at the repeat point.

## Attach a .c3p

No luck reproducing in a new .c3p but I'm working on it. 

## Observed result
![asdasd](https://user-images.githubusercontent.com/36490901/89744331-85d96d00-da71-11ea-9d02-01254620753f.gif)

Tiny black lines / seams

No seams
## More details

**Affected browsers/platforms:** 
Chrome / Desktop

**First affected release:** 
Since the new clamp / repeat / wrap options were added to the Tiled BG object.
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The default repeat-repeat mode is identical to how it used to work, so that should not affect it. Maybe you need to use the clamp option to prevent wrapping on one axis, or maybe it's [this](https://www.construct.net/en/blogs/ashleys-blog-2/surprising-difficulty-1528). I'm afraid as ever, without a project provided, it's impossible to investigate this any further, so closing.
