### ISSUE TITLE
Advanced minification does not work in android export in given file

### ISSUE THREAD

**Issue by layilpaht** [Scirra/Construct-3-bugs#4105]
## Problem description

In some files(not all),when we use advanced minification for android export,the game freezes on the loading bar. I am attaching a file 

## Attach a .c3p

https://drive.google.com/file/d/1JxHgqJH31_h9gS8sY7eR83rlCGsVnpAN/view?usp=sharing

You don't have to deal with the content of the file.I just want to prove the bug

## Steps to reproduce

Export the project to android (signed release) with advanced minification. At the end you will get an apk. Install it on you phone and notice that the game freezes on the loading bar

## Observed result

The game freezes on the starting

## Expected result

Game should work as in case of none an simple minification

## More details

No idea why but this happens with few projects. All demo given works perfectly. Only my project hangs on the screen.

**Affected browsers/platforms:** 
Android.No idea about ios.

I don't remember the last stable release number (before r210) but the advanced minification was working perfectly and that's too with double speed. After that I never saw advanced minification work in following beta and then current stable release 

## System details
Platform information
Browser: Chrome
Browser version: 84.0.4147.105
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
C3 release: r210.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 67 gb
Storage usage (approx): 2.3 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GT 710 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

If possible then can you provide 2 options of advanced minification (one with you were using at r204 and another one currently used) ? Because last one works

**Comment by karimlahbach** [comment]
The same happen with me when i use advanced minification it give the "project Fail to Export" error

**Comment by layilpaht** [comment]
> The same happen with me when i use advanced minification it give the "project Fail to Export" error

Don't take me wrong but I think that your issue is different.
In my issue my build gets complete but when apk file is tested,it hangs on the loading bar. In your case it is failing to even build it.
If you are using scripts in the game,give a look to it. Or try again (maybe due to net fluctuations the build failed)
Or maybe your issue is also connected to my issue 🙂

**Comment by AshleyScirra** [comment]
It's working fine for me. I did a signed release APK build in r210.2, and also debug APK builds in r210.2 and r211 (the build type should not affect anything), all of which with advanced minification on export. All of them loaded and ran just fine on a Pixel 3 running Android 10.

It's difficult to help if we can't reproduce the issue. Maybe it's a false positive, or maybe it's not actually to do with minification and there is something else that is really the problem. Are you certain the problem is specific to only the advanced mode minification and it's not something else that really affects it? Can you provide any more information about the problem that might help shed some light on this?

**Comment by layilpaht** [comment]
Why I believe that it is connected to advanced minification:- because before and on r204 it was working perfectly. Later on I never saw it getting worked. And I have seen many many complaints regarding same topic from other users. And adding fuel to fire it does not happen with all projects. 
And because of which I had to submit my games to play store with simple minification (it is working smoothly with simple minification. Again saying in advanced minification in my case the apk file gets build but it hangs on loading bar. And it happens with my 3 mobiles)
And I have neither used any third party plugin nor any js code.
My suggestion would be to revert back (or give 2 options ,one with babel minify and another with Google one) the compiler you used in r204 and before. And babel minify was much much times faster too
BTW why construct 3 shifted from babel minify ?

**Comment by layilpaht** [comment]
Exactly same as #4093

**Comment by layilpaht** [comment]
If you are unable to figure it out then close the bug. Later on when I will get time then I will itself narrow down the bug and report again
Advanced minification is very important to me as it will secure my admob details

**Comment by layilpaht** [comment]
Also what is the meaning of regression (you are using same word for similar issues 😀)

**Comment by AshleyScirra** [comment]
As far as I can tell, it's working. What you've stated is evidence, but is not actually proof. Are you certain that:

- if you advanced-minify export the exact project you provided here, it does not work, and
- if you simple-minify export the exact project you provided here, it does work?

This is what I cannot reproduce. Everything else you've said suggests there may be some *other* problem involving other project files, other features, something else that got broken since r204, or other problems that were already since fixed. This is all very common - without unequivocal proof, such as the direct comparison I requested above, it is actually very difficult to say for sure that these really are all the same problem, and it's frequently the case that people incorrectly cite other issues or mis-diagnose the problem. So can you try the direct comparison? It may be that you actually cannot reproduce it with a direct comparison either, which would prove the problem actually is not what you think it is - although there may well be a different problem.
