### ISSUE TITLE
Audio (Sound and Music) Not Working After Export to NWJS

### ISSUE THREAD

**Issue by ziggyhere** [Scirra/Construct-3-bugs#4113]
## Problem description

There is no sound and music (no audio can be heard) when c3p project file is exported to NWJS (v0.45) using Advanced Minification. However, all audio (music and sound) works fine when running on Construct 3 preview. I tested several variables and found that the issue only happens when export is done with Advanced Minification. With Simple and None Minification, all audio works just fine. To ensure the bug is reproducible, I repeated the export with different audio files 3 times. All consistently expresses the same problem. With Advanced Minification, no audio is detected after NWJS export. Bear in mind that it has nothing to do with the music format as all files were originally from ogg and wav format and automatically converted to webm upon import.

## Attach a .c3p

It is not a code issue, it is an nwjs export minification issue. Also the project uses audio and music and may have copyright issue if posted here, hence no .c3p is attached. Scirra programmers can easily test my observation using Advanced and Simple Minification. 

## Steps to reproduce

1. Import any audio file (ogg or wav) to C3 under the Sound or Music folder.
2. Export to NWJS (any format) - I have tested with NWJS 0.45 and 0.46 versions
3. Select Minify: Advanced
4. Test .exe file
5. Listen to audio presence

Repeat with all steps above (with the exception of Step 3: Minify: Simple)

## Observed result

No audio detected in NWJS exports (v0.45 and 0.46) with Advanced Minification)

Audio detected only if exported with Simple or No Minification.

## Expected result

I would expected Advanced Minification should have no effect on audio presence.

## More details

Already explained concisely above. No extra details is required.

**Affected browsers/platforms:** 

**First affected release:** 

Tested with r210.2

## System details

No crash report.

**Comment by AshleyScirra** [comment]
It works fine for me.

Project I tried (none was provided so I created my own): 
[sound-playback.zip](https://github.com/Scirra/Construct-3-bugs/files/5063632/sound-playback.zip)

Resulting export with advanced minify: https://www.dropbox.com/s/d2mvnv2g63y4ce5/sound-playback-export.zip?dl=0

In both cases the sound correctly plays when clicking the button.

Please always follow the bug report guidelines. This always happens when reports skip steps - there is probably something specific to the project you tried that causes the issue, but you didn't attach one, so I'm not able to identify the specific issue. This is why we require a project is attached to every report - it's specifically intended to avoid this outcome.
