### ISSUE TITLE
Can't edit default family properties

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#4121]
My intention is to edit the default family properties (in this case the default physics behavior settings) but it won't let me:

![image](https://user-images.githubusercontent.com/5744908/90367000-78dcff00-e0ab-11ea-8821-11f9dfbf6f2a.png)

As seen above, it says there are no instances but this is a lie, there are several objects in this family with instances across many layouts:

![image](https://user-images.githubusercontent.com/5744908/90367676-6c0cdb00-e0ac-11ea-8adf-9de0798635a1.png)

It should allow me to edit the default properties regardless of whether I am on a blank layout, since my intention is not to edit specific instances on a specific layout, but to adjust the values across the entire family across all layouts. 

________________________________

Project file: 
[familyBug.zip](https://github.com/Scirra/Construct-3-bugs/files/5082730/familyBug.zip)

1. Go to layout 1
2. Select Family1 in the project bar
3. attempt to edit default family properties in the physics behavior

**Comment by AshleyScirra** [comment]
This is by design. Selecting an object type or family in the Project Bar selects all instances on the current layout. Since no Sprite is placed on Layout 1, selecting either Sprite or Family1 will not be able to select any instances, and therefore properties which belong to instances will be unavailable.

All you need to do is switch to a layout that does have an instance, or right-click the object type/family in the Project Bar and use 'Select all in project', which will then let you edit properties for all instances in the entire project.
