### ISSUE TITLE
Child with Sine behavior changes magnitude depending on parent's angle

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#4128]
## Problem description

If I put a child with a horizontal Sine behavior and rotate the parent 90 degrees, the child doesn't move anymore. It seems Sine movement doesn't get translated to the other axis of movement with parent rotation.

## Attach a .c3p

[children test.zip](https://github.com/Scirra/Construct-3-bugs/files/5092137/children.test.zip)

## Steps to reproduce

1. Preview
2. Left click until the platform is rotated 90 degrees
3. Child moves less and less until rotated and stops moving at that point.

## Observed result

Child's Sine movement stops working

## Expected result

The child should still sine (with a piston like movement) in the angle of the parent, no matter the angle.

## More details

**Affected browsers/platforms:** 

**First affected release:**  r212

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
@DiegoScirra - the horizontal sine behavior is moving the child with absolute SetX() calls. Looks like the scene graph code is not correctly compensating for the rotated parent.

**Comment by AshleyScirra** [comment]
This should be fixed for the next release, some of the maths used for the transforms in scene graph was wrong. Once it's fixed it still looks a bit odd since where the sine behavior object ends up after a rotation depends on its specific position, and with the fix it only moves horizontally no matter the parent angle, so after multiple rotations it can end up drifting away from the parent. But as far as I can tell it's actually working correctly, it's just an odd thing to set up.
