### ISSUE TITLE
(R210.2) An object's "dt" expression always returns 0

### ISSUE THREAD

**Issue by Fib100** [Scirra/Construct-3-bugs#4147]
## Problem description

When you check an object's own timescale (dt expression), it always returns 0 no matter what it's set to. Just to be clear, I mean the dt expression from the common expressions of all plugins (https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/common-features/common-expressions).

## Attach a .c3p

[typewriter_text_timescale_issue.zip](https://github.com/Scirra/Construct-3-bugs/files/5114962/typewriter_text_timescale_issue.zip)
 
## Steps to reproduce

1. Add a few objects types to the project, at least 1 Text object and Sprite
2. On start of layout set all the object's timescales to anything except zero.
3. Use the text object to display the object's timescale (dt expression)
4. Observe that the expression always returns zero

## Observed result

Observe that the "dt" expression on an object (object's own timescale) always returns zero

## Expected result

It should return what the object's timescale is actually set to

## More details

**Affected browsers/platforms:** 

Just tested it on Chrome 84.0.4147.135.

**First affected release:** 
Just tested it on R210.2.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's actually working correctly. Note that:

- your text object describes it as the time scale, but you're actually getting the `dt` (delta-time) expression for an instance
- you only get it once on startup, in a 'Trigger once' event (not sure why you used this instead of 'On start of layout')
- the first tick has no previous frame, so there is no delta-time, so it's zero

Update the values in 'Every tick' and you can see the `dt` expressions updating correctly.
