### ISSUE TITLE
TEXT and SPRITE causing error in families. Same error as before. Informations there if you need it 

### ISSUE THREAD

**Issue by FlippyDolphin** [Scirra/Construct-3-bugs#4151]
It seems to be happening when using keyboard commands with mouse commands (using shift or ctrl to select multiple objects and adding them to a family)

I feel like this next bit is a feature request but i feel like you should be able to add them to a family (for example im using it for a health bar with pin commands (although i guess this could be done with containers))

**Comment by AshleyScirra** [comment]
I still can't reproduce this. If I hold down control or shift and select both sprites and text, it unselects the previous selection when the plugin type changes, so you can only select only objects of the same plugin, as it is designed to.

Please always follow the bug report guidelines and be as clear and detailed as possible, otherwise it's impossible to help. This always happens when people skip details.

**Comment by FlippyDolphin** [comment]
I made a new post and recorded my issue and uploaded it as an unlisted video for you guys to watch
