### ISSUE TITLE
Drawing Canvas surfaceDeviceWidth/Height do not update when canvas size changes

### ISSUE THREAD

**Issue by ariepert** [Scirra/Construct-3-bugs#4163]
## Problem description

the surfaceDeviceWidth and surfaceDeviceHeight for a Drawing Canvas instance seem to get set when a project starts. If the size of the the Drawing Canvas changes, those values don't get updated.

## Attach a .c3p

[CanvasBug.zip](https://github.com/Scirra/Construct-3-bugs/files/5145993/CanvasBug.zip)

(I just changed the extension from .c3p to .zip)

## Steps to reproduce

I used the "Drawing Canvas: generate image" scripting example to demonstrate the bug...
The only change I made to the script was to log the surfaceDeviceWidth and height to the console.
And added a button to changed the size of the drawing canvas.

1. run the file, click the generate image button. (works great!)
2. click the OK button to change the size of the Drawing Canvas. (no problem!)
3. click the Generate image button again. (It still thinks the drawing canvas is the original size!)

## Observed result

C3 doesn't realize the drawing canvas has changed size, so the image gets distorted. If the script makes a new ImageData variable with the updated drawing canvas dimensions and tries to use "loadImagePixelData" an error is logged in the console saying: Uncaught Error: wrong size ImageData: expected (original width) x (original height), got (new width) x (new height).
I didn't add creating a new ImageData variable to the sample above because it clearly shows that it believes the dimensions haven't changed.

## Expected result

the surfaceDeviceWidth and surfaceDeviceHeight should be set to the new dimensions when the drawing canvas instance changes size. I am working on an app that needs to load full size photos taken by a cell phone (and other sources) and reduce them to thumbnail sizes to save in a database. The Drawing Canvas instance needs to be set according to the dimensions of the source image.

## More details

**Affected browsers/platforms:** - I only tried it on Chrome and Edge

**First affected release:** I tried it as far back as r177, where the Drawing Canvas script sample first appeared - same result. The script would not run in r176.

**Comment by AshleyScirra** [comment]
It's actually working correctly. The surface size is not the same as the object size, and in some cases the two may be different.

When you resize the DrawingCanvas it simply stretches the existing content to the new size, which is why the object size and surface size do not match. The DrawingCanvas object then triggers 'On resolution changed', because the surface size no longer matches the displayed size. The intent is for you to redraw the contents of the DrawingCanvas in this trigger, so it updates to match the new resolution. However because nothing is drawn in this trigger, it falls back to just stretching the old content. For more information see the 'Handling resizing and resolution' section in the [Drawing Canvas manual entry](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/drawing-canvas).
