### ISSUE TITLE
Real-time Multiplayer Bug with 2 different, but identical projects

### ISSUE THREAD

**Issue by 4demon** [Scirra/Construct-3-bugs#4165]
## Problem description

I have a project that has a different program for the host than it does for the peer. I currently have the 2 projects identical, for testing purposes only.

What I notice is that when the host creates an object, the second project is unable to create an object, yet the peer is certainly connecting, as that's what's informing the host to create the object.

However, if I open one project's debug, then alt-open the same project's debug (creating another window), the two are able to communicate without issues.

If I want the separate projects to communicate and create sync'd objects, I have to give the peer a delay of around a second.

## Attach a .c3p

[MultiplayerTest.zip](https://github.com/Scirra/Construct-3-bugs/files/5147320/MultiplayerTest.zip)

## Steps to reproduce

1. Open MultiplayerTest01
2. Open MultiplayerTest02
3. Run them in either order

## Observed result

Note that only one of the sprites is created, even though both projects are a copy/paste of the other.

## Expected result

I expect the two projects to work together. They are identical, yet they only work as expected when alt-opening another version of the same project, or that 1 second delay is added.

## More details
In additional tests with my actual project, I note that upon setting the ID to the Multiplayer.PeerID on creation, rather than setting the ID to the Peer, it is actually setting it to the HostID instead, even though the system appears to recognise it as a peer, not a host.

I've not been able to replicate this in this version, but it's driving me slightly insane.

I've set up a forum discussion with screen shots about this issue here:

[https://www.construct.net/en/forum/construct-3/how-do-i-8/anyone-whats-going-wrong-154888](url)

**Comment by AshleyScirra** [comment]
Sorry, 'Sync object' is not supported between different projects. The immediate reason is each project actually assigns objects different internal IDs which are sent over the network, and the multiplayer object cannot match the received internal IDs for objects from other projects with the wrong IDs. Secondly there is no guarantee that object types from a different project are compatible (e.g. it could be a different plugin type, it could have different or missing instance variables that are synced, etc.), and it's far simpler to not support this than it is to handle all the possible incompatible cases that could arise, and make sure they're handled reasonably and don't crash or cause further bugs that people would otherwise go on to report.

**Comment by 4demon** [comment]
But it does work if you add in that delay... Like I mentioned in the project.

**Comment by AshleyScirra** [comment]
I'm afraid it's not supported. If it works in certain specific circumstances, that is entirely by accident. It's not designed to.
