### ISSUE TITLE
DrawingCanvas - pasting an object from a layer with a different scale/angle

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#4205]
## Problem description

When an object which is on a layer with a different scale is pasted on DrawingCanvas, it's resized.

## Attach a .c3p

https://www.dropbox.com/s/krw7yod2236ecbe/CanvasPaste.c3p?dl=0

## Steps to reproduce

1. Run the project

## Observed result

The pasted image is resized.

## Expected result

I believe the object should be pasted as seen on the screen.

I understand that as a possible workaround I can just temporary resize the sprite itself before pasting. Unfortunately, this will not work for other objects - Tilemap, Tiledbackground etc. 

## More details

**Affected browsers/platforms:** all

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 85.0.4183.102
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
C3 release: r215 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 127 gb
Storage usage (approx): 578 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 620 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_draw_instanced_base_vertex_base_instance
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_multi_draw_instanced_base_vertex_base_instance
WEBGL_video_texture
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Note to self: review issue #4240 as another case of this issue.

This is super complicated. Basically instances on different layers can have a different layer transform (scale/angle). This involves a lot of tricky mathematics to correctly transform the pasted instance taking in to account the difference between its source and destination layer. Further there's already lots of complicated code to handle other difficult cases like correctly compensating for rotating the Drawing Canvas object itself. This makes it even harder to update the code to correctly handle this without breaking anything else.

As a workaround, for the time being if you only paste objects on the same layer as the Drawing Canvas, everything should work correctly. If you need to adjust the scale or angle of the object being pasted, you can do that by rotating or scaling the object itself rather than the layer it's on.

**Comment by AshleyScirra** [comment]
OK, well I think I figured it out after all - both cases should be working in the next beta. It wouldn't surprise me if more edge cases came up though, so we'll have to see how well it works out.
