### ISSUE TITLE
Multiplayer Kick Issue

### ISSUE THREAD

**Issue by niceplugin** [Scirra/Construct-3-bugs#4217]
## Problem description

If the host kicks a peer in multiplayer, the peer does not receive a reason in the "on kicked" event, even though the reason for the kick was sent.

And if you check the room information using "Request room list", the number of peers in the room is 2.

It should be 1 because the host kicked a peer, but it doesn't.

In this state, you cannot enter any other room that blooms. ("leave room" also doesn't work.)

When the host of the kicked room leaves the room, the kicked peer will trigger an "On kicked" event again, and the reason for the kick is transmitted.

After that, the peer can enter (or create) another room.

## Attach a .c3p

https://drive.google.com/file/d/1H4qXjQhifeR2muKekpaxxoGD-bvhOkF_/view?usp=sharing

## Steps to reproduce

1. Create a room. (host)
2. Enter the room. (Peer)
3. Kick out the peer. (host)

## Observed result

1. Peers that are kicked are not given a reason for kicking. You cannot enter other rooms. The room list still shows that there are 2 people in the room.
2. Leave the room. (Host)
3. Peer is now given a reason for being kicked out. You can enter another room.

## Expected result

1. Peers that are kicked are given a kickback reason.
2. And you can enter another room normally.
3. In the room list, there is only one person in the room.

## More details

Tested in Chrome, Firefox, and Edge browsers.
These are all the latest versions.
I don't think this is a browser issue.

## System details

Windows 10, and nothing else...

**Comment by AshleyScirra** [comment]
This is currently by design. You are reading the *LeaveReason* expression in the *On kicked* trigger, but [the documentation](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/multiplayer) states it can only be used in *On peer disconnected*:

> **LeaveReason**
> A string identifying a reason for leaving in *On peer disconnected* ...

If you use it this way, you'll note that the kicked peer is not shown the kick reason - only other peers in the room see the kick reason. The kicked peer is just shown "disconnected".
