### ISSUE TITLE
Messed up editor layout on startup. Edge and Chrome.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4224]
## Problem description

I just opened Edge and faced this issue again. The first time was in chrome and Scirra (Ashley) said it could not be fixed due to no repro. So there we go, ready for a new no repro.

![bug](https://user-images.githubusercontent.com/34659544/93237127-10d71280-f756-11ea-905e-e5490acbe967.PNG)

This is it for me if it doesn't get fixed. I will not keep changing browsers just for C3 and hope that it doesn't break at some point.

## Attach a .c3p

n/a

## Steps to reproduce

1. Open C3 on desktop browser. Edge or Chrome afaik.

## Observed result

Messed up editor.

## Expected result

a working product.

## More details

I've been using edge for about 2/3 months since this same issue happened in Chrome. Chrome is not fixed. Edge is only now presenting it. literally for the first time today.

**Affected browsers/platforms:** Edge and Chrome.

**First affected release:** 200 ish for Chrome. 215 for Edge. I did not update to 216 before I found the bug, but it happened after 216 was released, so maybe there's something to it.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Sorry, there's just nothing we can do about a report without steps to reproduce. We ask for that information because it's virtually impossible to do anything without it.

If you don't have steps to reproduce there's little point in filing an issue. For sporadic or rare issues it would be better to try to use a forum discussion to track down what might be going on.
