### ISSUE TITLE
Debug when working offline

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4242]
## Problem description

Construct 3 is unable to start remote preview or debug (trying to access editor debugger url) layout.

## Attach a .c3p

Not c3p related.

## Steps to reproduce

1. Disconnect from the internet
2. Launch C3
3. Try to run debug or remote preview.

## Observed result

Debugger is trying to load files online and fails.
Remote preview is unable to connect.

## Expected result

I understand why remote preview might not work, though that is the only way to test on chrome when using the NWjs version.
But the debugger should be cached along with the editor.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Remote Preview requires an internet connection to work, so it is not a bug if it doesn't work offline, that is to be expected.

I'll investigate the issue with the debugger for this report.

**Comment by AshleyScirra** [comment]
I tried using the debugger offline and it works fine for me.

I think most reports of "something doesn't work offline" are because people aren't waiting for the "ready to use offline" notification, which may take a while to appear. If you report an issue with something not working offline, make sure your steps to reproduce include: optionally clearing the browser cache to reset the offline state; loading C3; waiting for the "ready to use offline" notification to appear; going offline; and then trying your steps. If you omit these and it works for me, I can only assume you didn't wait for offline caching to complete.
