### ISSUE TITLE
Objects can'T be moved to global layers

### ISSUE THREAD

**Issue by eleanorawesome** [Scirra/Construct-3-bugs#4251]
## Problem description
objects can't be moved to global layers unless those layers are present in the layout

Also, moving objects to a global layer and then deleting that layer says that all instances will be deleted, but they are not, they are still present on other layouts with that global layer

## Attach a .c3p

https://drive.google.com/file/d/1QjNvVvVHKrtICRwHmEUqy-rMAHgBd2Qx/view?usp=sharing
## Steps to reproduce

1.on layout 1, try to move the yellow sprite to Layer 2, you can't
2.on layout 2, try to move the red sprite to Layer 1, you can.
3.on layout 2, destroy layer 1

## Observed result

can't move yellow sprite to a different layer,
Destroying Layer 1 on Layout 2 says it will destroy all sprite instances, but it doesn't
## Expected result
to be able to move sprites to my global layers at all times,
no weird error messages that says all my sprites will be deleted

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This appears to be by design. The reason you can't move the sprite on Layout 1 to another layer, is because the layout only has one layer. Global layers don't affect that. If you want the global layer to appear on that layout, you need to add a layer with the same name, and it will appear in the global "overridden" state.
