### ISSUE TITLE
Setting TextInput value in javascript does not change the Text property

### ISSUE THREAD

**Issue by ariepert** [Scirra/Construct-3-bugs#4255]
if you select a TextInput in javascript using getElementById and assign it a new value, the new value shows on screen but the object's .text property does not change.

It seems to work fine if you change the value through runtime.objects.TextInput. getFirstInstance().text however, but that isn't always possible when you are incorporating an external javascript library.

selecting an input using getElementById (or any other method) and assigning a new value worked in C2.

[TextInputBug.zip](https://github.com/Scirra/Construct-3-bugs/files/5303396/TextInputBug.zip)
(I just renamed the file to .zip)

## Steps to reproduce

1. run the file, click the button that says Click Me.
2. you will see the text in the TextInput box change, but when the object's value is appended to the text object on the right the original value is appended.
3. manually edit the text in the TextInput, then click the button again. The last value manually entered is retained, not the value set in the script.

## Observed result

The text in the TextInput is visibly changed on screen, but the object retains the original text.

## Expected result

setting the value should change the .text property

## More details

**Affected browsers/platforms:** 

**First affected release:** 
I tried it as far back as stable 171.3 and got the same result.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is actually a difficult problem and partly by design. Construct's form control plugins cache all the state of the element they control, only updating it if you make changes through Construct, or if change/input events fire on the element. The reason for that is to support worker mode, where your code runs in a Web Worker, and does not have direct access to the DOM element (so your code using document.getElementById() won't work there). Since it doesn't have direct access to the text input in worker mode, this is the only way it can provide things like the text content immediately (synchronously) in an expression.

Unfortunately programmatically changing the text input value, as in your code, does *not* fire an input event, so Construct does not know the value has updated in order to change the cached text content. That's why you get an old value. Since there is no event that indicates this has happened, there's no good way to update the cached value Construct stores (other than polling, which generally is too inefficient to consider). This also affects all state in all Construct form control plugins, not just the text input's value.

I don't think there's really a good way to solve this in general, because in worker mode this is the only way it can actually work at all. You can manually fire an "input" event and Construct will then see the change and identify the new value, like so:

```js
const elem = document.getElementById('input1');
elem.value='test 1 2 3';
elem.dispatchEvent(new Event("input"));
```

I think you will have to rely on that approach - or if you can, make changes exclusively through Construct, since that way it knows about all the changes that happens to the element.

**Comment by ariepert** [comment]
Thanks Ashley,
I tried the dispatchEvent solution in my script and it works great! That actually fixed another minor issue I was having - the On Text Changed trigger not firing.The script I am using doesn't use getElementById, I just used that in the minimal example for the bug report. I can quite happily live with this solution.
-- Allan

    On Monday, October 5, 2020, 11:02:50 a.m. EDT, Ashley (Scirra) <notifications@github.com> wrote:  
 
 


This is actually a difficult problem and partly by design. Construct's form control plugins cache all the state of the element they control, only updating it if you make changes through Construct, or if change/input events fire on the element. The reason for that is to support worker mode, where your code runs in a Web Worker, and does not have direct access to the DOM element (so your code using document.getElementById() won't work there). Since it doesn't have direct access to the text input in worker mode, this is the only way it can provide things like the text content immediately (synchronously) in an expression.

Unfortunately programmatically changing the text input value, as in your code, does not fire an input event, so Construct does not know the value has updated in order to change the cached text content. That's why you get an old value. Since there is no event that indicates this has happened, there's no good way to update the cached value Construct stores (other than polling, which generally is too inefficient to consider). This also affects all state in all Construct form control plugins, not just the text input's value.

I don't think there's really a good way to solve this in general, because in worker mode this is the only way it can actually work at all. You can manually fire an "input" event and Construct will then see the change and identify the new value, like so:
const elem = document.getElementById('input1');
elem.value='test 1 2 3';
elem.dispatchEvent(new Event("input"));
I think you will have to rely on that approach - or if you can, make changes exclusively through Construct, since that way it knows about all the changes that happens to the element.
