### ISSUE TITLE
Recreate object picking does not pick last objects recreated (as create objects does)

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-3-bugs#4262]
## Problem description

Recreate object picking does not pick last objects recreated (as system create objects does)

## Attach a .c3p
[RecreateIssue.zip](https://github.com/Scirra/Construct-3-bugs/files/5315961/RecreateIssue.zip)

## Steps to reproduce

1. Click to recreate objects.
2. Set Color and Assign Children are not applied to the recreated objects
3. Objects are instead white and not children of the recreated objects.
4. Instead they are set on previously recreated objects.

## Observed result

Set Color and Assign Children are not applied to the recreated objects

## Expected result

Expect to match system create ACE which picks newly created objects, so they can be manipulated.

## More details

A workaround Group shows how a possible way may work, however it likely has hazards if multiple simple recreate actions occur per tick. (Set other group inactive to test.)

**Comment by BonzerKitten** [comment]
Thanks for reporting this issue, Mikal! I started to implement a level loading system using the "Recreate initial objects" action, but I just realized it broke many things in my game. All the "On created" conditions were not being properly triggered, making it impossible to setup a scene. I really hope this can get fixed, otherwise I'll need to completely scrap my level loading system and avoid this feature.

**Comment by AshleyScirra** [comment]
@BonzerKitten - note this issue refers to picking only. If there are other things that don't work, please file a separate issue.

**Comment by BonzerKitten** [comment]
@AshleyScirra I believe it's also related to picking because the conditions themselves are triggered and can even send a log to the console, but some actions will simply not work because they can't find/pick any instances of the recently created objects. I was able to workaround this issue by creating a weird delay system that only allow specific parts of the code to run after one or two ticks, it's not very ideal, but it's working for now.

**Comment by AshleyScirra** [comment]
> All the "On created" conditions were not being properly triggered

This is what you said that sounded unrelated to this issue.

**Comment by BonzerKitten** [comment]
@AshleyScirra I'm so sorry about it, I definitely expressed myself badly here. I really didn't meant to make it sound like it's a different issue or make you more worried.

**Comment by AshleyScirra** [comment]
Updated 'Recreate initial objects' to pick the created instances for the next beta.

**Comment by MikalDev** [comment]
Thanks!

**Comment by BonzerKitten** [comment]
Great news! Thanks for the update.
