### ISSUE TITLE
Problem with browsers loading with many audio files (offline related)

### ISSUE THREAD

**Issue by COGames66** [Scirra/Construct-3-bugs#4264]
## Problem description
I have apps with a lot of audio files, and they load into the Chrome browser fine on the first time. After that they take a long time to load (and sometimes they don't seem to load at all). 

## Attach a .c3p

https://1drv.ms/u/s!AobC4q3rBlr6yuBL2sDU1wXwsqd58g?e=cms6xP

## Steps to reproduce

1. export to html5

2. load to a server (from things I've read it has to be https)

3. Run it.

4. Close the browser tab and then reopen the app (it may also hang up on a refresh, but not all time).

## Observed result

Hangs up when loading; result of f12:

sw.js:11 [SW] Update check failed: TypeError: Failed to fetch

## Expected result

I expect to see the app load normally.

## More details
Does the same thing on Edge.
When I delete the offline.json and sw.js files then they will always load fast without hanging up.
When I do not delete the offline.json and sw.js, but instead delete the sounds folder (so no audio files), then it loads normally on the second time going in.
This only happens in projects that have a lot of audio files.

**Affected browsers/platforms:** 
Only tested on Chrome and Edge, acts the same on both.

**First affected release:** 
This has happened when I used Construct 2 as well, as far back as I can remember. To get by, I always remove the offline capability.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I can reproduce Chrome failing to offline cache the files in the first place due to some requests failing with `(failed)net::ERR_INSUFFICIENT_RESOURCES`. This looks like a problem with Chrome, especially since it appears to work correctly in Firefox.

Since the problem appears to be with Chrome instead of Construct, please report this to Google at crbug.com. Let me know the bug number and I'll follow the issue in case Google have any questions specific to our engine.

In the short term, you can halve the number of files your project needs - you only need one WebM Opus audio file in Construct 3 (C2 instead required dual-encoding, having two formats for every file). Reducing the number of files by half might work around any limit in Chrome, but you'll still run in to the same problem if you keep adding more audio files.
