### ISSUE TITLE
[r219.2] Issue loading and playing video in FireFox

### ISSUE THREAD

**Issue by Kyatric** [Scirra/Construct-3-bugs#4270]
## Problem description

Error loading and playing a video (using Video plugin) in FireFox.
The same code works without issue in Chrome

## Attach a .c3p

https://kyatric.com/c3/bugs/play.video.bug.FF.2020.10.08.c3p

## Steps to reproduce

1. Open project in FireFox
2. Preview
3. Click anywhere on screen, or on the button.

## Observed result

Nothing

## Expected result

A video to start playing.
The text changing from "No play" to "Play"

## More details
Notice the NaN value for the video duration, whether the video is set from Start of layout, or on touch/click.
The very same project works without issue in Chrome.

**Affected browsers/platforms:** 
Firefox

**First affected release:** 
Not sure

## System details

<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 81.0
Browser engine: Gecko
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0
C3 release: r219.2 (beta)
Language setting: fr-FR
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 1,6 mb (0.1%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.
    image-set() is not supported. Mouse cursors may appear with reduced quality.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    WebM Vorbis (audio/webm; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    Ogg Opus (audio/ogg; codecs=opus)
    WebM Opus (audio/webm; codecs=opus)

Video information

Supported decode formats:

    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The project is a bit of a mess:
- there is a H.264 video, but it's in a QuickTime .mov format, which I don't think is widely supported (usually it's .mp4)
- there is a WebM video, but it's in the Files folder - it won't play unless it's in the Videos folder
- the video source properties are empty, so it initialises trying to load an empty video source, which will fail
- since that takes a moment to fail, half way through failing it does 'set source' in 'On start of layout', setting different sources to load - which may itself fail since the original source is in the process of failing to load

Here's a minimal repro that eliminates these issues: 
[video-min-webm.zip](https://github.com/Scirra/Construct-3-bugs/files/5348384/video-min-webm.zip)

This still fails to load the video in preview mode, but it works after export. As best as I can tell, this is some kind of Firefox bug, so I don't think Construct is doing anything wrong here. You could try reporting it to Mozilla, but it will be tough to persuade them it's really a Firefox problem and not Construct unless you make a minimal repro, which itself could be difficult and time-consuming... and I think this seems minor enough to not really be worth the trouble right now.
