### ISSUE TITLE
Black screen when Scan lines effect when set Parameter 0 to zero 

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4279]
## Problem description

Set "Scan Lines "effect Parameter 0 to zero, will adds Scan lines without spacing. It causes complete blackening. Maybe it should be more appropriate for "disable".That is, the "Scan Lines "effect Parameter 0 has a value of at least 2

## Attach a .c3p

Start page any effects examples.

BTW. I test it with "Effects - pixellate transition". add  "Scan lines" effect to Layout 1. Put it before "Pixellate" effect.The whole scene turned black

## Steps to reproduce

1. add any layer / layout "Scan lines" effect
2. set Parameter 0 to zero
3. Black screen

## Observed result

Black screen

## Expected result

Disable effect.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I don't know why you filed an issue for this - 0 is obviously an invalid value for the effect because it doesn't make sense to have scan lines 0 pixels apart. That would imply an infinite number of scan lines. The shader does a division by zero and ends up outputting solid black, which I regard as reasonable behavior with an invalid parameter.
