### ISSUE TITLE
Mesh Object incorrect bounding box after rotation

### ISSUE THREAD

**Issue by andygilbert29** [Scirra/Construct-3-bugs#4321]
## Problem description

Using the new Mesh deform action I am able to move correctly each point as well as move the the whole object (Drag and drop) without any effect. However, after rotating the object the points or bounding box no longer position correctly when I try to move them.

## Attach a .c3p

[mesh_issue.zip](https://github.com/Scirra/Construct-3-bugs/files/5477561/mesh_issue.zip)

## Steps to reproduce

Using the attached file.
1. Drag each corner of the object (Works)
2. Drag whole object and then again each corner (Still Works)
3. Rotate whole object and then move each corner (no longer works)

## Observed result

The coordinates no longer correlate. 

## Expected result

For the mesh points to be positioned correctly.

## More details

**Affected browsers/platforms:** 

Chrome

**First affected release:** 

Tested in latest R222.

## System details

<details><summary>View details</summary>

First posted by me here: 
https://www.construct.net/en/forum/construct-3/how-do-i-8/object-mesh-anyone-expert-156306#forumPost1026743

</details>

**Comment by AshleyScirra** [comment]
I believe this is a mistake in your events. Adjusting the mesh also adjusts the bounding box so that it fits the mesh. It appears your events do not take this in to account though and continue to refer to the bounding box while moving mesh points, therefore creating a conflict between updating the mesh from the bounding box, and updating the bounding box from the mesh. This is the same reason the built-in mesh distortion example saves the bounding box of the sprite to global variables, eliminating the effect of the mesh altering the box. If you use a tiled background or some other object to visualise the bounding box of the sprite, you should see that at all times it is correctly updated taking in to account the mesh, rotation, etc. so that it always encompasses the full extent of the object.

**Comment by andygilbert29** [comment]
Is there any chance at all (for my own educational purposes) you could amend the example to show it working correctly?
