### ISSUE TITLE
Keyboard shortcuts not working after "Open to popup window"

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4339]
## Problem description

When working with a separate tab, in an event sheet, there are no shortcuts working.

## Attach a .c3p

Any file should present it.

## Steps to reproduce

1. Make an event sheet into a secondary tab.
2. Try pressing "A" to add an action or "C" to add a condition.
3. Observe nothing happens.

## Observed result

Nothing.

## Expected result

Being able to use shortcuts on a secondary tab.

## More details

**Affected browsers/platforms:** Tested on latest Edge.

**First affected release:**  Tested on 224.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
As with issue #4338, what exactly do you mean by "a secondary tab"?

**Comment by dupuqub** [comment]
I don't really know what to call them, but when you drag an event sheet outside the normal editor and turn it into a new tab.

**Comment by AshleyScirra** [comment]
Note to self: also check holding space in layout view as per issue #4338

**Comment by ReflextionsDev** [comment]
@AshleyScirra This happens with paste as well (ctrl v) but oddly not with cut and copy.

**Comment by ReflextionsDev** [comment]
Never mind, copy and paste are having lots of problems as well.

**Comment by AshleyScirra** [comment]
Note to self: also check using escape to close dialogs as per issue #4440

**Comment by AshleyScirra** [comment]
It turns out popup windows weren't handling all keyboard shortcuts properly. This should be fixed in the next beta. I verified it now works with 'A' and 'C' in the event sheet view; space for panning the layout view; and pressing escape to close dialogs. I also tried Ctrl+C/Ctrl+V and it seems to work fine, if there's still any issue with that after the next release please file a new issue following all the guidelines.
