### ISSUE TITLE
Audio issues with mobile iOS

### ISSUE THREAD

**Issue by jogosgratispro** [Scirra/Construct-3-bugs#4349]
## Problem description

Audio is not playing on mobile iOS devices (phones). It works on Mac OS, Windows 7,8,10, Android 8,9,10 and 11

## Attach a .c3p

https://www.dropbox.com/s/pc0kzbiou72g7gh/audio-issues.c3p?dl=0

## Steps to reproduce

1. Import an audio file mp3, m4a or ogg (which is converted to webm) to the sounds or music folder
2. Add the audio object
3. Create a sprite to serve as button
3. Add the event to play any of the audio file to the sprite (button)

## Observed result

When I click/tap on the button, the audio works in the following platforms:
- Windows 7,8,10
- Linux
- MacOs
- Ipad runnion iOS 13.1
- Android 8,9,10 and 11

The audio doesn't work on the following platforms:
- iOS (Iphone X running 14.1)
- iOS (Iphone 6 Plus running 11.4.1)

## Expected result

The audio should work on iOS mobile devices for one of the those formats. Either m4a, mp3 or ogg (which is converted to webm)

## More details

I included a new screen to make sure the user/player would tap on it to active the audio.
Also, I included a text file to show if the audio is playing. In most cases, the text shows that the audio is playing but the sound doesn't come up.

**Affected browsers/platforms:** 

- Safari on Iphone x running iOS 14.1
- Safari on Iphone 6 Plus running iOS 11.4.1

**First affected release:** 

I'm not sure which version that started happening but for the longest time I can't get Audio to work on mobile iOS.

EDITED: I know for a fact that the audio for games I have built using Construct 2 version 206 does work. At the time, there was two types only (ogg and m4a)

## System details

<details><summary>View details</summary>
</details>

**Comment by AshleyScirra** [comment]
On an iPad running iOS 14.2 all three sounds play just fine for me via Remote Preview.

In Xcode only the WebM sound plays correctly, but we do document that WebM Opus is the only audio format that is supported across all platforms, and that if you use other formats, they may not always play successfully in all cases. So as advised you should just use WebM Opus everywhere.

The C3 runtime only supports iOS 12+ (which according to Apple's data covers 98%+ of devices released in the last four years). If it doesn't work on iOS 11, it's because the iOS version is too old to work correctly.

**Comment by jogosgratispro** [comment]
You are correct. It does work on Ipad but it doesn't work on Iphone X iOS 14.1.
In fact, it works on Firefox but it doesn't on Safari.

**Comment by AshleyScirra** [comment]
I tried on an iPhone 7 Plus via Remote Preview and it worked fine there too. This is no surprise to me, iOS devices usually work the same, so usually testing on iPad proves it also works on iPhone and vice versa.
