### ISSUE TITLE
JumpThru objects stop other close JumpThru objects from working.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4356]
## Problem description

In the file below there are 3 jumps, A, B and C.

In A and B, the Char's hitbox collides with a JumpThru object above the one the Char aims to stop at, therefore triggering the fall through behavior (I think). In jump C, the hitbox is not inside any other JumpThru object, therefore the jump never triggers the fall through behavior, working as expected.

It just doesn't match what is expected from the behavior.

I can fix it by making my Char's hitbox smaller, but then it passes through gaps smaller than its art, which is not great. Also using 2 different hitboxes for the Char's Solid and JumpThru behaviors would be not optimal, right (or even possible, because there is no selective collision with JumpThru)?

[Thru_Issue.zip](https://github.com/Scirra/Construct-3-bugs/files/5556934/Thru_Issue.zip)

## Steps to reproduce

1. Open the file and execute the 3 jumps.
2. Observe A and B make the Char fall through the lowest JumpThru platform.
3. Observe C works as expected.

## Observed result

above.

## Expected result

Being able to stop at any given JumpThru object, as long as it is logically below the character, even if it is touching some other JumpThru object at another position.

## More details

**Affected browsers/platforms:**  Tested in Edge.

**First affected release:**  Tested in 225.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The problem is you use an entire tilemap with the jumpthru behavior. The Platform behavior tracks jumpthrus on a per-object basis. Therefore it considers the entire tilemap a single large jumpthru object. One of the rules of jumpthrus is you don't land on it if you didn't clear the top of the jumpthru (i.e. if you only get half-way through the jumpthru you still fall down without landing on it). In this case both the upper and lower tiles on the jumpthru tilemap are considered the same object, and so it counts it as never clearing the top of the jumpthru, because you still overlap the same jumpthru.

It's easy to work around though - just place separate Sprite objects with the jumpthru behavior and it works correctly: 
[jumpthru-workaround.zip](https://github.com/Scirra/Construct-3-bugs/files/5603805/jumpthru-workaround.zip)

The platform behavior is already extremely complex and difficult to change without regressions, and there's a straightforward workaround, so I don't think this is worth the very difficult changes that would be necessary to the Platform behavior to specially handle the tilemap object.

**Comment by dupuqub** [comment]
I understand that it's currently unfeasible to achieve this fix, but in the long run I do believe this is something to be considered since it is the logical assumption regarding the behavior, and maybe a general pattern as well. I don't think it is great to have to build transparent sprites to achieve the same effect since it possibly bloats projects dependent on it where otherwise there would have to be no coding at all for the devs.

Again, I understand that now is not the time, but it would be nice to have this fix at some point.
