### ISSUE TITLE
Particles with sprite object - size calculation is based on 1st frame and doesn't keep aspect ratio

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4361]
## Problem description

In the c3p file below, I have 3 objects with the same animation, just a different frame order and 3 particles instances with the exact parameters, each running a different sprite.
You'll see that the first instance runs the animation as it should.
But the other two, stretches and deforms the frames

## Attach a .c3p

[particles.zip](https://github.com/Scirra/Construct-3-bugs/files/5578009/particles.zip)

## Steps to reproduce

1. Just run the c3p and watch the particles.

## Observed result

From what I managed to figure out, each frame size is based on the size and ratio of the 1st frame in the animation, causing deforming and stretching.

## Expected result

Size should affect each frame based on the frame scale and ratio. 

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. The Particles object only has one property for "size", and so spawns square sprites. Separately, the Sprite animation then preserves the aspect ratio as it changes frame. So if you have a wide and short sprite that is spawned by the Particles object as a square, it is actually taller than it was originally; this extra height is then preserved across other animation frames. You can see the same thing without using the Particles object at all if you allow the sprites in the layout to animate, but resize one of them to be a square.

**Comment by avishaymizrav** [comment]
@AshleyScirra 
Sure, but you rarely want that outcome for sprite resizing, that's why I always use scale, to keep proportions.
Can't you treat the size value as a scale factor instead of height?

**Comment by AshleyScirra** [comment]
Particles has always spawned square images or objects. It's not clear how the size value could be re-interpreted as a scale value. I think this would be better tracked as a new feature suggestion.
