### ISSUE TITLE
1-frame animation not triggering 'On any animation finished' 

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#4366]
When an animation has one frame, set to a non-zero speed, it does not trigger 'On any animation finished' when the animation is complete.

https://drive.google.com/file/d/1_McmqlOXq6lDto_wNqfAQblZV4AKDIpr/view?usp=sharing

## Steps to reproduce

1.  Run the above project.
2. The sprite has a 1-frame animation with default speed 10, but is not destroyed on completion.
3.  Enable the disabled action, which sets the Speed to 10 again.
4. Run the project again; this time the sprite is destroyed.

## Observed result

The sprite remains after animating at its default speed.

## Expected result

The sprite is destroyed without having to set its speed.

**Affected browsers/platforms:** Chrome 87

**First affected release:** r225

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design and arises from an important optimisation in the engine that ensures many projects continue to run smoothly.

Currently if you have a sprite with only one animation frame, the engine skips running the animation engine at all on that sprite. This ensures there is no per-tick overhead for sprites that do not animate. This saves a significant amount of processing in large projects, especially since it's common to use single-frame sprites for static features. Some projects will use many thousands such sprites.

There is an inconsistency as you've noticed - some features like changing the animation speed will restart the animation processing, since it now looks like you're interested in the animations of the sprite. But it seems a reasonable assumption that if a sprite has only one frame, you don't care about animations at all. Why would you care when "On any animation finished" in this case? There is nothing else it can display. Forcing all sprites to always process their animations - even if there is nothing else to display - could potentially significantly degrade performance, and there doesn't seem to be any reason to be interested in the animation timing of a single-frame sprite, so I don't think this warrants a change.

**Comment by brushfe** [comment]
Hey, thanks for the detailed explanation! I can see how the engine would benefit from that (and the retroactive problems that would cause). 

My goal was to use the animation speed as the simplest way to time how long the sprite should be on-screen. Specifically, I have a "hit" effect that pops up when a weapon makes contact with something. It's just a one-frame mark to show contact. I had set it to speed 10, and then destroyed it on finish.  

It might be worth disabling the Animation Speed entry field until there's more than one frame. And/or adding a note in the manual under On animation finished, since it's logical on the backend but an unexpected exception to users.

Thanks!
