### ISSUE TITLE
Picking children in subevent, not working when creating instance with hierarchy 

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-3-bugs#4369]
## Problem description

In the action block an object is created with hierarchy (scene graph) you cannot manually pick children,

in the example c3p project on click/touch it is creating a root object with four children in sub event it it picking all the children and changing the animation. this is currently not working, the children are not being picked in the subevent of the create object action

## Attach a .c3p

https://drive.google.com/file/d/14flG3CNs8v2nl_GCVvFqi2KUG0Asz0RL/view?usp=sharing

## Steps to reproduce

1. create an object with a scene graph
2. create sub event and pick children on root
3. change state of children
4. nothing happens to the children (because they are not getting picked)

NOTE : adding a wait 0 sec after the creation of root works

## Observed result

Nothing happens to children

## Expected result

The children animation change

## More details

**Affected browsers/platforms:** Edge/Windows (chrome also)

**First affected release:**  r226

## System details

<details><summary>View details</summary>

Platform information
Browser: Edge
Browser version: 87.0.664.41
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36 Edg/87.0.664.41
C3 release: r226 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 237 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 970 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is very difficult to deal with in the engine because it runs in to a long-standing limitation in the event system that newly created instances don't actually finish creation until the next top-level event. They cannot be picked by other events until then. This is why the sub-event to pick child instances doesn't work: it hasn't reached the next top-level event yet so they cannot be picked.

There is an exception made for "Create object": it picks the instance it creates - but it only picks the instance specified in the action (in this case "root"). This also is difficult to change because for performance reasons, the event system is only allowed to pick objects referenced in the action's object parameter. So "child" instances cannot be picked by a "create root object" action - the event system architecture does not allow it.

Another exception is made for "Pick last created", but this only lets you pick one of the four created child instances.

You can however use "Child: On created" and set its animation there, and it works, since all created instances trigger "On created" with the right instance picked, as you'd expect. This looks like the best workaround in this example. Would that solve the problem for you? Any other changes would be very difficult given the limitations of the current event system architecture.

**Comment by armandoalonso** [comment]
it does in this particular use-case, thanks

**Comment by AshleyScirra** [comment]
OK, given the complexity of dealing with this in other ways I think that workaround will have to suffice for now. It's possible this might come up again but in a way where using *On created* doesn't work as a workaround, but we'll deal with that if it comes up.
