### ISSUE TITLE
actions item width too small

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4373]
## Problem description

- Set position to another object
It's too long, so the 'Set scale' on the right is too close

2 columns
![Imgur](https://i.imgur.com/4B6fdCz.png)

3 columns
![Imgur](https://i.imgur.com/8xdtrn9.png)

4 columns
![Imgur](https://i.imgur.com/Bw8M7PJ.png)

5 columns
![Imgur](https://i.imgur.com/7guud72.png)

## Steps to reproduce

1.
2.
3.

## Expected result

```
.pickActionConditionIconView[label-right] ui-iconviewitem {
    min-width: 17em!important;
}
```
![Imgur](https://i.imgur.com/kB1lXY7.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>
__

**Comment by AshleyScirra** [comment]
This is currently by design.

There is no fixed width which is guaranteed to always display the full condition/action text, in particular since translations may use longer phrases, and the SDK allows third-party developers to specify arbitrary texts. The current approach is the fallback for long strings.
