### ISSUE TITLE
TextInput does not auto convert integers into string like Text object.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4376]
## Problem description

I spent some time bumping my head against this problem since I was getting integers from a JSON and they were not displaying in a TextInput object, I found out only later that when you try to write an integer into a "Set text" action it throws a warning that the data must be a string.

Maybe an issue, maybe not, but it made me lose some time not really knowing what was going on (since I was bringing data from a JSON, there was no warning) and is counter intuitive since Texts can perform the same task.

## Attach a .c3p

[InputIssue.zip](https://github.com/Scirra/Construct-3-bugs/files/5603549/InputIssue.zip)

## Steps to reproduce

1.Write an integer into a Text, all good.
2.Write an integer into a TextInput through "Set text" or "Append text" actions, throws warning.
3.Write an integer into a TextInput through a JSON.Get(), no warning and no text.

## Observed result

above.

## Expected result

TextInputs should accept integers and convert them into string just like Text objects.

## More details

**Affected browsers/platforms:** Chrome
**First affected release:**  226

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Previously the Text object accepted both strings and numbers and the Text Input object accepted only strings. This meant what you're seeing is by design: the editor can tell you the number 8 alone is invalid since it knows it's a number and text is required, and str(8) works around that. However JSON.Get() can return either strings or numbers, so the editor can't warn you that a number result is not valid there, since it could actually be returning a string. Instead it detects at runtime that you're passing a number which is not valid for a text parameter, and skips calling the action.

It is inconsistent with the Text object though, so I've switched Text Input to also accept either strings or numbers in "Set text" and "Append text" for the next release.
