### ISSUE TITLE
Canvas Size and Layout Scale break Anchor objects after change of layout

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#4380]
## Problem description

**Canvas Size** and **Layout Scale** break **Anchor objects** after change of layout.

It affects all instances with its **Left edge** in `Viewport right`, or **Top edge** in `Viewport bottom`.

## Attach a .c3p

[Report.zip](https://github.com/Scirra/Construct-3-bugs/files/5607718/Report.zip)

## Steps to reproduce

1. Open project.
2. Preview project.
3. On start, the events will set the **canvas size** (scale) and **layout scale** to `0.5x`.
4. The canvas and layout, with the anchor instances, will successfully scale.
5. After every 5 seconds, the layout will restart.
6. On restart, notice that the instances anchored at the **bottom or right** sides going out of their supposed position.

## Observed result

After restart of layout, all instances with its **Left edge** in `Viewport right`, or **Top edge** in `Viewport bottom`, go outside of their supposed position.

## Expected result

After restart of layout, all instances with its **Left edge** in `Viewport right`, or **Top edge** in `Viewport bottom`, to maintain their supposed position.

**Affected browsers/platforms:** **N/A**

**First affected release:** **N/A**

## System details

**N/A**

**Comment by Chadori** [comment]
Any news?

**Comment by AshleyScirra** [comment]
It's not a bug, although it's hard to tell because you have a confusing setup here. In the layout view you've positioned the objects according to the viewport guide, which in the editor represents the viewport at the size specified in project properties and 100% scale. The Anchor behavior identifies where objects are positioned in the viewport *before* 'On start of layout' triggers. Then you change the viewport size and layout scale in 'On start of layout', both of which change the viewport size.

On the first run the anchor behavior moves the object on the second tick according to the updated viewport. However after restarting the layout, it keeps the same canvas size and layout scale (those are effectively global settings), but the initial placement of the objects in the layout view is according to the default size and scale, which no longer matches the current viewport, so they end up offscreen.

There are a few ways you can deal with this:
- don't mess around with setting the viewport size/layout scale like that, just pick the right project settings and use letterbox scaling
- have the Anchor behavior disabled on startup, and enable it after your changes in 'On start of layout'. Upon being enabled, the Anchor behavior recalculates where to anchor itself, so this means its behavior is always consistent with the updated viewport based on prior actions. However then the viewport guide in the layout view is no longer correct because  you change it at runtime, so you have to make your own guide to help position the objects.
- don't use the Anchor behavior and just position objects every tick based on the system viewport expressions, which gives you full control over how positioning works, especially since you change the viewport at runtime

**Comment by Chadori** [comment]
Thanks, I will review the details.
