### ISSUE TITLE
Cordova Plugin White-list request for the Cloud Build

### ISSUE THREAD

**Issue by emi415064** [Scirra/Construct-3-bugs#4381]
cordova-admob-plus@0.40.0
~cordova-plugin-app-review@2.0.2~
cordova-plugin-camera-preview@0.12.1
cordova-plugin-codeplay-facebookads-free@0.1.5
cordova-plugin-firebasex@11.0.3
cordova-plugin-firebase-crash@3.0.0
cordova-plugin-firebase-analytics@~5.0.0
cordova-plugin-firebase-inappmessaging@4.0.0
cordova-plugin-firebase-authentication@4.0.1
~cordova-plugin-androidx@3.0.0~
~cordova-plugin-androidx-adapter@1.1.3~
com.pollfish.cordova@1.1.0

**This is a free plugin**

https://www.construct.net/en/make-games/addons/464/app-review
https://www.construct.net/en/make-games/addons/472/firebasecrashlytics
https://www.construct.net/en/make-games/addons/489/firebase-in-app-messaging
https://www.construct.net/en/make-games/addons/490/firebase-sign-in-verify-phone

**Thanks.**

**Comment by AshleyScirra** [comment]
Please note: we're a small team with limited resources, and this looks like a significant amount of review work. Please allow several weeks for the review to be completed.

**Comment by AshleyScirra** [comment]
Also please note:

> cordova-plugin-app-review@2.0.2

The built-in Share plugin can already do app reviews. Do you still need to have this plugin added?

> cordova-plugin-androidx@3.0.0
> cordova-plugin-androidx-adapter@1.1.3

I don't think you need to use these plugins, since AndroidX is now built-in to Cordova. Instead use `SetAndroidXEnabled(true)` in the SDK [IPluginInfo](https://www.construct.net/en/make-games/manuals/addon-sdk/reference/iplugininfo) interface.

**Comment by emi415064** [comment]
okay no problem.

thanks.

**Comment by AshleyScirra** [comment]
I'm not clear what you mean by this response. Do you still need those Cordova plugins added to the build server, or not?

**Comment by emi415064** [comment]
Yes add

**Comment by AshleyScirra** [comment]
I need an explanation to justify this though, because there doesn't seem to be any reason to add these plugins. What is the reasoning for it?

**Comment by emi415064** [comment]
difficult to explain because I don't speak English,
this is google translate text.

How do they use my plugins if they can't use cordova cli?

building locally also requires high pc specifications.

I want to create a large number of new plugins, and it's free, I really like it when people use my plugin .

**Comment by emi415064** [comment]
![Screenshot_2020-11-30-22-29-17-657_com android chrome](https://user-images.githubusercontent.com/39442895/100629279-ae0c1500-335b-11eb-8f02-b7ed5ce1003f.png)

**Comment by AshleyScirra** [comment]
My point is: it looks like you don't need these Cordova plugins to be added.

Can you explain why the alternatives I pointed out are not sufficient and so why they still need to be added even though there appear to already be other solutions?

**Comment by emi415064** [comment]
cordova-admob-plus@0.40.0
cordova-plugin-app-review@2.0.2
cordova-plugin-camera-preview@0.12.1
cordova-plugin-codeplay-facebookads-free@0.1.5
cordova-plugin-firebasex@11.0.3
cordova-plugin-firebase-crash@3.0.0
cordova-plugin-firebase-analytics@~5.0.0
cordova-plugin-firebase-inappmessaging@4.0.0
cordova-plugin-firebase-authentication@4.0.1
cordova-plugin-androidx@3.0.0
cordova-plugin-androidx-adapter@1.1.3
com.pollfish.cordova@1.1.0




cordova-plugin-app-review@2.0.2
cordova-plugin-androidx@3.0.0
cordova-plugin-androidx-adapter@1.1.3

**Comment by AshleyScirra** [comment]
The following plugins are now permitted on the build service:

cordova-admob-plus@0.40.0
cordova-plugin-camera-preview@0.12.1
cordova-plugin-codeplay-facebookads-free@0.1.5
cordova-plugin-firebasex@11.0.3
cordova-plugin-firebase-crash@3.0.0
cordova-plugin-firebase-analytics@~5.0.0
cordova-plugin-firebase-inappmessaging@4.0.0
cordova-plugin-firebase-authentication@4.0.1

Note `com.pollfish.cordova@1.1.0` was not added because it does not appear to be a valid npm package. `npm install com.pollfish.cordova@1.1.0` fails with `No matching version found for com.pollfish.cordova@1.1.0.` Please request this separately with a valid npm package name if you still want it to be added.
