### ISSUE TITLE
On Drag Start always show Touch position at (0,0) , this didn't happen on Construct2 

### ISSUE THREAD

**Issue by kimarutaGM** [Scirra/Construct-3-bugs#4398]
## Problem description
1. Adding Sprite with behavior Drag&Drop.
2. On event sheet, set On Drag Start event and log the Touch position.
3. Game always show Touch position at (0,0) , this didn't happen on Construct2 (on C2, it working well and show Touch Pos exactly, not (0,0) 

I don't know this is a BUG or not :(

## Steps to reproduce
1. Adding Sprite with behavior Drag&Drop.
2. On event sheet, set On Drag Start event and log the Touch position.
3. Game always show Touch position at (0,0) , this didn't happen on Construct2 (on C2, it working well and show Touch Pos exactly, not (0,0) 

## Expected result
 Game should show Touch position in right way.
## Attach a .c3p
[testDrag.zip](https://github.com/Scirra/Construct-3-bugs/files/5640292/testDrag.zip)

**Comment by AshleyScirra** [comment]
Your events set up a race: which sees the touch event first, the Drag & Drop behavior, or the Touch object? This is not a reliable thing to set up, since it's an internal detail which is subject to change, and it only works if the Touch object sees the touch event before the Drag & Drop behavior. This is not guaranteed to happen. You should only read Touch expressions in Touch triggers like 'On any touch start'.
