### ISSUE TITLE
Platform objects fall through Jumpthru objects

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-3-bugs#4406]
## Problem description

Objects with Platform behaviour are inconsistently landing or passing through an object with Jumpthru behaviours. It seems to happen when the Jumpthru object is rising. 

Forum discussion: www.construct.net/en/forum/construct-3/general-discussion-7/jumpthru-bug-156926

## Attach a .c3p

Forum user kossglobal created this example:

https://drive.google.com/file/d/1Gqy-JEXB8FzOjKPu55WCwkkqOaxE0UR5/view

## Steps to reproduce

1. Run the attached example.
2. Press ENTER to spawn Platform objects.

## Observed result

Some Platform objects pass through the Jumpthru object (as it rises).

## Expected result

All Platform objects should land on the Jumpthru object.

## More details

Not sure if this is the same bug as https://github.com/Scirra/Construct-3-bugs/issues/4239

**Affected browsers/platforms:** Chrome 87, Safari 14

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Since there was some exasperation expressed in the associated forum thread, I'll try to explain the level of complexity that we have to deal with in the platform behavior, and how it changes over time. This particular issue is yet another complicated edge case that I think is a regression since r190 as a result of fixing issue #3631 back in March (which I rightly feared at the time might cause further issues). The logic of jumpthrus is complicated: unlike solids, a platform behavior object is allowed to intersect a jumpthru (e.g. be half-way through it). Since all movement really happens in small steps tick-by-tick, intersecting a jumpthru after having fallen from above means you should actually land on its surface, but otherwise you're just passing through (e.g. jumping from below but not clearing the top of the jumpthru, which acts as if the jumpthru is simply not there). An upwards moving jumpthru platform is a further complicating factor: it means the player can land on its top either because the player moves down to intersect the jumpthru, *or* because the platform moved *up* to intersect the player. It's the latter case that causes the problem here, since the platform behavior does not recognise that it fell on to it - it's more like it suddenly finds a jumpthru placed on top of itself, and has to specially handle that case as also like falling on to a jumpthru.

The next complication comes from the fact the platform behavior used to have pretty loose tolerances, and would happily shift the platform object up to say 30px in order to fix any discrepancies. This means it used to work, because the upwards moving platform case just got handled by the loose tolerances for detecting things like floors. However this caused noticeable glitches in other cases, such as moving horizontally in to a slightly higher up platform would actually snap the player up to run along that platform. This was the problem filed in issue #3631. The fix to that was to tighten the platform behavior tolerances to be stricter. However this meant that *if* the player was falling fast enough on to a jumpthru *and* the jumpthru was moving upwards fast enough, the stricter tolerance for detecting the floor was no longer sufficient to cover the combined distance and identify a floor-landing case, resulting in this issue. (The fact nobody else appears to have filed this issue since March suggests it's a relatively rare case.)

I've now added a special case increase to the floor landing tolerance to specifically handle the case of falling downwards on to a jumpthru that could possibly be moving upwards, and temporarily apply an increased tolerance for the single tick where the intersection happens, which appears to fix this case, so it should be working better in the next beta. However given the rules around jumpthrus, I suspect this case will still happen with a jumpthru moving upwards very fast. Unfortunately if it's moving fast enough, it is pretty much indistinguishable from just using "Set position" to teleport a jumpthru on top of the player, which you'd rightly expect the platform behavior to ignore. So, as with many edge cases in the platform behavior, there's basically a "fudge factor" to guess a reasonable tolerance and hopefully that covers most realistic uses. And we may have to continue tweaking these factors over time, since over many years of supporting the platform behavior, there seems to be no end to mind-bendingly complicated edge cases.

**Comment by AshleyScirra** [comment]
Also since the forum thread was locked as getting too heated, also locking this issue to prevent the discussion resuming here. Hopefully the issue is fixed in the next release; if not, as ever, please file a new issue afterwards following all the guidelines.
