### ISSUE TITLE
Function * (Local variable + Wait) = Local variable don`t reset

### ISSUE THREAD

**Issue by ReviveR200** [Scirra/Construct-3-bugs#4426]
## Problem description

If you add a local variable under the Function, add a sub-event with Wait and change the variable, then Local variable don`t reset.

## Attach a .c3p

[Func.zip](https://github.com/Scirra/Construct-3-bugs/files/5708346/Func.zip)

## Steps to reproduce

1. Preview
2. Click on the button "OK" -> Append text (variable)
3. Click on the button "Go to" -> Go to layout "Layout2" from "Layout1"
4. Click on the button "Go back" -> Go back to layout "Layout1"
5. Click on the button "OK" -> Append text (variable)

## Observed result

![1](https://user-images.githubusercontent.com/62239715/102470260-929c4c00-4075-11eb-8c77-4e18d7c0f46a.gif)

## Expected result

Gif, but without "Toggle disable"
![2](https://user-images.githubusercontent.com/62239715/102470682-1d7d4680-4076-11eb-801d-145bb800bdd3.gif)

## More details

**Affected browsers/platforms:** broke in Chrome

**First affected release:** broke in r220-r229, maybe more

**Comment by AshleyScirra** [comment]
Minimal repro: [issue4426.zip](https://github.com/Scirra/Construct-3-bugs/files/5709222/issue4426.zip)

**Comment by AshleyScirra** [comment]
Thanks for the report, local variables in this case were indeed incorrectly preserving their state. This is fixed for the next beta: local variables inside functions will save their value on "Wait", and restore their value when resuming.

Note however that this makes your project print "1" ten times, since every time "Wait" is used the local variable has a value of 0, so ten times you resume with a value of 0, add 1 to it, then print that. I think this is the correct behavior since local variables inside functions do not remember their value between function calls, and nor should they remember their state between separate resumes in to the same function, only the value that was originally there when "Wait" was first used. To make it print 1 through 10, make the local variable static and reset it to 0 when first calling the function, which makes it explicit that you intend to save the state of the variable: [workaround4426.zip](https://github.com/Scirra/Construct-3-bugs/files/5716510/workaround4426.zip)
This also works around the issue in r229, so you can use that workaround now.
