### ISSUE TITLE
Click Object without dragging Triggers Drag & drop behavior 

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4430]
## Problem description

In my opinion, the DROP will be triggered when the object move exceeds (0, 1] px. So, when I click on the object in place, drag should not be triggered.

![](https://user-images.githubusercontent.com/45864744/102852350-05803b00-4459-11eb-8b04-e28f922a9bac.jpg)

## Attach a .c3p

[ClickObject_ButDontDrag.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/5727942/ClickObject_ButDontDrag.c3p.zip)

## Steps to reproduce
1.  click object but dont drag

## Observed result

1 Drag Start
2 Mouse Left Click
3 Dragging
4 On Drag

## Expected result

1 Mouse Left Click
(Because I haven't started dragging yet.)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design: a drag starts as soon as you click, and a corresponding drag end occurs when you release.

Changing the logic of this would also be a breaking change, since projects relying on drag start firing immediately would be broken if we then introduced a minimum drag distance, so I don't think this is worth the trouble of changing.
