### ISSUE TITLE
Bugs with system saving/loading actions

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#4434]
## Problem description

Issue 1:  Saving with physics revolute joints fails to load, returns console error.
Issue 2: Loading sometimes need two request to work - no error in the console.
Issue 3: Platformer locked on moving direction when focus is lost to browser alert (seems like the button is still registered as down, even when the focus returns, only pressing it again releases it.

## Attach a .c3p

[savingBug.zip](https://github.com/Scirra/Construct-3-bugs/files/5742360/savingBug.zip)

## Steps to reproduce

Issue 1:
1. Run the layout
2. Press 1 to save
3. Press 2 to load

Issue 2:
1. Disable joints action so saving will work.
2. Press 1 to save
3. Press 2 to load
4. press 2 to load again

Issue 3:
1. Move the platformer object left/right
2. While moving press 1 to save and get the browser alert.

## Observed result

Issue 1:
Loading fails, see console error. 

Issue 2:
Second load request is not triggering, the 3rd one will work.

Issue 3:
Platformer keeps moving and ignores other direction requests.

## Expected result

Issue 1:
Loading should work.

Issue 2:
Loading should work whenever it is triggered.

Issue 3:
Keyboard input should be ignored when alerts are displayed.

## More details

**Affected browsers/platforms:** Chrome/NWjs

**First affected release:** tested on r229.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I've fixed issue 1 for the next beta, thanks for the report.

As for issues 2 and 3, firstly please note the bug report guidelines ask to only report one issue at a time as otherwise we can't track them separately. Secondly I believe they only occur due to the use of the alert dialog, which is generally only used for testing and diagnostics, and they don't reproduce if you don't use alerts. So it doesn't seem important to fix it.
