### ISSUE TITLE
Screen recorder example not working properly

### ISSUE THREAD

**Issue by layilpaht** [Scirra/Construct-3-bugs#4435]
I was checking screen recorder example from construct 3 main screen on my android phone. "Record canvas" was working,but "record screen" was not working

## Attach a .c3p

Go to editor.construct.net and in examples, search for screen record

## Steps to reproduce

Launch the project. Select record screen. Nothing happens

## Observed result

Nothing hppened

## Expected result

Screen should get recorded

## More details
 I did this in my android phone.
Browser chrome. And it is updated

**Comment by AshleyScirra** [comment]
It looks like Chrome on Android doesn't support screen recording. There's an open Chrome issue for it here: https://bugs.chromium.org/p/chromium/issues/detail?id=487935

In Chrome Dev it appears to correctly indicate screen recording is not supported, so I think the main issue is the latest Chrome incorrectly indicates screen recording is supported when it is not. That should be fixed in the next Chrome release or two, i.e. just correctly indicating it's not supported - but actual support for screen recording looks like it's still in development (or maybe is just a desktop-only feature).

**Comment by layilpaht** [comment]
Welcome back 🙂
