### ISSUE TITLE
Poor layout performance in event sheet view

### ISSUE THREAD

**Issue by TheRealDannyyy** [Scirra/Construct-3-bugs#445]
## Problem description

I have noticed that C3's eventsheet view gets a bit "choppy" when a lot of events are in use.
Not only that but it also takes quite a while to display collapsed sub-events.

## Attach a .c3p

[Download](https://cdn.discordapp.com/attachments/225550155531812865/321301531569684480/Event_Delay.c3p) here.

## Steps to reproduce

1. Open the project
2. Go to the eventsheet
3. Unfold the collapsed event
4. Notice that it takes up to 2 seconds to load (it's also quite "choppy" while scrolling)

## Observed result

Construct 3 seems to take longer when loading huge event structures.

## Expected result

It should load much faster like Construct 2 did.

## Affected browsers

* Chrome: yes
* Firefox: yes
* Edge: -
* Safari: -

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Nothing.

</details>

**Comment by JeFawk** [comment]
Takes up to 3 seconds on my machine to collapse it.

**Comment by jaydonteh** [comment]
Yes I noticed collapsing lots of events like a group caused the event sheet to refresh each frame until the animation to complete.

Thought I had my UI animation disabled but I guess this is another issue.

**Comment by AshleyScirra** [comment]
Chrome is taking ages to do layout in this case for some reason. I filed a Chrome bug here: https://bugs.chromium.org/p/chromium/issues/detail?id=730585

Closing this report as we'll follow up there. Please star the issue to help promote it and follow further updates.

**Comment by TheRealDannyyy** [comment]
Not sure if it matters but my tests have been done using Chrome Version 59.0.3071.86 (Stable).

**Comment by AshleyScirra** [comment]
Google won't help and this is still an issue, so re-opening. This could be tough, we might have to do some shotgun debugging to work out what aspect is slow.

**Comment by AshleyScirra** [comment]
As mentioned in #765 this also affects Firefox.

**Comment by JeFawk** [comment]
I've noticed a visible improvement if i zoom out from the whole app till ~ 80-70%

**Comment by AshleyScirra** [comment]
I'm not sure there's anything immediately to be done about this issue; layout performance isn't great in any browser, and that seems to be the bottleneck. I've experimented with the code a bit and couldn't get any significant speedup even with removing things, and I tried some alternatives but they have even worse trade-offs (like making expanding/collapsing fast, but the rest of the UI laggy instead). There is work going on in Chrome to rewrite significant parts of the layout engine and improve CSS containment to make some of the tradeoffs less bad. Some of the issues around this are:

https://bugs.chromium.org/p/chromium/issues/detail?id=730585 - original issue filed with Chrome based on this report. Comment 12 has a good overview of the tradeoffs involved and what they can do about it.

https://bugs.chromium.org/p/chromium/issues/detail?id=793374 - issue to improve performance with CSS containment, which currently isn't very effective and limits our options.

https://bugs.chromium.org/p/chromium/issues/detail?id=591099 - long term project to rewrite the layout engine in Chrome (LayoutNG), which should bring performance improvements. (I think Firefox has a similar project too.)

I've starred all these issues so I'll be notified as they're updated. However until then I don't think there's anything else to be done about this, so I think it's best to close the issue and reopen todo items when the Chrome issues see some progress.

One workaround if very large projects are affected is to split events across more event sheets, so there are lots of small event sheets rather than a few large event sheets. This has the side effect of better organising events, so doesn't seem like a terrible side effect. Also if you collapse groups, it no longer does layout for events inside those groups, so you should still be able to work in very large event sheets by collapsing everything, and just expanding the groups you're working in.

**Comment by TheRealDannyyy** [comment]
Alright, thanks for the testing work. Going to star those issues and follow the progress as well.

I know you probably wouldn't like to do this but it might be better to inform C3 users about this "limitation" so that they don't run into this issue and split events across more event sheets from the start.

**Comment by AshleyScirra** [comment]
Well, as I mentioned, splitting events across multiple sheets is probably a good idea anyway, so I don't think we should warn anyone against that :P

**Comment by TheRealDannyyy** [comment]
I was thinking more about something like a tooltip that pops up when a user has 100 or more events on a single sheet (e.g. "_C3 detected a high amount of events in this event sheet. It's highly recommended to split events across multiple event sheets because..._").

Idk, the example I provided is more a of stress-test than a real project anyway so it might not be necessary.

**Comment by AshleyScirra** [comment]
Any time we've ever done that, it was just a burden. The limit is arbitrary, users on high-end systems don't need it, and it goes out of date real quick. For example we used to have an alert warning you if your project used 1GB of memory. Lots of users were happy when we got rid of it!

**Comment by TheRealDannyyy** [comment]
Yes I remember that one, although an option to "don't show again" might have done the job there as well.

I just feel like it's always a good thing to make people aware of stuff like this so you can save time by not answering the same questions about this or similar issues over and over again.

Anyway your decision and thanks again!

**Comment by JeFawk** [comment]
Thanks for the update. Good to know this is being looked into.

One improvement that could be added without big issues would be the suggestion i put up a while ago of collapsing everything with a shortcut and expanding it with a different one (or a button, or anything really).

1 out of 3 times when I open a project i either saved under a different name or something (i really don't know how this happens, it seems random) everything is expanded. I've already split my project into a LOT of event sheets but when i'm running it on my i7 laptop with 3 previews in the background using remote preview, the event sheets are really slow to even collapse groups in. I often scroll down, click then i see the event sheet moved a few more rows and i misclicked it.

Halp :( 

![eventsheets](https://user-images.githubusercontent.com/7268697/34961153-bff9227c-fa46-11e7-81dd-e8a95c82fd64.gif)

**Comment by AshleyScirra** [comment]
@JeFawk do you have a link to the suggestion entry?

**Comment by JeFawk** [comment]
Yes @AshleyScirra  https://construct3.ideas.aha.io/ideas/C3-I-297

**Comment by TheRealDannyyy** [comment]
I'm still following the progress of this and using Chromium 65, it's still terrible with an average of 5fps.
(Tested using the most recent _Demonoire_ example on the "eGameRoom" eventsheet.)

Chrome Performance (60fps Recording):
https://drive.google.com/file/d/1sQT5cvUDE0_9HESvQrjFfUGAzkLhmNfR/view?usp=sharing

FireFox Performance (60fps Recording):
https://drive.google.com/file/d/192QfxH6GEOtVbcSDcyl7FMCbNW0Nhrah/view?usp=sharing

I know there is probably nothing that you could do regarding this @AshleyScirra but maybe it would be worth it to tell the Chromium Dev's that their competition is doing much better than them currently regarding performance. Maybe that could give them a little bit of motivation to do their work.

**Comment by AshleyScirra** [comment]
@TheRealDannyyy is it the same with the default theme? The dark/light themes can have a performance impact.

**Comment by TheRealDannyyy** [comment]
@AshleyScirra Much better performance with the default theme. I get an average ~40fps using that one.

**Comment by JeFawk** [comment]
wow that's a huge difference!
