### ISSUE TITLE
SpriteFont is wrong textWidth at start layout

### ISSUE THREAD

**Issue by kimarutaGM** [Scirra/Construct-3-bugs#4450]
## Problem description
At start of Layout, I call a function **SetCoin** to reposition of Sprite Font and Icon Coin. After that, I press A key to call that function (**SetCoin**) again. The result should be same as before, But the coin and the Sprite Font being change position, this will make a trouble when the text inside Sprite Font become longer, make me cann't calculate exactly the position of SpriteFont and The Coin.
## Attach a .c3p
[https://drive.google.com/file/d/1SC6Sl6Crv3Gf8Hn8wC--a7zGUvjBl3Ft/view?usp=sharing](url)

## Steps to reproduce
1. Start of Layout, the function **SetCoin** was Call
2. Wait 1s, and press A to call Function **SetCoin** again.
3. You will see Coin image and the SpriteFont is being changed position.

## Expected result
When I press A to call Function **SetCoin** again, the Coin Image and the SpriteFont should not be changed position. 

https://user-images.githubusercontent.com/52479622/103622552-7bac9380-4f69-11eb-85b5-81d84a18b8df.mp4

**Comment by AshleyScirra** [comment]
I think this is just a mistake in your events. This minimal project demonstrates the SpriteFont size is correct both on start of layout and when dynamically updating it afterwards: [spritefont-size.zip](https://github.com/Scirra/Construct-3-bugs/files/5771114/spritefont-size.zip)
We ask for minimal projects like that in the bug report guidelines to clearly prove the issue is not a problem with your events. Since your project adjusts the position based on the text size which changes depending on the content, it could easily be misaligning it due to your own logic.
