### ISSUE TITLE
Touch Oh Hold inconsistent

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#4455]
## Problem description
The touch behavior Gesture condition "On Hold" triggers at inconsistent times.
While the time between initiation and trigger is fairly close for multiple uses in one run, it may be off by as much as 1/4 of a second for others.

## Attach a .c3p
https://www.dropbox.com/s/7p8r7mtw1fxu4d2/on%20hold.c3p?dl=0

## Steps to reproduce

1. Run the project
2. Touch and hold, noticing the timer showing how long it takes for the condition to trigger
3. Release the touch 
4. Repeat

The times will be listed to the left until the fifth hold. After that the browser will refresh and start a new run.
Please repeat the process a few times and take note of the time differences. 
## Observed result

The observed times were anywhere from 1.7 to 2.10(5 to 30ms) seconds between runs, and 2 to 10 milliseconds difference in the same.
## Expected result

The times for all holds should be as close as possible, or at least as predictable as a timer.
## More details

**Affected browsers/platforms:** 

**First affected release:** 
All
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I couldn't get your project to report any values on a Pixel 3. Minimal repro that works: [touch-hold-timing.zip](https://github.com/Scirra/Construct-3-bugs/files/5776884/touch-hold-timing.zip)
This does demonstrate the problem - it turns out the touch hold time is supposed to be 500ms, but it can actually vary from 1-2 seconds. This only happened in worker mode, and it turns out it was incorrectly using different clocks between the DOM and worker for timing gestures. This is fixed in the next release to be consistently about 500ms.

> 2 to 10 milliseconds difference in the same

Note since at 60 FPS each frame takes 16ms, and there could be up to one frame error at either end of the timing period, you probably can't expect better resolution than 32ms for timing any period across ticks.

**Comment by pigmalien** [comment]
I figured the difference during regular runs was for fps, which is acceptable.
Thanks for the update, and fix.
