### ISSUE TITLE
Tiledbackground cannot redo some user changes, also crashed on undo

### ISSUE THREAD

**Issue by SnipG** [Scirra/Construct-3-bugs#4470]
## Problem description

Not sure if this is how C3 undo/redo works, could not find any info about it.

Basically if user undo and changes object properties you cannot fully redo all changes anymore. Everything that was done after object properties change, which has to do with frame change, cannot be redone!

## Steps to reproduce

1. Make object with drawable surface: sprite, tiledbackground
2. Edit it and draw something, close animation editor. Repeat once.
3. Click undo, change angle(size,position etc), try to fully redo.

## Observed result
Changing properties looses object redo chain.

## Expected result
Can still redo object changes when needed.

## More details

I got multiple crashes while trying to put together this report, at least 4+ times. 
Error report information
Type: unhandled rejection
Reason: Error: frame is not active @ Error: frame is not active at g.isb 

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 87.0.4280.141
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
C3 release: r231 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 1.4 gb (1.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 660 Ti Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by DiegoScirra** [comment]
There are two issue here.

The first one, is not really a problem but rather how undo systems works. It is a stack of changes, as you make actions you add them to a pile, that way you can go back and forth in the pile.

If the undo system is pointing at the end of the pile when a new change is made, the change is just added at the end and nothing is lost.

If the undo system is pointing anywhere else when a change is made, the new change is added in the current position of the pile, and all the changes coming after it are discarded. This makes sense, because otherwise you would need to keep track of different undo branches and I am not even sure how the UI for that would look like.

Another thing to take into consideration, which is particular to Construct, is that all the changes made in the animations editor are lumped together into a single change once the editor is closed.

Here is a pretty drawing to try and explain that better.
![Untitled](https://user-images.githubusercontent.com/27006273/104588400-34f12480-5660-11eb-8fd1-45494d85c3bc.png)

So that is not going to change, the crash on the other hand will be fixed. it is related to the fix for #4462

**Comment by DiegoScirra** [comment]
The crash will be fixed in the next beta.

**Comment by SnipG** [comment]
Well undo and redo chain was not bug, then it could stay as it is.

I think there is no branching, just linear line. But if user went back and added something, then he already discarded step 4&5, Case is just he cannot undo/redo himself back to it.
But it is like a feature suggestion, which can undo everything. 
Just fiddled around idea and it comes down to:
When overwrite happens, copy redo chain behaind new property and add everything after default chain.
![logic](https://user-images.githubusercontent.com/28864889/104647468-9645e180-56ba-11eb-86a7-29a987a20948.jpg)

Not sure if something like this is feasible, but just my possible solution, if future something like this is needed.

**Comment by DiegoScirra** [comment]
Looking more into this I found an issue relating to #4414. The issue made it seem as if undo points were lost, so it might have been what you were noticing. Anyway, this should be fixed in the next beta.
