### ISSUE TITLE
manuals missing Browser expressions

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#4471]
## Problem description

I am trying to get the width of the browser. However, i can't found similar browser expression in the [manuals](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/browser).

Until I found [this post](https://www.construct.net/en/forum/construct-2/how-do-i-18/fit-game-width-parent-div-133095).

> dop2000:
> Try Browser.WindowInnerHeight and Browser.WindowInnerWidth expressions.

I tried it and it worked. But there is no autocomplete in the editor. It's not even mentioned in the manual.

![02](https://user-images.githubusercontent.com/45864744/104543231-0e32ee00-5660-11eb-8c84-da7ca43f9709.jpg)
![01](https://user-images.githubusercontent.com/45864744/104543157-e0e64000-565f-11eb-986e-f8d814a7e969.gif)

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The browser window size expressions are deprecated. They were moved to the [Platform Info](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/platform-info) object and are present in the manual entry there.

The Browser expressions still work only so we don't break old projects, but otherwise the expression is not displayed anywhere in the interface.
