### ISSUE TITLE
Cordova Webview screen stuttering

### ISSUE THREAD

**Issue by norman74** [Scirra/Construct-3-bugs#4494]
## Problem description

There's some strange screen stuttering appears with c3runtime when built on android with cordova webview.

No matter how complicated code is, there's only 1 event in example below but screen lags persist.

Any project i've tried to compile with cordova webview is impacted. I used both Cordova CLI and built-in construct 3 apk builder.

## Attach a .c3p

C3P: https://drive.google.com/file/d/1ttfhPbohsCvBjVnKj8umOmma6A-Kz_DQ/view?usp=sharing

APK: https://drive.google.com/file/d/1phNyFdUvybZK3jTGYmwDUxfA_rM7oLVj/view?usp=sharing

## Steps to reproduce

To reproduce the issue use c3runtime, there is no screen lags with c2runtime.

1. Start the game on your android device
2. Observe screen lagging

## Observed result

Screen stuttering

## Expected result

Smooth and stable screen updates

## More details

[I captured the screen](https://drive.google.com/file/d/11nwFnIWTSB1AtblkCVPsQOOO5NO7O_3E/view?usp=sharing) on my device in 30 fps, so probably you will not notice stuttering itself but as you can see framerate is almost stable ~1-2 fps drops.

**Affected browsers/platforms:** Android (problem appears when project built with Cordova Webview, but works well in Chrome)

**First affected release:** Tested on r232 beta only

## System details

Tested on Xiaomi Mi5 Android 8.0
Another devices are also affected

**Comment by AshleyScirra** [comment]
It's perfectly smooth for me on a Pixel 3.

Usually device-specific rendering issues like this come down to GPU driver problems (including software rendering due to working around known problems), or frame scheduling issues in Chrome. Both are beyond our control. Your best bet is to report them to Google at crbug.com. If you let me know your issue number I can follow along and provide any Construct-specific details if Google request them.

**Comment by norman74** [comment]
So the issue was closed and seems it won't be fixed by chrome team.
Anyway posting the link here.

https://bugs.chromium.org/p/chromium/issues/detail?id=1171302
