### ISSUE TITLE
Unable to set particle color in events when particle uses sprite object and is set to "one-shot".

### ISSUE THREAD

**Issue by ianmagenta** [Scirra/Construct-3-bugs#4508]
## Problem description

When a particle object is set to use a sprite object (instead of an image) and is set to "one-shot", it will ignore the "Set Color" event.

## Attach a .c3p

[particle_color_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/5878101/particle_color_bug.zip)

## Steps to reproduce

1. Simply run the included c3 Project. You can observe how the one-shot particles (left) react to the "Set Color" event compared to the same particles using "Continuous Spray" (on the right).

## Observed result

The particles kept their default color during their one-shot firing.

## Expected result

The particles should have changed color to the one set in the event sheet during their one-shot firing.

## More details

Nothing more to really add. Unless I'm missing something, one-shot particles that use objects should re-color themselves the same way that their continuous spray counterparts do.

**Affected browsers/platforms:** 

Tested on Windows 10 version 20H2:
- Firefox Version 85.0 (64-bit)
- Chrome Version 88.0.4324.104 (Official Build) (64-bit)

**First affected release:** 

First encountered on r225. Tested it as well on r233 and it is still an issue there.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 88.0.4324.104
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36
C3 release: r225 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 388 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce RTX 2080 SUPER Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
A one-shot particles object creating objects creates all its objects just before 'On start of layout'. If you use the `ParticleCount` expression just before the 'Set color' action, you can see it's already 50. So the ship has already sailed when you use that action. In this case you can just use 'Set color' on the sprites instead, though.

There is some special code in the Particles object to handle adjusting the built-in particle properties, like the particle speed, if they are changed immediately after the Particles object is created. However in object mode, the properties are part of other objects rather than part of the Particles object itself, so it does not apply these. This includes things like the Z elevation the particle objects are spawned at: if you change the Z order of the Particles object immediately after creating it, the objects it created won't be re-ordered either. I don't think this is particularly easy to change, and it looks like there's an easy workaround anyway to just modify the particle objects themselves, so closing.

**Comment by ianmagenta** [comment]
I appreciate you taking the time to respond this and I'll use the work-around mentioned in your answer.
