### ISSUE TITLE
Authentication Error [Google Drive]

### ISSUE THREAD

**Issue by AlonsoGLP** [Scirra/Construct-3-bugs#4525]
I am receiving this error when try to save or open from Google Drive:
Error 401: deleted_client
The OAuth client was deleted.

More users are getting this issue [C3 Forum](https://www.construct.net/en/forum/construct-3/general-discussion-7/authentication-error-158164)

**Comment by ruti951** [comment]
anche a me fa lo stesso errore

**Comment by OneRepCloser** [comment]
I'm also receiving the error.

**Comment by Qwzheng** [comment]
same error with me.

**Comment by mstemigiwa** [comment]
Same error as well
![image](https://user-images.githubusercontent.com/4749013/106856408-aef45680-66be-11eb-820c-10738fb48e1a.png)

**Comment by brantwo** [comment]
I'm also receiving the error.

**Comment by Javanie7** [comment]
Me too, same error here.

**Comment by AshleyScirra** [comment]
Apologies for the inconvenience. We have just released an r234.2 update that should help mitigate the problem. However due to the way Google's verification process works there may still be some warning prompts, but it is possible to get past them. For more information please see [this forum thread](https://www.construct.net/en/forum/construct-3/general-discussion-7/google-drive-cloud-save-outage-158182) which we will keep updated with the current situation and any workarounds.

**Comment by AshleyScirra** [comment]
Everything should now be working normally in r234.4. Once again apologies for the inconvenience.
