### ISSUE TITLE
Signalling server not allowing someone who disconnects to reconnect without browser refresh

### ISSUE THREAD

**Issue by part12studios** [Scirra/Construct-3-bugs#4531]
## Problem description

Hi there, I've been fighting this for a few days now and really can't see what else could be done differently.  I'm using the latest build 234 (stable) but this happened with the last beta version too.. don't think this is a new bug introduced by stable version.  

## Attach a .c3p

[bbs chat.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/5925078/bbs.chat.c3p.zip)

## Steps to reproduce

it's pretty simple to replicate..  

1. i go into my chat room much like the construct 3 example.. everything works.  people can connect and people can leave and the others are informed of that person leaving.  

2. if any person leaves my chat room i have a hot key command to exit (alt + q) which fires off this logic
https://part12studios.com/images/construct3/chat1.png

3. this works fine. the user leaves and is taken back to the main menu.  however when anyone (even the host alone) comes back after leaving they are met with these messages
https://part12studios.com/images/construct3/chat2.png

4. those messages should be 1:1 of the original example, just stylistically different.  

here is my latest version of the chat room.  just hit C to go into it..  enter a user name (5 character minimum) 

https://part12studios.com/games/rd_bbs/rd_bbs_59/

## Observed result

see link above step 3

## Expected result

you should be simply brought back into the existing chat room again.. 

## More details

I'm simply trying to allow users to come and go and not require a browser refresh to reconnect.  that "works" but is very disruptive to the bbs experience..  

NOTE: the logic in the first screenshot was not my only attempt.  any variation of these attempts to leave the room ultimately all result in failure to reconnect.  

It feels like the scirra server perhaps is letting people know the user has left, but perhaps the server itself is not truly "letting go" of that IP address or whatever it's using to identify a unique user thus the user tries to reconnect (using any user name, it's not about that, it's the user themselves that can't get back in).  

Maybe there is a way to do this, but leaving and returning isn't something in the chat room example.  Perhaps the process to properly disconnect and return is managed in a different way that I haven't discovered.

Thanks,
Caleb

**Comment by AshleyScirra** [comment]
The actions shown in this picture are wrong: https://part12studios.com/images/construct3/chat1.png

You try to use "Leave room", "Disconnect from room" and "Disconnect from signalling server" simultaneously. Firstly "Disconnect from room" also does "Leave room", meaning you give two potentially conflicting instructions simultaneously. Secondly these are all asynchronous and require a small amount of time to complete, but you don't wait for them and kick them all off at the same time. Since leaving a room requires being connected to the signalling server until "On left room" triggers (indicating the user successfully left the room) but you disconnect from the signalling server before that process completes, the process does not have the chance to finish and so the user is likely left in the room.

You should do these things one at a time and wait for their successful completion before proceeding.

This mistake has come up a few times before in issue reports, so to investigate further you'd need to provide a minimal project as per the bug report guidelines.

**Comment by part12studios** [comment]
Ok i'll try that.  I had tried a few other things besides this (overkill)
approach but didn't know since none of them seemed to work, but i'll
investigate further and confirm.  Also the other tips / advice are greatly
appreciated.  That makes sense.

Thanks!
Caleb
