### ISSUE TITLE
Unable to toggle visibility if the sprite is on same layer and stacked on top of each other

### ISSUE THREAD

**Issue by prodbysour** [Scirra/Construct-3-bugs#4552]
Sprite will not toggle back from visible / invisible if they are on the same layer and stacked on top of each other in the same X and Y position. 

[VisibilityBug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/5953497/VisibilityBug.c3p.zip)

**Comment by AshleyScirra** [comment]
It's not a bug. Because the objects are at the same position, 'On object clicked' triggers for both objects, causing you to swap the object visibility twice, which means it ends where it started.

Please note as per the bug report guidelines we do not normally investigate reports that do not follow the bug report guidelines. The guidelines are there to try to avoid the situation that you report mistakes in your events as bugs, which is what happened here.
