### ISSUE TITLE
8-Direction Movement Behavior - VectorX and VectorY report non-0 values when they shouldn't

### ISSUE THREAD

**Issue by RobitGames** [Scirra/Construct-3-bugs#4559]
### **Problem description**
I noticed when using the 8-Direction Behavior that VectorX becomes a non-zero value when the player is moving ONLY Up or Down AND VectorY reaches its maximum speed.

It also happens when moving only left. Vector Y becomes a non-0 value when it reaches maximum speed.

However, when  the player is moving to the right VectorY always remains at 0 even at maximum speed - which is the expected behavior.

This causes a problem when using the VectorX and/or VectorY values to determine animations or mirroring.

### **Attach a .c3p**
[Example C3P project](https://www.dropbox.com/s/kps3wxhy0r9nl0r/8dirmove_TEST.c3p?dl=0)

### **Steps to reproduce**
You can replicate this bug using the project file above. 

1. Move the character (using default 8-Direction Behavior controls) in any cardinal direction until it reaches max speed
2. Watch the VectorX and VectorY numbers. 

### **Observed result**
VectorX becomes a non-0 value when the player is moving Up or Down and reaches maximum speed.

VectorY becomes a non-0 value when the player is moving Left and reaches maximum speed.

### **Expected result**
VectorX should report 0 when the player is only moving Up or Down

VectorY should report 0 when the player is only moving Left

### **First affected release:**
Using r234.4

**Comment by AshleyScirra** [comment]
The nonzero numbers are extremely small = in my case I see 1.22e-14, which is 0.0000000000000122.

This is just yet another case of "CPUs don't calculate fractional numbers exactly". It happens in the CPU circuitry, therefore affecting all software development with all technologies. The 8-direction behavior uses floating point calculations, and non-linear operations like atan and sqrt for various aspects of controlling the movement, none of which are exactly precise, so in cases where they ought to produce 0, they can produce an extremely small number instead.

As mentioned this is a standard and well-understood thing in the software industry, but Construct users are often new to it. The workaround is usually just to add a small tolerance. For example if you want to know if the player is moving up, not moving vertically, or moving down, instead of using `<0` and `>0`, you'd use a small value like `<-0.001` and `>0.001`. This eliminates the effect of small rounding errors.
