### ISSUE TITLE
add my plugin to Whitelist plugins

### ISSUE THREAD

**Issue by SurenaMHZ** [Scirra/Construct-3-bugs#4578]
Hi, could you add this to the build service:

cordova-plugin-android-tools

Thank you!

This plugin is available for construct 2 but I need this plugin for my project in construct 3 ;Because it has interesting Android capabilities

**Comment by AshleyScirra** [comment]
I'm afraid "toolbox" style plugins that do a wide variety of completely different things like this are too difficult and time consuming to properly review. Further, many features are either already supported officially (e.g. open URL, rate app), or have no clear purpose for Construct games (why would a game need to change the system brightness or call volume?), which indicates they may possibly only exist or be used for abusive reasons. So there doesn't seem to be a strong reason to support it in the first place.

You can already build with any Cordova plugin using the Cordova CLI. If you really want a plugin supported on the build service, please develop a separate Cordova plugin with just the minimum features you need, and request allowing that, along with an explanation as to why it is meaningful for use in Construct games, in order to justify the security review work.

**Comment by SurenaMHZ** [comment]
Thank you
