### ISSUE TITLE
Scene Graph issue with Timeline

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-3-bugs#4582]
## Problem description

I'm trying to use the scene graph with the timeline to make modular animations but the movement in the timeline contradicts the scene graph. You can see the result below:

https://user-images.githubusercontent.com/2965842/108388313-912b0380-721f-11eb-9d8d-149e05f4bd2c.mp4

## Attach a .c3p

[timeline_graph.zip](https://github.com/Scirra/Construct-3-bugs/files/6004327/timeline_graph.zip)

## Expected result

https://user-images.githubusercontent.com/2965842/108388733-fda60280-721f-11eb-99ca-c41427b78df0.mp4

**Comment by KekGames** [comment]
In your example the upper arm is moved vertically by Sine behavior, plus the forearm and the hand change their Y as parts of hierarchy. And at the same time, your timeline has keyframes for Y coordinate for every object. If you remove the Y property from timeline - it works fine. Sorry if I misunderstood the issue.

**Comment by bilgekaan** [comment]
> In your example the upper arm is moved vertically by Sine behavior, plus the forearm and the hand change their Y as parts of hierarchy. And at the same time, your timeline has keyframes for Y coordinate for every object. If you remove the Y property from timeline - it works fine. Sorry if I misunderstood the issue.

It might look like that fixes the issue (still it won't be the same movement when you remove the Y) for this specific example but the issue is deeper than that and it would affect anything with timeline+scene graph.

**Comment by DiegoScirra** [comment]
The problem is that the editor and the runtime are producing  different results, and it is confusing. That is being worked on.

In this particular case, I think what you need to do to achieve the intended result at runtime, is for the hand to only change it's angle by means of the timeline and leave the rest to the scene graph transformation. That way it looks like the arm is moving while the hand is waving.

Of course, doing that, falls into the same problem of the editor and the runtime showing different things. Instead of the editor looking ok and the runtime looking messed up, it will be the other way around.

**Comment by DiegoScirra** [comment]
Starting with the next beta release, the editor can correctly preview timelines which include instances that are in a hierarchy.
