### ISSUE TITLE
Adding a button to a hierarchy results in black layout

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#4594]
## Problem description

Adding a button to a hierarchy will cause an uncaught exception and stop the layout from loading.

## Attach a .c3p
[Bug Hierarchy.zip](https://github.com/Scirra/Construct-3-bugs/files/6020364/Bug.Hierarchy.zip)

## Steps to reproduce

1. Add a sprite
2. Add a button
3. Select the button
4. Select the sprite with it (Ctrl-select)
5. Right click on sprite
6. Hierarchy
7. Add selection to this instance
8. Run layout

## Observed result

- Black layout
- Console shows: 
`Uncaught (in promise) Error: object does not support scene graph
    at Instance.VerifySupportsSceneGraph (instance.js:11)
    at Instance.AddChild (instance.js:13)
    at Instance.SetupInitialSceneGraphConnections (instance.js:14)
    at Layout._StartRunning (layout.js:14)
    at async C3Runtime.Start (runtime.js:33)
    at async C3Runtime.Init (runtime.js:22)
    at async InitRuntime (ceaa4350-a01f-4c2f-b3e1-b3f7d9bf8a95:7)`

## Expected result

- The button added to the hierarchy.
- Layout loading is not stopped.

## More details

**Affected browsers/platforms:** Chrome.

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.

The fix prevents plugin instances which are not supported by hierarchies to be added as children of instances which are supported by hierarchies. The editor is incorrectly allowing to add a button instance as a child.

If you want to have the button plugin supported by hierarchies (or other instances which are not currently supported), please file a different issue and they will be added on future versions.
