### ISSUE TITLE
Multiplayer cannont join when starting preview with unsaved editor changes.

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#4596]
## Problem description

Trying to send join from peer and host without much time between them, results in the first peer (only the first peer after the host) stuck and getting kicked after a few seconds.
I get the same result if I refresh my preview windows right after changing some thing in the layout (without saving): the multiplayer fails to make the first peer to join a game (host joins just fine).

It might take some time to reproduce, but please be patient. I spent 4 days of my job testing because of this, and I rewrote my whole MP code from scratch, and even started to make my game from scratch. Now I am testing the Pong sample, and it shows the same error.

## Attach a .c3p

[Multiplayer pong.zip](https://github.com/Scirra/Construct-3-bugs/files/6021660/Multiplayer.pong.zip)

## Steps to reproduce

**Please try to execute the following as fast as possible.**
First time:
1. Open the project in Chrome.
2. Press Alt on the debug preview button to create a debug preview window (same result with normal preview).
3. Repeat step 2.
4. Have the 2 previews side by side.
5. Click join in one of them.
6. As soon as possible, click join in the other one.
You may have to refresh (Ctrl+R) one preview and repeat as soon as they reload. The bug will show after less than 10 tries (in my case).
If it didn't show up, please do the following (as quickly as possible):
7. Alt+tab to editor.
8. change the positions of a few controls.
9. minimize Chrome.
10. Refresh previews.
11. Try to click join on both of them without much delay (i.e Repeat from 5).

## Observed result

The host will join, while the peer will have its Paddle destroyed, and show "Attempting to establish connection to host" for a few seconds, before getting "Kicked, either could not connect to host or host quit".
This happens mostly with the first peer only (not the host). In a few cases when I clicked join on 3 peer previews almost at the same time, the 3 peers couldn't join too.

## Expected result

Either the joining stops before it starts (i.e. the paddle is not destroyed), or the peer joins.
Getting a proper error message, or firing OnError.

## More details

I was testing before noon (UTC+02:00) and did not face the issue that much. Now (1 pm UTC+02:00) I can reproduce it almost every time.
Maybe it is related to signaling server, that before noon there were only few people online?
Or it might be related to internet in my region, as most people do not use it at this time (6am-1pm).

While reproducing the bug, I had 2 other projects open in Construct, and 4 previews for one of them. This bug shows with at least 2 previews open at the same time.

I know it could be hard to reproduce, and you guys surely have tons of other things to attend to, but I doubted my code to the last minute and rewrote it multiple times and spent a few days of my job time because I didn't want this to happen to my players.
Please give it a try.
Here are two videos of me reproducing it.
[reprod.zip](https://github.com/Scirra/Construct-3-bugs/files/6022057/reprod.zip)

Please let me know if you need any further details.

**Affected browsers/platforms:** Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I tried doing this 10 times in a row and it worked fine every time. I'm afraid there's little we can do unless there is a reliable way to reproduce the problem.

Besides, it seems like a minor problem - even if there is some kind of problem with simultaneous joins, it should be highly unlikely in practice that two peers join at exactly the same moment. Perhaps it would be a bit annoying while testing, but that shouldn't be a major hindrance to publishing an app. Further, networking is unreliable anyway - there is never any guarantee any particular connection will work, and things can definitely fail unpredictably at any time for any reason. So in a real-world game you should have error messages and a way to go back and start over so the user can try again. If it's a one-in-ten-times type of problem, the second time they try will probably work, so they can get there in the end.

Knowing the code, I can assure you the saved/unsaved state will have no bearing at all on this. Preview uses the state in memory and has nothing to do with what you last saved to storage. It's quite common with unpredictable issues that people falsely correlate them with something unrelated, because it happened once or twice when they did something unrelated and a false conclusion was drawn. I would guess that's what happened here with the "unsaved editor changes" aspect.
