### ISSUE TITLE
Multiplayer.PeerCount shows the peers in the room before OnPeerConnected triggers.

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#4602]
## Problem description
I have a condition that compares peer count of a multiplayer object. It also prints the Multiplayer.PeerCount expression. They both show the peers in the room before the OnPeerConnected triggers.

## Attach a .c3p
[Bug MP Crash(1).zip](https://github.com/Scirra/Construct-3-bugs/files/6029877/Bug.MP.Crash.1.zip)

## Steps to reproduce

1. Run 3 debug (pop up) previews in Firefox (or Chrome).
2. In the small text input on the left, enter a random room name (e.g. "rt653"). Enter the same name for the 3 previews.
3. In the host preview, enter "testserver" (without quotes) in the middle text input.
4. In the 2 peer previews, enter any name (other than "testserver")
5. Click "Press Here To Start" in the three previews.
6. Wait a moment (until the peers start polling the room list), then click "Ready" on the host.
7. Wait a moment, the peers should join (if they got stuck, please refresh and repeat).
8. Read the log messages on the host.

## Observed result
Firefox:
"peer connected: [PEER1_ID](3=0)"
"peer connected: [PEER2_ID](3=1)"
"3" here is what Multiplayer.PeerCount and Multiplayer->Compare peer count return (which is the max peer in the join room action). "=0" and "=1" are the value of a variable that I use to count peers (incremented by 1 in each "On peer connected" event)

Currently, I use the variable to send the next message (shows on peers as "received mode: ...."). If it is >= 2, I send.
If I use Multiplayer.PeerCount instead, and compare if it is >=3 (2 peers + 1 host already there), it will send the message twice, indicating the condition triggered twice (once whenever a peer connects), instead of once (once the 2nd peer connects)

On Chrome (sometimes!):
"peer connected: [PEER1_ID](2=0)"
"peer connected: [PEER2_ID](3=1)"
Chrome shows the correct number of Multiplayer.PeerCount.

I retested twice after writing this and it shows the same behavior like Firefox..

## Expected result

Multiplayer.PeerCount and Multiplayer->Compare peer count action should return the number currently in the room.

## More details
My guess is that when the 2 peers join at the same time, Multiplayer.PeerCount already gets the result before  "On peer connected" triggers. If that is intended, please indicate this in the manual; so we can consider this when using Multiplayer.PeerCount is such contexts.

**Affected browsers/platforms:** Chrome (Version 88.0.4324.182 (Official Build) (64-bit)) and Firefox 85.0.2 (64-bit) and 86.0 (64-bit)

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is actually by design. The process of a peer joining a room goes like this (assuming a host is already waiting in a room and a peer is trying to join):

1. The peer connects to the signalling server
2. The peer requests to join the room on the signalling server
3. The signalling server tells the peer "OK, you joined", and tells the host "A new peer joined the room", at which point the peer count increments.
4. The peer begins establishing a peer-to-peer connection to the host.
5. If the connection is successfully established, 'On peer connected' triggers for the host.

Therefore the peer count does actually increment before 'On peer connected'. In other words it reflects the peer count on the signalling server, even if peer-to-peer connections aren't yet established.

I don't think the Multiplayer object actually has a trigger for step 3 (i.e. "On peer joined room on signalling server"). I didn't think it mattered, since presumably peers were only interested in when peers actually successfully established connections.
