### ISSUE TITLE
Multiplayer not able to join game in Nox and Bluetacks emulators

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#4612]
## Problem description

Multiplayer can connect to signalling server, but fails to join on latest versions of Nox and Bluestacks.

## Attach a .c3p

Pong example. ([Multiplayer pong (1).zip](https://github.com/Scirra/Construct-3-bugs/files/6044430/Multiplayer.pong.1.zip))

## Steps to reproduce

1. Build Android apk (I test with unsigned debug, and signed release. default parameters)
2. Run 2 instances of Nox using its Multi-Drive app.
3. Drag and drop in the apk in the 2 Nox's
4. Wait until it is installed
5. Run both of them
6. Write an alias and press the button to connect and join.
You can also try Bluestacks and repeat from step 3.

## Observed result

The game connects and logs in, but does not join. Stops at the "Joining..." and "Attempting to connect..." log messages.

## Expected result

Connect, log in, and join normally.

## More details

It is probably not a firewall issue, since Nox is connected to Google Play, and we tried disabling Antivirus and Firewall, but faced the same result.

**Affected browsers/platforms:** Nox 7, Bluestacks 4

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This just means it failed to make a peer-to-peer connection between the devices. Whether or not this succeeds depends on the networking configuration: it is not guaranteed to work. In order to increase connectivity and cover all kinds of devices, you may need to run a TURN server. The multiplayer tutorial has more details: https://www.construct.net/en/tutorials/multiplayer-tutorial-concepts-579
