### ISSUE TITLE
Drawing Canvas multiple triggers

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#4619]
## Problem description
Drawing Canvas's On Resolution Changed is being triggered multiple times unexpectedly in specific situations.

## Attach a .c3p
https://www.dropbox.com/s/5ieuz6pmbjoxosr/fslsdcrc.c3p?dl=1

## Steps to reproduce
The conditions for the bug are that the project is in fullscreen mode, and the layer is scaled.

1.Run the project
2.Click the button object to enter fullscreen and scale the layer.
3.Click into the layer to regain focus(somebody else's bug).
4.Use the keyboard arrow keys to move the Drawing Canvas around.
5.Continue moving the Drawing Canvas around randomly until the object triggers the resolution change multiple times.

 ## Observed result
After a short time, and several angle changes the objects trigger will go off even though there are no changes to the objects resolution. Note the object doesn't change its angle, and the bug happens in other circumstances when the object is moving, or the screen is scrolling. Also note that its triggered multiple times, with the color changing, and red x's being spawned in specific areas.

## Expected result
There's no reason for the resolution to change in these circumstances.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details
R237 
Windows 10 Chrome

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by pigmalien** [comment]
It seems like lowers scales are less effected.

**Comment by AshleyScirra** [comment]
This is actually just a variant of "floating point calculations aren't exactly precise".

The Drawing Canvas surface size is calculated by rounding up its display size on-screen. According to the parameters involved, this ought to be exactly 600x600. However since floating point calculations aren't exactly precise, it ends up calculating results like 599.9999999999986 x 599.9999999999993 and 600.0000000000014 x 600.0000000000007, i.e. just above/just below the true size. This is a normal result when calculating with floating point numbers.

The Drawing Canvas surface size is rounded up, since you need a whole number of pixels. This means it gets either a 600px or 601px surface size depending on the particular floating point calculation result. When the surface size changes, it fires "On resolution changed" so you can redraw it accordingly.

A more stable way to handle this would be to put the Drawing Canvas on a HUD layer that does not scroll, so you can avoid moving or scrolling it.

**Comment by pigmalien** [comment]
Alright thanks for checking.
Actually I think planning on not allowing the Drawing Canvas be a static object would be a better solution.
Like it or not the resolution will get changed, I thought the trigger was a suitable answer to that.

**Comment by SnipG** [comment]
Because this flickering has affected me when I have fiddled around with it and also planned to report it some day. 
It occurs especially when there is fullscreen/stretching involved, which is common. I have to ask, why cannot it be forced to handle the size calc differently.

Because the image does not need to be redrawn, nothing has changed. It flickers, while layer, layout, viewport, screen, window and everything else is has same size. In this case it seems the canvas object itself has not decided, which size it should have. 
Sprites, SVG etc also have the same case, it draws once and then if something triggers it then redraws itself and not flickers between. 

From this, 

- do other objects also recheck themselves, in some cases where some calculation forces them to do resize check? Or they can go to sleep instead?

- with some scale, do whole viewport/canvas is redrawn and changed because some rounding errors? Which force whole viewport to flicker redrawn itself. This could massively impact on games that are very static, nothing moves most of the time. Can user check when it happens and force game to sleep / stop rendering?

- 'The Drawing Canvas surface size is rounded up, since you need a whole number of pixels.' - from this it could have big safe zone. If 100x100 is scaled up, it does not matter if it's 600 or 603, it just needs to have 1:1 size to viewport surface or something. SVG also redraws occasionally

- Why is 'clean itself' first thing it does, and not just draw on top of itself and give slightly blurred image, if user like he can delete the content. From Guide "This is destructive, because internally the drawing surface is destroyed and recreated at the new resolution." - it seems good reason, but it makes 0 sense, I know it follows overall runtime rendering that's why it does it. But runtime rendering could also not clear itself, if screen is already filled up by objects, then there is no need for it.
- It should be possible for user to paste old content back, but in case of flickering, you need to trigger this pasting  a lot! 
Also from Guide 'This is destructive' I  mean the image is still in memory, if it fits image back and blurs/scale it, it might not be so bad and faster if user issues a some sort of pasting itself back. Common sprites are allowed get blurry if you scale and mipmap helps sprites. 

There are already restrictions on drawing canvas. This flicker is very random, impacts alot(clears everything) and restricks it even more.


Why flickering between two states is not a bug, when nothing else changes? Should it be feature suggestion instead?

**Comment by pigmalien** [comment]
One more question.
If this isn't a bug then why is the Drawing Canvas not being cleared when the resolution changes?
If there is no change to the texture when its resolution changes **every time** then what is the purpose to having the trigger?
