### ISSUE TITLE
wrong Text alignment in iPhone

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#4621]
## Problem description

A text position in Android VS iPhone is different. In Android its okay but in iPhone it slightly down to its position. See image
![wrong pos](https://user-images.githubusercontent.com/17684135/109506381-927fea00-7ac3-11eb-8539-b61601a3f895.jpeg)

## Attach a .c3p
[text position.zip](https://github.com/Scirra/Construct-3-bugs/files/6062063/text.position.zip)

## Steps to reproduce

1. open attached file
2. do remote preview on both Android and iPhone

## Observed result

iPhone showing text position slightly down

## Expected result
position should exactly same as position in layout

## More details

iPhone 7 Plus (iOS 14.4)

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It looks like this isn't a regression - it seems to have worked the same way in the latest stable release. So as best as I can tell, it's always worked this way... also between these two cases, it's not really clear which is meant to be the right one either. I would guess that Chrome and Safari have different interpretations of the text baseline.

It works better in the latest beta if you enable BBcode, since we have updated code for calculating the text size, so it gets a better vertical position. That works more consistently between the two, so I would advise using that for the time being, and I'll look in to this and see if I can find why the text is positioning differently.

**Comment by AshleyScirra** [comment]
So it turns out even when using top alignment, Chrome and Safari draw the text at different positions. They seem to have a different idea of where the "top" baseline is. This is kind of surprising because without using BBcode - including all usages in C2 since 2011 - the Text object uses the "top" baseline, and I don't recall this ever coming up in the past. So I would guess either Chrome or Safari changed how they handle this in a recent release.

I'm not sure which one is the correct one, but I filed an issue for Chrome here: https://bugs.chromium.org/p/chromium/issues/detail?id=1183752
I'll follow up the issue and see what happens regarding browsers and the specification, and amend Construct if necessary (but we might not need to make any changes if the change only needs to happen in the browser).
