### ISSUE TITLE
9patch objects appear distorted in Safari and iOS (take 2)

### ISSUE THREAD

**Issue by lukasinspace** [Scirra/Construct-3-bugs#4626]
## Problem description

When using Construct 3 in Safari on MacOS, 9patch objects appear distorted when placed into a C3 layout.
When changing the 9patch object margins, the correct dimensions of the artwork are not maintained.

Distortion is also present if the project is exported from C3 running in Safari to iOS.

This is my second attempt submitting this bug. I thought I attached a project file first time. My bad. File attached this time.  
[9patch_test.zip](https://github.com/Scirra/Construct-3-bugs/files/6067956/9patch_test.zip)

## Steps to reproduce

1.Open the attched c3p in Chrome on Windows, or Chrome on MacOS. See in the editor that the 9patch object placed into the layout is pixel perfect with no distortion.
2.Open the same c3p in Safari on MacOS. See in the editor that the 9patch object placed into the editor is NOT pixel perfect.
3.Change the left and right margin settings for the object and notice that the distortion of the 9patch artwork changes. Some elements become thicker, others become thinner.

## Observed result

9patch artwork in MacOS safari is distorted in the editor.
If the project is exported for iOS and tested on a device, the distored appearance of the 9patch object is also apparent on iOS when tested on an Apple device.

## Expected result

Would expect the artwork to stay pixel perfect, matching the original artwork imported into the 9patch object (as is the case with 9patch objects in Chrome on Windows and MacOS)

## More details

**Affected browsers/platforms:** 

Safari on MacOS
iOS when project exported from C3 running is Safari on MacOS.

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It looks identical to me on Chrome for Windows and Safari on macOS. Am I missing something? I'm afraid there's little we can do if we cannot reproduce the problem.

**Comment by lukasinspace** [comment]
This is how it looks in Safari to me. Not pixel perfect. This is looking at the object placed into a layout.

![9patch_bug1](https://user-images.githubusercontent.com/22804707/109641718-25915080-7ba6-11eb-8c9d-95127ce1abb5.png)

And this is in Chrome on Windows: Pixel perfect. Again 9patch oblect placed into layout.
![9patch_bug2](https://user-images.githubusercontent.com/22804707/109641723-26c27d80-7ba6-11eb-8bcd-c9db85742cc1.png)

**Comment by AshleyScirra** [comment]
Oh right, I see. I remember this is a problem with Safari because it only supports WebGL 1, and so can only tile power-of-two size textures. Since you're using a left margin of 14, in order to use the tiling mode you've set, the engine is forced to resize it up to the next power of two size (16px) to tile it, but that operation is lossy. I'm afraid there's nothing much we can do about this, we just can't tile a 14px image in WebGL 1. Safari should be supporting WebGL 2 some time soon, or alternatively, make sure the 9-patch margins are all a power-of-two size and then the engine won't have to resize it, allowing your pixel art to be preserved exactly.
