### ISSUE TITLE
Texts get mixed up when it contains different languages

### ISSUE THREAD

**Issue by fredriksthlm** [Scirra/Construct-3-bugs#4650]
Well, this is a bit odd thing actually...
If you mix languages that are written right-to-left and other languages that are written left-to-right in the same text field it can show odd/wrong order of the words.

In my case I import names into C3, which different users has stored in a database. They can then be written in left-to-right (like latin or chyrillic) but they can also be right-to-left (like hebrew or arabic). When putting all these names into one textfield it can happen that some text show up in a "strange" order.. At least to me this is a bit odd.

## Attach a .c3p
[example.zip](https://github.com/Scirra/Construct-3-bugs/files/6110122/example.zip)
(This is a c3p)

## Steps to reproduce

1. Open the project
2. Look into the event sheet to "understand" how the names "should" be populated.
3. Preview the project

This is the event, the three Text-fields used contains three different names.
![image](https://user-images.githubusercontent.com/76128871/110508206-1019aa80-8101-11eb-9ade-b57102fc5631.png)

## Observed result
When all three names are left-to-right (Latin), it shows up like this (which to me is logic!)
![image](https://user-images.githubusercontent.com/76128871/110508367-3b9c9500-8101-11eb-9171-1e1144feae3b.png)

If the first name is right-to-left (arabic), it shows like this:
![image](https://user-images.githubusercontent.com/76128871/110508485-52db8280-8101-11eb-946c-01bfd6036407.png)

If both the first name is left-to-right (arabic and hebrew), it shows like this:
![image](https://user-images.githubusercontent.com/76128871/110508704-933b0080-8101-11eb-9bda-5abffaf58d46.png)

If all three names are left-to-right it shows like this:
![image](https://user-images.githubusercontent.com/76128871/110508815-b5348300-8101-11eb-9fbb-70437f63c71f.png)

If the middle name is a combination of both left-to-right and right-to-left then that poor guys name is totally mixed up.. But at least the numbers was in the correct place :)
![image](https://user-images.githubusercontent.com/76128871/110509077-02b0f000-8102-11eb-8646-b29bd3e379d5.png)

## Expected result

Well...... I would have expected that even though a single name would be righ-to-left I still would have though that the order and numbers would still be in the "correct" order in the rest of the text field..

Note: The above is just random examples. You can try copy in different words from different alphabets into the three text fields in the project and you might experience also other strange behaviours 

## More details

I understand that this issue just seem like odd behaviour that no one would use, but I actually I experienced this when one word was in hebrew in a textfield where the rest was latin words...

**Affected browsers/platforms:** 
I can see the same behaviour in an exported apk, as well as directly in preview in the editor, I use Windows10. Latest C3.

**First affected release:** 

I believe maybe this has "always" worked like this?

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is not actually a bug. Welcome to the complications of [Bidirectional text](https://en.wikipedia.org/wiki/Bidirectional_text).

Unicode effectively defines three types of direction: left-to-right (LTR), right-to-left (RTL), and indeterminate ("weak characters" in the linked article). The numbers and punctuation have an indeterminate direction, which in this case means "carry on with the last direction". The English name has a LTR direction, and the Hebrew and Arabic names have an RTL direction.

The direction is determined character-by-character through the string, and automatically flips the direction when it comes across a character with a different text direction. Suppose we use imaginary [rtl] tags to indicate the resulting direction (note these do not exist in Construct, but they help explain what is going on) - you effectively end up with this:

`1 [rtl]ArabicName 2 HebrewName 3 [/rtl]EnglishName`

That's what you set the text to, but with some automatic direction flips added. Notice that when it comes across an RTL character, it flips the direction; the indeterminate characters keep going; and it only flips it back when it reaches English text that is definitely LTR. Since the content of the RTL tags runs in the other direction, you end up with a visual text ordering approximately like this:

`1 3 HebrewName 2 ArabicName EnglishName`

This isn't exactly what is produced in your example - this is an oversimplification and the actual algorithm is more complicated, but it demonstrates why the ordering gets mixed up.

You can fix this with unicode control characters, which are invisible characters that force the text direction, but they're kind of awkward (being invisible, it's hard to tell if they're really there), and I'm not sure they are universally supported. However as it happens BBcode tags also solve this. For example if you put each name in `[b]` tags, they appear bold *and* the ordering is restored to what you want. The reason for this is the content of any BBcode tag is measured and drawn independently of the rest of the string. This avoids the automatic LTR-RTL flips which aren't working like you want.

You may want to show the text without any formatting at all, but as it happens, there's actually already an undocumented feature in Construct that can do this: the `[insert]` tag. This measures and draws the content of the tag independently, avoiding the automatic flips, and also does not change the style of the text. So you can use an expression like:

`"1. [insert]" & Text.Text & "[/insert] 2. [insert]" & Text2.Text & "[/insert] 3. [insert]" & Text3.Text & "[/insert]"`

This does what you want, isolating the inserted bits of text so the text direction is handled separately for each, and producing the intended overall ordering. I added `[insert]` to the [Text manual entry](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/text) to document this feature as it's useful for this case.
