### ISSUE TITLE
GoogleService-Info.plist set as reserved file that is not renamed into lowercase.

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#4653]
## Problem description

Hi, please make the `GoogleService-Info.plist` into a reserved file that is not renamed into a lowercase file `googleservice-info.plist`.
It's causing issues with exported Firebase projects.

Before import to the `Files` folder:
![image](https://user-images.githubusercontent.com/31282960/110584111-aef9e180-81a9-11eb-8a85-7bf26b420736.png)

**After import:**
![image](https://user-images.githubusercontent.com/31282960/110584177-c46f0b80-81a9-11eb-8c93-c9d7d1263dce.png)

Please make the file retain its letter case, since it's a Google Firebase requirement.

Thank you!

**Comment by AshleyScirra** [comment]
This would actually be a pretty complicated change to make. The entire editor, export system, and runtime, expects all project file names to be lowercased. This was done to avoid 404 errors on case-sensitive servers. Can you find a different workaround?

**Comment by Chadori** [comment]
I understand.

> Can you find a different workaround? Perhaps the file could be bundled as a dependency with an addon, for example.

Unfortunately, nothing comes up.
This file is actually an app credentials file, each application has its own values, sort of like Mobile Advert and its keys.

**Comment by AshleyScirra** [comment]
I really hate making changes like this as they create inconsistencies and can end up causing bugs years down the line... but I added a hard-coded exception for a project file named "GoogleService-Info.plist" specifically to preserve its case on export. All other files will still be lowercased as that is by design to avoid case sensitivity problems. Hopefully that will be all we need to do and it won't cause any unexpected problems...

**Comment by Chadori** [comment]
Thank you!
