### ISSUE TITLE
Anchor behavior: wrong position for first tick

### ISSUE THREAD

**Issue by Dramamini** [Scirra/Construct-3-bugs#4666]
## Problem description

Problem with anchor behavior and wrong position for first tick, was fixed in r239 but not completely.. 

## Attach a .c3p

[anchorProblem2b.zip](https://github.com/Scirra/Construct-3-bugs/files/6136526/anchorProblem2b.zip)

## Steps to reproduce

1. Run / Preview attached project
2. Click "Restart Layout" button, to see the problem

## Observed result

Button, text and line are losing position for the first tick. 

## Expected result

Everything should be stable in position. 

## More details

• Button has the anchor behavior however it is moving.
• Text and line objects are moving but they don’t have the anchor behavior. They are pinned to an object that is pinned to another object that has the anchor behavior.
• Object with anchor behavior stays in place. 

**Affected browsers/platforms:** Chrome/Firefox, Windows

**First affected release:** r239

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 89.0.4389.82
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36
C3 release: r239 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 269 gb
Storage usage (approx): 682 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce G105M Direct3D11 vs_4_1 ps_4_1)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
There are two things going on here:

1. The Pin behavior is attached to an object with the Anchor behavior. This means whether the position updates immediately depends on the order the behaviors run in. For example if the Anchor behavior positions the object, then the Pin behavior positions the attached object, it works; if it's the other way round, it will have the wrong position until the next tick. This cannot really be solved, since behaviors don't have a defined order that they run in. You can however use the scene graph instead, since attaching children always updates their positions immediately, avoiding the tick-sequencing issues of the Pin behavior. In fact, the scene graph is basically a better replacement for the pin behavior, so you should just use that.
2. Form controls like Button are actually HTML elements that float above the canvas. The browser paints them separately to the canvas. So even if Construct updates its position correctly on the first tick, it's possible the browser already painted it in the position it was originally created in. This is also difficult to fix, since Construct only controls the painting of the canvas, not anything else. I think the best thing to do is make the button create invisible, and make it visible on the first tick when its position is updated.

I don't think there is much we can do about either issue I'm afraid, so closing - but note there are workarounds for both.
