### ISSUE TITLE
Poor performance on Android device (LG G Stylo) - simple game

### ISSUE THREAD

**Issue by part12studios** [Scirra/Construct-3-bugs#467]
## Problem description
android debug builds run poorly with simple game

*Enter a concise description of your problem here*
I make a build and install it on the phone.  i must run unminified because if minified it will not load.. just showing a black screen.  when i play the game seen here http://part12studios.com/temp/Games/soaring/ on the phone in chrome or on a pc it runs great, but in the app the frame rate struggles.  its playable but probably 10-12fps on a device that can play it solid / fast fps in chrome.

## Attach a .c3p
[Soaring.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1061444/Soaring.c3p.zip)

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. build the app as a debug version
2. open the app
3. play the game and see how laggy it is.  

## Observed result

*What do you see happen?*
it runs poorly

## Expected result
it should run smooth like it does in Chrome on the device

*What did you expect to happen instead?*
it ran poorly.. maybe 10-12 fps

## Affected browsers

* Chrome: no
* Firefox: yes/no ???
* Edge: yes/no ???
* Safari: yes/no ???

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

Running r36 in this build but i've been observing this behavior since at least r34 and no performance changes have occurred. feels just as laggy.  

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please always include your system details. They include your C3 version, and we made some Cordova changes very recently, so we need to know if you are using those changes.

**Comment by part12studios** [comment]
ok understood, i missed that in the template on github.  i am using r36 for this latest issue. it has performed no better since r34  

one thing i’d ask.  is it possible to put a “force update” or some kind of button somewhere to initiate revision updates.. seems like when i know i’m anticipating an update i have to fumble around refreshing / going to about.. etc..  maybe making rXX number somewhere visible persistently somewhere so people know what version they are on?  i do see the notifications to update, but it just feels clunky to not really know what version i am on unless i go to the about page and when i see i’m not on the latest.. i fumble around some more till the update appears to take effect.  Just a thought.  

Sincerely,
Caleb Garner / 615-818-8483
Game Producer @part12studios <http://part12studios.com/>

**Comment by AshleyScirra** [comment]
I tried it on a HTC 10. It starts a bit choppy but then settles down to a smooth 58-59 FPS. I'd guess it's just another case of GPU blacklisting. Can you check chrome://gpu on the device (in the Chrome browser) and paste the details here?

**Comment by part12studios** [comment]
Yea that might explain it. Silly they do this.  like my iMac with Chrome.. wtf.. it runs C3 just fine.  here is the text from that report on my device:
https://www.dropbox.com/s/5znwtf9vayvdg90/lg%20phone.txt?dl=0 <https://www.dropbox.com/s/5znwtf9vayvdg90/lg%20phone.txt?dl=0>

**Comment by AshleyScirra** [comment]
Hmm, says it has hardware-accelerated WebGL. Unless the web view uses a different GPU blacklist, not sure that's the cause.

**Comment by part12studios** [comment]
Are there any published android games made by C3 on the App Store currently? I could perhaps install some of those games and see if there is a difference. 

The GPU on this unit is not bad it plays other games just fine so it's peculiar that my game would run so choppy and others wouldn't. 

The unit is even daydream compliant. At least I saw a daydream as an option under settings on this device which I thought was interesting. 

Thanks,
Caleb Garner
www.part12studios.com
615-818-8483
"If there are typos, it is Siri's falt"

**Comment by part12studios** [comment]
we know the game runs fine in chrome itself in the browser so it makes sense that this isn’t a clear cut problem.  what in cordova checks for hardware?  we know it’s in Cordova..  how can that be troubleshot?  

Sincerely,
Caleb Garner / 615-818-8483
Game Producer @part12studios <http://part12studios.com/>

**Comment by part12studios** [comment]
from what i can tell no changes in R37 will effect Cordova is that right?  should i bother trying R37 for iOS or Android issues?

**Comment by simoneddeland** [comment]
@part12studios Check out my forum thread https://www.scirra.com/forum/cordova-stuttering-on-android_t191976?start=20 where I talk about the same issues that you are having, though not as severe. I did some measurements with the value of the dt variable and the Cordova build performed worse than a web export, for me the Cordova app has a high FPS but experiences frequent stuttering.

**Comment by part12studios** [comment]
Thanks for sharing.  yea i don’t know if it’s the same or not, but regardless it’s definitely not our issue.  we shouldn’t have to “work around” something this fundamental so I hope they are able to find an answer in the near future or be ready to issue some refunds.. i couldn’t build an app without paying the full subscription..  only then to see it doesn’t work..  might need to come back in like six months and just keep working with C2 in the meantime. .

**Comment by shortercode** [comment]
Just to update the status I ran some profiles on Android yesterday, and did some additional reading on differences between the Chrome and WebView implementations. I used your game for the profiling. Bare in mind these were taken on a more powerful Android phone.

### Profiling

Device:
Oneplus 3
Android 7.1.1

In terms of busy frame time I was seeing about 2 - 4ms per frame of JS time, and perhaps 3ms of GPU time. ( so less than half the available frame time ). What I did notice was that VSync on my device was quite variable, and hence the actual frame interval was over quite a range. Most of the frames still sat around the 16.6ms(60Hz) time, but I saw frames from about 14 - 21ms.

I'm going to try get some more detailed information, and record basically any device I can get my hands on in the office that will run it, then report back here with my findings.

### WebView changes

So a few things have been going on with the Android WebView that I wasn't aware of. As of Android 7 it has basically been retired, and now the device will use Chrome directly for rendering. Unless the user specifically chooses the WebView APK. There is still a difference between how rendering is done between chrome and a webview though. Chrome itself can run it's render multi process, but due to some old Android synchronous rendering limitation when run as a webview it has to run in a singular process. They are working on fixing this, and can be enabled in the developer options on Android 7. It will be released enabled by default in Android 8 supposedly. I actually tried this out, and didn't see a huge amount of difference but then it is still in development.


**TL;DR** No answers yet, still trying to replicate. Android VSync sucks.

**Comment by simoneddeland** [comment]
@shortercode Here is the game mentioned in my forum thread if you want to use if for profiling as well. 
[TappyPlane.zip](https://github.com/Scirra/Construct-3-bugs/files/1081554/TappyPlane.zip)

If you can get your hands on a Samsung  Galaxy S5 Neo you should be able to replicate my stuttering.

**Comment by shortercode** [comment]
Thanks @simoneddeland I think the best I have available is a Samsung Tab running android 5, and by best I mean slowest! Not sure how that compares to the Neo, but there's a few other devices lying around that hopefully still work.

**Comment by part12studios** [comment]
https://www.dropbox.com/s/81iv8y3i65vb2pr/IMG_2174.JPG?dl=0

https://www.dropbox.com/s/l2qe8pwmewexz27/IMG_2175.JPG?dl=0

https://www.dropbox.com/s/0x3kf4668nrqwk0/IMG_2176.JPG?dl=0

these are the numbers on my device.  i don’t know if those are good or not..  seems not bad.   the game did play ok overall.. wasn’t 60fps… but it wasn’t as choppy as I experienced with my game.  

Sincerely,
Caleb Garner / 615-818-8483
Game Producer @part12studios <http://part12studios.com/>

**Comment by triptych** [comment]
Try using chromium on Android as well - it seems that there have been many memory issue fixes.

**Comment by part12studios** [comment]
The game runs fine on Chrome in android.. it’s when it’s made into a cordova APK that I experience problems with my simple game

http://part12studios.com/temp/Games/soaring/ <http://part12studios.com/temp/Games/soaring/>  

it plays blazing fast on my device in Chrome so it’s not the broswer.. it’s the way the cordova app is running.  

Sincerely,
Caleb Garner / 615-818-8483
Game Producer @part12studios <http://part12studios.com/>

**Comment by AshleyScirra** [comment]
@part12studios - could you try installing this app and seeing what the performance is like in that? https://play.google.com/store/apps/details?id=com.html5test.webview&hl=en_GB

That is just a wrapper for the Android webview. The result running in that should tell us if it's the Android webview or Cordova itself that's causing a slowdown.

**Comment by part12studios** [comment]
moved some images around.. but here is the benchmark
https://www.dropbox.com/s/sr0dzqsk8xj6z17/IMG_2177.JPG?dl=0

504 of 555 points..  everything was in the green except:

output 3/10
full screen support - prefixed
web notifications - no

payments 0/5
Web payments - no

other performance pictures are now here
https://www.dropbox.com/s/81iv8y3i65vb2pr/IMG_2174.JPG?dl=0
https://www.dropbox.com/s/l2qe8pwmewexz27/IMG_2175.JPG?dl=0
https://www.dropbox.com/s/0x3kf4668nrqwk0/IMG_2176.JPG?dl=0

Sincerely,
Caleb Garner / 615-818-8483
Game Producer @part12studios <http://part12studios.com/>

**Comment by AshleyScirra** [comment]
No, the HTML5 test itself is not important, I meant for you to run your game in that app. Are those pictures from your game running inside the HTML5 test app? It's not clear what they refer to.

**Comment by part12studios** [comment]
not i didn’t do it before but now I have tested my game in the app.. so this was my take away from it:

- playing the game in this app you suggested had the choppy behavior i’ve seen in the apk in landscape or portrait

- chrome in portrait in the android device also showed choppy behavior BUT in landscape the game ran noticeably smoother.  there was some slight chop and i’m not sure i’d say it’s acceptable considering how basic this game is.. but still better..   and the game is intended to be played in landscape.  


Sincerely,
Caleb Garner / 615-818-8483
Game Producer @part12studios <http://part12studios.com/>

**Comment by simoneddeland** [comment]
@AshleyScirra @shortercode I tested my game (The "Tappy plane" game referenced earlier, also referenced in my forum thread here https://www.scirra.com/forum/cordova-stuttering-on-android_t191976?start=20 ) with the HTML5Test app.

The performance when running my game in the HTML5Test app is a lot closer to the performance I have on my Chrome browser than the Cordova app, there is still some minor stuttering but not enough to be bothersome. Expandin the performance stats I already measured with my app (which measures the value of the dt variable) here are the results:

**Cordova**
- 0 - 20 ms: 90 %
- 20 - 40 ms: 8.5 %
- 40 - 60 ms: 1.2 %
- 60+ ms: 0.3 %

**Chrome**
- 0 - 20 ms: 99.5 %
- 20 - 40 ms: 0.4 %
- 40 - 60 ms: 0 %
- 60+ ms: 0.1 %

**HTML5Test**
- 0 - 20 ms: 98.6 %
- 20 - 40 ms: 1.3 %
- 40 - 60 ms: 0 %
- 60+ ms: 0.1 %

**Comment by AshleyScirra** [comment]
Okay, based on @simoneddeland's data this suggests Cordova is the performance problem, not the webview. I think we should do a bit more testing to confirm that, though.

**Comment by AshleyScirra** [comment]
There's another report on the forum and it sounds like C2 is affected as well: https://www.scirra.com/forum/mad-performance-difference-between-html-and-cordova-export_t193904

Given reports of this only started recently I'd suspect a recent Cordova update has added an unreasonably high performance overhead. I think the next steps would be to isolate which Cordova version is affected and file an issue with Cordova about it.

**Comment by simoneddeland** [comment]
@AshleyScirra I'd be happy to run some games for testing purposes on my Samsung Galaxy S5 Neo if you can send me an .apk made with Construct 2 and an older version of Cordova. I don't have a C2 license so I can't do it by myself.

**Comment by part12studios** [comment]
yea please let me know what I can do to help test with my hardware.  

Sincerely,
Caleb Garner / 615-818-8483
Game Producer @part12studios <http://part12studios.com/>

**Comment by shortercode** [comment]
I'm still looking into this on occasion, but haven't found anything concrete yet. However, [this chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=555116) is interesting and possibly related though.

The tl;dr of it is some mobile devices support webGL in chrome, but not in webview.

I'm not sure if the status of this changed, but apparently quite a few devices were affected including the S6 Edge and the Nexus 10.

**Comment by part12studios** [comment]
Hi Ian,

Thanks for following up about this and the follow up means a lot.  :)

While I’m no chromium pro, what you’re saying does seem consistent with what i’m experiencing.  The fact that the same game plays GREAT on my hardware in the native “browser” and “chrome” is what frustrates me.  Cordova is using the native browser right?  so it seems odd that if it is using the browser as it’s canvas.. why would a cordova app not support webgl like the actual browser does? 

Thanks,
Caleb

**Comment by shortercode** [comment]
So it's a bit complicated by what version of Android your using. Cordova uses whatever "webview" the OS provides.

A brief history of the Android WebView:

> **Android 4.3 and below**
> The webview was part of the OS, so it only updated when you got a new version of Android ( which was pretty rare event, you got maybe 3 updates over the life of a phone ). It was also not based on the Chromium / Chrome project so it supported different features and generally had bad performance. Many people got around this by adding Crosswalk to their applications, this packaged a complete version of Chromium into your app so that you wouldn't have to use the inbuilt WebView. It also added around 30MB to your game size.
> 
> **Android 4.4 and above**
> The WebView became an application, so that it could be updated by the play store app. The WebView was based on Chromium, but was independent of the version of Chrome you had installed.
> 
> **Android 7.0 and above** 
> The WebView was removed completely. Now the version of Chrome you have installed on your device is used for the WebView.

So this specific issue arose during the middle time-span, while the chromium team was trying to figure out how to safely use openGL as webGL within the browser. GPU's have a long history of bad bugs and exploits, as such giving bare metal access to a arbitrary website was considered pretty risky. In chrome they decided to put the openGL parts into their own process, to isolate it from the rest of the browser.

For some unexplained reason it wasn't possible to do this within the WebView, so instead they decided to use some security specific openGL extensions to add extra protection. This worked great, but it's up the GPU manufacturer to add these openGL extensions and some devices didn't have them.

Any device that didn't have these extensions, didn't get WebGL in the WebView. But would have got it in Chrome, provided it didn't have any major GPU bugs.

**Comment by AshleyScirra** [comment]
I checked and multiprocess webview was enabled in Android 8.0, but I'm not sure if this covers the GPU process or not? Essentially this seems like an issue that has been fixed, but we still have a bunch of old Android devices hanging around that have WebGL blacklisted in the webview due to a GPU driver that is considered insecure.

GPU drivers strike again :(

**Comment by part12studios** [comment]
This reply is to Ashly and Iain,

Thanks for the history on webview stuff.  I have Android 6.0 on my particular phone.  So yea that explains that.  

So with 7.0 and above are you saying that if no one installs chrome on the device it has no webview or perhaps Chrome is now standard with all 7.0+ devices?  

Ok so my final question would just be if there might be some way i could hack my device to not be blacklisted or whatever might be possible to enable it.  this is not a phone i use for anything but android testing (or at least it was the plan when I bought it) so maybe something could be rooted or something?  I just paid like $100 for the phone to use for testing and I hate that it’s pretty much a brick as far as I’m concerned if I can’t use it for that.  I know i could try to sell it again.. but before I go that route I want to be sure I explored my options.


Thanks,
Caleb

**Comment by SebaSOFT** [comment]
I think it has to do with the current state of Android WebView I've been encountering. The Construct 2/3 tutorials and documentation point that using any device with Android 5+ would benefit of using native WebView. The Truth is that WebView was left outdated for many devices that have Android 5+ but the WebView is a lot more buggy/old that the last Chromium used in Jan 2017 (latest version of Cordova). 

Ergo, this devices all benefit of using Cordova rather than the native WebView. I't pretty clear once you test in Chrome for Android and performs several times better (both render and physics) than native WebView. The APK size here is not a problem at all compared to the gross bugs in touch detection, frame rate and all.

@AshleyScirra I think this is a valid point to remark in the documentation and exporters, as is not always advisable to leave Cordova out even in "new" low end phones.

**Comment by AshleyScirra** [comment]
At this point we currently believe this actually stems from a specific GPU blacklist entry in Chrome that only affects the webview. There's a bug filed here where we're following this up: [crbug.com/810928](https://bugs.chromium.org/p/chromium/issues/detail?id=810928)

Users with old software have old software, there's nothing new about that. They could equally have an old browser, but we don't warn people exporting with HTML5 about that, it's just the nature of the ecosystem.

**Comment by SebaSOFT** [comment]
Outdated webview or blacklisted GPU could be two faces of the same coin. I've seen Cordova overall perform better in any Android between 5 & 7 since I should test and create any possible scenario of hundreds of phone models that the performance varies and create at least 6 versions of my APK for any given update.

**Comment by part12studios** [comment]
I thought cordova leveraged the native browser.  which is why it’s smaller and (usually) runs better..  compared to crosswalk which had it’s own full “engine/browser” wrapped in it.  as far as i could tell i’m using cordova when i do builds with Construct 3’s built in apk maker.  

Sincerely,
Caleb Garner / 615-818-8483
Game Producer @part12studios

**Comment by SebaSOFT** [comment]
Updated my comments, when I said Cordova I meant Crosswalk. I always compile using Cordova CLI

**Comment by part12studios** [comment]
Ok that makes a lot more sense :) 

Sincerely,
Caleb Garner / 615-818-8483
Game Producer @part12studios

**Comment by AshleyScirra** [comment]
Yes, the Android webview does use the Chrome engine on the system, but there are still GPU blacklist entries that only affect the webview, due to various technical differences about how the webview works.

Crosswalk was able to completely disable the GPU blacklist, whereas this is not currently possible in the webview. So in devices where the webview had WebGL disabled, Crosswalk was able to bypass that and use it anyway. One of the things we're discussing with Google is the possibility of providing a way to do this for the webview too.

**Comment by part12studios** [comment]
XDK was sunset awhile back.  How is Crosswalk used today with Construct 3?   I only used XDK when doing crosswalk back in the C2 days.  

Could that be a possible compiling option for C3?  for those of us who hit that issue or need the most compatibility?  I seem to recall that crosswalk worked well for me (aside from the bloated size) so that’s a fair tradeoff.  

Sincerely,
Caleb Garner / 615-818-8483
Game Producer @part12studios

**Comment by AshleyScirra** [comment]
Crosswalk was retired over a year ago, and is now so old that going back to it will probably cause more problems than it solves. For example I think the Chromium engine it uses is now so old it lacks the WebM Opus decoder, so audio playback won't work. That's just off the top of my head.

**Comment by SebaSOFT** [comment]
That suxs but for C2 is almist mandatory. Still some people are still cretaing pull requests here in github crosswalk project

**Comment by part12studios** [comment]
Ah i didn’t know Crosswalk died..  wow.. XDK dead..  Crosswalk Dead..    oh well ok yea sounds like the blacklist is something we can circumvent.  

Sincerely,
Caleb Garner / 615-818-8483
Game Producer @part12studios

**Comment by AshleyScirra** [comment]
Google are interested to know any specific devices that show this behavior (fast in Chrome, slow in an APK). Can everyone who's affected by this report which specific device they have that it's happening on? All I have from this thread is "LG G Stylo".

**Comment by SebaSOFT** [comment]
Samsun J5, I can get you a lot more

**Comment by Kunnatam** [comment]
Samsung galaxy s7

**Comment by AshleyScirra** [comment]
Can you verify that if you add a string set to the expression `renderer` it does **not** say "webgl" on these devices?

If it does say "webgl" then I think that it would be a separate issue that we are already investigating, but for this one, we're specifically after devices that do not use webgl when in an APK.

**Comment by simoneddeland** [comment]
Samsung Galaxy S5 Neo

**Comment by Kunnatam** [comment]
Well I've checked on my affected devices list which is
- samsung s7 (renderer says webgl)
- sony xperia z3 (renderer says webgl)
- asus zenfone 2 (untested)
Seems like they are using webgl. Sorry for making confusion.

**Comment by AshleyScirra** [comment]
@simoneddeland - can you confirm that device does _not_ say it's using "webgl" using the `renderer` expression?

**Comment by angelo-lopez** [comment]
Samsung J5 and A5.

**Comment by angelo-lopez** [comment]
Sorry, it was Samsung J3 not J5.

**Comment by SebaSOFT** [comment]
Samsung J5, it says webgl

**Comment by AshleyScirra** [comment]
@angelo-lopez - can you confirm that the Samsung J3 and A5 devices both do _not_ say it's using "webgl" using the `renderer` expression?

**Comment by simoneddeland** [comment]
@AshleyScirra It says webgl

**Comment by angelo-lopez** [comment]
@AshleyScirra It says "webgl" on both the Samsung J3 and A5.

**Comment by bewa11** [comment]
Galaxy Tab 4 10.1 

Poor performance on apk but smooth on chrome.

It does say webgl

**Comment by AshleyScirra** [comment]
So... am I right that the only device so far that does _not_ say "webgl" in an APK is the LG G Stylo?

**Comment by MekaSkull** [comment]
LG Nexus 5X, says "webgl" on the test.
Stutters when playing "soaring", phone gets hot.
Tested on both Android 7.0 and 8.0 for the same result.

**Comment by angelo-lopez** [comment]
I have the same experience with @bewa11. Smooth on Chrome but poor performance with apk.

**Comment by part12studios** [comment]
I am at GDC now and do not have my device to verify. However I believe that is correct Regarding the LG phone

Thanks,
Caleb Garner
www.part12studios.com
615-818-8483
"If there are typos, it is Siri's falt"

**Comment by Agoraphobic** [comment]
shield tablet k1 says WebGL but only gets between 15-60fps. with chrome stable, chrome dev, or chrome canary set as the webview implementation.

**Comment by gameglaux** [comment]
Lenovo Tab 4 running Android 7.1.1: my apk gives me a choppy 37-42fps. Using remote preview in chrome it runs at a silky 59-60fps. Renderer reports webgl in both tests.

**Comment by AshleyScirra** [comment]
Just to be clear, we're looking for devices that _don't_ say "webgl" in an APK. At this point in the investigation we're not looking for any devices that do say they use webgl, only those that don't.

**Comment by SebaSOFT** [comment]
I think we should link a separate issue for the choppy webgl apk thing

**Comment by Agoraphobic** [comment]
If no one can find a device that doesn't say WebGL...maybe the whole gpu blacklist thing is only the problem for like 1% of the ppl. and whatever this is is the real problem that 99% of the ppl are assuming is gpu blacklist but really isn't.

I thought I was blacklisted until this test lol scirra forms are great don't get me wrong but as soon as you report stuttering your just told you must be blacklisted without much thought. 
all of us low-level guys really don't know much just that it stutters and that crosswalk fixed it... for some reason, we really don't understand lol

and yes a link to new thread about this issue would be nice

**Comment by AshleyScirra** [comment]
Historically, blacklisting _has_ been a big cause of mobile performance issues. Maybe things are changing, but that assumption is based on a lot of such cases in the past. Additionally things like poor v-sync quality can look like the same problem (or at least sound like the same problem when described), and even if they are something like v-sync quality, there's not much we can do about it in our engine, since that aspect is handled by the browser/OS/graphics driver stack. Also note in such cases reporting issues directly to Apple/Google/etc has always been an option so you can try to resolve issues entirely bypassing Scirra - it's mentioned briefly in the bug report guidelines.

Anyway, based on the only data we can find (which only goes by number of devices, not market usage), around 30% of Android 5.x devices could be affected by GPU blacklisting, which would be around 7-8% of all Android devices. Given we have a lot of users, and happy users don't report issues, it still seems possible that at least some of the reports are caused by this. (This can also give a distorted impression in the forum, where it seems like "everybody" is having issues, but really it's only a minority since the majority for whom it works OK aren't coming to the forum.) It's confusing though since the original report mentioned the LG G Stylo as being blacklisted, but Google say when they tried a device, it was not blacklisted.

Separately there's a v-sync issue in Android that may be resolved in Chrome 67. So I guess we need to wait until that gets to the stable channel. If these reports all then evaporate, we can probably assume we mis-attributed the cause. Otherwise there may still be blacklisting issues (or a third issue we haven't yet figured out either - entirely possible if there are multiple bugs that all look the same). Meanwhile if anyone can dig up a device that supports WebGL in Chrome but not in the webview (in an APK), that would allow Google to proceed with the next part of their investigation.

It's a frustrating issue but please be patient - we're a small company with a limited number of devices, and in general if we can't reproduce an issue we can't do anything about it. I've been hassling Google to get on the case too and they're looking in to it, but I think they're a bit mystified right now given nobody can find a blacklisted device so far.

**Comment by part12studios** [comment]
it’s a great idea to make a video of the game playing.  not in-device video.. just take a video with another device playing the game like i did here https://www.youtube.com/watch?v=pInkI--EnwY&t=4s <https://www.youtube.com/watch?v=pInkI--EnwY&t=4s>. though try to focus better than i did :).  but i wasn’t dealing with tearing / vsync issues but you can see mine is more about slower fps rendering.. not jaggies.. just something about it not completing each frame as fast as it should in one app vs another.  

Sincerely,
Caleb Garner / 615-818-8483
Game Producer @part12studios

**Comment by AshleyScirra** [comment]
Generally recording videos doesn't help - we either need to know something specific (e.g. does `renderer` say "webgl" in an APK), or test if something makes a difference (e.g. trying Chrome Canary as the webview implementation on Android 7+).

**Comment by bewa11** [comment]
I am using Galaxy tab 4 10.1 and running on Android 5.01 and I installed beta version of webview (version 67.0.3396.29) using these instructions: https://www.chromium.org/developers/androidwebview/android-webview-beta

Unfortunately the performance is not any better and is still horrible. Renderer does say ‘webgl’. 

Using the endless runner APK that you posted here: https://bugs.chromium.org/p/chromium/issues/detail?id=822727, The FPS is between 25 and 45. It does not get above 45 FPS.

**Comment by AshleyScirra** [comment]
Chrome 67 is now out and has a fix for smoothness in the Android Webview (which is what Construct games use in Android APKs). Has this resolved the issue, or can anyone still reproduce it? It would be useful to get feedback from everyone who's mentioned they were affected in this report, since it covers a wide range of devices which we don't have available to test ourselves.

On a HTC 10 running Android 8 the Chrome 67 noticably improved the smoothness for me, so it does seem like there's been a significant fix on the Chromium side.

**Comment by Kunnatam** [comment]
To confirm this is actually getting fixed for me!!(Samsung S7) I tried couples of my old projects which haven't been touched or changed and it is super smooth. I can clearly saw the improvement of fps and I saw none micro-stuttering or jaggering occurred at all.
However, one of my project is suddenly having a white screen issue and some texts are not showing but that is for different issue from this topic.

**Comment by part12studios** [comment]
I can try my original jumpy test game on my LG G Stylo.  How do I insure that my phone has Chrome 67?

Caleb

**Comment by AshleyScirra** [comment]
@Kunnatam - great to hear!

@part12studios - the most reliable way is probably to display a text object with the Browser.UserAgent expression. (It's quite long so make the text object large enough.) Somewhere in that will be the Chrome version in use for the APK, e.g. Chrome/67.0.3396.99

**Comment by angelo-lopez** [comment]
This is awesome news. I look forward to testing my game on my 2 Samsung devices (j3 and a5) where I experience extreme jank. Will be able test within a few days.

**Comment by gameglaux** [comment]
Lenovo Tab 4 running Android 7.1.1 - fully updated. 

No change. 

APK still runs a choppy looking 35-43fps. Buttery 60fps in the browser.

**Comment by part12studios** [comment]
How do I insure I have the latest chrome installed?    does it automatically update?   should i just reinstall?   I want to be sure i have the right version before I test it and report back on performance.

**Comment by shortercode** [comment]
@part12studios Chrome updates through the play store app, so if you've got automatic app updates enabled it should be up to date. If you visit the chrome page on the play store it will have an "update" button if there's a newer version available.

To check your version you can visit [what is my user agent](https://www.whatismybrowser.com/detect/what-is-my-user-agent) on your device it will give you the useragent for your browser, which includes the version.

For example mine is: 

> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) **Chrome/67.0.3396.99** Safari/537.36

so chrome 67

**Comment by AshleyScirra** [comment]
@part12studios - I already explained - the most reliable way is:

> @part12studios - the most reliable way is probably to display a text object with the Browser.UserAgent expression. (It's quite long so make the text object large enough.) Somewhere in that will be the Chrome version in use for the APK, e.g. Chrome/67.0.3396.99

@gameglaux can you use that approach to verify you are running Chrome 67? Additionally is it using WebGL? (put a text object showing the `renderer` expression to see)

**Comment by angelo-lopez** [comment]
Still janky on both Samsung J3 and A5.

**Comment by bewa11** [comment]
Performance is also still horrible on Galaxy Tab 4. It does not feel that the latest webview update improved performance it at all. It does use Webgl.

**Comment by AshleyScirra** [comment]
Given that:
1) this report is already very long and appears to mix up various issues
2) some devices appear to be fixed by the recent update, but not others, indicating separate issues
3) jank is likely caused by the browser or OS
I'm going to close this issue now. Please file any issues relating to jank directly with Google at crbug.com with a minimal repro and full details about the device, OS and Chrome version so Google can investigate.

**Comment by part12studios** [comment]
Thank you for looking into this.  It does seem like a splintering issue.  

Thanks,
Caleb
