### ISSUE TITLE
Documentation correction for SDK CreateDynamicTexture(width, height, opts)

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-3-bugs#4687]
## Problem description

Documentation for wrap modes for CreateDynamicTexture(width, height, opts) does not look correct. in opts, isTiled has no effect. The keys that have an effect are wrapX, wrapY (verified in source and usage.) wrapX, wrapY are not included in the documentation.

## More details

**Affected browsers/platforms:** 

**First affected release:**

**Comment by AshleyScirra** [comment]
This turned out to be a bit more complicated: the editor implemented the methods as documented, but had a bug that meant it misinterpreted the options parameter. The runtime used the newer `wrapX` and `wrapY` options. I think the easiest solution is to update the documentation to match the runtime (using wrapX and wrapY), and update the editor to also support these options (and fix the issue with interpreting the parameter) which is done for the next beta.
