### ISSUE TITLE
"Properties" window content not changing when selecting some objects

### ISSUE THREAD

**Issue by UncleHo74** [Scirra/Construct-3-bugs#475]
## Problem description

Some objects in my project won't show their properties in the corresponding window. I can add behaviours etc. in their context menu though.

See in my project the objects "ReferenceLOS" and "Doppelgaenger"

## Attach a .c3p

[TheLastSquad.zip](https://github.com/Scirra/Construct-3-bugs/files/1064216/TheLastSquad.zip)

## Steps to reproduce

1. Select within the project window an object where everything works normal, like "ScoreLabel"
2. Select "ReferenceLOS" or "Doppelgaenger" in the project window

## Observed result
Properties - window won't change content

## Expected result
Properties - window should change to corresponding object properties.

## Affected browsers
Chrome Version 59.0.3071.86

**Comment by shortercode** [comment]
Typically the properties window will only display information for an **instance** highlighted in the layoutview, and neither of those objects have an instance within the project. There's a few exceptions, like global objects, the project etc.

I believe this is because most of the information that you edit for these objects is actually part of the instance, so editing it without an instance doesn't actually mean anything. 

A common trick I've seen is to have an layout, that isn't actually used, to hold objects that don't need to exist at instantiation.

**Comment by UncleHo74** [comment]
@shortercode So sorry... couldn't believe that this is normal and NOT a bug... :( :( You're right it works as soon as there is an instance ... Slightly confusing though.

**Comment by shortercode** [comment]
Yeah it's an odd behaviour... there's some slightly awkward requirements to have at least one instance in
the C2 runtime. I think it's on the "nice to have" list for the new [runtime](https://www.scirra.com/blog/204/the-future-of-the-construct-3-runtime), but we haven't got an official timescale for the runtime yet.
