### ISSUE TITLE
The Z elevation feature is not working properly with layers

### ISSUE THREAD

**Issue by BonzerKitten** [Scirra/Construct-3-bugs#4751]
## Problem description

Hi! After the 3D shape update, the Z elevation feature stopped working properly with layers, so if an object has a low Z elevation value it can go through any layer and disappear behind it, this is not how it performs in the current stable release.

## Attach a .c3p

[Z Elevation Layers Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/6345643/Z.Elevation.Layers.Bug.zip)

## Steps to reproduce

1. Open both projects, one in the stable release and the other on the beta release.
2. Watch how the objects interact with the layer below them.

## Observed result

Object go through layers in the beta release.

## Expected result

Objects to not go through in the beta release, just like in the stable release.

## More details

**Affected browsers/platforms:** Chrome.

**First affected release:** R245 (Beta).

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is a necessary side-effect of 3D rendering. When you add a 3D shape plugin to your project, Construct must use a depth buffer to produce the correct rendering. Depth buffers mean that surfaces that are behind other surfaces in depth are obscured by the one on front, even if they are drawn afterwards. This means Z-elevating an instance below another instance will cause it to become obscured, even if it is in front of it in terms of layers or draw order. If we turn off the depth buffer, it will no longer render correctly relative to 3D shapes either.

Arguably the rendering with 3D shape is correct anyway: why should an object Z-elevated behind another one still be visible? Previously this was more or less a glitch that was only allowed because Construct used 2D rendering with a strict draw order. Now when you add in 3D rendering, it handles the depth properly, and Z elevating objects behind another one will obscure it.

This is the kind of compromise that is necessary for 3D rendering to work properly. It will be covered in the documentation for 3D shape and Z elevation when documented.

**Comment by BonzerKitten** [comment]
@AshleyScirra  The 3D shape feature is awesome and I can definitely see your point from a technical perspective, but I think I should at least try to show you why this can a bit of bottleneck for users trying to apply 3D shapes to their projects. I made this small demo of a top down city, like in old GTA games, but as you can see the buildings are constantly overlapping the HUD, making them really hard to see. Hopefully this will show you how annoying it can be to create something with this feature without compromising essential parts of a game, like the user interface.

Project (.c3p): [Depth Buffer Consequences.zip](https://github.com/Scirra/Construct-3-bugs/files/6350922/Depth.Buffer.Consequences.zip)

Preview: https://i.imgur.com/2CUQyG7.mp4

If there's isn't much you can do about it, that's okay, I just wanted to show you the issues I see from my personal experience.

Thanks for listening!

**Comment by skymen** [comment]
I think there should be a way for layers to be drawn separately from the depth buffered rendering, so they always appear under or on top of everything else.
That, or make every layer automatically adjust its Z elevation, size, rotation and whatnot to always be just in front of the camera at the nearest possible spot.

**Comment by AshleyScirra** [comment]
I see, yeah it makes sense. I think the best approach is a layer setting to turn off 3D rendering and switch back to 2D rendering, so for example the HUD can just render as an overlay to everything else ignoring depth. It should be straightforward, so I'll look in to doing that for the next release.

**Comment by skymen** [comment]
Nice!

**Comment by BonzerKitten** [comment]
@AshleyScirra Thanks a lot! I appreciate your attention and efforts. Hopefully your solution will be able to allow users to have content in front and behind 3D shapes. I already showed you an example for content in front of a 3D shape, like the HUD, now I'll try to show you an example for content behind a 3D shape.

I made a small scene where some spaceships are crossing the galaxy. The spaceships are 3D shapes and the galaxy is a scrolling tiled background, but as you can see, the spaceships are not visible behind the galaxy image, even tho it's on a lower layer.

Space Demo: https://i.imgur.com/A5di0iU.mp4

This can be considered an issue, because it wouldn't be possible to have a fixed image in the horizon, like in Star Fox from the SNES. Users would always need to fill the background with a solid color or a bunch of 3D shapes, which might not be desirable depending on the project aesthetics.

Star Fox: https://i.imgur.com/4Nd8ixE.png

**Comment by skymen** [comment]
My hope is you just implements an algorithm like this
From bottom up, layer by layer, start with 2D rendering:
Layer 0 is 2D, use base 2D renderer
Layer 1 is 3D stop 2D renderer, start 3D renderer, render layer
Layer 2 is 3D, keep using same renderer, render layer
Layer 3 is 2D, stop using 3D renderer, switch to 2D
etc, and basically make "render groups" that you'd stack on top of one another in the final render
Like, Layer 0 is in 2D group 1
Layer 1 and layer 2 are in 3D Group 1
Layer 3 is in 2D Group 2.

This would solve 
1: rendering UI separately on top of everything
2: render Background separately behind everything
3: using a 2D layer between two 3D layer would "force" a drawing separation between the two layers for when you need to be able to render 3D elements in the background without a risk of them clipping with elements of the scene
4: Allow for using 3D elements for UI as well
5: Allow for very cool and creative effects using quirks of the renderer
6: Potentially even make use of blend modes over layer groups because then the blend mode would check againt what's being drawn on the "current renderer" and this would actually be helpful in a LOT of ways. Aka, being able to draw things using blend modes on multiple layers over a single object acting as the "destination" for all objects on top of it in the same render group.
