### ISSUE TITLE
Rendering edge case

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-3-bugs#4755]
## Problem description

Hi, I was playing around with the 3D renderer and noticed a weird edge case

## Attach a .c3p

[renderingEdgeCase.zip](https://github.com/Scirra/Construct-3-bugs/files/6352015/renderingEdgeCase.zip)

## Steps to reproduce

1. Open layout or hit play
2. Move the camera around

## Observed result

Any sprite that is rendered BEFORE the 3D object renders correctly (as if it was back to front)
Any sprite that is rendered AFTER the 3D object is cut off by the frame buffer 
This means that a 3D object with opacity, or with semitransparent faces will still show where they cut off other objects, even though stuff under it should still render.
This also happens with Z elevated sprites

## Expected result

It should render correctly

## More details
However, I am 100% fine with this not being fixed, because it does allow for some very very cool effects, despite the limitations.

**Affected browsers/platforms:** 

**First affected release:** r244

## System details

n/a

**Comment by AshleyScirra** [comment]
Transparency basically doesn't work with depth buffers. It works when the draw order is back-to-front, but otherwise transparency will still obscure content behind it. This is a known limitation and I explained it further here: https://github.com/Scirra/Construct-3-bugs/issues/4734#issuecomment-819493836
