### ISSUE TITLE
Construct 3 editor freezes when using a probably bad While loop

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#476]
## Problem description

The editor freezes even though the preview is closed when using a most likely infinite while loop.

## Attach a .c3p

[WhileBug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1064757/WhileBug.c3p.zip)

![image](https://user-images.githubusercontent.com/7268697/26986491-71f22dec-4d50-11e7-9225-e08e5ccbaa7e.png)

## Steps to reproduce

1. open the project
2. run it
3. press any mouse button

## Observed result

Notice both the preview and the editor become unresponsive. The preview can be closed but it doesn't make the editor responsive again.

## Expected result

I'd expect for the editor to not become unresponsive. There is crash log.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r36

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 131 mb (1.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
CSS element() is not supported.
Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is because the browser runs both the editor and preview window in the same process and thread. It's tricky to resolve since there's no explicit way to tell the browser to use a separate process/thread for a different window.

We're planning on moving the preview to its own origin, which may help avoid this, since cross-origin popups are more likely to be moved in to their own process/thread.

**Comment by AshleyScirra** [comment]
We just released r42 today which moves preview to its own origin. Unfortunately this doesn't seem to have helped. It's also pretty much the most we can do to try and isolate preview from the editor.

It's up to Chrome to isolate a cross-origin popup to its own process, and they're currently doing a lot of architectural work to make this better, including allowing things like iframes to run in their own process. There's a Chrome bug that tracks all this work here: https://bugs.chromium.org/p/chromium/issues/detail?id=467770

I'm going to close this issue now as it's up to the browser to separate the browser windows. However even if that doesn't happen, we are experimenting with hosting the runtime in a worker for the C3 runtime, which would definitely fix this since it isolates all event code in to a separate JavaScript context that runs in parallel.

**Comment by AshleyScirra** [comment]
Actually in the end I filed a Chrome bug since I can't see any reason for it to work like this, even now: https://bugs.chromium.org/p/chromium/issues/detail?id=738046

**Comment by AshleyScirra** [comment]
FYI this should now be fixed with the C3 runtime using worker mode. You can test this as of r108 in Chrome 69+ (currently canary). Since the runtime is hosted off the main thread in a worker, even if it gets stuck in an infinite loop, you can still close the window (which terminates the worker) and the editor is not affected.
