### ISSUE TITLE
Issues in the reverse speed and acceleration of the "car" behavior.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4796]
## Problem description

As an example, set the car to max speed: 1000, acceleration: 100, deceleration: 100000 (as in the file provided).

Observe the car will take some time to move forward, but it will immediately reach its max speed if reversing.

This is not optimal because it implies that brakes and reverses are related, so, in case a player seriously improves the brakes of a car, then said car will for no reason be a reverse monster.

I understand it is easily circumvented by changing the max speed and acceleration of the car by recognizing inputs and then applying new values to them, but the name of the behavior is "car", and it currently does not behave like a car in this specific case, which is not that small. And also it is not optimal to have to do these things when the behavior could already provide the right functionalities out of the box, even if the behavior is not only for cars, but anything vehicle related.

In a perfect world, the fix would be having 2 max speeds, 1 for forward and 1 for reverse. Acceleration would only work for forward (precisely as it is right now) and deceleration would only work for reverse (not connected to braking). Lastly there should be a "breaking" number that is not related to acceleration nor deceleration.

I also understand how this can sound more like an "idea" then an issue, but aside from my opinions, the name of the behavior is "car" and this is not how a car, or possibly any vehicle really, behaves.

## Attach a .c3p

[car.zip](https://github.com/Scirra/Construct-3-bugs/files/6416558/car.zip)

## Steps to reproduce

above.

## Observed result

above.

## Expected result

above.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** 246

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by oosyrag** [comment]
Wouldn't say it's a bug... but it is decidedly unintuitive. Deceleration implies braking, which is also what the manual states, but braking would normally be understood as acceleration towards zero rather than negative infinity. The way it is now "Reverse Acceleration" would probably be a more appropriate description.

Adding a "Braking Speed" property and a "Brake" action would probably be a feature request.

I think having forward max speed and reverse max speed as separate properties is probably unnecessary, as max speed by itself is pretty clear. It is simple enough to set the max speed by comparing angle of motion to determine forward or reverse motion.

**Comment by dupuqub** [comment]
I can see why it's plausible to assume braking as a feature request, but my point overall is that reverse speed should not be connected to braking at all, therefore a braking speed and action would be the natural transition to fix how the behavior works.

Again, I agree, as I already mentioned, everything is doable in the current state of the behavior. My point here is to help the tool since it's meant to be used in vehicle mechanics, but it currently does not behave as such.

**Comment by AshleyScirra** [comment]
Obviously the car behavior is not a full realistic physics simulation of a car. It is a considerably simplified model. For example there is no concept of gears, and normally going in to reverse would involve a change of gears. It is currently by design that reversing applies reverse acceleration, i.e. deceleration, and reverse movement is allowed.
