### ISSUE TITLE
Disabling physics Collision action doesn't work with "On collision or Is Overlapping" conditions

### ISSUE THREAD

**Issue by justifun** [Scirra/Construct-3-bugs#4802]
## Problem description

Using the action  (Physics) "Disable collisions with object _____" doesn't occur if using the "On collision with other object" or "Is overlapping object" conditions

it DOES however work with On start of layout, or If comparing the Z elevations of the two objects together.

## Attach a .c3p

[
[Physics Collisions Issue.zip](https://github.com/Scirra/Construct-3-bugs/files/6429429/Physics.Collisions.Issue.zip)

](url)

## Steps to reproduce

1. Press Play
2. Purple ball should roll across the yellow bridge via physics, while colliding with the grey walls.
3. See the other disabled groups for other methods that do work

## Observed result

Purple ball gets stuck on the red walls below it

## Expected result

I provided 3 different groups in the event sheet to show that disabling the collisions on the red walls only works on layout start and using a z elevation comparison.  it does NOT work when using the On Collision with object or Is overlapping object conditions

## More details
The goal was to be able to have a physics object cross over other physics objects temporarily like crossing a bridge over another road below.  I was attempting to achieve this by disabling the collisions with the road below temporarily while the ball is on the bridge overhead.

**Affected browsers/platforms:**  Chrome/Edge

 R247

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 90.0.4430.93
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
C3 release: r247 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 1.1 tb
Storage usage (approx): 449 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3090 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6627)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This appears to be a limitation in Box2D. We use the `ShouldCollide` callback to implement filtering out disabled collisions. Their [documentation](https://box2d.org/documentation/classb2_contact_filter.html) states "for performance reasons this is only called when the AABBs begin to overlap". An AABB is an Axis Aligned Bounding Box, i.e. a rectangle that contains the entire object. In the image below I've drawn a selection box to show the approximate AABB for the top RedWall.
![box2d-collision-filter](https://user-images.githubusercontent.com/768723/117307945-ec60af80-ae78-11eb-82e9-5307c1b8318c.png)
As you can see the ball actually starts inside the AABB. Therefore Box2D will immediately decide if the ball should collide with the RedWall. If you have disabled collisions before then, it works; if you have disabled collisions after then (e.g. after waiting for the ball to fall and collide with the YellowBridge), it's too late to disable collisions, since Box2D already decided to allow it. You may notice it also works if you move the ball higher so it starts outside of the AABB.

We don't make Box2D - it's a standard physics library used in a wide range of game engines - and it's difficult for us to change, so I don't think this is feasible for us to do anything about. You may be able to work around it with another technique, e.g. using 'Set enabled' to completely disable the physics behavior on walls (which removes the physics body completely), or creating and destroying invisible physics objects to simulate the collisions being enabled and disabled, etc.

**Comment by justifun** [comment]
Thank you for the detailed reply and suggestions.
