### ISSUE TITLE
Noises  don't output consistent values.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4818]
Different noises output different scales of noises, the disparity is even more pronounced with a higher number of octaves.

Running the file will display clearly the gap between values from each noise.

## Attach a .c3p

[Noise_Debug.zip](https://github.com/Scirra/Construct-3-bugs/files/6455088/Noise_Debug.zip)

## Steps to reproduce

1. Run the file.

## Observed result

Voronoi will behave as expected outputting values from 0 to 1 while other noises output values from >0 to <1. It gets worse the more octaves you use, values will become even more distant from 0 and 1. Under these conditions you'd need to format the numbers, but even that is troublesome since each seed outputs minor differences on top of that.

## Expected result

Values reliably outputting from 0 to 1, otherwise it becomes pretty much useless in many cases.

## More details

**Affected browsers/platforms:**  Chrome

**First affected release:**  247

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by dupuqub** [comment]
Hi, this is mission critical for some of my projects, is there any news on this issue?

**Comment by AshleyScirra** [comment]
This issue shouldn't be blocking you on anything - if any of the returned ranges is wrong or otherwise not what you want, you can just do some extra calculations in expressions to scale it to what you want.

The maths behind these expressions is fairly complex so it can be difficult to tell what the correct result ranges are supposed to be. The range of the cellular (Worley) expressions does look like it's incorrectly in the range [0, 0.8], and I've updated that to be [0, 1] for the next beta. You can work around this yourself in prior releases just by multiplying the returned result by 1.25, since that undoes a multiply by 0.8 in the internal calculation, but that is no longer necessary as of the next beta.

As for classic/perlin noise, as best as I can tell, the calculations are correct, and the way the math works means that certain values are extremely unlikely, so in practice you get a range that is smaller than the [0-1] range. So I don't think that's actually a bug and no change is warranted. However as I mentioned before if this is not what you want, you can scale it yourself with some extra expressions. For example if you tend to get results in the [0.3, 0.7] range, you can double that by using `((n - 0.5) * 2) + 0.5`, and then you should get results in the [0.1, 0.9] range. You can change the multiplier there to get any range you want.

**Comment by AshleyScirra** [comment]
I believe we use standard calculations for perlin noise, and the range is a standard feature of the algorithm.
