### ISSUE TITLE
Changing variable name casing does not update references.

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-3-bugs#4819]
## Problem description

If you change a variable name without changing the actual characters, but only changing casing, references will not update.

## Attach a .c3p

[case.zip](https://github.com/Scirra/Construct-3-bugs/files/6459487/case.zip)

## Steps to reproduce

1. Create a variable.
2. Change some casing in any character.
3. Observe that references will not change.

## Observed result

references not changing.

## Expected result

references changing.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** 247

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. All names update everywhere, such as in 'Set variable' actions, but not in expressions where you've typed your own expression. The intent behind this is to preserve the user's own typing where possible. For example if you have a variable named `Myvar`, and you type in an expression all lowercase like `myvar + 1`, then rename `Myvar` to `MyVar`, it leaves the expression as you typed it, rather than changing it to `MyVar + 1`. The case makes no difference to whether the expression is valid, so it can be left as-is. Obviously renaming to a completely different name requires that the expression be updated, and so Construct does that and uses the case matching the new name, because the case of the previously typed expression is no longer applicable so there's nothing to preserve.

This is how it's worked since Construct 2, and I can imagine some users would prefer it works this way rather than rewriting their expressions from their preferred case. So I don't think a change is warranted based on a single issue report.

**Comment by dupuqub** [comment]
I completely disagree with your assessment of whether this is necessary or not.

In the case you somehow find yourself rearranging your code and you need to change variable names casing for clarity, then you have to rewrite to a different name and then to the original with the different casing.

It's not huge, but my point is that I don't believe this is the best possible design.
