### ISSUE TITLE
Editing a function parameter removes all of the user formatting from expressions in the expression editor

### ISSUE THREAD

**Issue by eleanorjmorel** [Scirra/Construct-3-bugs#4827]
## Problem description
Adding or removing a function parameter from a function with a return value removes all of the user formatting from expressions in the expression editor if it contained that function and automatically formats all of the text.

## Attach a .c3p
https://drive.google.com/file/d/1KNrvgRy1Exs2oQ77LE6zKRaIes64_NcF/view?usp=sharing

## Steps to reproduce
1. add a new function parameter to the functions reverseX or reverseY

## Observed result
The expressions for set X and set Y go from this readable text:
![image](https://user-images.githubusercontent.com/32940085/118410876-ae753f80-b65f-11eb-946b-1c74a754bc91.png)

to this unreadable expression
![image](https://user-images.githubusercontent.com/32940085/118410886-c1880f80-b65f-11eb-9b48-1a943f3a92df.png)
Undoing does not fix the expression formatting, it's gone forever

## Expected result
For the new function parameter to be added in the expression editor, just like when you change the name of a function, without affecting  all expressions that contain the function

## More details

has always happened with the new functions

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by eleanorjmorel** [comment]
quick screenshot of an event that would be a nightmare to re-format 
![image](https://user-images.githubusercontent.com/32940085/118382329-445a8d00-b5c2-11eb-8d43-f05999c37243.png)

**Comment by AshleyScirra** [comment]
The problem is when changing parameters, Construct must modify the tree of expression nodes to keep it valid. Once it has done that, it must regenerate the expression text from the expression nodes, but the expression nodes don't have any syntax information (it's an abstract syntax tree, aka AST). So it reverts to a default formatting mode.

It's difficult to remedy this, and besides, expressions aren't designed to be used like you're using them there. The intent of the event block system in Construct is to use conditions and actions, not trees of complex expressions using conditionals. So I don't think it's worth making further changes to better support this.

**Comment by eleanorjmorel** [comment]
Okay thank you for looking into it!


I just want to add, since it'S related, using events like this is very effective in combination with conditions, very cool "**pick by evaluate**" conditions can be created!

They allow very complicated "or blocks" to be done in a breeze!

You can also "early exit" those complex expressions by using a ternary operator and return 0 or 1 on one of the early branches for an object to be picked or not picked !


It'S really cool that your engine supports all of this, and so well !
Is there a reason why it's not documented or used in any project examples ?
That makes it really difficult for users to adopt  that way to use the event
