### ISSUE TITLE
"Crop Transparent Edges" feature in Graphics editor did not work for this PNG unless the pixels were copied into a new frame.

### ISSUE THREAD

**Issue by whistlegraph** [Scirra/Construct-3-bugs#4842]
This is probably a subtle bug, with other effects. Here is the sample image: 
![round_face](https://user-images.githubusercontent.com/3620017/119072728-d7b80780-b9a0-11eb-9d47-a988b302a012.png)

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.

Keep in mind that the default behaviour of the crop tool also adds a padding of 1 pixel on all sides, to help with texture bleeding at runtime. Normally this isn't noticeable in larger images, but because the example image you provided is so small, it can be clearly seen.

If you wish to crop without margin, you need to be pressing **Ctrl** when using the tool.

**Comment by whistlegraph** [comment]
Thanks! Yes I love that default behavior and often use the shortcut too!
