### ISSUE TITLE
Tween resume bug

### ISSUE THREAD

**Issue by jorbart** [Scirra/Construct-3-bugs#4851]
## Problem description

"Tween2" won't resume if we want it to do so at the event 'On "Tween1" finished', if "Tween2" and "Tween1" are of the same type.

## Attach a .c3p

[TweenResumeBug.zip](https://github.com/Scirra/Construct-3-bugs/files/6543168/TweenResumeBug.zip)

## Steps to reproduce

1. Click the green rectangle
2. Wait 1 sec till the horizontal tween ends

## Observed result

The rectangle starts to move right when you click it (horizontal tween is fired). When the move right tween finishes, the rectangle starts to move down.

## Expected result

When the move right tween finishes, the rectangle should start to move both down and left.

## More details

There's also another rectangle (purple one) included to this attached project file with tweens for width and height. It is there to show that this bug doesn't relate to only one property.

**Affected browsers/platforms:** 
Chrome/Opera/Firefox on Windows
Chrome/Opera on Android

**First affected release:** 
r241

## System details

<details><summary>View details</summary>
Platform information
Browser: Chrome
Browser version: 90.0.4430.212
Browser engine: Chromium
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 7
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.9375
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
C3 release: r241 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 57 gb
Storage usage (approx): 98 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0, D3D11-20.19.15.4352)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
This isn't a bug, it is working as expected. Only one tween for any given property is allowed to exist.

What is happening in your example is that after pausing a tween, when you create a new one that will affect the same property as one of the paused ones, the existing paused tween is removed in favour of the new one.

The main reason for the feature to work this way is that tweens are absolute, so having multiple ones affecting the same properties would produce strange results.

Going to your example again, if a paused tween was not removed and resumed playback, it would change the position of the instance towards the position it was initially configured to, rather than going towards a position relative to it's current location.

Any any case, if you want to chain tweens, I suggest creating the tweens when they are needed  rather than trying to keep them paused and resuming them.

If you still need to have multiple tweens affecting the same properties at the same time, you should look into the **Value Tween**. It is a special kind of tween which is not related to any particular property, and you can have as many of them working at the same time as you need. 

You can then get the current value of the tween using the **Tween.Value** expression and assign it where ever you need it.
