### ISSUE TITLE
Text with center vertical alignment - fine tune

### ISSUE THREAD

**Issue by Dramamini** [Scirra/Construct-3-bugs#4852]
## Problem description

Ashley did a great work in the past few weeks and now vertical alignment is exactly the same when enabling bbcode, also text remains in position if you increase text object's height, so two main issues are solved.

But there is a final step to be done in order to have a pixel perfect center vertical alignment: 

Now Construct takes into account the total distance of the upper and the lower point of letters. For example in the phrase "1000 Xp" takes into account the upper point of "1", "0", "X" and the lower point of "p". This leads to a wrong measurement and puts the whole text about 2 pixels up from the right position.

I believe that only the height of capital letters or numbers should be calculated in order to have a true center vertical alignment.
Only 5 letters (g j p q y) have a "tail" below them so it's such a pity to sacrifice a perfect alignment fore those letters.

## Attach a .c3p

[TextAlignmentFineTune.zip](https://github.com/Scirra/Construct-3-bugs/files/6535576/TextAlignmentFineTune.zip)

## Steps to reproduce

Let's say we want to make a notification circle as a background for a number of unread messages.

1. Draw a circle
2. Put a text object in the middle of the circle

## Observed result

You see that text is slightly up (2 pixels) above center point

## Expected result

Text should be perfect aligned in center.

## More details

![TextAlignmentFineTune](https://user-images.githubusercontent.com/53188782/119424612-78465880-bd0e-11eb-80e3-2525b049836b.jpg)

Chrome/Firefox/Safari, Windows/macOS/Android

**First affected release:** r245

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 90.0.4430.212
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
C3 release: r248 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 269 gb
Storage usage (approx): 1 gb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce G105M Direct3D11 vs_4_1 ps_4_1, D3D11-9.18.13.4195)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Urgh, this text alignment stuff is really complicated and never seems to end.

If we change how vertical alignment works when BBcode is disabled, it will be a breaking change for all old projects not using BBcode (i.e. all old Construct 2 content). If we limit the change it when BBcode is enabled, then vertical alignment is no longer consistent when using BBcode enabled/disabled.

The current vertical alignment now also matches what we've been using since Construct 2 was introduced in 2011, and AFAIK this is the first time anyone's asked for it to be different to that original approach. On the other hand, I checked how browsers calculate vertical text alignment in HTML and it seems to match the request here, i.e. it positions the text based on the top-to-alphabetic baseline height, rather than the top-to-bottom baseline height.

I think there are some uses for the current approach anyway. In your project if you look at the '8' in the red circle, move it down 2px to simulate the alternate vertical alignment, and then change the text to a lowercase 'g', it looks positioned too far down. If you move it 2px back up again it actually looks better. So I can imagine that even if we made this change, someone else might file a bug that says "lowercase letters don't vertically center like they used to, please put it back to how it used to work".

Given this is a compatibility minefield, the current approach seems to have been generally acceptable for several years, and it's not clear that the downside of potential breakage is outweighed by the benefit of the change, I think it would be best to track this as a suggestion here: https://construct3.ideas.aha.io/
If it gets lots of votes that would suggest it's worth dealing with the compatibility fall-out and breaking changes - but if not then I think we can just leave it as is.

**Comment by Dramamini** [comment]
![Text TextInput](https://user-images.githubusercontent.com/53188782/119750599-5c73bb80-bea2-11eb-83d5-44a88dc433ae.jpg)

This screenshot is another example of what I mean. On the left is a text with center alignment and on the right is construct's text input field where center alignment is perfect in my opinion.

Anyway, maybe a solution would be if in text options could be added a padding option, an input field where user could define a number of pixels and make text adjustments. How can we adjust line height.. something like that. Maybe this could solve every other problem (not only with center but also with top or bottom alignment, bbc, different fonts etc) a c3 user might face trying to align text.

I'll post a suggestion on construct3.ideas

Thanks @AshleyScirra , keep up the good work!

**Comment by skymen** [comment]
The solution I found in C2 was to replace the text renderer with my own that gives me finer control over alignment (as a 0-100 percentage rather than 3 values) https://www.construct.net/en/forum/construct-2/addons-29/plugin-text-alignement-127462

And, I have a piece of code that detects what browser the game is running on and replaces the alignment with the correct value. 

Another way is to never ever center text at all when possible, and just place stuff manually with as little wiggle room as possible. Browsers seem to all render top left text correctly from what I can tell.

Anyway, it would be cool to have an additional 0-100 alignment option for C3 as well instead of the 3 values.
