### ISSUE TITLE
issue on removing child object from project

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-3-bugs#4873]
## Problem description
there is a hierarchy in layout with name "parent" and "child". If I just delete "child" object from the project then "parent" still showing hierarchy property in the property bar. This causes an issue. If I do copy of "parent" object in layout and create a new "child" object and add it as child of the second "parent" object and in the event action I do "create object" with "create hierarchy" =  True then it doesn't create "child" object at runtime. Because by default c3 picks only first created "hierarchy" out of 2 hierarchies of the same object. and because first "parent" object doesn't have any child to create but construct still treat it as a "parent" object So no object is creating on the runtime.

## Attach a .c3p
[hierarchy issue.zip](https://github.com/Scirra/Construct-3-bugs/files/6596930/hierarchy.issue.zip)

## Steps to reproduce

1. open project file
2. preview it

If you want to reproduce this bug yourself then
1. create 2 sprite objects "objA" & "objB".
2. set "objA" as parent of the "objB".
3. delete "objB" from the project.
4. create new sprite object "objC".
5. copy "objA" in the layout and set it to parent of the "objC".
6. in eventsheet, On start of the layout destroy "objA" and create object "objA" with "create hierarchy" set to True.
7. Preview it.

## Observed result

Child object didn't created in the runtime.

## Expected result
it should create child object in the runtime.  Also there should a way to choose which hierarchy to be created out of multiple hierarchies of the same object. for example in the "hierarchy property" in properties bar there should a TAG option on parent object by which we can create specific hierarchy out of multiple hierarchies of the same object.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. When you create an object at runtime, Construct picks an arbitrary instance in the project as the template, and uses that for all the default object properties. Object properties include everything from the size and angle to instance variables and effect parameters, and hierarchies are also a part of the initial object properties and are handled the same. The design assumes that you either have everything the same, in which case it doesn't matter which is picked, or you can change the properties you want to specify with actions after creating the instance.

**Comment by luckyrawatlucky** [comment]
This is by design. So it means When I have 2 instance of the same object "objA" then I always have to set "objB" as a child to first instance of "objA" otherwise runtime will never accept it.
