### ISSUE TITLE
bug in example?

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#4881]
In the "Disintegration Effect" example project, the code for the effect says this:

![image](https://user-images.githubusercontent.com/5744908/121301279-49012f80-c93b-11eb-965e-00a40caa7f44.png)

There are two actions that both use the "Rotate" tag.

It seems like that tag should say "Size" instead?

**Comment by BonzerKitten** [comment]
Hi @alastajj! Thank you for taking the time to write a bug report about this issue, however I'm not entirely sure if it could be considered a real bug, since the "Rotate" tag is not being used to trigger any other action once it's finished, so it doesn't interfere with any functionality in the project. However, just to keep things as organized as possible, I renamed the second "Rotate "tag to "Resize", so it better matches its action purpose. I sent the updated project to Ashley, so he should be able to replace the old file sometime during the next beta release/cycle.

**Comment by AshleyScirra** [comment]
Project file updated for next beta.
