### ISSUE TITLE
Resizing the Inspector while paused turns the game screen black

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#4924]
## Problem description

I am tracking a bug and paused the game when it happened. I resized the inspector to see more data, but the game screen turned black.
I can't see the bug now, and if I clicked resume, the game will move on and I will have to restart and reproduce it again.

## Attach a .c3p

(New project)

## Steps to reproduce

1. Create a new project.
2. Debug the layout.
3. Click Pause in the inspector.
4. Resize the inspector window (using the horizontal bar between the game and the inspector)

## Observed result

Game screen is black (but clicking an instance in the inspector still shows the red rectangle around where it is supposed to be)

## Expected result

Game screen remains visible

## More details

**Affected browsers/platforms:** Firefox 89.0.2

**First affected release:**

**Comment by skymen** [comment]
That is because the game's rendering is halted. The old behavior was that the image would be stretched. As far as I know, there is no easy way to make the game rerender without causing a new tick (which would defeat the purpose of having the game paused)
Instead, what you can do is either resize the inspector window before you try to reproduce the bug, have the inspector window as a separate window entirely, or hit the "next frame" that will rerender the screen, and keep the game paused after a single frame has passed. Depending on your bug, one of these solutions might work.

**Comment by AshleyScirra** [comment]
Yeah, the runtime is not ticking so the canvas was not being redrawn. However we do have a mechanism for redrawing only, which is already used when stepping through breakpoints to reflect any changes. I applied this for window resizes while the debugger is paused so it should be working like you expect in the next beta.
