### ISSUE TITLE
Layer scale down scales all layers

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#4934]
## Problem description

When you scale a layer to less than  1 it scales all the other layers.
## Attach a .c3p

https://www.dropbox.com/s/ywtpolxdjwnsdm3/layerscalesneg.c3p?dl=1
## Steps to reproduce

1.Run the project
2.Click the sprite to scale layer 1 to 0.9
3.See the layers scaled

## Observed result

All layers are scaled
## Expected result
The referenced layer should be the only layer scaled.

## More details

It does not happen when the scale is above 1

**Affected browsers/platforms:** 
w10 Chrome

**First affected release:** 
Stable
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Layer 0 is not actually scaling. The scroll position is being offset, because bounded scrolling is enabled for the layout, and one layer is being zoomed out, which increases the viewport size and therefore reduces the scroll bounds. Tick 'unbounded scrolling' on the layout and you can see it works as expected.
