### ISSUE TITLE
Editor bars won't persist

### ISSUE THREAD

**Issue by stalin-joseph** [Scirra/Construct-3-bugs#4952]
## Problem description

Opened editor bars and their size will not persist unlike other settings.

## Steps to reproduce

1. Change selected theme in settings
2. Restart Construct

## Observed result

All editor bars will reset to default, while other Construct settings remain the same.

## Expected result

Editor preferences such as opened bars and their size persist.

**Comment by AshleyScirra** [comment]
It's by design that when you change the theme, the UI layout resets. This is because themes can size things differently, and so there's no guarantee your previous UI layout is actually valid with the new theme. Resetting the layout avoids this problem.

The UI layout is preserved between reloads providing you don't change the theme. This should not be a significant problem since I imagine most people choose a theme and then stick with that long term.
