### ISSUE TITLE
Admob is not working :'(

### ISSUE THREAD

**Issue by Leomcs1982** [Scirra/Construct-3-bugs#4955]
## Problem description

Mobile ads are not working on version R256.
In test mode it works fine, but with real ID it doesn't work.

Another point is that the "fail" condition is behaving like a canceled rewarded ad.

I want to emphasize that the pandemic is still going strong in my country and advertisements are my only way of survival and these failures will prevent me from reaching the minimum value of Admob. I am desperate.

## Attach a .c3p
https://app.box.com/s/k28t95upe3jfvp1tfaskohwy3wynr1t5

## Steps to reproduce

- Export to APK using a real Admob id
- Test mobile ads

## Observed result

No ad

## Expected result

Ads being displayed

## More details
Construct 3 version: R254, R255 and R256
Browser: Chrome, Firefox and Edge
OS: W10

**Comment by DiegoScirra** [comment]
It is impossible to tell what the problem is with this information.

There were a few issues in r254 and r255. Those have been fixed and by r256 there are already people saying that it works for them.

I got it working with the test application I used for development, which uses a real Admob Application ID and real Ad unit IDs.

The only thing I can think of is that there is something misconfigured with the Ad units themselves or maybe your Admob application status is not in a  **Ready** state yet.

You can see more about application ready state here [](https://support.google.com/admob/answer/10564477)

Asides from that, there isn't much else to do.
