### ISSUE TITLE
Performance degradation. c3p file corruption. r257

### ISSUE THREAD

**Issue by ykanske** [Scirra/Construct-3-bugs#4991]
During the development of the project, for unknown reasons, performance dropped sharply in one of the versions.
I periodically checked the result of the work, using a remote preview on my phone and everything worked fine, but in one of the later versions I suddenly noticed a drop in fps. I tried to optimize my project for a long time, tried many ways, but they did not give results, no matter how much I tried to simplify my project, I always got poor performance.
Since I was doing a backup of versions, I opened the later one and found that all subsequent versions inherited this problem.
I made two **almost identical versions** of my project, you can see the difference in performance on remote viewing or compiling the APK.

[c3p_corruption.zip](https://github.com/Scirra/Construct-3-bugs/files/6902933/c3p_corruption.zip)

1. Open RNDA_0.0.7.2T.c3p in Construct 3 r257
2. Send Remote preview
3. Look at dynamic fps meter on top of the screen, 
4. Fps meter shows values in the range from 61 to 54 fps when you open the lists and click on the checkboxes.

5. Open RSWP_0.1.2.c3p in Construct 3 r257
6. Send Remote preview
7. Look at dynamic fps meter on top of the screen
8. Even without the fps meter, there are noticeable slowdowns in the animation of the list and checkboxes. FPS indicators vary between 58-43. Sometimes they can fall below 30 fps.

9. You can make sure that the contents of the files are almost the same. I copied the code from the version

When viewed on a PC, the problem is not visible.
I also want to say that all subsequent saves of a file with poor performance give the same bad fps and cannot be repaired or optimized.
A file with good performance saves a good result in the preview.

**Affected browsers/platforms:** 
Chrome
Android 10

**First affected release:** 
Construct 3 r257

## System details
HUAWEI HONOR 9X

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid this does not appear to amount to evidence of a problem with Construct.

If project A and project B have different performance in the same version of Construct, this would indicate there is a difference between the projects that causes a performance difference.

If project A has different performance across two different versions of Construct, that would be evidence of a possible performance issue in Construct, but that is not what is stated here in the steps to follow.

So it seems reasonable to conclude that until proven otherwise the projects are different in some way and the performance measurements are measuring that difference. Even if you thought the projects were exactly identical, it's probably just an oversight or some small mistake that makes for a significant difference, which is very common in bug reports (hence the guidelines, which aim to filter out these kinds of mistaken reports). See the [Performance tips](https://www.construct.net/en/make-games/manuals/construct-3/tips-and-guides/performance-tips) manual section for advice on performance and how to make measurements and investigate performance issues.
