### ISSUE TITLE
APK Build Error

### ISSUE THREAD

**Issue by Leomcs1982** [Scirra/Construct-3-bugs#5009]
## Problem description

For 2 days I tried to build an APK file, but the APK file doesn't work. I can't install on my Android device and Google Play Console won't accept the file.

On each export, the built APK file has a different size, sometimes 2mb, sometimes 37mb, my project is 35mb.

No APK file works, neither the release version nor the debug version.

In the past I've had this problem, but after many attempts I successfully built an APK, this time I've been trying for a long time and it doesn't work.

In this screenshot, you can see how the same project has built many APK files with different sizes that don't work:
https://app.box.com/s/ed1ljjficggot972db7iy2du270snppy

## Attach a .c3p

https://app.box.com/s/ogfwefhd7jhruc5v6m911u49ogc5ra1b

## Steps to reproduce

1. Export project to APK (debug or release)
2. Check if the APK file size is compatible with the project
3. Try installing the app
4. Repeat the process and check if the second APK file is the same size as the first

## Observed result

Every build results in a file with a different size and no build creates a working file

## Expected result

APK file that works on an Android device and can be published to Google Play Console

## More details
This project was tested on Chrome and Edge with the same result. On Firefox the build is never completed, I waited 12 hours and the build didn't finish.

**Affected browsers/platforms:** 

W10, Chrome, Edge and Firefox

**First affected release:** 

R258 / R259

## System details
Platform information
Browser: Chrome
Browser version: 92.0.4515.131
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
C3 release: r259 (beta)
Language setting: pt-BR

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 3,8 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon HD 5450 Direct3D11 vs_5_0 ps_5_0, D3D11-8.17.10.1433)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
The first thing that happens on export is it shows this warning:

> Using upper-case characters in an app ID may prevent the app from installing on some Android devices. Consider changing the app ID to only lower-case characters.

If you ignore that warning and the app doesn't install, the problem is that you ignored the warning.

I fixed that in the project and then did two consecutive debug APK builds. Both came out the same size (34957 KB) and the first one installed just fine on my Pixel 3. So as far as I can tell it's working fine.

Perhaps your Internet connection is unreliable and the transfer is being cut off half way through or something. Try checking your connection. If you have an unreliable connection, it might be more reliable for you to export Cordova projects and do manual builds offline with the Cordova CLI.

**Comment by AshleyScirra** [comment]
I tried it myself and it worked fine. Unfortunately as our bug report guidelines describe, it's very difficult to help unless we can reproduce the issue ourselves; if we can't it's usually evidence that the problem is not in Construct or our services and that it's probably something specific to your system or setup. If the build server itself really was broken, my builds would have been broken too; but they worked fine, so presumably the build service is actually working fine, and the problem is somewhere else. Without further evidence it seems to be the only good explanation, and without knowing exactly what is different about your local setup or how the local issue happens - i.e. the real steps to reproduce - it's impossible for us to act on it.
