### ISSUE TITLE
tilemap bug if tilemap had polygon on r260,it can open on r251.2

### ISSUE THREAD

**Issue by wertt22** [Scirra/Construct-3-bugs#5044]
**Problem description**
i can,t open on r260 unless i delete the polygon for tile
https://construct-static.com/images/v931/r/uploads/articleuploadobject/0/images/64126/file_v1200.png
**Attach a .c3p**

[testfaild.zip](https://github.com/Scirra/Construct-3-bugs/files/7118206/testfaild.zip)

**Comment by AshleyScirra** [comment]
The problem appears to be there is a Tilemap object with an instance variable named "tilewidth", which is invalid for a Tilemap as it has an expression with that name. This ought to be impossible to set up as the editor will stop you - e.g. if you open a new project, add a tilemap, and try to add a variable with that name, it will show an error and stop you.

Without more information it's difficult to tell what really happened, but my best guess is since these are new expressions, existing projects using instance variables with the new expression names can't be opened in the latest release. You should be able to work around this by opening the project in the previous release, renaming the instance variable, saving, and then opening in the latest release.

**Comment by wertt22** [comment]
ok solved thanks
