### ISSUE TITLE
DrawingCanvas inserts Shadowlight with a delay when rotating, artifacts appear.

### ISSUE THREAD

**Issue by ibiz3091** [Scirra/Construct-3-bugs#5045]
## Problem description
Last normal operation in r250

## Steps to reproduce

I have created 2 projects in r261 and r250. Just open the projects and move the mouse with the button pressed to the left and right. In r261 it can be seen that the canvas resumes with a delay when rotating
In r250, drawing occurs more smoothly, so that the edges of the red rectangles practically do not come out during rotation.
r261 https://drive.google.com/file/d/1wZwy3rHtX4WHvCK8L4bPI_S4njbrf2fT/view?usp=sharing
r250 https://drive.google.com/file/d/1f9nTEdxgBGTefSQWDe8lYN4HnVNKhrLJ/view?usp=sharing
## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I think this is an unfortunate side effect of other recent bug fixes for DrawingCanvas.

I think the project actually relied on a bug. The drawing is actually done at the end of the frame, after the time the "Paste object" action is used. Previously if you changed anything after the paste action, it would actually paste with the change, which is unexpected behavior. The fix was to save the state at the time of the paste action, then when it comes to really draw it, it restores the state of everything at the time of the paste action, does the paste, then restores everything to what it was before.

The problem with ShadowLight specifically is its drawing depends on the position of the ShadowCaster objects. The "paste" action's save and restore does not include ShadowCaster objects, because it does not know that they affect the drawing of ShadowLight. So previously it would (incorrectly) draw with everything up-to-date rather than with the state used at the time of the "paste" action, but now it draws the pasted content with the correct state at the time of the "paste" action, but ShadowCaster objects are not included so are one tick behind.

I can't think of a good solution to this problem and we can't reverse the change as it will reintroduce the original problems again. It seems pretty niche as it appears to only affect ShadowLight when using dynamic positioning. I think your best bet is to adapt your project to work around it.
