### ISSUE TITLE
Everything in the Layout Disappears after leaving chrome tab for around 5 to 10 minutes

### ISSUE THREAD

**Issue by RecraftedS** [Scirra/Construct-3-bugs#5059]
## Problem description

Layout disappears randomly after leaving the google chrome tab for a few minutes and it can only be fixed by closing out the tab or refreshing buts it annoying cause then you gotta stop what you're doing to save the project and then refresh just so you can see what your doing

## Attach a .c3p

no need for one since this is a universal issue (I checked on another project of mine and I can't see anything in the layout either)

## Steps to reproduce

1. open your project
2. then after it's done loading open a layout
3. switch to another chrome tab and wait like 5 or 10 minutes (It can very cause I didn't keep track of the time)
4. then switch back to the construct 3 tab and everything in the layout should be invisible for some reason...
## Observed result

everything in my layout disappeared

## Expected result

everything in my layout not to be disappeared

## More details

I only have/use Chrome so I'm not sure this will happen with other web browsers but it is likely 

**First affected release:** I'm pretty sure It was the new r260 update
## System details

WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
layoutView.js:134 WebGL context lost

<details><summary>View details</summary>

WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
layoutView.js:134 WebGL context lost

</details>
![icon](https://user-images.githubusercontent.com/77114634/133339728-9454d365-ab7d-4357-ad3e-113472832ca4.png)

**Comment by AshleyScirra** [comment]
I leave tabs with Construct in the background regularly as I work through the day, and I don't recall ever seeing this. This suggests the steps to reproduce don't work for me. Further, "context lost" usually means the GPU driver crashed or some other system-level issue caused the WebGL renderer for the Layout View to stop working. Since this would be a system-specific issue, it would also explain why I'd never see it, as it's only affecting your device.

I'm afraid there's little that can be done about this - try checking for an update for your graphics driver.
