### ISSUE TITLE
Text set Z height low fps

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#5060]
## Problem description

Text object causes low fps when setting z height on multiple objects
## Attach a .c3p

https://www.dropbox.com/s/b2zt2sgs0vd17bq/textzheight.c3p?dl=1
## Steps to reproduce

1.Run the project
2.Take a look at the fps when the text objects are not changing their z height
3.Touch anywhere to start changing the text z heights

## Observed result

The fps drops dramatically then raise a little after a while
## Expected result
The fps should stay at 60 

## More details

Tested in last stable, same this is happening there

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Increasing the Z elevation increases the size of the text, which increases the text resolution, which then means re-rendering the text in order to improve the display resolution and avoid the text becoming blurry.

Similarly to constantly-changing text, re-rendering text is slow. Unfortunately I don't think there's anything that can really be done about that.

**Comment by pigmalien** [comment]
I was afraid of that. Thanks anyways.
