### ISSUE TITLE
3D shapes behind a billboard are not rendered.

### ISSUE THREAD

**Issue by BonzerKitten** [Scirra/Construct-3-bugs#5074]
## Problem description

3D shapes behind a billboard are not rendered, like if the billboard is acting as a transparency mask or something similar.

## Attach a .c3p

[3D Render Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/7198323/3D.Render.Bug.zip)

## Steps to reproduce

There are no steps to follow, the bug can be reproduced by simply running the project.

## Observed result

3D shapes behind a billboard are not rendered.

## Expected result

3D shapes behind a billboard to be rendered.

## More details

**Affected browsers/platforms:** Chrome, Windows

**First affected release:** r263

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's not actually a bug - transparency in 3D is more complicated due to the depth buffer. Transparent areas still fill in the depth buffer and block rendering behind them. It's the same issue covered in the tutorial [Using 3D in Construct](https://www.construct.net/en/tutorials/using-3d-construct-2746) (see section on transparency).

The solution is to make sure the billboard is drawn last. See the FPS shooter example for one technique for handling this: all the opaque scenery is on one layer, and all billboards are on a layer on top with the "camera distance" draw order, ensuring the billboards themselves are drawn from furthest to nearest.
