### ISSUE TITLE
Object with bullet behaviour does not inherit Turret angle of motion unless Bullet.SetAngle property is selected

### ISSUE THREAD

**Issue by calminthenight** [Scirra/Construct-3-bugs#5096]
**Problem description**

When using the Turret behaviour, spawned objects with the bullet behaviour do not inherit the angle of motion from the Turret Object's angle unless the Bullet property 'Set Angle' is selected.

This does not make sense, based on the description of the Bullet Set Angle property "Automatically set the object's angle to the angle of motion".

This limits the usefulness of the turret behaviour for Pixel Perfect games where sprite rotation is undesirable. The angle of motion should still be inherited regardless of if the spawned object has the 'Set Angle' property enabled, as the turret should be able to fire non rotating bullets at the correct angle.

While easily worked around it would be one less action needed when spawning bullets. If the decision is made to leave it as is, the Bullet and Turret documentation should be updated to include a description of the interaction.

**Attach a .c3p**
https://1drv.ms/u/s!AkmrWgxeuxlKhIkE8R8JjF-2GWeQOQ?e=LCoPGO

**Steps to reproduce**

Toggle 'Sprite2' Bullet Set angle property

**Expected result**

Bullet object should continue to inherit their angle of motion from the turret angle while not having the sprite angle set to the angle of motion.

**Comment by AshleyScirra** [comment]
This is currently by design. The 'Set angle' setting is actually two-way: when enabled it both sets the object angle to the angle of motion, and if the object angle is changed, updates the angle of motion to correspond. If disabled, the object angle and angle of motion work completely independently and don't affect one another. 'Spawn an object' only sets the object angle, and therefore does not update the angle of motion.

You can just add a 'Set angle of motion' action in the bullet behavior and it works like you want.

**Comment by calminthenight** [comment]
I figured it would be something like that, and as mentioned am aware of the simple workaround. I still think it is important to update the Turret Behaviour and Bullet entries in the manual to include this interaction. As it is not detailed anywhere currently.

**Comment by AshleyScirra** [comment]
I updated the Bullet behavior manual entry to cover this. It's not related to the Turret behavior at all.
