### ISSUE TITLE
Blend effects bug

### ISSUE THREAD

**Issue by elfwy-uwu** [Scirra/Construct-3-bugs#5226]
## Problem description

All effects from "Blend" section don't apply on transparent layers

NOTE: The new effect compositor did not cause this issue, nor fixed it. Since I discovered it in earlier builds.

## Attach a .c3p

https://drive.google.com/file/d/1UJRhuTXofNQPr0HXnpfg4hpqQIrMknNI/view?usp=sharing

## Steps to reproduce

1. Open the source code
2. There's 3 cases presenting screen effect, explore them
3. Case#3 doesn't work correct, while case#2 which is logically the same works fine

## Observed result

Sprite with blend effect on transparent layer is simply an original transparent sprite

## Expected result

Opaque sprite (with blend effect) on transparent layer produces the same result as transparent sprite on opaque layer

## More details

**Affected browsers/platforms:** Chrome, Firefox

**First affected release:** First release build I guess

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 95.0.4638.69
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
C3 release: r271.2 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 67 gb
Storage usage (approx): 198 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9649)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by elfwy-uwu** [comment]
Seems like none of blend effects work with transparent layer.

**Comment by AshleyScirra** [comment]
This is by design. When you change the layer opacity, it has to switch to 'own texture' mode, where it renders the entire layer to a separate off-screen surface, and then afterwards draws that surface to the display. This does not need to happen with normal drawing, but in order to get all the pixels on the layer to change opacity as desired, it's necessary to do this so the opacity can be altered when drawing the entire layer surface to the display. Various other parameters such as the blend mode and adding effects also enables own-texture mode. Layer Properties has a 'Uses own texture' field that tells you if it's doing this. You can see the same thing happening on the other layers if you enable 'Force own texture', which forces that mode of drawing (which can be useful for various masking effects).

When a layer is drawing to its own surface, anything that blends with the background will then blend with the content of the layer's own surface - which for a transparent layer, is all transparent black. Hence the results you see.

**Comment by elfwy-uwu** [comment]
Thank you @AshleyScirra for detailed explanation
