### ISSUE TITLE
3D Effects: Transparent textures issue

### ISSUE THREAD

**Issue by elfwy-uwu** [Scirra/Construct-3-bugs#5248]
## Problem description

3D effects are not visible through transparent sprites & produce unexpected results

Bunch of screenshots: 
<details><summary>Everything on a single layer</summary>

![image](https://user-images.githubusercontent.com/15311427/142349082-faa91e4f-2e93-4dff-9079-ae7d4090b188.png)
![image](https://user-images.githubusercontent.com/15311427/142349190-6374367f-e4c3-48c2-9b25-96e7a45bd3aa.png)

</details>

<details><summary>Transparent objects separated from terrain to a different layer</summary>

![image](https://user-images.githubusercontent.com/15311427/142349508-d624fa0d-6f03-40a7-b097-094d64376958.png)
![image](https://user-images.githubusercontent.com/15311427/142349560-28965f8f-45a1-471d-8160-3567d5e0ae8b.png)

</details>

## Attach a .c3p

Use built-in templates modifies with 3D effects

## Expected result

3D effects consider textures transparency

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r272

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 95.0.4638.69
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
C3 release: r272 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 67 gb
Storage usage (approx): 54 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9676)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This just reflects how 3D rendering works. Transparency in 3D is complicated. Transparent areas of images still count as opaque for depth purposes and so can both cover up the rendering of objects behind them, and count as nearer than the background for depth-processing effects like fog. It's covered in more detail in this tutorial here: https://www.construct.net/en/tutorials/using-3d-construct-2746

For effects like Fog in the 'First person shooter' template, it works reasonably well if you add fog to each layer separately (Main and Billboards), since that ensures the background is drawn with fog, and then the pigs draw over that with fog affecting the pigs. It's not perfect when the pigs intersect as once again the transparent areas still fill in depth. Perhaps it could be improved upon by using fog just for the background and using another effect, like tint, using events to adjust the effect amount based on distance - i.e. faking it, which is a lot of what computer graphics involves.
