### ISSUE TITLE
Tween Zelevation & ZIndex

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-3-bugs#5291]
## Problem description
Tween ZElevation not going back old ZIndex.

## Attach a .c3p

[bugTween.zip](https://github.com/Scirra/Construct-3-bugs/files/7671394/bugTween.zip)

## Steps to reproduce

1. Run project and look browser console logs.

## Observed result

```
START-ZElevation: 0
START-ZIndex: 3
END-ZElevation: 0
END-ZIndex: 0
```

## Expected result

```
START-ZElevation: 0
START-ZIndex: 3
END-ZElevation: 0
END-ZIndex: 3
```
**NOTE:** In r272-2 version it is showing "END-ZIndex: 5". I think it should be re-back old ZIndex -> "END-ZIndex: 3"

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** i think r273

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Version openable in older releases:
[issue5291.zip](https://github.com/Scirra/Construct-3-bugs/files/7675836/issue5291.zip)
Here it looks like the END-ZIndex is always 5, in both latest beta and right the way back to r241, so it doesn't look like a recent regression.

**Comment by AshleyScirra** [comment]
Upon further consideration, this is not actually a bug: it is currently by design.

The way Z order works is everything is sorted by Z elevation first, and then where the Z elevation is the same, the Z index is used. Actions like "Bring to front" affect only the Z index - it won't make something appear on top of another object that has a higher Z elevation.

In this case as soon as the Z elevation of a sprite is increased, it jumps to the top of the Z order - similar to doing "Bring to front" on it. When the tween finishes it, it returns to the same Z elevation, but it is coming from the top of Z order, so it is left in front of everything else with a higher Z index - since increasing the Z elevation effectively did "Bring to front".

It's not really feasible to fix this - it could in theory remember what its Z index was at the Z elevation where it came from, but then this process might be repeated at multiple Z elevations, and the place where it came from might also change as well, with the Z indices being changed or the Z elevations altered in a dynamic way. So I don't think it's actually really solvable in a useful way that wouldn't just end up interfering with existing projects.

So I think it's best to leave it up to your project to sort Z order, and re-sort after changing Z elevations if necessary. Actions like the system 'Sort Z order' action should be useful for that.

**Comment by CrackHub** [comment]
I see it looks a little complicated. But as i said r272.2 and lower versions give me "END-ZIndex: 5" and starting with r273 it gives wrong result ("END-ZIndex: 0"). With r273 it is breaking some projects.
This should be fixed?

**Comment by AshleyScirra** [comment]
I ran it 10 times in r275 and it was consistent that the end Z index was 5. I cannot reproduce any variability.

**Comment by CrackHub** [comment]
Really? 🤔  I don't know what's going on but i try it with clean Firefox and incognito Chrome still happening.
No extension, no plugin.

![image](https://user-images.githubusercontent.com/54614906/145810482-442be4a4-32b5-43b5-87a7-9006c6b696e3.png)

If it's help there is my system (Windows 11)

## System details




<details><summary>View details</summary>

Platform information

Browser: Firefox
Browser version: 95.0
Browser engine: Gecko
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0
C3 release: r275 (beta)
Language setting: en-US
Local storage

Storage quota (approx): 2 gb
Storage usage (approx): 8.8 mb (0.4%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
    The <dialog> element is not supported. A polyfill is in use.
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    ImageBitmapOptions is not supported. Texture loading performance may be degraded.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.7247)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 8
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>
