### ISSUE TITLE
Displaying Return-Based Function Parameter Interface

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-3-bugs#5292]
Problem: When modifying an existing return function's parameter input values, I'm not able to see which parameter I'm modifying.

Image 1: Parameter interface shown when you first start adding the parameter values.
![image](https://user-images.githubusercontent.com/37854520/145144278-febb0384-870d-4291-af64-857fbee282ef.png)
Image 2: Parameter interface does not show when modifying the values (unless you wipe all values clean and start over)
![image](https://user-images.githubusercontent.com/37854520/145144291-46560ee4-fac2-48df-aeb6-c31de8eea00d.png)

Desired Result: Parameter interface shows when modifying any of the parameter values.

**Comment by AshleyScirra** [comment]
Similar to #5271, this is currently intentional, as supporting call tips when editing in the middle of parameter lists would require parsing expressions of arbitrary complexity while backtracking to find the expression and object name, which is very complicated. It would be best to track this as a feature request here: https://construct3-21h2.ideas.aha.io/
