### ISSUE TITLE
Turret targets itself when using families

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#5323]
## Problem description

I have a strategy game, with 3 families: Unit (all units), Enemy (enemy units only), and Player (player units only). I put a Turret behavior on Unit; since it is common for all units. I added Player as a target to Enemy, and Enemy as a target to Player.
What happens when I run the game is that units of the same family target themselves! (i.e. Enemies target enemies).

I had to remove Turret from Unit, and add a Turret for Enemy and Player separately. Now targeting works correctly, but I have to repeat the Turret code twice (once for Enemies and once for Player), instead of using it once on Unit for all units.

## Attach a .c3p

[Turret Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/7743146/Turret.Bug.zip)

## Steps to reproduce

1. Preview the game.
2. Drag the orange sprites around the green ones.

## Observed result

At the start: S2 (green) objects will trigger OnShoot and turn black. In the debugger you can see the target UID is the same as the object UID (i.e. targeting itself, or targeting other green objects). Even though the game doesn't set a target for them! The game only sets a target for S1 (orange).
But S1 (orange) objects work correctly: they only turn black when they become close to their target (green sprites).

## Expected result

Each object targets its target, not itself.

## More details
The problem is fixed when not using a common Family Turret behavior, i.e. a Turret behavior for each object separately. Like this:
![Untitled](https://user-images.githubusercontent.com/12113416/146726609-43331254-48ca-4079-bccc-eee490e30541.png)

**Affected browsers/platforms:** Firefox

**First affected release:**

**Comment by AshleyScirra** [comment]
I've updated the next beta to ensure turret behaviors don't target themselves. However the project will still not do what you want: the target list for the Turret behavior applies to the entire behavior. So "S1: add target S2" actually modifies the family turret behavior, and so all objects in the family - both S1 and S2 - will target S2. The other disabled action will work the same, so everything will end up targeting everything. This is currently by design.
