### ISSUE TITLE
Find all references has some results which are irrelevant

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#533]
## Problem description

This is slightly related to the issue I've opened about the Find not having a match word. Find all references does seem to include some results which have only a part of their name the referenced object's name.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*
![image](https://user-images.githubusercontent.com/7268697/27259361-1b0f5812-541a-11e7-8ee8-290b1d1c76a5.png)

[FindAllReferences.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1082965/FindAllReferences.c3p.zip)

## Steps to reproduce

1. open the project
2. right click **Ability_Array_LastIteration**
3. select Find all references

## Observed result

An object which has a part of the name included in the object we're looking for showed up in the results.

## Expected result

I expect strictly the object I'm looking references for to appear in the results.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The problem with "Create object by name" is it creates ambiguous references. For example if you create an object by the name of some text the user inputted, it's impossible to know in the editor if that action references the object you are searching for or not. So it currently - by design - lists an ambiguous result with the "?" icon.

It may be obvious that given an expression of the form `"foo" & x`, an object named "bar" won't match, but extending this to the general case still doesn't work (e.g. `x & y`) and involves some pretty complicated static analysis code. It's not something we are looking to address right now.

**Comment by JeFawk** [comment]
I understand now what happens, thanks for explaining.
