### ISSUE TITLE
Text Quality Loss when Resizing  

### ISSUE THREAD

**Issue by Tarek200** [Scirra/Construct-3-bugs#5331]
If you resize the Text size many times it will lose rendering quality

Example:

If you have a long text and you are showing the text by typewriting, every time you add a character to the txt we resize the txt object to adjust the (Height & Width) to fit the txt, so the more we resize the more it loses the quality.

or 

You paste the whole string into the txt object and resize the txt many times it will lose quality too

![Image 10](https://user-images.githubusercontent.com/41597700/147467120-694dcaee-21ac-4350-9f76-92f804733909.png)

## Attach a .c3p

[1-Txt Quality Loss BUG.zip](https://github.com/Scirra/Construct-3-bugs/files/7779928/1-Txt.Quality.Loss.BUG.zip)

## Steps to reproduce

1. Run the project 
2. Wait a few seconds until it runs all the Actions

## Observed result

The text losses quality 

## Expected result

That the text doesn't loss quality

## More details

Chrome

C3 R268 
C3 R276.2

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 96.0.4664.110
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
C3 release: r276.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 124 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-27.21.14.6663)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. Text objects render as a texture, and a maximum texture size is specified both to save memory, and to avoid exceeding the hardware maximum texture size limit. Therefore beyond a certain size text objects will not be able to render to a larger texture, and so reduce the quality instead. You should break up long texts e.g. in to paragraphs to avoid this problem.

**Comment by Ldwebster111** [comment]
This is actually really annoying. I've been tasked with writing a system that can paste segments of text to the screen in split pages in different languages. The easy solution to this would be to draw the entire text off screen and use canvas to draw segments to screen as required. As Tarek points out though, the larger the text segment the blurrier the text, making this solution unfeasible.

**Comment by Tarek200** [comment]
Indeed it is really annoying

"Therefore beyond a certain size text objects will not be able to render to a larger texture"
Ashley, can you tell us the max text size that doesn't exceed the texture?  
To have a general idea of how big can be the paragraphs

**Comment by Ldwebster111** [comment]
So imagine this. You spend a few years making a game in Construct 3. One of the last things you need to add is a credit roll, taking everyone who's helped over the years, publishers and contributing factors, and then add them to a single vertical text reel that scrolls up the page.

Except that doesn't work because, for some bizarre reason, the larger a text object is, the more unreadable it becomes. You look online, only to find that other Construct users have been resorting to spritefonts because of issues like this with the text object. Except, part of the reason you've been using the text object is because your game needs to be translated into a variety of different languages (recommended in the C3 manual), including Asian and Latin accents. Because of this, there's hardly any spritefonts that will work for you, a problem compounded by the fact that no other game engine has such a ridiculous limitation on something that's a basic feature, so the pool of spritefonts on other marketplaces that can be drawn on is extremely limited (and likely doesn't exist).

Ashley, you've tagged this as 'not a bug', but that doesn't make it a non-issue, it just highlights how poorly implemented text is in the C3 engine.

No other game engine has this problem.

Please look further into it.

**Comment by AshleyScirra** [comment]
It should be easy to split a credit roll in to different text objects.

The hardware ultimately imposes a maximum texture size limit, so this cannot be unlimited: there is a hard limit that it will always run in to one way or another. So there's no way to use unlimited size text objects, so you need to split them up in to different objects.

**Comment by Ldwebster111** [comment]
Well, the credits roll was just one example where this is going to be a common issue. I can present others if you'd like.

Ultimately, it would be great if there was an option to prevent text from rendering at all and instead paste segments of it to drawing canvas to display only those parts of the text at any one time.
