### ISSUE TITLE
Ctrl+A then Delete, doesn't work for the Icons

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#5332]
## Problem description

I have to set all icons 1 by 1, but when I click Ctrl+A to select all, then Delete to clear the image and add the new one, it doesn't work. I have to use the eraser and erase each image manually.

## Attach a .c3p

(New Project)

## Steps to reproduce

1. Create a new project.
2. Double click any image in the Icons folder.
3. click Ctrl+A
4. click Delete on the keyboard

## Observed result

Nothing happens

## Expected result

Clear image

## More details

**Affected browsers/platforms:** Chrome, Firefox

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta. Currently Ctrl + A only works when the rectangle select tool is active. After this patch hitting the keyboard shortcut will change to the tool and select the whole image, regardless of which tool was selected previously.

Deleting the selection was just not working on project files.
