### ISSUE TITLE
Preview switches to the game tab, even when there are code errors

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#5357]
## Problem description

I deleted some objects from my project and clicked Preview Project. C3 moved to the preview tab, and I kept waiting for it to load. When it took a while I went back to C3 tab and found an error message about an Else without a condition before it. Turns out, when I deleted an object, it deleted one of its conditions before the else.
But instead of warning me, C3 moved directly to the preview tab (that was already there from previous runs).

## Attach a .c3p

[preview.zip](https://github.com/Scirra/Construct-3-bugs/files/7839688/preview.zip)

## Steps to reproduce

1. Run the project in a new tab.
2. Leave the preview tab opened, and go back to C3 tab.
3. Delete the condition before the else.
4. Click preview again.

## Observed result

C3 switches to the tab opened in step 1, but nothing happens.
Return to C3 to see the error.

## Expected result

Do not switch to a tab if there are errors; to allow the user to see the error, instead of assuming everything is fine.

## More details

**Affected browsers/platforms:** tested only Firefox 95.0.2

**Comment by AshleyScirra** [comment]
This is tricky because browser rules about popup windows mean that the preview window can only be focused in a user input event. Chromium-based browsers have more relaxed rules about what counts as user input, so I've changed it for the next beta to delay focusing the preview window until project validation is complete. However other browsers like Firefox (which you stated you are using) have stricter user input rules. Validating the project takes a short amount of time, and in these browsers that tiny delay means that it no longer counts as in a user input, and so the preview window cannot be focused. Therefore the only option is to focus the preview window up-front, before the validation is done, but if an error occurs then it will still do what you described.

I don't think there's any way around this since these rules are imposed for security/usability reasons. However if Firefox/Safari add the same feature as Chrome has for allowing more relaxed user input rules (which is now part of the standard, not a Chrome-only invention), then Construct will automatically detect that and delay focusing until after validation.
