### ISSUE TITLE
Dark theme: Behaviors without properties and Add/edit not separated from previous panel

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#537]
## Problem description

The Persist behavior is inside the Sine panel. This makes it very hard to spot as I'm used to behaviors having names on the header of a panel, with a different background and written all in capslock.
Also I find it pretty odd as the Add/edit Family behaviors is not split by a dark line, something which could be applied to the behaviors without properties as well.

## Attach a .c3p

![image](https://user-images.githubusercontent.com/7268697/27290145-05d564fe-5515-11e7-8d45-5a56855d5c2c.png)

## Observed result

I see the Persist and Add/edit Family behaviour in the same panel as the SINE_ATIVATEDABILITY

## Expected result

I expect the Persist to be shown as the SINE_ACTIVATEDABILITY, as a header with capslock, split from the SINE_ACTIVATEDABILITY panel even though there are no properties for it. I also expect for the Add/edit Family behaviors shown below Persist to be separated.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 58.0.3029.110
Browser engine: Blink
Browser architecture: 64-bit
Context: webapp
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
C3 release: r39

Local storage
Storage quota (approx): 6.7 gb
Storage usage (approx): 68 mb (1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Backdrop filters are not supported. Some UI effects are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 770 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Animmaniac** [comment]
This is something I can't change just through css. The Persist behavior is inserted as a 'behaviorProperty' instead of being a '<td propgroup>' inside a '<ui-proprow>' as regular behaviors. And it seems there's no other selectors I could use to differentiate it from regular behavior's properties. It can only be fixed on the code side by inserting Persist with a regular behavior structure or adding a new class to it.

Ideally sub-groups like added behaviors and effects would not have separator lines, and their names would not be in uppercase since they are user editable and case-sensitive (I would probably use other methods to differentiate them and indicate they belong to the 'Behavior' or 'Effect' group). But since I kind of hacked the current style over the original table layout they are not something I can change right now. They simple inherit the same style as group titles. With a different class for sub-groups it should be possible.

Also the add buttons ideally should probably take the whole width of the line, drop the "Add/edit" label and have it as part of the button's text instead like "Add/Edit Behavior". It would probably be a lot easier to spot them. But that is out of my control currently.

**Comment by AshleyScirra** [comment]
@Animmaniac - I just added a `behaviorWithNoProperties` class to rows added for behaviors with none of their own properties. It didn't make r40 but will be in r41. That should at least let you customise the appearance of that kind of row so it's more obvious it's a separate behavior.

**Comment by Animmaniac** [comment]
Fixed for next theme release.
