### ISSUE TITLE
Offline Construct editor, Free / guest mode

### ISSUE THREAD

**Issue by redfoc** [Scirra/Construct-3-bugs#5382]
## Problem description

Construct 3 editor can be used offline, but when I go offline, my account is detected as a Free / guest mode, even I have an active subscription.

So, when I use offline mode, I can't modify my project due to free mode limitation

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It works fine for me. The account icon changes to this:
![offline-icon](https://user-images.githubusercontent.com/768723/150329271-8453dcfe-c75e-4c16-8c85-027f27939657.png)
It should continue to allow you to use the features of your account for up to 7 days.

Make sure you haven't changed browser settings or used a browser extension that clears storage, since this will block Construct saving your offline account details. Other than that it's impossible for us to help unless you provide more information as per the bug report guidelines.
