### ISSUE TITLE
Text BBcode background - spaces and newlines

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#5388]
## Problem description

I'm trying to add bbcode background to my captions and I want to add a little extra padding on each side. 
When a text is broken into more than 1 line, the space in the end of each line are ignored by the background bbcode tag.

## Attach a .c3p

[textBBcodeBGcolor.zip](https://github.com/Scirra/Construct-3-bugs/files/7919392/textBBcodeBGcolor.zip)

## Steps to reproduce

1. Take a look at the text object and the text strings.
2. Notice it has spaces at the end of each line.
3. Look at how it is rendered in either the editor and run-time.

## Observed result

Spaces at the end of each line are being ignored.

## Expected result

Keep the spaces.

## More details

**Affected browsers/platforms:**  Chrome/NWjs, Windows

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is intentional: with word break, spaces are allowed to be collapsed to newlines. This also ensures center/right alignment looks correct and that underlines are not drawn past the ends of words.

If you intend to include a space such as for styling purposes, then you should use a non-breaking space character (alt+0160 on Windows). However I noticed the word break algorithm still breaks on non-breaking space characters, which is incorrect. This is fixed for the next beta.
