### ISSUE TITLE
Mobile IAP on purchase success triggered issue

### ISSUE THREAD

**Issue by DanPkg** [Scirra/Construct-3-bugs#5404]
## Problem description

Using the Mobile IAP inbuilt plugin ,  On Purchase Success is triggered for an already purchased product, if you load a layout quickly that holds the trigger.

## Attach a .c3p

See comment below with attachment

## Steps to reproduce

1. Create a blank project
2. On First (Menu) Layout1: Add a non-consumable product id on the"On Start Layout" trigger and then the "Complete Registration" action afterwards.
2. Add a sprite (button) to (Menu) Layout1. Add Trigger "On Touched Sprite" loads Layout2
3. Add Layout2. In Layout2 Eventsheet, add On Purchase Success "ProductIDofNon-Consumable"
4. As an action to this "On Purchase Success" -> Create a Text Object with text "Test Purchase" in middle of layout.
5. You must purchase the test product to repeat the issue.

## Observed result

If you load the game and press the sprite quick enough (<1sec) the Text Object is created in Layout2 even though this is embedded in the "On Purchase Success" trigger.

If you wait 2-3 seconds after the (menu) Layout1 has loaded and touch the sprite, this is not a problem.

## Expected result

"On Purchase Success" trigger should not fire at all from loading a (menu button) layout quickly and a non-consumable product already purchased before.

## More details

I suspect the Complete Registration action hasn't finalised and conflicting with On Purchase Success trigger from layout2, given if you wait 2+ seconds more it's not a problem.

**Affected browsers/platforms:** 
Android and the test product id (non-consumable) must be purchased.

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please attach a project as per the bug report guidelines.

**Comment by DanPkg** [comment]
[TestMobileIAP.zip](https://github.com/Scirra/Construct-3-bugs/files/7962389/TestMobileIAP.zip)

But only reproduceable on Android (not desktop) and with the Test Product ID non-consumable already purchased.

**Comment by AshleyScirra** [comment]
This just looks like a mistake in your events. As per the [manual entry](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/mobile-iap), you must wait until *On Registration Success* triggers before you can check the state of any products. However your project does not wait for this and allows the user to change the layout before the IAP plugin's registration is ready. This is not valid so the resulting behavior may be unexpected.

FWIW the IAP plugin does not care what layout you are on - the triggers will work the same. But since triggers only fire if they are on an event sheet used by the current layout, what you are effectively doing is disabling and enabling different sets of IAP triggers at an unpredictable time. Your project should either make sure all IAP triggers are included on all layouts so none are missed, or prevent the player from moving to the next layout until all registration/initialization has completed.

**Comment by DanPkg** [comment]
Thanks but I am not "checking the state of any products". The "On Purchase Success" Trigger itself is firing off. This should only trigger once you purchased something from Google Play Store I would of thought.

Thanks for your advice and time. I will workaround.
