### ISSUE TITLE
On created bug

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#5467]
## Problem description

If the "On created" trigger condition is present, then the sprite does not set a color.

## Attach a .c3p

[on_created_bug.zip](https://github.com/WilsonPercival/WilsonPercival/files/7965585/on_created_bug.zip)

## Steps to reproduce

1. Open and run source code.
2. Press the "1" key.

## Observed result

If the "On created" trigger condition is present, then the top "Sprite2" does not set a color. If the triggered condition "On created" is not present, then everything works correctly (the color is set).

![bug1](https://user-images.githubusercontent.com/91274932/151693354-715ce24f-9cf1-4b08-ae8e-5cebdb6c90bd.gif)

## Expected result

The triggered condition "On created" does not affect the performance of other events.

![bug2](https://user-images.githubusercontent.com/91274932/151693360-4b657636-e66b-4673-b6f9-c8ba5af988ab.gif)

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r276-2s

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 95.0.4638.54
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 7
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36
C3 release: r276.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 452 mb (0.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0, igdumdim64.dll-10.18.10.4653)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_float_blend
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
EXT_sRGB
KHR_parallel_shader_compile
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
As a note about your recent submissions: please do not dump loads of issues on us in one go. We are a small team with limited resources and this has created a large amount of work for us in one go. If several people did this, we could easily end up with an insurmountable amount of work. Further, if many of these issues are not bugs, system-specific, or too minor to be considered a problem, many of them could be closed without any action, which means you wasted a lot of time filing them. Filing the issues as you find them means you will be more likely to learn what kinds of reports are actually meaningful and will be acted on. Presumably you have queued up a large number of reports over a long period of time and filed them in one go - please file them as you find them instead.

**Comment by arturbier** [comment]
> As a note about your recent submissions: please do not dump loads of issues on us in one go. We are a small team with limited resources and this has created a large amount of work for us in one go. If several people did this, we could easily end up with an insurmountable amount of work. Further, if many of these issues are not bugs, system-specific, or too minor to be considered a problem, many of them could be closed without any action, which means you wasted a lot of time filing them. Filing the issues as you find them means you will be more likely to learn what kinds of reports are actually meaningful and will be acted on, and then you can adapt later issues accordingly, avoiding wasting time. Presumably you have queued up a large number of reports over a long period of time and filed them in one go - please submit them as you find them instead.


I think you should have thanked him, not scolded him.

**Comment by AshleyScirra** [comment]
I appreciate the testing work this has involved. However sitting on your test results for months and then submitting them all in one go (which is what I'm assuming happened here) causes a lot of problems. For one thing it's clear few or none of these reports have been tested in the latest beta release (currently r281) as our bug report guidelines require. The point of the guidelines is to avoid wasting time by filing issues that have already been investigated and dealt with, and this approach is particularly likely to waste the time of both the submitter and our team.

Further as a small team with a huge amount of work to begin with, it is unhelpful to receive a huge volume of work out of the blue in one go. Imagine having a very busy day at the office and then someone comes and dumps a huge pile of paperwork on your desk, says "do this as well please", and then walks off. It messes up your ability to schedule work, delays other important work, reduces the time we have available to support other customers, and frankly is demoralising. It is also inefficient, as if some of these reports were discovered say 2 months ago, and were filed at the time, we'd have had the past 2 months to investigate it and work on it, but since they were held back we have not had the chance to work on it for a long time since it was found. And the longer an issue is held back, the more likely it is to get fixed anyway, and therefore submitting it just creates unnecessary extra work. Our ability to respond effectively to bug reports does actually depend on the fact they tend to be reported gradually in small numbers over time.

Users testing Construct and reporting problems is indeed valuable feedback and I appreciate it. All I am asking is that issues are reported as soon as you find them. This should be easy. It will avoid causing problems for us managing our workload and supporting other customers. It is also in your interest: we are able to do better quality work, and resolve issues sooner, than if you hold them back. As it is we do not have the resources to do a detailed investigation of all these issues, so we will try to work through them as quickly as possible and close them if we cannot immediately identify the problem, especially since it seems likely they could have been fixed in the latest beta.

I'm afraid for all these reasons if a large number of issues are submitted in one go again and they have not been tested with the latest beta, I will close all of them without investigation. I will review the issues submitted this time on this occasion only, on the assumption this really was a good faith effort to report issues, and not really an attempt to spam us or disrupt our ability to work effectively. Please only report issues that have been tested in the latest beta - Construct changes every week, after all - and our bug report guidelines already require this. The guidelines are based on around a decade's worth of software development experience. They are very carefully written, and everything stated is there for a very good reason, to avoid all these problems that we've seen time and time again, and want to avoid happening again.

**Comment by WilsonPercival** [comment]
Sorry. I missed the point that said what to test in the latest beta. I specifically tested in the latest stable, because beta usually has more bugs.

**Comment by elle-trudgett** [comment]
It may be due to the way the picking system works. Since you are doing something for multiple instances, it can be worked around by using the 'For Each' then your event block is running on a single instance each time which seems to avoid the issue.

[on_created_bug_workaround.zip](https://github.com/Scirra/Construct-3-bugs/files/8006982/on_created_bug_workaround.zip)

**Comment by skymen** [comment]
If this behavior is linked to the way Spawn is designed, why not deprecate it and replace it with a brand new action instead? That way old projects can keep using it, avoiding any large scale breakage, and you'd be free redesigning the entire action with no fear.

IMO, 75% of the reasons you'd be using spawn is when you have multiple "parent" instances, so if you can't do that because it just breaks when multiple instances are involved, then I don't see how the action is any useful in its current state.

**Comment by AshleyScirra** [comment]
It's to do with the event engine, not the specific action. Currently there's no way in the engine to design a new action that fixes this.

**Comment by AshleyScirra** [comment]
The ideal solution is to fix the action in a backwards-compatible way. It's possible, but can be difficult. Deprecating and replacing such a commonly used action with one that works differently will introduce its own quirks and gotchas, like projects working differently after deleting and recreating an action.

**Comment by skymen** [comment]
Makes sense. Alright 👌

**Comment by AshleyScirra** [comment]
I managed to come up with a way that I think should solve this without any extra performance cost, by adding a special case in the event engine for this type of action specifically. It's quite complex but since the 'Spawn' action is such a fundamental and widely used feature I think it's worth the trouble to get it right.

The old code dates back years - probably from the early days of Construct 2, or possibly even back to Construct Classic - and changing it is quite risky in terms of breaking backwards compatibility. So the fix is being held back for the next release cycle. It will be out in the first beta after the next stable release. This will maximize the amount of time it's on the beta channel and help identify if there's any backwards-compatibility breakage from the new approach.
