### ISSUE TITLE
The Example Browser's Filters dont clear when first search

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5472]
## Problem description

Currently, Example Browser enables ` Recommended ` Filters by default. So when I first search, it will only search under Recommended tag.

I think that the Recommended filters should be automatically cleared when the user does the first search without manually enables Filters. Only keep them if the user has opened Filters themselves.

## Steps to reproduce

1. open Example Browser
2. search any thing, e.g. ‘Player’

## Observed result

0 results (of 266 total)
Matching tags '<em>Recommended</em>' and search '<em>Player</em>'</span>

## Expected result

40 results (of 266 total)
Matching search '<em>Player</em>'

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. If search always clears tags, then it might be annoying - suppose you select the "scripting" tag and then search for "storage". Currently it filters down to projects with both "scripting" tag and matching term "storage". However if we made the change you suggest, this would instead clear the "storage" tag and show results for all projects matching "storage", including non-scripting ones.

If the first search is different, then it makes searching inconsistent: from the user's point of view, sometimes it clears tags, sometimes it doesn't.

The search results footer tells you what you have searched for, e.g. "Matching tags 'Recommended' and search 'storage'". You can just click "Clear tags" and then you are left with no tags and all results for search "storage". Alternatively you can unselect the "recommended" tag first. I think this approach is a reasonable compromise. But perhaps there's a different way?

**Comment by XHXIAIEIN** [comment]
Maybe it could be so that the recommended filters are not selected by default. Instead, they should be displayed above the default content? Display them all on the same page.

```
## New
## Recommended 
## default content(A-Z)
```

The cost of sliding down with the mouse wheel is much easier than moving the mouse and clicked.

**Comment by AshleyScirra** [comment]
I think the simplest solution is actually just to make the Example Browser remember the last search. It still defaults to the "recommended" tag the first time you view it, but then after that it will restore whatever search you last had, rather than always reverting to just the "recommended" tag. This is probably useful anyway in case you're doing something like going through a list of example projects matching a search across several sessions, and it also avoids constantly reverting to the "recommended" tag, allowing you to leave it with an empty search showing everything and get that back again next time. I think that will do the job, and it's done for the next beta.
