### ISSUE TITLE
C3 Editor: Sorting tabs in multiple rows not working correctly

### ISSUE THREAD

**Issue by pandabear7413** [Scirra/Construct-3-bugs#5499]
If there are multiple rows of tabs in the C3 Editor, moving a tab from one row to another causes unexpected results.  See [this post for more details](https://www.construct.net/en/forum/construct-3/general-discussion-7/lock-layoutevent-sheet-tabs-166977).  Per DiegoM, "I see what the problem is now. What is happening is that as a tab is dragged, it switches place with the one located where the pointer is at.  This works properly if there is a single row, because you can only move left or right, but I can see why it would produce unexpected results when moving up and down."

To reproduce, open layouts in attached c3p until there are multiple full rows of tabs.  Then move/drag a tab from one row to the middle of the other row.   On mouse release, the tab under the pointer is swapped with the original tab.

[tabBug.zip](https://github.com/Scirra/Construct-3-bugs/files/8121461/tabBug.zip)

**Comment by ChromeWisp** [comment]
This has definitely been occasionally bothersome on bigger projects with that many tabs... Maybe dragging a tab should be used to find the nearest space between two tabs to drop it into without otherwise adjusting the order, rather than how currently the dragged tab just instantly swaps with every other tab it moves across?

**Comment by AshleyScirra** [comment]
Should be fixed in next beta.
