### ISSUE TITLE
"Paste object" works incorrectly with Z axis scale "regular"

### ISSUE THREAD

**Issue by BonzerKitten** [Scirra/Construct-3-bugs#5500]
## Problem description

The "Paste object" action from the "Drawing canvas" plugin is now trying to copy the entire image instead of only what's below it, which is a completely different behavior when compared to the previous stable release.

## Attach a .c3p

[Drawing Canvas Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/8126731/Drawing.Canvas.Bug.zip)

## Steps to reproduce

1. Just hit F4 to preview the project.

## Observed result

The drawing canvas will copy the entire image.

## Expected result

The drawing canvas to copy only what's below it.

## More details

**Affected browsers/platforms:** Google Chrome/Windows 11

**First affected release:** r284.2

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The project uses Z axis scale "regular" (a new feature since the last stable release) - it works correctly if you use "normalized", which is what all existing projects default to. We're close to a stable release and this should not regress existing projects since it depends on the new Z axis scale setting, so we will look in to this for the next release cycle.

**Comment by BonzerKitten** [comment]
@AshleyScirra Thanks for the clarification! That's totally understandable, I'll wait and revisit this topic once the next beta is ready.

**Comment by AshleyScirra** [comment]
Thanks for the report, should be fixed in the next beta.
