### ISSUE TITLE
Scripting Interface's "phase" method of the Sine behavior is not using the cycle position

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-3-bugs#5534]
## Problem description

Scripting Interface's `phase` method of the Sine behavior is not using the cycle position, contrary to its documentation.

### Preview

![image](https://user-images.githubusercontent.com/31282960/159098786-ac29e59c-dcf8-44ff-ab73-bfdcc05835b1.png)

### Documentation

![image](https://user-images.githubusercontent.com/31282960/159098804-2eed6a62-618d-4a63-abb7-0812b047e965.png)

### Event sheet

![image](https://user-images.githubusercontent.com/31282960/159098928-eaf97a70-aac5-4b4d-8391-cfa7e0068a5b.png)

## Attach a .c3p

[Sine Phase Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/8308178/Sine.Phase.Bug.zip)

## Steps to reproduce

1. Preview the attached project.
2. Please observe the difference between the cycle position and the `phase` value.

## Observed result

The `phase` value is not setting and outputting the cycle position. Instead, more like the 6 parts of the sine cycle. 

## Expected result

The `phase` and cycle position having the same value.

## More details

r285.3

##
Thank you!

**Comment by AshleyScirra** [comment]
The phase in the script interface actually uses the range [0, 2π] rather than [0, 1]. This is because the wave function takes a value in radians. The event system uses a different unit system that IIRC never exposes radians, it always uses degrees, or in this case normalized. The script interfaces do use radians for angles, as that's what is really passed to functions like `Math.sin`, which is a more natural fit for JS coding. The documentation of the [Sine behavior script interface](https://www.construct.net/en/make-games/manuals/construct-3/scripting/scripting-reference/behavior-interfaces/sine) was incorrect though, stating the phase went from 0-1. I've updated the manual entry to correct that.

**Comment by Chadori** [comment]
Oh, yeah that makes sense and is indeed better, thank you for explaining.
