### ISSUE TITLE
ImageInfo isRotated value not set properly

### ISSUE THREAD

**Issue by ratalaika** [Scirra/Construct-3-bugs#5555]
## Problem description
When using deduplicate images option we found a particular case in which the isRotated value is exported as false stored on the data.json instead of true, that causes one of the frames to not render properly.

We're unsure if this extends to other values or not from the same frame ImageInfo.

## Attach a .c3p
[Test.zip](https://github.com/Scirra/Construct-3-bugs/files/8336040/Test.zip)

## Steps to reproduce
1. Open the game on preview and change frame with A/S
2. Export to html5, and check the "deduplicate images" option
3. Upload to a server and re-test (on this versions the frames do not move properly.

## Expected result
I guess it should work both the same on preview and exported.

## More details
This seems to happen when exporting to HTML5 but not when previewing on the editor, so I assume preview is not using the deduplicate image logic due to been preview mode.

This also seems to affect NWJS export if using deduplicate option too.

First seen on r268, also seen on r285.3 stable and on latest beta.

**Comment by AshleyScirra** [comment]
Thanks for the report, it's a good catch. It turns out image deduplication was based on a hash of the image pixel buffer, but that could actually be the same for different sized images - in this case 20x10 and 10x20 solid blue images both produce a pixel buffer of 200 blue pixels, and therefore hash the same. The next beta ensures only the same size images get deduplicated to avoid this problem.
