### ISSUE TITLE
Chrome for Android wakelock support

### ISSUE THREAD

**Issue by oosyrag** [Scirra/Construct-3-bugs#5564]
## Problem description

Wake lock is not supported via the platform info object in Construct 3 when using Chrome version 99.0.4844.73 on Android Oxygen OS 11.0.4.1.HD65AA. However, it works fine when wake lock is requested via the demo at https://reillyeon.github.io/scraps/wakelock.html by the same browser and on the same platform (via https://chromestatus.com/feature/4636879949398016).

Is there an issue with Construct's implementation of wake lock?

## Attach a .c3p

https://www.dropbox.com/s/xydj1bt5d4a1n2x/wakelocktest.c3p?dl=0

## Steps to reproduce

Preview project in Chrome on Android.

## Observed result

On start of layout, platform info condition 'Is wake lock supported' returns false. Wake lock cannot be requested successfuly.

## Expected result

Wake lock supported, and able to be requested successfully.

## More details

**Affected browsers/platforms:** Chrome version 99.0.4844.73 on Android Oxygen OS 11.0.4.1.HD65AA

**First affected release:** N/A

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It works fine for me on an Asus ZenFone 8 with Android 12. The support check just tests for the existence of `navigator.wakeLock`, which is exactly the same support check as used by the other link you gave. Since Construct is doing the same thing, I think there must be some circumstances in which support is turned off, maybe depending on permissions or the specific device. Anyway if the API doesn't appear to be there, there's nothing we can do about it.

**Comment by oosyrag** [comment]
I looked into it some more and found that wakelock is only available in secure contexts (https), I had been deploying the web app on my own unsecure web server so it wasn't working. src: https://developer.mozilla.org/en-US/docs/Web/API/WakeLock

Leaving comment for future reference. Thanks for checking, sorry I didn't figure it out myself first.

**Comment by AshleyScirra** [comment]
Yeah, lots of features don't work on insecure HTTP these days. You should always use a HTTPS server even just for testing.
