### ISSUE TITLE
Dictionary row resize cause crash

### ISSUE THREAD

**Issue by henrikszucs** [Scirra/Construct-3-bugs#5579]
## Problem description

Dictionary row resize cause crash in the editor

## Attach a .c3p

in editor

## Steps to reproduce

1. New project
2. Add dictionary in files
3. Resize column
4. Crash

## Observed result

Crash

## Expected result

Resize column

## More details
Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'size') @ TypeError: Cannot read properties of null (reading 'size') at Nib.w8b.pjc (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:60:313) at d.mE (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:15:504) at Array. (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:15:10) at Nib.w8b.dispatchEvent (https://editor.construct.net/r288/main.js:1055:42) at Nib.w8b.Ek (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:56:120) at Nib.w8b.eMb (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:50:275)
Stack: TypeError: Cannot read properties of null (reading 'size') at Nib.w8b.pjc (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:60:313) at d.mE (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:15:504) at Array. (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:15:10) at Nib.w8b.dispatchEvent (https://editor.construct.net/r288/main.js:1055:42) at Nib.w8b.Ek (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:56:120) at Nib.w8b.eMb (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:50:275)
Construct 3 version: r288
URL: https://editor.construct.net/r288/
Date: Tue Mar 29 2022 17:05:30 GMT+0200 (közép-európai nyári idő)
Uptime: 104.3 s

Platform information
Browser: Chrome
Browser version: 99.0.4844.84
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
C3 release: r288 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA Corporation)
Renderer: ANGLE (NVIDIA Corporation, NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2, OpenGL 4.5.0 NVIDIA 512.15)
Major performance caveat: no
Maximum texture size: 32768
Point size range: 1 to 2047
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 99.0.4844.84
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36
C3 release: r288 (beta)
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 137 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA Corporation)
Renderer: ANGLE (NVIDIA Corporation, NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2, OpenGL 4.5.0 NVIDIA 512.15)
Major performance caveat: no
Maximum texture size: 32768
Point size range: 1 to 2047
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Wackytoaster** [comment]
For me the same crash/error happens when I try to open my (main) project without doing anything. Some more testing also seems to cause the same error when attempting to close the array editor.

[arrayeditor.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/8372769/arrayeditor.c3p.zip)

1. open project
2. attempt to close array editor

Here's the error from my main project in case it's a different one because that other project opens fine and does not crash until I do something where my main project instantly crashes.

<details><summary>errorlog</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'size') @ TypeError: Cannot read properties of null (reading 'size') at Nib.w8b.pjc (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:60:313) at d.mE (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:15:504) at Array. (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:15:10) at Nib.w8b.dispatchEvent (https://editor.construct.net/r288/main.js:1055:42) at Nib.w8b.Ek (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:56:120) at Nib.w8b.eMb (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:50:275)
Stack: TypeError: Cannot read properties of null (reading 'size') at Nib.w8b.pjc (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:60:313) at d.mE (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:15:504) at Array. (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:15:10) at Nib.w8b.dispatchEvent (https://editor.construct.net/r288/main.js:1055:42) at Nib.w8b.Ek (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:56:120) at Nib.w8b.eMb (https://editor.construct.net/r288/components/editors/dataEditor/dataEditor.js:50:275)
Construct 3 version: r288
URL: https://editor.construct.net/r288/
Date: Tue Mar 29 2022 17:14:07 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 24.6 s

Platform information
Browser: Chrome
Browser version: 99.0.4844.82
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36
C3 release: r288 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11-30.0.14.9709)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>
