### ISSUE TITLE
Fullscreen Scaling Error

### ISSUE THREAD

**Issue by C3GameDev** [Scirra/Construct-3-bugs#5581]
## Problem description

Fullscreen scaling sometimes uses the full display height with camera area, so some of the UI won't be displayed right!

## Attach a .c3p

https://kkgames.de/test.c3p
APK:
https://kkgames.de/test.apk
APK is build like this: Android Export:
Debug APK 5.1+ simple minify, deduplicate and recompress images

## Steps to reproduce

The apk needs to be started on a big display device (resolution higher than 9:16, for example 9:20).
You need to restart the apk multiple times (I got the error after around 50 restarts, but also once after 5 restarts, so it's random).
Tested on Samsung Galaxy S22 Ultra and Google Pixel 6, both got the issue after several restarts.
The error can also appear after the first start!

## Observed result

https://kkgames.de/fail.jpg
(the bottom ui isn't fully displayed, see the expected result)

## Expected result

https://kkgames.de/nofail.jpg

## More details

**Affected browsers/platforms:** Android

**First affected release:** I'm not sure, but currently using "Release r285.3 stable"

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Can you find a way to more relialby reproduce the problem?

We routinely will have to test if the problem has changed or been fixed 20+ times during development. If we have to do 50 restarts to check, and do that 20 times, that means 1000 checks. As a small company with limited resources we just can't afford to do that. Further if it turns out to be a Chrome/Android/WebView issue, we will not be able to fix it anyway. So reliable steps to reproduce the problem are essential for it to be feasible for us to investigate.

**Comment by C3GameDev** [comment]
Hey,
it's not possible. I've created the simplest way to get the error and have no idea how to manipulate it.
A possible workaround / fix would be a function to get the full display size, than compare it with the size on start up, if it's different, then do new scaling. First 2 steps I can simply do in construct, but I don't see a function for rescaling the game.

**Comment by AshleyScirra** [comment]
Does changing the device orientation fix it?

Construct relies on the browser engine to tell it what the window size is, so if it gets told the wrong thing, it will look wrong and there's not much we can do about it.

**Comment by C3GameDev** [comment]
Hey,
changed the "Orientations" to "Any". Now when the error appears and i rotate the phone to landscape and back to portrait, the error is gone.

**Comment by AshleyScirra** [comment]
I made a change based on some guesswork for the next release. Let's see if that affects anything.

**Comment by C3GameDev** [comment]
Great, thanks a lot. Let me know if I can test anything.

**Comment by C3GameDev** [comment]
Hey,
I've updated to "Release R289 beta" and built a new debug apk. The error still exists.

**Comment by AshleyScirra** [comment]
Too bad.

I'm afraid as described previously, such issues are basically infeasible to fix if they have to be repeatedly tested so many times. If you can find a more reliable way to reproduce the problem, please file an issue with those steps. Otherwise there's no good way to investigate and diagnose the problem.

**Comment by C3GameDev** [comment]
Hey,
I have another fullscreen game which I built on 29th December 2021 (Stable r276.2) and there everything works fine. I did 200 game-starts just to be sure (I get the error around every 20-30 starts) and no error. I've built the same game with the current version (so same code, zero changes, just new Construct Release) and the error appears (around every 20-30 starts).

So it must be something in the update of Stable r285...

**Comment by C3GameDev** [comment]
@AshleyScirra 
I've finished testing:
r271 and also r271.2 and everything below is working fine.
r272.2 has the error (maybe also r272 but I couldn't test the version, since the editor is not working in r272).

So I'm 100% sure it's the r272 or r272.2 where the error appeared first.
In all versions I've tested (over 10 releases tested), the error came between 20-30 starts. In r271 and r271.2 I've restarted over 200 times each and no error.

Hopefully this will help to find the error.

Let me know if I can do anything else.

**Comment by AshleyScirra** [comment]
I'm afraid as I said it's not feasible to investigate problems that need to be tested hundreds of times. It makes it almost impossible to know if any changes we've made have actually fixed it.

**Comment by C3GameDev** [comment]
I can't do more than telling you that it's the r272 update which causes the error, so maybe you can remove some of the changes and give me a new version and I do the testing for you.

But it's very important to fix this issue since otherwise it's not possible to do fullscreen android apps with Construct 3, since almost every user who gets this error will quit... And doing non fullscreen android apps nowadays is not the best idea since most of the smartphones aren't 9:16, but bigger and bigger, like 9:20 and more...

**Comment by C3GameDev** [comment]
Btw. everyone will have this error as soon as they update their projects on google play, so every fullscreen android app made with Construct 3 will be destroyed by this...

**Comment by AshleyScirra** [comment]
I guess it's something to do with the updated handling of the virtual keyboard on Android. However I'm afraid I have no idea what, and if we simply remove the entire feature, it will regress the handling of the keyboard to the old behavior that lots of people asked us to change because it was pretty bad (the keyboard resized the display, which in turn could cause things to become unreadable or unusable). We have to support that.

As it is, there are two options: one is to find a more reliable way to reproduce the problem, which would likely allow us to resolve the issue promptly. The second is to just make wild guesses and hope we solve the problem by chance. That could last months of trying all sorts of different things and has no guarantee it would even find a solution after all that. Hence the focus on the first.

We can still try guesswork though. Is there a setting that affects it? Maybe something to do with the status bar?

**Comment by C3GameDev** [comment]
Hey,
the problem appears on Samsung Galaxy S20+, Samsung Galaxy S22 Ultra, Google Pixel 6 and Google Pixel 5 (these are the only devices I can test at the moment). And normally we wouldn't have recognized the error with simple app updates, it's just because we are intensively testing 2 new apps at the moment and like I said you need around 20-30 restarts in average to get this error shown up.

Some more details I figured out during testing:
On startup, the android's bottom ui (home-button, back-button...) is active for around 2 seconds. As soon as it disappears, sometimes there is something like a flickering (maybe rescaling) and when this happens the error appears (from r272+). On versions below the error doesn't show up but the same kind of "flickering / rescaling" happens, just without the error afterwards.
So maybe it's the top statusbar or the bottom-buttonarea of Android.

I can test more on this, but if you already have any ideas please let me know.

Also another question (maybe for a simple workaround):
Is there a way to request the fullscreen-scaling with an evenhandler or maybe just Javascript so I can test it out without any new release required. Something like the same which happens in the start of the app, just do it like 5 seconds after start or even better as an eventhandler. I think as soon as the statusbar disappeared and you do another rescaling, it should work, similiar to changing the orientation, since this also fixed the issue.

Thanks for the help!

**Comment by AshleyScirra** [comment]
The "Hide status bar" find is interesting. I think that may be causing the view size to change in a way that looks similar to the virtual keyboard appearing. It may not be possible to clearly tell these cases apart. But for the next beta I've tried adding one more hack: it will not treat size changes as the VK appearing for an extra 1 second on startup. It's a pretty bad hack but if the problem is a viewport shift happening just after startup, then that may be enough to ignore that effect. So it will be worth checking again on the next beta.

**Comment by C3GameDev** [comment]
@AshleyScirra 
Thanks a lot! It seems like the error is fixed in r290 (over 50 restarts and the "rescaling" already appeared 2 times without the error, so I guess you can mark it as solved)

**Comment by AshleyScirra** [comment]
OK, thanks for confirming!
