### ISSUE TITLE
Pinned sprite font does not scale

### ISSUE THREAD

**Issue by rraffo** [Scirra/Construct-3-bugs#5592]
## Problem description

Pinned sprite font does not scale

## Attach a .c3p

[pin bug.zip](https://github.com/Scirra/Construct-3-bugs/files/8399097/pin.bug.zip)

## Steps to reproduce

1. see the attached example.

## Observed result

Regular sprite scale as expected
Sprite font does not change scale.

## Expected result

Sprite font should scale like the regular sprite

## More details

tested using Chrome

**Affected browsers/platforms:** 

R287

## System details

Windows 10

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Scaling text/spritefont is not implemented for the Pin behavior. Architecturally it's complicated as the engine does not have a built-in way of knowing the parent/child relationship - it's all independently implemented within the Pin behavior.

This is the exact problem hierarchies solve, and it works if you use "Add child" instead. I would recommend using that anyway as it's essentially the modern replacement for the Pin behavior, which has a bunch of other quirks that are fixed by hierarchies.
