### ISSUE TITLE
number fields support up and down arrows for fine adjustment

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5607]
## Problem description

This is an enhancement suggestion,   extended from this thread.
https://github.com/Scirra/Construct-3-bugs/issues/5493

It is recommended to support up and down Arrows for fine adjustment at number fields. This will be more precise than the mouse drag

## Expected result

![Snipaste_2022-04-07_14-55-00](https://user-images.githubusercontent.com/45864744/162138261-420f6fde-c00a-4645-a598-aad095d19df1.png)

When I focus on the X fields, press the up arrow the value +1. Press down arrow the  value -1.
  
  
You might say that want to keep current desigin can jump to the beginning and end. Then you can jump on the first press and fine-tune on the second time.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
HTML does not provide an explicit way to provide spinners. The browser shows them only in certain cases with certain styles and with certain limitations.

In this case we cannot support both spinners and expression compute (e.g. typing `100 * 2` to get `200`). Calculations seem more important, so we support that instead of showing spinners.
