### ISSUE TITLE
Bullet bounce off differs depending on the frame rate when gravity is used

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#5617]
Run the example and observe the flight pace of the bullet, then change the framerate mode to unlimited and check again.

Observed result: Flight path is very different.

Expected result: Path should be the same

This only happens when the bullet has gravity, otherwise the path is consistent across framerates

Example:
[gravityBulletPathFrameDependecy.zip](https://github.com/Scirra/Construct-3-bugs/files/8459398/gravityBulletPathFrameDependecy.zip)

**Comment by F3der1co** [comment]
ROJOhound did some additional tests on this topic:

1."Here is a test to see if and why the bounce is different depending on the framerate.  I recreated the motion with events and had each red ball use a different dt.  Basically simulating 30, 60 and 90fps.  I found on flat areas it bounced pretty consistently but on corners it varied a lot.  Basically where the ball is when it collides with the corner will change the bounce a lot. 
I think the bounce could be made more consistent if the ball was moved back on it's path till it was exactly touching the edge of the wall before bouncing."
[bullet_test_2.zip](https://github.com/Scirra/Construct-3-bugs/files/8462298/bullet_test_2.zip)

2."Here's my attempt at moving the ball to the point of collision.  At least accurate to around 10^-14 pixels."
[bullet_test5.zip](https://github.com/Scirra/Construct-3-bugs/files/8462306/bullet_test5.zip)

**Comment by AshleyScirra** [comment]
The bounce angle calculation is only an estimate. It has to basically make a guess since the engine does not necessarily know the normal angle of the surface (which could be a combination of several overlapping objects). The engine is also based on stepping instances per frame, and so the guess can be influenced by the precise values of `dt` (delta-time), which varies depending on the framerate. So the bounce angle is indeed a framerate-dependent estimate.

That may not be ideal but unfortunately I don't know how to improve it - as I said the true value of the surface normal is not known, and may not be calculatable in all circumstances, such as with overlapping objects, and so the engine just makes an estimation. Estimations vary depending on the circumstances. Perhaps some completely different algorithm could do a better job. But then that may fail in other edge cases too, and the endless nightmare edge cases of the Platform behavior make me think that is a likely outcome. Further changing it could end up a breaking change - suddenly lots of projects relying on the old behavior act differently. So I think this is just a quirk we have to live with.
