### ISSUE TITLE
C3 R290 crash report

### ISSUE THREAD

**Issue by rraffo** [Scirra/Construct-3-bugs#5630]
## Problem description

While exporting an HTML5 project C3 crashed unexpectedly.

## Steps to reproduce

I'm not able to reproduce the problem.
I think that while C3 was saving a local automatic backup of the project  I clicked the HTML5 icon and a crash has been generated.

## More details

**Affected browsers/platforms:** 

C3 R290, please check the details below.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: blob:https://editor.construct.net/c513587a-e5fe-4361-9fbe-b6f19f36046a, line 1918, col 3
Message: Uncaught NetworkError: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://downloads.scirra.com/cheerpj-runtime/20201027b/jni.js' failed to load.
Stack: null
Construct 3 version: r290
URL: https://editor.construct.net/r290/
Date: Thu Apr 14 2022 21:31:54 GMT+0200 (Central European Summer Time)
Uptime: 6635.9 s

Platform information
Browser: Chrome
Browser version: 100.0.4896.88
Browser engine: Chromium
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36
C3 release: r290 (beta)
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
It looks like a problem with your Internet connection caused a script to fail to load. I was able to reproduce it by putting a block on that URL so the same request would fail.

Unfortunately it fails in third-party code used by the minifier which we can't easily modify, and the manner in which it fails doesn't appear to be detectable so we can't add a better way to handle it. I tried making Construct ignore the crash, but it then just gets stuck exporting if you enable the minifier, which seems like it could actually be worse, since at least the crash report dialog lets you save the project so you can preserve your latest changes. So sadly I don't think there's any better we can do here.
