### ISSUE TITLE
Spawned Spritefont text does not change

### ISSUE THREAD

**Issue by rraffo** [Scirra/Construct-3-bugs#5676]
## Problem description

The spawned spritefont that is hierarchically linked to a dummy object keeps the default text and the request to change the text has no effect.
## Attach a .c3p

[spawned_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/8626277/spawned_bug.zip)

## Steps to reproduce

1. run the project
2. click the green box
3. the yellow spawned box will appear with the linked sprintefont text

## Observed result

the text of the spawned spritefont does not change and the default text appear

## Expected result

I do expect the text change as requested in the event
## More details

**Affected browsers/platforms:** 
tested on Chrome windows platform

**First affected release:** 
C3 R293.2
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is more or less by design at the moment: nothing in that event picks a SpriteFont, and newly created instances aren't fully created until the next top-level event, so the newly created SpriteFont can't be used until then. (It should work if you set its text in 'On created' though.) I think this probably ought to work though: 'Create object' picks the instance of the object you give it, but when using the newer 'Create hierarchy' option, nothing else in the hierarchy is picked, which makes it difficult to modify them after creation. I think it makes sense to change that and have the hierarchy picked too.

**Comment by rraffo** [comment]
Great news! thanks.
