### ISSUE TITLE
(Tween Behavior) Tag Parsing Issue

### ISSUE THREAD

**Issue by Tokinsom** [Scirra/Construct-3-bugs#5679]
## Problem description
When checking if a tween tag is playing, only one word from a tag needs to match instead of the entire thing. This suggests some sort of tag parsing issue.

e.g. If I tween "fade one" or "fade two" then a condition checking if only "fade" is playing still works. This extends to the action as well e.g. setting an object's opacity to Self.Tween.Value("fade") will grab the value of either "fade one" or "fade two".

## Attach a .c3p
[tween naming bug.zip](https://github.com/Scirra/Construct-3-bugs/files/8643667/tween.naming.bug.zip)

## Steps to reproduce

1. Preview the .c3p
2. Press 1 on your keyboard and observe the square fading
3. Press 2 on your keyboard and observe the square fading

## Observed result

The square fades

## Expected result

The square should not fade at all because the "fade" tween is never executed - only "fade one" and "fade two" are.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** I think this bug has always existed. I've worked around it for a long time by giving tweens wholy unique names but it is becoming a real issue now.

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 101.0.4951.54
Browser engine: Chromium
Context: webapp
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36
C3 release: r293.3 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 94 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by UbruPro123** [comment]
Hi I am not sure about it but I have state like this:

For the first time it is ok I am in menu and going to game -> exit game and go back to menu OK
For the second time when I want to go back to menu there remains zoomed layer "map" (from previous menu action it is ok) however it should be reset after going back to menu but there is error, whole app freeze... so I think it would be related to this issue because I am using tween for layer attribute.
No change in project at my side and I already tested it in previous stable 285.3 and it works OK. So please fix new stable 293.3 release !!!

![error](https://user-images.githubusercontent.com/44697344/167225845-c2643290-6fb6-4027-b33a-5a4d1f1fa8a4.png)

I do not know more info.

**Comment by AshleyScirra** [comment]
I think this is by design. As noted in the [Tween manual entry](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/tween), you can use multiple space-separated tags:

> Tweens can also be given multiple tags, separated by spaces. Actions which affect a tween will only affect tweens that match all of the given tags.

I think expressions allow retrieving a value for any tween that has one of the given tags. I'm not sure of the intention here - @DiegoScirra should be able to comment further.

**Comment by DiegoScirra** [comment]
@Tokinsom From what you describe the feature seems to be working as expected.

Tweens can be given multiple tags in a space separated list.

If you tag a tween as "fade one", you are giving it two tags "fade" and "one". A trigger could then use the tag "fade" or "one" to refer to that tween. In the case of multiple tweens having the same tags, you would need to provide more unique tags to match a specific one.

In your example, the behaviour makes sense, because both tweens are tagged with "fade", so both are matched by the condition. Tween tags work this way in all places where they are involved.

The documentation needs to be updated because it's not very clear on the subject.

**Comment by avishaymizrav** [comment]
> @Tokinsom From what you describe the feature seems to be working as expected.
> 
> Tweens can be given multiple tags in a space separated list.
> 
> If you tag a tween as "fade one", you are giving it two tags "fade" and "one". A trigger could then use the tag "fade" or "one" to refer to that tween. In the case of multiple tweens having the same tags, you would need to provide more unique tags to match a specific one.
> 
> In your example, the behaviour makes sense, because both tweens are tagged with "fade", so both are matched by the condition. Tween tags work this way in all places where they are involved.
> 
> The documentation needs to be updated because it's not very clear on the subject.

It would be great if we could have this on audio tags, just saying :)

**Comment by Tokinsom** [comment]
Ahhh okay. _Somehow_ after all this time I never read the description explaining the space-separated tween tags - I just viewed them the same as timer, audio, etc.  Using camel or snake case for my tweens from now on should fix the "issue" then.
