### ISSUE TITLE
Sprite Font Formatting Bug in the v.294

### ISSUE THREAD

**Issue by 1mrpaul1** [Scirra/Construct-3-bugs#5694]
## Problem description

when setting text from array into sprite font it is loosing formatting

[TextDoc.zip](https://github.com/Scirra/Construct-3-bugs/files/8669400/TextDoc.zip)

<worked normal in 293.3 but was broken in 294-->

## Steps to reproduce

just add some text with newline code from array

## Observed result
![Wrong Formating](https://user-images.githubusercontent.com/64515864/167837906-6aa6057e-378a-433d-9481-7dea3cb3d0d5.png)
wrong formatting without wrap to next line

## Expected result
![RightFormating](https://user-images.githubusercontent.com/64515864/167837960-a0380ba7-467a-4392-b7de-70421c420c3d.png)

formatting with wrap to next line

**Comment by AshleyScirra** [comment]
The problem is the text uses `\r\n` for newlines, when you only need `\n`. (I'm not sure why you'd be using `\r\n` - I think that is only relevant for old bits of Windows and has never been needed on the web or other platforms...) I think this previously only worked by accident, breaking on `\n` and leaving a dangling `\r` on the previous line. A change to better handle languages/emojis in #5622 appears to group \r\n as a single character, which means it's no longer recognised as a single newline character by the word wrap engine. I've updated it for the next beta to also recognise `\r\n`, but I would advise just using `\n` anyway to avoid any other compatibility problems - and it will also work around the problem in r294.

**Comment by 1mrpaul1** [comment]
> I've updated it for the next beta to also recognise

thank you Ashley
