### ISSUE TITLE
Timelines - cubic bezier overriding linear ease

### ISSUE THREAD

**Issue by Ldwebster111** [Scirra/Construct-3-bugs#5696]
## Problem description

It appears that when a timeline is set to cubic bezier path mode, the ease is being affected by the position of the handles, even when linear is selected in the ease mode.

## Attach a .c3p

[cubic bezier path.zip](https://github.com/Scirra/Construct-3-bugs/files/8669563/cubic.bezier.path.zip)

## Steps to reproduce

1. Play the c3 file.
2. Alternatively, go into edit mode and observe that the two timelines are effectively the same, with the only difference being the handle length of short vs long (gif below)

## Observed result

Neither sprite moves at a linear speed along the timeline, instead being affected by the handle length of each node in the timeline edit mode, speeding up and slowing down between the keyframes.

## Expected result

As both sprites move the same distance over the same time, I feel like they should move at the same speed across the timeline, effectively staying neck and neck through the whole thing. This would align with expectations around using 'linear' as an ease, and reflect how that ease is supposed to function. In my mind, there should be no speed up or slow down during the linear ease.

The reason I found this out is I'm trying to do a flyover of a level and timelines are a good fit. However, due to this problem, it's actually really difficult to get a smooth sweeping camera motion using this method. I'm hoping it's an actual bug and can be fixed, as otherwise it makes timelines quite difficult to work with when trying to make finer curves.

## More details

![image](https://user-images.githubusercontent.com/46861823/167842746-8cefc898-f704-451f-8bea-30a16c5cfb91.png)

![cubic bezier](https://user-images.githubusercontent.com/46861823/167842885-5e16feaf-ea1d-4f2c-a4ae-6dd95277c55f.gif)

**Affected browsers/platforms:** 

Chrome stable, win 10

**Comment by Ldwebster111** [comment]
Hi Diego, the only reason I used a straight line in the example above was to demonstrate that both sprites are not moving at a consistent rate, as would be expected with a linear ease. The actual issues I'm having with this relate to curved lines.

I had the thought that perhaps I could avoid this by use the moveTo behaviour and just have the sprite move along the timeline at a consistent speed, but when this is done the timeline path is treated like a line rather than a curve (perhaps a separate issue)?

**Comment by Ldwebster111** [comment]
Here's an example with a curve. If you watch closely, you can see that it noticeable slows down the closer it is to the key frames.

![curve2](https://user-images.githubusercontent.com/46861823/167956378-7566b74c-62fe-4a80-9480-93c998c8494b.gif)

While it may not look like a big deal at first, once you add camera scrolling and a background in there, it becomes pretty noticeable, even with a lot of tweaking of curves and node placement. 

While that's maybe a bit of

**Comment by DiegoScirra** [comment]
I think the problem here is that tweens are time based. The instance needs to change it's movement rate in order to make it in time to the end position, that is the change in speed you are noticing.

Moving on a straight line using a linear ease produces a uniform motion, because it is the shortest distance and the steps are consistent along the way. In the case of a curve, the path is always longer than a straight line but the distance must still be covered in the same time, this produces steps along the way which are not consistent, some are shorter and some might be longer.

This isn't something that can be fixed, it's just how time based animations work.

You were right to think about using the MoveTo behaviour, that would sort out your problem, because the movement would not be time based, but rather speed based. That would mean you could move along the curve at a constant speed, it would take longer to complete the path, but the speed would be constant. Unfortunately, moving along a bezier curve using the MoveTo bhaviour is not yet supported.

I have been thinking of implementing it, but there are always things to do, so I can't really say when it will be done.

**Comment by Ldwebster111** [comment]
Okay, I might drop it for now and leave things as is. If I know there's a potential workaround coming at some point in the future then that's enough for me.

Thanks for the response.

**Comment by DiegoScirra** [comment]
Closing this now as there is nothing to do about it.
