### ISSUE TITLE
My game won't start on Android since version 295

### ISSUE THREAD

**Issue by KabutoJRM** [Scirra/Construct-3-bugs#5729]
Hi, I am starting a new game and it works perfectly on PC but when I run it on android mobile it freezes on the C3 splash screen. Until the beta version prior to 295 it went without problems and worked perfectly, the project is very small because I just started this game.

[Umi Liberator DX.zip](https://github.com/Scirra/Construct-3-bugs/files/8764384/Umi.Liberator.DX.zip)

**Comment by AshleyScirra** [comment]
I'm afraid the project uses third-party plugins which we don't accept for bug reports:

- Plugin Firebase Auth Basic (Sparsha_FirebaseAuth) by Sparsha
- Plugin Firebase RD Basic (Sparsha_FirebaseRealtimeDatabase) by Sparsha
- Plugin Firebase SDK (Sparsha_FirebaseSDK) by Sparsha
- Effect Rainbow Shimmer (Mikal_RainbowShimmer) by Mikal

Since the problem could be caused by one of these addons, we need a project not using any third-party addons to prove the problem is with Construct. Please see the bug report guidelines where this and further details are covered; it is required for us to be able to help you.

**Comment by KabutoJRM** [comment]
Hi Ashley, thank you very much for answering so quickly, I removed both add-ons from the project but it still gives me the same error. I attach new C3P file.

[Umi Liberator DX W-addons.zip](https://github.com/Scirra/Construct-3-bugs/files/8765052/Umi.Liberator.DX.W-addons.zip)

**Comment by AshleyScirra** [comment]
Please file a new issue following all the guidelines. For example you have not provided any steps to reproduce, so I don't know whether you're using Remote Preview, Chrome on Android, an APK, what your export settings are, etc. Without that information I can't follow what you're doing. Please always follow the bug report guidelines, we can't help if you skip all the requested information.
