### ISSUE TITLE
Press and hold the screen causes the page to be 'selected' on iOS.

### ISSUE THREAD

**Issue by renatofd** [Scirra/Construct-3-bugs#5743]
## Problem description

Press and hold the screen causes the page to be 'selected' on iOS. All the game area is selected as it was a text.

## Attach a .c3p

It happens with any project.

## Steps to reproduce

Tap and hold the screen, all the game area will be selected.

## More details
I tried a solution that I found here: [https://stackoverflow.com/questions/826782/how-to-disable-text-selection-highlighting](url)
So I added the following lines inside the **html, body, canvas {}** in the style.css file:
        webkit-touch-callout: none; /* iOS Safari */
        webkit-user-select: none; /* Safari */
        khtml-user-select: none; /* Konqueror HTML */
        moz-user-select: none; /* Old versions of Firefox */
        ms-user-select: none; /* Internet Explorer/Edge */
        user-select: none;

But it doesn't worked. 

Here is a video of the issue in one game:
https://user-images.githubusercontent.com/11575441/170774141-8eb81cdc-87b8-4cf8-af10-d63ca71d966f.MP4

**Affected browsers/platforms:** 

IOS 15.4.1

**Comment by AshleyScirra** [comment]
No project was provided so I tried Space Blaster. I cannot reproduce the problem: it never tries to select the canvas either by Remote Preview or after a web export.

The provided video shows the game running on a different host. If they do something like iframe the game or apply their own styles, it may be that the changes made by that website are causing the problem. In that case you will need to report the problem to the website. Otherwise please follow the bug report guidelines and ensure your steps to reproduce the problem work otherwise we cannot help.
