### ISSUE TITLE
Animation is not playing bug

### ISSUE THREAD

**Issue by TecenGOD** [Scirra/Construct-3-bugs#5745]
## Problem description

Using the "stop animation" action is triggered, and "is playing - false" is displayed in debug mode, but we can't get it in the code. The inverted action "animation does not play" does not work properly.

## Attach a .c3p

.c3p link - [https://www.dropbox.com/s/sdzqpu15wtg3yzf/animationBugC3.c3p?dl=0](https://www.dropbox.com/s/sdzqpu15wtg3yzf/animationBugC3.c3p?dl=0)

## Steps to reproduce

1. Run the attached .c3p
2. Press J to stop the animation.
3. Animation has stopped, but the condition "animation is not playing" does not work

## Observed result

![image](https://user-images.githubusercontent.com/7480088/170867686-18ae08dc-e383-4ce7-8b20-8816c2c14d0b.png)

## Expected result

![image](https://user-images.githubusercontent.com/7480088/170867982-29806bfb-d7da-42ad-ae95-19aaf4d97e1f.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

![image](https://user-images.githubusercontent.com/7480088/170868032-f36bed51-970a-45de-bafc-191788811a5c.png)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by dop2000** [comment]
I think "Is playing" is a confusing condition name, because it doesn't supposed to test if an animation is actively playing or paused or stopped. It should actually be named "Is current animation".
And I agree, it is odd that there is no way to check if an animation is stopped.

**Comment by AshleyScirra** [comment]
This is actually by design. The naming isn't great, but it checks "is the current animation set to the given animation name", which in this case it is regardless of whether the animation is playing or not.

This condition has worked this way for at least several years. Changing how it works will probably cause backwards compatibility problems, and even just renaming it may break years worth of documentation, tutorials and lesson plans. I think it is a quirk we will have to live with.
