### ISSUE TITLE
Set animation speed bug

### ISSUE THREAD

**Issue by TecenGOD** [Scirra/Construct-3-bugs#5746]
## Problem description

At the end of the first animation, we turn on the second animation and set the second animation "Animation Speed" to 0. But the action does not work as expected.

## Attach a .c3p

.c3p link - https://www.dropbox.com/s/7ndzr7mg8zewmyo/animationSpeedBugC3.c3p?dl=0

## Steps to reproduce

1. Run the attached .c3p
2. After the end of the first animation, we expect the second animation to turn on at a speed of 0

## Observed result

![image](https://user-images.githubusercontent.com/7480088/170868307-5d186a1f-1a14-4c97-973a-b338bf6fd99a.png)

## Expected result

![image](https://user-images.githubusercontent.com/7480088/170868373-0c4febb1-d718-4fd2-ad9a-10b4e6ea63d8.png)

## More details
![image](https://user-images.githubusercontent.com/7480088/170868401-a09c5eca-67ac-4d47-9309-37330c2f2416.png)

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The problem is that changing animation in "On animation finished" does not actually immediately change the animation: it waits until the next tick and then sets the animation. I remember changing it to do that, but I've forgotten the reason why. I think it was to fix a difficult crash bug, or some unexpected behavior of events in other cases. Then when the animation really changes, it sets the default animation speed, therefore overriding the 'Set animation speed' action in this case.

I don't want to change 'Set animation' to work immediately as I am sure we will just regress whatever issues were meant to be solved by the original change. Changing how it works in such a fundamental and widely used feature will have extremely high backwards compatibility risk. So I'm not sure how it would be best to handle this.

**Comment by avishaymizrav** [comment]
@AshleyScirra I was thinking of suggesting it a few times, but it wasn't that important so I let it go.

What about adding a parameter to the "set animation" action to set the speed?

Something like a tick box for "use default animation speed" that will be ticked by default and when you untick it you can input an alternate speed value.

**Comment by AshleyScirra** [comment]
This appears to be a rarely-encountered issue that could prove difficult to fix without breaking thousands of existing projects going back years. I think it is better to leave it - it's a bit of a quirk but I think we can live with it.
