### ISSUE TITLE
Double bug - calculation retuns NaN - NaN saved as hsl param corrupts save file.

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#5763]
## Problem description

The first issue is that this calculation return NaN:
4+player.coolDown*(12/player.coolDownTotal)
Both the varibles are set to 0 in this case.

The second bug is that if you save the game (official save actions) with HSL param set to NaN, it will fail to load, the game will get stuck and the save file will get corrupted.

## Attach a .c3p

[calcAndHslBugs.zip](https://github.com/Scirra/Construct-3-bugs/files/8835737/calcAndHslBugs.zip)

## Steps to reproduce

1. Run capx.
2. Click save.
3. Click load.
4. Look at console log.

## Observed result

Calculation returns NaN.
Effect param accepts NaN.
Load fails, game is stuck.

## Expected result

I don't see why the calculation shouldn't work and return Nan, am I missing somthing?
Either way, maybe effect param shouldn't accept NaN or overwrite it with 0.
Maybe even the loading process shouldn't break the game on something like this, just don't read the value if it's incompatible.

## More details

**Affected browsers/platforms:** Chrome/NWjs

**First affected release:** Not sure.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
In your first calculation if both variables are set to 0, you are dividing by 0, which results in NaN. After that, the whole thing will evaluate to NaN.

**Comment by AshleyScirra** [comment]
Dividing by 0 actually results in Infinity; doing 0 * Infinity results in NaN. That is not a bug, it is the correct result of the calculation.

The second issue is because, rather frustratingly, JSON actually doesn't support NaN or Infinity, so they turn in to null. The loading code didn't handle that correctly; I've fixed it for the next beta to turn null in to NaN (which will change the value of Infinity, but I suspect that's not a useful effect parameter anyway).
