### ISSUE TITLE
If functions with the same parameter name are placed in a group they cannot drag

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5803]
## Problem description

If functions with the same parameter name  in a group and use they in the dictionary they cannot drag.

![Snipaste_2022-06-21_11-38-38](https://user-images.githubusercontent.com/45864744/174711218-4ffc6827-12da-425d-ac6d-cc1429fb85a2.png)

![Snipaste_2022-06-21_11-40-01](https://user-images.githubusercontent.com/45864744/174711406-e2029679-8b4b-4d39-afc7-ee82b12c54a3.png)

But can drag the event block
![8](https://user-images.githubusercontent.com/45864744/174710724-4af4ccad-0314-4d6a-8d78-1fe526c9356f.gif)

## Attach a .c3p

[same-parm-dict-issue.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/8945592/same-parm-dict-issue.c3p.zip)

## Steps to reproduce

1.  Add 2 Function,  same parameter name (a, b)   
2.  Dictionary: Add key {a} with value {b}  
3.  placed 2 function the same group.  
4.  drag the group  

## Observed result

Cannot drag events here

## Expected result

Normal drag

## More details

**Affected browsers/platforms:** Chrome, Windows

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r298 (beta)
Browser: Chrome 102.0.5005.115
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 1.7 gb (2.9%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The code to resolve variable names during drag&drop is exceptionally complicated and these cases are always tough.

I think this is a regression caused by the fix to #5760: if variable names match in a drag&drop, they get renamed to avoid name collisions. However in these cases the variable names do not actually collide, but they get renamed anyway, and then events referencing them cannot be resolved.

I've made a change that I think fixes the function parameter case - those can be handled more easily as it's clear that function parameter names don't collide with anything outside the function block. However the local variables in sub-events in the second case is much tougher. I don't think it's feasible to fix, the code is just too complicated, and if it is done wrong it risks variable name collisions which corrupts the project (as was the case in #5760). However they can still be moved one at a time, or via copy/paste instead (which works somewhat differently internally), so it seems at best only a minor inconvenience in specific cases, so I don't think it's worth the trouble to fix.
