### ISSUE TITLE
Pathfinder cuts corners and gets itself stuck

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#5807]
## Problem description

Pathfinder cuts corners and gets itself stuck

## Attach a .c3p

[PathfidnerCutCornersAndStuck.zip](https://github.com/Scirra/Construct-3-bugs/files/8953035/PathfidnerCutCornersAndStuck.zip)

## Steps to reproduce

1. click the moveToTarget button (don't click anywhere else)
2. observe the object cutting the corner (which it shouldn't based on the cell border settings)
3. after the object arrived click anywhere to find a path to the mouse position
4. the Pathfinder can't find a path

## Observed result

Pathfinder cuts corners and gets stuck

## Expected result

pathfinder doesn't cut the corner and doesn't get stuck. If the pathfinder can find a way to a point it should also be able to find a path away from that point.

**Comment by AshleyScirra** [comment]
If you display the pathfinding map you will see it leaves only a tiny path through:

![image](https://user-images.githubusercontent.com/768723/175006932-2b81a903-1acf-4eb2-b8d9-95827f37a59a.png)

As with most behaviors it doesn't work well in extreme circumstances like this - it's designed to work with reasonable spaces and tolerances.

Its movement also cuts corners by design. In a way it has to: if the movement directly moves over every waypoint, then depending on the turn speed it can massively overshoot turns that it should obviously have made earlier. So it makes a guess at the extent it can cut the corner. It is a very difficult problem to solve and it doesn't always work perfectly, and having worked on this for years I'm not sure it's possible to design a method that works perfectly in all cases. If you want to try designing your own movement, you can access the list of node positions returned by the pathfinding behavior, and implement your own movement, e.g. with the Move To behavior. That will probably work better than the built-in movement especially if you have set the rotation speed to be essentially instant rotation.

**Comment by F3der1co** [comment]
I see, interesting. Thank you for the answer!

Some additions:
- a simple way to avoid the cutting of corners is to have the object move to the node, stay and rotate. Once rotated to the next node, start moving. This obviously would look more mechanically and might not be desired depending on the use case.

- the rotation speed etc. are not really relevant, I just put them to extreme values to figure out why this happens.

- I totally understand that this is a case with tight tolerances, but still not an unrealistic case. Assuming you don't want the sprite to ever visually clip (in theory without corner cutting) you would need a cell border of the diagonal of the rectangle of the Sprite/2.
Another case where it could happen is with a more free-form level design or generated levels, even if the tolerances are wider in general there still might be cases like this. So making sure there can never be a tight tolerance anywhere could be a lot of extra work, especially as this is something you might not realize is nescessary to avoid. 

**The corner cutting bug is not that important imo. But that it can get stuck is a high severity/game breaking bug imo and can happen in other cases that are not super tight corridors, like I described above.**

**Comment by F3der1co** [comment]
I'm not sure I understand, doesn't the timeline and tween ease curves decelerate to an relatively exact position?

Maybe I'm underestimating the tolarance on how far it can be off the target position. But couldn't it just snap to it on arrive.
