### ISSUE TITLE
destroying an overlapping object doesn't trigger is not overlapping

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#5841]
## Problem description

destroying an overlapping object doesn't trigger is not overlapping

## Attach a .c3p
[notOverlappingDestroy.zip](https://github.com/Scirra/Construct-3-bugs/files/9018845/notOverlappingDestroy.zip)

## Steps to reproduce

1. drag the left rectangle over the right one

## Observed result

object changes opacity on collision and stays

## Expected result

object instantly changes opacity back to 100% as after the destruction it is not overlapped anymore (no change in opacity should be seen)

**Comment by AshleyScirra** [comment]
This is currently by design: if no instances of an object exist, conditions for that instance are not checked because there's no instance to check with. This happens because the check is done on the *drag* object - if you switch it around to say "Sprite is not overlapping drag", it works because there is an instance of Sprite to check. You could argue it kind of makes sense, as if no instance exists, the answer to "does it overlap something?" is not yes, and not no, it's more like "not applicable".

In theory we could change this to make an exception for this case, but not only would that make this condition inconsistent with the way other conditions run, I also fear it would be a major breaking change, as thousands of existing projects suddenly start to run negated overlap events where they previously didn't run. So I don't think it's worth the trouble of altering this.
