### ISSUE TITLE
Undo redo text bug

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#5879]
## Problem description

After removing the text and manipulating `Redo` and `Undo`, it turns out that I have text with an effect that I did not impose.

## Attach a .c3p

[undo_redo_text_bug_r302s.zip](https://github.com/WilsonPercival/WilsonPercival/files/9109298/undo_redo_text_bug_r302s.zip)

## Steps to reproduce

1. Create a new project.
2. Go to the event editor.
3. Add a text object.
4. Remove it.
5. Add an effect to it.
6. Go to the layout editor.
7. Press the `Undo` button 3 times.
8. Click the `Redo` button.

## Observed result

![bug](https://user-images.githubusercontent.com/91274932/178920570-b486be59-ef30-4bd9-8f9f-39657224c645.gif)

## Expected result

After pressing `Redo` the text has no effect.

## More details

This works with text, but doesn't work with sprites. If you delete the sprite, the properties window will immediately disappear.

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r302s

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r302 (stable)
Browser: Chrome 103.0.5060.114
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 220 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0, igdumdim64.dll)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_float_blend
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
EXT_sRGB
KHR_parallel_shader_compile
OES_element_index_uint
OES_fbo_render_mipmap
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by GameSoul7Eugene** [comment]
After some testing, I discovered that this issue is not unique to the **Text** plugin. Here is a further list of plugins for which the properties window doesn't immediately disappear after deleting them:

## Plugin list
[Button](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/button)
[File chooser](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/file-chooser)
[HTML Element](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/html-element)
[iframe](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/iframe)
[List](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/list)
[Progress bar](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/progress-bar)
[Slider bar](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/slider-bar)
[Text input](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/text-input)
[Shadow light](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/shadow-light)
[SVG Picture](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/svg-picture)
[User Media](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/user-media)
[Video](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/video)
[Drawing Canvas](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/drawing-canvas)
[Twitter](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/twitter)

## Additional information
An instance variable can be added to a deleted object while its properties are still visible. If you do this and twice press the Undo button, Construct will crash and display the following message:

**Error report information**
Type: unhandled rejection
Reason: Error: cannot undelete active project object @ Error: cannot undelete active project object at d.hi (https://editor.construct.net/r302/projectResources.js:523:16) at d.hi (https://editor.construct.net/r302/projectResources.js:625:367) at d.Ki (https://editor.construct.net/r302/projectResources.js:522:409) at d.Ki (https://editor.construct.net/r302/projectResources.js:607:168) at RL.IG.pf (https://editor.construct.net/r302/projectResources.js:1755:76) at window.Ac.Yh (https://editor.construct.net/r302/projectResources.js:1752:19) at d.Yh (https://editor.construct.net/r302/projectResources.js:1634:95) at window.C$a.Yh (https://editor.construct.net/r302/main.js:2351:91) at hi.g.J.oj.qhb.gea [as anb] (https://editor.construct.net/r302/components/misc/mainMenu/mainMenu.js:22:480) at Xh (https://editor.construct.net/r302/main.js:394:253)
Stack: Error: cannot undelete active project object at d.hi (https://editor.construct.net/r302/projectResources.js:523:16) at d.hi (https://editor.construct.net/r302/projectResources.js:625:367) at d.Ki (https://editor.construct.net/r302/projectResources.js:522:409) at d.Ki (https://editor.construct.net/r302/projectResources.js:607:168) at RL.IG.pf (https://editor.construct.net/r302/projectResources.js:1755:76) at window.Ac.Yh (https://editor.construct.net/r302/projectResources.js:1752:19) at d.Yh (https://editor.construct.net/r302/projectResources.js:1634:95) at window.C$a.Yh (https://editor.construct.net/r302/main.js:2351:91) at hi.g.J.oj.qhb.gea [as anb] (https://editor.construct.net/r302/components/misc/mainMenu/mainMenu.js:22:480) at Xh (https://editor.construct.net/r302/main.js:394:253)
Construct version: r302
URL: https://editor.construct.net/
Date: Fri Jul 15 2022 08:35:09 GMT+0300 (Eastern European Summer Time)
Uptime: 40.3 s

Platform information
Product: Construct 3 r302 (stable)
Browser: Edge 103.0.1264.49
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.49
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA NVS 5200M Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

**Comment by AshleyScirra** [comment]
The actual bug happens at step 4: the Properties Bar should clear if you delete the thing it's showing properties for, but in this case it does not. Using any of those properties is accessing a deleted object which is invalid. The next beta properly clears the Properties Bar when deleting an object type, which prevents any invalid access to it after deleting.
