### ISSUE TITLE
Importing image from outside, the frame order not sort by folder filename.

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#5892]
## Problem description

folder: 
![Snipaste_2022-07-18_20-08-30](https://user-images.githubusercontent.com/45864744/179508069-41ed964f-f0ff-4565-99c5-bc5d65273fd7.png)

If I Ctrl + A select all in Folder and then click any one and drag to C3.  

animation editor frame: 
![Snipaste_2022-07-18_20-09-46](https://user-images.githubusercontent.com/45864744/179508196-ee6caa1d-1770-4932-be18-0a103d975063.png)

E.g. i drag  the 'black'  into C3. it will put the ‘black’ as the first, not the first of the filename ‘01.png’

## Attach a .c3p

[issue.zip](https://github.com/Scirra/Construct-3-bugs/files/9131727/issue.zip)

## Steps to reproduce

1. in external folder, Ctrl + A select all image file.
2. click one file and drag to C3 animation editor.
3.

## Observed result

Sort by first file dragged  

Original file:  0 1 2 3 4 5   
If select all (Ctrl + A), and click ‘3’ and drag to C3. frame ordering:  3 4 5 0 1 2

## Expected result

Sort by filename  
0 1 2 3 4 5

## More details

**Affected browsers/platforms:** Chrome r103 / Windows 11

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r302 (stable)
Browser: Chrome 103.0.5060.114
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 189 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 Super with Max-Q Design Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
@XHXIAIEIN

Currently C3 doesn't do any kind of sorting when you drag and drop files into the Animations editor. In the case of Windows, after making a selection and dragging the files, the particular file you chose to drag becomes the "privot" of the group and the list the browser picks up is in relation to that one file.

In your case if you make the selection and drag by **01.png**, then the files will be imported in the order you are expecting. 

@AshleyScirra This is how the browser works, so I am not sure if I should override what it is doing. Specially because a lot of people might be expecting this behaviour.

**Comment by AshleyScirra** [comment]
@DiegoScirra - didn't you make some other change recently where imported files are sorted alphabetically to solve the same problem in another case? I think it makes sense to sort before import, since files named things like 001.png, 002.png are commonly used and those ought to import in the number sequence and not some sequence that Windows decided.

**Comment by DiegoScirra** [comment]
This will be included in the next beta. Files will automatically be sorted in numerical and ascending order by default, but only in the case all the imported files have numerical names, otherwise no sorting will happen.

The bulk importer will follow the same rules, unless a different behaviour is specified by using a configuration file.

Revision 17575
