### ISSUE TITLE
Auto-completion issues after update with half-way editing

### ISSUE THREAD

**Issue by jaydonteh** [Scirra/Construct-3-bugs#592]
## Problem description

Sometimes you want to edit at the beginning of your expressions. For example, I have written:

`p1.Angle`

If I would to auto-complete from the beginning let say to add 'anglerotate', the `P1` will be overwritten with the auto-complete. Why don't you let the user keep it instead of correcting the entire text.

`anglerop1.Angle` <-- "anglero" was typed at the beginning to get `anglerotate` auto-completion.

After "Enter" for the auto-completion, it became this:

`anglerotate.Angle` <-- which is a bad expression.

**Comment by AshleyScirra** [comment]
Hmm, it's designed to help you replace things like `Player.XDelta` with `Player.YDelta` by editing just one character, but it does get in the way when you're editing something to the left side of the dot. I'll look in to this for the next build.

**Comment by AshleyScirra** [comment]
OK, should be fixed in r45. The difference is now it will only replace the entire identifier if there is not a dot to the right. So editing `variable_one_name` to `variable_two_name` correctly substitutes the entire variable name with a mid-way edit, but in your example typing `anglero` before `Player.Angle` will give you `anglerotate(Player.Angle`, since the identifier `Player` has a dot to its right.
