### ISSUE TITLE
The "On finished" event is delayed by one frame in the Tween behavior.

### ISSUE THREAD

**Issue by BonzerKitten** [Scirra/Construct-3-bugs#5947]
## Problem description

The "On finished" event in the Tween behavior is delayed by one frame when compared to other similar events, like the ones present in the Timer behavior or event the built-in animation system (Sprite object). This is causing many inconsistencies in one of my projects, because anything that relies on the "On finished" event in the Tween behavior is running in an unexpected order.

For example, moving an object on top of another object and checking for a collision is returning a false result, when in reality it should be returning a true result.

![TweenCode](https://user-images.githubusercontent.com/27010889/182044935-96bb2df6-86d2-4df8-9489-b0656a299e2c.gif)
_Tween finishes on the 14th tick, but the collision is only detected on the 15th tick._

As you can see, the "Is overlapping" event is only considered true in the next frame, which doesn't make much sense. On the other hand, the exact same code performed with the Timer behavior works absolutely fine, giving the expected result on the same tick.

![TimerCode](https://user-images.githubusercontent.com/27010889/182044976-7ae4ac81-1ced-4cd2-8080-a92bd05d38b3.gif)
_Timer finishes on the 15th tick, along with the collision which is also detected on the 15th tick._

I did a bit of research and I believe this might be related to the quite old #3529 issue, where the user describes a very similar problem to what I'm experiencing, so maybe this is some sort of regression. 

This inconsistency can also be seen by checking if a Tween sequence is still running, which will return true, even if after the "On finished" event was triggered.

![image](https://user-images.githubusercontent.com/27010889/182045378-447bdf63-78c5-4c5a-99e4-0337f4102f19.png)

However, before I conclude my issue description, I need to say that based on what I read on issue #3529, the main problem might not be a delayed tick, but an early tick. You see, the Timer behavior consistently delivered results on the 15th tick, collisions also only happened on the 15th tick after the "On finished" event from the Tween behavior, only the "On finished" event itself was running on the 14th tick. 

Well, I hope I was able to explain the issue in a very detailed and insightful way, but if you've any other questions I'll be more than glad to assist you with more information based on my findings.

## Attach a .c3p

[Tween vs Timer Bug.zip](https://github.com/Scirra/Construct-3-bugs/files/9229731/Tween.vs.Timer.Bug.zip)

## Steps to reproduce

1. Enable the code on line 2 and run the project.
2. Note the inconsistency in ticks between the Tween behavior and the collision system.
3. Disable the code on line 2, enable the code on line 3 and run the project.
4. Note the consistency in ticks between the Timer behavior and the collision system.

## Observed result

The "On finished" event in the Tween behavior is inconsistent.

## Expected result

The "On finished" event in the Tween behavior to be consistent.

## More details

**Affected browsers/platforms:** Google Chrome/Windows 11.

**First affected release:** r302 (current stable).

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
This is because the tween end condition is checked after all other events. I think this should be fixed so that the end condition of a tween takes into account the order in which it appears in the event list.

![b](https://user-images.githubusercontent.com/91274932/182187321-f5848c19-9d0d-4d0a-8f60-cbb9c36c8675.png)

[tween_before_ticks.zip](https://github.com/Scirra/Construct-3-bugs/files/9235208/tween_before_ticks.zip)

Actually I already reported this bug: https://github.com/Scirra/Construct-3-bugs/issues/5435

But Ashley said it's because I can't select the newly created instance until the next top-level event, although it's not, here's the evidence (I'm passing the instance directly through scripts):

[tween_create_bug_r276s_scripts_version.zip](https://github.com/Scirra/Construct-3-bugs/files/9235210/tween_create_bug_r276s_scripts_version.zip)

**Comment by DiegoScirra** [comment]
This indeed happens because all tweens execute their **on finished** triggers after all other behaviours.

In this example, whatever you do in the on finished trigger will end up waiting for the next tick, because everything else has already been done for that tick.

This is hard to change without introducing any other problems. Not to mention any projects out there which are already relying on this subtlety, willingly or not, to work.

**Comment by dop2000** [comment]
This is true, I'm relying on Tween state (playing, finished) in many of my game mechanics. Any change to their timings may certainly break something in my project.

**Comment by BonzerKitten** [comment]
I've also got a few games that rely heavily on the current version of the Tween behavior, like [Gardener's Path](https://www.nintendo.com/store/products/gardeners-path-switch/) on the Switch for example. However, I do think it's a valid change to make the engine more consistent in the future and avoid unexpected problems like the ones I'm currently experiencing. From what I can see it was even marked as fixed on #3529, but somehow managed to become a problem again at some point. In any case, it's not up to me to decide how to handle this, so I'll just wait and hope that it's fixed.

**Comment by WilsonPercival** [comment]
> I've also got a few games that rely heavily on the current version of the Tween behavior, like [Gardener's Path](https://www.nintendo.com/store/products/gardeners-path-switch/) on the Switch for example. However, I do think it's a valid change to make the engine more consistent in the future and avoid unexpected problems like the ones I'm currently experiencing. From what I can see it was even marked as fixed on #3529, but somehow managed to become a problem again at some point. In any case, it's not up to me to decide how to handle this, so I'll just wait and hope that it's fixed.

Workaround: [Tween.vs.Timer.Bug (workaround).zip](https://github.com/Scirra/Construct-3-bugs/files/9253557/Tween.vs.Timer.Bug.workaround.zip)

**Comment by AshleyScirra** [comment]
It's not actually the case (as stated by the bug report) that "On finished" is delayed by a frame. It does trigger in the same tick as "On timer", which you can see if you enable all the events. The issue comes down only to sequencing. There have been several reports of sequencing bugs involving behaviors over the years; they are often not fixable because ultimately everything has to run in some order, and changing the order usually means you just get different sequencing problems when doing things in a different order. Changing the order can also cause serious backwards compatibility problems, which means we usually only change them if there's a very good reason.

In this case the order is:

1. "On timer" triggers
2. The event sheet is run (including checking overlap)
3. "On tween finished" triggers

If it's important what the state of an overlap is when a tween finishes, shouldn't that be checked in a sub-event to the "On tween finished" trigger? Otherwise you have set up a race condition with your events, depending on the specific order things run in, and race conditions are notoriously unreliable.

@DiegoScirra - I note that tweens are ticked before event sheets run, but "on finished" is triggered after the event sheet runs. Is there any particular reason for that? We could try moving the finish trigger to fire before the event sheet is run, at least as an experiment on beta releases, to see what the backwards compatibility impact is. But if it breaks too many things we'll probably just have to revert and live with it.

**Comment by DiegoScirra** [comment]
Originally tweens (and timelines) just triggered their **on finished** events the moment they were completed, this was sometime during the main tick event.

At one point, #3529 was reported, in which Tweens claimed to still be playing after **on finished** triggers were called. To ensure that didn't happen, all the **on finished** triggers were moved to a point after everything else has already been processed, so there is no chance of anything else happening after the triggers.

Additionally there is also #2718. In that one, the value of a value tween was queried continually on the "Every frame" event and if the tween was playing, something was done with the value. The problem was that as soon as the tween finished, it was not playing anymore and it was not possible to get the ending value. Because this was a pretty common way of using the behaviour, what I did was assume the tween is still playing, as long as the condition is checked in the same tick it finished. If you explicitly check for **Is Playing** on a sub event inside the **on finished** trigger, it will still be playing. You would never need to do that though, because you are in the finished trigger already.

Both fixes are from 2019, fairly close to the first release of the behaviour and loads of things have been done with both of them in place. We can try changing them, but it's a bit sketchy.

**Comment by AshleyScirra** [comment]
I think it makes sense that we need this ordering for updating the value of tweens every tick while the tween is playing. Logically that requires the final tick to run events with the tween marked playing, followed by triggering 'On finished' after the events. This looks like long-standing functionality that we have reason to believe lots of existing projects already depend on. Therefore I don't think there is any change to be made here. Some projects would prefer the current ordering, and others would prefer a different ordering, but we have to pick one, and at least the one we've got is compatible with existing projects. If this ordering is not ideal I'm afraid I think you'll just have to live with it, but as I noted it is not delayed by a tick, it is just finishing at the end of a tick; if you need to do anything important when a tween finishes, make sure you do it in the "On finished" trigger, and then everything should be up-to-date as expected.
