### ISSUE TITLE
Copying events which require an object to be added to the project creates non-existing functions.

### ISSUE THREAD

**Issue by BigBuckBunny12** [Scirra/Construct-3-bugs#5957]
## Problem description

If a group of events contains a function and a reference to an object, and this group is copied to the event sheet of another project (in which the object isn't present), no events get added (as expected), but the function gets added to the function list, while not existing anywhere in the event sheet. This causes the game not to run when the object and the group of events are added to the new project, since Construct calls a function that doesn't appear anywhere in the event sheet. 

## Attach a .c3p

Project one, where everything is normal:
[Project_1.zip](https://github.com/Scirra/Construct-3-bugs/files/9249395/Project_1.zip)

Project two, which contains a non-existing function:
[Project_2.zip](https://github.com/Scirra/Construct-3-bugs/files/9249400/Project_2.zip)

## Steps to reproduce

1. Create a new project, add an object to the game and give it a name.
2. Add a function to the event sheet, and an event that does something with the object previously added
3. Create a second project, go straight to the event sheet and paste the events from the first project
4. Close the pop up that tells you that an object is required to copy the events, and add that object (with the same name as the other)
5. Paste again the events from the first project and run the game.

## Observed result

The game doesn't start, and a black screen is shown instead. This is because Construct calls a function not present in the event sheet.

## Expected result

Nothing should be added to the project if the events we're trying to copy are not compatible to the project itself. If this was the case, the game should run fine after point 5.

## More details

**Affected browsers/platforms:** Tested on Chrome

**First affected release:** No idea, but i found out that the same bug was reported [here ](https://github.com/Scirra/Construct-3-bugs/issues/3941)

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r302 (stable)
Browser: Chrome 103.0.5060.134
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 137 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This only reproduces with both a function inside a group (it does not reproduce if the function is at the top level of the selection), and if pasting first fails due to a missing object, and then later succeeds. The problem is functions in sub-events are not correctly cleaned up after the paste fails due to a missing object; the subsequent successful paste then renames the pasted function to AddTwoNumbers2 thinking that the name is already in use, which results in a mismatch between the called name and the actual function name.

The code around this is extremely complicated and this will be difficult to fix. However given the somewhat obscure steps involved, hopefully it should be rare that anyone runs in to this.

**Comment by OverboyDev** [comment]
It happens to me everytime i import eventsheet stuff from one project to an other. 
Each time i just rename the non-existing functions in the eventsheets .json so my project works again.
In the JSON, my breaking functions are called "NameOfFunction5" "OtherNameOfFunction6" instead of "NameOfFunction" and "OtherNameOfFunction",  and i usually I just need to remove the number at the end of those function names, that shouldn't be there and that seems to match the number of time i tried to import them with missing elements, so it works again.

It happens to me something like twice per month with my usecase of Construct. 
So i suppose it's not that rare.
I also think for most users who don't know they can fix it by renaming things in the .json files, it seems like their project is totally corrupted and they probably think they need to rollback if they have a backup.

**Comment by BigBuckBunny12** [comment]
I agree with @OverboyDev, I often import events organized in groups from other projects and sometimes the bug occurs. I don't understand why Construct adds a function while the relative events are not added in the event sheet, and the fact that the project cannot be opened after being closed, because of the non-existing function, may lead people to think that their game file is totally corrupted, while, in reality, the fix is pretty simple. I really hope to see this fixed in the future.

**Comment by Alaadel** [comment]
It happened to me when I was trying to copy a function from one version of my project to another version (fork).

**Comment by AshleyScirra** [comment]
I've been working in this area a fair bit recently and think I finally got to the bottom of this with a fix for the next beta. Better late than never!

**Comment by OverboyDev** [comment]
Nice ! Thank you 🙏
