### ISSUE TITLE
Move to global layer bug :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-3-bugs#5958]
## Problem description

There is no global layer in the dropdown list.

## Attach a .c3p

[move_to_global_layer_bug_r304b.zip](https://github.com/WilsonPercival/WilsonPercival/files/9251681/move_to_global_layer_bug_r304b.zip)

## Steps to reproduce

1. Create a new project.
2. Add a layer and make it global.
3. Add a new layout.
4. Add a sprite.
5. Add a layer - it will automatically become global because it will have the same name as in the first layout.
6. Right click on the sprite.
7. Select `Z order` -> `Move to layer`.

## Observed result

![bug](https://user-images.githubusercontent.com/91274932/182618466-9be8bcac-4808-4c2f-89e6-660bafac9cd2.gif)

## Expected result

![expected](https://user-images.githubusercontent.com/91274932/182618449-83b2ad43-6e08-481b-a521-96ad27e840f7.png)

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r304b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r304 (beta)
Browser: Chrome 103.0.5060.114
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 315 mb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D9Ex vs_3_0 ps_3_0, igdumdim64.dll)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 256
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_float_blend
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
EXT_sRGB
KHR_parallel_shader_compile
OES_element_index_uint
OES_fbo_render_mipmap
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I think this might be by design. Moving an instance to a global layer essentially moves it to an entirely different layout, since the global layer inherits the content of a layer from a different layout. Therefore the layout only lists the layers on the current layout since the option only allows it to be moved within layers of the same layout. @DiegoScirra what do you think?

**Comment by Gryphonn** [comment]
> I think this might be by design. Moving an instance to a global layer essentially moves it to an entirely different layout, since the global layer inherits the content of a layer from a different layout. Therefore the "move layer" option only lists the layers on the current layout since the option only allows it to be moved within layers of the same layout. @DiegoScirra what do you think?

There is a related issue.
Let's say I have 3 layers and 1 global layer (from a different layout).

If I want to move something from this global layer to another layer, there is no "Move to layer" option at all. 

I think Global layer on another layout should be treated as a layer of the current layout (in regard to moving stuff).

If I can copy something manually to and from this Global layer, why not allow "Move to"? It's much more convenient since it keeps the position.

**Comment by Gryphonn** [comment]
> I think this might be by design. Moving an instance to a global layer essentially moves it to an entirely different layout, since the global layer inherits the content of a layer from a different layout. Therefore the "move layer" option only lists the layers on the current layout since the option only allows it to be moved within layers of the same layout. @DiegoScirra what do you think?

I'll explain why it is important.
Sometimes you want to move some element to another layer/layout keeping **the same** position. 
Usually programs copy an element on the same position by default.
But in C3 you need to choose a paste position with a cursor. I think it's not convenient and don't see any reason for this behaviour.

What I would like to see is when pasting an element it is pasted on the same position right away. And then you can move it around of course. This way you would satisfy everyone.


Going back to the OP.
1. I can't move an element to another layer (because it's global)
2. I can't copy an element with keeping the same position like many office and graphic apps offer.

So I end up with writing coordinates manually. Not very convenient.
Please allow at least one way of pasting with the same position.

**Comment by DiegoScirra** [comment]
This could be implemented, it would essentially be another method of moving an instance between layouts.

**Comment by AshleyScirra** [comment]
@DiegoScirra - it looks like the 'Layer' property in the layers bar already lists all layers including global layers; only the 'Move to layer' context menu submenu does not list the global layer. This makes it inconsistent with the Properties Bar and presumably we already have a full implementation of moving objects between layouts when changing them to a global layer, so that should just be applied to the context menu as well.

**Comment by DiegoScirra** [comment]
On the next beta there will be more options to move instances in global layers to other layouts.
