### ISSUE TITLE
Event Search does not find results sometimes 

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#5976]
## Problem description

I encounter this issue often, where it can be very challenging to search for an exact event. 

Currently I cannot find an event where I have 2 objects overlapping each other, even though I think the event should exist somewhere in the project.

It's difficult to know the exact string required for a successful search. "Am I formatting the search phrase wrong? Is the event missing? Or is the search bugged?"

Often meaning that we'll then resort to simpler searches, like "overlapping" or even just the name of the object, which are guaranteed to work, but which provide hundreds of irrelevant results — thus making it very inefficient to sift through them all.

## Illustration of the bug

It does not seem like I can find an event that is matching.

I'm pretty sure I phrased and worded it accurately, but yet it gives 0 results:

![a](https://user-images.githubusercontent.com/5744908/183847995-3921d05b-28a9-4007-8153-48ff18b20f75.PNG)

So I tried a generic search for "overlapping" to see if I need to change the formatting, I noticed that other results have a colon in them ":", but that didn't seem to help either:

![b](https://user-images.githubusercontent.com/5744908/183848036-2aeb9fca-215d-4384-a259-45836cb309ea.PNG)

However, after some manual searching I eventually found it, I'm not sure what's going wrong.

![image](https://user-images.githubusercontent.com/5744908/183848364-783c54e7-7d73-43c2-950e-7f267845ef7a.png)

## Solution idea

Instead of requiring an exact string match with the condition/action, make it look for conditions/actions that contain each word in the search phrase. 

This makes it far simpler for users to find events, as it does not require them to be overly specific about the exact wording of conditions.

Because Construct does not have us constantly typing our code in a script like other languages, it's visual, so it's very difficult for us to know the exact string conventions that the search will accept.

## Expectation

I would expect that either of the above illustrated searches would work at finding the specified condition/event, 

But IMO a solution that allows for looser and less pedantic phrasing should also work, given that the nature of this software is built on the foundational philosophy of ease of use.

Here is an example of this looser phrasing, notice that I don't even include "is", I just include some of the words that are in the condition, in an attempt to narrow down the results:

![image](https://user-images.githubusercontent.com/5744908/183850482-2f3f5be0-3e3e-4d7c-8b9a-349a4930401d.png)

This image should show 1 result.

_________________________________________________________________________
__________________________________________________________________________

## Attach a .c3p

[search_bug.zip](https://github.com/Scirra/Construct-3-bugs/files/9298243/search_bug.zip)

## Steps to reproduce

1. Attempt to search for this condition: 
![image](https://user-images.githubusercontent.com/5744908/183853975-a8fbcd5d-be35-468b-9751-c4301ea241d7.png)

## Observed result

0 results

![image](https://user-images.githubusercontent.com/5744908/183854265-b604f1a4-b984-4160-a3e1-cd35f7a384fd.png)

## Expected result

1 result

![image](https://user-images.githubusercontent.com/5744908/183854430-d929dc97-9c09-45e6-a502-6c600279ed57.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's by design at the moment that a string search matches the search term exactly. Changing this will likely break other kinds of searches; in particular matching by space-separated words likely has its own pitfalls with either returning thousands of results or irrelevant things that happen to have the same words involved.

One quirk is that because the object name in a condition is separated from the condition text, it is not considered a contiguous string; therefore it's not currently possible to get a search hit for something like "immunity is overlapping". I suppose matching by individual words might help with this.

As this is a proposal to change or extend an existing feature, please post it as a suggestion instead.

**Comment by OverboyDev** [comment]
**To be honest this must be the most annoying thing in my daily use of Construct for many years**, 

> ; in particular matching by space-separated words likely has its own pitfalls with either returning thousands of results or irrelevant things that happen to have the same words involved

In fact, because of the current limitation, you can only write 1 word at a time to find the event you're looking for.
So if i need to find an event related to my Player's (most used object in my project) Angle, i either need to type "Player" (and i get hundreds of results as Player is used in a huge amount of actions and conditions) or "angle" (and i also get hundreds of results related to all kind of Object Types in my project) => The current behavior is exactly why it returns thousands of results or irrelevant things

**The expected result would be that i find all events related to Player's angle if I type either "Player angle" or "angle player" both should work** and show me all the results related to Player Angle such as "Is Player angle between X and Y" or "Set Player Angle". There wouldn't be any unexpected results this way. Contrary to the current implementation.

I don't see why it would be an issue for the other "find" fields in construct as it's the expected behavior in all cases we need to find stuff. _Also nowadays most software have even better find algorithm such as fuzzy search_.

**Comment by alastajj** [comment]
@OverboyDev thank you for your support.

It's always a challenge with this kind of software, since they don't have anyone on their team making big games with C3 on a daily basis like us, so they don't understand how helpful it would be to fix this kind of issue.

I've shared this issue with them multiple times over the years but perhaps with more people requesting them to fix it, they'll take notice.

Could you share you opinion here? 

https://www.construct.net/en/forum/construct-3/general-discussion-7/c3-event-search-needs-171935
