### ISSUE TITLE
Families don't take into account object's changed Z-position when moved to top of layers

### ISSUE THREAD

**Issue by MihaMS** [Scirra/Construct-3-bugs#5978]
## Problem description

If objects changes their z-order and then it families was moved to top of layer it's z-order reset to the beginning state.
(**_+ please also check the code with restoring z-order while loading game_**)

## Attach a .c3p

https://drive.google.com/file/d/18CBP8koBeHlwJz5y2NehIFhWW1DdUTVB/view?usp=sharing

## Steps to reproduce

1. Open attached c3p file. (Originally sprites has wrong z-order and it's changed on start)
2. Press the Button which call Action for Family (which contain both sprites) to move  to the top of the layer.

## Observed result

z-Order of sprites changed.

## Expected result

Z-Order of sprites preserved.

## More details

Looks like Move to bottom - works correctly and this happened only with Move to top, but I'm not sure.
In my big project I have really weird bug with messing z-order in family sprites when using move family to top of the layer after Loading game and it behaves even more strange... So I can't figure this out in a simple example, but hope this is the same bug. **_But please also check the code with restoring z-order while loading game._**

**Affected browsers/platforms:** 

Tested in Chrome only

**First affected release:** 

C3 r302 stable. not tested in previous releases

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is by design. All actions are essentially run as "for each picked instance, run the action". So in this case there's an implicit "for each instance in family, move to top". That depends on the order of the instance iteration, not the Z order. So you will get an ordering that corresponds to the logical instance order, not the Z order. It does not attempt to preserve anything; it just does what you told it.

For better control of Z order, I'd advise to use the *Sort Z order* system action, which is also far more efficient than using move to top/bottom when using large numbers of objects.

**Comment by MihaMS** [comment]
Ok, thanks for the answer!
