### ISSUE TITLE
Setting 3D object face to a sprite object created during runtime provides inconsistent results

### ISSUE THREAD

**Issue by Aldenwar** [Scirra/Construct-3-bugs#5979]
## Problem description

Creating 3D objects, sprites to use as a face, and setting said sprite as the face is inconsistent. The 3D object face may not connect at all or connect to a different instance. 

## Attach a .c3p

[SetFaceBug.zip](https://github.com/Scirra/Construct-3-bugs/files/9303896/SetFaceBug.zip)

## Steps to reproduce

1. Click on the spawned enemy sprites to have them play animation

## Observed result

Notice how the animation being played does not always reflect correctly on the matching 3D object instance above it, even though they should be linked. Different instances can however work with different setup, such as using no family and only one enemy type instead of 2.

## Expected result

Each 3D object to be showing the animation of the respective animation sprite instance they should be linked to upon creation.

## More details

**Affected browsers/platforms:**  Tested on Chrome and Brave, same issue both

**First affected release:** R302, R305 same issue still

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. Setting an object to the face of a 3D shape ignores picked instances; it just sets the object type to use. Later when it comes to rendering, it tries to pair up sprite instances with 3D shape instances; that only works if there are the same number of both Sprite and 3D shape instances. I would advise using a sprite in a container with a 3D shape to make sure you always have pairs of instances, and then it should work as you want.

**Comment by Aldenwar** [comment]
Ah, I tried my best to find out if this was meant to work or not before making a report but couldn't so I assumed it should, since it mostly seemed to do so. Thanks for the explanation, managed to get the container solution working!
