### ISSUE TITLE
Construct 3 Graphic Glitch

### ISSUE THREAD

**Issue by hammanneric6** [Scirra/Construct-3-bugs#6017]
## Problem description

The issue is somewhat hard to describe but there are screenshots that show it.  There is what looks like a mesh texture that is following the player within the game.  It almost seems like there is a section of the window that has just malfunctioned, similar to having a bad pixel in a monitor.  Whatever this is I can confirm that this mesh isn't any sort of sprite asset in the game.

## Attach a .c3p

I don't have a file to attach as I don't even know what causes this.  I can send the .c3p file for this release of the game but it is far from minimal.

## Steps to reproduce

I don't have steps to reproduce.  I can say however that the person reporting this has logged around 50 hours in the game via Steam at the time of reporting this.  So it doesn't always happen right when you boot the game.  The error also occurred in the middle of playing and according to the user it persists even after they have saved, closed the game, and reopened.

## Observed result

There is a mesh covering a chunk of the screen

## Expected result

There shouldn't be a mesh

## More details

**Affected browsers/platforms:** NW.js, specifically it would be on version 0.60.0

**First affected release:** I don't know about a first release but the version of the game that is public was made back in April.  I only use stable releases so it would have been stable r285.3

## Details

I don't really have any details to add here.  I did want to mention that I'm wondering if this is an NW.js issue.  I've seen this happen I think two other times.  As I recall the previous solution was, update your graphics drivers.  I wanted to be sure about that however.  If we think this is actually NW.js I'll submit a bug report to them instead.

![glitch example 2](https://user-images.githubusercontent.com/11020190/185801182-11991240-2db9-46c2-bbc1-783a7000721a.jpg)
![glitch example 1](https://user-images.githubusercontent.com/11020190/185801184-d4190870-9cb9-44f5-b2ed-d3f38d78d95e.jpg)

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to help without the requested bug report information, so there is nothing we can do with this report.

It could well be a mistake in your own project and not a Construct bug. Providing a minimal project is intended to eliminate the chance it's a mistake in your project from bug reports.

It could also be a graphics driver bug. These are frequently the cause of graphic glitches and are also not caused by Construct. If that's the case your best bet is to just install all available software updates. In NW.js also try unticking "Ignore GPU blacklist", as the GPU blacklist is there to work around some known glitches.
