### ISSUE TITLE
3d rez portrait with text

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-3-bugs#6018]
## Problem description
Setting the resolution for 3d projects to portrait makes text mesh lower quality

## Attach a .c3p
https://www.dropbox.com/s/c6g59mi8gtlx2vo/3dtext.c3p?dl=1

## Steps to reproduce

1.Run project
2.Click Ok
3.Click Ok

## Observed result
Changing the sizes winds up lowering the quality of the billboarded text(mesh)

## Expected result
The quality should remain the same

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Text remains primarily a 2D feature, mainly because deciding what resolution to render the text at uses the 2D scale. When you get a 3D camera involved, it gets far more complicated, especially since the text could be at an angle to the camera and therefore have a range of possible scale values. Text rendering in 3D is a complicated area and usually something a full 3D engine would take care of, but Construct is not a full 3D engine and so we don't support that.

**Comment by pigmalien** [comment]
> Text remains primarily a 2D feature, mainly because deciding what resolution to render the text at uses the 2D scale. When you get a 3D camera involved, it gets far more complicated, especially since the text could be at an angle to the camera and therefore have a range of possible scale values. Text rendering in 3D is a complicated area and usually something a full 3D engine would take care of, but Construct is not a full 3D engine and so we don't support that.

Ok thanks for looking.
