### ISSUE TITLE
Platforminfo size expressions are incorrect

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#6039]
Same as #6011 except this same problem is with the Platforminfo size expressions and not NWJS plugin.

Therefore, it's not a bug with NWJS. 

______________________

My monitor settings: 
![image](https://user-images.githubusercontent.com/5744908/187017072-7238861d-5960-436b-b6ca-5de1b7bf08c9.png)

_____________________

What the expressions say when I make my game **fullscreen**:

- PlatformInfo.CanvasCssWidth = **3148** ❌
- PlatformInfo.CanvasDeviceWidth = **3841** ⚠️ (Close, 1 pixel off!!!)
- PlatformInfo.ScreenWidth =  **3148** ❌
- PlatformInfo.WindowInnerWidth =  **3148** ❌

_______________________

When I take a screenshot and paste in MSPaint, the pixel dimensions of the image say **3840** x **2160** ✔️✔️

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines with every report otherwise it's difficult to help adequately.

In most cases Construct is only reporting the values provided by the browser. It may well be beyond our control if the values reported are wrong.

The CSS and device sizes are expected to be different if the device pixel ratio is not 1. The screenshot you have shown does not prove that the device pixel ratio is 1. For that you need to check the Platform Info's own device pixel ratio expression.
