### ISSUE TITLE
The browser freezes when moving the sprite down using the keyboard. 

### ISSUE THREAD

**Issue by Salfer13** [Scirra/Construct-3-bugs#6081]
## Problem description

The browser freezes when moving the sprite down using the keyboard.

## Steps to reproduce

1. We create an empty project.
2. We create a sprite.
3. Moves the sprite down using the keyboard.
    Hangs for a few seconds if the project is empty.
    If the project is working, then it hangs for almost a minute.

## Observed result

Moves the sprite down using the keyboard.
Hangs for a few seconds if the project is empty.
If the project is working, then it hangs for almost a minute.

## Expected result

Smooth movement of the sprite, as well as up, left, right.

https://www.youtube.com/watch?v=6UTJE5igGrY

**Comment by AshleyScirra** [comment]
I tried following these steps and moving a sprite with arrow keys for ages and it worked fine for me. I'm afraid in that case there's nothing we can do.

I would suggest to always follow the full bug report requirements as we frequently need all that information to be able to figure out what's going on, which is why we ask for it.
