### ISSUE TITLE
C3 - Bug when upgrading to new stable version

### ISSUE THREAD

**Issue by iagolirapasssos** [Scirra/Construct-3-bugs#6094]
## Construct3 is failing in some situations:

![image](https://user-images.githubusercontent.com/4522963/189488763-9ce921f6-b3e6-4799-b2b0-34a90f558871.png)
[DD.zip](https://github.com/Scirra/Construct-3-bugs/files/9540643/DD.zip)

**Comment by iagolirapasssos** [comment]
Construct3 is failing in some situations:

1. When copying and pasting images from the WEB directly into the Sprites.
2. When we use Ctrl+C and Ctrl+z
3. According to the image, my project is not being executed, it is being loaded infinitely.

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it's impossible for us to help.

I tried opening the project file you provided, but it uses a third party addon (UnityAdsX). That may be causing the problem; as per our bug report guidelines we require projects not to use any third party addons in order to eliminate that as a cause.
