### ISSUE TITLE
animation editor - sprite copy does not work

### ISSUE THREAD

**Issue by vtrixdev** [Scirra/Construct-3-bugs#610]
version 44
## Problem description

2 problems

- frame copying using **ctrl - c** 
- marque selection copy (in sprite window) using  **ctrl - c** 

 (not using duplicate)

## Steps to reproduce

**ctrl - c** on a frame and pasting in new animation first works 
but when moving to another animation and returning its gone.... (empty)

the same happens with  marque selecting a sprite in a frame and pasting in a new frame,
first works but when moving away its gone (empty)

**Comment by DiegoScirra** [comment]
These are not bugs.

I'll explain:

1) When you paste something, the content is still in selection mode. You can still see the dashes outline.
2) At this point the pasted content is visible but still not part of the image, you can move the selection around.
3) When the selection is in the position you want you need to click anywhere outside of the selection so it will become part of the image. At this point you won't be seeing the dashed outline anymore.
4) If at any point you leave the current image, be it by going to another frame or another animation and the pasted content was still in selection mode, it will be lost because you never confirmed that you actually wanted to paste it.

This is what C2 does.

I'll admit that there might be better solutions to this problem, but at the moment we have better things to be spending our time on. So I will have to leave this one for further down the line.

**Comment by vtrixdev** [comment]
if i didn't want to commit to what ive done, i would delete it, going to another frame is simply me comfirming what i just did, no need to deselect, + having alot of experience with software it strikes me as off, once you paste something its there, only if you delete it again its gone

selection active + going to other frame or animation = deselect and merge with image

if not bug, maybe flag it as enhancement usability then?

**Comment by DiegoScirra** [comment]
Reopening this so I don't forget about it.
