### ISSUE TITLE
text vertical alignment odd behavior

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6113]
## Problem description
The text objects vertical alignment causes unexpected results.

## Attach a .c3p
[textValignment.zip](https://github.com/Scirra/Construct-3-bugs/files/9591556/textValignment.zip)

## Steps to reproduce

1. start preview
2. select the different options in the list
3. observe the text objects vertical placement

## Observed result
center is higher than top on some and bottom sometimes places the text out of the text object bbox.

## Expected result
Top is higher than center and center is higher than bottom. (another user could also get center to be lower than bottom)
If the text fits inside the box at top or center it should also fit at bottom alignment.

**Comment by AshleyScirra** [comment]
AFAICT this is all currently by design. There is a very complex set of backwards compatibility requirements that makes BBcode on/off work differently, dating back to how C2 has done it since 2011. The alignment also depends on various text metrics as reported by the browser and font. The bounding boxes in this example are also very small and so will constrain the vertical positioning; use taller boxes for better results.
