### ISSUE TITLE
Unable to Load Image from URL

### ISSUE THREAD

**Issue by zakkaplay** [Scirra/Construct-3-bugs#6115]
## Problem description
I used to be able to load image from url, but I am unable to do it now. 
I've copied the objects and events from the working project to a new project, but load image from url won't work on the new project. 

## Attach a .c3p
This is the new project which fails : load_from_url_failed.zip
https://drive.google.com/file/d/1BGvY8pCkp390IiZBFQXOj9H85CMR7xZe/view?usp=sharing

This is the old project which loads successfully : load_from_url_works.zip
https://drive.google.com/file/d/1HY_-uo-jp6AkooIbx_f-H3r4NajTdJ2x/view?usp=sharing

## Steps to reproduce

1. Build apk from : load_from_url_works.zip
2. Build apk from : load_from_url_failed.zip

## Observed result

Apk built from load_from_url_works.zip
► the icons will load (There are a few different icons displayed)

Apk built from load_from_url_failed.zip
► the icons will not load (Smiley face icons only)

## Expected result

Apk built from load_from_url_failed.zip should not display the smiley face but should display some icons instead.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Wackytoaster** [comment]
This could be due to a recent change. Make sure this isn't the issue.

![image](https://user-images.githubusercontent.com/31101309/191088292-f72e6766-7301-435e-af32-60e99b5d0367.png)

**Comment by zakkaplay** [comment]
@Wackytoaster I'ved tested it with CONSTRUCT 3 R310 as you recommended, but there are no difference. 
I've exported 4 versions : 
- Load from URL Load Passed version (Flat)  : Works
- Load from URL Load Passed version (Folders) : Works
- Load from URL Load Failed version (Flat) : Failed
- Load from URL Load Failed version (Flat) : Failed

Seems to be something else?

**Comment by AshleyScirra** [comment]
It's difficult to investigate large, complex projects. The two projects are not directly comparable and so it's hard to say if they actually do anything equivalent, and one of them has over 440 events. Please see our bug report guidelines - we ask for minimal projects otherwise it's generally too complicated to investigate.

As far as I can see, neither project works correctly: if I open the browser console both are logging errors along the lines of

> Access to fetch at 'https://storage.googleapis.com/zakkaplay_gamesportal/logos/boba_fishing_128_v1.png' from origin 'https://preview.construct.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

So it looks like you're making cross-domain requests which the target server has not opted in to, and so aren't allowed.

Without simpler projects that's my best guess at what the issue is. See the section on cross-domain requests in the [AJAX manual entry](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/ajax) for more details.
