### ISSUE TITLE
BBcode breaks automatic word wrapping

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6123]
## Problem description
When using BBcode the text doesn't automatically wrap to the next line anymore when extending beyond the bbox.

## Attach a .c3p
[BBcodenLinebreak.zip](https://github.com/Scirra/Construct-3-bugs/files/9618005/BBcodenLinebreak.zip)

## Steps to reproduce
move the slider to the right (it adds an offset between each letter via bbcode)

## Observed result
text gets cut off

## Expected result
words wraps to the next line when a word extends past the bbox width even with bbcode

## More details
According to this report it was already fixed? But doesn't seem like it for me.
#2834

**Comment by AshleyScirra** [comment]
Offsetting characters does not affect word wrap. The way it works is it does a normal text layout/word wrap without any offsets, and then the offset is applied relative to where the character would be normally. Since the normal layout of the text does not wrap, then no matter what offset you use, it won't make it wrap.
