### ISSUE TITLE
very many sprites - error in opening file .c3p

### ISSUE THREAD

**Issue by barabash777** [Scirra/Construct-3-bugs#6132]
So hello, I don't know for sure if this is a bug or not.

**- I came up with the concept of the game. This is a puzzle (we collect the image from the pieces).** 
**- For my concept, a lot of sprites are needed, 3000-5000 or 10000+.** 
**- Each sprite has about 100 frames of size 250-250. (1 sprite = 1 image, it needs to be assembled from parts to win = 1 levelgame)**
**- To test the idea, I created a sprite, it has 100 frames 250-250. Next I cloned 1 sprite many many times and when there were 400-500 sprites in the project I couldn't open the project and I need to be able to have 3000-5000 or 10000+ sprites. I attached the source file, it weighs 400 mb and an image of the error.** 
--- https://cloud.mail.ru/public/TDHc/eBs5x3ewk
--- https://ibb.co/W0Yt746

Maybe the problem is in my computer, but it is average or even good (rtx 2070, ryzen 2600, 16 gb memory)
If the problem is in the limitation of the engine, can we wait for changes and fixes in the future, or should I not make more than 200-300 sprites in each of which are 100 frames in the game? Thank you.

I would like to have 10000+ sprites in the project and in each instance of the sprite 100 frames with images sized 250-250

browser - Chrome

r308.2

**Comment by AshleyScirra** [comment]
The provided project file appears to be corrupt. If you rename .c3p to .zip you can open it and extract the files. There should be a file named project.c3proj in the root of the zip and some other files, but there are no files in the root, only subfolders.

Without knowing what happened it's hard to comment further - we'd need steps to reproduce the problem as per the bug report guidelines in order to investigate further. So all there is left to do is restore a backup.

FWIW, someone was talking about having a 7 GB Construct project recently, so it should be able to handle lots of content OK. The problem with the project is not that it is big, but that it is corrupt.
