### ISSUE TITLE
8direction - MovingAngle is wrong when "Allow sliding" is enabled

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-3-bugs#6189]
## Attach a .c3p

https://www.dropbox.com/s/udu0v41t1mbskcm/8direction_bug.c3p?dl=0

## Steps to reproduce

1. Try sliding along the walls

## Observed result

Here, for example I'm holding Down key, the sprite is moving to the right and slightly down, but MovingAngle expression returns 90.

![image](https://user-images.githubusercontent.com/36763350/195828934-da40925f-4ece-430f-90a9-023ab0cafd77.png)

Similar issue if you are moving along the right vertical wall holding two keys - Down and Right. The sprite is moving straight down, but MovingAngle returns 44

## Expected result

MovingAngle expression should return the real angle of motion.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r308.2 (stable)
Browser: Chrome 106.0.5249.119
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.75
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 275 gb
Storage usage (approx): 535 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by UbruPro123** [comment]
I observed big change in physics behaviour in this last beta 314 (in 313 it was ok), so I guess it must be related to this. Physics collisions behave really weird as you can see here (only 8dir movement with physics collisions with sliding on).

https://user-images.githubusercontent.com/44697344/195931253-e331da2c-4324-4194-85dd-71432142b9b0.mp4

**Comment by dop2000** [comment]
@UbruPro123 No, I'm pretty certain my issue has nothing to do with Physics changes. 
Also, you shouldn't mix Physics with any other movement behaviors - this will cause all kinds of problems.

**Comment by UbruPro123** [comment]
@dop2000 ahhh sorry my bad, I understand it wrong.
I know but it was ok in 313 beta so there must be something broken with physics.

**Comment by AshleyScirra** [comment]
I think this is just confusion caused by the name of the expression. A better (but too verbose) name would be "the angle the movement is trying to move in". It is named to distinguish itself from the angle of the object. Since the two can be different, there's the object angle which can point one way, and then the moving angle which can point another way for the direction it's moving in. If it is moving down and hits a sloped obstacle, it is still attempting to move down, but the slope is causing it to move sideways as well; but the expression is correct in that it's reporting which way it's trying to move.

I guess a separate expression could be added, but that's more of a feature request, and you can get the angle anyway - save the last X and Y position and compare the angle from the last position to the current position. I think you might run in to corner cases where that angle is erratic though, as small movements will fall in to the realm of floating point precision error and then you'll get an angle that can oscillate wildly; but even if Construct supported this expression directly, it'd just do the same thing and get the same results.

**Comment by dop2000** [comment]
@AshleyScirra I don't see how this is not a bug.. Many other behaviors have the same MovingAngle expression, and it always returns the actual angle at which the object is moving. How 8-direction is different?
Besides, I can't imagine a situation where I would need the angle at which the object is trying to move (and which may often be wrong) instead of the actual movement angle.

**Comment by AshleyScirra** [comment]
It's analogous to the Platform behavior's vector expressions. You can be running rightwards along a bumpy platform that slopes up and down, but vectorX remains at 300 and vectorY remains at 0. It doesn't take in to account the movement of the platform. That's because the angle it's trying to move in isn't always the same as the angle it's actually moving in. These "sliding" features means the actual end movement can be different to where you're trying to go.

**Comment by dop2000** [comment]
Wow, I didn't know MovementAngle and VectorX/VectorY in Platform behavior are also unreliable..
Still, it would make more sense if these expression would always return the actual movement angle.

**Comment by AshleyScirra** [comment]
Would it? If you want to do something like set the animation or object angle to match the direction of movement, then the existing expressions are what you want. For example you still want a platform character, and anything else they are holding, facing exactly to the right regardless of whether they are running up a slope or on flat ground.

**Comment by dop2000** [comment]
Well, in my example in the ticket, if a character was moving straight down along the vertical wall, I'd want it to play "Down" animation. But since the MovingAngle expression returns 44, it's actually closer to 0 degrees than to 90, so the "Right" animation would be selected, which is wrong.
