### ISSUE TITLE
Account loading stops files from opening (minor problem)

### ISSUE THREAD

**Issue by iamthepineapple** [Scirra/Construct-3-bugs#6199]
This isn't something to do with a project. When opening Construct 3, the account thing in the top right has 3 dots by it. Waiting for your account to load can take forever, and while this isn't really a problem in itself, while the account is loading you can't open files. When opening a .c3p file while your account is loading it doesn't open, it just loads. This is a minor issue, but it would be nice to see it fixed. Thanks for upholding Construct 3 so well!
![Screenshot 2022-10-19 08 23 44](https://user-images.githubusercontent.com/105768666/196525150-aa591208-1143-4b07-86c6-96b5938bcdc4.png)

**Comment by AshleyScirra** [comment]
It appears waiting on the account state before opening the project was intentionally added in order to fix #5885. Even for paying customers, Construct remains in free edition mode until the login finishes, since it hasn't finished checking the user account yet. If the project opens before knowing the account state, then a paying customer can get free edition messages/prompts or have part of the project not restore due to free edition restrictions.

> Waiting for your account to load can take forever

@iamthepineapple - it should time out after a maximum of 5 seconds. Have you ever had to wait longer? It shouldn't be stuck indefinitely regardless of your connection.

@DiegoScirra - this was your change, perhaps it could be done another way to avoid making people wait for the account state?

**Comment by DiegoScirra** [comment]
Since the change made to fix #5885 was only really meant for the case of opening projects that need to restore data or text editor tabs, I have moved the wait for the login state so it only takes place if data or text editor tabs need to be restored. In other cases the login state will not block the loading process.
