### ISSUE TITLE
Template>replace whole creates replicas hierarchy with incorrect z-order 

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6212]
## Problem description
Using Template>replace whole creates the replicas hierarchy with incorrect z-order 
## Attach a .c3p
[templateZOrder.zip](https://github.com/Scirra/Construct-3-bugs/files/9847647/templateZOrder.zip)

## Steps to reproduce
![ezgif com-gif-maker (33)](https://user-images.githubusercontent.com/89512047/197420943-34cbc685-9b65-4c7e-a7ae-b0e4f1ac3f79.gif)

1.right-click the sprite in the top left
2. go into the context menu template>apply template to all replicas>hierarchy>replace whole
3. see the replica on the right with the newly created hierarchy

## Observed result
the text object on the right is sorted under the sprite instead of on top

## Expected result
both template and replica have the same z-sorting

## More details
additionaly side note: I would greatly appreciate if the workflow would be improved for "replace whole", as I use it very often. Going so many levels into the context menu every time I want to test a change is a pain. A toggle on the replicas template properties to auto update the hierarchy would be awesome.

**Comment by DiegoScirra** [comment]
The z indexing issue will be resolved starting with the next beta cycle along with a keyboard shortcut to make the feature easier to use.

Automatically updating the hierarchy, while possible it's not trivial, mainly because there are many changes to look at that can affect how a hierarchy looks like. The context menu option was the first method implemented because it was the minimal work required to get something useful out in a short amount of time.

I would suggest opening a new issue for that, so it doesn't get lost. 

Revision 17968.
