### ISSUE TITLE
Two musics not playing simultaneously on Safari on Ipad & Iphone

### ISSUE THREAD

**Issue by Telecs** [Scirra/Construct-3-bugs#6214]
## Problem description

On iPad and iPhone, with the latest update installed, on Safari: when I start a second music while the first one is already playing, the first one is stopped immediately instead of persisting.
I guess it should also happen on iPhone, but did not have the chance to test.

## Attach a .c3p

[Link to project](http://pestorosso.com/two-musics/Two%20Musics%20not%20playing%20on%20Safari.c3p)

## Steps to reproduce

1. Launch remote preview on iPad/iPhone with Safari
2. Tap once to launch the first music
3. Double tap to launch the second music: the second music replaces the first one.

## Observed result

The second music replaces the first one.

## Expected result

In Chrome and other browsers, the two tracks play simultaneously. I expect it to be the same.

## More details
--

**Affected browsers/platforms:** Safari on smart devices. Did not appear on Mac. Tested on iPad A1827 and iPad 2021. On recent iPhone, but don't have the model.

**First affected release:** no clue

## System details

Not useful, I guess

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The link to download the project doesn't work for me.

Besides, IIRC Construct has never supported playing two music tracks simultaneously. So this is something that is not supported rather than a bug.

**Comment by Telecs** [comment]
Hi @AshleyScirra,

I just updated [the link](https://pestorosso.com/two-musics/Two%20Musics%20not%20playing%20on%20Safari.c3p), sorry for that.
From what I understand, playing two music tracks simultaneously is not supported by default by Construct. In that case, how come it is supported in all browsers except Safari? I'm a bit confused and trying to understand. 
In order to seamlessly crossfade two tunes, I was playing two until now because it was the only way identified on the forums by other users. Is it a bad practice to fade out one music while fading in another?

I'm sorry if these are more questions I should be asking on the forum, please let me know and I'll make a new thread about it.

**Comment by F3der1co** [comment]
that's news to me as well. I also crossfade different tracks.

**Comment by AshleyScirra** [comment]
I think what happened here is we had to work around a bug in Safari: https://bugs.webkit.org/show_bug.cgi?id=245428
Our workaround now plays audio in Safari like it does in iOS apps - which as it happens, doesn't allow playing multiple music tracks simultaneously. AFAICT this has never been supported in iOS apps, and the fact it works in Safari actually creates a compatibility problem, as if you then publish an iOS app you'll find it doesn't work there.

For now we are snookered by the bug in Safari which forces our hand and I don't think we will be able to put it back until Apple fix the problem. After that we can revert the change, and we can look in to supporting it in iOS apps as well - looking at our code it seems that's a very old limitation that can probably be lifted given several important upgrades that have happened since then - but first it's on Apple, and unfortunately they don't usually move quickly in my experience...
