### ISSUE TITLE
browser is fullscreen never true

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6233]
## Problem description

browser is fullscreen never true, tested on chrome and edge

## Attach a .c3p

[isFullscreenNotDetected.zip](https://github.com/Scirra/Construct-3-bugs/files/9909421/isFullscreenNotDetected.zip)

## Steps to reproduce
1. start preview
2. press f11 to fullscreen

## Observed result
text remains as "not fullscreen"

## Expected result
text changes to "fullscreen"

**Comment by AshleyScirra** [comment]
I think this is the same thing as was mentioned in #5795. Browsers for some reason don't treat requesting fullscreen the same as F11 fullscreen - they're two separate fullscreen methods, and "is fullscreen" only checks for the requesting fullscreen method. I filed an issue with Google about it, but it seems intentional.

**Comment by F3der1co** [comment]
That is sad, as with this exception the condition is not really usable imo.
I guess comparing the window size with the screen size would be a way, but there might be other exception with that as well.
