### ISSUE TITLE
Element HTML Rotate Don't working when you play the game

### ISSUE THREAD

**Issue by beebits** [Scirra/Construct-3-bugs#6248]
## Problem description

Good

Putting an HTML Element I have realized that the Rotate behavior does not work correctly; since in preview when you are creating the scene if you enable it it looks like the element rotates, but when you hit play, the element does not rotate, even if you put it in the event sheets.

Orbit, Custom Move, Blink works fine, but Rotate doesn't.

Thank you

## Steps to reproduce

1. Create a Element HTML
2. Behaviour Rotate
3. View preview ; works
4. Play the game
5. Dont Rotate

## Observed result
When i play the game

## Expected result

Rotate the Element HTML

**Comment by AshleyScirra** [comment]
HTML element, along with other form controls like Button, don't currently support rotation. They have no angle property and don't provide any actions to set the angle. The problem is only that live previewing the 'rotate' behavior incorrectly shows it rotating them in the editor. That is fixed for the next beta.

**Comment by beebits** [comment]
And for using CSS animate? Could be possible do it? 

I need to try move a table for my game; arround, lineal and ohter things
