### ISSUE TITLE
Color picker :  when press 'enter' that focus return to color picker instead of confirm

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-3-bugs#6266]
## Problem description

After I use the color picker, I get the color, and I press Enter again, and the focus is still on the color picker, instead of closing it to make the property take effect.

![Snipaste_2022-11-10_21-03-41](https://user-images.githubusercontent.com/45864744/201099118-c5b8b079-a250-47a8-ad66-c64615742a6e.png)

## Steps to reproduce
1.
2.
3.

## Observed result

![1](https://user-images.githubusercontent.com/45864744/201100425-34122dd3-c829-493b-b5a4-79c080a969ad.gif)

## Expected result

When I finish picking up the color, press Enter, close the color picker, and make the color take effect

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid the color picker is implemented entirely by the browser and we have no control over it.

This may also be by design: within the color picker, the last button you pressed retains focus, and the enter key will activate a focused button.

You can also tab to a different control and then press enter, and it will close the picker and apply the change.
