### ISSUE TITLE
Animation editor drawing artifacts

### ISSUE THREAD

**Issue by TackerTacker** [Scirra/Construct-3-bugs#6282]
## Problem description

Using Hardness or Opacity below 1.0 with or without Smooth enabled to draw in the Animation editor causes anywhere from moderate to severe artifacts.

https://user-images.githubusercontent.com/18266300/202578027-26549b88-905b-4a62-a097-ab4aa0c86346.mp4

Some artifacts aren't visible in the video because they are more subtle.

## Attach a .c3p

[animation_editor_drawing_artifacts.zip](https://github.com/Scirra/Construct-3-bugs/files/10036367/animation_editor_drawing_artifacts.zip)

## Steps to reproduce

1. Open project
2. Look at the sprite in layout
3. Open Sprite with Animation editor and test any combination of Hardness or Opacity below 1.0 with or without Smooth enabled and draw a few lines.

## Observed result

Drawing artifacts in the animation editor

## Expected result

No drawing artifacts in the animation editor

## More details

**Affected browsers/platforms:** 

I installed C3 as a PWA via chrome

**First affected release:** 

I'm on release r317.2 but noticed this in previous releases, idk when it started or if it was always an issue.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
This is a really old issue, it was first reported back when C3 was launched in 2017. At the time it was not possible to fix it because it was a a problem at the browser level, were very low opacity values produced strange results when attempting to do the colour blend.

Haven't looked at it since, now it might be possible to fix it since there have been a lot of improvements to the canvas API. Still this could be difficult.

**Comment by AshleyScirra** [comment]
@DiegoScirra - we might be in luck with floating point color type support in the standard 2D canvas which appears to have just started development in Chrome: https://chromestatus.com/feature/5086141338877952
Would be worth starring the implementation bug and following so it could be prototyped if Chrome supports it: https://bugs.chromium.org/p/chromium/issues/detail?id=1382422
However it may well still turn out to be complicated to implement - in particular things like ImageData would become floats rather than bytes and so possibly a lot of the image processing code across the image editor's various drawing/editing features would need updating; and then even more work to support both bytes & float format, and dealing with any bugs where there are accidental differences between the two modes; and possibly some memory issues since floating point types use more memory.

Overall I would say this issue is ultimately a limitation of 8-bit color support in the canvas used by the image editor: it's not always good enough precision for repeated drawing actions with some settings like low opacity. This has been reported a couple of times before: #28, #2577

Floating point color type support is more of a feature request to overcome this limitation. Meanwhile there's always third-party image editors, so if this kind of thing is causing problems for a particular art style, it can be drawn with high precision in a third-party tool and imported at the end. So closing as an enhancement - would be best to post on the suggestions platform and also keep an eye on the floating point color type support on our side.

**Comment by TackerTacker** [comment]
It is a bug

**Comment by AshleyScirra** [comment]
This is a limitation of 8-bit color precision. I went in to some detail about the nature of the problem. Merely asserting it is a bug without adding anything further to the conversation is not useful, so locking this issue.
