### ISSUE TITLE
can't zoom out all the way with Z axis scale set to regular

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-3-bugs#6299]
## Problem description

I can't zoom out all the way with Z axis scale set to regular and large-ish layout.

## Attach a .c3p
[zoomOutAxisScale.zip](https://github.com/Scirra/Construct-3-bugs/files/10135512/zoomOutAxisScale.zip)

## Steps to reproduce
1. scroll out to see the whole layout.

## Observed result
I can only scroll out to see about 50% of the layout

## Expected result
I can zoom out all the way to see the full layout and margain.

## More details
the amount you can scroll out seems to changes with the layout size and FOV

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The problem is the default "far" distance is 10000. (The latest betas have a project property for this, but it currently only affects the runtime, not the editor.) If you drop in the 3D Camera object you'll see the default camera Z is about 1300, which corresponds to 100% scale. This means you can only move the camera about 7.7x further away before you hit the maximum far distance of 10000. If the editor let you zoom further past that, all the content on the layout would suddenly disappear as it has gone beyond the maximum draw distance.

I guess the fix should be for the editor to respect the project far distance so you could configure a greater distance and allow a larger zoom range.

**Comment by F3der1co** [comment]
yea, Imo either make it respect the far distance or just allow scrolling past the limit, bc depending on the different z-elevations objects have they could still be visible or disappear no matter what.

**Comment by AshleyScirra** [comment]
The next beta updates the Layout View to respect the near/far distances. This better reflects how the runtime will appear. It also uses the project properties to compute the minimum and maximum allowed zoom levels, which makes this configurable, so you can zoom out further by increasing the far distance.
