### ISSUE TITLE
Text is unreadable by screen readers

### ISSUE THREAD

**Issue by eleanorjmorel** [Scirra/Construct-3-bugs#6318]
## Problem description

None of the text options (spritefont, text, html element) are readable by screen readers or accessibility options)
## Steps to reproduce

1. press windows + ctrl + enter to launch the windows narrator
2. in the editor, texts and properties can be read
3. preview any project
4. the narrator just says "empty document"

## Observed result
 the narrator just says "empty document"

## Expected result
text be read !!!

## More details

**Affected browsers/platforms:** 
all of them as far as I know

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I've looked in to this and prototyped a way to read out Text objects with Windows Narrator. However while accessibility is important, I'm not convinced that allowing screen readers to automatically read out every text/spritefont object is going to be meaningful for many projects. I quickly ran in to a few problems, including:

- Construct doesn't currently have any meaningful indication of what the sequence of text objects is, so a screen reader will read them out in a semi-random order. You could probably control this via some accidental ordering like Z order, but then that might itself be limited by layers for the correct visual appearance.
- Construct doesn't currently have any indication of which are important text objects, and which are either decorative or otherwise unimportant. It will just read out everything (and in an arbitrary order). For example a row of buildings in the background with faint text objects for decoration like "shop", "bakery", "smith" etc. will still be read out, and possibly before something more important like the conversation a character is having.
- Some text objects update regularly, such as the score counter in Space Blaster. The screen reader just ends up reading out a non-stop sequence of numbers, and since the score updates faster than the screen reader can read out updates, it quickly falls behind and becomes irrelevant to the current state of the game. This will probably also hold up more important updates such as if a "game over" message appears.
- I am sure that in some games the above two will combine even worse, where multiple informative text objects are regularly updated (e.g. maybe a bunch of dial read-outs of a decorative control panel in the background), which will cause a non-stop stream of meaningless random numbers to be read out, blocking more important information
- Some text objects don't appear visually, either because they're offscreen, or they are covered up by other objects. Some objects could also be partially off-screen, and we would have to decide when they get read out as they move on-screen. One example of this problem is again in Space Blaster, where a screen reader reads out the "you reached the end!" text placed at the top of the layout that you only visually see if you fight your way all the way through the level, but if the text object exists it gets read out. Since it exists on the start of the layout, it's immediately read out as you start playing.
- Text objects set to invisible should probably be skipped, and read out if they are made visible. But Space Blaster has flashing text on the title screen. Presumably that shouldn't keep reading out the same text. What if the text changes though? Or what if the text is hidden for a minute and then made visible again? It's hard to know what thresholds should be set for this kind of thing.
- Supporting HTML elements is even harder. By default screen readers don't appear to read out anything added to the page by JavaScript, which all HTML element objects are. So it falls to the Construct project developer to handle this, and it's not straightforward (e.g. if you add the `aria-live="polite"` attribute, it still doesn't read out the initial content; only changes shortly after the element is created will be read out).

Some of these options could be mitigated by various extra settings, but on the whole it will still mean it's the responsibility of the Construct project developer to set everything up right so there is a meaningful experience with a screen reader. Meanwhile Construct has a Speech Synthesis object. If you're going to have to do extra work to make your project work well with a screen reader anyway, then using Speech Synthesis actually solves a lot of the above problems: you can make sure it only reads out the salient parts of the game, in the correct order, at the right times, and regardless of whether the content is text or HTML. So perhaps the best solution is just to use Speech Synthesis? The only problem with that though is there isn't a good way to detect if the user is using a screen reader, but perhaps the game could provide a clear setting for that somehow?

**Comment by AshleyScirra** [comment]
That Android talkback feature sounds like it works significantly differently to Windows Narrator, which appears to just read out any screen-reader-accessible text on the page. That makes it even more difficult to support. Unfortunately it's a challenge to make canvas games accessible, as text is drawn directly in to the canvas basically as a large image, so the information about the text and the position is lost, as well as missing metadata about the sequence and importance.

I guess my prototype for reading out text objects at least provides one extra way to make games accessible - just providing a "expose to screenreader" checkbox means you can choose some text to be read out by a tool like Windows Narrator, which can also be completely separate to all the other text objects on-screen. But it will still leave a lot of the remaining problems for the Construct project developer to deal with.

**Comment by AshleyScirra** [comment]
r322 now includes a 'read aloud' option for Text and SpriteFont, providing a basic way to expose text to screen readers. However it will still have a number of shortcomings, some of which were noted above.

I'm going to close this issue as there is now an opt-in, and I think any further enhancements should be tracked as feature suggestions, mainly because as my previous comment demonstrates (and is often the case with suggested improvements), a seemingly obvious approach can have a lot of downsides to the extent it may not actually achieve the intended goal. Therefore any further improvements need to be carefully designed and thoughtfully implemented, which is part of what the suggestions platform aims to encourage, and such improvements do not normally qualify as defects (which is what bug reports are for).
