### ISSUE TITLE
Moving event visuals are not clear

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#632]
## Problem description

It's not very clear when you move events to become subevents or toplevel events where they will be going.

## Attach a .c3p

[moving events bug.zip](https://github.com/Scirra/Construct-3-bugs/files/1158314/moving.events.bug.zip)

## Case 1

![1](https://user-images.githubusercontent.com/5744908/28355061-ca5d427c-6ca5-11e7-9b21-2dee6472eb50.PNG)

Here I'm dragging event 3 so that it's between 1 and 2, this is fine and a good representation. 

All is fine.

## Case 2, subevent creation visuals

![2](https://user-images.githubusercontent.com/5744908/28355166-28130c12-6ca6-11e7-8f09-a2feeb9f3969.PNG)

When we want to move to make a subevent for event 1, we put the mosue in that red area, but the feedback is not clear that it's going to be a subevent. Sure that green line is cut off on the right side, near the actions, but is that really enough to say something different is happening? The green line is not clearly representing it's future position, I would suggest showing it with a slight indent like this to make it obvious:

![3](https://user-images.githubusercontent.com/5744908/28355248-8f1c54c2-6ca6-11e7-8e36-7e9255086fb6.PNG)

**Comment by AshleyScirra** [comment]
Case 2 looks unique to the dark theme, the default theme shouldn't do that. I'm not sure if it's a deliberate change but I agree with this report that it should indent to indicate a sub-event placement.

Not sure about case 8 though, may be a separate issue.

**Comment by alastajj** [comment]
Yes Case 3 is unrelated to theme, you can only drag the event to the bottom, it doesn't let you choose which level to drag it to. 

This is why I'm proposing that you can drag events to the left or right, instead of just up and down, to select their level easier.

**Comment by AshleyScirra** [comment]
Yeah, it would be best to split case 3 to a separate report since it is unrelated to case 2.

**Comment by Animmaniac** [comment]
For the dark theme I removed the indentation from 'conditionFiller' (the darker part of the condition block) to turn events more into a block and make the hierarchy easier to read. It turns out the 'eventInsertMark' currently uses the margin/width of the 'conditionFiller' to set the size of it's sub-event indentation, and it's something I can't control with CSS alone.

I agree that it should have an indentation, and it's something I pondered when creating the dark theme but prefered to preserve the blocky structure instead.

If there's a way to detect through CSS that an 'eventInsertMark' is meant for a sub-event I could probably add an indentation by changing padding and the background-clip. If there's a way to add a "sub-event" class to it I could probably fix it. The alternative is to add the indentation back to 'conditionFiller', but it's something I would prefer not to.

**Comment by AshleyScirra** [comment]
@Animmaniac - I just added a new "subevent" attribute to the event insert marker which is applied when it's aligned with the conditionFiller in the normal theme. That should let you manually indent it with the theme.

**Comment by Animmaniac** [comment]
Great, that should probably fix it.

**Comment by Animmaniac** [comment]
Fixed for next theme release.
