### ISSUE TITLE
Drawing canvas not working on android

### ISSUE THREAD

**Issue by Sirtaximan** [Scirra/Construct-3-bugs#6329]
## Problem description

Drawing canvas not working on android

## Attach a .c3p

https://mega.nz/file/bYR0wAiL#p7g9EYLwAwOhwUIlV4h9C0PybnNAnPikDDzj0KB_wV0

## Steps to reproduce

1.Preview the project. The project works.
2.Export the project to android.
3.The project does not work on android.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The problem is the canvas is sized 6100 x 571. This means it has to create a surface at least that size; on a device with a high pixel density - especially common on phones - it will multiply that even higher. For example with a device pixel ratio of 2, it will create a surface sized 12201 x 1143.

This is beyond the maximum texture size supported by many devices. 4096 is the largest you can rely on being widely supported. 8192 should still cover most devices, but beyond that you're limiting support to only high-end GPUs.
