### ISSUE TITLE
Events can't be moved to some places

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#634]
## Problem description

Moving events around can sometimes feel a bit weird, as you can't move them to some positions. 

## Attach a .c3p

[moving bug.zip](https://github.com/Scirra/Construct-3-bugs/files/1159268/moving.bug.zip)

## Problem illustrated

Event 5 is selected.

![image](https://user-images.githubusercontent.com/5744908/28369698-bade301e-6cdb-11e7-8b5c-7ac8acac30af.png)

If you want to move event 5 without going above another event, it only offers you 1 possible solution of movement, despite there being so many other desired movements, it does not let you move the event anywhere else! As shown this is the only position it will currently accept:

![image](https://user-images.githubusercontent.com/5744908/28369895-37d779c2-6cdc-11e7-9695-e8b10c72475f.png)

## The bug is currently preventing the following positions

Following on from before, to illustrate the issue, here are the places where it is impossible to move event 5 to with a single mouse movement:

![image](https://user-images.githubusercontent.com/5744908/28369986-804dae6a-6cdc-11e7-9613-652c923b6cc1.png)

![image](https://user-images.githubusercontent.com/5744908/28370057-af267708-6cdc-11e7-878e-4e010d5dd1a5.png)

## Solution Mockup Suggestion

Perhaps a solution would be to allow events to move to the left and right, not only will that solve the problem it will feel more intuitive as a bonus.

Here is a mockup of what I think should happen: I'm dragging event 5 with the mouse cursor by keeping it in middle of the event but also moving it to the left, to a position that the bug is currently preventing:

![image](https://user-images.githubusercontent.com/5744908/28370516-d10d585e-6cdd-11e7-9c14-da16c14fb177.png)

Or perhaps you want to go 1 step more to the left? No worries, just move the mouse a little more to the left! Here:

![image](https://user-images.githubusercontent.com/5744908/28370606-0a645300-6cde-11e7-80c9-d81f20ddd873.png)

If the above is achieved, then we could  go as far as allowing an event to moved to the right as well to create subevents. Here is an example of moving event 7 to become a subevent of 6, without having to drag the mouse to a weird spot in event 6, but keeping the cursor on top of 7 while moving it to the right:

![image](https://user-images.githubusercontent.com/5744908/28370798-8aa9932c-6cde-11e7-84b2-b6a839007ea7.png)

I hope this report makes sense. 

Thanks!

**Comment by Animmaniac** [comment]
I thought about something similar some years ago for C2, still have a mockup around:

![event-sheet-drag-event-02](https://user-images.githubusercontent.com/29487913/28422071-e13847a8-6d5e-11e7-8d22-a2ad5d67614a.png)

The colored areas represents where the mouse cursor would trigger each hierarchy level change during drag. They have an offset because I thought it made more sense to try dragging to the hierarchy lines rather than the spaces between them.

My idea at the time was slightly different and would apply to any kind of drag (including when changing the vertical position).

When dragging an event to a position above parent level of the next event (cyan case), the event should be moved to the top of the next event with a higher hierarchy level, but keep the desired hierarchy level. Today I'm not sure what behavior would be better, the above or just setting the event to the desired hierarchy position while readjusting all the event chain below to be it's children.

Anyway, food for thought.

**Comment by AshleyScirra** [comment]
The main difficulty with this is it depends on the event sheet hit-testing system, which is already pretty complicated, and currently has no concept of "hovering after an event but at a different sub-event level". Since this is a non-trivial suggestion and we're aiming to clear suggestions out from the bug tracker, I'm going to close this issue - please re-post at https://construct3.ideas.aha.io/ if you'd still like us to follow up on this in future.
