### ISSUE TITLE
Visual bug in 3d

### ISSUE THREAD

**Issue by Baguhan-p** [Scirra/Construct-3-bugs#6342]
## Problem description
If you enable trilinear or bilinear texture filtering and high-quality scaling, then a visual bug happens.

The example shows two 3D objects with only one side turned on. I do not know how to explain, but they become transparent at certain angles around the edges or something like that.

If you set the nearest neighbor filtering, then there will be no visual bug, but everything will be pixelated and not beautiful

## Attach a .c3p
[bug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/10251962/bug.c3p.zip)

## Steps to reproduce

1. create two or more 3d objects
2. cross them
3. put a texture with png texture
4. deliver trilinear or bilinear filtering and high quality scaling

## Observed result
At the intersection and at the edges, the textures become transparent

## Expected result
Textures should not become transparent at edges and intersections

## More details
I used the "camera distance" layer mode, but it didn't help

**Affected browsers/platforms:** 
Yandex and Chrome

**First affected release:** 
R322
## System details
Windows 10
gtx1650
16gb RAM
i9300h
desktop version of construct 3

![1](https://user-images.githubusercontent.com/45269472/208248784-1819aa72-8845-4232-add7-3b878f92147b.png)
![2](https://user-images.githubusercontent.com/45269472/208248787-97bd4aa9-e1de-4f7f-8795-255c5f8a402c.png)
![3](https://user-images.githubusercontent.com/45269472/208248790-48ce71fd-3bd0-440c-bebe-3cb6022a08d4.png)
![image](https://user-images.githubusercontent.com/45269472/208290752-60a4613e-46c3-4302-8913-613d59bd0bea.png)
![image](https://user-images.githubusercontent.com/45269472/208291170-581de48f-6d45-4f89-a620-32faa2714604.png)

**Comment by AshleyScirra** [comment]
It's not a bug, it's that if you use semitransparency (which can also happen due to resizing or linear sampling) then you must get the render order right otherwise it can cause glitches due to the fact that semitransparent pixels still fill in the depth buffer. See the section on transparency in the [Using 3D in Construct tutorial](https://www.construct.net/en/tutorials/using-3d-construct-2746). It's one of the examples of why 3D rendering is much more complicated than 2D!
