### ISSUE TITLE
Layer scale rate set to 0 resets layer scale to default

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#6364]
## Problem description

Setting the layer scale to 0 resets whatever scale the layer had, making it impossible for this action to be used with UI (UI which should scale once and remain like that)

## Attach a .c3p

[Layout scaling test.zip](https://github.com/Scirra/Construct-3-bugs/files/10324031/Layout.scaling.test.zip)

<img width="623" alt="image" src="https://user-images.githubusercontent.com/7268697/210057678-d932d379-3816-4bda-9fe3-67a795daadb6.png">

## Steps to reproduce

1. change from .zip to .c3p
2. run project

## Observed result

Notice the smiling face sprite gets scaled up as it's expected, but when the last action runs (set layer scale rate to 0) it gets scaled back to default.

## Expected result

I was expecting for the scale to be kept and for the sprite to not scale anymore afterwards due to having the scale rate set to 0 again.

This is not the expected behaviour and it would help **a lot** and save a lot of development time if it's fixed / changed (in case this is actually the intended behaviour). Worse case would be for a new action to be added under System -> "Set layer scale to 0 and keep current scale" if it would be possible (to not break projects which use this current behaviour). 
<img width="144" alt="image" src="https://user-images.githubusercontent.com/7268697/210058365-c163da4e-ebc2-4420-8886-449e24047441.png">

This is very useful to have it working in the way that at least I expected it to work because it allows for UI to be scaled entirely, depending on user settings and device, and then it allows the UI to not scale further when the layout scales. (Imagine a general "UI scale" setting in a game)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by F3der1co** [comment]
I didn't know that "0" resets it to the initial scale rate, tbh I would love to keep that though, would be very useful :D
Thouhg I understand that its not very intuitive

**Comment by AshleyScirra** [comment]
It's actually by design. The scale rate modifies the calculated overall scale - including both the layout and the layer scale - with this formula:

`((layerScale * layoutScale) - 1) * scaleRate + 1`

In other words the scale rate adjusts how quickly the overall scale changes from 100%. If you set it to 0, then the overall scale will always be 100%, regardless of the layer or the layout scale. It's a bit like parallax (where a parallax of 0 will never scroll) but for scale. Changing how it works will likely break existing projects so I wouldn't consider that an option.

I'm not convinced the scale rate is actually that useful a feature. I think it's mostly just a carry-over from the Construct Classic days. If you want to set different layers to different scales, a much more obvious way to do it is just set each layer scale to what you want, and ignore the scale rate. You could wrap that in a function so you only have to have one place where you have a bunch of 'Set layer scale' actions to modify different things (like UI layers or game layers). So I don't think it is worth adding some extra scale rate type features to handle this - you can already control every layer's scale individually, so just do that.

**Comment by JeFawk** [comment]
> It's actually by design. The scale rate modifies the calculated overall scale - including both the layout and the layer scale - with this formula:
> 
> `((layerScale * layoutScale) - 1) * scaleRate + 1`
> 
> In other words the scale rate adjusts how quickly the overall scale changes from 100%. If you set it to 0, then the overall scale will always be 100%, regardless of the layer or the layout scale. It's a bit like parallax (where a parallax of 0 will never scroll) but for scale. Changing how it works will likely break existing projects so I wouldn't consider that an option.
> 
> I'm not convinced the scale rate is actually that useful a feature. I think it's mostly just a carry-over from the Construct Classic days. If you want to set different layers to different scales, a much more obvious way to do it is just set each layer scale to what you want, and ignore the scale rate. You could wrap that in a function so you only have to have one place where you have a bunch of 'Set layer scale' actions to modify different things (like UI layers or game layers). So I don't think it is worth adding some extra scale rate type features to handle this - you can already control every layer's scale individually, so just do that.

Fair enough.
Any idea if scaling 5 layers at the same time (background, grass, buildings, clouds, etc) has any performance impact than scaling the whole layout (with 10 layers, 5 of them having 0 scale rate (UI) )? (i know i can test myself, but if it's something you know already, it would save me some time :) )
Thanks!

**Comment by AshleyScirra** [comment]
I always recommend [measuring it yourself](https://www.construct.net/en/blogs/ashleys-blog-2/answer-own-performance-925) as that's usually the best way to confirm performance questions. However in terms of the engine, every layer calculates its own scale individually using more-or-less the formula above. So something like setting the layout scale to 2 is, internally in the engine, identical to setting every layer scale to 2.
