### ISSUE TITLE
Android export fails Error: /bin/sh: 1: apksigner: not found

### ISSUE THREAD

**Issue by ibiz3091** [Scirra/Construct-3-bugs#6377]
Android export fails with an error when trying to make a signed application

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Can you explain exactly what you're doing? I just tried a signed Android App Bundle build and it seemed to work fine. (As our bug report guidelines explain, it's important to always include steps to reproduce, even if you think the problem is obvious.)

The signed release APK build does seem to fail with an error about `zipalign`, but that doesn't match what you say. I did some maintenance on the build server today, I probably missed something - I'll look in to that.

**Comment by AshleyScirra** [comment]
I think it's fixed temporarily but I need to do some more work to ensure the configuration is preserved after a reboot. It would still be useful to know exactly what you were doing.

**Comment by ibiz3091** [comment]
> Я думаю, что это временно исправлено, но мне нужно проделать еще кое-какую работу, чтобы гарантировать сохранение конфигурации после перезагрузки. Все равно было бы полезно точно знать, что вы делаете.

@AshleyScirra 
I just tried to make a signed build, and now it works fine. thanks for the quick fix.

**Comment by ibiz3091** [comment]
@AshleyScirra 
I just tried to make a signed build, and now it works fine. thanks for the quick fix.

**Comment by ibiz3091** [comment]
@AshleyScirra I just tried to make a signed build again and it again ended with the error Error: /bin/sh: 1: apksigner: not found. I'm just doing a SignedDebugApk.

**Comment by AshleyScirra** [comment]
I've updated the build server configuration and a signed debug APK, signed release APK, and signed Android App Bundle builds are all working for me now. I verified the configuration persists after a server reboot. Apologies for the inconvenience, we've been doing a lot of work on the build server this week to try and resolve reliability issues, and the configuration is complicated.
