### ISSUE TITLE
AdMob Interstitial Ad Not Working on iOS

### ISSUE THREAD

**Issue by am-brick** [Scirra/Construct-3-bugs#6407]
## Problem description

I have implemented MobileAds plugin to my game in Construct3 for iOS platform and live interstitial ads do NOT appear on physical device.

## Attach a .c3p

[BrokenAppleAds.zip](https://github.com/Scirra/Construct-3-bugs/files/10461775/BrokenAppleAds.zip)

## Steps to reproduce

1. Click play button
2. Wait for game over layout
3. Function is called to show interstitial ad on game over layout

## Observed result

Nothing happens.

## Expected result

An interstitial ad should have been shown to the user.

## More details

The odd thing is the ads work in Xcode device simulator with both Test option ON and OFF (I checked both)

However, after having submitted my game successfully on the Apple App Store and trying to play the game on my own device, no ads were showing.

Affected platform is iOS, I personally tested on iPad and iPhone

The game that I published can be found here and  you can see that AdMob ads are not working: https://apps.apple.com/ca/app/apple-store/id1662296901

Using version r317.2 of Construct 3

## System details

Platform information
Product: Construct 3 r317.2 (stable)
Browser: Edge 109.0.1518.55
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.55
Language setting: en-US

Local storage
Storage quota (approx): 1.1 tb
Storage usage (approx): 1.2 gb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Are you sure your events are correct and that ads are correctly configured? As far as I'm aware it's working for everyone else, and we have not made any significant changes to mobile ads for months, and given we've had no other reports over that whole time period, I'd assume it's working for everyone else. Meanwhile such issues are very commonly event or configuration problems, and it's usually difficult for us to reproduce issues, as it depends on your mobile advert configuration, which is under your control and not something we can easily see or verify as we don't have access to your account.

I'd suggest as a starting point at least adding some debug messages (either log to the console or show on-screen) to verify your events really are working as intended, to rule out things like a mistake in your events meaning it is not actually attempting to show an ad. Also make sure you handle all failure/error triggers in Mobile Advert, since your project does not appear to attempt to handle any of those, and if they are triggering they may indicate a problem with your configuration.

**Comment by am-brick** [comment]
But I've tested the ads in Xcode device simulator and they were working fine. How is it possible that they are working in the device simulator but not in an actual device? Is it because of the IDFA not being configured properly? Thanks for replying.

**Comment by am-brick** [comment]
You were right, it was an issue with MobileAdvert not being implemented correctly as well as missing IDFA message setup in AdMob. Thanks.
