### ISSUE TITLE
Sprite animation negative speed doesn't loop

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-3-bugs#6410]
## Problem description

When setting the sprite animation speed to negative based on path finding moving angle, it doesn't work as expected.

## Attach a .c3p

[spriteSpeedBug.zip](https://github.com/Scirra/Construct-3-bugs/files/10466886/spriteSpeedBug.zip)

## Steps to reproduce

1. Run project and preview in debug.
2. Note that the text object does show the sprite is at a negative speed, but the actual object in the debugger still shows a positive value and is not playing.

## Observed result

Animation freeze at negative value.

## Expected result

Animation to play and loop normally in negative value.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r326

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by F3der1co** [comment]
what should even happen in that case, the animation playing backwards?

**Comment by avishaymizrav** [comment]
> what should even happen in that case, the animation playing backwards?

Yes, I believe it always has, I used this many times before.

**Comment by avishaymizrav** [comment]
I just noticed that negative speed doesn't loop at all, though in the animation editor preview it does and live preview also loops, but for some reason plays very fast with negative values.

**Comment by jobel0092** [comment]
I didn't think it was supposed to loop for a negative speed.  In fact, I'm pretty sure I've made games that count on that.

**Comment by avishaymizrav** [comment]
> I didn't think it was supposed to loop for a negative speed. In fact, I'm pretty sure I've made games that count on that.

I think logically if you choose to loop an animation it should loop both ways.
You can always choose not to loop, unless you need to loop forward but not backward, then I guess another "set looping" action would be required.

**Comment by DiegoScirra** [comment]
Just to clear things up.

The runtime is working as expected but there is a subtlety which is explained in the manual entry for **Sprite** in he **repeat to** action description.

https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/sprite

Basically if you set negative speeds, playback will be backwards, but in the case of looping you also need to change the **repeat to** property to go to the last frame of the animation rather than the first. Otherwise the animation will get stuck in the first frame because when it reaches it, it just tries to go to the frame indicated by **repeat to** and since in most cases that is 0, it just stays there.

The preview of the Animations editor is currently not consistent with this behaviour, so it produces different results than the runtime. The next beta will fix the inconsistency so both places produce the same results.

**Comment by avishaymizrav** [comment]
> Just to clear things up.
> 
> The runtime is working as expected but there is a subtlety which is explained in the manual entry for **Sprite** in he **repeat to** action description.
> 
> https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/sprite
> 
> Basically if you set negative speeds, playback will be backwards, but in the case of looping you also need to change the **repeat to** property to go to the last frame of the animation rather than the first. Otherwise the animation will get stuck in the first frame because when it reaches it, it just tries to go to the frame indicated by **repeat to** and since in most cases that is 0, it just stays there.
> 
> The preview of the Animations editor is currently not consistent with this behaviour, so it produces different results than the runtime. The next beta will fix the inconsistency so both places produce the same results.
> 
> No changes will be made to the runtime because there are most likely projects that rely on the current behaviour.

Ha, that's great, I don't why I didn't think to try that, but it makes sense, thanks!
