### ISSUE TITLE
Access to context menu to update replicas is often blocked by other sprites

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-3-bugs#6411]
## Problem description
![contextmenu](https://user-images.githubusercontent.com/31101309/213721211-eebab3a5-57f2-4d52-9408-14d4f94f4155.PNG)

The access to this menu is often blocked by other sprites. E.g. commonly you have an (invisible) collider sprite with a visible sprite on top. It's not possible to rightclick the collider that is set as a template. Unless there's a nice keyboard shortcut that I'm not aware off? Moving the sprite is not an option since then you'd update it in the wrong position.

The only thing I found is locking the sprite, which is doable if it's only a single sprite, but if there's multiple sprites overlapping and you are actively working on it and moving them/changing variables/scaling them, it can get tedious to lock/unlock them constantly just to be able to update the replicas.

## Attach a .c3p

[updatereplicas.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/10467042/updatereplicas.c3p.zip)

## Steps to reproduce

1. Attempt to update all replicas from the template

## Observed result

The context menu cannot be opened because the rightclick is blocked by the sprite on top.

## Expected result

I'd like to see the option to update all replicas somewhere else in addition. My proposal would be two buttons and maybe a keyboard shortcut.
![prop](https://user-images.githubusercontent.com/31101309/213722801-d8f6669e-43d4-4214-b76e-c913e176d611.PNG)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r326 (beta)
Browser: Chrome 109.0.5414.75
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 4.4 gb (3.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by F3der1co** [comment]
this issue is a good chunk of why I made both of these suggestions :D

https://construct23.ideas.aha.io/ideas/C23-I-91

https://construct23.ideas.aha.io/ideas/C23-I-5

**Comment by DiegoScirra** [comment]
There are keyboard shortcuts for both options, still in the beta channel only, so they aren't documented yet.

**Ctrl/Cmd + [** to replace the whole hierarchy of the current selection
**Ctrl/Cmd  + ]** to modify the existing hierarchy of the current selection

**Comment by Wackytoaster** [comment]
I see two issues with these shortcuts.
1. I'm on german keyboard layout. I've tried a bit but I couldn't figure out what I have to press. [ and ] require me to press Alt Gr, but Ctrl+AltGr+[ did nothing. I've also tried to press the buttons that correspond with [ and ] on the english layout, which also does not work.
2. I have to select the replicas. If I have a big project with 100 levels, I'd have to go into each individual level, select all replicas and replace them. I'd rather just go to my template layout, and update all replicas from the template across the project.

**Comment by DiegoScirra** [comment]
So I have a few things to say:

**1)**

The main issue will be fixed in the next beta.

**2)**

I just found out that the key codes in a German keyboard are quite different, specially when it comes to none word characters, which are often moved around depending on the layout and the language of the keyboard.

C3 is just not prepared to handle this, it looks at physical key codes rather than logical values. I don't think the logical values where even available when we implemented the main bulk of the keyboard shortcut code, which is pretty old at this point. That is why you can't hit the correct key.

What I will do is make sure the square brackets are interpreted logically rather than by a key code, so this particular shortcut works as expected in all keyboard layouts. Reviewing all keyboard shortcuts is a massive undertaking though, so will have to leave that for another time.

**3)**

As for applying the changes to all your replicas, the options work slightly differently depending on if you apply them on a replica or a template. You will notice the names in the context menu are slightly different to hint at this.

Applying on a replica applies the change on the replica alone (or selection of replicas), while doing the same thing on a template propagates the change to all corresponding replicas.

What I though the workflow should be when working with templates, was to have a template in an object bank layout, make changes on it, and then use the option to propagate all changes to the existing replicas across the project. If you then want to make unique changes to a few replicas you could go to the specific layout that holds them.

**Comment by Wackytoaster** [comment]
1. Oh that's... unlucky I guess. I wonder how other applications handle the different keyboard layouts. Are they really going by symbol and not by keycode?
2. Applying from the Template to all replicas is what I meant. The issue technically applies to both cases but it's less of an issue if you just want to update a bunch of replicas since you **can** move the overlapping sprites since they'll get updated anyway. But when updating from the Template you cannot move the sprites since that would change the Template.

**Comment by DiegoScirra** [comment]
I was just talking with Ash about this, and he mentioned that if you press TAB while clicking on a bunch of stacked instances, the selection cycles through the overlapping instances. Are you using this feature already? To be honest I wasn't even aware it existed.

We where talking about adding the option of bringing the correct context menu in the case you right click while pressing TAB, instead of just the context menu for the top most instance as it does now, which would be useful not only on this case but in any case there are stacked instances.

I am thinking of adding that along with buttons in the properties bar as you mentioned.

**Comment by Wackytoaster** [comment]
I did not know about the TAB thing, that's quite useful indeed.

**Comment by DiegoScirra** [comment]
The next beta will make the three options in the **Templates** context menu (apply properties, replace hierarchy and modify hierarchy) available in the Properties bar.

Even though the ideal solution is for templates to propagate their changes automatically, that isn't as easy to implement (there are many hidden caveats), so for the time being the manual toggles will have to do. It should be easier to work with them now.

Will close this now.

**Comment by DiegoScirra** [comment]
Just letting you guys know that I removed the options from the Properties bar, because on second though that's not really what the Properties bar is for. 

I will rework the context menus so there aren't as many levels of nesting, but that will be for the beta release after the next one.
