### ISSUE TITLE
WaterBackgrounds breaking apart after long ingame time

### ISSUE THREAD

**Issue by DinoSystem** [Scirra/Construct-3-bugs#6450]
## Problem description

After a long in-game time, Water Background and similiar effects start to glitch and totally break.

## Attach a .c3p

[WATERBACKGROUND BUG.zip](https://github.com/Scirra/Construct-3-bugs/files/10556463/WATERBACKGROUND.BUG.zip)

## Steps to reproduce

1. Change the timescale using the button
2. Wait few sec

## Observed result

The WaterBackground effect breaks apart.

## Expected result

WaterBackground should continue normally.

## More details

- The bug happens and worsen gradually as time passes ingame, no matter how fast the timescale: if it takes few sec at 50000x timescale, it will take double time with 25000x, and 10 times longer at 2500x. I've tested with only 5x timescale in 2 rl days, and it still happens eventually.
- The bug happens also if you disable the effect and enable it after those ingame time. 
- It still happens if the game is saved and loaded. 
- It probably also happens for other similiar water effects, but didn't test extensively.

**Affected browsers/platforms:** 

Edge, Chrome

**First affected release:** 

Tested only for r319 to r328, but happened in C2 too!

## System details

<details><summary>View details</summary>

Device name	LAPTOP-DAOHK829
Processor	Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz   2.50 GHz
Installed RAM	8.00 GB (7.83 GB usable)
Device ID	3FC91B51-E8DD-4CFB-B006-E1141BF1C7B0
Product ID	00325-82098-04728-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
Edition	Windows 11 Home
Version	22H2
Installed on	‎20/‎11/‎2022
OS build	22621.1105
Experience	Windows Feature Experience Pack 1000.22638.1000.0

</details>

**Comment by AshleyScirra** [comment]
I've looked in to this and can reproduce, but the problem is when the time value becomes very large, it runs out of floating point precision in the GPU shader code, which causes the quality of the effect to degrade. I've tried forcing everything to use the maximum precision, but it still happens. Also since the effect does not repeat in a loop, the time value can't be cycled back round to keep it low without causing a visible jump in the animation.

So I think all we can do is make the animation repeat on a long time scale, which means it visibly jumps after a given amount of time. I've gone with a 10800-second loop (3 hours at a normal time scale) for the next beta, which ensures your example continues rendering normally even after running at a time scale of 50000 for an extended period of time. However this technically makes it a 3-hour repeating animation being played in fast forward. Players may also notice the jump in effect animations at the 3-hour point, but at least it is a one-off discontinuity and not a permanent degradation in the effect quality, and I'm not sure there's anything better we can do.

**Comment by DinoSystem** [comment]
> I've looked in to this and can reproduce, but the problem is when the time value becomes very large, it runs out of floating point precision in the GPU shader code, which causes the quality of the effect to degrade. I've tried forcing everything to use the maximum precision, but it still happens. Also since the effect does not repeat in a loop, the time value can't be cycled back round to keep it low without causing a visible jump in the animation.
> 
> So I think all we can do is make the animation repeat on a long time scale, which means it visibly jumps after a given amount of time. I've gone with a 10800-second loop (3 hours at a normal time scale) for the next beta, which ensures your example continues rendering normally even after running at a time scale of 50000 for an extended period of time. However this technically makes it a 3-hour repeating animation being played in fast forward. Players may also notice the jump in effect animations at the 3-hour point, but at least it is a one-off discontinuity and not a permanent degradation in the effect quality, and I'm not sure there's anything better we can do.

Buch better a little visual inconsistency every 3 hours than the whole effect breaking permanently on the long run!

**Comment by DinoSystem** [comment]
I don't use 50000x timescale in my game, but games can be very long or go indefinitely, so the bug would happen. The workaround you applied sounds fine to me, but i'll test it extensively.
