### ISSUE TITLE
Cannot work offline with project above free limits

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-3-bugs#6510]
## Problem description

I remember C3 was supposed to work offline for 10 days? More? Unless anything changed, I cannot do that. First it happened ~3 weeks ago on an airplane, now my WIFI crashed for a bit and I noticed it's still a problem.

## Attach a .c3p

Video instead :) : https://streamable.com/kvahnz

## Steps to reproduce

1. with internet on, make sure you are logged in on c3 (using firefox), can even log out and log back in (to reset offline timer?)
2. turn off the internet, quit firefox
3. open it back up
4. navigate using firefox to the c3 page
5. notice you are logged out
6. pull any big project on to open it
7. notice you can't

## Observed result

Cannot open big project while offline, the editor freezes in "Opening..."

## Expected result

I expected to be able to work on any project while offline within reasonable limit.

## More details

**Affected browsers/platforms:** Firefox 109.0.1

**First affected release:** i dont remember last time this worked, even a year or two ago i had this problem and submitted a report i think (the C3 app while offline wouldnt load at all, instead you had the logo really big on the screen)

## System details

<details><summary>View details</summary>

Platform information

Product: Construct 3 r327.2 (stable)
Browser: Firefox 109.0
Browser engine: Gecko
Context: browser
Operating system: macOS 10.15
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0
Language setting: en-US
Local storage

Storage quota (approx): 10 gb
Storage usage (approx): 460 mb (4.5%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to [bug 1163426](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426)
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Apple
Renderer: Apple M1
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 64
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_draw_buffers_indexed
    OES_texture_float_linear
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Huh, it works fine for me in Chrome (after several seconds the account badge should change from "..." to a cloud with a cross through it to show offline mode), but in Firefox it never gets past "...". Perhaps it's some weird Firefox compatibility issue. This stuff is difficult to test so it could take a while to get to the bottom of it.

**Comment by AshleyScirra** [comment]
I think I figured out something funny Firefox was doing which hopefully should fix it, but marking to check after next release to verify it works for you.

**Comment by AshleyScirra** [comment]
r330 is now out, can you check again with that?

**Comment by AshleyScirra** [comment]
Are you sure you waited for the "ready to use offline" notification? If your steps do not explicitly include that then I would assume it hadn't fully offline cached before you tried it offline, which is quite a common problem. I tried it in r330 in Firefox and my account does appear to work offline and I can create a new project successfully, so I think at least the account part of this issue is solved anyway.

It does seem like you need to preview at least once while online to make sure that preview itself is also cached for offline use. The editor does try to cache the preview window as well when loading it to make sure it's ready offline as well, but I think browsers are tightening their rules around storage and it may be that Firefox prevents the preview being saved when it's not the top-level window. I'm not sure there's much we can do about that - I added a note to the documentation to say we recommend previewing a project while online.

So I think the original issue is solved, and if anything else is still a problem it's probably best we start over so please file a new issue, and make sure it starts with:

1. Wait for the "ready to use offline" notification
2. Preview a project while online
3. Go offline and then attempt to do something
