### ISSUE TITLE
Platformer VectorX are not framerate independent

### ISSUE THREAD

**Issue by Kapusta-dev** [Scirra/Construct-3-bugs#6599]
## Problem description

When running the attached project on 144Hz, 60Hz, and under unlimited frames, the result will be different on each.
The project sets the 'VectorX' parameters of a platformer object manually right before performing a jump. When running on each of the refresh rates above, the player ends up in a different place.

The documentation states VectorX would be in pixels per second, which implies framerate independence. 
Furthermore, adding deltatime to the VectorX parameter in event #6 to try and fix this causes inconsistent results.

## Attach a .c3p

[PlatformerJumpBug.zip](https://github.com/Scirra/Construct-3-bugs/files/10800254/PlatformerJumpBug.zip)

## Steps to reproduce

1. Ensure Project is set to VSync framerate mode
2. Press Q to position the player and wait for him to land on the ground
3. Press W to make the player jump - note the jump distance
4. Set the project to unlimited framerate mode
5. Press Q to position the player and wait for him to land on the ground
6. Press W to make the player jump - note player ends up in a different location than when running in VSync mode

## Observed result

Player lands in a different spot depending on framerate.

## Expected result

The player should land in the same spot since the documentation states 'VectorX' of the platforming behavior is in pixels per second, which implies framerate independence. If the documentation is wrong, there still seems to be an issue here since  adding deltatime to the VectorX parameter in event #6 still causes inconsistent results.

## More details

Tested on Chrome and Edge - same issue.
Currently broken in R331 but I've had other projects going as far back as R270 that exhibited this issue. 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r331 (beta)
Browser: Chrome 110.0.5481.104
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 80 gb
Storage usage (approx): 305 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 with Max-Q Design Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Wackytoaster** [comment]
I have to comment since I had a run-in with the platformer behavior vectors myself just recenty. Pretty sure this happens because "Is not on floor" is a 1 frame occurance.

1. Press W -> vectorX = 93.3
2. Behavior ticks after events -> vectorX = 93.3-deceleration*dt -> update sprite position
3. Now "is not on floor" fires -> vectorX = 93.3
4. Behavior ticks...

Knowing this you can counteract the frame of deceleration as such and get consistent results across framerates.
![image](https://user-images.githubusercontent.com/31101309/220630003-2947041c-4e1c-48d6-925f-4d4ee80bd843.png)

The behavior first decelerates, then updates position. Possibly this could be solved by switching this around in the behavior and first update the position, then decelerate, Resulting in

1. Press W -> vectorX = 93.3
2. Behavior ticks after events -> update sprite position (at vectorX 93.3) -> apply deceleration
3. Now "is not on floor" fires -> vectorX 93.3 (overrides the deceleration as if it never happened)
4. Behavior ticks -> vectorX 93.3

Coincidentally, the same solution I believe is needed for my case (with vectorY) and I'd argue this is the "more correct" behavior. As in if I set an objects vectorX to 100, I expect it to have this vectorX for the first tick of movement, whereas right now it's more like if I set it to 100, internally it starts at a lower value due to being decelerated instantly before any movement happens.

**Comment by AshleyScirra** [comment]
This issue looks like it is basically the same as #6550 but operating on the horizontal axis rather than the vertical, so merging as duplicate. I will also check this repro when dealing with the other issue.
