### ISSUE TITLE
Sprite.ObjectTypeName returns empty string if Sprite is not in the layout

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-3-bugs#6635]
## Problem description
My project has a Layout for objects, and needs to create objects by name at runtime. I pass "Sprite.ObjectTypeName" but it evaluates to empty string (because the object is not in the layout), but the Create action still works fine if I pass hardcoded string.
I thought ObjectTypeName was like a static property (unlike Height, X, Y.. which change per instance).

I don't know whether this is intended or not.

## Attach a .c3p
[New project.zip](https://github.com/Scirra/Construct-3-bugs/files/10833755/New.project.zip)

## Steps to reproduce

1. Run layout 1

## Observed result

Empty alert

## Expected result

Object type name "Sprite"

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. If no instance exists, there is no instance to query expressions for, and so you will only get empty values for its expressions.

Construct currently has no concept of static expressions, and even this expression can't really be static anyway, as you could have Family.ObjectTypeName which requires an instance in order to return the correct value.
