### ISSUE TITLE
Layer Effect "Tint" values give different (darker) results than C2

### ISSUE THREAD

**Issue by NetOneGames** [Scirra/Construct-3-bugs#665]
## Problem description

RGB 100 in C2 is equivalent to RGB 255 in C3

## Attach a .c3p

attaching capx with compatible events for C3 included

[tint.zip](https://github.com/Scirra/Construct-3-bugs/files/1198806/tint.zip)

## Steps to reproduce

1. twiggle the slider and compare C2 and C3

## Observed result

C3 darker

*What did you expect to happen instead?*

Consistency between C2 and C3, or maybe not, not sure what is supposed to be what,  but I am testing migration to C3 and this is an issue as my game uses tinting on one of the layers.

## Affected browsers

* Chrome: yes
* Edge: yes

**Comment by AshleyScirra** [comment]
Hmm, I think the problem is that the `rgb()` expression clamps the color inputs so it can't go out of bounds (e.g. tint at 200%). This is a bit awkward and something C2 could do, so there probably needs to be a new expression to cover that..

**Comment by AshleyScirra** [comment]
The basic problem is C2 'set effect parameter' actions used a 0-100 scale, but the C3 rgb() expression uses a 0-255 scale. You can easily fix this in the project, but it makes porting C2 projects harder since you have to multiply by 2.55 to get the same scale.

For r52 I've added a new system expression rgbEx() that should fix two issues:
1. It uses a 0-100 scale for each parameter, making it consistent with the old C2 'set effect parameter' actions
2. It allows out-of-range values, e.g. 200, allowing things like overdrive tint, which the rgb() expression previously did not allow.
Hopefully that resolves everything here.

**Comment by NetOneGames** [comment]
Hi Ashley, is it possible to somehow link the old C2 tint behavior to this so that importing C2 to C3 gives the same results.

Currently importing C2 to C3 still results in the incorrect tint values and so requires updating all tint related code.

**Comment by AshleyScirra** [comment]
You have to update all shaders with color parameters anyway, because we changed them from 3 parameters (for each color component) to 1 (using an rgb/rgbEx expression).
