### ISSUE TITLE
Dictionary C2 to C3 problem

### ISSUE THREAD

**Issue by sajmons** [Scirra/Construct-3-bugs#67]
## Problem description

When opening Construct 2 file with Dictionary key accessed by Variable value, C3 crashes.

## Attach a .c3p

Atached Dictionary_C2_to_C3_problem.capx

## Steps to reproduce

1. Go to Construct 3 and open Construct 2 CAPX file Dictionary_C2_to_C3_problem.capx

## Observed result

Construct 3 shows crash report dialog.

## Expected result

File should open normally, Construct 2 handles that with no problem.

## Affected browsers

* Chrome: yes
* Opera: yes
* Firefox: na
* Edge: na
* Safari: na

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Invalid parameter: 'Dictionary.Get' parameter 0 does not take 'number'
Construct 3 version: r17
URL: https://editor.construct.net/
Date: Thu Apr 13 2017 08:35:37 GMT+0200 (Central Europe Daylight Time)
Uptime: 385.7 s

Platform information
Browser: Opera
Browser version: 44.0.2510.1159
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 8
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36 OPR/44.0.2510.1159

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Vendor: Google Inc.
Renderer: ANGLE (Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

</details>
[Dictionary_C2_to_C3_problem.zip](https://github.com/Scirra/Construct-3-bugs/files/918688/Dictionary_C2_to_C3_problem.zip)

**Comment by AshleyScirra** [comment]
The problem is the 'Get' expression does not accept a number. It must be passed a string. Try using Dictionary.Get(0) - it marks an error in the expression. The problem is C2 allows this invalid expression if it happens to be a number variable. C3 has stricter checking and rejects it.

I don't really want to relax C3's checking because it means you can use invalid expressions again. It's probably too late to fix it in C2 at this point, since it would prevent you opening the project in C2 in the same way you can't open it in C3. So it seems the best workaround is just to fix the expression in C2 to be valid again, and then import to C3.
