### ISSUE TITLE
Image Editor: Origin (image points) drastically changes position after cropping, if the point is outside image

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#673]
## Problem description

If the origin point is outside of a frame, once you crop the image the point will change position.

Thanks for your work in making the Image Editor usuable! 

## Attach a .c3p

[origin crop bug.zip](https://github.com/Scirra/Construct-3-bugs/files/1202161/origin.crop.bug.zip)

## Steps to reproduce

1. Go to image editor, see how the origin point is outside the image, in the same position on every frame of animation
2. Shift + Crop to crop entire animation

## Observed result

Notice how the red target is moving all over the place, the origin point has shifted to random positions in each frame despite it being uniform before the crop.

## Expected result

The red cross should stay still.

The origin point should stay where you placed, even if it's outside of the image before you crop,

**Comment by DiegoScirra** [comment]
I found a bug which caused the image points to be positioned seemingly randomly after undoing a crop command.

I have fixed that. Not to sure if that was your problem.

The image points are meant to change position after cropping, this is inevitable, because after doing so, the image is smaller. So the image points must change position to appear in the same relative place as they were before the change.

Anyway. As of r49 C3 should be doing the exact same thing as C2.
