### ISSUE TITLE
Add support for remote URL dependency scripts

### ISSUE THREAD

**Issue by Psychokiller1888** [Scirra/Construct-3-bugs#675]
## Problem description

Hello!

Thank for r48 adding file dependency. It works well! The only problem is we cannot include external script, or distant scripts, from the internet. When exporting, C3 fails saying the file is not found.

Why I want this? Because that way we can have the plugin include an always up-to-date API somewhere on the internet rater than have a manually copied local file that might be deprecated

**Comment by AshleyScirra** [comment]
This is by design for security reasons. Construct 3 deliberately blocks access to third-party origins, since this entirely prevents the chance that malicious scripts could steal people's work or login details by posting it to a third-party server. This is far too much of a risk to lift just because of addon bundling. Besides loading directly from the web would cause dependency hell (you never know when you get updated and can't ever roll back) and prevents working offline.

**Comment by Psychokiller1888** [comment]
So it's normal that C3 miserably fails with an error if we specify a url as plugin dependency? That a good idea on how to brake C3... Beside, including ext script was working in C2.... For me it's not a problem, I already setup a btach that mods the export to add the distant API....

**Comment by AshleyScirra** [comment]
I thought you wanted C3 to pull in the URL when you export. Do you just want to add a script tag with a URL to the exported index.html? If so you don't need the dependency system, just create a script tag when your runtime script loads.

**Comment by Psychokiller1888** [comment]
No. Technically I want what C2 was doing: Specifying a dependency. As you did on C3, it adds a <script> tag in the index file. But it doesn't add it if the file's not locally. I could do whatever you want, dynamically add a <script> tag in the dom through the runtime of course, but doing this exposes the plugin to failure, as this dynamic loading can take time and by the time it loads, the plugin might already have needed the API. This was the case for AirConsole API in the early C2 plugin.

What I would like is that, like in C2, the specified dependency is added in the index.html file as a <script> tag even if the file is not existing locally. In the meantime I did it through a batch file that edits the html for the users and ads the tag along with correctly renaming the exported files for AirConsole

**Comment by AshleyScirra** [comment]
OK, I'll take a look at doing that.

**Comment by Psychokiller1888** [comment]
Great, thanks!

**Comment by AshleyScirra** [comment]
On further reflection there are still two drawbacks with doing this:

1. It breaks offline support, since cross-origin typically can't be added to the offline cache
2. Some stores (e.g. iOS App Store) have rules about loading executable code from the web, and it might get the app banned. At the very least it will probably require additional configuration to permit requests to the origin.

So doing this may prevent the app being published, and even if it is published, creates an app that won't work offline. So I am feeling pretty sceptical about this. It still seems better to bundle the API with the addon, so it's included with the project.

**Comment by Psychokiller1888** [comment]
You can't play AirConsole while being offline....

**Comment by AshleyScirra** [comment]
Maybe it doesn't make sense for AirConsole, but for the SDK we have to think about the general-purpose usage, and whether or not we want to allow this kind of thing in general with other addons. Given the drawbacks I'd rather not. It doesn't seem to be too big an inconvenience to bundle the API with your addon, and it guarantees offline support will work and has no implications for app publishing.

Also if a remote script fails to load while offline, the entire API will be unavailable. Unless you carefully test this, the project will crash at the first use of the API. It seems better for the API to be present, even if it fails to connect. It seems more straightforward to handle API errors rather than the dual case of either the API failing, or the API missing entirely.

**Comment by Psychokiller1888** [comment]
Please read this: https://github.com/AirConsole/airconsole-api/issues/33

AirConsole says we shouldn't include the API but link it...

**Comment by AshleyScirra** [comment]
This is a problem in C2. The drawbacks are the same. If you already do this, you already break offline support. I'd rather offline support in C3 is a guaranteed feature and not subject to third-party addons that break it.

**Comment by Psychokiller1888** [comment]
There's no offline support in airconsole

**Comment by AshleyScirra** [comment]
I know:

> Maybe it doesn't make sense for AirConsole, but for the SDK we have to think about the general-purpose usage, and whether or not we want to allow this kind of thing in general with other addons. Given the drawbacks I'd rather not. It doesn't seem to be too big an inconvenience to bundle the API with your addon, and it guarantees offline support will work and has no implications for app publishing.

**Comment by Psychokiller1888** [comment]
Why don't you just let the plugin dev chose??? It doesn't affect C3 safety

**Comment by AshleyScirra** [comment]
Plugin developers routinely make user-hostile choices, so we are keen to impose strict rules about what plugin developers can do. For example if we allowed this, I'm sure some developer would load something like jQuery from a CDN and unnecessarily break offline support for everybody who uses that addon. We end up having to support those users who come to us complaining that offline support doesn't work. So we would rather force plugin developers to do the right thing at the cost of flexibility.

**Comment by Psychokiller1888** [comment]
Yeah... Ok, nothing to change your mind.... ECMA6 will soon add external includes, it's gonna be fixed by itself then

**Comment by AshleyScirra** [comment]
If you really want to you can still attach the script at runtime, but you will have to expose the load state to events. Honestly, I'd just bundle the library with your addon.

**Comment by Psychokiller1888** [comment]
We are not allowed by the TOS to bundle the library, as with many other libraries

**Comment by AshleyScirra** [comment]
That's something to take up with the library author.

**Comment by paala** [comment]
If you keep this restriction, Google IMA can't be implemented.
https://github.com/googleads/googleads-ima-html5/blob/master/simple/index.html
In their demo they request this file:
//imasdk.googleapis.com/js/sdkloader/ima3.js
If you download the file and point the local file it will not work.
So with this setup Construct 3 is not able to support Google IMA ads.

**Comment by Psychokiller1888** [comment]
You can bypass that restriction easily, check how I did in airconsole for construct3 plugin

**Comment by paala** [comment]
can you please tell me how? or link to your plugin?

**Comment by Psychokiller1888** [comment]
Not on computer, pretty hard to show, but check here : https://github.com/AirConsole/airconsole-construct3/blob/master/plugin/c2runtime/runtime.js

**Comment by Psychokiller1888** [comment]
Got my hands on a tablet... Technically that part does the job at remote loading:

var script = document.createElement('script');
script.src = 'https://www.airconsole.com/api/airconsole-1.7.0.js';
script.onload = function() {
	self.initAirConsole();
};
document.head.appendChild(script);

You'll need a delayed check if it loaded to have your plugin working though. Mine uses initAirConsole() and retries a couple of times before failing amd falling back to a script mockup

**Comment by paala** [comment]
this seams to work but not in preview mode...

**Comment by AshleyScirra** [comment]
OK, I guess we should add a feature for this after all. I filed #884 to track that. You should be careful to gracefully handle the API failing to load though, which will always happen if the user is offline.

**Comment by Psychokiller1888** [comment]
What a great news.... As I said, imo it's the devs that have to think thoroughly and add what's needed if the api is missing
