### ISSUE TITLE
chrome: construct3 can register as default "application" for *.c3p (& others) files in one line

### ISSUE THREAD

**Issue by rvion** [Scirra/Construct-3-bugs#689]
I just discovered about chrome being able to register as default file handler !

from https://developers.google.com/web/updates/2011/06/Registering-a-custom-protocol-handler:

```html
navigator.registerProtocolHandler(
    'c3p', 'https://editor.construct.net/rph?q=%s', 'My App');
```
> The first parameter is the protocol. The second is the URL pattern of the application that should handle this scheme. The pattern should include a '%s' as a placeholder for data and it must must be on the same origin as the app attempting to register the protocol. Once the user approves access, you can use this link through your app, other sites, etc.:

```html
<a href="c3p:some+zip+url">Open in "Construct3"</a>
```

enabled by default on chrome: see [chrome://settings/handlers](chrome://settings/handlers)

It looks like a quick win feature for construct3 !

![image](https://user-images.githubusercontent.com/2150990/29112557-8b0371d8-7cee-11e7-9a2d-764714b691a6.png)

**Comment by shortercode** [comment]
Unfortunately we can't really use this.

I've looked through the specs and it only works for links on websites, not for files on your computer. Also due to security restrictions it's awkward/impossible for us to load resources from other domains, so it would be limited to projects on **construct.net**.

All in all it would be pretty awkward and restricted. When the standalone version of C3 is released I expect we'll have a binding for c3p files on the local machine, but it's not something the web platform currently allows as far as I'm aware.
