### ISSUE TITLE
MOBILE IDE: impossible to add objects to layout after creation time

### ISSUE THREAD

**Issue by rvion** [Scirra/Construct-3-bugs#692]
## Problem description

On my android device, when I create a sprite, if I don't place it right away on the layout, I can't place it any more.

Indeed, 

 - i can't copy paste it since there is no other instance in any layout
 - 🔴  I can't drag and drop it from the project pane (touch drag and drop not working)

more generally, adding a large number of instance in a layout is really painful on mobile (related: https://github.com/Scirra/Construct-3-bugs/issues/682)

💚  an "instance brush" or something related would really help !

## Attach a .c3p

from any blank project,

## Steps to reproduce

1. create a sprite object
2. either don't place it, or place it and delete it (long touch, delete, message about last instance being deleted appears) 
3. impossible to re-instantiate it from mobile

**Comment by AshleyScirra** [comment]
The mobile version of C3 is currently designed mainly for reviewing and light editing of projects; it doesn't currently have the full editing features of the desktop version. (Mainly because it's really hard to design all those features in a way that works well on mobile!)

Consequently the fact you can't drag-and-drop from the project bar is mostly just one of these missing features that basically needs a new mobile-specific alternative to be implemented. This is not currently a very high priority. I think it would be better to post such feature ideas to our [feature tracker](https://construct3.ideas.aha.io) instead.

**Comment by rvion** [comment]
@AshleyScirra, can you please reconsider this one ? 

This issue is one of the most important one on mobile, as it just __completely__ prevent mobile editing. Some other tasks may be clunky to do, but there is at least a way.

Here, without this feature, there is no way to place instances at all.

> The mobile version of C3 is currently designed mainly for reviewing and light editing of projects; it doesn't currently have the full editing features of the desktop version. (Mainly because it's really hard to design all those features in a way that works well on mobile!)

The mobile IDE is almost usable, and that's quite impressive. I almost completed small games to the end on mobile only (until some crash or lock as this one happened). I think you're __very close__ of having a powerful mobile IDE :)

**Comment by AshleyScirra** [comment]
Our goal with the mobile version is to, at first, make it a good way to review projects. Only some light editing features are provided, because most of the time, as this issue shows, we need to implement a separate mobile-specific mechanism. That is also difficult given the screen size and touch input constraints. We've already been working flat out for 3 years on Construct 3, and we still are; we can't do everything at once, and since we anticipate most people use desktop devices since it's a lot easier to be productive there (and our stats do show this), adding all these extra mobile-specific editing features are not currently a high priority. We also think that most of the time if you open a project on a phone, it's probably just to review or tweak it anyway, since it is so much easier to get real work done on a desktop system.

If you have a tablet (or you are willing to squint at a phone screen), you can connect up a mouse & keyboard and change the UI to desktop mode in Settings. Then you can use it like a mini laptop.
