### ISSUE TITLE
No context menu in text editor

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#722]
In the text editor, right-clicking does not show anything. Either a C3 menu should appear, or the browser default menu, so things like cut/copy/paste can be accessed.

**Comment by shortercode** [comment]
Have added a C3 menu, which provides:

- undo
- redo
- cut (native)
- copy (native)
- delete
- close
- select all

Unable to implement paste (native) due to security restrictions. I did consider using our clipboard but I think the text editor is one area that can benefit from the native clipboard, and if we used both trying to decide which one to paste from is somewhat awkward. Something to improve in future anyway.
