### ISSUE TITLE
Setting animation speed to a negative value doesn't make it reverse in playback, instead it stops

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-3-bugs#734]
## Problem description

When you set the speed of an animation to a negative value in the events it treats it as 0, when setting the value below 0 in the image editor it will set it to 0.

## Attach a .c3p

[run.zip](https://github.com/Scirra/Construct-3-bugs/files/1241509/run.zip)

## Steps to reproduce

1. Set the animation speed of an animation to -20 in the events or image editor

## Observed result

The animation stops, as if its at 0 speed.

## Expected result

It should reverse in playback, similar to the ping pong setting. 

For instance, a -20 speed animation should play the same as a +20 speed animation with the only difference being that it's doing the frames in the reverse order.

**Comment by AshleyScirra** [comment]
It does actually work at runtime, the problem is the repeat-to frame is set to 0 so when looping it sticks to the first frame. If you set the repeat-to frame to 5, then you can set a reverse looping animation at runtime.

The editor didn't let you set a negative animation speed though, so that's been fixed for r52.
