### ISSUE TITLE
Web App exported from construct 3 keep show Black Screen on Safari

### ISSUE THREAD

**Issue by ZalaXeN** [Scirra/Construct-3-bugs#761]
## Problem description

The game I deploy on a web just show Black Screen on Safari.
in Inspector show
"Initialise — opus.js:37 RangeError: Maximum call stack size exceeded.".

## Steps to reproduce

1. Export Project -> Web
2. Deploy it
3. Open web on Safari

## Observed result

Web App just show Black Screen on Safari.
in Inspector show
"Initialise — opus.js:37 RangeError: Maximum call stack size exceeded.".

## Expected result

Web App show normally.

## Affected browsers

* Chrome: no
* Firefox: no
* Edge: no
* Safari: yes

## Workaround

I just fixed it by added code on opus.js (line 37)

` if(!n){
				return;
			}
			Initialise(n); `

**Comment by shortercode** [comment]
Okay dokes, looks like this specifically happens if your project does **not** pre-load audio and the browser doesn't have a native decoder for opus. I appears just to be a naming collision, that only affects that one function. Kinda frustrating!

The workaround which you've listed will work, but will cause a delay when you actually need to decode audio. So what I'll do is post a patched file for you now, so you don't have to wait until the next release to come out.

**Comment by shortercode** [comment]
[opus.txt](https://github.com/Scirra/Construct-3-bugs/files/1259903/opus.txt)

Okay this is the patched version of that javascript file, I've also made some changes which should reduce the delay before decoding a file that isn't loaded at startup. If you could test it out that would be greatly appreciated.

**Comment by ZalaXeN** [comment]
I test it out and now It look Great!
I hope to see it for next release, Thx for fast fixed file.

**Comment by shortercode** [comment]
No worries, I made some pretty big changes to the decoder for the r50 so I've been keeping an eye out for bugs in it.

Going to keep this bug open until R52 is released, but can consider this closed.

**Comment by AshleyScirra** [comment]
r52 is out, please verify it works as expected.

**Comment by shortercode** [comment]
I think the patch file was tested, so going to close this.
