### ISSUE TITLE
Expressions Dictionary does not have default instance variable description

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#794]
## Problem description

You recently added a description of the variable type such as (String) etc, but you missed adding it to object instance variables.

https://www.dropbox.com/s/3dfteozcfz3q387/Screen%20Shot%202017-09-10%20at%2016.35.29.png?raw=1

## Steps to reproduce

1.
2.
3.

## Observed result

add variable type label

## Expected result

missing.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
In C2 if an instance variable has no description it defaults to something like "A string instance variable". C3 should do this as well, since that puts the type information in the description field. If you do enter a description that commonly includes a type as well by the nature of the description (e.g. "[i]number[/i] of bullets", "[i]string[/i] of player name"). If that's still not clear enough I guess we could add type annotations beside the name as well.

**Comment by mOOnpunk** [comment]
I think type annotations is the way to go and would make it like the drop down menus etc.

**Comment by DiegoScirra** [comment]
Added in r56.

Global, Local and Instance variable now have a default description and type annotation next to their name.
