### ISSUE TITLE
nested sub-events display issue.

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#796]
## Problem description

Some times you need to use nested sub events, but with a limited screen space it all becomes a squashed up mess. 

https://www.dropbox.com/s/42e2o2651b3ynae/Screen%20Shot%202017-09-13%20at%2015.20.00.png?raw=1

Would it please be possible not to alter the event spaceing but instead just add a horizontal scroll bar to the bottom of the screen? This is much better option in my opinion.

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.
2.
3.

## Observed result

It becomes hard to read and follow code with lots of nested sub events.

## Expected result

keep things clear to read and select.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by mOOnpunk** [comment]
Please address this issue. It can't be that hard to add a horizontal scroll bar to the event sheet?

**Comment by AshleyScirra** [comment]
10+ levels of indentation is a lot and must make for some pretty confusing events. Why not refactor them in to separate functions to help make them more manageable?

The lack of horizontal scrolling in the event sheet is a very deliberate design decision to make it easier to manage your events. In some tools you can end up scrolling a long way horizontally and it makes everything harder to work with. So I would rather ban horizontal scrolling and encourage people to adjust their events to use less indentation.

**Comment by mOOnpunk** [comment]
With respect you need to stop telling users how to use the software and listen to how they are actually using it. You cant accout for everything. I'm doing complicted things sorting and comparing many token lists, using functions would make things more confusing. Please reconsider. If you want to allow users to make more complex games then you need more complex functionality.

**Comment by AshleyScirra** [comment]
Sorry, we're not going to fix this. C2 never did this and we won't for C3 either. Your screenshot also shows a large text size, surely you can reduce it to get more space? You can also remove the side bars or dock them differently to free up more horizontal room. I'd also strongly recommend refactoring events in to functions to simplify them and reduce the indent level. I suspect this is what the majority of users do, since we have had no other complaints about this AFAIK, nor was it ever a problem with C2 IIRC. 

There might even be performance issues if we did this. Currently we have a fixed size column for the condition blocks, so the browser doesn't have to calculate the column size, it just takes the value we give it. If it's possible for the column to overflow horizontally, the browser has to first do layout all the way through the event sheet to compute the column size in case anything overflows, then probably go all the way through again in a second pass to actually wrap text and such. We already have issues elsewhere with layout performance and I definitely don't want to make it worse. Additionally the DOM layout and CSS rules are very complex with a lot of nesting and various hacks for cross-browser support; it could prove tricky implement this correctly, and I wouldn't be surprised if it caused a few other followup bugs.

Finally I'd add I think it's actually a poor usability experience to have to scroll horizontally (some design guidelines even say "never have horizontal scrolling at all"). If this is really a problem for a lot of users (which it doesn't seem to be right now), I'd still want to find a different way to solve the problem. Overall there are many reasons why we can't "just" add a scrollbar, so closing as won't fix.
