### ISSUE TITLE
Adding a variable is restarting the page as a new tab

### ISSUE THREAD

**Issue by danainbar** [Scirra/Construct-3-bugs#798]
Adding a variable is restarting the page as a new tab

I just updated my construct , I bought it few months ago and it worked perfectly. Since this morning,
Whenever I try to add a new var the site is switching to a new tab page.

![untitled](https://user-images.githubusercontent.com/31949515/30415540-217fa894-9931-11e7-870c-afe02e8dc529.png)

## Steps to reproduce

1. add a new var 

## Affected browsers

* Chrome: yes

**Comment by griffenk** [comment]
Not possible to work at all. Redirectling to new tab all the time!!! Very frustrating

**Comment by AshleyScirra** [comment]
I can't reproduce any issue in either Chrome or Firefox. The steps to reproduce are confusing - you say "add a new var" but your screenshot contradicts this, since it does not show a new variable being added, just a condition to compare a variable. I tried both adding a variable then adding the condition, or just adding the condition directly with no variables in the project; it works fine in both Chrome and Firefox.

Please always follow the bug report guidelines as closely and fully as possible - they exist so we can actually find the issue you are reporting.

**Comment by griffenk** [comment]
Dear Ashley,

Please see new #800 Issue open

Thanks,

Sergey
