### ISSUE TITLE
Redirect in preview mode

### ISSUE THREAD

**Issue by rexrainbow** [Scirra/Construct-3-bugs#799]
## Problem description

In preview, page(app) will be closed after url redirected.

## Attach a .c3p

https://1drv.ms/u/s!Am5HlOzVf0kHmCJ2WrmNQTEN0UXo

## Steps to reproduce

1. run this c3p in preview mode.

## Observed result

2. page(app) redirects to google search page
3. page(app) is closed 

## Expected result

Page(app) stays in google search page

## Affected browsers

* Chrome: yes

## System details

C3 r55, winodw 7 64bit

**Comment by AshleyScirra** [comment]
This is not supported. You're trying to navigate to a URL directly with JavaScript - just use the browser object's 'Go to URL' instead. In preview mode that action opens a new window, because navigating away is not supported in preview mode - the window is owned by Construct 3 and is used exclusively for preview purposes, and if the page is unloaded it assumes the popup was closed.

**Comment by rexrainbow** [comment]
Facebook or google authentication has pop-up or redirect mode, it seems that only pop-up mode could work in C3's preview. Thanks.

**Comment by AshleyScirra** [comment]
Popup sounds like a better idea anyway, since navigating back will reboot the game.
