### ISSUE TITLE
Can you whitelist "cordova-plugin-game" by @cranberrygame on Construct Cloud Compiler?

### ISSUE THREAD

**Issue by TombasOnly** [Scirra/Construct-3-bugs#804]
Hi TeamConstruct,

I use C2C3AddonConverter by blackhornet on MagiCam plugin and LiteTween behavior, both working well. So I try to use it on "cordova-plugin-game" by @cranberrygame, because Google Play Services in C3 didn't work on mobile.
link: https://www.npmjs.com/package/cordova-plugin-game

Then I succesfully instal it to Construct 3 like addon.

Then I exported project like Cordova for Android in C3 exporter.
And in config.xml there are just default plugins (for iap and browser plugin).
plugin name="construct-mobile-purchase" />
plugin name="cordova-plugin-inappbrowser" />
plugin name="cordova-plugin-whitelist" />
plugin name="cordova-plugin-statusbar" />
plugin name="cordova-custom-config" />

I expected one more line like:
plugin name="cordova-plugin-game" />
or maybe something like this
plugin name="cordova-plugin-game">
    variable name="APP_ID" value="my_app_id" />
/plugin>

If I add this and compile game to apk by Construct Cloud Compiler, plugin didn't work.
So I write about my issue on forum and @AshleyScirra say you have a Whitelist for allowed plugins.

Can you please whitelist this plugin? Or more from cranberry? I think he is trustworthy source because his plugins works with C2 :)
https://www.npmjs.com/~cranberrygame

Yours sincerely, Tombas

**Comment by shortercode** [comment]
Plugin has been added to the whitelist, let me know if you have any problems

**Comment by TombasOnly** [comment]
@shortercode 
I tried C3 Compiler and still didn't work. So I installed my own cordova.
I try installed "[cordova-plugin-game](https://www.npmjs.com/package/cordova-plugin-game)".
It first end with error. Than I found that  has dependency on other cranbbery's plugin "cordova-plugin-extras-google-play-services".
https://www.npmjs.com/package/cordova-plugin-extras-google-play-services
https://github.com/cranberrygame/cordova-plugin-extras-google-play-services

Than I install git. And now plugin is sucessfully instaled and working on mobile.
![screenshot](https://user-images.githubusercontent.com/31991351/30642445-4587bb62-9e0b-11e7-86fd-de0a32b2998f.png)

Maybe if you whitelist "cordova-plugin-extras-google-play-services" It will work in C3 Compiler. 

In config.xml I have now this more lines:
```
  <plugin name="cordova-plugin-game">
    <variable name="APP_ID" value="here_is_my_id" />
  </plugin>
```
and config.json/package.json
```
"dependencies": {
        "cordova-plugin-extras-google-play-services": "git+https://github.com/cranberrygame/cordova-plugin-extras-google-play-services.git"
    },
    "cordova": {
        "plugins": {
            "cordova-plugin-game": {
                "APP_ID": "here_is_my_id"
            }
        }
    }
```

**Comment by shortercode** [comment]
Okay will look into it!

**Comment by shortercode** [comment]
@TombasOnly Okay so I'm doing some work on the build server so updating the whitelisted plugins. In my testing on the mac one of the dependant plugins for this doesn't actually install correctly, `cordova-plugin-ad-admob-sdk` performs an illegal syscall. 

@Kyatric reported this bug in 2015 and it hasn't been fixed, unless you can persuade cranberrygame to fix the issue I'm going to have to close this, sorry :/

**Comment by ERAgames777** [comment]
Hello! I need the google play services plug-in for C3, could you post it for download?

**Comment by shortercode** [comment]
So I had put this bug to the side, as I needed to implement cordova variables for the build service to get it to work. But, I did the work for that when I rewrote the google play plugin so this SHOULD now work.

In practice, it doesn't. I've done some debugging and it looks like the plugin doesn't work correctly with the latest version of cordova. The plugin defines that a new file called "ids.xml" should be created and the variable should go into it. The file is created, but the value is never set. I'm guessing cordova has some bug here, normally plugins put values in the "strings.xml" file which should always exist and that definitely works.

So it's whitelisted, but the plugin doesn't work... The fix is quite simple, but you would need to get cranberrygame to fix it and he's not really active anymore from what I've heard. I guess you could fork his plugin if you want?

Alternatively, we support leaderboards via Google Play and Game Center now so you can use those instead?
