### ISSUE TITLE
Special chars like Ă are not being interpreted by StringFromKeyCode expression

### ISSUE THREAD

**Issue by paala** [Scirra/Construct-3-bugs#837]
## Problem description

When you type special characters like Ă from other language than english, the text is interpreted as if the keyboard would be english
[specialkeyboard char.zip](https://github.com/Scirra/Construct-3-bugs/files/1329838/specialkeyboard.char.zip)

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1.modify in windows the keyboard to another language
2. open project 
3. observe that if you type a special char is interpreted as if the keyboard is english

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/
* Firefox: yes
* Edge: yes
* Safari: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
You're using the `StringFromKeyCode` expression, and AFAIK key-codes are language neutral key identifiers which more or less identify a key position rather than a typed character. For example you'll get a key code like `56` which you then ask for a string from. The StringFromKeyCode expression falls back to an ASCII interpretation. I think what you want instead is something that returns the KeyboardEvent.key property, which would be a new expression.

**Comment by paala** [comment]
Well : 
This website shows that you can detect when a special char is input:
http://javascript.info/keyboard-events
How can I do that with construct 3?

**Comment by AshleyScirra** [comment]
Should be in r78 as TypedKey expression.
