### ISSUE TITLE
can't resize object expression window

### ISSUE THREAD

**Issue by mOOnpunk** [Scirra/Construct-3-bugs#863]
## Problem description

This is a common issue for me and it drives me nuts!

Some times when i'm in the expression editor the object window will appear very small (also annoying) so i try to resize the window but the resize handles don't appear so i can't grab the window to resize it.

https://www.dropbox.com/s/hop5hukv1or4t0v/cantResize.gif?raw=1

In the gif you can see i can resize height up and down but i cant grab the side to alter the width, or grab the corner.

I try moving the mouse slow, i try different positions up and down the side, i try to reposition the window but still nothing.

As i say this is a common problem for me, its not just resizing the width of the box it just happened in this case.

## Attach a .c3p

editor issue

## Steps to reproduce

1.
2.
3.

## Observed result

can't resize window

## Expected result

be able to resize window

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: (unknown)
Context: webapp
Operating system: Mac OS X
Operating system version: 10.11_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r59
Language setting: en-US

Local storage
Storage quota (approx): 61 gb
Storage usage (approx): 20 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: ATI Technologies Inc.
Renderer: ATI Radeon HD 5670 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
In issue #427 there's a problem with changing the mouse cursor in Chrome - it doesn't always change the cursor correctly. It may be that if you click anyway even though the wrong cursor is showing, you can still resize the dialog. If that's the case, it's probably a duplicate.

**Comment by mOOnpunk** [comment]
I've tried clicking, even in the attached gif above but it does not register, and still can't resize the window. I think there is more to the problem than not changing the cursor image.

**Comment by DiegoScirra** [comment]
**Update:**

Trying this out in our MAC I was able to reproduce the bug in Safari, 100% of the time. Everything works fine in Chrome though.

From looking at the platform information the only difference I can see between our MAC and @mOOnpunk 's MAC is that he is running OSX 10.11 (El Capitan) and we are running OSX 10.13 (High Sierra)

So maybe it's the old version of OSX triggering the bug in Chrome.

Here is the platform information from running the current version of C3 in our MAC in Safari and Chrome.

<details><summary>Safari Platform Details</summary>
Platform information

Browser: Safari
Browser version: 11.0
Browser engine: WebKit
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: (unavailable, defaulting to 2)
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38
C3 release: r61
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
CSS containment is not supported. Editor performance may be significantly degraded.
Service Workers are not supported. Construct 3 cannot be used offline in this browser.
The <dialog> element is not supported. A polyfill is in use.
Web Animations are not supported. Animations are disabled.
This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
ImageBitmap is not supported. Texture loading performance may be degraded.
Idle callbacks are not supported. Background loading performance may be degraded.
Determining input device capabilities is not supported.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 1.0 (2.1 INTEL-10.28.26)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Vendor: Intel Inc.
Renderer: Intel Iris Pro OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions:

EXT_blend_minmax
EXT_sRGB
EXT_frag_depth
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_standard_derivatives
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
OES_vertex_array_object
OES_element_index_uint
WEBGL_lose_context
WEBGL_compressed_texture_s3tc
WEBGL_depth_texture
WEBGL_draw_buffers
ANGLE_instanced_arrays
WEBGL_debug_renderer_info
Audio information
System sample rate: 44100 Hz
Output channels: 0
Output interpretation: speakers
Supported decode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats: (encoding not supported)

Video information
Supported decode formats:

H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats: (encoding not supported)
</details>

<details><summary>Chrome Platform Details</summary>
Platform information

Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.13_0
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r61
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: (status unavailable)

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
Persistent storage is not available. Local storage could be deleted by the browser.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Intel Inc.
Renderer: Intel Iris Pro OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>
