### ISSUE TITLE
Can't open Project from Google Drive in r60

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#892]
## Problem description

see Title
i can open fine in r59
it also seems i can save to cloud fine

when i try to open from cloud, the login window appears, i log in, but then the login window does not disappear (then i close the login window to: "authentication stopped")

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce

1. upload a file on google drive
2. close project
3. try to open from cloud

## Observed result

*What do you see happen?*

## Expected result

*What did you expect to happen instead?*

## Affected browsers

* Chrome: yes/no

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by shortercode** [comment]
Assigning @TomGullen to keep an eye on the caching situation.

**Comment by shortercode** [comment]
@Leralasss We made a change to the way the login works in r60, but there's some caching issues preventing part of the change reaching users.

It's going to take a day or 2 for the cache to sort out... In the meantime you will have to either load files locally or use r59.

Unfortunately due to the way this change works the cloud login will stop working on r59 and below once  the cache has updated.

**Comment by shortercode** [comment]
@Leralasss The caching situation seems to have been resolved with the release of r61, could you check that you can log in now?

**Comment by shortercode** [comment]
Seems to be fixed as of the r61 release, so closing.
