### ISSUE TITLE
Construct 3 does not enables persistence storage

### ISSUE THREAD

**Issue by newman321** [Scirra/Construct-3-bugs#948]
## Problem description

Construct 3 does not enables persistence storage
## Attach a .c3p

this is not about projects.

## Steps to reproduce

1.Reload construct 3 (clean start no cookie, etc)
2.Construct 3 asks for persistence storage, accept it.
3.dialog goes away but chrome does not asks for permission. construct 3 about page says you have it but when something went wrong and construct 3 logs off automatically or cleaning data there is no local save.

## Affected browsers

* Chrome: yes

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r64
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 17 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: yes
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GT 330M OpenGL Engine
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 2047
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_disjoint_timer_query
EXT_frag_depth
EXT_shader_texture_lod
EXT_sRGB
EXT_texture_filter_anisotropic
WEBKIT_EXT_texture_filter_anisotropic
OES_element_index_uint
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_compressed_texture_s3tc
WEBKIT_WEBGL_compressed_texture_s3tc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBKIT_WEBGL_depth_texture
WEBGL_draw_buffers
WEBGL_lose_context
WEBKIT_WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
We can't follow bug reports that say things like "when something went wrong". We need specific steps to be able to follow them and help you.

**Comment by newman321** [comment]
@AshleyScirra i dont know what happens and why but i know that in result i lost my access to latest changes i made on my project .

also not asking for persistence storage by google is clear problem.

**Comment by shortercode** [comment]
Chrome doesn't ask for permission from the user for persistent storage, it decides if it should be allowed based on user interaction and site settings. Unless persistent storage is granted we display a warning every time you open the browser save dialog. Even so you should basically consider browser saves temporary storage at the moment.

A site is allowed persistent storage if any of the following is true:

- The site is bookmarked (and the user has 5 or less bookmarks)
- The site has high site engagement
- The site has been added to home screen
- The site has push notifications enabled

Persistent storage is still under development, and it has limited effects at the moment. Using clear cache will still delete site data. The only guarantee it offers so far is that if chrome needs to clear up some space (  because of low disk space for example ) it won't clear persistent sites. I believe the intent is to extend this to user triggered deletions, but given how confusing this area already is for the average user they haven't come to a decision on how to implement it.
