### ISSUE TITLE
Construct shows wrong file structure from Dropbox

### ISSUE THREAD

**Issue by gpibernats** [Scirra/Construct-3-bugs#958]
## Problem description

I have the following file **structure in Dropbox**:
```
CONSTRUCT
|_ FOLDER1Level1
    |_ FOLDER2Level2
    |    |_ FOLDER3Level3
    |    |    |_ Project3.c3p
    |    |_ Project2.c3p
    |_ Project1.c3p
```
But that's the **structure** shown in **Construct3**:
```
CONSTRUCT
|_ FOLDER1Level1
|    |_ FOLDER2Level2
|    |_ Project1.c3p
|_ FOLDER3Level3
|_ Project2.c3p
|_ Project3.c3p
```

## Attach a .c3p

-

## Steps to reproduce

1. Create the file structure in Dropbox.
2. Look at the file structure in Construct.

## Observed result

Wrong file structure.

## Expected result

Same file structure than in Dropbox.

## Affected browsers

* Chrome: yes
* Firefox: ?
* Edge: ?
* Safari: ?

## System details

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_6
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r64
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 317 mb (1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Intel Inc.
Renderer: Intel Iris OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by shortercode** [comment]
Okay so this seems to be a weird inconsistency in the Dropbox website, thought you might be interested in the why so here goes:

The Dropbox API treats letter case as optional ( names are stored with case, but it's generally ignored ) and the website seems to alter the case in some situation related to placing entries in folders. If you create the structure in C3 it works fine, but when I created the structure on the Dropbox website I got:
```
/FOLDER1Level1
/Folder1level1/FOLDER2Level2
/Folder1level1/FOLDER2Level2/FOLDER3Level3
/Folder1level1/Project1.c3p
/Folder1level1/FOLDER2Level2/Project2.c3p
/Folder1level1/FOLDER2Level2/FOLDER3Level3/Project3.c3p
```

Which renders on C3 as:

```
CONSTRUCT
|_ FOLDER1Level1
|_ FOLDER1Level2
    |_ FOLDER3Level3
        |_ Project3.c3p
    |_ Project2.c3p
|_ Project1.c3p
```

We actually ended up resolving 4 folders instead of 3 from the entry list because of the different names. When generating the directory tree we treat both `/` and `/Folder1level1` as root folders as neither of them actually have an entry, they only exist as parents of other entries. So when we try to display the contents of the root folder we show the contents of both folders.

Your view seems different, but I expect it's the same issue but with the different entries.
