### ISSUE TITLE
Error: object instance does not have associated behavior instance

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-3-bugs#962]
We are seeing a lot of reports of the error "object instance does not have associated behavior instance", but we have never been able to reproduce it ourselves. It looks like it happens when deleting something. It's currently one of our top crashers so we are keen to fix it, but currently we have no way to do that. Hopefully filing a bug with the error message will encourage someone to come along and report a reliable way to reproduce the problem.

Some bugs that mention the problem: #853, #876

**Comment by tunepunk** [comment]
I managed to reproduce this issue because I noticed something similar before. This seems to be something about the clipboard. If you add a behaviour to a sprite, copy the sprite, then delete the behaviour and then paste I could get a crash. Or if it was reverse, but at least I suspected the clipboard not updating after adding or removing behaviours.

Steps to reproduce:

1. Add a sprite, and give it solid behaviour.
2. Copy the sprite.
3. Remove the solid behaviour from the sprite.
4. Paste several of the sprites in clipboard.
5. Try to delete one of the sprites, or remove the sprite from the project window.

Would give me this.

Error report information
Type: unhandled rejection
Reason: Error: object instance does not have associated behavior instance @ Error: object instance does not have associated behavior instance at window.ǃDx.ǃzU (https://editor.construct.net/r65-2/main.js:63:136860) at d.ǃDkN (https://editor.construct.net/r65-2/main.js:63:207885) at n.ǃDkN (https://editor.construct.net/r65-2/main.js:63:161119) at n.ǃxs (https://editor.construct.net/r65-2/main.js:63:71407) at n.ǃxs (https://editor.construct.net/r65-2/main.js:63:152205) at s.then (https://editor.construct.net/r65-2/components/bars/projectBar/projectBar.js:1:10002) at 
Stack: Error: object instance does not have associated behavior instance at window.ǃDx.ǃzU (https://editor.construct.net/r65-2/main.js:63:136860) at d.ǃDkN (https://editor.construct.net/r65-2/main.js:63:207885) at n.ǃDkN (https://editor.construct.net/r65-2/main.js:63:161119) at n.ǃxs (https://editor.construct.net/r65-2/main.js:63:71407) at n.ǃxs (https://editor.construct.net/r65-2/main.js:63:152205) at s.then (https://editor.construct.net/r65-2/components/bars/projectBar/projectBar.js:1:10002) at 
Construct 3 version: r65.2
URL: https://editor.construct.net/
Date: Mon Nov 06 2017 14:41:27 GMT+0100 (CET)
Uptime: 2611.4 s

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.12_5
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r65.2
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: NVIDIA Corporation
Renderer: NVIDIA GeForce GTX 775M OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2047
Extensions: EXT_color_buffer_float, EXT_disjoint_timer_query_webgl2, EXT_texture_filter_anisotropic, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context

**Comment by tunepunk** [comment]
Steps to reproduce works every time. I just tried it in r66 as well.

**Comment by AshleyScirra** [comment]
Ah, thanks for finding reproduction steps! Shame it just missed r66 but I've fixed that particular case for r67. I'll leave this open until that's released to verify.

**Comment by tunepunk** [comment]
I tried to find some alternative reproduction steps as well. This can also happen if do like this:

Reproduction steps:

1. Create a sprite with Solid Behaviour.
2. Clone the sprite from project window.
3. Right click the new clone and choose > edit behaviours.
4. Remove the behaviour from the list.
5. Drag and drop the clone to layout
6. Delete the clone from layout.

Causes same crash.

**Comment by AshleyScirra** [comment]
@tunepunk - those steps seem to work OK with the same fix I've applied. I'd guess it's the same underlying cause, which is a good sign this will be fully fixed in r67. Still, let's wait for that release and see.

**Comment by AshleyScirra** [comment]
Did a r66.2 patch release with this fix which is out now. Can you confirm all cases you've found of this are fixed now?

**Comment by tunepunk** [comment]
This seems to be fixed now. Tried several ways to replicate this issue, but not getting any errors.

**Comment by AshleyScirra** [comment]
Great, thanks for confirming.
