### ISSUE TITLE
Browser action broken when exported to apk and run on android device

### ISSUE THREAD

**Issue by mageekm** [Scirra/Construct-3-bugs#967]
[test.zip](https://github.com/Scirra/Construct-3-bugs/files/1411804/test.zip)

Browser action broken when exported to apk and run on android device

I am using the Browser action (Open URL in a new window) in my app. Works fine in Construct3 preview mode both on my desktop and on my android phone. When I export to Cordova and create an apk, the Browser call is ignored once running on an Android device. I have created a simple test program that does nothing but make the call. Tried this with Construct 2 and 3. Works perfectly in preview mode in both versions. I have been trying various combinations of exporting to Cordova and then to the Intel XDK then using Construct 3 build to create a debug apk. Since Intel has depreciated their XDK features such as white listing are not supported in Intel App preview. You have to test it on an actual device. I have tried no less than 50 combinations that vary from using a debug apk to publishing an alpha version on play store with and without involving the Intel XDK.

I have tried backtracking to kitkat with C2 and then importing into the C3 builder but I can't see where to edit the white listing tags. I have tried all available versions of Cordova with Crosswalk and without. 

These calls used to work on older older versions. I suspect that newer security measures either in Cordova, Android or the browsers themselves are killing the action. I do have two year old apps on my phone that use this call just fine. What changed?

I have tried using the wildcards "*" in the XDK build specs but they seem to have no effect. I have tested access, intent, and navigation. 

Here is a simple action.
-> Browser: Go to "http://maps.google.com" in a new window ("Google Maps")
I have attached some simple code for test

I have tried editing the config.xml file that is built by C3 build process, but it is uneditable by all my editors that typically work.  Seems to contain special characters.  

I would like to avoid having to buy a phonegap subscription with no assurance this work and why should I have to pay just for the privilege of creating an android apk?

I have spent a week testing various combos but have hit a wall.

**Comment by shortercode** [comment]
We don't have any explicit URI whitelist settings at the moment for the build service, although it's probably a good idea to introduce it for security. I'm not if there's any implicit settings, but it wouldn't surprise me if cordova used a default value. I'll look into adding the access properties for r65 but it's not due to be published for at least a week.

I doubt switching to phonegap subscription will make any difference, the config.xml file just needs editing to include <access origin="https://maps.google.com" /> before being built. It's a normal xml file, so it should open fine with the likes of TextWrangler, SubLime, Atom, VS Code, Notepad++, etc. Even if it did contain special characters most text editors just show them as a unrenderable glyph so you can just ignore them. When you say uneditable what do you mean?

Have you tried just using the cordova CLI to perform your build? Unless your fully against using the command line the cordova CLI is generally the easiest way to do a custom build. It's a fairly clear/verbose tool so it's not hard to use and get's you all the features of phonegap without having to pay.

**Comment by shortercode** [comment]
@mageekm Also can you try to stick to the bug template, it makes it easier for us to find the information we need in the report.

**Comment by mageekm** [comment]
Sorry about not following your template.  I thought I was.  Next time, I will leave all the text and type around it.
I just used C3 to build a Cordova Xcode version and it works fine in the Xcode simulator.  Nice job, but I am getting a lot of warnings after "Build"..  

Back on the windows machine to prepare all of the screens and icons.  What a pain.  That was one nice thing about the XDK.  oh well.    

I get that cordova CLI is the way to go now.  What a pain.

The whole concept of working in a higher level language like Construct is moot once you are forced to terminal line programming to do the job.

**Comment by hansonbrody** [comment]
I am having a similar issue: my project is exported to HTML5 and the "Open in new window" action is not working when using iOS browser, but does work on my desktop.

**Comment by shortercode** [comment]
It's okay, you gave pretty much everything we needed. Just took me a little while longer than normal to understand the problem was all.

The warnings are generally related to projects settings, I'm intending to try and get rid of as many as possible at some point but they have little effect at the end of the day, so it's quite low down the priority list. Incidentally most of them can be fixed by applying the xcode recommendations.

We give the option of using the cordova CLI as an option for high level users, but ideally no one should really need to use it. Once we've fixed the issue with the whitelist hopefully you will be able to just use C3 and xcode.

**Comment by mageekm** [comment]
My apology for asking a stupid question but have you updated your code from the depreciated "window.open" call?  https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-inappbrowser/ 
if I read it right we should be using.  cordova.InAppBrowser.open() function  with the latest cordova plugin.  I don't think the whitelist is the issue.
makes sense to me that the iOS is a different approach.
Just wondering.

**Comment by mageekm** [comment]
[config.zip](https://github.com/Scirra/Construct-3-bugs/files/1429600/config.zip)

Take a look at the config.xml file I have attached.  Tell me what editor you can edit with.
it is out of your android-release-unsigned.apk

**Comment by shortercode** [comment]
We actually use `navigator.openURL` when it's been added by cordova. It will open the location with the system default program ( which will normally be chrome ). `window.open` actually works fine with the default settings. I debugged this in android studio yesterday and found there's actually 3 whitelists for networking, one of which basically only effects this method.

Check out the full whitelist documentation [here](https://github.com/apache/cordova-plugin-whitelist), it's the section for `allow-intent` you want to look at in particular.

I had a look at that file and your right that it's gibberish, the XML files inside an APK have some weird encoding that make them basically unreadable, you can transform them with a special tool. But this is the wrong config.xml file, and your editing at the wrong step in the process.

You need to make the changes before the project is compiled into an APK. When exporting select "cordova project" at the build stage and download the zip file it gives you, that has a file in the root folder called config.xml that is the one your looking for. Make your edits using a code aware text editor then run `cordova prepare` to setup the project, then `cordova build --release android` to generate an unsigned release APK. If you haven't set up android studio before then that will need to be done first. Checkout this tutorial [here ](https://www.construct.net/gb/tutorials/building-mobile-apps-locally-with-cordova-cli-21) for details.

**Comment by mageekm** [comment]
The process I thought would work but didn't, was to have Construct build a cordova project  Then edit the config.xml file, then import to Construct's build manager, then have it build an unsigned apk.  Shouldn't this work?

**Comment by shortercode** [comment]
Well it was never really intended to work like that, but in theory it should work. The issue your facing here is that the build server actually uses the config.json file, not the config.xml.

**Comment by shortercode** [comment]
In r65 we've added a new option in the build options dialog, you can now specify a URL whitelist specifically for this action. The default setting of `http://*/* https://*/*` will cover all standard websites. This should solve your original problem without having to resort to customising a build. Closing this issue as fixed.
