### ISSUE TITLE
iOS Export to Cordova and XCode White Flash Issue

### ISSUE THREAD

**Issue by burnjaco** [Scirra/Construct-3-bugs#971]
I ve completed my game and published to the android store, but when i exported the game into Xcode project , run build and then tried the game, i get black and white flash on my device (iPhone 6 plus with iOS 11). I  tried the cocoon build service also but no luck, Same problem occured.  Xcode debug error code as follows; 
017-10-26 00:09:09.205287+0300 Disko[13416:4133583] 0
2017-10-26 00:09:10.262812+0300 Disko[13416:4133860] [ProcessSuspension]  0x1c067b880 - ProcessAssertion() Unable to acquire assertion for process with PID 0
2017-10-26 00:09:11.015789+0300 Disko[13416:4133583] support@scirra.com

and on one try i got the error below also;

com.apple.WebKit.WebContent: 113: Could not find specified service...

There isn't any useful info on web and i can't find a solution, any suggestions???

**Comment by shortercode** [comment]
We need a more information than that to actually diagnose a bug, please refer to the [guidelines](https://github.com/Scirra/Construct-3-bugs) and update your issue.

**Comment by burnjaco** [comment]
[Disko.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/1427491/Disko.c3p.zip)

I ve attached the sample project.

**Comment by shortercode** [comment]
Okay! I've spent a chunk of time on this, but finally found out what was up. The WebView is actually crashing and restarting itself repeatedly which is whats causing the flashing. The issue is with either one or both of these 2 sound files "sound_lock.m4a", "sound_start.m4a". When safari's audio decoder tried to process them it crashed the webview, so you've successfully found a safari bug! I can't really tell you what's wrong with the files, but if you replace them with one of the other files then it works fine.

Also as a note: your using the depreciated AdMob plugin, there's actually a bug in the native part for this plugin that prevents it from being installed correctly. We've just published our new advertising plugin in r65 which you should be able to use instead.

Hope this helps!
