### ISSUE TITLE
Physics Behavior: Weird Interaction+Jerking around when Objects overlap that are connected to another object with revolute joint but collisions with each other disabled

### ISSUE THREAD

**Issue by Leralasss** [Scirra/Construct-3-bugs#986]
## Problem description

we have 2 objects: (both with physics behavior enabled)
object 1 (in .c3p = Sprite2)
object 2 (in .c3p = Sprite)

now have object 1 in the middle, surrounded by eight object2 overlapping each other.
at the start of the layout you connect each object 2 to the object 1 with limited revolute joint.

if you leave it at that, nothing special happens.

if you now disable collisions (at the start of layout) of object 2 with object 2 (action: enable/disable collisions), the objects will start to jerk around object 1
[TEST_Physics_SelfCollisionAndLimitedRevoluteJoint - Copy.zip](https://github.com/Scirra/Construct-3-bugs/files/1439488/TEST_Physics_SelfCollisionAndLimitedRevoluteJoint.-.Copy.zip)
(i downloaded .c3p and changed extension to .zip i hope it works.)

if you disable the event where it disables collisions with itself you will see

## Attach a .c3p

*A minimal Construct 3 project (.c3p) is required to be attached. Please see the guidelines*

## Steps to reproduce
follow steps in Problem Description

## Observed result

*What do you see happen?*
weird jerking around

## Expected result

*What did you expect to happen instead?*
no weird jerking around

## Affected browsers

* Chrome: yes/no

## System details

there is no crash report as there is no crash

*If you see a crash report dialog, please copy and paste it to where it says "PASTE HERE" below. Otherwise please go to **Menu** -> **About** -> **Platform information** and paste that information there instead.*

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This appears to be happening entirely in the physics engine, which we didn't develop, so I don't think there's anything we can do to fix it I'm afraid. I think the physics engine has some provision for automatically disabling collisions between jointed objects, so I guess explicitly disabling collisions somehow conflicts with that.

I'm not sure why it's a problem anyway - it seems to work fine if you don't disable collisions, presumably because the physics engine is smart enough to recognise the objects are jointed together.
